### ISSUE TITLE
#yourfirstpr - Update our template and remove thousands of warnings from our build logs.

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/ReactiveUI#1005]
Instead of fixing this issue immediately, we are leaving this [issue open and up for grabs](http://up-for-grabs.net) for someone [who has never contributed to open source before](http://www.firsttimersonly.com/). We will not accept solutions to this issue from non-first-timers to this project or open-source, [we will check](http://firstpr.me/).

# Problem

We lack XML documentation on our ReactiveUI-Events package which results in an excessive amount of warnings when building ReactiveUI on our continuous integration environment.

It really doesn't make sense to go back and add the missing XML documentation as these projects are automatically generated by a [moustache template](https://github.com/reactiveui/ReactiveUI/blob/master/ReactiveUI.Events/Events.mustache) and a [console application](https://github.com/reactiveui/ReactiveUI/blob/master/ReactiveUI.Events/EventBuilder.cs).

Additionally it does not make sense to add dummy XML documentation so the approach we are proposing is update the template that generates the projects to [supress the compiler warning](https://msdn.microsoft.com/en-us/library/edzzzth4%28v=vs.90%29.aspx?f=255&MSPPError=-2147217396).

# Suggested Resolution

On https://github.com/reactiveui/ReactiveUI/blob/master/ReactiveUI.Events/Events.mustache#L14

At the top of the file you will find the following section

	{{#Namespaces}}
	namespace {{Name}}

Change it to be

	#pragma warning disable 1591
	{{#Namespaces}}
	namespace {{Name}}

At the bottom of the file you will find the following section

	{{/Types}}
	}
	{{/DelegateNamespaces}}

Change it to be

	{{/Types}}
	}
	#pragma warning restore 1591
	{{/DelegateNamespaces}}

Submit your first pull-request and when it gets merged, we will send a tweet to  [@yourfirstpr](https://twitter.com/yourfirstpr) in celebration :)

# What you'll be fixing

In our build logs #1006 we have thousands of these annoying and erroneous warning messages:
	
	Events.cs(2506,16): warning CS1591: Missing XML comment for publicly visible type or member 'TimelineEvents.TimelineEvents(Timeline)' [C:\projects\reactiveui\ReactiveUI.Events\ReactiveUI.Events_Net45.csproj]
	Events.cs(2512,46): warning CS1591: Missing XML comment for publicly visible type or member 'TimelineEvents.CurrentStateInvalidated' [C:\projects\reactiveui\ReactiveUI.Events\ReactiveUI.Events_Net45.csproj]
	Events.cs(2516,46): warning CS1591: Missing XML comment for publicly visible type or member 'TimelineEvents.CurrentTimeInvalidated' [C:\projects\reactiveui\ReactiveUI.Events\ReactiveUI.Events_Net45.csproj]
	Events.cs(2520,46): warning CS1591: Missing XML comment for publicly visible type or member 'TimelineEvents.CurrentGlobalSpeedInvalidated' [C:\projects\reactiveui\ReactiveUI.Events\ReactiveUI.Events_Net45.csproj]
	Events.cs(2524,46): warning CS1591: Missing XML comment for publicly visible type or member 'TimelineEvents.Completed' [C:\projects\reactiveui\ReactiveUI.Events\ReactiveUI.Events_Net45.csproj]
	Events.cs(2528,46): warning CS1591: Missing XML comment for publicly visible type or member 'TimelineEvents.RemoveRequested' [C:\projects\reactiveui\ReactiveUI.Events\ReactiveUI.Events_Net45.csproj]
	Events.cs(2536,25): warning CS1591: Missing XML comment for publicly visible type or member 'EventsMixin' [C:\projects\reactiveui\ReactiveUI.Events\ReactiveUI.Events_Net45.csproj]
	Events.cs(2538,43): warning CS1591: Missing XML comment for publicly visible type or member 'EventsMixin.Events(BitmapDecoder)' [C:\projects\reactiveui\ReactiveUI.Events\ReactiveUI.Events_Net45.csproj]
	Events.cs(2542,42): warning CS1591: Missing XML comment for publicly visible type or member 'EventsMixin.Events(BitmapSource)' [C:\projects\reactiveui\ReactiveUI.Events\ReactiveUI.Events_Net45.csproj]
	Events.cs(2548,18): warning CS1591: Missing XML comment for publicly visible type or member 'BitmapDecoderEvents' [C:\projects\reactiveui\ReactiveUI.Events\ReactiveUI.Events_Net45.csproj]
	Events.cs(2552,16): warning CS1591: Missing XML comment for publicly visible type or member 'BitmapDecoderEvents.BitmapDecoderEvents(BitmapDecoder)'

**Comment by Charlotteis** [comment]
Thanks for this great issue! Putting it up on the @yourfirstpr account tomorrow at 1pm (GMT). :sparkles:

**Comment by ghuntley** [comment]
@Charlotteis this PR has been resolved by @Avrozavr! 

See https://github.com/reactiveui/ReactiveUI/pull/1010

This has been a pleasure, look forward to working with you again in the future.

**Comment by Charlotteis** [comment]
Nicely done :)
