### ISSUE TITLE
CreateCollection should take scheduler as parameter

### ISSUE THREAD

**Issue by kentcb** [reactiveui/ReactiveUI#1009]
The `CreateCollection` method uses `RxApp.MainThreadScheduler` in its implementation, but does not allow callers to override this. This makes it impossible to control scheduling unless one assigns their scheduler to `RxApp.MainThreadScheduler` first. Whilst `With` does this, not everyone uses `With`.

`CreateCollection` should include an optional `scheduler` parameter. If `null`, it can use `MainThreadScheduler`. Otherwise, it should use the provided scheduler.

**Comment by gluck** [comment]
:+1: it also prevent its use in contexts where the `MainThreadScheduler` can't be relied upon (multiple dispatchers in WPF, multiple message loops in winforms, and I believe UWP also has multiple UI threads)
