### ISSUE TITLE
Let's not package the Windows metadata files in the repository (for building RxUI.Events)

### ISSUE THREAD

**Issue by moswald** [reactiveui/ReactiveUI#1011]
The build machine should have the metadata files installed, meaning these binaries are just bloating the repo. Also, UWP appears to be changing quickly, and we don't want to keep checking it in.

**Comment by paulcbetts** [comment]
Not checking these in will cause builds that are different from machine to machine, it's already caused problems in the past

**Comment by onovotny** [comment]
How is it different? It should always have the latest Windows SDK on the build server?

**Comment by paulcbetts** [comment]
@onovotny It means that different people making local builds get different results

**Comment by onovotny** [comment]
Do we really care for local builds if people have the wrong version? Second, if we have the SDK version in the csproj file, VS should take care of that. Like if we say the Version is 10158, VS should complain about opening the project if the user doesn't have that.

I get what you're saying but I think this better belongs to the documentation/getting started/setting up your local build environment area. We can and should specify what versions of SDK's people need to have installed, but we shouldn't have to check them in. 

At the end, the build server is the One True Master (tm)

**Comment by paulcbetts** [comment]
> Do we really care for local builds if people have the wrong version? 

I mean, do we really care about disk space?

**Comment by onovotny** [comment]
Guess not....just that it forever increases the clone size :/

**Comment by moswald** [comment]
I worry about clone size, and RxUI being out of date. It's a lot easier to drop a new SDK onto a build machine than it is to add binaries to the repo.

**Comment by ghuntley** [comment]
Let's get rid of them once #1006 closes?

**Comment by moswald** [comment]
That's fine with me, it's kind of a CI thing, anyway.

**Comment by paulcbetts** [comment]
> Recursively destroy by filter branch if need be to reduce repo size if the space savings merit it?

We *cannot* filter-branch this repo, that will be a 100% disaster, every branch and fork will be permafucked.

**Comment by moswald** [comment]
Oh sorry, that part didn't register. Yeah, rewriting history would be bad. What's done is done, I just wanted to know if we could do it differently moving forward.

**Comment by moswald** [comment]
@ghuntley, is this taken care of at this point?

**Comment by ghuntley** [comment]
@moswald all taken care of. EventBuilder now uses the metadata on the CI host.
