### ISSUE TITLE
DefaultViewLocator doesn't resolve IViewFor<IFooBarViewModel>

### ISSUE THREAD

**Issue by olevett** [reactiveui/ReactiveUI#1014]
According to the comments in DefaultViewLocator, it looks for IViewFor<IFooBarViewModel> for a ViewModel of type FooBarViewModel. This doesn't appear to be the case, so the test below fails

```C#
[Fact]
public void ResolveByInterfaceType()
{
    var resolver = new ModernDependencyResolver();

    resolver.InitializeSplat();
    resolver.InitializeReactiveUI();
    resolver.Register(() => new FooBarView(), typeof(IViewFor<IFooBarViewModel>));

    using (resolver.WithResolver()) {
        var fixture = new DefaultViewLocator();
        var vm = new FooBarViewModel(null);

        var result = fixture.ResolveView(vm);
        this.Log().Info(result.GetType().FullName);
        Assert.IsType<FooBarView>(result);
    }
}

namespace Foobar.ViewModels
{
    public interface IFooBarViewModel : IRoutableViewModel {}

    public class FooBarViewModel : ReactiveObject, IFooBarViewModel 
    {
        public string UrlPathSegment { get { return "foo"; } }
        public IScreen HostScreen { get; private set; }

        public FooBarViewModel(IScreen hostScreen)
        {
            HostScreen = hostScreen;
        }
    }
}

namespace Foobar.Views
{
    using ViewModels;

    public class FooBarView : IViewFor<IFooBarViewModel> 
    {
        object IViewFor.ViewModel { get { return ViewModel; } set { ViewModel = (IFooBarViewModel) value; } }
        public IFooBarViewModel ViewModel { get; set; }
    }
}

```
I've had a crack at fixing it, but the only way I can see is to attempt to resolve an IViewFor for every interface the ViewModel implements and that seems a little ugly (it might be reasonable to restrict that to interfaces that implement IRoutableViewModel which is a little better though?).

**Comment by moswald** [comment]
I'm confused as to what you're trying to do differently than this test. https://github.com/reactiveui/ReactiveUI/blob/master/ReactiveUI.Tests/RxRouting.cs#L66-L82

That one passes, why doesn't yours?

**Comment by olevett** [comment]
That test is resolving a view model by building a name for BazViewModel, it puts an I on the front, and replaces ViewModel with View, rather than doing anything more intelligent with the view types/implemented interfaces

There are three cases listed in the ViewLocator (https://github.com/reactiveui/ReactiveUI/blob/master/ReactiveUI/ViewLocator.cs#L49-L51)
* IFooBarView that implements IViewFor - what the above test cases covers, and what https://github.com/reactiveui/ReactiveUI/blob/master/ReactiveUI/ViewLocator.cs#L60-L63 does
* IViewFor<IFooBarViewModel> - what this issue is about, that doesn't seem to be handled anywhere
* IViewFor<FooBarViewModel> (the original behavior in RxUI 3.1) - this is handled by https://github.com/reactiveui/ReactiveUI/blob/master/ReactiveUI/ViewLocator.cs#L65-L67 but doesn't have any test coverage

**Comment by olevett** [comment]
I've expanded the example a little to make it clearer, but the particular case that isn't working for me is that
- I have a ViewModel that implements an IViewModel
- I have a view that implements IViewFor<IViewModel>
- The view is registered with Splat/the service locator
- The view isn't resolved for an instance of the ViewModel

**Comment by ghuntley** [comment]
Thanks for the high quality bug report @olevett!

We have been talking in slack about it, specifically the fact you submitted a failing test as part of the initial bug report and that you proceeded to resolve the issue via a PR.

You should come and join us in Slack, see the README.md for details - for now I've sent you an invitation to join the ReactiveUI community which when accepted will provide the ability to display the ReactiveUI badge on your github profile.

**Comment by ChrisPulman** [comment]
# RxUI 7 Navigation Bug
I Have attached a repo of this BUG, the `DefaultViewLocator` fails to resolve an `IViewFor<INTERFACE>`
Included in the repo is a potential fix or another way to try and resolve the view I have named it `SplatViewLocator`.
I have also included an extension method that might be useful when using Routing I have Extended from IScreen however it may be more flexable to extend from the `RoutingState` therefore allowing multiple routers within an `IScreen`.
Open the solution and run to see the exception
Open the `AppBootstrapper` and change `UseDefaultViewLocator` to false to run with the fix.

[DefaultViewLocatorTest.zip](https://github.com/reactiveui/ReactiveUI/files/505098/DefaultViewLocatorTest.zip)

**Comment by olevett** [comment]
I think the fix I had is on master but not the RxUI7 branch, not sure exactly why that is however...

**Comment by trucksmart** [comment]
Do we have any info on when this will be released?
