### ISSUE TITLE
Shall we switch to GitFlow after (or before) v7 release?

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/ReactiveUI#1019]
Right now people are opening PR's against `master` instead of `rxui7-master` which makes their first experience with contributing not the smoothest. @kentcb is working on the v7 release and it is also causing him a bunch of pain, not to mention wasted effort on his and the communities part.

* `master` is where stable nuget packages are produced from.
* `develop` is where -pre nuget packages are produced from when CI is up and running.
* maintainers/contributors submit PR's to the `develop` branch.

When a release is in the oven, you branch a release branch, make any necessary tweaks based on testing, then merge that to master (with a tag for that release).

https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow/

Also related to #1006 but we can start doing this practice before CI comes in.

**Comment by paulcbetts** [comment]
I've switched the default branch to rxui7-master, we don't need git flow (and imho, neither does anyone else)

**Comment by moswald** [comment]
I'm not a huge fan of git flow, personally. IMHO, It's one of those things that developers do because they like, neat, ordered processes, but it's not a good idea in practice.

**Comment by shiftkey** [comment]
:thumbsup: to changing the default branch

I'm neutral to the Git Flow proposal - beyond "long lived branches are the devil" I don't have any strong opinions on branching flows...
