### ISSUE TITLE
Make `develop` the default branch in Github if/when we switch to Gitflow

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/ReactiveUI#1020]
This is so that the default clone/PR workflow works better, because ultimately you want to contribute to to the `develop` branch - not `master`. It also prevents contributors from accidently sending PR's to the wrong branch which wastes their and time of the maintainers.

Master is always visible on GitHub and the intent is to implement sourcelink or gitlink as part of CI which be the way most people will interact with `master` in the future anyway.

Related #1006 and #1019

**Comment by paulcbetts** [comment]
Switched it to rxui7-master which should solve these problems
