### ISSUE TITLE
Need to figure out how to use the new v7 version of ViewModelViewHost with Xamarin.Mac

### ISSUE THREAD

**Issue by mteper** [reactiveui/ReactiveUI#1023]
In version 6.5, we would instantiate a ViewModelViewHost like this:

``` cs
private ViewModelViewHost _subViewHost;

public override void AwakeFromNib()
{
    base.AwakeFromNib();

    // here, CustomView is an IBOutlet tied to an NSView
    _subViewHost = new ViewModelViewHostLegacy(CustomView);
    _subViewHost.ViewModel = ViewModel.SubViewModel;
}
```

In v7 world, there is no longer a constructor that accepts an NSView, and presumably the code in `AwakeFromNib` has to be replaced with something similar to this:

``` cs
    _subViewHost = new ViewModelViewHost();
    _subViewHost.ViewModel = ViewModel.SubViewModel;
    CustomView.AddSubview(_subViewHost.View);
```

Unfortunately, this causes a crash:
[VMVH crash.txt](https://github.com/reactiveui/ReactiveUI/files/88216/VMVH.crash.txt)

**Comment by ChrisPulman** [comment]
Closing as outdated and Xamarin is no longer supported
