### ISSUE TITLE
NuGet package update / timeline?

### ISSUE THREAD

**Issue by rvlieshout** [reactiveui/ReactiveUI#1024]
Is there a timeline for updating the NuGet packages? There are 30+ commits since the 6.5.0 package and the current packages are 6+ months 'old'.

I'd rather not copy the github source into my project.

**Comment by paulcbetts** [comment]
Nope, there's not!

**Comment by ghuntley** [comment]
Hey @rvlieshout, we are going through the motions of getting ready for a release, at which point in the future the project will start producing `-pre` packages off `develop` via CI thus this pain-point will melt away. So much to do, so little time - your welcome to come join us over in Slack (see the README.md), we would love to have you. Especially if you could lend a hand :+1: 

FYI whilst not final, here's what's coming in v7. -> http://docs.reactiveui.net/en/release-notes/version-7-0-0.html
