### ISSUE TITLE
Nuget didn't reference the dll's for my portable project

### ISSUE THREAD

**Issue by NPadrutt** [reactiveui/ReactiveUI#1025]
Hi
I made a new Windows Universal Project to play aroud with reactiveUI. In the Windows Project it worked without issue. But the portable project didn't reference any dll's. I could set them manually and it worked.
The packages.config was updated properly. 
Profile 111

EDIT: I'm not sure if this is an error of the nuget package manager or the nuget package itself.
When I completly delete the package and readd everything it is working.

**Comment by ghuntley** [comment]
Hey @NPadrutt I've experienced the same thing.

https://github.com/reactiveui/ReactiveUI/issues/983#issuecomment-164584017

It has been fixed in the source but an updated package has not been released. Workaround is to install splat first, then reactiveui second.
