### ISSUE TITLE
RoutedViewHost should throw if requested ViewModel is not IRoutableViewModel

### ISSUE THREAD

**Issue by kentcb** [reactiveui/ReactiveUI#1027]
It seems that `RoutedViewHost` will happily consume any view model, even if it doesn't implement `IRoutableViewModel`. However, nothing really happens when one tries to navigate to such a VM. There might be a log message, but it should really be an exception.

**Comment by olevett** [comment]
Was trying to reproduce this, but I can't... On what platforms does this occur? On Xaml at least, there's an exception thrown if the view/viewmodel can't be located. Is being swallowed?

```csharp
throw new Exception(String.Format("Couldn't find view for '{0}'.", x.Item1));
```

The behaviour is different across the various platforms, so I might have missed something...

**Comment by moswald** [comment]
That only throws if there isn't a view for the viewmodel. The problem is that if the viewmodel isn't an `IRoutableViewModel`, then we navigate to nothing.

**Comment by kentcb** [comment]
I think this was inadvertently fixed by the move to the new `ReactiveCommand`. Now the command is strongly-typed, it is _only_ possible to navigate to `IRoutableViewModel` instances.
