### ISSUE TITLE
Mac missing generic ReactiveViewController

### ISSUE THREAD

**Issue by kentcb** [reactiveui/ReactiveUI#1029]
For some reason (possibly due to legacy Xamarin not supporting it), the Mac layer doesn't include a generic `ReactiveViewController<T>`. A quick experiment indicates that this will now work, so we should change the existing non-generic implementation to a generic one.

Base classes for all common controls should be updated.

**Comment by mteper** [comment]
@kentcb This is not possible in the "classic" Xam.Mac, but should be possible in Unified. I had been meaning to test, but looks like you beat me to it. Great news! I guess the question we need to resolve now is whether to continue to support classic or to cut off and go Unified from v7 onward. The latter choice would be OK with me. I don't know whether there are any MonoMac and classic Xam.Mac users of RxUI out there who might feel different.

**Comment by ghuntley** [comment]
FYI here's apples stance on classic vs unified

> Starting February 1st, 2015 Apple requires that all new iOS submissions to the App Store must be 64 bit applications built with the iOS 8 SDK; and from June 1st, 2015 app updates will also need to follow the same requirements. As a result, Xamarin.iOS applications will need to be migrated to the new Unified >API instead of the existing Classic MonoTouch API to support 64 bit.

Do you want me to send out a comms asking for community feedback? imho let's go Unified.

**Comment by mteper** [comment]
Don't think this applies to OS X submissions though. Or, my google-fu failed me.

**Comment by ghuntley** [comment]
https://developer.xamarin.com/guides/cross-platform/macios/unified/

**Comment by mteper** [comment]
So like I said, Unified is imposed on iOS but not on OS X. I am :+1: going Unified-only, FWIW.

**Comment by mteper** [comment]
@ghuntley, did you hear back from anyone about this?

**Comment by Qonstrukt** [comment]
This was added by #1216.
