### ISSUE TITLE
[RFC] UserInteraction - local handling API change

### ISSUE THREAD

**Issue by pmbanka** [reactiveui/ReactiveUI#1030]
## The problem
Let's analyze [`UserInteraction`](https://github.com/reactiveui/ReactiveUI/pull/964) from the UX point of view.

A user sees an updated Compelling Example, and uses it in his app:
```
Search
    .ThrownExceptions
    .Subscribe(ex => 
    {
       (new UserErrorInteraction<Unit>(ex)).RaiseGlobal();
    });
```
When he does that, he gets an`UnhandledUserInteractionException`. Based on the message (see the bottom of this post), he fixes the problem by registering global handler. Done.

Now, the user discovers the `Raise` method, and learns from the XML docs something about local user interaction. Cool! Globals are bad, aren't they?

So, he uses:
```
Search
    .ThrownExceptions
    .Subscribe(ex => 
    {
       (new UserErrorInteraction<Unit>(ex)).Raise();
    });
```
And... **nothing happens. No prompt, nothing. But also: no exceptions, everything compiles fine.** Quick check if there is a `RegisterLocalHandler`, but apparently not. WTF?

## More problems
Local interactions require a user to do a lot of non-obvious things.
```
public class LocalInteractionViewModel : ReactiveObject
{
	// !! Need to declare subject by hand, every time.
	// * What type of subject? Why not BehaviorSubject?
	// * What happens if I call OnError? OnCompleted? Should I do that? Why not?
    private readonly Subject<UserInteraction<bool>> confirmFileDeletion;

    public LocalInteractionViewModel()
    {
        this.confirmFileDeletion = new Subject<UserInteraction<bool>>();
    }

    public IObservable<UserInteraction<bool>> ConfirmFileDeletion => this.confirmFileDeletion;

    public async Task DeleteFileAsync()
    {
        var confirmFileDeletion = new UserInteraction<bool>();
        // !! I hope I do not forget to add this line this time...
        // !! Global UserInteraction does not require this awkward step. Maybe I should stick to it...
        this.confirmFileDeletion.OnNext(confirmFileDeletion);
        var result = await confirmFileDeletion.Raise();
    }
}
```

## The proposed solution
**We want `Raise` to throw when a user does something wrong.** I think we can modify the feature to achieve that goal.

Let's create a type:
```
public class UserInteractionSource
{
    protected UserInteractionSource() {}

	protected readonly Subject<object> subject = new Subject<object>();

	internal void Post(UserInteraction interaction)
	{
		if (!subject.HasObservers)
		{
			throw new UnhandledLocalUserInteractionException();
		}
		subject.OnNext(interaction);
	}
}

public class UserInteractionSource<T>
    : UserInteractionSource, IObservable<UserInteraction<T>>
{
	public UserInteractionSource() { }

    public IDisposable Subscribe(IObserver<T> observer)
    {
        return base.subject.Cast<T>().Subscribe(observer);
    }
}
```

How do we make the user discover this class? By requiring him to pass in explicitly to `Raise` method. Let`s see the implementation:

```
public class UserInteraction : ReactiveObject
{
	protected IObservable<object> Raise(UserInteractionSource source)
    {
	    source.Post(this);
        return this.result;
    }
}

public class UserInteraction<T> : UserInteraction 
{
	public new IObservable<TResult> Raise(UserInteractionSource<T> source)
    {
        return base.Raise(source).Cast<TResult>();
    }
}
```

ViewModel code:
```
public class MyVM
{

	public UserInteractionSource<bool> AskToDelete { get; } = new UserInteractionSource<bool>();

	public async Task DeleteFileAsync()
    {
        var confirmFileDeletion = new UserInteraction<bool>();
        var result = await confirmFileDeletion.Raise(AskToDelete);
        if (result)
        {
            // delete the file
        }
    }
}
```
View code does not change.

## Proposed renames
I think that renaming `Raise` to `RaiseTo` or `RaiseOn`, or even `RaiseLocalOn` might make everything easier to understand.

I know that `UserInteractionSource` is not a good name, but I don't have a better idea now.

## Problems with proposed solution
This proposal does not fix an issue of having different API in local `UserInteraction`s and global ones.

## Side note - exceptions messages
We can differentiate `UnhandledLocalUserInteractionException` from `UnhandledGlobalUserInteractionException`. I also think the messages for these exceptions should propose what to do:

`You have to subscribe to UserInteractionSource in your view.`

`You have to register global UserInteraction handler. See UserInteraction.RegisterGlobalHandler`

**Comment by mteper** [comment]
RE: naming, how do this sound?
`UserInteractionSource` => `UserInteractionObservable`
`RaiseOn` => `RaiseWith`

**Comment by kentcb** [comment]
FWIW, @pmbanka and I were discussing this in Slack beforehand and I agree that it would be much nicer if the user had a more consistent experience, regardless of whether they're doing local or global interactions. My reservation with the proposed solution is that the approach is still not consistent (one requires a source, one does not). I think we need to converge the two scenarios even further, and I've had a little bit of time to think about this, so...

```C#
public class LocalInteractionViewModel : ReactiveObject
{
    private readonly UserInteractionSource<UserInteraction<bool>> confirmFileDeletionSource;

    public LocalInteractionViewModel()
    {
        this.confirmFileDeletionSource = new UserInteractionSource<UserInteraction<bool>>();
    }

    public UserInteractionSource<UserInteraction<bool>> ConfirmFileDeletionSource => this.confirmFileDeletionSource;

    public async Task DeleteFileAsync()
    {
        // create the interaction instance
        var confirmFileDeletion = new UserInteraction<bool>();

        // raise it and await the result
        var result = await confirmFileDeletion.Raise(this.confirmFileDeletionSource);

        if (result)
        {
            // delete the file
        }
    }
}

public class LocalInteractionView
{
    public SomeView()
    {
        this
            .ViewModel
            .ConfirmFileDeletionSource
            .RegisterHandler(
                async interaction =>
                {
                    var deleteIt = await this.DisplayAlert(
                        "Confirm Delete",
                        "Are you sure you want to delete this super important file?",
                        "YES",
                        "NO");

                    interaction.SetResult(deleteIt);
                });

    }
}

public class GlobalInteractionViewModel : ReactiveObject
{
    public async Task DeleteFileAsync()
    {
        // create the interaction instance
        var confirmFileDeletion = new UserInteraction<bool>();

        // raise it globally and await the result
        var result = await confirmFileDeletion.Raise(UserInteractionSource.Global);

        if (result)
        {
            // delete the file
        }
    }
}

public class GlobalInteractionView
{
    public SomeView()
    {
        UserInteractionSource
            .Global
            .RegisterHandler<UserInteraction<bool>>(
                async interaction =>
                {
                    var deleteIt = await this.DisplayAlert(
                        "Confirm Delete",
                        "Are you sure you want to delete this super important file?",
                        "YES",
                        "NO");

                    interaction.SetResult(deleteIt);
                });
    }
}
```

The idea here is that all interactions - global or local - occur through a source. `UserInteractionSource.Global` is just a static instance of a source. This _should_ be doable (hard to say until I actually try), and I think it results in a much more consistent experience.

Thoughts?

As for naming, it's a source from the perspective of the consumer (view), but a sink from the perspective of the producer (VM). Maybe we should call it something that reflects the duality of its roles - `UserInteractionSubject`?

**Comment by mteper** [comment]
@kentcb I like the proposal, consistency is good!

In terms on naming, the visible part of the duality is the source (which is why I was earlier proposing the name `UserInteractionObservable`) while the sink aspect is hidden in the implementation (so why confuse the consumer with extra info?). If we won't implement it as an `IObservable`, perhaps calling it `UserInteractionSource` is better after all. However, is there a reason not to?

**Comment by kentcb** [comment]
@mteper: I take your point about visibility. I was thinking about things from the VM's perspective, but you're right that the VM doesn't currently sink the interaction into the source. Rather, it passes the source to the interaction.

Now that I look at that again, it seems to me it might be nicer to change it thusly:

```cs
var confirmFileDeletion = new UserInteraction<bool>();

var result = await this.confirmFileDeletionSource.Raise(confirmFileDeletion);
```

That way we _can_ follow standard reactive nomenclature:

```cs
var confirmFileDeletion = new UserInteraction<bool>();

var result = await this.confirmFileDeletionSubject.OnNext(confirmFileDeletion);
```

A `UserInteractionSubject` is therefore nothing more than a specialized subject that orders observers and only invokes them if a previous observer has not already handled the interaction. This seems way cleaner and clearer to me.

Thoughts?

**Comment by mteper** [comment]
@kentcb so the VM would expose a public read-only observable and the View would simply subscribe to it, correct? Sounds reasonable. @pmbanka?

**Comment by kentcb** [comment]
@mteper @pmbanka right. To be super clear, this is what I'm proposing (more or less - time will tell if it's all possible, and naming may change a little):

```cs
public class LocalInteractionViewModel : ReactiveObject
{
    private readonly UserInteractionSubject<UserInteraction<bool>> confirmFileDeletion;

    public LocalInteractionViewModel()
    {
        this.confirmFileDeletion = new UserInteractionSubject<UserInteraction<bool>>();
    }

    public IObservable<UserInteraction<bool>> ConfirmFileDeletion => this.confirmFileDeletion;

    public async Task DeleteFileAsync()
    {
        // create the interaction instance
        var confirmation = new UserInteraction<bool>();

        // raise it and await the result (this will throw if nothing handles the interaction)
        var result = await this.confirmFileDeletion.OnNextAsync(confirmation);

        if (result)
        {
            // delete the file
        }
    }
}

public class LocalInteractionView
{
    public SomeView()
    {
        this
            .ViewModel
            .ConfirmFileDeletion
            .Subscribe(
                async interaction =>
                {
                    var deleteIt = await this.DisplayAlert(
                        "Confirm Delete",
                        "Are you sure you want to delete this super important file?",
                        "YES",
                        "NO");

                    interaction.SetResult(deleteIt);
                });
    }
}

public class GlobalInteractionViewModel : ReactiveObject
{
    public async Task DeleteFileAsync()
    {
        // create the interaction instance
        var confirmation = new UserInteraction<bool>();

        // raise it globally and await the result (this will throw if nothing handles the interaction)
        var result = await UserInteractionSubject.Global.OnNextAsync(confirmation);

        if (result)
        {
            // delete the file
        }
    }
}

public class GlobalInteractionView
{
    public SomeView()
    {
        UserInteractionSubject
            .Global
            .OfType<UserInteraction<bool>>()
            .Subscribe(
                async interaction =>
                {
                    var deleteIt = await this.DisplayAlert(
                        "Confirm Delete",
                        "Are you sure you want to delete this super important file?",
                        "YES",
                        "NO");

                    interaction.SetResult(deleteIt);
                });
    }
}
```

**Comment by pmbanka** [comment]
I really like what @kentcb proposed.

1. `UserInteractionSubject` name also crossed my mind, and I agree that while `Subject` is not a perfect name, it is generally understood by Rx community. And the class is a thin wrapper over a Subject, after all.

2. Moving `Raise` to the said subject, instead of `UserInteraction` itself makes everything look uniform, so :+1: 

3. Naming: `Raise` and `RegisterHandler` are words from events world, `OnNextAsync` and `Subscribe` are from Rx world (which is better). OTOH, they might confuse people (where is OnCompleteAsync? Why OnNextAsync is not void-returning?), but sprinkling same XML comments might help.

4. Instead of `UserInteractionSubject<UserInteraction<bool>>`, I would simply use `UserInteractionSubject<bool>` (because there is no point in `UserInteractionSubject<SomethingElse<bool>>`, so why repeat oneself).

**Comment by kentcb** [comment]
OK, so I just remembered why I didn't do it this way in the first place (sorry, just came back to me). Observers are not asynchronous. Because of the way interactions work, each observer needs to be invoked in order, and once the interaction is handled no more observers are invoked. So the source/subject needs to basically await the `OnNext` call for each observer, which it can't do against `IObserver<T>`.

So I think that whilst we can simulate a subject and naming etcetera, it won't truly be regular rx. I could imagine us defining an `IAsyncObserver` and building a whole bunch of infrastructure off that, but that's not realistic.

As for point 4, this was intentional. People can subclass `UserInteraction<T>` and we want them to be able to use their subclasses in a `UserInteractionSubject`.

**Comment by pmbanka** [comment]
@kentcb 

Re point 4 - totally agree, didn't think of that.

Re your first paragraph (*OK, so I just remembered why I didn't do it this way...*), do I understand it correctly that this problem occurs only when moving `Raise` into the subject class? If so, we can take one step back and settle up on this kind of an API:

```
public class LocalInteractionViewModel : ReactiveObject
{
    private readonly UserInteractionSubject<UserInteraction<bool>> confirmFileDeletion;

    public LocalInteractionViewModel()
    {
        this.confirmFileDeletion = new UserInteractionSubject<UserInteraction<bool>>();
    }

    public IObservable<UserInteraction<bool>> ConfirmFileDeletion => this.confirmFileDeletion;

    public async Task DeleteFileAsync()
    {
        // create the interaction instance
        var confirmation = new UserInteraction<bool>();

        // raise it and await the result (this will throw if nothing handles the interaction)
        var result = await confirmation.RaiseOn(this.confirmFileDeletion);

        if (result)
        {
            // delete the file
        }
    }
}

public class LocalInteractionView
{
    public SomeView()
    {
        this
            .ViewModel
            .ConfirmFileDeletion
            .Subscribe(
                async interaction =>
                {
                    var deleteIt = await this.DisplayAlert(
                        "Confirm Delete",
                        "Are you sure you want to delete this super important file?",
                        "YES",
                        "NO");

                    interaction.SetResult(deleteIt);
                });
    }
}

public class GlobalInteractionViewModel : ReactiveObject
{
    public async Task DeleteFileAsync()
    {
        // create the interaction instance
        var confirmation = new UserInteraction<bool>();

        // raise it globally and await the result (this will throw if nothing handles the interaction)
        var result = await confirmation.RaiseOn(UserInteractionSubject.Global);

        if (result)
        {
            // delete the file
        }
    }
}

public class GlobalInteractionView
{
    public SomeView()
    {
        UserInteractionSubject
            .Global
            .OfType<UserInteraction<bool>>()
            .Subscribe(
                async interaction =>
                {
                    var deleteIt = await this.DisplayAlert(
                        "Confirm Delete",
                        "Are you sure you want to delete this super important file?",
                        "YES",
                        "NO");

                    interaction.SetResult(deleteIt);
                });
    }
}
```

**Comment by kentcb** [comment]
@pmbanka no, it actually has to do with the fact that we're trying to implement it as observable/observer when that pattern does not allow for return results from observers (each observer is potentially asynchronous with respect to the observable). Try to imagine how you would implement [this method](https://github.com/reactiveui/ReactiveUI/blob/rxui7-master/ReactiveUI/Interactions.cs#L171) if each handler is an `IObserver<T>`. The more I think about this, the more I'm coming back to thinking I was right to avoid Rx terminology the first time around because it's even more misleading.

So I think what can actually be improved is as follows:
* moving the responsibility for delivering interactions to handlers into a separate class (call it an interaction source, for now)
* moving the method to raise an interaction to the source
* making global interactions occur via a static instance of a source
* tweak naming further if we can come up with something better

**Comment by mteper** [comment]
:+1:
