### ISSUE TITLE
[Documentation] Example Code contains errors and throw runtime error

### ISSUE THREAD

**Issue by NPadrutt** [reactiveui/ReactiveUI#1040]
The Sample in the documentation found [here] (http://docs.reactiveui.net/en/getting-started/example.html) Seems to contain an error. It will run but as soon as it's started crash with a System.NullReferenceException at this code:

````
this.WhenAnyValue(x => x.SearchTerm)
                .Throttle(TimeSpan.FromMilliseconds(800), RxApp.MainThreadScheduler)
                .Select(x => x.Trim())
                .DistinctUntilChanged()
                .Where(x => !String.IsNullOrWhiteSpace(x))
                .InvokeCommand(ExecuteSearch);
````

More precise at the:
````
.Select(x => x.Trim())
````

I tried some things to fix this, but didn't suceed. If the snipped is somewhere available and someone can give me some hints how that is to fix I could make a pull request.

Two minor things:
- there is a semicolon missing
- IMHO a note that there is a reference on System.Web required would be great, especially for those without resharper

**Comment by ghuntley** [comment]
Cheers for the report nino, I'll take a look in a sec. Closing this issue but https://github.com/reactiveui/documentation/issues/15 has been opened in it's place.

Sorry if you wasted time on this, you should come join us in Slack :-)
