### ISSUE TITLE
For a VS extension, RxUI runs in Unit Test mode if Resharper is installed.

### ISSUE THREAD

**Issue by smobs** [reactiveui/ReactiveUI#1041]
(Windows 10, Visual Studio 2015, RxUI 6.5)
I'm using ReactiveUI with WPF to create a Visual Studio extension.

Running the extension on my experiment instance of Visual Studio without Resharper everything is fine.
However when I run the application in a copy of Visual Studio with Resharper installed the UI remains blank.

I believe this is because Resharper depends on nunit, and because nunit is loaded ModeDetector thinks that we are running a unit test and destroys the threading.

I see that Splat provides ModeDetector.OverrideModeDetector (https://github.com/paulcbetts/splat/blob/495874640b048384d727b3a82cff60aca7313a34/Splat/ModeDetector.cs), but RxUI doesn't appear to surface that functionality.

Has anyone got any suggestions?

**Comment by flagbug** [comment]
Just use Splat's `ModeDetector.OverrideModeDetector`, RxUI will automatically "detect" that change

**Comment by smobs** [comment]
Good idea, I'll give it a go.

**Comment by smobs** [comment]
Awesome that worked a treat.
