### ISSUE TITLE
Wrong Splat dependency inside ReactiveUI nuspec 

### ISSUE THREAD

**Issue by Aszan** [reactiveui/ReactiveUI#1060]
```ReactiveUI``` packages (version **6.5.0** ATOW) leverages ```Splat``` **1.0.0** which lacks many platform support. If we try to install ```ReactiveUI``` packages, installation rollback due to ```Splat``` incompatibility.

Workaround: start by installing ```Splat``` (version **1.6.2** ATOW) then continue with ```ReactiveUI```

Please review & update the minimum ```Splat``` requirement

**Comment by ghuntley** [comment]
See also #905 and #983 and #928. Fixed in issue #850 but not available as binary package at this stage.  Apologies for the inconvenience, haven't seen you around these woods before. Come join us in Slack @Aszan!

**Comment by Aszan** [comment]
Thanks for you quick reply @ghuntley, hope v7 is coming soon because this kind of issue is not very new-comer friendly... See U soon on slack

**Comment by ghuntley** [comment]
Howdy we have pushed v6.5.1 to NuGet which resolves installation into portable class libraries that target Profile259. This release contains the exact same binaries as v6.5.0 but resolves a nuspec metadata version definition which was causing this problem.

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">.<a href="https://twitter.com/ReactiveXUI">@ReactiveXUI</a> v6.5.1 has been released. Resolves install into Profile259 ie UWP/XamForms. Same binaries as v6.5.0. <a href="https://t.co/gBjxHQxsjZ">pic.twitter.com/gBjxHQxsjZ</a></p>&mdash; Geoffrey Huntley (@GeoffreyHuntley) <a href="https://twitter.com/GeoffreyHuntley/status/765822657463857152">August 17, 2016</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
