### ISSUE TITLE
include more IBindingTypeConverter's by default

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/ReactiveUI#1070]
This is a issue to track what IBindingTypeConverter's are missing from RxUI and to encourage those who have already implemented their own type converters for common controls to contribute them back to the project. 

If you stumble upon this issue and find a IBindingTypeConverter missing then please comment below AND send through a pull request. The documentation has been updated with instructions on how to create them.

http://docs.reactiveui.net/en/user-guide/binding/type-converters.html

When submitting a pull-request please reference this issue.
# UWP
# WPA
# Android
# iOS
# Mac
# WinForms
# WPF

**Comment by rdavisau** [comment]
I'd like to add binding converters for the iOS Unified primitives - `nint`<->`int`, `nuint`<->`uint`, `nfloat`<->`float`. This applies to 64 bit only.

I think I need to:

- [x] write the converters, put them in `ReactiveUI_IOS64\Cocoa\Converters`
- [ ] link? the converters into `ReactiveUI_Mac64\Cocoa\Converters`
- [ ] add the registration of the converters to _________? 
- [ ] add the tests to _________?

The work-in-progress is [here](https://github.com/reactiveui/ReactiveUI/compare/rxui7-master...rdavisau:unified-primitive-bindingconverters).
