### ISSUE TITLE
Update the Xamarin Android Support libraries

### ISSUE THREAD

**Issue by aalmada** [reactiveui/ReactiveUI#1073]
The ReactiveUI.AndroidSupport is using the version 22.1.1.1 released in April 2015. The latest version is 23.1.1 released in December 2015.
https://www.nuget.org/packages/Xamarin.Android.Support.v4/
https://www.nuget.org/packages/Xamarin.Android.Support.v7.AppCompat/

**Comment by flagbug** [comment]
We don't depend on any of the new functionality, so user can update those themselves, instead of ReactiveUI enforcing a higher version

**Comment by aalmada** [comment]
Ok. Fair enough. :)
