### ISSUE TITLE
ObservableAsPropertyHelper not on dispatcher by default

### ISSUE THREAD

**Issue by dhintermann** [reactiveui/ReactiveUI#1075]
The documentation of ObservableAsPropertyHelper (file ReactiveUI/ObservableAsPropertyHelper.cs) mentions the following regarding the scheduler parameter:

_The scheduler that the notifications will be provided on - this should normally be a 
Dispatcher-based scheduler (**and is by default**)_

However, in the constructor code you have
`scheduler = scheduler ?? CurrentThreadScheduler.Instance;`

which is not the the main thread scheduler. Therefore, the ToProperty() method is not guarantueed to be executed on the dispatcher.

Is the documenation misleading or wrong or the behaviour of ObservableAsPropertyHelper to be changed?
I checked the source code of 6.5.0 and the 7 master branch. It's in both sources the same.

**Comment by kentcb** [comment]
@dhintermann can I ask why you closed? If what you're saying is true, I would agree that either the code or docs need to be changed.

**Comment by dhintermann** [comment]
@kentcb I thought it's a bit an insignificant issue compared to the rest in the open issue list, but I think you're right, it would be worth fixing. I reopen this.
