### ISSUE TITLE
Memory leaks using Xamarin-IOS

### ISSUE THREAD

**Issue by DrakorBofh** [reactiveui/ReactiveUI#1093]
Memory leaks using Xamarin.IOS

I have serious memory leaks with ReactUI.
I make a simple app to try to figure out the problem with this.
This app have 3 simples screens. 1- just have one UIBUtton for change to screenOne. 2- This screen have 3 button and 2 extra buttons for navigation (Back and go to last screen) 3- Have 4 buttons and one more to back.

All elements related with UIKit is disposed correctly, but not all reactive related.

I try everything to figure out what is wrong. I think the problem is between Reference counter of IOS and Garbage collector of Xamarin, but i cant confirm o refute this hipotesis.

The app source code is here: https://github.com/DrakorBofh/ReactiveIOSTest
This is a export of the app using the xamarin profiling tool:https://drive.google.com/file/d/0BwHPAEqsPcm5TjRhMVlONkl1ZEE/view?usp=sharing

In this file, i followed the following steps:
FirstScreen -> SecondScreen -> ThridScreen-> back to SecondScreen -> back to FirstScreen.
In all change of screen, the previous is disposed.

I Attached 3 screenshots of the Profiling tool with some examples.  
This show the reference to some Viewmodels that must be disposed.

![screen shot 1](https://cloud.githubusercontent.com/assets/3043906/14328613/da7d7cf8-fc0d-11e5-951a-80c3cd066f1c.png)
![screen shot 2](https://cloud.githubusercontent.com/assets/3043906/14328614/daa14d4a-fc0d-11e5-9ccd-4ed24f5dd342.png)
![screen shot 3](https://cloud.githubusercontent.com/assets/3043906/14328615/dad97440-fc0d-11e5-8c19-ad4b32e35fbb.png)

**Comment by mjracca** [comment]
Paul, could you send us the quick fix for the KVOObservableForProperty you mentioned the other day?

**Comment by DrakorBofh** [comment]
# A deeper analysis of memory leaks
I created incrementally an example to try to get all memory leaks.
The results:

**ReactiveObject**
ReactiveObject without any Properties or Commands.

- ReactiveUI.IReactivePropertyChangedEventArgs
- ReactiveUI.IReactiveObjectExtensions.ExtensionState
- ReactiveUI.IreactivePropertyChangedEventArgs
- System.Collections.Generic.ObjectEqualityComparer
- System.Reactive.DisposedObserver
- System.Reactive.DoneObserver
- System.Reactive.NopObserver

**ReactiveObject + RaiseAndSetIfChanged**

- The following classes, will be instanced for each view model used
- System.Reactive.NopObserver<ReactiveUI.IReactivePropertyChangedEventArgs
- System.Func<ReactiveUI.IReactivePropertyChangedEventArgs
- System.Func<SystemCollections.Generic.IList<ReactiveUI.IreactivePropertyChangedEventArgs

**ReactiveView**

- ReactiveView without any ViewModel or bindings.
- ReactiveUI.AppSupportJsonSuspensionDriver
- ReactiveUI.CanActivateViewFetcher
- ReactiveUI.CocoaDefaultPropertyBinding
- ReactiveUI.ComponentModelTypeConverter
- ReactiveUI.CreatesCommmandBindingViaCommandParameter
- ReactiveUI.CreatesCommandBindingViaEvent
- ReactiveUI.DateTimeNSDateConverter
- ReactiveUI.DefaultVideLocator
- ReactiveUI.EqualityTypeConverter
- ReactiveUI.ExpressionRewriter
- ReactiveUI.FlexibleCommandBinder.CommandBindingInfo
- ReactiveUI.INPCObservableForProperty
- ReactiveUI.IROObservableForProperty
- ReactiveUI.KVOObservableForProperty
- ReactiveUI.KVOObservableForProperty.<KVOObservableForProperty>c_AnonStorey1
- ReactiveUI.NSRunloopScheduler
- ReactiveUI.NSRunloopScheduler.<Schedule>c_AnonStorey0<System.Action>
- ReactiveUI.NullDefaultPropertyBindingProvider
- ReactiveUI.PlafotmOperations
- ReactiveUI.POCOObservableForProperty
- ReactiveUI.ReactiveCommand<System.Exception>
- ReactiveUI.StringConverter
- ReactiveUI.SuspensionHost
- ReactiveUI.UIKitcommandBinder
- ReactiveUI.UIKitObservableForProperty
- ReactiveUI.UIKitObservableForPropertyBase.ObservablePropertyInfo
- ReactiveUI.WaitForDispatcherScheduler
- System.Reactive.Subjects.ConnectableObservable<System.Boolean, System.Boolean>
- System.Reactive.Subjects.ReplaySubject.ReplayOne<System.IObservable<System.IDisposable>>
- System.Reactive.Subjects.ReplaySubject.ReplayOne<System.IObservable<System.Reactive.Unit>>
- System.Reactive.Subjects.ReplaySubject<System.IObservable<System.IDisposable>>
- System.Reactive.Subjects.ReplaySubject<System.IObservable<System.Reactive.Unit>>
- System.Reactive.Subjects.Subject.Subscription<System.Exception>
- System.Reactive.Subjects.Subject.Subscription<System.Reactive.EventPattern<System.EventArgs>>
- System.Reactive.Subjects.Subject<System.Boolean>
- System.Reactive.Subjects.Subject<System.Exception>
- System.Reactive.Subjects.Subject<System.Object>
- System.Reactive.Subjects.Subject<System.Reactive.EventPattern<System.EventArgs>>
- System.Reactive.Subjects.Subject<System.Reactive.Unit>

**ReactiveView + IViewFor**

- ReactiveUI.WeakEventManager<ReactiveUI.INotifyPropertyChanging, ReactiveUI.PropertyChangingEventHandler, ReactiveUI.PropertuChangingEventArgs>
- ReactiveUI.WeakEventManager<System.ComponentModel.INotifyPropertyChanged, System.ComponentModel.PropertyChangedEventHandler, System.CompoenentModel.PropertyChangedEventArgs>

**OneWayBind**
No extra memory leaks

**BindCommand**
No extra memory leaks

**WhenAnyValue**
No extra memory leaks

**ReactiveCommand.Subscribe()**
No extra memory leaks

**Comment by DrakorBofh** [comment]
# A deeper analysis of memory leaks
I created incrementally an example to try to get all memory leaks.
The results:


**ReactiveObject**
ReactiveObject without any Properties or Commands.
- ReactiveUI.AppSupportJsonSuspensionDriver
- ReactiveUI.CanActivateViewFetcher
- ReactiveUI.CocoaDefaultPropertyBinding
- ReactiveUI.ComponentModelTypeConverter
- ReactiveUI.CreatesCommmandBindingViaCommandParameter
- ReactiveUI.CreatesCommandBindingViaEvent
- ReactiveUI.DateTimeNSDateConverter
- ReactiveUI.DefaultVideLocator
- ReactiveUI.EqualityTypeConverter
- ReactiveUI.ExpressionRewriter
- ReactiveUI.FlexibleCommandBinder.CommandBindingInfo
- ReactiveUI.INPCObservableForProperty
- ReactiveUI.IROObservableForProperty
- ReactiveUI.KVOObservableForProperty
- ReactiveUI.KVOObservableForProperty.<KVOObservableForProperty>c_AnonStorey1
- ReactiveUI.NSRunloopScheduler
- ReactiveUI.NSRunloopScheduler.<Schedule>c_AnonStorey0<System.Action>
- ReactiveUI.NullDefaultPropertyBindingProvider
- ReactiveUI.PlafotmOperations
- ReactiveUI.POCOObservableForProperty
- ReactiveUI.ReactiveCommand<System.Exception>
- ReactiveUI.StringConverter
- ReactiveUI.SuspensionHost
- ReactiveUI.UIKitcommandBinder
- ReactiveUI.UIKitObservableForProperty
- ReactiveUI.UIKitObservableForPropertyBase.ObservablePropertyInfo
- ReactiveUI.WaitForDispatcherScheduler

![reactiveobject-1](https://cloud.githubusercontent.com/assets/3043906/14447092/fd2b443c-0032-11e6-8d29-edf39edece57.png)
![reactiveobject-2](https://cloud.githubusercontent.com/assets/3043906/14447103/055c425a-0033-11e6-9124-f8122b2dfa36.png)

**ReactiveObject + RaiseAndSetIfChanged**

- ReactiveUI.WeakEventManager<ReactiveUI.INotifyPropertyChanging, ReactiveUI.PropertyChangingEventHandler, ReactiveUI.PropertuChangingEventArgs>
- ReactiveUI.WeakEventManager<System.ComponentModel.INotifyPropertyChanged, System.ComponentModel.PropertyChangedEventHandler, System.CompoenentModel.PropertyChangedEvent

![reactiveobject_raiseandsetifchanged-1](https://cloud.githubusercontent.com/assets/3043906/14447126/35797f20-0033-11e6-8b38-d4c262fb9f66.png)
![reactiveobject_raiseandsetifchanged-2](https://cloud.githubusercontent.com/assets/3043906/14447130/36028162-0033-11e6-9e8a-28a7793c5689.png)
![reactiveobject_raiseandsetifchanged-3](https://cloud.githubusercontent.com/assets/3043906/14447127/35d3377c-0033-11e6-84d3-6f0ce011f04c.png)
![reactiveobject_raiseandsetifchanged-4](https://cloud.githubusercontent.com/assets/3043906/14447129/35ef48ae-0033-11e6-9bc5-b3a5fbfd32d5.png)
![reactiveobject_raiseandsetifchanged-5](https://cloud.githubusercontent.com/assets/3043906/14447131/3665c178-0033-11e6-8f76-7e1e024f5da2.png)

**ReactiveView**
ReactiveView without any ViewModel or bindings.
- System.Reactive.Subjects.ConnectableObservable<System.Boolean, System.Boolean>
- System.Reactive.Subjects.ReplaySubject.ReplayOne<System.IObservable<System.IDisposable>>
- System.Reactive.Subjects.ReplaySubject.ReplayOne<System.IObservable<System.Reactive.Unit>>
- System.Reactive.Subjects.ReplaySubject<System.IObservable<System.IDisposable>>
- System.Reactive.Subjects.ReplaySubject<System.IObservable<System.Reactive.Unit>>
- System.Reactive.Subjects.Subject.Subscription<System.Exception>
- System.Reactive.Subjects.Subject.Subscription<System.Reactive.EventPattern<System.EventArgs>>
- System.Reactive.Subjects.Subject<System.Boolean>
- System.Reactive.Subjects.Subject<System.Exception>
- System.Reactive.Subjects.Subject<System.Object>
- System.Reactive.Subjects.Subject<System.Reactive.EventPattern<System.EventArgs>>
- System.Reactive.Subjects.Subject<System.Reactive.Unit>

![reactiveview-1](https://cloud.githubusercontent.com/assets/3043906/14447145/47a93942-0033-11e6-8ecf-ebe77bbd317b.png)

**ReactiveView + IViewFor**
- System.Func

![reactiveview_iviewfor](https://cloud.githubusercontent.com/assets/3043906/14447149/4ca13f62-0033-11e6-9e24-eedb5751cd07.png)

**BindCommand**
- ReactiveUI.ViewForMixins
- ReactiveU.WeakEventManager
- ReactiveUI.IreactivePropertyChangedEventArgs
- ReactiveUI.IReactiveObjectExtensions.ExtensionState
- ReactiveUI.IreactivePropertyChangedEventArgs

![bindcommand-1](https://cloud.githubusercontent.com/assets/3043906/14447156/5c5b75b2-0033-11e6-87a3-5c5e792136a5.png)

**OneWayBind**
No extra memory leaks

**WhenAnyValue**
No extra memory leaks

**ReactiveCommand.Subscribe()**
No extra memory leaks

**Comment by mjracca** [comment]
Dismiss all of this, everything works fine

**Comment by paulcbetts** [comment]
We did it!
