### ISSUE TITLE
ReactiveUI with Xamarin Forms on Windows Phone 8.1

### ISSUE THREAD

**Issue by justcoding121** [reactiveui/ReactiveUI#1094]
I was able to integrate successfully ReactiveUI for both Android and ios following the xamarin.forms playground projects in this repository.

Would be nice to have the same for Windows Phone 8.1.

In my [App.xaml.cs file](https://github.com/justcoding121/JW-Reminder/blob/master/src/JW.Reminder/JW.Reminder.WinPhone/App.xaml.cs) and the [MainWindow.xaml.cs](https://github.com/justcoding121/JW-Reminder/blob/master/src/JW.Reminder/JW.Reminder.WinPhone/MainPage.xaml.cs) I reached the point of bootstrapping the MainPage with reactiveUI but don't know how to connect it to the phone UI.

I request to include some samples in to this repository.

**Comment by justcoding121** [comment]
Found a way to integrate in my latest commit. Hopefully correct.

**Comment by ghuntley** [comment]
@justcoding121 come join us in Slack & check out https://github.com/kentcb/WorkoutWotch & https://www.youtube.com/playlist?list=PLwqdWBgwaokVPpdPOOJ-GTGiHcqoG5alU
