### ISSUE TITLE
[v7] ReactiveUI.Events_XamForms.dll does not automatically install into Xamarin.Forms (shared library project)

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/ReactiveUI#1098]
`ReactiveUI.Events_XamForms.dll` will not be automatically added as a reference when installing `reactiveui-events` (v7) into a Xamarin Forms shared library application. This means the user will need to `right click -> add reference` the library and do those manual steps every time a new version is released. Yick. The NuGet package `reactiveui-events` cannot force consumers of the package to install Xamarin Forms FYI as it is a global package that targets multiple platforms, including Mac, WPF, WP8, NET45, Xamarin.iOS and Xamarin.Android.

This is potentially(?) a bug with NuGet itself with Shared Library resolution. If you know how to fix this, then please send in a PR :-)

v7 nuspec is @ https://github.com/reactiveui/ReactiveUI/blob/myget/src/ReactiveUI-Events.nuspec

**Comment by jbogard** [comment]
Why isn't this its own package? For just xam-forms events?

**Comment by Redth** [comment]
Is there code specific to Xamarin.Forms in that library? If so, I would tend to agree, it should be in its own nuget package and take a dependency on Xamarin.Forms.

I'm not exactly sure how the nuget resolution works with shared libraries.  The recommended way of creating Forms apps is to use a PCL instead of shared project.

Also, if it's any help, here's the platform string I use in my ZXing.Net.Mobile.Forms nuspec to target the PCL project:
`portable-net45+netcore45+wp8+UAP10.0+MonoAndroid403+MonoTouch10+Xamarin.iOS10`

**Comment by jbogard** [comment]
@Redth Yeah, it's completely specific to Xamarin.Forms. And for Shared vs. PCL, I was conducting an experiment, but it should still work I think.

**Comment by Redth** [comment]
@jbogard then I would agree, this should be in its own nuget package... 

So the way shared projects work (at least from my experience in Xamarin Studio) is you add nuget packages to the projects that reference them, not directly to the shared project itself.  

So is the real question is, why isn't that reference being pulled into the individual projects in the Forms solution when added to them? 

One immediate thing that comes to mind is `Xamarin.iOS` is completely missing from the profile string, so it won't get added to any new xamarin.ios projects (only classic API ones which are quite deprecated).

Perhaps the easiest way to work around this would be to specify a line item for the same library for each platform in the nuspec like this:

```xml
<file src="bin/Release/Portable-Net45+WinRT45+WP8+MonoAndroid10+MonoTouch10/ReactiveUI.Events_XamForms.dll" target="lib/WP8/ReactiveUI.Events_XamForms.dll" />
<file src="bin/Release/Portable-Net45+WinRT45+WP8+MonoAndroid10+MonoTouch10/ReactiveUI.Events_XamForms.dll" target="lib/MonoAndroid403/ReactiveUI.Events_XamForms.dll" />
<file src="bin/Release/Portable-Net45+WinRT45+WP8+MonoAndroid10+MonoTouch10/ReactiveUI.Events_XamForms.dll" target="lib/Xamarin.iOS10/ReactiveUI.Events_XamForms.dll" />
<file src="bin/Release/Portable-Net45+WinRT45+WP8+MonoAndroid10+MonoTouch10/ReactiveUI.Events_XamForms.dll" target="lib/UAP10.0/ReactiveUI.Events_XamForms.dll" />
```

**Comment by jbogard** [comment]
I think it's gonna need its own package, because the underlying assumption with the current setup is that the XamForms assembly only installs into PCL, so ONLY PCL libraries will have Xamarin.Forms, and nothing else.

**Comment by onovotny** [comment]
Agree. This needs its own package as Xam Forms itself is not a TFM you can pivot on.

**Comment by Redth** [comment]
Great! I think it should also just target the correct PCL profile (probably 78), which I believe means it won't work ootb with shared projects, but like I mentioned before, that's really not the recommended way to build a Forms project anyway.

**Comment by onovotny** [comment]
@ghuntley FTFY: https://github.com/reactiveui/ReactiveUI/commit/95b8a9fed1e4224ab12b7ca6240770f54a9e29b7 :)

**Comment by onovotny** [comment]
Bottom line is that the events package should not pull in Xam Forms at all. It's an explicit choice to pull it in.

**Comment by ghuntley** [comment]
So many brains - @Redth (and others!) thanks for stopping by and offering help. Separate package `reactiveui-events-xamforms` has been created (which has Xamarin.Forms as a dependency) and is available on NuGet - it works with shared and PCL projects. Additionally will review PCL target for all other packages and make adjustments where needed.
