### ISSUE TITLE
reactiveui nuget package fails to install on PCL 259

### ISSUE THREAD

**Issue by kjeremy** [reactiveui/ReactiveUI#1103]
It resolves splat version 1.0 which fails to install via nuget.  I have to manually install splat before I can install reactiveui.

**Comment by moswald** [comment]
Yeah, I believe this has been fixed in v7, which is in beta.

For now, the workaround is to install Splat 1.6.2 first, _then_ install RxUI.

**Comment by ghuntley** [comment]
Howdy we have pushed v6.5.1 to NuGet which resolves installation into portable class libraries that target Profile259. This release contains the exact same binaries as v6.5.0 but resolves a nuspec metadata version definition which was causing this problem.

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">.<a href="https://twitter.com/ReactiveXUI">@ReactiveXUI</a> v6.5.1 has been released. Resolves install into Profile259 ie UWP/XamForms. Same binaries as v6.5.0. <a href="https://t.co/gBjxHQxsjZ">pic.twitter.com/gBjxHQxsjZ</a></p>&mdash; Geoffrey Huntley (@GeoffreyHuntley) <a href="https://twitter.com/GeoffreyHuntley/status/765822657463857152">August 17, 2016</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
