### ISSUE TITLE
[myget] investigate/resolve exception with UWP and routing

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/ReactiveUI#1106]
Michael has encountered some problems with the w/v7 bits from the MyGet CI feed when using IScreen/RoutedViewHost navigation:

https://reactivex.slack.com/archives/reactiveui/p1462395325000522

> Additional information: Method not found: 'ReactiveUI.ReactiveCommand`1<System.Object> ReactiveUI.RoutingState.get_Navigate()'.

**Comment by glennawatson** [comment]
Confirmed as fixed.
