### ISSUE TITLE
Unit Testing ReactiveUI 6.5.0 doesn't invoke Reactive Events

### ISSUE THREAD

**Issue by MistyKuu** [reactiveui/ReactiveUI#1108]
Hey,
simple test case:
http://stackoverflow.com/questions/37155703/reactive-6-5-0-reactivecommand-after-migration.
After downloading ReactiveUI 6.5.0 from NUGET a lot of my Unit Tests (Resharper Runner + Nunit) stopped working without any obvious reason.
After downloading sources from here https://codeload.github.com/reactiveui/ReactiveUI/zip/6.5.0, building it manually and including ReactiveUI.dll instead of the one from nuget everything works fine. This is not the only test case that doesn't work. Not sure why there is any difference between these two versions but I assume there shouldn't be.

**Comment by MistyKuu** [comment]
Hey, I have solved the issue. It happens in ReactiveUI 7.0 as well and I assume it's not the expected behaviour.
One of my Unit Tests was using DelegateCommand (my own implementation) which was calling CommandManager.InvalidateRequerySuggested. After calling that it completely changes ReactiveUI behaviour - DispatcherScheduler.Current doesn't throw an exception and different dispatcher is used later on during all unit tests. For more details please go to stackoverflow topic for further explanation

**Comment by kentcb** [comment]
ReactiveUI 4.5 is before my time, so I'm not really sure what the situation is there. However, in more modern ReactiveUI it's actually Splat (a dependency) that decides whether you're executing in a test environment or not. If Splat is deciding that you're not, the scheduler being used by the reactive command won't default correctly.

First, make sure you upgrade to the latest Splat. If that doesn't solve the problem (and arguably even if it does), you should probably be explicitly passing a scheduler to the command. That way you can control scheduling from your test.

Here's a simplified example, using RxUI 7 (it's similar in 6, but with some different names):

```C#
public ViewModel(IWfController workflowController, IScheduler scheduler)
{
    _workflowController = workflowController;

    _runProcessCommand = ReactiveCommand.Create(RunImpl, CanRunProcess, scheduler);
}

// in the test
var workflowController = ...;
var scheduler = new TestScheduler();
var sut = new ViewModel(workflowController, scheduler);

sut.Actions.Single().Execute();
scheduler.Start();

Assert(...);
```

Please let me know if this helps.

**Comment by MistyKuu** [comment]
Hey,
you are probably talking about ModeDetector.InUnitTestRunner() function. This function always returns value correctly. Passing a scheduler wasn't enough in all cases. I've got a lot more tests that were failing because for example CommandManager.InvalidateRequerySuggested was called previously which created a dispatcher and then RaiseAndSetIfChanged was executed and subscription related to that event weren't raised because attemptToCreateScheduler() returned dispatcher in unit tests. I am not even sure why this function is being called even if I pass scheduler.

**Comment by kentcb** [comment]
Yes please - a standalone repro would be ideal.

**Comment by MistyKuu** [comment]
This behavior I've experienced at work and I couldn't reproduce it at home. But I am sure that something must be wrong unless there is something I don't understand about Reactive. I think there is no point of including the entire project, this example is showing exactly that scheduler is dispatcher instead of current thread if you use that function. Please debug it and you'll notice a different behaviour between these two calls in  attemptToCreateScheduler() function in WaitForDispatcherScheduler class. ReactiveUI is version 7.0.

```
   [Test]
        public void TestMethod1()
        {
            RxApp.MainThreadScheduler.Schedule<string>(null, (x, y) => Disposable.Empty);
            CommandManager.InvalidateRequerySuggested();
            RxApp.MainThreadScheduler.Schedule<string>(null, (x, y) => Disposable.Empty);
        }
```

**Comment by MistyKuu** [comment]
Related issue: https://github.com/reactiveui/ReactiveUI/issues/854

**Comment by kentcb** [comment]
So, the reason the second invocation exhibits different behavior is beacuse `InvalidateRequestSuggested` must be accessing the dispatcher internally. By accessing the dispatcher, it gets created if it hasn't already been created. For example, this test acts the same:

```C#
[Fact]
public void repro()
{
    RxApp.MainThreadScheduler.Schedule<string>(null, (x, y) => Disposable.Empty);
    var foo = System.Windows.Threading.Dispatcher.CurrentDispatcher;
    RxApp.MainThreadScheduler.Schedule<string>(null, (x, y) => Disposable.Empty);
}
```

So the questions I have now are:

* should the unit tests even be using a dispatcher scheduler?
* if so, should the unit tests pre-emptively access the dispatcher to ensure it has been created?

Need to look into this more, but right now is Dinner Time.
