### ISSUE TITLE
ReactiveUI 7.0

### ISSUE THREAD

**Issue by MistyKuu** [reactiveui/ReactiveUI#1109]
Hey,
I have noticed performance hit when using ReactiveUI. After digging into sources I've noticed that function attemptToCreateScheduler() silently fails and as a result is using CurrentThread.Instance instead of Dispatcher. I understand this behaviour if there is no dispatcher but in my case I didn't include System.Reactive.Windows.Threading and missing dll exception was thrown there. Please add specific exception handling for that type and rethrow exception.

**Comment by paulcbetts** [comment]
Can you submit a PR to this effect?

**Comment by MistyKuu** [comment]
Done. https://github.com/reactiveui/ReactiveUI/pull/1110
