### ISSUE TITLE
ReactiveListAdapter never renders

### ISSUE THREAD

**Issue by akamud** [reactiveui/ReactiveUI#1111]
I'm trying to use a `ReactiveListAdapter` to render a `ReactiveList` that will be populated by a `ReactiveCommand`, I'm doing pretty much the same as the [Playground-Android](https://github.com/reactiveui/ReactiveUI/tree/6.5.0/Playground-Android) code does, but my `ListView` never shows up.

This is how I attach the adapter to the `ListView` in the `MainActivity`:
```C#
var adapter = new ReactiveListAdapter<GitHubUserInfo>(
				ViewModel.SearchResult,
				(viewModel, parent) => new GitHubUserInfoView(viewModel, this, parent));
``` 

Then `SearchResult` gets populated by a `ReactiveCommand` result:
```C#
_searchResult = Search.ToProperty(this, v => v.SearchResult, new ReactiveList<GitHubUserInfo>());
```

This doesn't work and doesn't fire any errors, but my `ReactiveViewHost` implementation never gets called, as if it never saw the `ReactiveList` getting updated.

What am I missing here?

The whole code is in here: https://github.com/akamud/HackDaysRxUI

**Comment by kentcb** [comment]
Hi @akamud,

You are creating the adapter against a given instance of `ReactiveList<GitHubUserInfo>`, but then you're completely replacing that instance every time a search is performed. So the adapter in use is pointing to the old, empty instance.

You can either change your logic to create a new adapter every time, or - as I suspect you were trying to do - don't create a new instance on every search, but instead clear and repopulate the list.

Here's an example of creating a new adapter every search (in `MainActivity`):

```C#
            this.WhenAnyValue(x => x.ViewModel.SearchResult)
                .Select(sr => new ReactiveListAdapter<GitHubUserInfo>(sr, (vm, parent) => new GitHubUserInfoView(vm, this, parent)))
                .Subscribe(a => UsersList.Adapter = a);
```

To clear and repopulate, you'll need to fix up your code a bit. The search layer can just return a standard list. Your VM should subscribe to your `Search` command (which would just return `List<GitHubUserInfo>`) and do something like:

```C#
Search
    .Subscribe(
        results =>
        {
             this.SearchResults.Clear();
             this.SearchResults.AddRange(results);
        });
```

**Comment by akamud** [comment]
Thank you so much for the quick response.

For future reference, is here the best place to ask questions like this?

**Comment by kentcb** [comment]
No worries @akamud. Here is fine, but you might get quicker turnaround on our Slack channel. See [the readme](https://github.com/reactiveui/ReactiveUI) for details on how to join. We'd love to have you there!
