### ISSUE TITLE
Observable breaks after exception

### ISSUE THREAD

**Issue by akamud** [reactiveui/ReactiveUI#1112]
I am trying to create an Observable from `TextChange` event from an EditText component. From there I call an async task that simulates a remote service call.

I do this creating a `ReactiveCommand` from an async task:

```C#
 Search = ReactiveCommand.CreateAsyncTask(parameter => GetGitHubUsers((string)parameter));

// executing the command
this.WhenAnyValue(u => u.UserName)
                .Select(u => this.Search.ExecuteAsync(u))
                .Switch()
                .Subscribe(results =>
                {
                    SearchResults.Clear();
                    if (results != null)
                        SearchResults.AddRange(results);
                }, ex => { ShowError = true; });
```

So from my understanding I have an Observable with Observables.

Then I throw an exception in my service, my code doesn't crash and it successfully shows the `Error` message. The problem is that then my observable stops watching for text change events. If I keep typing anything the command is not called again.

Is this a bug on Android's `ReactiveCommand` or am I doing something wrong?

I tried to have the simplest repro [here](https://github.com/akamud/HackDaysRxUI/blob/breaking/HackDaysRxUI-Core/ViewModels/ViewModel.cs#L21), I tried this code on WPF and it works, but it behaves as explained above on Android.
*Please note the sample is in the `breaking` branch.*

**Comment by moswald** [comment]
I'm actually surprised it's working properly on WPF. Catching the exception should kill the subscription. Instead of letting it reach your exception handler, you should consider adding a `.Retry` before the `.Switch` (or maybe after, I forget 😃)

**Comment by akamud** [comment]
I have tried so many things that maybe I'm mistaken about the code being exactly that on WPF.

If I just subscribe to `Search.ThrownExceptions` does it kill the subscription too?

I plan on using a `Retry`, but I was trying to show this as a step to justify the use of `Retry`. I just wanted a way to keep the application running and keep the subscription for text change alive. Is this possible?

**Comment by moswald** [comment]
Subscribing to `Search.ThrownExceptions` will only notify you and let you take action on an exception, but it won't stop the exception from being sent (and caught) in the `Subscribe`. I think what you have is correct, but you just have to continue the stream when an exception is thrown.

**Comment by akamud** [comment]
If I remove the `OnError` action the exception gets thrown and the application crashes.

**Comment by kentcb** [comment]
It's hard to say for sure without knowing your exact requirements, but it looks like you're trying to trap any error in the command execution and set `ShowError` to `true`, but leave the pipeline operational for future attempts...?

Rx is designed such that an error that reaches the subscriber will cause the pipeline to cease operating. Same goes for completion actually: once it's done, it's done. Sounds limiting, but it's just the default behavior that is intended to avoid nasty surprises. There are all sorts of ways of obtaining different behavior.

In this case, I suspect you just want to use `Catch` like this:

```C#
this
    .WhenAnyValue(u => u.UserName)
    .Select(u => this.Search.ExecuteAsync(u))
    .Switch()
    .Catch<Unit, Exception>(
        ex =>
        {
            this.ShowError = true;
            return Observable.Empty<Unit>();
        }
    .Subscribe(
        results =>
        {
            SearchResults.Clear();
            if (results != null)
                SearchResults.AddRange(results);
        },
        ex => log.Error("Oops, the pipeline failed."),
        () => log.Error("Oops, the pipeline completed."));
```

That said, there is almost certainly a more reactive way of doing this. For example, if `ShowError` should be `true` until the command completes successfully:

```C#
this.showError = Observable
    .Merge(
        this.Search.Select(_ => false),
        this.Search.ThrownExceptions.Select(_ => true))
    .ToProperty(this, x => x.ShowError);
```

Are you OK with this issue being closed now?

**Comment by akamud** [comment]
Yes, thanks!
