### ISSUE TITLE
More granular packages?

### ISSUE THREAD

**Issue by dsaf** [reactiveui/ReactiveUI#1113]
I wanted to create a separate platform-agnostic project for unit testing the generic portion of view-model code.

However reactiveui always insists on bringing all the baggage with it e.g. ```Rx-Xaml```. Annoyingly it also adds a reference to ```WindowsBase```.

Is there a real "core" package not like ```reactiveui-"core"```?

Edit: OK, now I understand that ```ReactiveUI.dll``` is monolithic so it needs every possible thing.

**Comment by kentcb** [comment]
Alas, there is not. Suffice to say, this question has come up a lot. I, for one, would love to be able to do something similar to what you're doing. Longer term I hope to address this with exactly the kind of core assembly you mention. But in the meantime, you may find [this technique](http://kent-boogaart.com/blog/using-the-visual-studio-test-runner-for-mobile-development) useful.

**Comment by dsaf** [comment]
@kentcb Yes, MonoGame has a similar problem. Thank you for responding.

**Comment by moswald** [comment]
@dsaf Are you saying you want to build a PCL to host your ViewModels, and then create a unit test project for your VMs?

It's not possible to write a completely platform-agnostic RxUI application like that, but what you *can* do is write a platform-*specific* RxUI application that exercises your platform-agnostic VM assembly. What I do is write a full .NET unit test project that consumes the VM PCL, and then I have a choice of test runners (I'm partial to nCrunch, myself). If you prefer to run your tests on at least one handset device, there's always the [xUnit Runner for Devices](https://github.com/xunit/devices.xunit). I've never had the case where I needed to write an Android test runner _and_ a .NET test runner for the VMs.

**Comment by dsaf** [comment]
@moswald To be honest I just wanted my library project to not reference 8 additional DLLs to simply use  ```IReadOnlyReactiveCollection<T>```, ```ReactiveList<T>``` and ```ReactiveObject```.
