### ISSUE TITLE
ReactiveCommand executed several times

### ISSUE THREAD

**Issue by Dima2014** [reactiveui/ReactiveUI#1114]
I'm using ReactiveUI 6.5. I want to execute a command when my propery changes and store the result in another OAPH property. The test provided below shows that my command was executed 3 times instead of 1.

Please correct me if I'm doing something wrong. I subscribe to OAPH property in order to get it's updates:

> ```
>        viewModel.WhenAnyValue(x => x.State).Subscribe();
> ```

Are there other ways to test that my OAPH property was updated?

Another comment: if I change the line

> ```
>        this.WhenAnyValue(x => x.SelectedValue)
>            .InvokeCommand(Add);
> ```

to

> ```
>        this.WhenAnyValue(x => x.SelectedValue)
>          .Subscribe(async x =>
>          {
>              if (Add.CanExecute(null))
>                  await Add.ExecuteAsync();
>          );
> ```

everything works fine.

```
public class ViewModel : ReactiveObject
{
    private int _counter;
    private bool _selectedValue;

    private ObservableAsPropertyHelper<int> _state;

    public int State
    {
        get { return _state.Value; }
    }

    public bool SelectedValue
    {
        get { return _selectedValue; }
        set { this.RaiseAndSetIfChanged(ref _selectedValue, value); }
    }

    public ReactiveCommand<int> Add { get; set; }

    public ViewModel()
    {
        Add = ReactiveCommand.CreateAsyncObservable(
            this.WhenAnyValue(x => x.SelectedValue),
            _ =>
            {
                _counter++;
                return Observable.Return(_counter);
            });

        Add.ToProperty(this, x => x.State, out _state);

        this.WhenAnyValue(x => x.SelectedValue)
            .InvokeCommand(Add);
    }

}

[TestClass]
public class ViewModelTest
{
    [TestMethod]
    public void Test()
    {
        var viewModel = new ViewModel();

        viewModel.WhenAnyValue(x => x.State).Subscribe();

        viewModel.SelectedValue = true;

        Assert.AreEqual(1, viewModel.State);
    }
}
```

**Comment by akamud** [comment]
Had the same problem.

**Comment by kentcb** [comment]
Closing this out due to age (sorry we missed this). Please re-open if this is still a problem with the latest RxUI. Also,if you need a counter of command executions, it would be far nicer to do `Add.Scan(0, (acc, _) => ++acc).ToProperty(this, x => x.Counter)`. That way, your state is encapsulated in a reactive pipeline.
