### ISSUE TITLE
.Net4.5.2 WPF applcation : Error CS7069 Reference to type 'IEnableLogger' claims it is defined in 'Splat', but it could not be found

### ISSUE THREAD

**Issue by alski** [reactiveui/ReactiveUI#1120]
See also #983 
Bizarrely I've just had this issue again, but this time for a .Net 4.5.2 WPF application from VS2015 (14.0.25123.00 Update 2) running NuGet 3.4.2.830.
 With a single WPF application project, I created a quick UI and then added Reactiveui which came in as 6.5.0, upon adding  `myReactiveCommandObject.Subscribe(________)`  I got the red wiggles with Reference to type 'IEnableLogger' claims it is defined in 'Splat', but it could not be found

Furthermore, I can resolve this by running  `Install-Package Splat -DependencyVersion Highest` which migrated Splat from 1.0.0 to 1.6.2

    Package Manager Console Host Version 3.4.2.830

    Type 'get-help NuGet' to see all available NuGet commands.

    PM> Install-Package ReactiveUI -DependencyVersion Highest
    Package 'ReactiveUI.6.5.0' already exists in project 'Hilt'
    PM> Install-Package Splat -DependencyVersion Highest
    Attempting to gather dependency information for package 'Splat.1.6.2' with respect to project 'Hilt', targeting '.NETFramework,Version=v4.5.2'
    Attempting to resolve dependencies for package 'Splat.1.6.2' with DependencyBehavior 'Highest'
    Resolving actions to install package 'Splat.1.6.2'
    Resolved actions to install package 'Splat.1.6.2'
    Removed package 'Splat.1.0.0' from 'packages.config'
    Successfully uninstalled 'Splat.1.0.0' from Hilt
      GET https://www.nuget.org/api/v2/package/Splat/1.6.2
      OK https://www.nuget.org/api/v2/package/Splat/1.6.2 2343ms
    Installing Splat 1.6.2.
    Adding package 'Splat.1.6.2' to folder 'C:\Dev\Hilt\packages'
    Added package 'Splat.1.6.2' to folder 'C:\Dev\Hilt\packages'
    Added package 'Splat.1.6.2' to 'packages.config'
    Successfully installed 'Splat 1.6.2' to Hilt
    Removing package 'Splat.1.0.0' from folder 'C:\Dev\Hilt\packages'
    Removed package 'Splat.1.0.0' from folder 'C:\Dev\Hilt\packages'
    PM>

**Comment by ghuntley** [comment]
@alski Splat needs to be installed before ReactiveUI when using 6.5 currently. It's super annoying, v7 is just around the corner and has fixed this.

**Comment by alski** [comment]
Looking forwards to v7 then :-)

**Comment by ghuntley** [comment]
Come join us in slack. :)

**Comment by ghuntley** [comment]
Howdy we have pushed v6.5.1 to NuGet which resolves installation into portable class libraries that target Profile259. This release contains the exact same binaries as v6.5.0 but resolves a nuspec metadata version definition which was causing this problem.

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">.<a href="https://twitter.com/ReactiveXUI">@ReactiveXUI</a> v6.5.1 has been released. Resolves install into Profile259 ie UWP/XamForms. Same binaries as v6.5.0. <a href="https://t.co/gBjxHQxsjZ">pic.twitter.com/gBjxHQxsjZ</a></p>&mdash; Geoffrey Huntley (@GeoffreyHuntley) <a href="https://twitter.com/GeoffreyHuntley/status/765822657463857152">August 17, 2016</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
