### ISSUE TITLE
use new rx bits in rxui v8

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/ReactiveUI#1123]
This will be the last breaking change allowed in the release, once merged we will enter into a 30 day alpha and then release v7 on NuGet.org

https://www.dotnetfoundation.org/blog/rx-net-welcome

**Comment by tiksn** [comment]
How can we access alpha/beta version? will it be preview package on nugget or in myget?

**Comment by onovotny** [comment]
Just one update...the latest bits are Rx 3.1 ;)

**Comment by oliverw** [comment]
This was not intended. Please undo. My change. Sorry about that.
