### ISSUE TITLE
ViewModel inheritance

### ISSUE THREAD

**Issue by duyduong** [reactiveui/ReactiveUI#1130]
Hi, I am new to ReactiveUI and Xamarin Forms. I have a question that can I create a BaseViewModel class as super class for all other ViewModels to inherit?

At first my project run fine without ViewModel inheritance, but there's a lot of boiler plate code so I decided to create a BaseViewModel class. Then my application stop running, the bootstrapper return null. Here is the my code for that:

**BaseViewModel class:**

public class BaseViewModel<M> : ReactiveObject
{
    [IgnoreDataMember]
    public IScreen HostScreen { get; protected set; }

```
[IgnoreDataMember]
protected readonly IJsonService Service = new JsonService();

[DataMember]
public M Model { get; protected set; }

[DataMember]
public int Index { get; protected set; }

public BaseViewModel(IScreen screen = null)
{
    HostScreen = screen ?? Locator.Current.GetService<IScreen>();
}

public BaseViewModel(M model, IScreen screen = null)
{
    HostScreen = screen ?? Locator.Current.GetService<IScreen>();
    Model = model;
}

public BaseViewModel(M model, int index, IScreen screen = null)
{
    HostScreen = screen ?? Locator.Current.GetService<IScreen>();
    Model = model;
    Index = index;
}
```

}

**ListViewModel class:**

public class ListViewModel<M, VM> : BaseViewModel<M>
{
    [DataMember]
    public ReactiveList<VM> ListItemsSource { get; protected set; }

```
[IgnoreDataMember]
VM selectedItem;

[DataMember]
public VM SelectedItem
{
    get { return selectedItem; }
    set { this.RaiseAndSetIfChanged(ref selectedItem, value); }
}

public ListViewModel(IScreen screen = null) : base(screen)
{
    Init();
}

public ListViewModel(M model, IScreen screen = null) : base(model, screen)
{
    Init();
}

protected virtual void LoadSource()
{
}

protected virtual void OnSelectedItemChanged(VM cellViewModel)
{
}

void Init()
{
    // handle for selected item changed
    this.WhenAnyValue(vm => vm.SelectedItem)
        .Where(x => x != null)
        .Subscribe(OnSelectedItemChanged);

    // loading source for list view
    LoadSource();
}
```

}

**HomeViewModel class:**

[DataContract]
public class HomeViewModel : ListViewModel<Model, HomeMenuCellViewModel>, IRoutableViewModel
{
    [IgnoreDataMember]
    public string UrlPathSegment
    {
        get { return "Home"; }
    }

```
public HomeViewModel(IScreen screen = null) : base(screen)
{
}

protected override void LoadSource()
{
    var menuItems = Service.GetHomeMenus();
    ListItemsSource.AddRange(menuItems.Select((x, i) => new HomeMenuCellViewModel(x, i)));
}

protected override async void OnSelectedItemChanged(HomeMenuCellViewModel cellViewModel)
{
    var model = cellViewModel.Model;
    var navigator = HostScreen.Router.Navigate;
    if (model.Type == HomeMenuType.Information)
        await navigator.ExecuteAsync(new InformationViewModel(HostScreen));
    else
        await navigator.ExecuteAsync(new TabViewModel(HostScreen));

    SelectedItem = null;
}
```

}

[DataContract]
public class HomeMenuCellViewModel : BaseViewModel<HomeMenuItem>
{
    public HomeMenuCellViewModel(HomeMenuItem model, int index, IScreen hostScreen = null) : base(model, index, hostScreen)
    {
    }
}

**AppDelegate class:**

public AppDelegate()
{
    // initialize app state
    RxApp.SuspensionHost.CreateNewAppState = () => {
        return new AppBootstrapper();
    };
}

public override bool FinishedLaunching(UIApplication app, NSDictionary options)
{
    StyleAppearance();

```
Forms.Init();
RxApp.SuspensionHost.SetupDefaultSuspendResume();

suspendHelper = new AutoSuspendHelper(this);
suspendHelper.FinishedLaunching(app, options);

window = new UIWindow(UIScreen.MainScreen.Bounds);
var bootstrapper = RxApp.SuspensionHost.GetAppState<AppBootstrapper>(); // bootstrapper is null when using with inheritance

window.RootViewController = bootstrapper.CreateMainPage().CreateViewController();
window.MakeKeyAndVisible();

return true;
```

}

Is there any special to setup a ViewModel inheritance? If can, please give me an example. I am using ReactiveUI 6.5.

Thanks

**Comment by PureWeen** [comment]
This shouldn't really have any effect on anything. Especially at the VM layer.  I have basically the same kind of inheritance and it works fine. My guess is that there's some other exception happing in the instantiation of the bootstrapper or something else that changed when you made the switch which is causing the issue.  Just moving things into a base class shouldn't cause RxUI to care..

What if you just replace 
```
var bootstrapper = RxApp.SuspensionHost.GetAppState<AppBootstrapper>(); 
```

with
```
var bootstrapper = new AppBootStrapper(); 
```

All App state really is is some serializable object you can use to store your app state into... For example in my application I just instantiate the bootstrapper and then use some simple POCO class for GetAppState
