### ISSUE TITLE
ReactiveUI Meeting Minutes - 8th of July 2016

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/ReactiveUI#1132]
# In attendance
- Paul Betts
- Brendan Forster
- Kent Boogart
- Oren Novotny
- Geoffrey Huntley
- Dennis Daume
- Michael Stonis
# With Apologies
- Paul Betts, as we bait and switched him with the promise of a social occasion with beer.
# The Plan
## Reactive Extensions
- We will be upgrading to the latest version of Reactive Extensions in RxUI and all sister projects.
- Upgrading to latest version of Reactive Extensions is a breaking change and merits bumping the major.
  - Strong naming key is different and this will affect WPF applications that are strongly signed.
  - Using the new bits means migrating the project to netstandard.
## SemVer
- Oren proposed that we adopt the .NET SemVer guidelines (which are also used by the new Rx bits) and there were no objections. We will move forward and adopt https://docs.microsoft.com/en-us/dotnet/articles/core/versions/index#semantic-versioning for ReactiveUI and all sister projects. - https://github.com/reactiveui/ReactiveUI/issues/1134
### v6.6
- We will be doing patch release of v6 which fixes minor issues that are a hindrance to getting up and started. For example, fixing the `splat must be installed before reactiveui` packaging issue.
### Regular Standups

After v6.6 is out, start having regular standups alternating between morning pst and evening pst.
- Will be managed/scheduled via https://github.com/reactiveui/meetups
- Watch the repository to get notifications from GitHub, in GitHub and via email.
- We will use Google Hangouts and the standups will be recorded.
### v7

Once we have upgraded all of the sister projects (as an exercise in learning more about netstandard):
- Upgrade Splat to netstandard and add ci (https://github.com/paulcbetts/splat/issues/140)
- Upgrade Akavache to new Rx and netstandard and add ci (https://github.com/akavache/Akavache/pull/315)
- Upgrade Refit to netstandard and add ci https://github.com/paulcbetts/refit/issues/249
- Upgrade RxUI to new Rx - https://github.com/reactiveui/ReactiveUI/issues/1123
- Release v7 (but only after xamarin tooling for netstandard has improved) - https://github.com/reactiveui/ReactiveUI/pull/850
## Xamarin.Forms
- Still does not have a view lifecycle hook, someone should PR it into Xamarin.Forms now that it is open source. -  https://github.com/reactiveui/ReactiveUI/issues/1133

**Comment by ghuntley** [comment]
Version 6.6 ended up being Version 6.5.1. This release contains the exact same binaries as v6.5.0 but resolves a nuspec metadata version definition which was preventing the installation of ReactiveUI into portable class libraries that target Profile259.

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">.<a href="https://twitter.com/ReactiveXUI">@ReactiveXUI</a> v6.5.1 has been released. Resolves install into Profile259 ie UWP/XamForms. Same binaries as v6.5.0. <a href="https://t.co/gBjxHQxsjZ">pic.twitter.com/gBjxHQxsjZ</a></p>&mdash; Geoffrey Huntley (@GeoffreyHuntley) <a href="https://twitter.com/GeoffreyHuntley/status/765822657463857152">August 17, 2016</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by ncthbrt** [comment]
When you mention `We will be upgrading to the latest version of Reactive Extensions in RxUI and all sister projects.` does that imply that you will start using the `System.Reactive` instead of the `Rx.Net` package?
