### ISSUE TITLE
Xamarin.Forms does not have a view lifecycle/activation hook, someone should PR it into Xamarin.Forms

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/ReactiveUI#1133]
Xamarin Forms still does not have a view lifecycle/activation hook, someone should PR it into Xamarin.Forms now that it is open source. Kent has the details and can act as a mentor for anyone whom wishes to help make this happen.

If you want to make self-contained reactive views with RxUI prior to the XF issue being addressed, you're not ​_completely_​ dead in the water - see https://gist.github.com/kentcb/d8f310a4db40cc6833c5df48fa2de31a (for v7 upwards)

**Comment by marukami** [comment]
There is an activity Rx lifecycle hook in Java from Trello https://github.com/trello/RxLifecycle and something similar from Airbnb https://github.com/airbnb/RxGroups. 

Frameworks like https://github.com/bluelinelabs/Conductor use the activity lifecycle callback. Such as https://github.com/bluelinelabs/Conductor/blob/557e4c2122a145c44be7a3a51945174c02489b8c/conductor/src/main/java/com/bluelinelabs/conductor/internal/LifecycleHandler.java

**Comment by MelbourneDeveloper** [comment]
This is a big issue. Pages have OnAppearing, but Views don't. How are we supposed to know when the control put on screen?

**Comment by kentcb** [comment]
See also: https://forums.xamarin.com/discussion/84510/proposal-improved-life-cycle-support

**Comment by kentcb** [comment]
@MelbourneDeveloper btw, the only recourse I have found is to forward life cycle events from the host page to any views within it that need to activate/deactivate. It's a bit annoying, but it works. Of course, we want to improve the story _a lot_ moving forward, hence the XF proposal.

**Comment by MelbourneDeveloper** [comment]
I'm going to use the OnParentSet method which sucks but will probably do the job until this is fixed.

**Comment by ghuntley** [comment]
Microsoft announced at build they are adding these hooks into XF.

**Comment by glennawatson** [comment]
@PureWeen What's the status on this one?

**Comment by PureWeen** [comment]
Unfortunately we weren't able to get this into 4.0 because the implementation wasn't quite right

I have parts of that work accomplished here for shell
https://github.com/xamarin/Xamarin.Forms/pull/6527

This takes a couple steps forward with setting up Appearing to actually represent Appearing opposed to Appeared.  Once that's in I'm hoping to propagate that down to the View level then work on appeared.  

Out of curiosity would you make use of an Appeared event at all? 

It seems like for MVVM Appearing is most important.

**Comment by ChrisPulman** [comment]
As Xamarin is no longer supported I am closing this issue
