### ISSUE TITLE
Visual Studio 2015 (update 3) hang out when select to this.WhenAll

### ISSUE THREAD

**Issue by lyquocnam** [reactiveui/ReactiveUI#1135]
![image](https://cloud.githubusercontent.com/assets/8347826/16692887/fcee3f32-455c-11e6-9872-c1cfb14b42af.png)

**Comment by paulcbetts** [comment]
Please file a Connect bug

**Comment by kentcb** [comment]
@lyquocnam I have already reported this exact issue to Microsoft and provided them with a crash dump. I did it via the MVP email list, so I don't have a direct link for you. However, I will update this thread as I receive more info.

**Comment by kentcb** [comment]
@lyquocnam Install this update to fix the Intellisense freeze issue:

![vs update](https://cloud.githubusercontent.com/assets/1901832/16796629/db0d75e4-4922-11e6-9c8c-4a4f05a6cd8c.png)
