### ISSUE TITLE
Silverlight does not installed

### ISSUE THREAD

**Issue by kronic** [reactiveui/ReactiveUI#1136]
Severity	Code	Description	Project	File	Line	Source	Suppression State
Error		Could not install package 'Splat 1.0.0'. You are trying to install this package into a project that targets 'Silverlight,Version=v5.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0	IntelliSense

**Comment by moswald** [comment]
Splat does not support Silverlight. Either you are trying to use RxUI in a Silverlight project, or you have a PCL that includes Silverlight support. The fix is to stop targeting Silverlight.
