### ISSUE TITLE
Xamarin Android project: Build is broken.

### ISSUE THREAD

**Issue by SpiegelSoft** [reactiveui/ReactiveUI#1137]
When I add reactiveui or reactiveui-androidsupport to a Xamarin Android project, it breaks the build. The error message reads "Unable to resolve interface type 'Splat.IEnableLogger'. Are you missing an assembly reference?".

I note that the version of Splat that is installed by default is 1.0.0, not 1.6.2, but upgrading the Splat NuGet package doesn't help.

Running Visual Studio 2015, Update 3

![image](https://cloud.githubusercontent.com/assets/557824/16825933/f2d19dd8-4970-11e6-89a2-dc221fbf77cd.png)

**Comment by ghuntley** [comment]
Out of interest, what happens if you install splat first, then install reactiveui?

**Comment by SpiegelSoft** [comment]
Still the same result.

**Comment by Qonstrukt** [comment]
They're hard at work on version 7 which is nearing completing judging from https://github.com/reactiveui/ReactiveUI/issues/1123.

**Comment by PureWeen** [comment]
I'm pretty sure I had this issue once as well and resolved by manually adding the dll from the packages folder

packages\Splat.1.6.2\lib\monoandroid\Splat.dll

Is that the DLL that your android project is referencing?

As far as reactiveui-androidsupport 

The nuget one is a wee bit old and though it does have some helpful extension methods it lacks support for some of the newer base classes in android. 

Whereas the new version (coming soon) does
https://github.com/reactiveui/ReactiveUI/tree/rxui7-master/src/ReactiveUI.AndroidSupport

It's a great library but right now you've caught it between a shift from the old to the new hotness :-)

**Comment by SpiegelSoft** [comment]
Excellent news about Version 7. I'll check the dll later today.

**Comment by SpiegelSoft** [comment]
I context-switched and went away for a couple of weeks.

Coming back to it, I should simply have read the error message. It was trying to set an internal string called "library_name" to my copy of "library_name", and the build was breaking because it couldn't find "library_name" in my Android resource strings. I added one and the build magically fixed itself.

Can't wait for Version 7. :)
