### ISSUE TITLE
Support for Gtk# and mono

### ISSUE THREAD

**Issue by oscarvarto** [reactiveui/ReactiveUI#1138]
Hi!

I really liked to use ReactiveUI and WPF for a desktop application (and that works on Windows desktop only). Currently, there is no support for GTk#. How difficult is it to add support for Gtk#?

Would code be similar to that for Windows Forms? Maybe I could get some idea about how to do it by reading that code.

Any suggestions/guidance is appreciated.

**Comment by vector-man** [comment]
I second this! It would be great!

**Comment by ghuntley** [comment]
![image](https://user-images.githubusercontent.com/127353/27458976-4f7c82b8-57ef-11e7-966b-b779268bd003.png)

**Comment by ghuntley** [comment]
![image](https://user-images.githubusercontent.com/127353/27459009-7eb04646-57ef-11e7-88b2-cd6551443a8f.png)
