### ISSUE TITLE
Reference Rx 3.0.0 NuGet packages

### ISSUE THREAD

**Issue by eggapauli** [reactiveui/ReactiveUI#1139]
`Rx-Main` and all the other _old_ packages of Reactive Extensions are unlisted for some time now. Could you update the RxUI NuGet packages to reference `System.Reactive`?

**Comment by ghuntley** [comment]
Howdy @eggapauli this is planned for v7.

**Comment by ghuntley** [comment]
Howdy @eggapauli this is planned for v7. See https://github.com/reactiveui/ReactiveUI/issues/1132 and https://github.com/reactiveui/ReactiveUI/issues/1123

**Comment by oliverw** [comment]
v7 is out but still references the old Rx Packages. What's the current situation here?

**Comment by eggapauli** [comment]
#1123 now says it's planned for v8 :-(

**Comment by ericsink** [comment]
But my understanding is that v8 is mostly just v7+netstandard. In other words, netstandard is not waiting for a long dev cycle with a bunch of new features. Or so I've heard.

**Comment by shiftkey** [comment]
Due to the minor API churn that `System.Reactive` 3.0 introduced (it was more about the infrastructure and getting things into the foundation), and the fact that RxUI 7.0 was already so close, it was decided that it was easier to leave that out for the next major release.

And yes, with all the infrastructure work now in place we are aiming to keep the RxUI 8 release cycle focused.

**Comment by fschwiet** [comment]
+1

**Comment by Dunge** [comment]
+1

I was cleaning up our dependencies and wondered why we were using a deprecated package, trying to uninstall Rx-Core to update to use System.Reactive.Core until I realized ReactiveUI is the one lagging behind.

**Comment by masaeedu** [comment]
So is there a workaround for this, or do I need to go change everything to full-framework throughout the transitive closure of my dependency graph to be able to use ReactiveUI?

**Comment by robsonj** [comment]
I'd also be interested to know if there is any work around please.

**Comment by masaeedu** [comment]
@robsonj I looked around a bit more and there's a myget feed with
prerelease packages. I'm not at my computer right now, but you should be
able to find the url if you dig around the issues.

**Comment by masaeedu** [comment]
You can get ReactiveUI 7.5 alpha, which is .NET Standard compatible, here: https://www.myget.org/F/reactiveui/api/v3/index.json

**Comment by dboris** [comment]
I'm running into the following issue with ReactiveUI 7.5 alpha:

> Circular dependency detected 'reactiveui 7.5.0-alpha0032 => System.Reactive 3.1.0 => System.Reactive.PlatformServices 4.0.0-preview00001 => System.Reactive 3.1.0'.

**Comment by kentcb** [comment]
@dboris [relevant discussion on Slack](https://reactivex.slack.com/archives/C02AJB872/p1498463902405240).
