### ISSUE TITLE
Nuget package for Xamarin.Forms targets too low version of Splat

### ISSUE THREAD

**Issue by awesomowski** [reactiveui/ReactiveUI#1141]
Currently when trying to install ReactiveUI in Xamarin.Forms application installation fails and nuget returns

`Could not install package 'Splat 1.0.0'. You are trying to install this package into a project that targets 
'.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are 
compatible with that framework. For more information, contact the package author`

This can be locally bypassed through installation of a new version of Splat (works on splat.1.6.2) before ReactiveUI or by manually switching nuget to use newest versions of dependencies.

On a side note, Splat doesn't seem to be officialy supporting Xamarin.Forms, while RUI does.

**Comment by ghuntley** [comment]
Howdy @awesomowski we have pushed v6.5.1 to NuGet which resolves installation into portable class libraries that target Profile259. This release contains the exact same binaries as v6.5.0 but resolves a nuspec metadata version definition which was causing this problem.

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">.<a href="https://twitter.com/ReactiveXUI">@ReactiveXUI</a> v6.5.1 has been released. Resolves install into Profile259 ie UWP/XamForms. Same binaries as v6.5.0. <a href="https://t.co/gBjxHQxsjZ">pic.twitter.com/gBjxHQxsjZ</a></p>&mdash; Geoffrey Huntley (@GeoffreyHuntley) <a href="https://twitter.com/GeoffreyHuntley/status/765822657463857152">August 17, 2016</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
