### ISSUE TITLE
ReactiveUI 6.5.1

### ISSUE THREAD

**Issue by sickboy** [reactiveui/ReactiveUI#1145]
What is it?

(Can't find release notes, nor related commits)

**Comment by PureWeen** [comment]
https://github.com/reactiveui/ReactiveUI/releases/tag/6.5.1

**Comment by sickboy** [comment]
thanks.. hmm, wondering if I overlooked it, or if this just got ninja'd in :D

**Comment by shiftkey** [comment]
@sickboy it's fairly recent, yes https://github.com/reactiveui/ReactiveUI/issues/1132#issuecomment-240346193
