### ISSUE TITLE
Wrong folder name in lib folder of nuget package

### ISSUE THREAD

**Issue by Evangelink** [reactiveui/ReactiveUI#1146]
**Do you want to request a *feature* or report a *bug*?**
Bug report.

**What is the current behavior?**
Windows and WindowsPhone folders under the lib folder have an incorrect name:
Portable-Net45%2BWin8%2BWP8%2BWPA81
Portable-Win81%2BWPA81

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**What is the expected behavior?**
Folders shoud be named as follow:
Portable-Net45+Win8+WP8+WPA81
Portable-Win81+WPA81

**What is the motivation / use case for changing the behavior?**

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the latest stable and snapshot (http://docs.reactiveui.net/en/contributing/snapshot/index.html) versions.**
Works properly with ReactiveUI 6.5.0, bugs only affects 6.5.1. It seems to be an encoding issue but I haven't looked to what changed between 6.5.0 and 6.5.1.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by Evangelink** [comment]
Any news on this?

**Comment by kentcb** [comment]
thanks for reporting @Evangelink. I've created 6.5.2 packages to fix this issue, and they will be published ASAP once the core team has agreed to do so.

**Comment by ghuntley** [comment]
6.5.2 has been pushed, thanks for the bug report @Evangelink 

https://github.com/reactiveui/ReactiveUI/releases/tag/6.5.2
