### ISSUE TITLE
Move documentation to GitHub-Wiki

### ISSUE THREAD

**Issue by escamoteur** [reactiveui/ReactiveUI#1163]
Hi,

I don't know if this is the right place to ask, but I think everyone knows that the documentation is far behind the framework which makes it REALLY difficult to get started with RxUI.

I would like to contribute to the documentation while learning more, but I think storing the documentation in a repository does not encourage people to work on it.

The nancyfx project has it's doc in the wiki and everyone can contribute, which works great.

So why not do it that way with RxUI?

Best
Thomas

**Comment by ghuntley** [comment]
Howdy @escamoteur. 

I've thought and am actively considering hiring a technical writer using funds from OpenCollective to help pull up the quality once we have the fundamentals covered. In the last couple months documentation has been moved out and integrated into the new website (which has edit links on the right hand side). Pull-requests have been landing as a result of this migration so it's working. Additionally we now have API documentation.
