### ISSUE TITLE
Installing reactive.testing 6.5.0 on reactive UI 6.5.2 with nuget in Visual Studio 2015 Fail

### ISSUE THREAD

**Issue by drdran** [reactiveui/ReactiveUI#1172]
I'm newbie in reactive ui and rx extensions, and I want to begin a new project based un it for study.

So I've installed the last stable reactiveui that was the 6.5.2 version, but I want to install the reactiveui.testing packages that have the 6.5.0 version as strict dependece.

Do you suggest me to use the 6.5.0 for all packages? But why the package *.testing is not compatible with 6.5.2? It's a dependecies bug?

Regards

Franco

**Comment by shiftkey** [comment]
@ghuntley should we do a `6.5.3` release here or do you have access to the bits to just publish `reactiveui-testing`?

**Comment by drdran** [comment]
I think that is very strictly to use only the = dipendence.
