### ISSUE TITLE
Error install reactiveui-xamforms on WindowsPhone 8.1 profile(111) PCL project Xamarin

### ISSUE THREAD

**Issue by alexflyto** [reactiveui/ReactiveUI#1173]
Report a bug

**On Xamarin PCL project profile 111 and WindowsPhone 8.1, in Nuget, on try to install the reactiveui-xamforms extension this error appears:**

reactiveui-xamforms 6.5.00
    Could not install package 'reactiveui-xamforms 6.5.0'. 
    You are trying to install this package into a project that targets 'WindowsPhoneApp,Version=v8.1', 
    but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**AND on I try to update to ReactiveUI version 7 this error apears:**

reactiveui-xamforms 7
    Could not install package 'reactiveui-xamforms 7.0.0.1474320879'. 
    You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', 
    but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Someone has a solution for these errors?**

Thank you

**Comment by ghuntley** [comment]
Thanks for the detailed bug report and testing on v7. WPA81 _should work_ doubt it's an issue on your side; let me investigate.

**Comment by ghuntley** [comment]
Thanks for the solid repro @alexflyto. This has been fixed and `reactiveui-xamforms.7.0.0-alpha0477.nupkg` is now available on MyGet.
