### ISSUE TITLE
The main page example is outdated with 7.0 release

### ISSUE THREAD

**Issue by harvinders** [reactiveui/ReactiveUI#1200]
The search example at http://reactiveui.net/ should be updated with the APIs from the latest version.

**Comment by shiftkey** [comment]
@harvinders the source is here - https://github.com/reactiveui/reactiveui.github.io/blob/master/index.html - would you be interested in submitting a pull request?

**Comment by harvinders** [comment]
I would be more than happy, once I resolve some issues. I am having trouble with exception currently though. Please see the [stackoverflow link](http://stackoverflow.com/questions/40678349/reactiveui-command-is-not-invoked-after-the-command-implementation-throws-an-exc )

**Comment by GiusepeCasagrande** [comment]
Shouldn't this be moved on the Documentation Repository?
