### ISSUE TITLE
Added override to Interaction.RegisterHandler() with IScheduler parameter

### ISSUE THREAD

**Issue by aalmada** [reactiveui/ReactiveUI#1205]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

Handler is executed in the same thread as the call for Handle().

**What is the expected behavior?**

Execute the handler on the scheduler/thread specified by the IScheduler parameter.

**What is the motivation / use case for changing the behavior?**

Handler usually interact with UI elements, the call for Handle() may be inside a callback from a third-party library not using Rx or Tasks. The parameter makes simple to guarantee that the handler is executed in the correct thread, usually the UI thread.

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the latest stable and snapshot (http://docs.reactiveui.net/en/contributing/snapshot/index.html) versions.**

RxUI 7.0.0

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by shiftkey** [comment]
@aalmada do you have an example snippet of the code you're using, to go with this excellent write up?

**Comment by aalmada** [comment]
@shiftkey Unfortunately I don't. I've trying for several days to make this work. It's very frustrating.
