### ISSUE TITLE
Improve error message: Unsupported expression type: 'x'

### ISSUE THREAD

**Issue by kentcb** [reactiveui/ReactiveUI#1209]
**Do you want to request a *feature* or report a *bug*?**

Enhancement.

**What is the current behavior?**

When an unsupported expression type appears within an expression, a `NotSupportedException` is thrown with message:

> Unsupported expression type: 'type'

This is not helpful in understanding and solving the problem.

**What is the expected behavior?**

The exception message should probably include the expression that is causing the problem, along with an indication of what normally causes this. For example, the following code:

```C#
this.WhenAnyValue(x => this.Foo)
```

Triggers the exception with an expression type of "Constant". We should probably trap this case and provide a helpful clue as to why the exception is probably being thrown.

**What is the motivation / use case for changing the behavior?**

Widen the pit of success.

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the latest stable and snapshot (http://docs.reactiveui.net/en/contributing/snapshot/index.html) versions.**

RxUI 7.

**Comment by ghuntley** [comment]
There's still time to ship this in v7 as a minor otherwise it'll be in v8 which is netstandard.

**Comment by glennawatson** [comment]
Is this still an issue @kentcb -- https://twitter.com/kent_boogaart/status/1145907846451585030

**Comment by MovGP0** [comment]
I wrote 
```csharp
        this.WhenAnyValue(vm => vm.Value == vm.OriginalValue)
                .Select(_ => this)
                .ObserveOn(RxApp.MainThreadScheduler)
                .SubscribeOn(RxApp.MainThreadScheduler)
                .Subscribe(vm => HasValueChanged = vm.Value == vm.OriginalValue)
                .DisposeWith(d);
```
instead of 
```csharp
        this.WhenAnyValue(vm => vm.Value, vm => vm.OriginalValue)
                .Select(_ => this)
                .ObserveOn(RxApp.MainThreadScheduler)
                .SubscribeOn(RxApp.MainThreadScheduler)
                .Subscribe(vm => HasValueChanged = vm.Value == vm.OriginalValue)
                .DisposeWith(d);
```
by accident and got this error message. The message confused me, thinking that the error was in the subscribe statement for a few seconds.
