### ISSUE TITLE
The type initializer for 'ReactiveUI.CreatesCommandBindingViaEvent' threw an exception.

### ISSUE THREAD

**Issue by inyman** [reactiveui/ReactiveUI#1211]
I'm getting this error when running nunit tests on mac.

System.TypeInitializationException : The type initializer for 'ReactiveUI.RxApp' threw an exception.
  ----> System.TypeInitializationException : The type initializer for 'ReactiveUI.CreatesCommandBindingViaEvent' threw an exception.

```
[Test]
public void Fails()
{
  (new TestScheduler()).With(sched => {});
}

or 
[Test]
public void Fails()
{
  TestUtils.WithScheduler(new TestScheduler());
}
```
packages.config
```
...
<package id="reactiveui" version="7.0.0" targetFramework="net45" />
<package id="reactiveui-core" version="7.0.0" targetFramework="net45" />
<package id="reactiveui-testing" version="7.0.0" targetFramework="net45" />
<package id="Rx-Testing" version="2.2.5" targetFramework="net45" />
...
```

**Comment by inyman** [comment]
Ah ok so in unit test this is the line that throws exception, so am i missing some initialization for unit tests ?

RxApp.MainThreadScheduler


stackTrace	"  at ReactiveUI.Registrations+<>c.<Register>b__0_7 () [0x00000] in <d13e35ba0bd44f5faf701228ab8b1d28>:0 \n  at ReactiveUI.DependencyResolverMixins+<>c__DisplayClass0_0.<InitializeReactiveUI>b__0 (System.Func`1[TResult] f, System.Type t) [0x00000] in <d13e35ba0bd44f5faf701228ab8b1d28>:0 \n  at ReactiveUI.Registrations.Register (System.Action`2[T1,T2] registerFunction) [0x00149] in <d13e35ba0bd44f5faf701228ab8b1d28>:0 \n  at ReactiveUI.DependencyResolverMixins.InitializeReactiveUI (Splat.IMutableDependencyResolver resolver) [0x00028] in <d13e35ba0bd44f5faf701228ab8b1d28>:0 \n  at ReactiveUI.RxApp+<>c.<.cctor>b__0_0 () [0x0000d] in <d13e35ba0bd44f5faf701228ab8b1d28>:0 \n  at Splat.Locator.RegisterResolverCallbackChanged (System.Action callback) [0x00039] in <66ec575cc13f4eaea0cbad3add11aa6e>:0 \n  at ReactiveUI.RxApp..cctor () [0x00010] in <d13e35ba0bd44f5faf701228ab8b1d28>:0 "	string

**Comment by ghuntley** [comment]
What sort of class library is the unit test located in? 

- net45?
- mac45?
- pclprofile¿?

**Comment by inyman** [comment]
https://gist.github.com/inyman/ebc654f129b2eda0e00770a98218eeca

Thanks for quick response btw

**Comment by inyman** [comment]
Any ideas what I'm doing wrong ?

**Comment by PureWeen** [comment]
Not sure

your Splat version looks older maybe that's causing problems?  Update it to 1.6.2?

I tried a quick NUNIT project against .net45 here
https://github.com/PureWeen/RxUI7NunitNET45

and it seems to run fine

Maybe enable first chance exceptions as well see if that reveals more things?

**Comment by inyman** [comment]
I checked out your project and still fails for me. Running inside xamarin studio

**Comment by PureWeen** [comment]
![capture](https://cloud.githubusercontent.com/assets/5375137/21033151/b3bbe1f2-bd6b-11e6-978b-0eeb166f02cf.PNG)


I'm not really sure then when I run it in xamarin studio it compiles and passes for me just fine

Maybe something is messed up with your nuget cache of packages?

http://stackoverflow.com/questions/30933277/how-to-clear-nuget-package-cache-using-command-line

**Comment by inyman** [comment]
Hm still no luck, you're using mac ?

**Comment by inyman** [comment]
Looks like this is throwing exception   Locator.CurrentMutable.InitializeReactiveUI();

**Comment by inyman** [comment]
ok works on windows for me as well, would be cool to figure out what's the problem with mac

**Comment by PureWeen** [comment]
My guess with that would be from it being net45 so it's not going to load on iOS. Like I'm assuming the ReactiveUI net45 dll is full framework net45 which isn't going to be able to bootstrap up into iOS...

**Comment by inyman** [comment]
hm could i target some other framework ?

**Comment by PureWeen** [comment]
Yea most likely. Personally I haven't done a lot with unit tests in the context of iOS but if you look at the RxUI source there's an iOS based test project against xUnit.  If you just create an iOS class library that might possibly do what you need. The ReactiveUI iOS test project looks to just be a class library that targest Xarmin iOS.    I've only ever really ran unit tests in a windows environment and then I just use the Xamarin UI Test features to run UI tests through the emulator or against devices...    It'd probably be more correct for me to run the tests all the places :-) but just haven't really

**Comment by inyman** [comment]
Hm. Going without TDD any further is not an option for me. So either i switch to Windows (not likely) or i find a way to test it or switch to some other lib (if any)

**Comment by PureWeen** [comment]
Well that's not really what I was referring to just that I hadn't done it on iOS before.. The ReactiveUI source runs TDD against iOS. If you grab the source you'll see the project there. I've never messed with it but I'm assuming it works and runs on iOS :-) . If you create a Xamarin iOS library I'm sure you'll be able to add Xamarin iOS libraries to it plus a Xamarin iOS compatible TDD FW and it'll work.

**Comment by inyman** [comment]
Extracted logic that's executed within observable to protected method and i unit test that for now , tried mono mac, ios lib, changing csproj to Xamarin.Mac20 etc etc nothing worked so this is good for now

**Comment by Amnysia** [comment]
I have exactly the same issue.
I tried :
- Create a Xamarin.Mac library and add the Nunit test there. Switch the ReactiveUI and Splat to Xamarin.Mac20 and MonoMac.
- Create a Xamarin.Ios library and add the Nunit test there. Switch the ReactiveUI and Splat to Xamarin.ios10 and monotouch.
- Create a normal Nunit Xamarin lib Switch the ReactiveUI and Splat to Xamarin.Mac20 and MonoMac.

Also tried with net45 as path but nothing seems to works. It's also a big issue for us as we really need Unit Tests. If we cannot find a way to make it work we will need to swicth to an other library for our bindings. It's sad, we really like the way ReactiveUI is putting everything togheter.

Hope someone will be able to help us.Thanks in advance.

**Comment by inyman** [comment]
@Amnysia if you're testing domain logic outside ui i went for this approach until its fixed
```
protected override IObservable<Game> BuildUseCaseObservable(object[] args) {
      return Observable.Create<Game>(async observer => {
        Game newGame = await ExecuteUseCase();

        observer.OnNext(newGame);
        observer.OnCompleted();

        return Disposable.Empty;
      });
    }

    internal async System.Threading.Tasks.Task<Game> ExecuteUseCase() {
}
```

My unit tests are testing ExecuteUseCase logic , maybe this helps

**Comment by PureWeen** [comment]
With iOS have you tried the Xamarin Unit Test template projects? Or are you just running it straight from a class library?

I'm pretty sure the iOS tests have to be ran from inside a simulator which is what they do here
https://developer.xamarin.com/guides/ios/deployment,_testing,_and_metrics/touch.unit/

Which should then let you run specific tests

I'd test it out more but the latest Xamarin release to iOS seems to have horked my setup  on there :-(

**Comment by PureWeen** [comment]
Alright i had to set Link to Link SDK  only and now I'm back to working

But yea.. If you use the link I posted above then you can run unit tests. Basically it creates a little iOS app test runner and then you can kick off the tests inside the simulator

I'm not sure if there's an easier way to make it work on the iOS side of things :-/   I'm thinking once RxUI gets all updated to netstandard and nunit 3.5 gets better integration with xam studio then maybe you'll be able to just run those from a simple test runner.

**Comment by Amnysia** [comment]
Yeah i would like to avoid using the iOS test runner because we need the tests to be ran by our integration server. 
Except if i'm wrong i don't know any way to automate it.
@inyman So yes i used a ios library not a ios test library.


But ok, waiting for to be fixed, i will certainly use this workaround.

Thanks for your support. I hope this will be fixed quickly as it's very problematic.

**Comment by PureWeen** [comment]
I'm thinking once RxUI goes to netstandard then this might work but I still think the problem here isn't really a defect of RxUI but more about how platform specific code won't run without the simulator. @inyman's extracted code works because all of that isn't platform specific. That's all code that will map to an actual mono implementation when ran outside of the simulator. But once you start accessing things that are only available to iOS then i'm pretty sure you need to run them on a simulator...  

For example this test for me fails when ran with an iOS library against nunit
```
[Test]
		public void Fails5()
		{
			ICommand test;
		}
```
with
 
```
 at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
```


The Net45 implementation probably fails because it references RoutedEventArgs which doesn't exist in the ios world at all

The Mac one though I'm not super clear on why that fails but I'm sure it's something similar

**Comment by inyman** [comment]
Well true, my unit test project doesn't reference any android / ios libs. How i'm structuring it at the moment is that all domain logic is platform independent and running under plain nunit and i will have ui tests for running in the cloud / emulator.
