### ISSUE TITLE
ReactiveList tracks ItemChanged after Remove is called if change is made in Subscribe handler for ItemsRemoved or Changed

### ISSUE THREAD

**Issue by utahking** [reactiveui/ReactiveUI#1213]
I love ReactiveUI, still relatively new to to library, but it is simplifying my workflow tremendously!

**Do you want to request a *feature* or report a *bug*?** 
Bug or Feature (not sure if it is intended behavior)

**What is the current behavior?**
Making a change to a removed item in the Subscribe Handler for either Changed or ItemRemoved still fires an ItemChanged event. I would expect this to be the behavior in the Changing or BeforeItemRemoved handlers.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

```
public class KeyValue : ReactiveObject
{
	private string _value;
	public string Value
	{
		get { return _value; }
		set { this.RaiseAndSetIfChanged(ref _value, value); }
	}

	public int Key { get; set; }
}

void Main()
{
	var keyValues = new ReactiveList<KeyValue> { ChangeTrackingEnabled = true };

	//Watch for item changes and write out the key and if the item is in the list
	keyValues.ItemChanged.Select(x => x.Sender).Subscribe(x =>
	{
		Console.WriteLine($"Item: {x.Key} Changed. In List: {keyValues.Contains(x)}");
	});

	//Remove Item, updating value when removed
        // Remove the Changed handler below and uncomment the next line to verify second scenario
        // keyValues.ItemsRemoved.Subscribe( x => x.Value = string.Empty);	

	keyValues.Changed.Subscribe(x =>
	{
		if(x.Action != System.Collections.Specialized.NotifyCollectionChangedAction.Remove)
		 return;
		foreach (KeyValue item in x.OldItems)
		{
			item.Value = $"{item.Value} Updated";
		}
	}
	);	

	keyValues.Add(new KeyValue { Key = 1, Value = "Value 1" });
	keyValues.Add(new KeyValue { Key = 2, Value = "Value 2" });
	
	keyValues.First().Value = "Value 1 Updated";
	var keyValue2 = keyValues.First(x=>x.Key == 2);
	keyValues.Remove(keyValue2);
	keyValue2.Value = "Value 2 Updated";	
}
```

**What is the expected behavior?**
The Changed and ItemRemoved handlers should fire after the item is removed from change tracking

**What is the motivation / use case for changing the behavior?**
Being able to make Item level changes when an item is removed from a ReactiveList with Change Tracking enabled.

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the latest stable and snapshot (http://docs.reactiveui.net/en/contributing/snapshot/index.html) versions.**
ReactiveUI 7.0.0
WPF
Not tested in previous versions

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
N/A

**Comment by glennawatson** [comment]
We have dropped ReactiveList and ReactiveDerivedList in the next version of ReactiveUI and latest. Closing.
