### ISSUE TITLE
Using WhenAnyObservable on a ReactiveCommand before it is created doesn't work

### ISSUE THREAD

**Issue by nhajidin** [reactiveui/ReactiveUI#1219]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Using WhenAnyObservable on a ReactiveCommand before it is created causes nothing to happen when the command fires.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
```cs
public class MainViewModel : ReactiveObject
{
    public MainViewModel()
    {
        count = this.WhenAnyObservable(x => x.DoIt)
            .Scan(0, (acc, _) => acc + 1)
            .StartWith(0)
            .ToProperty(this, x => x.Count);

        DoIt = ReactiveCommand.Create(() => { });
    }

    public ReactiveCommand<Unit, Unit> DoIt { get; protected set; }

    ObservableAsPropertyHelper<int> count;
    public int Count
    {
        get { return count.Value; }
    }
}
```

I have created a repository where it works in v6.5.2:

https://github.com/nhajidin/RxUICommand

The RxUI7 branch has the code updated to the latest version:

https://github.com/nhajidin/RxUICommand/tree/RxUI7

**What is the expected behavior?**

The Count in the above code increments whenever the command is executed.

**What is the motivation / use case for changing the behavior?**

N/A

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the latest stable and snapshot (http://docs.reactiveui.net/en/contributing/snapshot/index.html) versions.**

This bug appears in ReactiveUI 7.0.0 in a WPF project on Windows 10.

It appears to works in v6.5.2.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

N/A

**Comment by kentcb** [comment]
I don't understand how this could possibly work in any version of RxUI because your `DoIt` property does not notify. Try changing it to use `RaiseAndSetIfChanged`. Re-open if you disagree.

**Comment by nhajidin** [comment]
Here's a test that shows the issue:

```cs
public class WhenAnyObservableTest
{
    public class TestViewModel : ReactiveObject
    {
        public TestViewModel()
        {
            var obs = this.WhenAnyObservable(x => x.IncrementCount)
                .Scan(0, (acc, _) => acc + 1)
                .StartWith(0);

            countBefore = obs
                .ToProperty(this, x => x.CountBefore);

            IncrementCount = ReactiveCommand.Create(() => Unit.Default);

            countAfter = obs
                .ToProperty(this, x => x.CountAfter);
        }

        public ReactiveCommand<Unit, Unit> IncrementCount { get; protected set; }

        ObservableAsPropertyHelper<int> countBefore;
        public int CountBefore => countBefore.Value;

        ObservableAsPropertyHelper<int> countAfter;
        public int CountAfter => countAfter.Value;		
    }

    [Fact]
    public async void CreateObservableUsingWhenAnyObservableBeforeReactiveCommandIsCreated()
    {
        var vm = new TestViewModel();

        Assert.Equal(0, vm.CountAfter);
        Assert.Equal(0, vm.CountBefore);

        await vm.IncrementCount.Execute();

        Assert.Equal(1, vm.CountAfter);
        Assert.Equal(1, vm.CountBefore);
    }
}
```

It fails on the line with `Assert.Equal(1, vm.CountBefore);`

**Comment by kentcb** [comment]
Like I said, the `DoIt` property is not notifying. The `WhenAny*` operators cannot possibly know when it changes unless it notifies. Try changing `DoIt` to:
```C#
private ReactiveCommand<Unit, Unit> doIt;
public ReactiveCommand<Unit, Unit> DoIt
{
    get { return doIt; }
    protected set { RaiseAndSetIfChanged(ref doIt, value); }
}
```

**Comment by nhajidin** [comment]
That does explain it but the following did work in v6.5.2.

```cs
public class MainViewModel : ReactiveObject
{
    public MainViewModel()
    {
        count = this.WhenAnyObservable(x => x.DoIt)
            .Scan(0, (acc, _) => acc + 1)
            .StartWith(0)
            .ToProperty(this, x => x.Count);

        DoIt = ReactiveCommand.Create();
    }

    public ReactiveCommand<object> DoIt { get; protected set; }

    ObservableAsPropertyHelper<int> count;
    public int Count
    {
        get { return count.Value; }
    }
}
```

**Comment by kentcb** [comment]
@nhajidin that would likely be due to the default lazy behavior of `ToProperty` in 6.5 which is now eager in 7.0. If you change your `ToProperty` call to specify `true` for the `deferSubscription` parameter, that will have the same behavior as 6.5.2. But you're really playing with fire if you rely on that for correctness, because anything that accesses `Count` ahead of `DoIt` being assigned will result in the same incorrect behavior.

Really my advice here would be to just assign `DoIt` _before_ creating `count`. That is, define your observables so that dependencies are created before dependents. This will also allow you to make `DoIt` read only.
