### ISSUE TITLE
[Feature] Create an ObservableForPropertyHolder

### ISSUE THREAD

**Issue by bradphelan** [reactiveui/ReactiveUI#1220]
**What is the current behavior?**

A developer must create an instance of ``ObservablePropertyHelper<T>`` for every property. This results in code bloat making the code less readable.

**A better solution would be to have a single object that manages the subscriptions. I've called it ``ObservablePropertyHolder<TParent>``** For example.

     public class Foo : ReactiveObject {
        ObservablePropertyHolder<Foo> _OPH;
        public Foo(IObservable<bool> isFunny){
            _OPH = new ObservablePropetyHolder<Foo>(this);
              
           isFunny.ToProperty(_OPH, p=>p.IsFunny);
           isFunny.Select(v=>!v).ToProperty(_OPH, p=>p.IsNotFunny);
        }
    
       bool IsFunny => _OPH.Value(p=>p.IsFunny);
       bool IsNotFunny => _OPH.Value(p=>p.IsNotFunny);
     }

**My current implementation is**

    public class ObservablePropertyHolder<TObj> : IDisposable
        where TObj : IReactiveObject
    {
        public TObj Source { get; set; }

        public ObservablePropertyHolder(TObj source)
        {
            Source = source;
        }

        readonly Dictionary<string, object> _Lookups = new Dictionary<string, object>();

        public void ToProperty<TRet>
        (IObservable<TRet> This,
         Expression<Func<TObj, TRet>> property,
         TRet initialValue = default(TRet),
         bool deferSubscription = false,
         IScheduler scheduler = null) 
        {
            var key = Key(property);
            var helper = This.ToProperty(Source, property, initialValue, deferSubscription, scheduler);
            _Lookups[key] = helper;
        }

        private static string Key<TRet>(Expression<Func<TObj, TRet>> property) 
            => Reflection.ExpressionToPropertyNames(property.Body);

        public TRet Value<TRet>(Expression<Func<TObj, TRet>> selector) => ((ObservableAsPropertyHelper<TRet>) _Lookups[Key(selector)]).Value;
        public TRet Value<TRet>([CallerMemberName]string key="") => ((ObservableAsPropertyHelper<TRet>) _Lookups[key]).Value;
        public void Dispose()
        {
            foreach (var lookup in _Lookups)
            {
                ((IDisposable)lookup.Value).Dispose();
            }
        }
    }

**This could be improved by integrating into ReactiveObject to achieve**

     public class Foo : ReactiveObject {
        public Foo(IObservable<bool> isFunny){                   
           isFunny.ToProperty(p=>p.IsFunny);
           isFunny.Select(v=>!v).ToProperty( p=>p.IsNotFunny);
        }  
       bool IsFunny => ReactiveValue(p=>p.IsFunny);
       bool IsNotFunny => ReactiveValue(p=>p.IsNotFunny);
     }

If this is interesting I can make a pull request. If it is of no interest I will leave it in my own code base.

**Comment by escamoteur** [comment]
What is the advantage over using ReactiveUI.Fody?

**Comment by bradphelan** [comment]
I use fody for the normal reactive properties. It's great.  I find this
neater for the driven props however . I think it's tidier but it's just a
preference.

**Comment by bradphelan** [comment]
I have a pull request pending on fody reactive ui for a code fix to convert
vanilla reactiveui props to fody ones so I guess I'm a bit inconsistent :)

**Comment by escamoteur** [comment]
I was just thinking as we have an elegant solution with Fody for this, why introduce another Object

**Comment by glennawatson** [comment]
Going to close this issue. Not probably somewhere we will go for now but thanks for the suggestion @bradphelan (sorry this took 3 years to close)
