### ISSUE TITLE
Remove UNIFIED symbol

### ISSUE THREAD

**Issue by kentcb** [reactiveui/ReactiveUI#1222]
**Do you want to request a *feature* or report a *bug*?**

Enhancement.

**What is the current behavior?**

Lots of bits of iOS/Mac code make use of a `UNIFIED` symbol such as:
```C#
#if UNIFIED
        protected ReactiveCollectionReusableView(CGRect frame) : base(frame) { }
#else
        protected ReactiveCollectionReusableView(RectangleF frame) : base(frame) { }
#endif
```

Since we have removed support for legacy iOS, all these can be cleaned up.

**What is the motivation / use case for changing the behavior?**

Cleaner code + avoid confusion.

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the latest stable and snapshot (http://docs.reactiveui.net/en/contributing/snapshot/index.html) versions.**

v7.

**Comment by escamoteur** [comment]
So I understand this correct, that only the UNIFIED implementation should kept? I think that I can do

**Comment by Qonstrukt** [comment]
🎉
