### ISSUE TITLE
Unable to upgrade reactiveui-xaml and Splate nugets to latest version

### ISSUE THREAD

**Issue by dasha-finch** [reactiveui/ReactiveUI#1223]
In our project we use these 3 nuget packages:

- reactiveui-core (7.0.0)
- reactiveui-xaml (2.3.2)
- Splat (1.6.2)

Once I upgraded reactiveui-core to the latest version 7.0.0, I can no longer upgrade the remaining two to latest. I keep getting an error "Unable to find a version of 'Splat' that is compatible with 'reactiveui-core 7.0.0 constraint: Splat (>= 1.4.0 && < 2.0.0)'"

**Comment by HumzaKhan** [comment]
Try updating reactiveui-core in the last perhaps?

**Comment by dasha-finch** [comment]
I have downgraded reactiveui-core nuget to 2.3.2, then upgraded the other two libraries successfully. Now I am unable to upgrade the core library to the latest. Do they all not match up? The new error I am getting is 

Unable to resolve dependencies. 'reactiveui-core 7.0.0' is not compatible with 'reactiveui-blend 6.5.0 constraint: reactiveui-core (= 6.5.0)', 'reactiveui-platforms 6.5.0 constraint: reactiveui-core (= 6.5.0)'.

Once I upgraded reactiveui-xaml, I now have a new package: reactiveui-platforms. Its description says it is depricated, so not sure why it got added. I am unable to remove it, because reactiveui-xaml 5.5.1 depends on it. And I am also unable to upgrade it to latest, getting the error: 

Unable to resolve dependencies. 'reactiveui-platforms 6.5.0' is not compatible with 'reactiveui-xaml 5.5.1 constraint: reactiveui-platforms (= 5.5.1)'.

**Comment by ghuntley** [comment]
What platforms are you targeting and/or trying to install `reactiveui-xaml` into? If it is a PCL what profile number?

**Comment by Im-PJ** [comment]
I had splat 2.0 already installed. I get following error while trying to install reactiveui-core
'Splat 2.0.0' is not compatible with 'reactiveui-core 7.4.0 constraint: Splat (>= 1.4.0 && < 2.0.0)
does this mean latest version of reactiveui-core doesn't support splat 2.0?

**Comment by olevett** [comment]
ReactiveUI 7.X uses the older version of splat (<2). The newer release, 8.0.0 which is currently pre-release and available on [MyGet ](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed) bumps that up to Splat 2 though.

**Comment by ghuntley** [comment]
Closing this one out; please start migrating to v8
