### ISSUE TITLE
Using RxUI with Rx v3.x possible?

### ISSUE THREAD

**Issue by dotNZ** [reactiveui/ReactiveUI#1232]
Hi,

I have a multi-project solution which uses Rx v3.1.1. In a new WPF application I would like to use RxUI, but RxUI v7.1.0 forces me to install Rx v2.2.5. Due to compatibility reasons I'm not allowed to use Rx v2.2.5 anymore.

- Can RxUI v7.1.0 be used with Rx v3.1.1?
- Or do I have to drop RxUI for now and wait for RxUI v8?
- When will RxUI v8 be available?

Thanks!

**Comment by ghuntley** [comment]
Howdy @dotNZ. I've put #1190 #1123 on hold until v7 stabilises as migration to netstandard at this stage will create a rift of those who can migrate and those who cannot.  You are feeling this right now (you belong in the "can migrate"). I specifically do not want to be concurrently supporting v7 (rx2) and v8 (netstandard/rx3) at the same time. 

Check out the `netstandard` branch on GitHub if you would like to help with progressing v8; let's talk.

**Comment by ghuntley** [comment]
@ShannonKasperNoesis, @oliverw, @Mephistofeles and @dotNZ. I've put #1190 on hold until v7 stabilises as migration to netstandard at this stage will create a rift of those who can migrate and those who cannot.  You are feeling this right now (you belong in the "can migrate"). I specifically do not want to be concurrently supporting v7 (rx2) and v8 (netstandard/rx3) at the same time as I don't have the time to be able to do so.  Check out the `netstandard` branch on GitHub if you would like to help with progressing v8; let's talk.  We would <3 to and intend to grow our team in 2017.

**Comment by ghuntley** [comment]
Closing this one out. If you need Rx3.11 please start migrating towards the pre-release that's available on NuGet.org
