### ISSUE TITLE
Method 'Android.Widget.TimePicker.get_Hour' not found.

### ISSUE THREAD

**Issue by Alhantro** [reactiveui/ReactiveUI#1233]
When I'm using Android API <23 "AndroidObservableForWidgets" throws and exception. I searched for roots of problem and saw that property Hour is not found. So I propose to fix it using runtime check for API version. I can do it if you want.

**Comment by ghuntley** [comment]
Greetings @Alhantro. 

This change was introduced in the following pull-requests:
- https://github.com/reactiveui/ReactiveUI/pull/1186
- https://github.com/reactiveui/ReactiveUI/blob/fa79ebce4f1a1e8a4e07e70764a6b33a31964347/src/ReactiveUI/Android/AndroidObservableForWidgets.cs#L31-L32

If I remember correctly Xamarin.Android was resuing to compile, happy to revisit this and for you to pull-request in conditional "If API < 23 use old implementation else use new implementation" to support this use case.

**Comment by ghuntley** [comment]
Fixed by @teamtam  - thank-you.
