### ISSUE TITLE
WireUpControls throws an exception

### ISSUE THREAD

**Issue by orzech85** [reactiveui/ReactiveUI#1234]
WireUpControls throws an exception:
`System.MissingFieldException: Failed to wire up the Property CurrentFocus to a View in your layout with a corresponding identifier`

But I have no view called `CurrentFocus`.

I think this commit caused it:
https://github.com/reactiveui/ReactiveUI/commit/276f96302a0ed9e444884dfa40f1cd5691ffd725

Example project with issue demo:
https://github.com/orzech85/ReactiveExample/blob/master/ReactiveUI.Droid/MainActivity.cs#L20

**Comment by Qonstrukt** [comment]
See #1231.
