### ISSUE TITLE
ReactiveUI.AndroidSupport

### ISSUE THREAD

**Issue by Jurabek** [reactiveui/ReactiveUI#1237]
I want to implement ReactiveAppCompatActivity, AndroidNavigationRouter, ReactiveAdapter for RecyclerView .

Is there some implemented stuff? 
Does reactiveui have some chat on gitter or slack to ask questions?

**Comment by rdavisau** [comment]
Howdy, 

You should find many (if not all) of those are implemented in the [reactiveui.androidsupport](https://www.nuget.org/packages/reactiveui-androidsupport/) package. Just add it to your android project. 

We do have a Slack and would have to have you there, you can read about how to join it [here](https://github.com/reactiveui/ReactiveUI#slack)!

**Comment by ghuntley** [comment]
Ace reply @rdavisau!

**Comment by ghuntley** [comment]
@Jurabek how'd you go? I'm closing this off but if you have problems please open this up again. Also please come join us in Slack. 👍

**Comment by Jurabek** [comment]
@ghuntley I sent an email for you.
