### ISSUE TITLE
Match file names to class names

### ISSUE THREAD

**Issue by olevett** [reactiveui/ReactiveUI#1246]
***Note*: for support questions, please ask on StackOverflow: https://stackoverflow.com/questions/tagged/reactiveui . This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
More a proposal for improvement/logging of tech debt...

**What is the current behavior?**
There are currently files with classes where the name and the class don't match, an example being within the test projects, `RoutingState.cs` contains the test class `RoutingStateTests`, or`MobileLifecycle.cs` contains the class `SuspensionHost`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**What is the expected behavior?**
File names match class names

**What is the motivation / use case for changing the behavior?**
Slightly reduce the mental overhead of finding code - this is quite a minor issue!

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the latest stable and snapshot (http://docs.reactiveui.net/en/contributing/snapshot/index.html) versions.**

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by olevett** [comment]
I wanted to raise this for discussion, rather than jumping in and renaming a load of things...happy if anyone disagrees, but I think it's helpful to line up naming where possible...

**Comment by kentcb** [comment]
@olevett I agree this is annoying and it's something that has irked me for quite some time. However, there is a compelling reason for bundling multiple types into a single file. Each and every file needs to be included into many different project files. It is incredibly painful to add or remove files from the ReactiveUI project, because then you need to go and update umpteen other project files.

The new tooling coming in VS2017 should rectify this situation because we should no longer need to individually list each source file within each project file. Maybe we can revisit this once that tooling has matured? Until then, `Ctrl+,` is your dearest friend.

**Comment by olevett** [comment]
I think this could reasonably be split into two different issues then, there are two cases
1. bundling types into one file - this is kindof reasonable (though doesn't the 'shared code' project type sort of fix it?)
2. files with one type where the name just doesn't match (or, things like a type + extension methods for that type I think should match the type name rather than something somewhat random)

For this issue, I was mainly thinking of the latter, as something solvable without going too far. Examples of this would be the 'MobileLifecycle.cs' file I mentioned before.

**Comment by kentcb** [comment]
@olevett agreed, but renaming files is just as painful as adding/removing them. I'd be happy if someone wants to pick this up and PR it, but otherwise I'll be waiting for the tooling to help alleviate the pain.

**Comment by olevett** [comment]
As an offshoot to this, and I know this is potentially pointless with the changes for VS2017 (@ghuntley mentioned something about this?) I wanted to see what would happen if these files got moved into a shared project (so there's effectively one reference to all the files, instead of a load of references to each file). It turns out, it's actually not too bad...I can put up a pull request for this if that's helpful, it's https://github.com/olevett/ReactiveUI/tree/shared-project otherwise.
