### ISSUE TITLE
XF: auto-assign ViewModel from BindingContext

### ISSUE THREAD

**Issue by kentcb** [reactiveui/ReactiveUI#1256]
**Do you want to request a *feature* or report a *bug*?**

Feature/enhancement.

**What is the current behavior?**

The `ViewModel` property for reactive views is not auto-populated from the `BindingContext`. This means that developers are required to manually propagate the property. For example:

```XML
        <ListView.ItemTemplate>
            <DataTemplate>
                <local:MyReactiveView ViewModel="{Binding .}"/>
            </DataTemplate>
        </ListView.ItemTemplate>
```

This is annoying and is an easy thing to miss.

**What is the expected behavior?**

It would be nice if the base reactive view classes could override `OnBindingContextChanged` and auto-assign to the `ViewModel` property where relevant:

```
protected override OnBindingContextChanged()
{
    this.ViewModel = this.BindingContext as TViewModel;
}
```

However, I think this code will need to be slightly smarter. If the `BindingContext` is not a `TViewModel` (or is `null`) then it shouldn't overwrite whatever is assigned to `ViewModel`, just in case the two differ.

**What is the motivation / use case for changing the behavior?**

Reduce friction.

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the latest stable and snapshot (http://docs.reactiveui.net/en/contributing/snapshot/index.html) versions.**

7

**Comment by FrancoisM** [comment]
I'm on my phone trying to find some kind of "like" button to support that request but cannot find any so I say it here: +1.

**Comment by PureWeen** [comment]
Along these lines would it also be helpful to assign the BindingContext in cases like VM Navigation?

**Comment by kentcb** [comment]
@PureWeen I think that's a good suggestion. Also true of `ViewModelViewHost`. It's not a pain point for me since I almost never use XAML bindings, but I can see how it would be for those who do.

**Comment by FrancoisM** [comment]
True. So far I use Xamarin Forms MVVM with Prism. I never care about BindingContext. Having to deal with it with ReactiveUI is like a regression.
And Binding with Xaml would be nice to have.
ReactiveUI should override Xamarin Forms bindings somehow.

**Comment by escamoteur** [comment]
xamvvm does assign the Bindingcontext of Pages to the ViewModel property
