### ISSUE TITLE
Document how to use VSTS as a package source to test pull-request builds

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/ReactiveUI#1272]
https://reactivex.slack.com/archives/reactiveui/p1487111431492910

**Comment by ghuntley** [comment]
Blocked by https://github.com/reactiveui/ReactiveUI/issues/1284

**Comment by ghuntley** [comment]
We now use VSTS - still needs documentation.

**Comment by vatsalyagoel** [comment]
Does this need to be an internal test or public test? VSTS package management is authenticated and private. If we use myget, we will have to publish it there. Depends on our requirement.

**Comment by glennawatson** [comment]
This was documented with github packages a while back.
