### ISSUE TITLE
Make our automated release notes and process better by contributing to GitVersion

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/ReactiveUI#1273]
Watch this video:

[![](http://img.youtube.com/vi/YNpvrVnQrVY/0.jpg)](http://www.youtube.com/watch?v=YNpvrVnQrVY "")

Then head on over to https://github.com/GitTools/GitReleaseManager/issues/90#issuecomment-279860853

**Comment by robertlyson** [comment]
Done. Now we can just wait for merge/feedback :)
https://github.com/GitTools/GitReleaseManager/pull/102

**Comment by ghuntley** [comment]
Thank-you @robertlyson
