### ISSUE TITLE
Duplicate key issue in `controlIds` dictionary in ControlFetcherMixin.cs in ReactiveUI_Android

### ISSUE THREAD

**Issue by ginev** [reactiveui/ReactiveUI#1275]
I think this is an issue with the way the `controlIds` dictionary is populated in ControlFetcherMixin.cs: https://github.com/reactiveui/ReactiveUI/blob/develop/src/ReactiveUI/Android/ControlFetcherMixin.cs#L34-L36

In a Xamarin.Android project that uses ReactiveUI, referencing Xamarin.Android assemblies that have resource IDs which are the same word but with different casing the following exception is thrown as soon as the static constructor of `ControlFetcherMixin.cs` is executed:

```
02-15 11:45:16.138 E/mono-rt ( 4726): [ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'ReactiveUI.ControlFetcherMixin' threw an exception. ---> System.ArgumentException: An item with the same key has already been added.
02-15 11:45:16.138 E/mono-rt ( 4726):   at System.ThrowHelper.ThrowArgumentException (System.ExceptionResource resource) [0x00000] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/referencesource/mscorlib/system/throwhelper.cs:72 
02-15 11:45:16.138 E/mono-rt ( 4726):   at System.Collections.Generic.Dictionary`2[TKey,TValue].Insert (TKey key, TValue value, System.Boolean add) [0x0008e] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/referencesource/mscorlib/system/collections/generic/dictionary.cs:336 
02-15 11:45:16.138 E/mono-rt ( 4726):   at System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) [0x00000] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/referencesource/mscorlib/system/collections/generic/dictionary.cs:192 
02-15 11:45:16.138 E/mono-rt ( 4726):   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] keySelector, System.Func`2[T,TResult] elementSelector, System.Collections.Generic.IEqualityComparer`1[T] comparer) [0x0004d] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/referencesource/System.Core/System/Linq/Enumerable.cs:881 
02-15 11:45:16.138 E/mono-rt ( 4726):   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] keySelector, System.Func`2[T,TResult] elementSelector) [0x00000] in /Users/builder/data/lanes/3511/501e63ce/source/mono/mcs/class/referencesource/System.Core/System/Linq/Enumerable.cs:873 
02-15 11:45:16.138 E/mono-rt ( 4726):   at ReactiveUI.ControlFetcherMixin..cctor () [0x00049] in C:\work\git\ReactiveUI\src\ReactiveUI\Android\ControlFetcherMixin.cs:34 
02-15 11:45:16.138 E/mono-rt ( 4726):    --- End of inner exception stack trace ---
```

This is related to the way the Android build system generates resource IDs in the corresponding R.id classes. In this particular case we have the following IDs:

```
public static int none=0x7f0b000f;
public static int None=0x7f0b002a;
```

Since the binaries I am using are a commercial product I am not able to share a project which reproduces the case.

The expected behavior here is to not allow duplicate keys in the `controlIds` dictionary.

This is reproducible with the latest version of ReactiveUI. I have managed to debug the case by cloning the ReactiveUI repo and using the develop branch to build the project.

Without having the complete ReactiveUI context, I suggest fixing the issue by omitting the `ToLowerInvariant()` call on the key value for each dictionary entry.

**Comment by Qonstrukt** [comment]
I agree the error message isn't very descriptive of what's wrong exactly. (I've ran into this issue before, and had to dive in the source to see what's going on.)
But there's a good reason for it to use `ToLowerInvariant`, because your property names often do not exactly match the casing of the resource names. And making a lookup dictionary with lowercase key names,  is much faster than having to compare the list case-insensitive. 

To be honest, it'd be a much better practice to make sure your resource names are concise and use equal casing everywhere. But I agree the error message could be clearer.

**Comment by ginev** [comment]
@Qonstrukt thanks for the info! I am still trying to figure out why the resource name are generated this way, i.e. None and none. We have an Android styleable attribute in our resource definitions that is called `None`:

```
     <attr name="weekNumberDisplayMode" format="enum">
            <enum name="None" value="0"/>
            <enum name="Inline" value="1"/>
            <enum name="Block" value="2"/>
        </attr>
```
 I believe there is a styleable attribute in the Android AppCompat .dll that is called `none` and thus the collision. For example, this is out of the Android AppCompat resources:

```     
<attr name="displayOptions">
            <flag name="none" value="0" />
            <flag name="useLogo" value="0x1"/>
            <flag name="showHome" value="0x2"/>
            <flag name="homeAsUp" value="0x4"/>
            <flag name="showTitle" value="0x8"/>
            <flag name="showCustom" value="0x10"/>
            <flag name="disableHome" value="0x20"/>
</attr>
```
I believe this can happen with any combination of third-party libraries. I guess the best way to solve this is by reducing the probability of having resource IDs with the same keys by applying a relatively unique but yet understandable prefix to all IDs within a library.

**Comment by Qonstrukt** [comment]
True, unfortunately we have no control over this. Prefixing the names in the lookup dictionary would make it impossible to reference them by name in your code because you wouldn't be aware of the prefix. That being said, there's more issues with Android resource handling in Xamarin I would like to see fixed, but none of them are particularly easy to fix.

In your case I would prefix the enum values myself, or follow Android-convention and all make them lowercase. 

I'll add the better error message in #1250.

**Comment by ghuntley** [comment]
Source code for AppCompat can be found over at https://github.com/xamarin/AndroidSupportComponents

**Comment by Qonstrukt** [comment]
The original names in the axml files originate from the native Android versions though. The names in the `Resource` class are just generated by the Xamarin build process.

**Comment by ginev** [comment]
We are going to resolve this by renaming the styleable attributes from `None` to `none` so that only one resource ID is generated.

**Comment by Qonstrukt** [comment]
This was improved with #1302. Thanks for reporting @ginev!
