### ISSUE TITLE
Issue with versioning of pull-request and develop builds

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/ReactiveUI#1284]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

v7.1.0 is out and released to NuGet.org and the version is for pull-requests is v6.6.0-pullrequest$incrementing

![image](https://cloud.githubusercontent.com/assets/127353/23160279/f59e8054-f879-11e6-9ae1-525be3ae37d7.png)

v7.1.0 is out and released to NuGet.Org and the identifiers for develop builds to myget are 7.1.0-alpha$incrementing

![image](https://cloud.githubusercontent.com/assets/127353/23160363/4a2452e8-f87a-11e6-91b1-cf639cf2b18b.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

https://ci.appveyor.com/project/ghuntley/reactiveui/build/513.Branch.pull/1265/merge.Sha.98946eaba68e097e632bfab117fd4095abf81b32

**What is the expected behavior?**

The root cause will need some tweaks to our human processes as part of releasing (https://github.com/reactiveui/ReactiveUI/compare/develop...master?expand=1)

As for actual expected behavior need to 💭

**Comment by ghuntley** [comment]
If v7.1.0 is out on NuGet.org then I would expect:

- develop would be v7.2.0-alpha$number
- pull-request builds would be v7.2.0-pullrequest$number

**Comment by ghuntley** [comment]
GitVersion `develop` as it currently is

![image](https://cloud.githubusercontent.com/assets/127353/23160870/348b5e3e-f87c-11e6-8fcf-d51abec3c7ec.png)

After merging master into develop

![image](https://cloud.githubusercontent.com/assets/127353/23161009/9aae6eb8-f87c-11e6-82ca-c1b7ad076212.png)

**Comment by ghuntley** [comment]
Identified root cause for pull-request builds not incrementing. 

![image](https://cloud.githubusercontent.com/assets/127353/23161261/9712b204-f87d-11e6-90c0-1fb2906ccc7d.png)


It's because the GitVersion configuration does not have a default catch all configuration.

**Comment by kentcb** [comment]
> What comes first? alphas or pull-requests?

My hope would be that alpha packages trump PR packages. Otherwise, the experience of `Install-Package reactiveui -Pre` would result in a more-or-less random PR package installed.

> What's the process for switching a project over from alpha build to test a pullrequest build

If I've got a project consuming the alphas, then I could just:

```
Install-Package reactive -pre -version 7.2.0-pullrequest1234
```

**Comment by gep13** [comment]
@ghuntley do you want to organise a chat about this at some point?

**Comment by ghuntley** [comment]
@gep13 yeah I really do. Want to get the project to a point where bugs are _always_ fixed with unit tests/repros and a maintainer can just pull down the CI built `pullrequest.nupkg` to do any manual verification as need be. No more having to clone branches, kick off builds etc.

**Comment by gep13** [comment]
@ghuntley quite busy this week, but should be able to arrange a meeting next week at some point to discuss if you want.

**Comment by ghuntley** [comment]
@gep13 works for me!

**Comment by gep13** [comment]
@ghuntley let me know when works for you.

**Comment by ghuntley** [comment]
We don't use this workflow anymore closing.
