### ISSUE TITLE
Can't build the ReactiveUI Solution on Xamarin Studio for Mac

### ISSUE THREAD

**Issue by GiusepeCasagrande** [reactiveui/ReactiveUI#1290]
***Note*: for support questions, please ask on StackOverflow: https://stackoverflow.com/questions/tagged/reactiveui . This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
Neither, an improvement over the building process. 

**What is the current behavior?**
It's not building on Xamarin Studio for Mac

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
- Clone the repo on a Mac
- Open it on a Xamarin Studio
- Select the Debug | X64 configuration
- If you hit rebuild all, it will print this error: 
`ReactiveUI/src/ReactiveUI/ReactiveUI_Mac.csproj: error : Target named 'Clean' not found in the project.`
- If you try to build the ReactiveUI_Mac project, it will give this error:
`ReactiveUI/src/ReactiveUI/ReactiveUI_Mac.csproj: error : Target named 'Build' not found in the project.`

**What is the expected behavior?**
To build :)

**What is the motivation / use case for changing the behavior?**
I was looking into solving one issue that is related to ReactiveUI.Mac, and I would like to be able to build it.

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the latest stable and snapshot (http://docs.reactiveui.net/en/contributing/snapshot/index.html) versions.**
Mac, not sure if was possible to build before, never tried to build RxUI before.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by b-straub** [comment]
#1287 will solve this isssue

**Comment by RLittlesII** [comment]
Resolved #1932
