### ISSUE TITLE
Issue Building ReactiveUI with a pure VS2017 machine (NO VS2015 ever)

### ISSUE THREAD

**Issue by ChrisPulman** [reactiveui/ReactiveUI#1295]
***Note*: for support questions, please ask on StackOverflow: https://stackoverflow.com/questions/tagged/reactiveui . This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
Contributers Issue

**What is the current behavior?**
Will open and build using VS2015 with correct Android SDK's installed and Win Mobile 8.1 SDK.
However when opened on a Windows 10 machine with only VS2017 Enterprise + all relevant add-on's fails to build all Andriod projects, ReactiveUI.Blend_WinRT, and ReactiveUI.Blend_Net45 project
execute Build.bat and get a failed build on a machine without VS2015 installed

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**What is the expected behavior?**
Open with VS2017 restore packages and Build resulting in a successful build
Open with VS2015 restore packages and Build resulting in a successful build
execute Build.bat and get a successful build

**What is the motivation / use case for changing the behavior?**
VS2017 is going to be released on March 7th, it has many beneficial features and support for C#7, there is also a Mac version of this (I don't personally own a Mac but... I am starting to see a need to have one even if I only use it for testing)

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the latest stable and snapshot (http://docs.reactiveui.net/en/contributing/snapshot/index.html) versions.**
Source code

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
![reactiveuibuilderrorwithvs2017](https://cloud.githubusercontent.com/assets/4910015/23340027/a8f94922-fc26-11e6-93ef-2c43ca7cae3c.PNG)
![reactiveuiideerrorwithvs2017](https://cloud.githubusercontent.com/assets/4910015/23340062/8cd28b04-fc27-11e6-847c-5799afa386dd.PNG)

Possible fix for some of the issues would be to add a nuget package Microsoft.Xaml.Interactivity.Unofficial for the ReactiveUI.Blend_WinRT project and System.Windows.Interactivity.WPF package for the ReactiveUI.Blend_Net45 project.
The Andriod project issues need more investigation as I am not certain what version of the SDK is meant to be in use. I may not have the correct versions installed if someone can identifiy the correct version I can update this issue with the new status of the Andriod projects with VS2017

**Comment by olevett** [comment]
@ChrisPulman I think this should now be resolved on the top of develop, with the process of reworking to the new style csproj files.

**Comment by ghuntley** [comment]
Can confirm that this is fixed in `develop`
