### ISSUE TITLE
ViewLocator can throw null reference exceptions

### ISSUE THREAD

**Issue by olevett** [reactiveui/ReactiveUI#1298]
***Note*: for support questions, please ask on StackOverflow: https://stackoverflow.com/questions/tagged/reactiveui . This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
DefaultViewLocator.AttemptViewResolutionFor can throw a null reference exception if ToggleViewModelType returns null.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**What is the expected behavior?**
Doesn't throw an exception (either, ToggleViewModelType doesn't return null, or there's a null check around it in ResolveView).

**What is the motivation / use case for changing the behavior?**
Not throwing exceptions when they shouldn't be thrown.

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the latest stable and snapshot (http://docs.reactiveui.net/en/contributing/snapshot/index.html) versions.**
7.2

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by SProst** [comment]
I am currently able to reproduce this. Going to have to roll back to 7.1 due to a significant change in behavior (it was not throwing the null reference before 7.2).
