### ISSUE TITLE
ReactiveCommand should not crash when a no arg Action is registered but an XAML CommandParameter is set.

### ISSUE THREAD

**Issue by bradphelan** [reactiveui/ReactiveUI#1305]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

If a command parameter in XAML for the command is set but the command is created with a no arg Action then an error occurs when the action is invoked.

```
<Button Command={Binding MyCommand} CommandParameter={Binding MyCommandData}/>
```

with

``ReactiveCommand.Create(()=> Console.WriteLine("ButtonPressed"))``

**What is the expected behavior?**

If I register an Action with no arguments it means I don't really care about the command parameters. The action should get called and the command parameter discarded. I should not have to write

``ReactiveCommand.Create( _ => Console.WriteLine("Button Pressed"))``

**Comment by njannink** [comment]
I second this I find it quite ugly to do the following code in the view when hooking up events

`Texts.Events().MouseUp.Select(x => Unit.Default).InvokeCommand(ViewModel, x => x.DoSomething);`

The EventArgs should just be ignored when the ReactiveCommand argument is of type Unit.

**Comment by kentcb** [comment]
Bit confused here. If your command does not want to take arguments, why are you attempting to pass an argument? ReactiveUI is doing you a favor by letting you know about the mismatch in your own usage of the command.

Given that the error message is very clear ("Command requires parameters of type X, but received parameter of type Y"), I think ReactiveUI is doing the right thing here. Any implementation that silently dropped provided parameters based on the target type would lead to far more confusion than an exception that tells you exactly what you did wrong.

As for the `InvokeCommand` example provided by @njannink, it can be simplified somewhat by a `ToSignal` extension:

```C#
public static IObservable<Unit:> ToSignal(this IObservable<T> @this) =>
    @this.Select(_ => Unit.Default);
```

To my knowledge, this extension doesn't exist in Rx/RxUI yet, but I think pretty much everyone ends up with it in some form in their code base.
