### ISSUE TITLE
Memory leak when nesting ViewModelViewHosts in WPF

### ISSUE THREAD

**Issue by kentcb** [reactiveui/ReactiveUI#1314]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

Memory leaks when nesting `ViewModelViewHost` instances. It seems the `DependencyProperty` infrastructure is holding onto an instance of the `ViewModelViewHost`, which in turn has a reference to a VM:

![image](https://cloud.githubusercontent.com/assets/1901832/23700032/7306b034-0441-11e7-9b82-e201bd754b7a.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

The best repro I have is the source code for my book samples, which is not currently publicly available. If someone wants to take a look at this before I do then ping me.

**What is the expected behavior?**

Memory should not leak, regardless of how nested `ViewModelViewHost` instances are.

**What is the motivation / use case for changing the behavior?**

Leaking memory is bad, mkay?

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the latest stable and snapshot (http://docs.reactiveui.net/en/contributing/snapshot/index.html) versions.**

7.2

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by offan** [comment]
1) Why reverse navigation creates a new copy of the view that is in the ViewModelViewHost?
2) If the ViewModelViewHost has set the visibility property Collapsed and reverse navigation (HostScreen.Router.NavigateBack.Execute(new System.Reactive.Unit());) have a memory leak. because of (fe.WhenAnyValue(x => x.IsHitTestVisible).SkipWhile(x => !x)) not dispose.

**Comment by ChrisPulman** [comment]
Should be fixed via #3105
