### ISSUE TITLE
WhenAnyValue should return ValueTuple rather than Tuple for future versions

### ISSUE THREAD

**Issue by bradphelan** [reactiveui/ReactiveUI#1316]
**Do you want to request a *feature* or report a *bug*?**

FEATURE

**What is the current behavior?**

WhenAnyValue currently return an observable of tuple.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**What is the expected behavior?**

WhenAnyValue should return an observable of ValueTuple

**What is the motivation / use case for changing the behavior?**

ValueTuple will be the standard tuple type going forward in C#. This will cause some editing to be required of users as it will cause a break with past versions.

**Comment by WilkaH** [comment]
@bradphelan I'm not sure that this will be a breaking change to the code. Even if you have `(int number, string text)` it will still expose Item1 and Item2 to be compatible with the old `Tuple<T1, T2>`

**Comment by bradphelan** [comment]
Yes if you just access them that way but if you have any utilities that declare they accept Tuple types rather than ValueTuple types you will get a compile error.

**Comment by WilkaH** [comment]
@bradphelan ah, yes. Very good point.

**Comment by SProst** [comment]
https://github.com/Microsoft/dotnet/blob/master/releases/net47/dotnet47-changes.md#bcl With changes to the BCL to integrate ValueTuple into the framework, it should be easier to incorporate ValueTuple if reactiveui also moves to support the net47 version once the broader release happens.

**Comment by bradphelan** [comment]
Hello bot ;)

**Comment by kentcb** [comment]
_Ping_

Definitely think this is a good idea and (probably) worth the break. But I think this should be targeted for v9, which is probably going to be a perf-focused release.

**Comment by glennawatson** [comment]
Hello not again

**Comment by ghuntley** [comment]
Add the label help wanted and it won't auto close.

**Comment by glennawatson** [comment]
This change was made as part of v10 of ReactiveUI.
