### ISSUE TITLE
ReactiveCommand.Execute() not delievered on outputScheduler

### ISSUE THREAD

**Issue by csmager** [reactiveui/ReactiveUI#1318]
**Do you want to request a *feature* or report a *bug*?**

Potential bug. A difference in behaviour in 7.x vs 6.x.

**What is the current behavior?**

The results from `ReactiveCommand.Execute()` are not delivered on the `outputScheduler`, only results from subscribing to the command itself. 

This differs from the observable returned by `ReactiveComand.ExecuteAsync()` in v6.x.

**What is the expected behavior?**

I'm unclear whether this change was intentional or not, but thought I'd raise as it bit us when migrating some of our commands.

**Comment by bradphelan** [comment]
I just found this as well. The documentation is clear on this but it seems a bit strange. The 99% case is

```
var command = ReactiveCommand.Create(()=>DoStuff(), schedular = TaskPoolSchedular.Instance)
```

or something like this. I'm not so often doing

```
var command = ReactiveCommand.Create(()=> Unit.Default, outputSchedular = TaskPoolSchedular.Instance);
command
    .Subscribe(x=>DoStuff());
```

**Comment by csmager** [comment]
@bradphelan I'm not sure that's related. I'd agree that's made very clear in the big '**Warning**' box [in the the documentation](https://docs.reactiveui.net/en/user-guide/commands/controlling-scheduling.html). 

Here I'm talking about the difference between these two subscriptions:
```csharp
command.Subscribe(x => ...);
command.Execute().Subscribe(x => ...);
```
Take this example:
```csharp
Debug.WriteLine("Main Thread [{0}]", Thread.CurrentThread.ManagedThreadId);

var command = ReactiveCommand.Create(() => Unit.Default, 
    outputScheduler: RxApp.MainThreadScheduler);

command.Subscribe(_ => 
    Debug.WriteLine("command [{0}]", Thread.CurrentThread.ManagedThreadId)
);

await Task.Run(() =>
    command.Execute().Subscribe(_ =>
        Debug.WriteLine("command.Execute() [{0}]", Thread.CurrentThread.ManagedThreadId))
);
```

I get this as output:

> Main Thread [1]
command.Execute() [3]
command [1]

Where I would expect (or would have seen in v6.x):

> Main Thread [1]
command [1]
command.Execute() [1]

**Comment by kentcb** [comment]
Thanks for the report @csmager. This was indeed something I missed in the rewrite. Curiously, I had created a test _intended_ to check this case, but I neglected to fix the test code up (copy/paste error). See #1325 for the PR.

**Comment by csmager** [comment]
@kentcb thanks for that. Pleased it wasn't a deliberate change!
