### ISSUE TITLE
Remove fully qualified test names in test explorer

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/ReactiveUI#1328]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

ReactiveUI's unit tests use fully qualified names, which makes it hard to see the actual name of the tests.

**What is the motivation / use case for changing the behavior?**

https://twitter.com/jbogard/status/846733211250102272

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

We are after someone from the community to send in a pull request that implements the changes as detailed in the Tweet above.

**Comment by shiftkey** [comment]
When I looked at doing this for Octokit.net ages ago I encountered two issues:

 - dropping the namespace would then require re-indenting, introducing a megadiff and making it harder to diff/blame previous changes to tests
 - zealous tools demanding to put the namespaces back in - I haven't tested if VS2017 is the same

If those don't seem too bad then :thumbsup:

**Comment by ghuntley** [comment]
![giphy](https://cloud.githubusercontent.com/assets/127353/24434188/c14f03f2-1479-11e7-9694-6b1c4f634035.gif)

**Comment by mholo65** [comment]
@ghuntley I could take a look at this.

**Comment by ghuntley** [comment]
@mholo65 go for it!
