### ISSUE TITLE
ReactiveAppCompatActivity is missing ctors for JNI ownership transfer 

### ISSUE THREAD

**Issue by oliverw** [reactiveui/ReactiveUI#1329]
In some circumstances, the Xamarin Android framework already has a reference to an object, but needs to create it's peer MCW. In these instances, the constructor that takes (IntPtr, JniHandleOwnership) is called.

This is basically the same problem as reported in #841.

**Comment by ghuntley** [comment]
Resolved via #1496 and new packages for v8 -pre will be pushed to NuGet in the next couple of minutes.
