### ISSUE TITLE
DefaultViewLocator thinks the View class has same name as ViewModel class if naming convention is not maintained

### ISSUE THREAD

**Issue by bradphelan** [reactiveui/ReactiveUI#1335]
See for behavior and workaround.

http://stackoverflow.com/questions/43585510/ninject-is-finding-multiple-bindings-for-implicit-self-bindings-after-upgrade-to/43590384#43590384

**Comment by olevett** [comment]
Possibly resolved by #1311 which has now been merged. Will try and find time to check this.

**Comment by cabauman** [comment]
I went ahead and checked this and verified this behavior is fixed.
