### ISSUE TITLE
Add netstandard target for ReactiveUI.Testing

### ISSUE THREAD

**Issue by olevett** [reactiveui/ReactiveUI#1340]
Following on from #1332, we should change the target for ReactiveUI.Testing to include NetStandard as Microsoft.Reactive.Testing now supports this target.

**Comment by kentcb** [comment]
Unless I'm missing something, I think this project need _only_ target netstandard. I mean, there is no platform-specific in any of the binaries, so just produce a single netstandard binary?

Might try this in a sec and PR...

**Comment by ghuntley** [comment]
Confirmed that this is needed, working on this now.

![image](https://user-images.githubusercontent.com/127353/30061149-95d28b98-9289-11e7-896f-eec69dcbf35a.png)

![image](https://user-images.githubusercontent.com/127353/30061156-9ed8cf72-9289-11e7-8758-afb14b3d9975.png)
