### ISSUE TITLE
any example on xamarin.forms?

### ISSUE THREAD

**Issue by koo9** [reactiveui/ReactiveUI#1341]
***Note*: for support questions, please ask on StackOverflow: https://stackoverflow.com/questions/tagged/reactiveui . This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the latest stable and snapshot (http://docs.reactiveui.net/en/contributing/snapshot/index.html) versions.**

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by ryanwersal** [comment]
There are several examples in #687 including some very complete applications. [Workout Wotch](https://github.com/reactiveui/ReactiveUI/issues/687#issuecomment-167390711) was a valuable resource for me personally. I'd also recommend [this routing sample](https://github.com/reactiveui/ReactiveUI/issues/687#issuecomment-249327116).

**Comment by aalmada** [comment]
Try this one https://github.com/aalmada/reactive-dev-days-lab

**Comment by kentcb** [comment]
Hopefully those samples are enough to get you going @koo9. We've also got more samples in the works, so stay tuned for them.
