### ISSUE TITLE
Cannot Subscribe to a command as shown in the compelling example

### ISSUE THREAD

**Issue by HasanAyan** [reactiveui/ReactiveUI#1347]
The compelling example shows how to subscribe to a command and do something with the value it returns ([see](https://docs.reactiveui.net/en/compelling-example/#update-the-user-interface)).

As follows;

```
// ReactiveCommands are themselves IObservables, whose value are the results
// from the async method, guaranteed to arrive on the UI thread. We're going
// to take the list of search results that the background operation loaded, 
// and them into our SearchResults.
Search.Subscribe(results => {
    SearchResults.Clear();
    SearchResults.AddRange(results);
});
```

However, when I try to Subscribe to a command (`ReactiveCommand<IEnumerable<MyType>,IEnumerable<MyType>>`) the subscribe method for it expects an `IObserver<IEnumerable<MyType>>` I cannot pass an Action to it. Is the example no longer valid? Is there another way to invoke an action after a command successfully finishes?

(I am referencing ReactiveUI 7.3.0)

**Comment by HasanAyan** [comment]
It's embarrassing when I solve trivial problems right after asking for a solution...

I had to add "using System" and the problem is resolved.

**Comment by kentcb** [comment]
All good - glad you found the solution quickly, @HasanAyan
