### ISSUE TITLE
Implement installation telemetry 

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/ReactiveUI#1349]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the motivation / use case for changing the behavior?**

- No idea what version of ReactiveUI people are using
- No insights as to how far or how long consumers have diverged behind latest release which makes planning harder.

**What is the new behavior?**

- When someone installs or restores ReactiveUI the website is displayed
- The request url contains the version the user is using.
- The user is informed when the next meetup is on.

Example of end output @ 
![image](https://cloud.githubusercontent.com/assets/127353/26247171/31b642f4-3ccf-11e7-86b4-c0db22bef6ab.png)

**Implementation**

- Lift https://github.com/JamesNK/Newtonsoft.Json/blob/master/Build/install.ps1 and customize
- Update nuspec and/or .csproj for ReactiveUI (if using VS2017 build environment) to invoke install.ps1
- Study Json.Net implementation for insights.
- Publish new release.

**Comment by Mephistofeles** [comment]
Aren't install scripts ignored in NuGet 3/4?

**Comment by ghuntley** [comment]
Had discussions with nuget team at summit. I'm 
closing this out as it would be better implemented at an ecosystem level.
