### ISSUE TITLE
ReactiveList.AddRange throws "Range actions are not supported" given a list of length 2<=n<=10, under certain circumstances

### ISSUE THREAD

**Issue by domyd** [reactiveui/ReactiveUI#1354]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`ReactiveList.AddRange` and `ReactiveList.InsertRange` throw a `System.NotSupportedException` "Range actions are not supported." when passing them a list with at least 2, but at most 10 number of elements, under certain circumstances that are still not entirely clear to me (see below examples).

`RxApp.SupportsRangeNotifications` is `true`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
The "cleanest" yet oddest example I came up with was this specimen:

### ViewModel
```csharp
public class MainViewModel : ReactiveObject
{
    public MainViewModel()
    {
        // This works for any number of elements
        SearchResults.AddRange(Create(5));

        Observable.Start(() => { })
            .Do(_ =>
            {
                // This also works for any number of elements
                SearchResults.AddRange(Create(5));
            })
            .ObserveOn(RxApp.MainThreadScheduler)
            .Subscribe(_ =>
            {
                // This fails for [2..10] elements
                SearchResults.AddRange(Create(5));
            });

        IEnumerable<string> Create(int numElements)
            => Enumerable.Range(1, numElements).Select(i => $"item_{i}");
    }

    public ReactiveList<string> SearchResults { get; } = new ReactiveList<string>();
}
```
### View
```xaml
<Grid>
    <ListView ItemsSource="{Binding SearchResults}"></ListView>
</Grid>
```

---

... which manifests itself in a more realistic scenario, like the following:

### ViewModel
```csharp
public class MainViewModel : ReactiveObject
{
    public MainViewModel()
    {
        // This works for any number of elements
        SearchResults.AddRange(Create(5));

        Search = ReactiveCommand.Create(() => { });
        Search.Subscribe(_ =>
        {
            // This fails for [2..10] elements
            SearchResults.AddRange(Create(5));
        });
    }

    private static IEnumerable<string> Create(int numElements)
        => Enumerable.Range(1, numElements).Select(i => $"item_{i}");

    public ReactiveCommand<Unit, Unit> Search { get; }

    public ReactiveList<string> SearchResults { get; } = new ReactiveList<string>();
}
```
### View
```xaml
<Grid>
    <Grid.RowDefinitions>
        <RowDefinition Height="Auto"></RowDefinition>
        <RowDefinition Height="*"></RowDefinition>
    </Grid.RowDefinitions>
    <Button Command="{Binding Search}" Content="Search" Grid.Row="0"></Button>
    <ListView ItemsSource="{Binding SearchResults}" Grid.Row="1"></ListView>
</Grid>
```

Code-behind of the above two examples:
```csharp
public partial class MainWindow : Window
{
    public MainWindow()
    {
        InitializeComponent();
        DataContext = new MainViewModel();
    }
}
```

---

However, the following `Button.Click` based example *also* triggers the error:

### ViewModel
```csharp
public class MainViewModel : ReactiveObject
{
    public MainViewModel()
    {
        // This works for any number of elements
        SearchResults.AddRange(Create(5));
    }

    public static IEnumerable<string> Create(int numElements)
        => Enumerable.Range(1, numElements).Select(i => $"item_{i}");

    public ReactiveList<string> SearchResults { get; } = new ReactiveList<string>();
}
```
### View
```xaml
<Grid>
    <Grid.RowDefinitions>
        <RowDefinition Height="Auto"></RowDefinition>
        <RowDefinition Height="*"></RowDefinition>
    </Grid.RowDefinitions>
    <Button Click="ButtonBase_OnClick" Content="Search" Grid.Row="0"></Button>
    <ListView ItemsSource="{Binding SearchResults}" Grid.Row="1"></ListView>
</Grid>
```
```csharp
public partial class MainWindow : Window
{
    public MainWindow()
    {
        InitializeComponent();
        DataContext = new MainViewModel();
    }

    private void ButtonBase_OnClick(object sender, RoutedEventArgs e)
    {
        // This fails for [2..10] elements
        (DataContext as MainViewModel).SearchResults.AddRange(MainViewModel.Create(5));
    }
}
```

**What is the expected behavior?**
For `ReactiveList.AddRange` and `ReactiveList.InsertRange` to not throw "Range actions are not supported" in a NET45 application, for any non-null list, like, ever.

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI?**
* OS is Windows 10 version 1703 (Creator's Update) with VS 2017 Update 2.
* Platform is WPF/.NET Framework 4.5.2 and 4.7 (likely any .NET Framework >= 4.5, but I only tested those two).
* ReactiveUI 7.*, 6.5.2, 6.0.0, 5.2.0 and 5.1.2 definitely exhibit this issue. Version 5.0.2 works as expected! So I guess it's safe to assume this bug exists since 5.1.2.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
[ReactiveList.cs, line 357](https://github.com/reactiveui/ReactiveUI/blob/7.4.0/src/ReactiveUI/ReactiveList.cs#L357) is the one that throws the Exception in the latest release (7.4.0).

#363 appears to be about the same problem, and indeed it works fine using the `SixReactiveList<T>` posted in that issue. It looks like it should be fixed, yet here I am ... 😕

**Comment by ghuntley** [comment]
Thank-you for the comprehensive issue 💯

**Comment by flyingxu** [comment]
I'm having the same issue and I'm not sure if it's related to this issue https://github.com/reactiveui/ReactiveUI/issues/363. After I added `RxApp.SupportsRangeNotifications = false;` as suggested by the PR of https://github.com/reactiveui/ReactiveUI/pull/593, I can use `AddRange` without any problem.

**Comment by domyd** [comment]
Yeah, if I recall correctly, `ReactiveList` will simply do an `Add` for each item if `RxApp.SupportsRangeNotifications = false`. The underlying issue, though, is that WPF inherently doesn't support range notifications, yet ReactiveList issues them.

However, now that WPF has been split into a separate package (right?), there might be a better way of solving this than in my PR.

**Comment by ElijahReva** [comment]
I'm having the same issue.  `Output` bound to `Listbox` ItemSource property.

Buggy version
```
ReactiveList<T> Output { get; }
...
this.Output.AddRange(data);
```
Workaround
```
using (this.Output.SuppressChangeNotifications())
{
  foreach (T expression in data)
  {
     this.Output.Add(expression);
   }
}
```

**Comment by ElijahReva** [comment]
Looking into it right now.

**Comment by ElijahReva** [comment]
Sorry for this weird commit feed. Was trying to remove corporative email from GIT_COMMITER_NAME and this resulted in several forced pushes. Could someone take a look at this?

**Comment by glennawatson** [comment]
We have dropped ReactiveList and ReactiveDerivedList in the next version of ReactiveUI and latest. Closing.
