### ISSUE TITLE
Proposal: move ReactiveList to Legacy and recommend DD instead

### ISSUE THREAD

**Issue by kentcb** [reactiveui/ReactiveUI#1372]
`ReactiveList<T>` is complicated, has loads of bugs, and no one really understands the code. Meanwhile, DynamicData does way more than `ReactiveList<T>` ever did.

For v8, I propose we move `ReactiveList<T>` to the `Legacy` namespace with a deprecation warning, then officially recommend DD as the way to work with collections in a reactive fashion.

Thoughts?

**Comment by aalmada** [comment]
DynamicData uses Rx.NET 3.0. Is this already supported in RxUI?

**Comment by modplug** [comment]
@aalmada Dynamic Data supports both Rx.NET 3.x and Rx.NET 2.x

**Comment by kentcb** [comment]
Thinking about this a bit more after a rare good night's sleep, the blocker right now will be ReactiveUI's use of `ReactiveList` for the routing infrastructure. There may be one or two other places where it is used internally too.

So perhaps a more realistic goal here is to deprecate it when we revamp the routing story (v9/v10?).

**Comment by olevett** [comment]
On the Rx.Net 3.x front (sort of irrelevant now) RxUI v8 is Rx.Net 3 currently.

**Comment by ghuntley** [comment]
Not sure if adding deprecation attribute though - it will cause any projects which are configured to fail on warnings to break (this is a good configuration). I think moving `ReactiveList<T>` into the legacy namespace and promoting DD is the way to go.

**Comment by GiusepeCasagrande** [comment]
> Not sure on adding the deprecation attribute though - it will cause any projects which are configured to fail on warnings to break
I would say that depends on how "hard" is to change from `ReactveList<>` to DD. If it's a matter of few changes, straight forward, I would be happy to see my CI broken with the update to v.8 (assuming that this would be made on v.8) and with a easy fix that would improve greatly my solution. A disclaimer: I haven't touched DD yet :)

**Comment by jcmm33** [comment]
Hmmm. Perhaps 18 months ago I would have said, yeah, just do it but now however (and it may well be just our use case(s)) but I find myself removing references to dynamic data and using it less and less. Our motivation is two fold - 1. The underlying sources of data (prior to transformation) don't maintain order upon edit; the assumption is that order is always maintained by a Sort operator further down the pipeline. Where you have the server however doing the sorting this just doesn't work for us. 2. And not so much relevant to this discussion, but there are issues with, once again, position being correctly handled in the mapping from ReactiveList sources to Dynamic Data ones. These issues may have been addressed, but I have discussed them with the author previously and the feedback I got was that 'this is by design'.

**Comment by RolandPheasant** [comment]
@jcmm33 I will join in the general discussion in a couple days time as I am away from laptop at the moment. However as for maintaining order a) the observable list does exactly the same order preservation as a standard list and b)the observable cache does exactly the same for order preservation as a dictionary so I am unsure why order preservation would be an issue.

However there are many ways of achieving the order preservation which you discussed and I found at least 3 different ways but I see that as a concern for a consumer to address not the library.

**Comment by VistianOpenSource** [comment]
@RolandPheasant If you have a look on Gitter for the September 28th - 30th last year you'll find our discussions regarding the above two points.  Specifically it was related to EditDiff not maintaining order and a similar issue related to mapping from an existing ReactiveList source over to DD.  

If people are going to consider dropping ReactiveList and shifting over to DD then given the way ReactiveList behaves more like a traditional .NET List/Collection people will need more information in understanding how to get their solutions to function with it since most will already be familiar with how Lists work in .NET.

**Comment by bradphelan** [comment]
Possible a better solution is https://github.com/Weingartner/ReactiveCompositeCollections

I was impressed with the abstraction that DynamicData uses so I wrote a different take on reactive collections. _ReactiveCompositeCollections_ fully implements LINQ. In geekspeak it is a Monad. It allows you to compose arbitrary hierarchies of  reactive collections using the familiar LINQ expression syntax.

For example you can create composite lists of composite lists and flatten them with LINQ. However if you update a leaf item then the flattened list is also updated.

Consider it more like a reactive database. It hasn't been well battle tested but we use it in production for some tasks.

```
CompositeSourceList<ICompositeSourceList<Line>> nestedLines = new CompositeSourceList<ICompositeSourceList<Line>>();

Widget wa = new Widget();
Widget wb = new Widget();

widgets.Add(wa.Lines);
widgets.Add(wa.Lines);

ICompositeList<Line> allLines = 
               from lines in nestedLines
               from line in lines
               select line;
               
// Subscribe the the stream of flattened lines               
allLines.Items.Subscribe((ImmutableList<Line> lines)=>RenderLines(lines));

// or create an INPC object with a property Items
using(var s = allLines.Subscribe()){
   RenderLines(s.Items);
}
```

**Comment by bradphelan** [comment]
Reading through the DD docs I came across the complexity that is dynamic filtering

https://github.com/RolandPheasant/DynamicData/blob/master/Docs/Filtering.md

the same can be achieved with RCC using plain old LINQ.

        [Fact]
        public void DynamicFilterShouldWork()
        {
            var data = new CompositeSourceList<int>();
            var filters = new CompositeSourceList<Func<int,bool>>();

            // Compose a dynamic filtering system by using a CompositeSourceList
            // to hold a filter. 
            var target =
                from fn in filters
                from s in data
                where fn(s)
                select s;

            data.AddRange( new []{0,1,2,3,4,5,6,7,8,9,10} );

            // Convert to an observable collection for testing purposes
            using (var oc = target.CreateObservableCollection( EqualityComparer<int>.Default ))
            {
                // Set the filter to be everything greater than 5
                filters.Add(  v => v> 5 );
                oc.Should().Equal( 6, 7, 8, 9, 10 );

                // Set the filter to be everything less than 5
                filters.ReplaceAt( 0, v=>v<5 );
                oc.Should().Equal( 0, 1, 2, 3, 4 );
            }
        }

Even more interesting is

         public class FilterHolder : ReactiveObject
        {
            private Func<int,bool> _Filter;
            public Func<int,bool> Filter { get => _Filter; set => this.RaiseAndSetIfChanged( ref _Filter, value ); }
        }

        [Fact]
        public void DynamicFilterWithRxUIShouldWork()
        {
            var data = new CompositeSourceList<int>();

            var filter = new FilterHolder {Filter = v => v > 5};

            // Compose a dynamic filtering system by using a WhenAnyValue to provide the filter
            var target =
                from fn in filter.WhenAnyValue( p=>p.Filter )
                from s in data
                where fn(s)
                select s;

            data.AddRange( new []{0,1,2,3,4,5,6,7,8,9,10} );

            // Convert to an observable collection for testing purposes
            using (var oc = target.CreateObservableCollection( EqualityComparer<int>.Default ))
            {
                // Set the filter to be everything greater than 5
                oc.Should().Equal( 6, 7, 8, 9, 10 );

                // Set the filter to be everything less than 5
                filter.Filter =  v=>v<5;
                oc.Should().Equal( 0, 1, 2, 3, 4 );
            }
        }

**Comment by glennawatson** [comment]
RxUI and DD have different licenses. DD still uses the MS-PL license which means you can't use it in GPL code, nor is it allowed at a lot of large corporates automatically. Until that happens I am stuck using the RxUI ReactiveList stuff.

**Comment by RolandPheasant** [comment]
@glennawatson I am happy to change the license for Dynamic Data. Could you raise an issue with your suggested alternative.

**Comment by glennawatson** [comment]
Now that the license of DD and RxUI match, it makes it much of a decent proposition as a replacement.

**Comment by glennawatson** [comment]
This is happening in the next few days.

**Comment by michaelstonis** [comment]
FWIW, there are still a handful of spots in RxUI Android that depend on `IReadOnlyReactiveList` and likely a few other places where it is lingering around as a hard dependency. Should we consider having those replaced with a more friendly interface before this fully goes into play?

**Comment by glennawatson** [comment]
Yeah that's the plan I've got a series of commits ready to go.
