### ISSUE TITLE
Get rid of Rebracer.xml and use .editorconfig

### ISSUE THREAD

**Issue by kentcb** [reactiveui/ReactiveUI#1377]
**Do you want to request a *feature* or report a *bug*?**

Tooling improvement.

**What is the current behavior?**

Rely on Rebracer.xml for formatting. No compile-time errors, and developers need to know to install Rebracer first. Also, Rebracer is really annoying in VS2017 now because it doesn't reset settings once you exit VS.

**What is the expected behavior?**

Let's use .editorconfig instead, which is supported in VS2017 (including community). We can set rules up in there and have them as errors and suggestions. For now, VS does not fail the build on these errors (it instead highlights them with a red squiggly). However, the Roslyn team are working on integrating it into the compiler, meaning we could enforce fairly detailed formatting requirements.

**What is the motivation / use case for changing the behavior?**

Reduce friction for developers, better enforcement of formatting.

**Comment by ghuntley** [comment]
Preference is to move towards using stylecop + pre-commit hooks. This is an extremely long term POV and would require slowly pulling up each file towards a standard convention and/or finding a way to make stylecop compatible with the existing convention. It's my understanding that editor config only handles things like tabs vs spaces and amount of spaces. What about automatically configuring of braces on a new line etc. What if we PR'ed the rebracer project instead?

**Comment by kentcb** [comment]
.editorconfig does braces and a bunch of other stuff. Think we should look into it over Rebracer for now.

**Comment by ghuntley** [comment]
👍 from me as it doesn't require the developer to install an additional plugin. Stylecop/automatic linting + reformatting can come at some other time.

**Comment by GiusepeCasagrande** [comment]
With some chance of derailing the discussion, but: Do we have to keep the current style or could we just adopt a new one (and update the code) to make easier to move to Stylecop for example?

**Comment by ghuntley** [comment]
If we were to move to a new style my vote is corefx (https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md)

**Comment by ghuntley** [comment]
Alright let's get rid of rebracer and use https://github.com/dotnet/roslyn/blob/master/.editorconfig as our baseline. See https://twitter.com/onovotny/status/873343604890140675

**Comment by Qonstrukt** [comment]
Does VS2017 support coding standards in the .sln as well? Because VS for Mac uses this to save settings. Maybe VS for Mac supports .editorconfig as well, but if it doesn't I'll give a go at adding the same config to the .sln, if that doesn't conflict with VS on Windows.
