### ISSUE TITLE
Calling Bind method repeatedly crashes

### ISSUE THREAD

**Issue by stephanemathis** [reactiveui/ReactiveUI#1379]
**Do you want to request a *feature* or report a *bug*?**

A bug.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

I have an error if I call the this.Bind in an Activity that is repeatedly destroyed and recreated.

`this.Bind(ViewModel, x => x.Text1, y => y.et1.Text);`

I have an Activity A with a button that directs to another Activity B.
In Activity B I have multiple EditText that are binded to a ViewModel with multiple string properties.

I go back and forth from Activity A to B, and after a fixed number of times the app crashes with the error below :

> 06-01 12:07:13.945 F/        ( 7845): * Assertion at /Users/builder/jenkins/workspace/xamarin-android/xamarin-android/external/mono/mono/metadata/sgen-tarjan-bridge.c:1139, condition `xref_count == xref_index' not met
06-01 12:07:14.025 F/libc    ( 7845): Fatal signal 6 (SIGABRT), code -6 in tid 7845 (App1.App1)

I've made a sample app. Anyone can download it here : [Sample app](https://drive.google.com/open?id=0B7De5DfDEi--QlJEN29xNjhDZGc)
With the sample app, it takes always 17 re-creations of Activity B for the crash to happen, but with the real app I develop it occurs after 4 times (maybe it depends on the number of fields binded).
The number of times required to make the app crashs depend also on the phone. It's 17 times with a LG G4c but 30 times with a Galaxy S6.

**Which versions of ReactiveUI, and which platform / OS are affected by this issue?**

I have tested with ReactiveUI 7.0.0 and 7.4.0, I have the latest stable version of Xamarin (4.5.0.476) and Xamarin Android (7.3.1.2).

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

The stack trace doesn't show anything special until the crash at the last 2 lines.

`06-01 12:19:21.535 D/BubblePopupHelper(10536): isShowingBubblePopup : false
06-01 12:19:21.535 D/BubblePopupHelper(10536): isShowingBubblePopup : false
06-01 12:19:21.535 D/BubblePopupHelper(10536): isShowingBubblePopup : false
06-01 12:19:21.555 I/Timeline(10536): Timeline: Activity_idle id: android.os.BinderProxy@ed5b788 time:109919942
06-01 12:19:21.575 D/OpenGLRenderer(10536): endAllStagingAnimators on 0xb856a660 (ListView) with handle 0xb8f44660
06-01 12:19:22.125 I/ViewRootImpl(10536): ViewRoot's Touch Event : ACTION_DOWN
06-01 12:19:22.165 I/ViewRootImpl(10536): ViewRoot's Touch Event : ACTION_UP
06-01 12:19:22.165 D/CliptrayUtils(10536): setInputTypeforClipTray(): 0
06-01 12:19:22.185 D/BubblePopupHelper(10536): isShowingBubblePopup : false
06-01 12:19:22.185 D/BubblePopupHelper(10536): isShowingBubblePopup : false
06-01 12:19:22.345 D/BubblePopupHelper(10536): isShowingBubblePopup : false
06-01 12:19:22.345 D/BubblePopupHelper(10536): isShowingBubblePopup : false
06-01 12:19:22.345 D/BubblePopupHelper(10536): isShowingBubblePopup : false
06-01 12:19:22.345 D/BubblePopupHelper(10536): isShowingBubblePopup : false
06-01 12:19:22.355 D/BubblePopupHelper(10536): isShowingBubblePopup : false
06-01 12:19:22.355 D/BubblePopupHelper(10536): isShowingBubblePopup : false
06-01 12:19:22.355 D/BubblePopupHelper(10536): isShowingBubblePopup : false
06-01 12:19:22.355 D/BubblePopupHelper(10536): isShowingBubblePopup : false
06-01 12:19:22.355 D/BubblePopupHelper(10536): isShowingBubblePopup : false
06-01 12:19:22.355 D/BubblePopupHelper(10536): isShowingBubblePopup : false
06-01 12:19:23.045 D/BubblePopupHelper(10536): isShowingBubblePopup : false
06-01 12:19:23.045 D/BubblePopupHelper(10536): isShowingBubblePopup : false
06-01 12:19:23.485 I/ViewRootImpl(10536): ViewRoot's KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x48, repeatCount=0, eventTime=109921854, downTime=109921854, deviceId=-1, source=0x101 } to com.android.internal.policy.impl.PhoneWindow$DecorView{344ecb07 V.E..... R....... 0,0-720,1188}
06-01 12:19:23.485 D/BubblePopupHelper(10536): isShowingBubblePopup : false
06-01 12:19:23.565 I/ViewRootImpl(10536): ViewRoot's KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x48, repeatCount=0, eventTime=109921933, downTime=109921854, deviceId=-1, source=0x101 } to com.android.internal.policy.impl.PhoneWindow$DecorView{344ecb07 V.E..... R....... 0,0-720,1188}
06-01 12:19:23.565 D/BubblePopupHelper(10536): isShowingBubblePopup : false
06-01 12:19:23.635 D/BubblePopupHelper(10536): isShowingBubblePopup : false
06-01 12:19:23.635 D/BubblePopupHelper(10536): isShowingBubblePopup : false
06-01 12:19:23.635 D/BubblePopupHelper(10536): isShowingBubblePopup : false
06-01 12:19:23.635 D/BubblePopupHelper(10536): isShowingBubblePopup : false
06-01 12:19:23.635 D/BubblePopupHelper(10536): isShowingBubblePopup : false
06-01 12:19:23.635 D/BubblePopupHelper(10536): isShowingBubblePopup : false
06-01 12:19:23.645 D/BubblePopupHelper(10536): isShowingBubblePopup : false
06-01 12:19:23.645 D/BubblePopupHelper(10536): isShowingBubblePopup : false
06-01 12:19:23.645 D/BubblePopupHelper(10536): isShowingBubblePopup : false
06-01 12:19:23.645 D/BubblePopupHelper(10536): isShowingBubblePopup : false
06-01 12:19:23.905 I/ViewRootImpl(10536): ViewRoot's KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x48, repeatCount=0, eventTime=109922270, downTime=109922270, deviceId=-1, source=0x101 } to com.android.internal.policy.impl.PhoneWindow$DecorView{344ecb07 V.E..... R....... 0,0-720,1188}
06-01 12:19:23.905 D/BubblePopupHelper(10536): isShowingBubblePopup : false
06-01 12:19:23.945 I/ViewRootImpl(10536): ViewRoot's KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x48, repeatCount=0, eventTime=109922331, downTime=109922270, deviceId=-1, source=0x101 } to com.android.internal.policy.impl.PhoneWindow$DecorView{344ecb07 V.E..... R....... 0,0-720,1188}
06-01 12:19:23.945 D/BubblePopupHelper(10536): isShowingBubblePopup : false
06-01 12:19:23.965 I/Activity(10536): Activity.onPostResume() called 
06-01 12:19:24.015 I/Timeline(10536): Timeline: Activity_idle id: android.os.BinderProxy@14915e10 time:109922401
06-01 12:19:24.055 E/CliptrayUtils(10536): hideClipTrayIfNeeded() TextView is focused!! hideClipTray()
06-01 12:19:24.305 E/CliptrayUtils(10536): hideClipTrayIfNeeded() TextView is focused!! hideClipTray()
06-01 12:19:24.465 I/ViewRootImpl(10536): ViewRoot's Touch Event : ACTION_DOWN
06-01 12:19:24.525 I/ViewRootImpl(10536): ViewRoot's Touch Event : ACTION_UP
06-01 12:19:24.585 I/Timeline(10536): Timeline: Activity_launch_request id:App1.App1 time:109922977
06-01 12:19:24.625 I/PhoneWindow(10536): [generateLayout] setColorNavigationBar => color=0x ff000001
06-01 12:19:24.625 D/PhoneWindowEx(10536): [PWEx][generateLayout] setNavigationBarColor2 : colors=0xff000000
06-01 12:19:24.625 I/PhoneWindow(10536): [setNavigationBarColor2] color=0x ff000000
06-01 12:19:24.635 I/CliptrayUtils(10536): CliptrayUtils created!! mTextView = android.widget.EditText{223dd7d2 VFED..C. ......I. 0,0-0,0 #7f050001 app:id/editText1}
06-01 12:19:24.635 I/CliptrayUtils(10536): CliptrayUtils created!! mTextView = android.widget.EditText{2a8310a3 VFED..C. ......I. 0,0-0,0 #7f050002 app:id/editText2}
06-01 12:19:24.635 I/CliptrayUtils(10536): CliptrayUtils created!! mTextView = android.widget.EditText{9f1efa0 VFED..C. ......I. 0,0-0,0 #7f050003 app:id/editText3}
06-01 12:19:24.635 I/CliptrayUtils(10536): CliptrayUtils created!! mTextView = android.widget.EditText{28c5f759 VFED..C. ......I. 0,0-0,0 #7f050004 app:id/editText4}
06-01 12:19:24.645 I/CliptrayUtils(10536): CliptrayUtils created!! mTextView = android.widget.EditText{157d9f1e VFED..C. ......I. 0,0-0,0 #7f050005 app:id/editText5}
06-01 12:19:24.745 F/        (10536): * Assertion at /Users/builder/jenkins/workspace/xamarin-android/xamarin-android/external/mono/mono/metadata/sgen-tarjan-bridge.c:1139, condition `xref_count == xref_index' not met
06-01 12:19:24.745 F/libc    (10536): Fatal signal 6 (SIGABRT), code -6 in tid 10536 (App1.App1)`

**Comment by Qonstrukt** [comment]
Looking at your exception, this might be related to Xamarin.Android switching to the Tarjan GC bridge:
https://developer.xamarin.com/releases/android/xamarin.android_7/xamarin.android_7.3/#Known_Issues

There still are some issues with it, so what happens if you switch back to the old bridge?

**Comment by stephanemathis** [comment]
This solves the issue.
Thank you very much.

I guess i'll use that fix for now and wait on the next update !
