### ISSUE TITLE
RoutedViewHost, ViewModelViewHost do not display default content

### ISSUE THREAD

**Issue by SProst** [reactiveui/ReactiveUI#1381]
***Note*: for support questions, please ask on StackOverflow: https://stackoverflow.com/questions/tagged/reactiveui . This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

RoutedViewHost and ViewModelViewHost both do not display default content or the content associated with the ViewModel that the ViewLocator finds. They both show up in the Live Visual Tree, but there is no content loaded for either default content or the ViewLocated content.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Using WPF, .NET 4.7, reactiveui prerelease 7.5 alpha 0028. Add a ViewModelViewHost or RoutedViewHost to xaml. Add the default content.
```

 <rui:RoutedViewHost x:Name="ContentView" Grid.Column="1" Width="Auto">
            <rui:RoutedViewHost.DefaultContent>
                <Border Background="Gainsboro">
                    <TextBlock Text="No view loaded."></TextBlock>
                </Border>
            </rui:RoutedViewHost.DefaultContent>
        </rui:RoutedViewHost>
```

**What is the expected behavior?**

Default content / content should be visible.

**What is the motivation / use case for changing the behavior?**

Currently RoutedViewHost / ViewModelViewHost appear broken in this build of reactiveui 7.5-alpha0028.

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the latest stable and snapshot (http://docs.reactiveui.net/en/contributing/snapshot/index.html) versions.**

reactiveui 7.5-alpha0028
Windows 7 SP1, Windows 10 Build 16199.rs_prerelease.170513-2252
This behavior is new to reactiveui 7.5 and was not present in 7.4 and earlier.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by ghuntley** [comment]
Thank-you so much for a good bug report and helping validate our MyGet builds.

**Comment by ghuntley** [comment]
This was resolved by reverting the WPF package back to use the legacy project format. Should be all good now!
