### ISSUE TITLE
Xamarin Forms Events is no longer git ignored

### ISSUE THREAD

**Issue by olevett** [reactiveui/ReactiveUI#1382]
***Note*: for support questions, please ask on StackOverflow: https://stackoverflow.com/questions/tagged/reactiveui . This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
src/ReactiveUI.Events.XamForms/Events_XAMFORMS.cs is generated but not .gitignored

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Run event builder, and the file is generated.

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**
Prevent accidentally checking in a file that gets generated as part of the build process.

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the latest stable and snapshot (http://docs.reactiveui.net/en/contributing/snapshot/index.html) versions.**

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

The build process run by Cake generates event files for each platform. This shifted recently to generate XamForms events in their own project, to make it easier to target the platform correctly.

The old event files are covered by the [.gitignore](https://github.com/reactiveui/ReactiveUI/blob/develop/.gitignore#L240) file so this should be as simple as adding a new line there.

**Comment by ghuntley** [comment]
Fixed in #1406
