### ISSUE TITLE
[BUG] Binding a ReactiveCommand to a ContextAction sends application into break mode

### ISSUE THREAD

**Issue by datoml** [reactiveui/ReactiveUI#1383]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When binding a ReactiveCommand in XAML inside a ContextAction the application stops when the command gets invoked.
```
<TextCell.ContextActions>
  <MenuItem Command="{Binding Path=DoSomeAwesomeStuff}" Text="Ask RNGesus" />
  <MenuItem Command="{Binding Path=DoNotSoAwesomeStuff}" Text="Old ICommand" />
</TextCell.ContextActions>
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

I have created a sample application with this exact behaviour.
[Sample](https://github.com/datoml/ReactiveUIContextActionsBug)

**What is the expected behavior?**
The command should be invoked.

**What is the motivation / use case for changing the behavior?**
-

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the latest stable and snapshot (http://docs.reactiveui.net/en/contributing/snapshot/index.html) versions.**
Currently I am only able to test it on an android device.
I also tried version 7.0.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
-

**Comment by ghuntley** [comment]
Thank-you for putting together a sample application.

**Comment by xamarindevelopervietnam** [comment]
I think is not a bug @datoml 
pls try this
<?xml version="1.0" encoding="utf-8" ?>
<reactive:ReactiveContentPage x:TypeArguments="local:MainPageModel"
                              xmlns="http://xamarin.com/schemas/2014/forms"
                              xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                              xmlns:reactive="clr-namespace:ReactiveUI.XamForms;assembly=ReactiveUI.XamForms"             
                              xmlns:local="clr-namespace:ContextActionsExample"
			      x:Name="MyMainPage"
                              x:Class="ContextActionsExample.MainPage">

    <StackLayout>
        <Label VerticalOptions="Start" HorizontalOptions="Center" Text="List of smart classes... yeah right" />
        <ListView x:Name="SmartClassList" VerticalOptions="FillAndExpand" HorizontalOptions="FillAndExpand">
            <ListView.ItemTemplate>
                <DataTemplate>
                    <TextCell Text="{Binding Path=RandomText}"
                              Detail="{Binding Path=RandomDetailText}">
                        <TextCell.ContextActions>
                            <MenuItem Command="{Binding Source={x:Reference MyMainPage}, Path=BindingContext.DoSomeAwesomeStuff}" Text="Ask RNGesus" />
                            <MenuItem Command="{Binding Source={x:Reference MyMainPage}, Path=BindingContext.Path=DoNotSoAwesomeStuff}" Text="Old ICommand" />
                        </TextCell.ContextActions>
                    </TextCell>
                </DataTemplate>
            </ListView.ItemTemplate>
        </ListView>
    </StackLayout>
</reactive:ReactiveContentPage>
