### ISSUE TITLE
ReactiveUI.Events - obnoxious wrong profile error

### ISSUE THREAD

**Issue by helzgate** [reactiveui/ReactiveUI#1384]
Brand new install of Visual Studio 2017 for Windows.  Brand new Xamarin Forms project.  I installed ReactiveUI nuget with no issues.  ReactiveUI.Events won't install, tells me wrong target profile 259.

here is my packages if this helps:
`<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Autofac" version="3.5.2" targetFramework="portable45-net45+win8+wp8+wpa81" />
  <package id="Newtonsoft.Json" version="10.0.2" targetFramework="portable45-net45+win8+wp8+wpa81" />
  <package id="reactiveui" version="7.4.0" targetFramework="portable45-net45+win8+wp8+wpa81" />
  <package id="reactiveui-core" version="7.4.0" targetFramework="portable45-net45+win8+wp8+wpa81" />
  <package id="Rx-Core" version="2.2.5" targetFramework="portable45-net45+win8+wp8+wpa81" />
  <package id="Rx-Interfaces" version="2.2.5" targetFramework="portable45-net45+win8+wp8+wpa81" />
  <package id="Rx-Linq" version="2.2.5" targetFramework="portable45-net45+win8+wp8+wpa81" />
  <package id="Rx-Main" version="2.2.5" targetFramework="portable45-net45+win8+wp8+wpa81" />
  <package id="Rx-PlatformServices" version="2.2.5" targetFramework="portable45-net45+win8+wp8+wpa81" />
  <package id="Splat" version="1.6.2" targetFramework="portable45-net45+win8+wp8+wpa81" />
  <package id="Xamarin.Forms" version="2.3.4.247" targetFramework="portable45-net45+win8+wp8+wpa81" />
  <package id="ZXing.Net.Mobile" version="2.2.9" targetFramework="portable45-net45+win8+wp8+wpa81" />
  <package id="ZXing.Net.Mobile.Forms" version="2.2.9" targetFramework="portable45-net45+win8+wp8+wpa81" />
</packages>`

**Comment by PureWeen** [comment]
If you use Profile44 for your PCLs then you can install it

**Comment by helzgate** [comment]
I get this error:
`Could not install package 'reactiveui-events 7.4.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.6,Profile=Profile44', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

**Comment by PureWeen** [comment]
oh ok I guess maybe I misinterpreted what's going on here

Reactiveui-Events is the platform specific package so you install the events package at the platform level for things like ios/android/winrt

for  xamarin forms where you have Xamarin Forms type things in a PCL then you'd install this
https://www.nuget.org/packages/reactiveui-events-xamforms/
Into the PCL

but this package
https://www.nuget.org/packages/reactiveui-events/
isn't really going to work at the PCL level because it contains events based on the platform (ios/android/windows) that it's being installed into

**Comment by helzgate** [comment]
That worked with profile 44.  Thanks!

**Comment by ghuntley** [comment]
Xamarin Forms has its own package as there's no way to target it with nuget. It doesn't have a TFM as it's a library.
