### ISSUE TITLE
Merge Xamarin/WindowsForms/Platform targets into one csproj (multiple nuget package IDs)

### ISSUE THREAD

**Issue by olevett** [reactiveui/ReactiveUI#1388]
***Note*: for support questions, please ask on StackOverflow: https://stackoverflow.com/questions/tagged/reactiveui . This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Targets that don't have a dedicated TFM are built as separate csproj files, which increases the maintenance overhead a bit.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**
Reducing maintenance overhead, and possibly creating an easier route to adding a new platform.

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the latest stable and snapshot (http://docs.reactiveui.net/en/contributing/snapshot/index.html) versions.**

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
I think it should be possible to do some csproj magic to effectively create a "target" of Xamarin.Forms for example, that creates a separate nuget package, effectively targets netstandard1.3 and includes the XamForms packages as required.

**Comment by ghuntley** [comment]
I can see this getting pretty messy. Visual Studio (for me) has been pretty sketchy with multi-targeting and at this stage would prefer not to complicate our builds further. Doing this would involve defining some custom property/leaning on @onovotny for some advice.  My preference is to leave things as is for now.

```xml
<PropertyGroup>
    <TargetFrameworks>netstandard1.1;net45;uap10.0;Xamarin.iOS10;Xamarin.Mac20;MonoAndroid70</TargetFrameworks>
    <PackageId>reactiveui</PackageId>
</PropertyGroup>
```

**Comment by onovotny** [comment]
I'm not sure I follow the suggestion? You want to have a single project generate different packages? That could be possible but does sound messy. Using files from a shared location via `Include="..\Shared\**\*.cs"` sounds cleaner?

**Comment by olevett** [comment]
My feelings aren't hugely strong on this, but I guess it's that we're effectively having to treat the XamForms, WinForms and other platforms very differently from the platforms that have TFMs supported (e.g. UWP, Tizen), and if we could effectively wrap XamForms to treat it as a separate platform, then we don't have the problem of shared code etc.

The other question is whether we should be treating XamForms/WinForms as a target for ReactiveUI or as a set of extensions that make it easier to integrate on top of the e.g. NetStandard/Net45 targets.
