### ISSUE TITLE
Modal WPF dialog from Interaction handler breaks ReactiveUI viewmodel

### ISSUE THREAD

**Issue by Wouterdek** [reactiveui/ReactiveUI#1396]
**Do you want to request a *feature* or report a *bug*?**
A bug.

**What is the current behavior?**
Opening a dialog (using OpenDialog()) from an interaction handler breaks ReactiveUI in the opened dialog. In my demo, ToProperty stops applying updates to the ObservableAsProperty value after the first change until the dialog is closed. When Open() is used instead, everything works as expected.

If the Interaction is not used, and the dialog is opened from a WPF click event handler, everything works as expected. Maybe a threading issue?

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
1. Download, open and run the attached VS2017 solution: [SSCCE.zip](https://github.com/reactiveui/ReactiveUI/files/1130651/SSCCE.zip)
2. A dialog with 2 buttons appears. Click "Open as window" to see the correct, intended behavior. Note that the "username" textbox has a red border when the textbox is empty. When text is entered, the red border disappears. Also note that this window is not modal (you can still interact with the first window). Close the window.
3. Click "Open as dialog". Note that the dialog no longer works correctly. Entering text in the username field does not make the red border disappear. Note that this window is modal.

**What is the expected behavior?**
Opening a modal dialog using OpenDialog() should not break the viewmodel behavior.

**What is the motivation / use case for changing the behavior?**
It is broken. My modal dialog doesn't work.

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the latest stable and snapshot (http://docs.reactiveui.net/en/contributing/snapshot/index.html) versions.**
I am running Windows 10 x64, and using Visual Studio 2017 for a WPF application.
I tested this with ReactiveUI v7.4.0 and v7.0.0, both showing identical behavior.
I tested this with .NET 4.7 and .NET 4.5.2, both showing identical behavior.

**Comment by Waterflames** [comment]
Additional testing seems to confirm this is a threading bug.

Changing
```C#
ViewModel.OpenAsDialogInteraction.RegisterHandler(interaction =>
{
    TestDialog dialog = new TestDialog
    {
        ViewModel = new TestDialogViewModel()
    };
    dialog.ShowDialog();

    interaction.SetOutput(Unit.Default);
}
```
to
```C#
ViewModel.OpenAsDialogInteraction.RegisterHandler(async interaction =>
{
    await Observable.Range(0, 1).ObserveOn(RxApp.MainThreadScheduler);

    TestDialog dialog = new TestDialog
    {
        ViewModel = new TestDialogViewModel()
    };
    dialog.ShowDialog();

    interaction.SetOutput(Unit.Default);
}
```
seems to fix the problem.

**Comment by Waterflames** [comment]
I just found #1205, which would be a perfect fix for this.

**Comment by kentcb** [comment]
I don't believe this to be a bug. The `RegisterHandler` API you're calling is explicitly called out as being _synchronous_, not _asynchronous_. Its main use case is for unit tests. Calling a blocking API like WPF's `ShowDialog` will have nasty side effects, as you've observed. Changing the API to use scheduling means it is no longer synchronous and breaks the contract of the API (and many existing unit tests in the process).

Instead, you should either use an asynchronous API to show the dialog (such as those provided by MahApps metro) or you should perform the work asynchronously, returning an observable representing that work, thereby using the _asynchronous_ `RegisterHandler` API:

```C#
ViewModel.OpenAsDialogInteraction.RegisterHandler(interaction =>
                {
                    TestDialog dialog = new TestDialog
                    {
                        ViewModel = new TestDialogViewModel()
                    };
                    return Observable.Start(() =>
                    {
                        dialog.ShowDialog();
                        interaction.SetOutput(Unit.Default);
                    }, RxApp.MainThreadScheduler);
                })
```
```

**Comment by Wouterdek** [comment]
That works for me. 
Thanks.

**Comment by trucksmart** [comment]
@Wouterdek you could also create an extension method for this:

```c#
public static IDisposable RegisterHandlerForDialog<TInput, TOutput>(
    this Interaction<TInput, TOutput> interaction,
    Action<InteractionContext<TInput, TOutput>> handler)
{
    return interaction.RegisterHandler(inter => Observable.Start(() =>
    {
        handler.Invoke(inter);
        return Unit.Default;
    },
    RxApp.MainThreadScheduler));
}
```

I used this all the time for some of our WinForms applications.  I wonder if this could be added to the framework?
