### ISSUE TITLE
(7.5-alpha)  ObserveOn adds System.Windows.Forms dependency 

### ISSUE THREAD

**Issue by BHandle** [reactiveui/ReactiveUI#1400]
In version 7.4, you can use the .ObserveOn(IScheduler) extension methods without any dependency on System.Windows.Forms.  In upgrading to the latest alpha (in order to leave Rx behind), the compiler yells that Control requires System.Windows.Forms v4.0.0.0.

**Repro**
1.  Create a new .Net 4.7 framework console application, and add the Alpha 7.5.0-alpha package.

2.  Add a reference to WindowsBase.dll

3. Modify the Program.cs to the following:

```CS
using System;
using System.Reactive.Concurrency;
using System.Reactive.Linq;
using System.Reactive.Subjects;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            Subject<string> a = new Subject<string>();
            a.ObserveOn(ThreadPoolScheduler.Instance).Subscribe(x => Console.Write(x));    //<<ObserveOn needs System.Windows.Forms so it can resolve Control, even though we just want to hand it a scheduler.
//please also ignore the 'why' you might want to do this, the same problem exists for any scheduler.
        }
    }
}
```

4. Note that there is now a requirement on System.Windows.Forms

System.Windows.Forms should not be required to use schedulers for non-winforms projects, especially WPF.  This appears to have been introduced by the changeover to the newer System.Reactive and is not an issue with 7.4.  This is an issue with 7.5-alpha30, and may be related to a binding redirect.

**Comment by ghuntley** [comment]
@PixelHero thank-you for the repro and high quality bug report. 👍

**Comment by ghuntley** [comment]
Looking into this over at https://github.com/reactiveui/ReactiveUI/pull/1411
