### ISSUE TITLE
Subscribe not found in ReactiveCommand as documented

### ISSUE THREAD

**Issue by fahadash** [reactiveui/ReactiveUI#1402]
I pulled latest Nuget 7.4.0.0 package and now Subscribe is not a method of ReactiveCommand.

The [main page sample](https://github.com/reactiveui/ReactiveUI#update-the-user-interface) Continues to use it as if it does exists. 

The [unit tests for ReactiveCommand](https://github.com/reactiveui/ReactiveUI/blob/develop/src/ReactiveUI.Tests/ReactiveCommandTest.cs) seem to not have it, they rather are using .Execute().Subscribe() which is not really what I want but even that is not found.

[The documentation site](https://docs.reactiveui.net/en/user-guide/commands/reactive-commands.html) continues to say the following

> Reactive commands are themselves observable. Whenever any execution of the command completes, the result will tick through the command itself.

**Comment by kentcb** [comment]
Hi @fahadash. Per the documentation, Reactive commands are observable. But observables don't define `Subscribe` for you - that's an extension method provided by Rx. You're likely just missing a `using System;`.

Feel free to re-open if that doesn't help.

**Comment by fahadash** [comment]
I don't have proper access to reopen it. I have the following using statements already added with no hint of Subscribe.

using System;
using System.Reactive.Linq;
using ReactiveUI;

**Comment by kentcb** [comment]
OK, have reopened. Only other thing I can think of is your reference to `System.Reactive.Core.dll` may be screwed up. Let us know. If not, we may need a standalone repro to diagnose further.

**Comment by kentcb** [comment]
Regarding the interfaces of `ReactiveCommand`, that is just a base class for various reactive command subclasses. You most likely want `ReactiveCommand<TParam, TResult>`. Can you show us more code in context? Perhaps you're just using the wrong command type?

**Comment by fahadash** [comment]
Ok I think I found the issue. My declaration of the command is 'ReactiveCommand' instead of 'ReactiveCommand<blah, blah>'.
