### ISSUE TITLE
.NET Core Compatible Build

### ISSUE THREAD

**Issue by jkoritzinsky** [reactiveui/ReactiveUI#1417]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Referencing ReactiveUI (v8 alpha) in .NET Core crashes in PlatformRegistrations since it is pulling in the .NET Standard build that throws the exception.

**What is the expected behavior?**
ReactiveUI references common services, or registers nothing at all without throwing an exception when referencing it in .NET Core.

**What is the motivation / use case for changing the behavior?**
No .NET Core apps or UI frameworks that run on .NET Core can use ReactiveUI (such as Avalonia).

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the latest stable and snapshot (http://docs.reactiveui.net/en/contributing/snapshot/index.html) versions.**
All versions have this bug in their PCL versions, but it is only applicable to v8 since v8 is the only one that is referencable by a .NET Core app.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
Either make the .NET Standard build not throw or add a .NET Core build that doesn't throw and keep the .NET Standard build throwing.

**Comment by ghuntley** [comment]
Let's keep the platform throwing exception. It puts people on the happy path and reduces the amount of frivolous GitHub issues.

:+1: to adding netcore build target. We have people who run ReactiveUI serverside and I've been meaning to do this. I welcome a PR - if you need help let me know.

**Comment by pellea** [comment]
I'm trying to use the 8.0.0-alpha0055 in a aspnet core app. When I do, I get this exception "You are referencing the Portable version of ReactiveUI in an App. Reference the platform-specific version.".

Is this linked to the issue above and the referenced one?

**Comment by ghuntley** [comment]
@pellea can you please try with `.8.0.0-alpha0061` from NuGet as .NET Core support was only merged recently. Open a GitHub issue if you run into problems.

**Comment by pellea** [comment]
@ghuntley  It's working. Thanks.

**Comment by ghuntley** [comment]
<3
