### ISSUE TITLE
The themes directory hasn't been included in `reactiveui-wpf` so the templates don't resolve

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/ReactiveUI#1424]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

* Views inside a VMVH not appearing.

**What is the expected behavior?**

* Views inside a VMVH appears.

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the latest stable and snapshot (http://docs.reactiveui.net/en/contributing/snapshot/index.html) versions.**

`reactiveui-v8-alphas`

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

* Bug introduced by https://github.com/reactiveui/ReactiveUI/pull/1406
* https://reactivex.slack.com/archives/C02AJB872/p1502701680528015

**Comment by ghuntley** [comment]
Thoughts -> Are these themes specifically for `net452 aka wpf` or are they shared? Should we relocate their place on the filesystem as well.

**Comment by olevett** [comment]
@kentcb did https://github.com/reactiveui/ReactiveUI/pull/1427 end up fixing this issue? It feels like it should have done...

**Comment by olevett** [comment]
Closing this as I think it's a duplicate of #1381, and has been resolved as per #1427. Can reopen if that's incorrect.

**Comment by ghuntley** [comment]
Yup. This is a dupe. Thx Olly.
