### ISSUE TITLE
Add AutoSuspendHelper to XF

### ISSUE THREAD

**Issue by kentcb** [reactiveui/ReactiveUI#1429]
**Do you want to request a *feature* or report a *bug*?**

Feature.

**What is the current behavior?**

There is no `AutoSuspendHelper` on XF.

**What is the expected behavior?**

XF should ship with an `AutoSuspendHelper` per the pattern established by other platforms.

**What is the motivation / use case for changing the behavior?**

Consistency, reduce friction of using auto suspension on XF.

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the latest stable and snapshot (http://docs.reactiveui.net/en/contributing/snapshot/index.html) versions.**

7/8.

**Comment by garyng** [comment]
Is there any examples of using `AutoSuspendHelper` in `Xamarin.Forms`?

**Comment by glennawatson** [comment]
Closed by https://github.com/reactiveui/ReactiveUI/pull/2523
