### ISSUE TITLE
Packages not published to MyGet

### ISSUE THREAD

**Issue by kentcb** [reactiveui/ReactiveUI#1434]
***Note*: for support questions, please ask on StackOverflow: https://stackoverflow.com/questions/tagged/reactiveui . This repository's issues are reserved for feature requests and bug reports.**

**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

packages no longer pushed to MyGet as part of a successful build

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

build and check myget after success

**What is the expected behavior?**

packages should be pushed to myget

**Comment by kentcb** [comment]
Workaround:

- Visit https://ci.appveyor.com/project/dotnetfoundation/reactiveui and click "new build"

**Comment by ghuntley** [comment]
This should now be fixed. It appears that ReactiveUI > Settings > WebHooks > AppVeyor was configured incorrectly. Monitoring.....

**Comment by vatsalyagoel** [comment]
This issue should now be closed

**Comment by glennawatson** [comment]
This is fixed under VSTS.
