### ISSUE TITLE
Make ViewContractAttribute.Contract public

### ISSUE THREAD

**Issue by alexeyzimarev** [reactiveui/ReactiveUI#1440]
The `ViewContractAttribute.Contract` property is currently internal. This makes perfect sense because it is only used in the `IMutableDependencyResolver` extension method.

However, we would also use this attribute to support another type of container (Autofac). We use this code: https://github.com/alexeyzimarev/ReactiveUI.Autofac/pull/2/files#diff-79d85e72a88e19d0308087e4c1091914R29

When the `Contract` property is internal, we cannot access it. So the adapter is not working for RxUI 7 onwards, only for 6.5. I think there is no issue making `Contract` public again.

**Comment by ghuntley** [comment]
@alexeyzimarev send in the pull-request. The constructor is public thus anything you pass into it should also be public.
