### ISSUE TITLE
Developer experience when using ReactiveUI with Visual Studio for Mac

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/ReactiveUI#1447]
**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**

```
=== Visual Studio Enterprise 2017 for Mac (Preview) ===

Version 7.2 Preview (7.2 build 583)
Installation UUID: 5445a492-fcd9-4a1d-9dc7-d2a3456b3ec2
Runtime:
	Mono 5.4.0.174 (2017-06/1afb931de69) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 504000174

=== NuGet ===

Version: 4.3.0.4199

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Version: 2.0.0
SDK: /usr/local/share/dotnet/sdk/2.0.0/Sdks
SDK Version: 2.0.0
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.4.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.5.6
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 8.3.3 (12175.1)
Build 8E3004b

=== Xamarin.iOS ===

Version: 10.14.0.26 (Visual Studio Enterprise)
Hash: 416f778f
Branch: d15-4
Build date: 2017-08-25 17:30:05-0400

=== Xamarin.Android ===

Version: 7.5.0.15 (Visual Studio Enterprise)
Android SDK: /Users/ghuntley/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.1    (API level 16)
		4.2    (API level 17)
		4.3    (API level 18)
		4.4    (API level 19)
		4.4.87 (API level 20)
		5.0    (API level 21)
		5.1    (API level 22)
		6.0    (API level 23)
		7.0    (API level 24)
		7.1    (API level 25)

SDK Tools Version: 25.2.5
SDK Platform Tools Version: 25.0.5
SDK Build Tools Version: 25.0.3

Java SDK: /usr
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin.Mac ===

Version: 3.8.0.26 (Visual Studio Enterprise)

=== Xamarin Inspector ===

Version: 1.3.0
Hash: 8c298a5
Branch: 1.3-release
Build date: Thu, 14 Sep 2017 21:21:26 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 702000583
Git revision: 861d3eb8f64655762b85235dde49874645208f51
Build date: 2017-09-05 15:23:48-04
Xamarin addins: 838dc0d12bdbb0407ea44b7bfd11fbe30ddac07b
Build lane: monodevelop-lion-d15-4

=== Operating System ===

Mac OS X 10.12.6
Darwin 16.7.0 Darwin Kernel Version 16.7.0
    Thu Jun 15 17:36:27 PDT 2017
    root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

DotNetCoreSupportAnyTargetFramework 1.0
Gist Ide Information 1.1.0
NuGet Package Explorer 0.2
xUnit.NET 2 testing framework support 0.7.5
Redth's Addins 1.0.9
Vim 0.37.3
```

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by ghuntley** [comment]
# Background
File -> New Xamarin.Forms application creates a Profile111 library, Xamarin iOS and Xamarin Android application (version?) application.

# Profile111
* Installs cleanly.

# Android
* Does not install due to #1413 and https://github.com/NuGet/Home/issues/5463

# iOS
* Does not install due to #1485 and https://github.com/NuGet/Home/issues/5463

**Comment by ghuntley** [comment]
# NET461 Class Library

File -> New Class Library (NET461)

# `reactiveui-winforms`
* Installs cleanly
* Adds reference to `windows.system.forms` as expected
* Not tested how bait/switch functions with actual test.

# `reactiveui-wpf`
* Installs cleanly
* Does not add reference to `PresentationCore` or `PresentationFramework`
* Not tested how bait/switch functions with actual test.

**Comment by ghuntley** [comment]
Note: Kent mentions workaround to `'System.Reactive.4.0.0-preview00001'` being installed is to install `System.Reactive-3.1.1` before installing ReactiveUI.

**Comment by giusepe** [comment]
Correct me if I'm wrong, but I believe this is fixed. 
I just created a clean project, installed ReactiveUI.XamForms into it and worked. 
@ghuntley  @kentcb Can we close it?

**Comment by Qonstrukt** [comment]
Regarding installing the packages into a new project, yes this works quite admirably.

**Comment by khadeeja-alif** [comment]
Tried Installing packages to new project ,it din't work.
Could not install package 'ReactiveUI 8.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework.

Could not install package 'ReactiveUI.XamForms 8.0.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework.

**Comment by giusepe** [comment]
@khadeeja-alif You are trying to install RxUI 8 on a PCL project, first convert it to .Net Standard and then install the new version of RxUI.

**Comment by Kavignon** [comment]
What’s the current state of this?

**Comment by giusepe** [comment]
@Kavignon It's working perfectly.
