### ISSUE TITLE
Xamarin forms binding perf vs  RxUI bindings perf

### ISSUE THREAD

**Issue by dhaligas** [reactiveui/ReactiveUI#1464]
**Do you want to request a *feature* or report a *bug*?**

Can we get some measurements of Xamarin Forms bindings vs RxUI bindings + findings documented + repeatable repro committed into `reactiveui/reactiveui`

See also https://twitter.com/s_delcroix/status/897853088593301505 and https://github.com/xamarin/Xamarin.Forms/blob/a6bbed029c64d2d64b74eeb67e27a099abf70664/Xamarin.Forms.Xaml.UnitTests/BindingsCompiler.xaml

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

Issue creation requested by @ghuntley

**Comment by RLittlesII** [comment]
Following up on this.  A Benchmark solution is being added to ReactiveUI in the coming release.  With this change we have the ability to Benchmark code that targets various [.NET Runtimes](https://benchmarkdotnet.org/articles/configs/toolchains.html).  Unfortunately, we are unable to target Xamarin.iOS or Xamarin.Android directly at this time.  As of now, it isn't on the road map.

So we can target getting RxUI Bindings performance benchmarks, but we won't be able to compare those to Xamarin.Forms performance.
