### ISSUE TITLE
nuget.exe shows up as modified after a fresh clone and build

### ISSUE THREAD

**Issue by eatdrinksleepcode** [reactiveui/ReactiveUI#1466]
**Do you want to request a *feature* or report a *bug*?**

Call it a "less-than-optimal contributor experience"

**What is the current behavior?**

On a fresh clone, running the build results in a modified nuget.exe file in the Git workspace.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

```
> git clone https://github.com/reactiveui/ReactiveUI.git
> cd ReactiveUI
> ./build.sh # Same behavior is expected for build.cmd
```
```
Checking for updates from https://www.nuget.org/api/v2/.
Currently running NuGet.exe 3.5.0.
Updating NuGet.exe to 4.3.0.
Update successful.
...
```
```
> git status
...
Changes not staged for commit:
...
	modified:   tools/nuget/nuget.exe
...
```
**What is the expected behavior?**

Building an unmodified copy of the source should not result in new changes to the source.

**What is the motivation / use case for changing the behavior?**

- It is not easy to tell with a glance at ```git status``` whether there are "real" outstanding changes or what they are.
- A contributor must be careful not to accidentally include this modified file when committing.

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**

It has apparently been this way since ```build.cmd``` and ```build.sh``` were added in 8f9731d4 (although nuget.exe has been updated a couple of times since then, which would have created brief periods where it would not have been noticeable).

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

At minimum, the nuget.exe should be copied to an ignored location and updated there. This will keep the working copy clean.

However, I would also suggest that nuget.exe should NOT be automatically updated as part of the build. This introduces non-determinism into the build, where you cannot predict ahead of time what version of NuGet will be used, and building the same source on different machines or at different times could have different outcomes due to the different version of the tool used. This is particularly true at the moment, with the tool being updated across major versions (3 -> 4).

If there is a desire to keep NuGet up to date, I would suggest using a [canary build](https://www.thoughtworks.com/radar/techniques/canary-builds), which could update NuGet and run the build, and if it passes, raise a PR with the updated version.

**Comment by eatdrinksleepcode** [comment]
Happy to submit a PR for this. @ghuntley do you have a preference between:

1. Copying nuget.exe to an ignored location and updating it there
OR
2. Not updating nuget.exe as part of the build at all (and relying on PRs to update nuget.exe as necessary)

**Comment by glennawatson** [comment]
This no longer happens.
