### ISSUE TITLE
Contributor guidlines refer to 'master' instead of 'develop'

### ISSUE THREAD

**Issue by eatdrinksleepcode** [reactiveui/ReactiveUI#1467]
**Do you want to request a *feature* or report a *bug*?**

Contributor documentation bug

**What is the current behavior?**

Contributor documentation states to make changes on top of and submit them to the ```master``` branch.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

[CONTRIBUTING.md](CONTRIBUTING.md#submitting-a-pull-request) states:

```
Make your changes in a new git branch:
  git checkout -b my-fix-branch master
```
and:
```
In GitHub, send a pull request to reactiveui:master
```

**What is the expected behavior?**

It appears from looking at recent PRs that the expectation for this repo is that changes are made on top of and submitted to the ```develop``` branch, instead of the ```master``` branch.

**What is the motivation / use case for changing the behavior?**

Smoothing out first-time contributor experience

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**

These particular guidelines were added in b96042d; and it does appear that at that time, some form of master branch strategy was in use. I am unsure when the ```develop``` branch was introduced.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by ghuntley** [comment]
@eatdrinksleepcode ugh that's terrible (of us!) - nice catch. Please send in the PR to `develop`
