### ISSUE TITLE
Build status badge is out of date

### ISSUE THREAD

**Issue by eatdrinksleepcode** [reactiveui/ReactiveUI#1471]
**Do you want to request a *feature* or report a *bug*?**

README bug

**What is the current behavior?**

The build status badge on the README.md is referring to the "ghuntley/reactiveui" project in AppVeyor, which is reporting the build status as "unknown".

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

See the [repo home page](https://github.com/reactiveui/ReactiveUI)

**What is the expected behavior?**

Presumably the build status badge should be referring to the "dotnetfoundation/reactiveui" project, which is running for PRs.

**What is the motivation / use case for changing the behavior?**

Radiating the status of the build is a good indicator of the status of the project to potential new contributors (and good motivation to keep the build green 😀)

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**

N/A

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

I would submit the PR to fix it myself, but AppVeyor appears to want the internal project ID in the build status link, and I was not able to find that ID with a quick search. Someone with direct access to the AppVeyor build could probably find it faster.

**Comment by ghuntley** [comment]
Fixed in https://github.com/reactiveui/ReactiveUI/pull/1478 - thanks for reporting this. Small yet important contribution.
