### ISSUE TITLE
Cake.PinNuGetDepenencies needs upgrading to Cake 0.22 soon or our builds will break

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/ReactiveUI#1474]
Received some advanced heads up from the Cake team

> FYI just a heads up, like with 0.16.x, 0.22.0 will have several breaking changes, so we will require addins to reference Cake.Core 0.22.0 or newer to be loaded, there's a "your one your own anything can happen" setting to skip verification but we recommend to start targeting the newer version as soon as possible post release. Example usage to skip verification
`Cake.exe --settings_skipverification=true`
> 
> Cake.Core 0.22.0 pre-release is already on MyGet so you can start to test with that, for most it's probably just a recompile, for modules and similar it can i.e. require implementing new members.
https://www.myget.org/gallery/cake This will be an epic release as we've unified around one scripting engine across all platforms, started work on removing need for nuget.exe for addin/tool directives and support dependencies for those (new nuget handling will be opt-in and described in blog post how to do so).  This means bootstrapping will be easier and more consistent across platforms and hopefully targeting .NET Standard 1.6 will be enough to work across all platforms (testing that now), obviously multi targeting will still be supported for platform specific scenarios, but in many cases one assembly will be enough.This also means that we will get up to speed with the latest C# features without the need for the _experimental_ flag. There's also a several bug fixes and new features so all in all this release will rock :wink:

**Comment by gep13** [comment]
@ghuntley to be clear, if your builds are pinned to a specific version of Cake, your builds won't break.  However, if you change your build to use the soon to be released version of Cake, then addin's that you depend on will have to be updated to compile against that new version, or you will need to use the skip verification option.

**Comment by ghuntley** [comment]
We have a heap of non-determism in our builds currently. Things aren't pinned etc.

**Comment by gep13** [comment]
Ah, gotcha.  In which case, this will be an issue 😄

**Comment by gep13** [comment]
Adding a `packages.config` file here: https://github.com/reactiveui/ReactiveUI/tree/develop/tools

Would be a first step.

https://youtu.be/xq41JgaGN7k

**Comment by ghuntley** [comment]
@gep13 check out http://embedyoutube.org by @sviridovserg. I use that site on the daily, so so often. Thanks for building it Sergei!

**Comment by gep13** [comment]
[![Pin Cake Versions](http://img.youtube.com/vi/xq41JgaGN7k/0.jpg)](http://www.youtube.com/watch?v=xq41JgaGN7k "Pin Cake Versions")

**Comment by gep13** [comment]
@ghuntley I was going to ask how you are generating the images.  I knew that it was possible, but it is a bit of a hassle to do it manually!  Great site!

**Comment by sviridovserg** [comment]
@ghuntley  thank you for idea 👍

**Comment by olevett** [comment]
This doesn't look quite like it's working, as per https://ci.appveyor.com/project/dotnetfoundation/reactiveui/build/1.0.173
```
Attempting to gather dependency information for package 'Cake.0.22.0' with respect to project 'tools', targeting 'Any,Version=v0.0'
```
