### ISSUE TITLE
InvokeCommand not executed in v8 where v7.4 would

### ISSUE THREAD

**Issue by Qonstrukt** [reactiveui/ReactiveUI#1476]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`InvokeCommand` isn't invoking the command in some situations where ReactiveUI 7.4 would.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
See the following repo: https://github.com/Qonstrukt/RxUI-8-InvokeCommand

The `WhenAnyObservable` chain at the end of the `WhenActivated` block in the `ViewController` never sees the command in the end actually invoking.

This while pressing all of the buttons actually does work, even the one that in the end also performs `InvokeCommand`. This makes me believe this might also be a bug in Rx 3.1.1. **Or** I'm doing something very wrong, which is also an option. 😉 But then I'm wondering why it does work with RxUI 7.4 and Rx 2.x.

**What is the expected behavior?**
The command actually invoking at the end of the pipeline like with Rx 2.x and RxUI 7.4.

**What is the motivation / use case for changing the behavior?**

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**
This seems broken in 8.0.0-alpha0081, but was ok with 7.4.0.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
I'm unable to get my own build of RxUI working at the moment, so debugging this further isn't possible for me.

**Comment by Qonstrukt** [comment]
I've added a branch `rxui74` which uses ReactiveUI 7.4.0, but is exactly the same code. Here the command is invoked properly: https://github.com/Qonstrukt/RxUI-8-InvokeCommand/tree/rxui74

**Comment by ghuntley** [comment]
@kentcb can you have a 👓 of this please?

**Comment by kentcb** [comment]
Pretty sure this is related to [this](https://github.com/Reactive-Extensions/Rx.NET/issues/444) unexpected behavior/bug. In previous RxUI we had our own `WithLatestFrom` implementation that works how you'd expect, but Rx doesn't work like that. Quite a few people have brought it up, but it's never been addressed.

I guess I'll have to add our own `WithLatestFrom` back in. _sigh_

**Comment by kentcb** [comment]
Fixed by #1534
