### ISSUE TITLE
Reviewers links are broken on readme.md

### ISSUE THREAD

**Issue by VeneetReddyK** [reactiveui/ReactiveUI#1481]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
These links give 404

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
click on the links

**What is the expected behavior?**
open valid page

**What is the motivation / use case for changing the behavior?**
Allows people to apply to be on review team

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**
Latest

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
Links lead to valid pages

**Comment by ghuntley** [comment]
Howdy @VeneetReddyK you need to be part of the ReacitveUI organization to be able to join these teams. I'm happy to send over a invitation, which platforms are you interested in?

**Comment by glennawatson** [comment]
I believe this one has been resolved by moving them out now.
