### ISSUE TITLE
Add ﻿memory leak tests (ReactiveUI.LeakTests) to assert even more correctness

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/ReactiveUI#1486]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the motivation / use case for changing the behavior?**

See https://github.com/AvaloniaUI/Avalonia/tree/master/tests/Avalonia.LeakTests

![image](https://user-images.githubusercontent.com/127353/30769622-53b7e4f8-a060-11e7-8eeb-cc8241fc0b84.png)

**Comment by riktimmondal** [comment]
I will like to work on it.Please can you tell how to approach it

**Comment by ghuntley** [comment]
Neat @riktimmondal! We would love to have a contribution from you.

Okay so what's needed is:

* Create `NET461` project called `ReactiveUI.LeakTests` in `~/src/`
* Reference `ReactiveUI` from `ReactiveUI.LeakTests`
* Install Package https://www.nuget.org/packages/JetBrains.DotMemoryUnit/
* Install Package Xunit

Open up the PR for review at that stage and we can have progress conversations on what should be tested and how we are going to hook this up into CI.

**Comment by ghuntley** [comment]
Reference reading material:
* https://blog.jetbrains.com/dotnet/2015/03/04/unit-testing-and-memory-profiling-can-they-be-combined/
* https://www.infoworld.com/article/3184892/application-development/working-with-the-dotmemory-unit-framework.html

**Comment by ghuntley** [comment]
Study the implementation over at https://github.com/AvaloniaUI/Avalonia/tree/master/tests/Avalonia.LeakTests for ideas. 👍

**Comment by GKotfis** [comment]
@riktimmondal are you working on this?

**Comment by ghuntley** [comment]
This has been implemented. Thank-you @GKotfis
