### ISSUE TITLE
XmlnsDefinition and XAML Themes are not included/defined for UAP

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/ReactiveUI#1494]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Regression

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

* `[assembly:XmlnsDefinition("http://reactiveui.net", "ReactiveUI")]` is not defined in UAP builds.
* The XAML theme (`<Page Include="Themes\generic-winrt.xaml">`) is not included in UAP builds.

**What is the expected behavior?**

https://github.com/reactiveui/ReactiveUI/blob/522170ebbe6a3e0c284136a473c18ba1b82a66bf/src/ReactiveUI/Xaml/Attributes.cs
https://github.com/reactiveui/ReactiveUI/blob/522170ebbe6a3e0c284136a473c18ba1b82a66bf/src/ReactiveUI/ReactiveUI_UWP.csproj#L124-L127

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**

Comparing implementation of `master` to `develop` shows that there has been a regression.

**Comment by ChrisPulman** [comment]
Project has been retired.
