### ISSUE TITLE
reactive-ui events doesn't have the WPF target anymore in 8.0 alpha 89

### ISSUE THREAD

**Issue by bradphelan** [reactiveui/ReactiveUI#1495]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

![image](https://user-images.githubusercontent.com/17650/31131619-ece7284e-a85a-11e7-83d0-ea50e64f569d.png)

missing dotnet45 

*

**Comment by bradphelan** [comment]
Damn I looked at the csproj file and it's too much multi-targetting Foo for me to fix.

If somebody fix this by tomorrow morning Austria time I've got 20euro donation for ReactiveUI in my pocket :)

**Comment by ghuntley** [comment]
@bradphelan it has been split out to `reactiveui-events-wpf` https://www.nuget.org/packages/reactiveui-events-wpf/8.0.0-alpha0089 otherwise VS4Mac w/NET45 explodes when it comes across the `Windows.Presentation` reference.

**Comment by bradphelan** [comment]
oh that easy .... :( I was having a bad day
