### ISSUE TITLE
Create robot that automatically sends the contributor an invitation to join the GitHub org when their PR is merged

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/ReactiveUI#1501]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the motivation / use case for changing the behavior?**

[![](http://img.youtube.com/vi/Krad7zyr9U8/0.jpg)](http://www.youtube.com/watch?v=Krad7zyr9U8 "")

**Comment by erickzhao** [comment]
Hey @ghuntley, this seems like a really cool project. I'm interested in taking this one up! So I create a new repository and send a link when it's ready?

**Comment by ghuntley** [comment]
@erickzhao neat. I'd love have this in existence. Right now I'm doing this manually ugh.

# Goals
- When someone submits a pull request
     - If user is already part of the organization AND has a pending invitation to join the organization-> do nothing
     - If user is not part of the organization AND does not have a pending invitation to join the organization -> send them an invite

# How
I'd recommend starting by forking https://github.com/behaviorbot/welcome and coming up for a name for your new robot (`badge`?) then moving on to studying how the GitHub API works.

The bot would be a `maintainer` in the ReactiveUI `Community` team should grant them privileges to invite/add people to the team. 

![image](https://user-images.githubusercontent.com/127353/31260711-78ad5866-aa9b-11e7-976d-46ca30443bfa.png)

Once you have done some study then I'd suggest creating your own GitHub organization (it's free) and get it working over there. Keep us updated as you progress and if you have any questions then just ask :)

**Comment by erickzhao** [comment]
Thanks a lot for the tips! I'll get started as soon as possible. :)

**Comment by erickzhao** [comment]
Hey @ghuntley, small update on my progress so far! I managed a minimal viable product up, where I run the bot locally with `npm start` and it does its stuff.

You can check it out here: https://github.com/erickzhao/badge

![Screenshot](https://i.imgur.com/XaWGmbx.png)

(The screenshot shows a simulated webhook, but 

What it currently does:
* Receives webhook from GitHub
* Checks for pull_request.closed action.
* Does nothing if action user is a bot, if pull request was closed without merging, or if repository is not part of an organization.
* If all checks are passed, use GitHub API to send organization request to user.

Todo:
- [ ] Write tests
- [ ] Clean up code
- [ ] Write usage docs
- [ ] Deploy

Possible improvements:
- [ ] Add CI
- [ ] Allow users to customize the organization that they're invited to
- [ ] If user is invited, give users the option to enable the bot to comment on the PR that was merged.
- [ ] Add CONTRIBUTING.md

I'll be improving it (and figuring out how to deploy to the cloud) pretty soon. I'm pretty swamped with schoolwork until Friday, though, so look for another update probably this weekend!

**Comment by ghuntley** [comment]
![](https://media.giphy.com/media/l46CnpmLlLhjzSa88/giphy.gif)

**Comment by ghuntley** [comment]
I've added it to the ReactiveUI organization so you now have your very first user. Before progressing too much further I'd suggest implementing analytics/telemetry/log capture via Sentry.io (information on this is in the Probot documentation). Then move onto creating some tests, then finally setting up CI with Heroku. Once you have all that setup then move onto progress/other features such as:

Provide configuration option via `yaml` that allows a consumer to specify whether `addOrgMembership` or `addTeamMembership` is used. Currently L24 always uses addOrgMembership:

```
      response = await context.github.orgs.addOrgMembership(memberPayload);
```

Would like to have see configuration option that allows maintainers to specify that the contributor is invited to a team and have configuration option to specify the identifier of the team that the contributor is invited to.

**Comment by erickzhao** [comment]
@ghuntley I just enabled 2FA and accepted the organization invitation. 😄 

I'll work on the things you mentioned first! I'll update the checklist as I go and leave another comment when I'm done. :)

By the way, do you know of a way we can make this count as a Hacktoberfest project, since I won't be submitting any PRs directly to any repositories?

**Comment by ghuntley** [comment]
It works!

![image](https://user-images.githubusercontent.com/127353/31423909-1fe29f3c-aea3-11e7-950d-3037f0797583.png)

![image](https://user-images.githubusercontent.com/127353/31423914-25c19412-aea3-11e7-88bb-0731ceb35263.png)

**Comment by ghuntley** [comment]
> By the way, do you know of a way we can make this count as a Hacktoberfest project, since I won't be submitting any PRs directly to any repositories?

Send in a pull-request to the `reactiveui/website` repository tagging this issue using this language in the commit message `fixes https://github.com/reactiveui/ReactiveUI/issues/1501` explaining that people who contribute get an invitation to join the ReactiveUI org on this page https://reactiveui.net/docs/thanks/

**Comment by erickzhao** [comment]
Hey @ghuntley! Four midterms, one assignment, and one interview later, I've gotten a decent amount of progress on `badge` so far. I've been updating my checklist as I've been going, but the summary is that I got Sentry and Travis CI working, wrote a bunch of unit tests (should cover most cases), and tested it in `badge-test-repo`.

My only issue right now is getting `context.github.paginate` to mock correctly in unit tests, so I haven't enabled it. Right now, badge is only getting the first page of teams for an org and checking the team name in the config against those, so organizations with over 30 teams might experience some difficulties.

Everything else should be working smoothly, though! Let me know if you have any other concerns about functionality or code quality. I'll be writing docs and sprucing stuff up!

Also, I'll make the PR to ReactiveUI/website right now. :)

Cheers!

**Comment by erickzhao** [comment]
Small update: showed the app to the Probot maintainers and decided to change `badge` to `invite-contributors` as it is clearer (albeit less sexy) and avoids confusion with repository badges/shields. :)

https://github.com/probot/probot.github.io/pull/78

**Comment by ghuntley** [comment]
`invite-contributors` is a great name. That's a really good change. Don't forget to rename the `badge.yml`. I've had to temporarily disable the robot as it looks like something occurred that shouldn't of happened. The robot demoted my access. Ooops. Can you please investigate & resolve 👍 

![image](https://user-images.githubusercontent.com/127353/31759141-23c61746-b4fc-11e7-9bfa-afb44fde95d4.png)

**Comment by erickzhao** [comment]
>Don't forget to rename the badge.yml

Good catch! I've scrubbed the name `badge` away from `package.json` and `test/index.js` as well.

>The robot demoted my access on the organization.

I noticed that this bug occurred 7 days ago. Could you potentially check again? I think that this case was handled in [a later commit](https://github.com/erickzhao/invite-contributors/commit/46f4078b2d1e7802b0719bf278370a78305299ff). From then on, the bot only invites if `getOrgMembership()` throws an error.

I ran a simulation where I invited myself into `badge-test-repo`, and it ran into the `return` clause I was already in the organization.

![Test Case](https://i.imgur.com/TZcsp6B.png)

The `terminates if user was already in organization` test should already handle this case as well. Let me know if this still occurs on your end, and I'll try to take a deeper look.

**Comment by erickzhao** [comment]
Hey @ghuntley have you tried using the app lately? I've also gotten it to work for outside collaborators! :)

**Comment by ghuntley** [comment]
Yup - we are using it in production. Thank-you @erickzhao
