### ISSUE TITLE
Scheduling problem with WhenAnyValue when applied to dependency props

### ISSUE THREAD

**Issue by bradphelan** [reactiveui/ReactiveUI#1510]
**Do you want to request a *feature* or report a *bug*?**

bug (maybe)

**What is the current behavior?**

FilterTextBox is a WPF textbox. I am not binding it to a viewmodel property like I really should but just using WhenAnyValue on the text property to drive a filter.

            this.FilterTextBox.WhenAnyValue(c => c.Text)
                .Select(txt => !String.IsNullOrWhiteSpace(txt))
                .ObserveOn(RxApp.MainThreadScheduler)
                .Subscribe(filtering =>
                {
                    if ( filtering )
                    {
                        VisualStateManager.GoToElementState(this.Grid, "Yes", true);
                    }
                    else
                    {
                        VisualStateManager.GoToElementState(this.Grid, "No", true);
                    }
                });

In RXUI7.4 this was working. I've upgraded to RXUI8.0-alpha-94 and it fails with 

![image](https://user-images.githubusercontent.com/17650/31380185-e149f056-adb0-11e7-95e2-dda0f2290202.png)

It is failing somewhere within WhenAnyValue 

  	System.Windows.Threading.Dispatcher.VerifyAccess	Unknown	No symbols loaded.
  	System.Windows.DependencyObject.GetValue	Unknown	No symbols loaded.
  	System.Windows.Controls.TextBox.Text.get	Unknown	No symbols loaded.
  	[Native to Managed Transition]		Annotated Frame
  	[Managed to Native Transition]		Annotated Frame
  	ReactiveUI.Reflection.TryGetValueForPropertyChain<object>	Unknown	No symbols loaded.
  	ReactiveUI.ObservedChangedMixin.TryGetValue<object, object>	Unknown	No symbols loaded.
  	ReactiveUI.ObservedChangedMixin.GetValue<object, object>	Unknown	No symbols loaded.
 	**ReactiveUI.ReactiveNotifyPropertyChangedMixin.nestedObservedChanges.AnonymousMethod__0	Unknown	No symbols loaded.**
  	System.Reactive.Linq.ObservableImpl.Select<ReactiveUI.IObservedChange<object, object>, ReactiveUI.ObservedChange<object, object>>._.OnNext	Unknown	No symbols loaded.
  	System.Reactive.Linq.ObservableImpl.Concat<ReactiveUI.IObservedChange<object, object>>._.OnNext	Unknown	No symbols loaded.
  	System.Reactive.Linq.ObservableImpl.Return<ReactiveUI.ObservedChange<object, object>>._.Invoke	Unknown	No symbols loaded.
  	System.Reactive.Concurrency.Scheduler.Invoke	Unknown	No symbols loaded.
  	System.Reactive.Concurrency.DefaultScheduler.Schedule.AnonymousMethod__0	Unknown	No symbols loaded.
  	System.Reactive.Concurrency.ConcurrencyAbstractionLayerImpl.QueueUserWorkItem.AnonymousMethod__0	Unknown	No symbols loaded.
  	System.Threading.ExecutionContext.RunInternal	Unknown	No symbols loaded.
  	System.Threading.ExecutionContext.Run	Unknown	No symbols loaded.
  	System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem	Unknown	No symbols loaded.
  	System.Threading.ThreadPoolWorkQueue.Dispatch	Unknown	No symbols loaded.

at the highlighted stack position

> 	**ReactiveUI.ReactiveNotifyPropertyChangedMixin.nestedObservedChanges.AnonymousMethod__0	Unknown	No symbols loaded.**

I see in the local variables windows

> expression	{c.Text}	System.Linq.Expressions.Expression {System.Linq.Expressions.PropertyExpression}

which matches the expression in the WhenAnyValue. Nowhere else in my code does ``c.Text`` exist.

My only guess is that some magic inside WhenAnyValue is scheduling some activity onto another thread and then trying to read the source property which, for WPF components is illegal.

**What should the behaviour be**
No activities on the source property should be scheduled on threads other than the thread on which WhenAnyValue was called.

**Comment by kentcb** [comment]
Do you have `reactiveui-wpf` installed?

**Comment by bradphelan** [comment]
Ummmm no!! I forget that it all got split up.  I'll try that. Will probably work.

However it still seems wrong in the general case that the source property is accessed on another thread than the thread that created the WhenAnyValue call.

**Comment by kentcb** [comment]
I don't think it is because you have the `.ObserveOn(RxApp.MainThreadScheduler)` in there. As per #1499, the behavior is far from ideal when the `reactiveui-wpf` package is not installed in a WPF app.

**Comment by bradphelan** [comment]
Yes the error has to be occurring directly within WhenAnyValue or some spawned task of it somewhere. The text  **c.Text** was found in the call stack of the error.

Anyway with the wpf lib installed it all works fine.

**Comment by ghuntley** [comment]
Damnit. Going to have to find a solution to this :/ sorry brad.
