### ISSUE TITLE
Hard to run unit tests from Visual Studio

### ISSUE THREAD

**Issue by glennawatson** [reactiveui/ReactiveUI#1513]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
At the moment to run unit tests from within Visual Studio is extremely difficult. I have AnyCpu with Release selected, but tried other combinations from the configuration manager.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Load the sln in Visual Studio 2017.3. Have the project in Debug/Any Cpu (or X64/Mixed CPU) and attempt to run Unit Tests. Even after running build.cmd it's extremely hard to run unit tests. 

I keep getting this output 
NU1202: Package System.IO.FileSystem.Primitives 4.0.1 is not compatible with net45 (.NETFramework,Version=v4.5). Package System.IO.FileSystem.Primitives 4.0.1 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - monotouch10 (MonoTouch,Version=v1.0)
  - net46 (.NETFramework,Version=v4.6)
  - netstandard1.3 (.NETStandard,Version=v1.3)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
  - xamarinmac20 (Xamarin.Mac,Version=v2.0)
  - xamarintvos10 (Xamarin.TVOS,Version=v1.0)
  - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0)

**What is the expected behavior?**
A much easier unit tests experience.

**What is the motivation / use case for changing the behavior?**

Make it faster to develop features/bug fixes for reactiveui library.

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**

ReactiveUI 8 from github. 

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by ghuntley** [comment]
Thanks for raising this @glennawatson. We care _alot_ about developer experience. For anything like this, if you ever feel like it's too hard or you are jumping through hoops then raise a issue just like this one!

**Comment by Asesjix** [comment]
@kentcb does the issue still exist for you, or can it be closed?
Because in Visual Studio I can run the tests without error.

![test](https://user-images.githubusercontent.com/7798041/40023468-7f3ffd9a-57cb-11e8-9169-a77126de64e6.PNG)

**Comment by Asesjix** [comment]
@glennawatson does the issue still exist for you, or can it be closed?
Because in Visual Studio I can run the tests without error.

![test](https://user-images.githubusercontent.com/7798041/40023468-7f3ffd9a-57cb-11e8-9169-a77126de64e6.PNG)

**Comment by glennawatson** [comment]
Can you right click, debug and set break points. That was the issue rather than running.

**Comment by Asesjix** [comment]
Yes without problems :)
![test2](https://user-images.githubusercontent.com/7798041/40024777-b006defe-57cf-11e8-9ab3-4d1f4d54dad9.PNG)
