### ISSUE TITLE
Add git hash to nuget package / assembly info

### ISSUE THREAD

**Issue by bradphelan** [reactiveui/ReactiveUI#1515]
**Do you want to request a *feature* or report a *bug*?**

FEATURE

**What is the current behavior?**

Not easy to cross reference the CI build number ie ``alpha-102`` to the specific git hash

**What is the expected behavior?**

The assembly informational version should have the git hash embedded as described here

https://stackoverflow.com/questions/15141338/embed-git-commit-hash-in-a-net-dll

**What is the motivation / use case for changing the behavior?**

easy to check if upgrading is a good idea by reviewing the git log

**Comment by ghuntley** [comment]
I agree. Let's do this.

**Comment by RLittlesII** [comment]
@ghuntley Looked at this last night, `AssemblyInformationalVersionAttribute` is now part of the csproj format.  [Cake.Incubator](https://github.com/cake-contrib/Cake.Incubator) has the new csproj parser, and [GitVersion](https://cakebuild.net/api/Cake.Common.Tools.GitVersion/GitVersion/) will return the sha of the latest commit.  Going to attempt to get this working this week.  I'd assume that the same git hash should be used for each package?

**Comment by ghuntley** [comment]
I agree - every ReactiveUI assembly should be stamped with the sha from gitversion.  You'll need two approaches though as ReactiveUI uses the .NET CPS SDK project system AND the legacy project system (for WPF projects - reactiveui-wpf and reactiveui-events-wpf)

# CPS

Check out the SDK over at

https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.GenerateAssemblyInfo.targets#L69-L70

In theory you should be able to do this:


```
            .WithProperty("InformationalVersion", $theShaFromGitVersion)
```

At https://github.com/reactiveui/ReactiveUI/blob/develop/build.cake#L203 


# Legacy (WPF)

Use https://www.cakebuild.net/api/Cake.Common.Solution.Project.Properties/AssemblyInfoAliases/A528A2DA with the $theShaFromGitVersion
