### ISSUE TITLE
Add ReactiveUI to Microsoft > WindowsTemplateStudio

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/ReactiveUI#1516]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the motivation / use case for changing the behavior?**

introduce new demographic to the wonders of reactive programming.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

See https://github.com/Microsoft/WindowsTemplateStudio/issues/586

/cc @crutkas

**Comment by crutkas** [comment]
@ghuntley can you guys reach out to me so we can discuss integration and expectations?  I referenced this in the Microsoft/WindowsTemplateStudio#586 issue.  my email is crutkas@microsoft.com  We can follow up in the issue after.

**Comment by ghuntley** [comment]
[![](http://img.youtube.com/vi/AoDs16tYInY/0.jpg)](http://www.youtube.com/watch?v=AoDs16tYInY

**Comment by tomverhoeff** [comment]
@ghuntley Happy to take the lead on this one. Just got an update from the WTS team that they're still deciding on some changes to the templating system, so will probably be a few weeks until we can really get this going. https://github.com/Microsoft/WindowsTemplateStudio/issues/586#issuecomment-385945557

Anyone else interested in helping out?

**Comment by touseefbsb** [comment]
WTS currently uses basic mvvm and some other popular mvvm frameworks like prism, mvvmlight etc, I am just curious what problems **reactive ui** tends to solve over these frameworks? I am a uwp developer and would love to learn more of the possible advantages it can bring to our development cycle. Thanks :) @tomverhoeff

**Comment by ghuntley** [comment]
@touseefbsb https://channel9.msdn.com/Shows/XamarinShow/Lifting-App-State-with-Geoffrey-Huntley/player

**Comment by touseefbsb** [comment]
would it also be benficial if it gets added to blazor ? what do you guyx think, should blazor team also be involved in this? I am sure you all know about blazor already?

**Comment by touseefbsb** [comment]
I didnt understand it completely because I am new to reactive stuff, but from what I understand, it can remove a lot of possible exceptions, caused by unexpected behaviour from the user and also prevent a lot of memory leaks because of the event handlers? correct me if I got it wrong.

**Comment by touseefbsb** [comment]
@ghuntley  any progress on this?

**Comment by gpriaulx** [comment]
I'm curious what the status of this is. 
Should this issue absorb #1881 ?

**Comment by glennawatson** [comment]
Probably. Safe to close the other one in favour of this.

**Comment by dpvreony** [comment]
https://github.com/dotnet/wpf/issues/1378
