### ISSUE TITLE
VS2017 15.4 issues

### ISSUE THREAD

**Issue by olevett** [reactiveui/ReactiveUI#1517]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
VS2017 update 4 with latest Xamarin for VS update stops events building correctly
- EventBuilder builds against reference assemblies installed by Xamarin (e.g. C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\ReferenceAssemblies\Microsoft\Framework\MonoAndroid) which is now 8
- ReactiveUI.Events builds against MonoAndroid70, which doesn't have the DrmInfoEventArgs types

Particular events are around DRM
```
public IObservable<Android.Media.MediaPlayer.DrmInfoEventArgs> DrmInfoEvent {
	get { return Observable.FromEventPattern<System.EventHandler<Android.Media.MediaPlayer.DrmInfoEventArgs>, Android.Media.MediaPlayer.DrmInfoEventArgs>(x => This.DrmInfoEvent += x, x => This.DrmInfoEvent -= x).Select(x => x.EventArgs); }
}

public IObservable<Android.Media.MediaPlayer.DrmPreparedEventArgs> DrmPrepared {
	get { return Observable.FromEventPattern<System.EventHandler<Android.Media.MediaPlayer.DrmPreparedEventArgs>, Android.Media.MediaPlayer.DrmPreparedEventArgs>(x => This.DrmPrepared += x, x => This.DrmPrepared -= x).Select(x => x.EventArgs); }
}
```

![image](https://user-images.githubusercontent.com/8627917/31493040-59ee9af8-af45-11e7-98f7-9f95f7d1fdb7.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Upgrade VS2017 and Xamarin to latest.

**What is the expected behavior?**
Can build RxUI, events etc.

**What is the motivation / use case for changing the behavior?**
Being able to build

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**

Latest master, Android platform and VS2017.4+Xamarin ~4.7

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by ghuntley** [comment]
Confirmed reproducible on my local machine

![image](https://user-images.githubusercontent.com/127353/31494920-1639b804-afa1-11e7-8c3e-757b9db8428f.png)
