### ISSUE TITLE
ReactiveUI doesn't exist on wikipedia? Time to create the page!

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/ReactiveUI#1521]
**Do you want to request a *feature* or report a *bug*?**

Create https://en.wikipedia.org/wiki/ReactiveUI

**What is the motivation / use case for changing the behavior?**

ReactiveUI inside of products made by Amazon (Cloud Drive), Atlassian (Sourcetree), Slack (Mobile), GitHub (Visual Studio), Elastic (Search) and 343 Industries (Halo 5). It's time to stop hiding and create a Wikipedia page!

**Comment by gpriaulx** [comment]
@giusepe is this something you are currently working on?

**Comment by gpriaulx** [comment]
Already on it. Just squeezing a snack in then I shall make a start.

**Comment by gpriaulx** [comment]
I would love to share - I think I need it to pass moderation first. I'm honestly surprised at how clunky Wikipedia editing and authoring is. I'm still a bit stuck finding a solid reference about the history of Reactive UI. 

I think for the bare minimum, I need something simple with references that states:

* What ReactiveUI is
* Who created ReactiveUI, when and why <- are there any none broken links that cover this?

I just going to make a start here:
https://www.writeurl.com/text/wwf8oh2czog0v6rwdfj6/kx1d2uf51x8ma9m9m6i9/fu45se6qgmtv9c1h9qhy

**Comment by gpriaulx** [comment]
Draft created at Wikipedia https://en.wikipedia.org/wiki/Draft:ReactiveUI

**Comment by gpriaulx** [comment]
Thank you everyone for your help in seeing this through; I really appreciate your help. I have submitted the Wikipedia entry for review. 
https://en.wikipedia.org/wiki/Draft:ReactiveUI

**Comment by RLittlesII** [comment]
Submitted again and got rejected again.  Going to follow up with the Wikipedia folks.

**Comment by glennawatson** [comment]
Seems to be references that are killing us with internal references only

https://visualstudiomagazine.com/articles/2017/10/01/create-responsive.aspx
https://blogs.msdn.microsoft.com/dotnet/2016/01/05/the-week-in-net-152016/
https://dotnetfoundation.org/projects?type=project&ps=10&pn=6
https://channel9.msdn.com/Shows/XamarinShow/The-Xamarin-Show-17-ReactiveUI-with-Michael-Stonis

**Comment by glennawatson** [comment]
https://www.planetxamarin.com/

**Comment by glennawatson** [comment]
https://forums.xamarin.com/discussion/128829/xamarin-university-monthly-update-july-2018

**Comment by glennawatson** [comment]
https://www.hanselman.com/blog/ReactiveExtensionsRxIsNowOpenSource.aspx

**Comment by gpriaulx** [comment]
Thanks @glennawatson , those are really useful finds! I have added a few lines here and there so that I could include all of them. @RLittlesII would you be able to look over the changes and make sure they are sensible (it's probably quicker to just read the whole page, it is pretty short) and resubmit if/when you are happy. If I haven't heard back from anyone I will resubmit in the current state tomorrow morning  (AEST).

**Comment by gpriaulx** [comment]
https://www.pattern.co.nz/our-blog/posts/2017/july/setting-up-a-reactiveui-viewmodel/
https://ericsink.com/entries/dont_use_rxui.html
https://discoverdot.net/projects/reactiveui

**Comment by glennawatson** [comment]
Talk to Mr wiki help desk rather than guessing what they want
