### ISSUE TITLE
Override UITableViewRowAnimation

### ISSUE THREAD

**Issue by Dimentar** [reactiveui/ReactiveUI#1523]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

Using `ReactiveTableViewSource<TSource>`, there is no possibility to change `UITableViewRowAnimation.Automatic` animation.
At first launch then the data is Binded from VM to DataSourse, all the cells appearing one by one from the top with animation delay.

**What is the expected behavior?**

Possibility to override https://github.com/reactiveui/ReactiveUI/blob/develop/src/ReactiveUI/Platforms/ios/ReactiveTableViewSource.cs#L114

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**

ReactiveUI 7.4.0

**Comment by ghuntley** [comment]
Nice catch. Looks like a PR will be needed. Specifically provide a way to allow pass in a configurable  https://developer.xamarin.com/api/type/MonoTouch.UIKit.UITableViewRowAnimation/ instead of forcing the default of Auto.

**Comment by glennawatson** [comment]
Resolved by #1712
