### ISSUE TITLE
Errors building ReactiveUI solution

### ISSUE THREAD

**Issue by RLittlesII** [reactiveui/ReactiveUI#1528]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When I pull down the latest on ReactiveUI open the solution in Visual Studio 2017 15.4, I get build errors.  I am unable to build the source code on my local machine.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Below is a gist containing the list of build errors I am seeing.

I am running Visual Studio 2017 15.4

`dotnet --version` returns 1.1 but I am sure I have other versions installed.

**What is the expected behavior?**
The expected behavior is that I am able to build the source code on my local machine.

**What is the motivation / use case for changing the behavior?**
I wanted to work on issues blocking the 8.0 release.

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**
This is not an issue with consumption of ReactiveUI, more an issue that I can't work on the source code.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

https://gist.github.com/RLittlesII/cf1672088522ab9d3b18135e0df899d3

Some of the errors are valid which I see in the project they are set "Warnings as Errors" which are the `NU1202` errors, although I am still not sure how to solve those.

**Comment by olevett** [comment]
Thanks for reporting this.

Can I check a couple of things
- do you know which workloads you have installed
- would you be able to do `git reset HEAD --hard` and `git clean -fdx`
- is this from within VS, or is this the output of running `build.cmd`?

**Comment by RLittlesII** [comment]
I updated my fork and don't see this issue anymore.  I was getting this from the command line running `.\build.cmd` in Power Shell.

**Comment by olevett** [comment]
Thanks for confirming, shout if you hit similar problems again!
