### ISSUE TITLE
build.cake fails if the pwd contains spaces

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/ReactiveUI#1535]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

![image](https://user-images.githubusercontent.com/127353/32655831-6f337e80-c663-11e7-9c5b-5fa56269e080.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

```shell
mkdir "c:\this folder has spaces"
cd "C:\this folder has spaces"
git clone [....]
cd reactiveui
.\build.cmd
```

**What is the expected behavior?**

No errors, clean green build.

**What is the motivation / use case for changing the behavior?**

Improve developer experience. Ensure that developers have smooth experience when compiling reactiveui from command line.

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**

`develop`

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by olevett** [comment]
Fixed by #1539
