### ISSUE TITLE
ReactiveUI.WPF nuget package has no .XML file included with .DLL

### ISSUE THREAD

**Issue by glennawatson** [reactiveui/ReactiveUI#1538]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
That the XML file with the comments isn't included. It's included in most other nuget package types.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
1. Get the nuget package, notice the missing xml file.

**What is the expected behavior?**
The generated XML file to be included as per the other nuget packages. 

**What is the motivation / use case for changing the behavior?**
To get extra information in intellisense etc when coding.

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**
reactiveui 8 alpha

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by ghuntley** [comment]
Thanks for taking the time to report this. It definitely needs to be resolved. Up for grabs for anyone who wants to help out, easy fix. Send in the PR!
