### ISSUE TITLE
The tag 'RoutedViewHost' does not exist in XML namespace in ReactiveUI 8.0.0 alpha0113

### ISSUE THREAD

**Issue by gtaspider** [reactiveui/ReactiveUI#1541]
It seems that RoutedViewHost doesn't work on ReactiveUI 8.0.0 alpha0113.
Any suggestions?

> The name "RoutedViewHost" does not exist in the namespace "clr-namespace:ReactiveUI;assembly=ReactiveUI"

![](https://image.ibb.co/bNKNhm/Unbenannt.png)
![](https://preview.ibb.co/kPTb8R/Unbenannt.png)

thanks in advance,
Spider

**Comment by kentcb** [comment]
Hi @gtaspider 

There is a separate package now for platform stuff. In this case, `ReactiveUI.XamForms`. Install that and let us know how you go.

**Comment by gtaspider** [comment]
Hi @kentcb 

After installing ReactiveUI.WPF alpha 0113 it works - Thanks!
