### ISSUE TITLE
Detected package version outside of dependency constraint: reactiveui-wpf 8.0.0-alpha0109 requires reactiveui (= 8.0.0-alpha0109) but version ReactiveUI 8.0.0-alpha0117 was resolved

### ISSUE THREAD

**Issue by pellea** [reactiveui/ReactiveUI#1545]
**Do you want to request a *feature* or report a *bug*?**
Bug-ish

**What is the current behavior?**
Detected package version outside of dependency constraint: reactiveui-wpf 8.0.0-alpha0109 requires reactiveui (= 8.0.0-alpha0109) but version ReactiveUI 8.0.0-alpha0117 was resolved.

**What is the expected behavior?**
The reactiveui-wpf should match/follow the version of the reactiveui package.

**What is the motivation / use case for changing the behavior?**
Get rid of a lot of warnings. 

Is there any reason why the WPF package doesn't follow the main package?

**Comment by ghuntley** [comment]
Please use `reactiveui.wpf` (not `reactiveui-wpf`)

**Comment by pellea** [comment]
I didn't see these packages ... my bad.
