### ISSUE TITLE
Rx-* NuGet packages are deprecated

### ISSUE THREAD

**Issue by Janek91** [reactiveui/ReactiveUI#1549]
According to [Rx.NET](https://github.com/Reactive-Extensions/Rx.NET) Rx-* packages are deprecated, and were unlisted from nuget.org. New versions are renamed to System.Reactive.*
I want only ask if and when will you move to new versions of those libraries?

**Comment by Qonstrukt** [comment]
Hey @Janek91, great that you're using RxUI! 😄 
You can install the pre-release versions of ReactiveUI 8.0 which are available from nuget.org. These are labeled as alpha, but you should preferably use those for new projects, or when you're ready to upgrade as they should be quite stable already.
These new packages are linked to the System.Reactive packages and compatible with .NET Standard.
