### ISSUE TITLE
OAPH does not trigger new value when command is fired

### ISSUE THREAD

**Issue by MJLHThomassen-Eurocom** [reactiveui/ReactiveUI#1550]
**Do you want to request a *feature* or report a *bug*?**
Bug (i think)

**What is the current behavior?**
Currently, I have a list of objects (POCO) which all contain a ReactiveCommand<Unit, Unit> named SendCommand.

The list of POCO objects can change depending on user input. I want to bind a result text to an OAPH based on if any of the commands, when run, throw an error or not.

Currently I have this:

```
this.WhenAnyValue(x => x.ListOfPocoObjectsWithCommandInside)
                .Subscribe(pocoObjects =>
                {
                    if (pocoObject != null && pocoObjects .Count() > 0)
                    {
                        var command = pocoObjects.ElementAt(0).SendCommand;

                        oaphField = command
                            .Select(_ => "Static string for testing")
                            .ToProperty(this, x => x.OaphProperty, "Initial string for testing");
                    }
                });
``` 
This currently does not do everything I want yet, but this is a minimal example that already fails me.
What i would expect is that every time i grab a new list, the oaphField gets re-assigned with the new property. Then, when i fire the command inside the pocoObject (which is a button in my ui), i expect the OaphProperty string text to change from "Initial string for testing" to "Static string for testing". This does not happen

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

See the code above.

**What is the expected behavior?**

I expect the OaphProperty to contain the string "Static string for testing" after i fire the command inside the 1st poco object of the new list of objects (which is done, i can verify that the command actually executes because i can break inside the command execution code).

**What is the motivation / use case for changing the behavior?**

I just want it to work

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**

I'm using 7.4.0 on Windows 10 Visual Studio 2017 inside a WPF application.

**Comment by Qonstrukt** [comment]
Is the delegate in your subscription hitting, can you step through it and see if the property is actually assigned? And how are you validating your property changes it's value?

**Comment by kentcb** [comment]
Hi @MJLHThomassen-Eurocom - thanks for the report. A standalone repro would be great, but I suspect it's because you're assigning an OAPH directly to a field. This won't notify observers of the associated property that the value has changed.

**Comment by MJLHThomassen-Eurocom** [comment]
@Qonstrukt Yes, i stepped trough and saw that the property is actually assigned. I have bound the OaphProperty string property to a textblock in my view. When I replace  "Initial string for testing" for somethign along the lines of (++i).ToString(), then every time i grab a new list, i see i increasing (1, 2, 3 etc). So the property is getting assigned which means the deletate is getting hit.

@kentcb I could have a look at producing a standalone repro, ill get back to you on that. As far as the OAPH goes, im doing it exactly like in the example on https://reactiveui.net/docs/getting-started/, they also assgin to a field: `_SearchResults = ExecuteSearch.ToProperty(this, x => x.SearchResults, new List<FlickrPhoto>());`  My `oaphField` field is of type `ObservableAsPropertyHelper<string>`. Any suggestion as to what you think is the way to do it?

**Comment by MJLHThomassen-Eurocom** [comment]
Ok, after a few hours of trying (i was working on this whole friday afternoon) i finally got it working:

```
this.WhenAnyValue(x => x.ListOfPocoObjectsWithCommandInside)
                .Subscribe(pocoObjects =>
                {
                    oaphField = pocoObjects
                        .Select(pocoObj => Observable.Merge(
                            pocoObj.SendCommand.Select(_ => "Success"),
                            pocoObj.SendCommand.ThrownExceptions.Select(ex => ex.Message)))
                        .Merge()
                        .ToProperty(this, x => x.OaphProperty);
                });
```

I really have no idea how this is different form what i did before, but its working now.
