### ISSUE TITLE
Can not install via Nuget. Splat is incompatible.

### ISSUE THREAD

**Issue by mark4asp** [reactiveui/ReactiveUI#1551]
I tried installing 3 different version of ReactiveUI.WinForms

Version 8.0.0-alpha0117
Version 7.2.0
Version 8.0.0-alpha0110

In that order. All failed to install.

(1) The two alphas will not install because :

Unable to find a version of 'Splat' that is compatible with 'reactiveui-core 7.5.0-alpha0001 constraint: Splat (>= 1.4.0 && < 2.0.0)'.
At line:1 char:1
+ Install-Package ReactiveUI.WinForms -Version 8.0.0-alpha0110 -Project ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

(2) Version 7.2.0 will not install because it is not on Nuget.

Solutions Please?

PS: Splat 1.4.0 was installed when I installed ReactiveUI.

**Comment by mark4asp** [comment]
To get it to work: (a) I changed the version of Splat to 1.6.2, and (b) I installed ReactiveUI-Winforms version 7.4.0 via Nuget. I don't know whether step (a) was essential; I doubt it.

**Comment by javiercampos** [comment]
This happened to me on the `nuget.org` repository. Installing from the `MyGet` repository ( add https://www.myget.org/F/reactiveui/api/v3/index.json to your nuget package sources ) fixed it for me.

**Comment by ghuntley** [comment]
Closing this out due to age. Please open another issue if you experience problems with v8.0.0
