### ISSUE TITLE
Reactive.Events Cause Xamarin.iOS Linker to Skip All Framework

### ISSUE THREAD

**Issue by ooikengsiang** [reactiveui/ReactiveUI#1558]
**Do you want to request a *feature* or report a *bug*?**
Bug / Problem

**What is the current behavior?**
Using any Reactive.Events extension API will cause the Xamarin.iOS Linker to skip all iOS framework. This cause iTune submission failed due to Apple will question on all API used on the app such as Call Kit API even though many of them aren't due to the bug.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
1. Start a new Xamarin.iOS project.
2. Include ReactiveUI and ReactiveUI.Events nuget package.
3. Create a UIButton and use Event extension API such as NewButton.Events().Clicked.Subscribe(_ => DoSomething());
4. Compile the project with Linker Behavior set to "Link Framework SDKs Only".
5. Use otool on the app package created for example "otool -L {your_project_path}/bin/iPhone/Release/{app_name).app/{app_name)
6. You will see a long list of framework included with the package even the app doesn't call most of them.

**What is the expected behavior?**
It shouldn't cause the linker to include all framework when only UIKit framework is used.

**What is the motivation / use case for changing the behavior?**
Prevent dev caught in surprise when submitting their app and try to figure out what happen. I need to create a new project, divide the project part by part to figure out which library caused the problem.

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**
reactiveui-events 7.4.0, project targeting iOS (I tested on Xamarin.iOS not Xamarin.Form). Not sure if the previous version have the same problem.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
I first posted the problem on Stackover flow which more information about what framework the Linker skipped. [https://stackoverflow.com/questions/47897990/xamarin-ios-submission-rejected-call-kit-features-api/47900470#47900470](https://stackoverflow.com/questions/47897990/xamarin-ios-submission-rejected-call-kit-features-api/47900470#47900470)

**Comment by Qonstrukt** [comment]
This makes sense as all Events are added to a single assembly. This would need to be split up into several different assemblies so the ones not actually being used would be linked out.

**Comment by glennawatson** [comment]
might have to change eventbuilder in that case, to dynamically generate “csproj” and then include them from the master csproj
that way we have different assemblies per event
or something like that
I suspect hopefully the lazy loading will take place then and won’t be linked in

**Comment by ajpinedam** [comment]
Tested and indeed I am having the same issue

This shows the list of libraries before using the ReactiveUI events: 

![reactiveuievents nousingevents](https://user-images.githubusercontent.com/1900897/50792819-41359080-1294-11e9-88f9-1983e4daae05.png)

Here's the list of libraries in the final app just by using the ReactiveUI events in a UIButton:

![reactiveuievents usingevents](https://user-images.githubusercontent.com/1900897/50792829-4abef880-1294-11e9-914a-5da16e068bea.png)

**Comment by 1Cor125** [comment]
Is there any update on this issue? This one has jumped up to bite us as we are just about to ship. We don't use Bluetooth API's but since they are not being linked away, AppStore is rejecting the app until we declare why we need access to Bluetooth. 
As an aside, perhaps the docs should warn devs about this before recommending use of the ReactiveUI.Events package?

**Comment by velocitysystems** [comment]
This is really a critical issue which needs to be addressed as soon as possible, especially given the App Store implications.

**Comment by glennawatson** [comment]
Realistically there isn't a timeline to fixing this in the short term. I got a couple crash bugs to fix and then will swing back around to this one. The reality of volunteer run open source software. 

Happy to take a PR about the warning about the iOS package though in the mean time.

**Comment by 1Cor125** [comment]
Thanks @glennawatson. I will look into a PR for the docs next week. In the meantime, for my information, I am wondering how much value we get from the Events package. I am comfortable using Observable.FromEventPattern even though the syntax is not as sugary as this.Events(). Are there other benefits to using ReactiveUI.Events?

**Comment by glennawatson** [comment]
The events packages are just auto generated `FromEvent` wrappers to avoid the reflection cost of `FromEventPattern` but otherwise just a convenience package.

**Comment by glennawatson** [comment]
We produce the .cs files as part of our build server. So you could even grab the latest and just copy paste the ones you need.

**Comment by glennawatson** [comment]
https://dev.azure.com/dotnet/ReactiveUI/_build/results?buildId=23081&view=artifacts

**Comment by glennawatson** [comment]
Consider using https://github.com/reactivemarbles/observableevents
