### ISSUE TITLE
ReactiveUI.Events.WinForms missing

### ISSUE THREAD

**Issue by kentcb** [reactiveui/ReactiveUI#1565]
**Do you want to request a *feature* or report a *bug*?**

Packaging bug.

**What is the current behavior?**

The `ReactiveUI.Events.WinForms` package is not present.

**What is the expected behavior?**

The package should be present (renamed from `reactiveui-events-winforms`.

**What is the motivation / use case for changing the behavior?**

Consistency/availability.

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**

v8

**Comment by rtigithub** [comment]
In the Winforms-Events branch the file Events_WinForms.cs is missing.

**Comment by kentcb** [comment]
So it seems like `reactiveui-events-winforms` was published at some point, perhaps completely independently of the main project (not sure). But because #1352 is not yet merged, there is no `ReactiveUI.Events.WinForms` package, which reflects the new package naming convention.

**Comment by ghuntley** [comment]
This needs to be fixed. Looking for a community member to finish up my work. #1352 is quite old and you may need to start again from `develop` and harvest the nuggets from that PR.
