### ISSUE TITLE
Validate this report and resolve pinning if something is wrong.

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/ReactiveUI#1566]
Validate this report and resolve pinning if something is wrong.

https://twitter.com/Cheesebaron/status/960601930807611392

> @ghuntley when looking at the nupkg artifacts produced for ReativeUI, i.e. latest build. Dependencies don't seem pinned. Could seem that the Pinning task looks for lowercase "reactiveui" while package name is actually "ReactiveUI" in the dependencies.

**Comment by cabauman** [comment]
Looks like this was resolved by #1568 a while back but forgot to close.
