### ISSUE TITLE
Try to make the build friendly for contributers without the mobile frameworks installed.

### ISSUE THREAD

**Issue by bradphelan** [reactiveui/ReactiveUI#1567]
**Do you want to request a *feature* or report a *bug*?**

Neither

**What is the current behavior?**

The build currently requires the mobile frameworks to be installed to allow it to run. This discourages potential committers who only are targeting a single platform. For example I target WPF. I may find a bug or feature in ReactiveUI core and wish to make a contribution. I then check out reactiveui, run build.cmd and find I am missing all the android and ios targetting packs and the build crashes. 

![image](https://user-images.githubusercontent.com/17650/36301085-f0dcc846-1303-11e8-9ae7-23a09f727c16.png)

At a minimum a friendly message explaining to the user that extra framework packs are required. Better still is that the missing packs are just ignored and the user is able to work with the parts they are able to work with.

**Comment by Asesjix** [comment]
@ghuntley Shall we make individual solution for each platform and / or customize the build process?

**Comment by glennawatson** [comment]
The individual solution might make the Mac build work again. Just a pain to maintain so maybe something like cmake but one that doesn't suck?

**Comment by glennawatson** [comment]
I am going to add a VS2019 configuration file to the main repo. This feature introduced in 2019 is detected by VS2019 and will auto prompt the user  to install missing functionality. This should solve this problem.
