### ISSUE TITLE
ReactiveCommand doesn't implement IHandleObservableErrors anymore

### ISSUE THREAD

**Issue by gtbuchanan** [reactiveui/ReactiveUI#1572]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
[ReactiveCommand](https://github.com/reactiveui/ReactiveUI/blob/master/src/ReactiveUI/ReactiveCommand.cs#L551) doesn't implement IHandleObservableErrors anymore

**What is the motivation/use case for changing the behavior?**
The previous version (ReactiveUI.Legacy.ReactiveCommand{T}) implemented this interface. It would be useful if the new version would implement it again. I'm assuming this was just an oversight, otherwise, [this](https://github.com/reactiveui/ReactiveUI/blob/master/src/ReactiveUI/RxApp.cs#L61) error wouldn't make much sense anymore.

Given the following extension method:

```
public static class CollectionExtensions
{
    public static T1 AddTo<T1, T2>(this T1 @this, ICollection<T2> collection)
        where T1 : T2
    {
        if (@this == null)
            throw new ArgumentNullException(nameof(@this));
        collection.Add(@this);
        return @this;
    }
}
```

Exceptions could be tracked in a generic way more easily:

```
var exceptions = new List<IHandleObservableErrors>();

SomeCommand = ReactiveCommand
    .CreateFromTask(...)
    .AddTo(exceptions)
    .DisposeWith(disposables));

SomeCommand
    .ToPropertyEx(this, @this => @this.Result) // ReactiveUI.Fody
    .AddTo(exceptions)
    .DisposeWith(disposables);

exceptions
    .Select(cmd => cmd.ThrownExceptions)
    .Merge()
    .Subscribe(...)
    .DisposeWith(disposables);
```

**Comment by Asesjix** [comment]
I think because the PR is merged, the issue can be closed.
