### ISSUE TITLE
Change to GPL compatible license?

### ISSUE THREAD

**Issue by RandomEngy** [reactiveui/ReactiveUI#1580]
I was wondering if there is any particular reason the Ms-PL was picked as the license. Would it be possible to change to a GPL-compatible permissive license like MIT, so unfortunate people who have been forced into the GPL license can use this awesome library?

**Comment by paulcbetts** [comment]
Sadly there isn't - we would have to get permission from all 105 contributors, which is overly difficult

**Comment by paulcbetts** [comment]
Wait, this is owned by the .NET Foundation now, 🤔

**Comment by ghuntley** [comment]
I wouldn't be against changing to the MOST license. Will need to speak with .NET foundation and involve legal thou for guidance.

**Comment by ghuntley** [comment]
Yo. @reactiveui/dotnet-foundation can we please start motions to change ReactiveUi's license to MIT? What's involved and what do you need from us.

.cc @reactiveui/owners

**Comment by glennawatson** [comment]
This would be handy for those of us who work at large corporates. At my company MIT/Apache 2 is on our automatic pre-approved distribution license list so would make the library much easier to work with.

**Comment by jongalloway** [comment]
Good suggestion, I'll review and update the issue on Monday (I'm traveling and speaking over the weekend). High level sounds do-able, I'll need to check no the process to change the license.

**Comment by ghuntley** [comment]
Should have answer in the next 24-48hours.

**Comment by jongalloway** [comment]
Considering there has been no community objection, we're okay from .NET Foundation side. Ready when you are.

**Comment by RandomEngy** [comment]
Fantastic! Thanks a bunch.
