### ISSUE TITLE
IsExecuting doesn't change when command execution is canceled

### ISSUE THREAD

**Issue by gtbuchanan** [reactiveui/ReactiveUI#1583]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`IsExecuting` stays `true` after command execution is canceled for a command created with `ReactiveCommand.CreateFromTask`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
NUnit Test
```
[Test]
public async Task ReactiveCommand_CancelExecution_IsExecuting()
{
    Task task = null;
    var command = ReactiveCommand.CreateFromTask(ct => task = Task.Delay(-1, ct));
    command.IsExecuting.Subscribe(isExecuting =>
        Console.WriteLine(@"IsExecuting: {0}", isExecuting));
    var execution = command.Execute().Subscribe();
    execution.Dispose();
    Console.WriteLine(@"Task: {0}", task?.Status);
    Assert.That(await command.IsExecuting.FirstAsync(), Is.False,
        "Execution cancelled, but IsExecuting is true");
}
```
**Outputs:**

> Execution cancelled, but IsExecuting is true
>   Expected: False
>   But was:  True
> 
> IsExecuting: False
> IsExecuting: True
> Task: Canceled

**What is the expected behavior?**
`IsExecuting` should be `false` when the command execution is canceled as described in the [documentation](https://reactiveui.net/docs/handbook/commands/canceling#basic-cancelation).

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReactiveUI?**
Latest stable ReactiveUI 7.4. Haven't tested version 8 yet.

**Comment by quinmars** [comment]
I think this could have been fixed in the develop branch. Related: #1525

**Comment by gtbuchanan** [comment]
@quinmars I was able to try it in the develop branch and you're right. Thanks for the reference. I'll try to merge those fixes into my fork.

@kentcb Are there any plans for a new service release of v7.4 or will we need to wait for stable v8? I'd love to see #1534 and #1573 before v8 is complete, unless that's relatively soon.

**Comment by kentcb** [comment]
@gtbuchanan definitely no plans for another v7 release. The v8 release is coming "real soon now". In the meantime, you can always consume the pre-release packages. There will be basically zero difference between them and the v8 release bits.
