### ISSUE TITLE
TEA 

### ISSUE THREAD

**Issue by ShalokShalom** [reactiveui/ReactiveUI#1585]
**Do you want to request a *feature* or report a *bug*?**

Feature 

**What is the current behavior?**

FRP

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

http://elm-lang.org/blog/farewell-to-frp

**What is the expected behavior?**

I have no expectations :slightly_smiling_face:

**What is the motivation / use case for changing the behavior?**

Simplicity 

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**

All until

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by ghuntley** [comment]
?

**Comment by ShalokShalom** [comment]
Why is functional reactive programming used, instead of the TEA concept?

Is there any difference in this project, which counters the benefits? 

How is the Elm architecture eventually implementable into ReactiveUI?

**Comment by quinmars** [comment]
The word/abbreviation isn't used at all in the linked article.

@ShalokShalom may you explain what it is and how ReactiveUI can profit from it?

**Comment by ShalokShalom** [comment]
The Elm Architecture

**Comment by ShalokShalom** [comment]
Elm basically invited FRP and it turns out, that they found another, similar concept, which works out more elegant.

**Comment by marcpiechura** [comment]
If you want to use TEA with WPF you can use https://github.com/Prolucid/Elmish.WPF 

> Elm basically invited FRP 
Not really, ReactiveUi has implemented FRP before Elm exist and the concept is probably even older. 
Also I don’t think WPF and TEA doesn’t fit well together once you need to handle big lists or grids since with elm you would produce a new list on every update which is very inperformant in WPF.

**Comment by ShalokShalom** [comment]
.Net is for more as Windows.

**Comment by marcpiechura** [comment]
Haven’t said otherwise just gave you some options for WPF and afaik Don Symen is working on Elmish for Xamarin Forms.

**Comment by ShalokShalom** [comment]
Thanks :)
