### ISSUE TITLE
Winforms ViewModelControlHost Bug

### ISSUE THREAD

**Issue by ThrasherGX** [reactiveui/ReactiveUI#1590]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
When a viewmodel is hosted in the ViewModelControlHost , the ViewModelControlHost sets the Content property before it sets the ViewModel property, which results in the ViewModel property on the View being null during the WhenActivated block, as well as during the view's Load event.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Host any viewmodel within the ViewModelControlHost control, then attempt to directly access the ViewModel property during the View's WhenActivated block.  A null reference exception should result.

**What is the expected behavior?**
Based on the behavior of the WPF ViewModelViewHost, the ViewModel should be set before the view is added to the visual tree, which means that the ViewModel would be non null during the WhenActivated block.

**What is the motivation / use case for changing the behavior?**
Currently, any use of the ViewModel during the WhenActivated block requires usage of WhenAnyValue then using Subscribe to ensure that the code will not be called until the ViewModel has been set.  This is not consistent with the WPF ViewModelViewHost, and may cause code that works in WPF to fail in Winforms due to this difference.

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**
I encountered this issue using ReactiveUI-Winforms version 7.4.1.  Based on examination of the source code for the [develop] branch, the Content property of the ViewModelControlHost is still set before the ViewModel property is, even in .

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
This issue should be very simple to fix, simply move line 98 (this.Content = view;) of https://github.com/reactiveui/ReactiveUI/blob/develop/src/ReactiveUI.Winforms/ViewModelViewHost.cs
after line 99 (view.ViewModel = x.ViewModel;).  This would ensure that the ViewModel would be non null during the WhenActivated block.

**Comment by Asesjix** [comment]
I also think it makes more sense to set the viewmodel before adding the control, but I can not understand the described problem.
You are welcome to view my examples at [Asesjix/ReactiveUI.Winforms.Samples](https://github.com/Asesjix/ReactiveUI.Winforms.Samples).
If the examples do not help please give me an code snipped.

**Comment by Wouterdek** [comment]
> Based on the behavior of the WPF ViewModelViewHost, the ViewModel should be set before the view is added to the visual tree, which means that the ViewModel would be non null during the WhenActivated block.

Actually, in my experience, this is not true. In WPF, WhenActivated is triggered when the view enters the visual tree and is disposed when it leaves the visual tree. The value or changes in the ViewModel do not seem to affect it at all. So, this behaviour is actually consistent with WPF, but poorly documented. In my WPF view code, I use WhenAnyValue. See also #839

**Comment by glennawatson** [comment]
Fixed by #1650
