### ISSUE TITLE
"Become a backer" link does not always work.

### ISSUE THREAD

**Issue by glennawatson** [reactiveui/ReactiveUI#1595]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
In the readme.md file, the "become a sponsor" section works if you click the link above the images of backers. If you click on "Become a backer" after the set of images, it'll take you to some random sponsors page and not the backer page.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Using Google Chrome, Version 65.0.3325.181 (Official Build) (64-bit) (macos)

**What is the expected behavior?**
That the link take you to the backers page. 

**What is the motivation / use case for changing the behavior?**
Get the monies for the pplz.

**Comment by glennawatson** [comment]
Just checked this one also affects the reactiveui.net webpage. 

Wasn't sure if I should put the issue on the website repo or the reactiveui one, my rationale before it was to do with the readme.md in the main repo but given it's happening in both places happy to move this (somehow)

**Comment by ghuntley** [comment]
Have escalated this into the open-collect support channel. Thank-you Glen - this is the right repo.

**Comment by vatsalyagoel** [comment]
Seems to have been fixed now

**Comment by glennawatson** [comment]
Closing due to being fixed.
