### ISSUE TITLE
Stamp <Product>$(AssemblyName) ($(TargetFramework))</Product> into builds

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/ReactiveUI#1596]
That way folks can right click on the assembly and know if they are looking at the bait or the switch. 

See https://github.com/xamarin/Essentials/blob/b85fdb2b1623e458037146e1ab4a4f33ed2a8978/Xamarin.Essentials/Xamarin.Essentials.csproj#L15 for instructions how to do it.

I recommend adding it to our `Directory.props` instead of to each csproj that way it's done once and automatically implemented for current and future csprojs.

**Comment by glennawatson** [comment]
This was fixed by #1604
