### ISSUE TITLE
Bind is currently not working two-way on NSTextFields. 

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/ReactiveUI#1603]
We are looking for someone to research what would be involved to improve this situation.

Deliverables:

* Research and come up with recommendations
* PR the main project
* Update the website documentation.
* Update our integration tests.

See https://github.com/reactiveui/ReactiveUI/pull/1601 and https://github.com/reactiveui/ReactiveUI/pull/1598#issuecomment-385487486

**Comment by Qonstrukt** [comment]
I want to check if we can fix this the way iOS works, I'll take this on tonight.
