### ISSUE TITLE
Let's have an in-person hackathon for @ReactiveX / @ReactiveXUI sometime soon?

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/ReactiveUI#1611]
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">That would be awesome! I&#39;ve just cleared the team swimming lane and replaced it with a single Todo. So I&#39;m gonna work out how we can arrange this the best, pick possible dates. It&#39;ll take me a couple of weeks to complete due to holidays, but it&#39;s top of my list now. <a href="https://t.co/tmU6DsusQk">pic.twitter.com/tmU6DsusQk</a></p>&mdash; Stefan Moonen (@Qonstrukt) <a href="https://twitter.com/Qonstrukt/status/992369077376208896?ref_src=twsrc%5Etfw">May 4, 2018</a></blockquote>

![dcwz6dmw4aerhil](https://user-images.githubusercontent.com/127353/39627111-fbf1ccf6-4fe7-11e8-8274-7bb5582883f5.jpg)

**Comment by giusepe** [comment]
<img width="684" alt="screen shot 2018-05-04 at 14 15 39" src="https://user-images.githubusercontent.com/37078773/39627311-c4b67364-4fa5-11e8-843a-2bc41ac0c3cb.png">
Can I call dibs?! :P

Seriously, that would be AMAZING!

**Comment by giusepe** [comment]
Let me know if and how I can help.

**Comment by Qonstrukt** [comment]
I'll contact you in the near future, I'll check what I can arrange combined with some other nearby events maybe, to make it worthwhile for @ghuntley to visit the country not for this alone.

**Comment by Depechie** [comment]
Belgium is just around the corner ;)

**Comment by jfversluis** [comment]
So is The Netherlands/Holland/Amsterdam/Tulips you know.. #justsayin

**Comment by ghuntley** [comment]
Current status:

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">also I would love to come back to the NL. Especially for a hackathon on ReactiveUI. Maybe we could secure a tiny amount of funding from the <a href="https://twitter.com/dotnetfdn?ref_src=twsrc%5Etfw">@dotnetfdn</a> to make this a reality <a href="https://twitter.com/jongalloway?ref_src=twsrc%5Etfw">@jongalloway</a>?</p>&mdash; 𝓖𝓮𝓸𝓯𝓯𝓻𝓮𝔂 𝓗𝓾𝓷𝓽𝓵𝓮𝔂 (@GeoffreyHuntley) <a href="https://twitter.com/GeoffreyHuntley/status/992365728798883841?ref_src=twsrc%5Etfw">May 4, 2018</a></blockquote>

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Let&#39;s discuss - e-mail or DM.</p>&mdash; Jon Galloway (@jongalloway) <a href="https://twitter.com/jongalloway/status/992433817192288260?ref_src=twsrc%5Etfw">May 4, 2018</a></blockquote>

**Comment by tomverhoeff** [comment]
There's a bunch of heavy users down here in the Netherlands. Keep me posted on the plans, happy to support organizing

**Comment by Qonstrukt** [comment]
Finally I've sent out emails asking for feedback. I had to hunt for some mail addresses, so let me know if you haven't received anything.

**Comment by glennawatson** [comment]
Only invite if the weather is good.

**Comment by Qonstrukt** [comment]
Nah, let him know what our weather is like normally 😂

**Comment by glennawatson** [comment]
Closing this one out for the moment. Organise on the twits if you want to take it further.
