### ISSUE TITLE
"We should get your projects into the Xamarin QA harness to catch regressions"

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/ReactiveUI#1615]
# Background

The community feels (rightly or wrongly) that they aren't getting enough support from the product teams and that they are are using data to solve the most common use case. If true, the problem with that is we the maintainers ("the power users") are the least common use case but your most common use case depends upon us. When you break us, you break the ecosystem.

ReactiveUI v8 could have been released on the 24th of May 2017 but was [only released a couple of days ago](https://reactiveui.net/blog/2018/05/reactiveui-v8.0.0-released) as I was waiting for the toolchain to settle on down. The historical specifics can be discussed in private - that's not the purpose of this thread. 

Let's focus on the future - this future

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">We should get your projects into@our QA harness to catch these.</p>&mdash; Miguel de Icaza (@migueldeicaza) <a href="https://twitter.com/migueldeicaza/status/992563477398081536?ref_src=twsrc%5Etfw">May 5, 2018</a></blockquote>

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">It&#39;s been offered before <a href="https://twitter.com/migueldeicaza?ref_src=twsrc%5Etfw">@migueldeicaza</a> but the project was in a deep branch due to netstandard20.<br><br>We are green and on VSTS.<br><br>I want to take you up on this offer.<br><br>How can we?</p>&mdash; 𝓖eoffrey 𝓗untley (@GeoffreyHuntley) <a href="https://twitter.com/GeoffreyHuntley/status/992567117554761729?ref_src=twsrc%5Etfw">May 5, 2018</a></blockquote>

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Email me</p>&mdash; Miguel de Icaza (@migueldeicaza) <a href="https://twitter.com/migueldeicaza/status/992567267903852545?ref_src=twsrc%5Etfw">May 5, 2018</a></blockquote>

# Scope
- Xamarin Forms
- Xamarin Android
- Xamarin iOS
- Xamarin Mac
- Visual Studio for Windows
- NuGet 

Visual Studio for Mac is out of scope because it does not have the necessary features implemented to build ReactiveUI. When it becomes possible to compile ReactiveUI using this product I'd like to see it integrated as well.

# Measurement of success
- The product teams responsible for Xamarin Forms, Xamarin Android, Xamarin iOS, Xamarin Mac, NuGet, Visual Studio for Mac and Visual Studio for Windows have an early feedback loop if their increment has broken ReactiveUI. 
- Fewer rage moments on Twitter from members of the open-source community at the product teams.
- Improved relationships with product teams with them supporting open-source maintainers.

# People

Geoffrey Huntley has the most knowledge as to how the product is built and where the skeletons are.  Oren Novotny is looking after the move to the .NET foundation VSTS instance, package signing and release management pipeline.

# ReactiveUI's build pipeline

ReactiveUI currently can only be built on windows or via xproj on the command line after removing a bunch of project references. (i.e. UWP).

We are moving to a continuous deployment model where we no-longer cut releases.  See https://reactiveui.net/blog/2018/05/moving-towards-vsts-and-continuous-deployment for specifics.

Don't look at our build.cake in master until this pull-request - https://github.com/reactiveui/ReactiveUI/pull/1613 - ships.

We are comfortable with changing implementations or configuration of VSTS and build scripts to meet Microsoft more than half-way.

We are comfortable with providing Microsoft employees with commit access to GitHub and administrative access on the .NET Foundation VSTS instance for ReactiveUI.

We are comfortable with working weird and odd hours to be able to pair with Microsoft engineering in whatever timezone that's most compatible.

# Next steps
- Determine what MSFT needs to know.
- 🚢

**Comment by kdubau** [comment]
Hello @ghuntley, I've opened a PR (https://github.com/reactiveui/ReactiveUI/pull/1717) to allow your build.cake to target prerelease instances of VS. This will allow us to test our increments of Xamarin.Android, Xamarin.iOS and Xamarin.Mac against your build process.

Xamarin.Forms is a slightly different beast as it ships on NuGet and I need a bit of help. I did some digging and presumably we'll need a way to point https://github.com/reactiveui/ReactiveUI/blob/master/src/EventBuilder/Platforms/XamForms.cs at a local NuGet package (out test definition would already have it downloaded and available on disk locally). Is that right?

**Comment by kdubau** [comment]
We could also run your unit tests quite easily I believe, would just need to parameterize this: https://github.com/reactiveui/ReactiveUI/blob/master/build.cake#L19 so I can use your cake script for debug builds.

**Comment by glennawatson** [comment]
@kdubau Worth noting that @ghuntley has stepped back from full time management of the project. He still is around but there is a bit of a delay with replies.

**Comment by kdubau** [comment]
Only pinged him because he originally opened the issue. Happy to work with whomever on this

**Comment by kdubau** [comment]
@glennawatson I've opened https://github.com/reactiveui/ReactiveUI/pull/1821 to help facilitate some more testing on our side.

**Comment by glennawatson** [comment]
@kdubau that's merged in.

**Comment by glennawatson** [comment]
@kdubau We just fixed our Mac side so it compiles.
