### ISSUE TITLE
Resolve opencollective search tags

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/ReactiveUI#1618]
> I’ll look into that sort of mapping. @ghuntley tags are indexed and used for relevancy. So reactiveUI should be able to add those tags to improve their relevancy for those search terms.

- by HipsterBrown

https://opencollective.slack.com/archives/C6JTTA4SK/p1525298321000390

**Comment by cabauman** [comment]
@glennawatson is this referring to the “Backer Requested” tags? If so, I’m guessing this issue is now resolved.
