### ISSUE TITLE
Pin Xamarin.Forms version used by EventBuilder to be same version as ReactiveUI.XamForms

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/ReactiveUI#1624]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

EventBuilder is currently unpinned and always downloads the latest

This has resulted in a broken build

![image](https://user-images.githubusercontent.com/127353/39814862-5e971d58-53d9-11e8-818e-29cee547853f.png)

**What is the expected behavior?**

This needs to be pinned.

**What is the motivation / use case for changing the behavior?**

💚 builds

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**

it's all on 🔥  - dev and master

**Comment by ghuntley** [comment]
Fixed by #1625

**Comment by ElijahReva** [comment]
Could it be the result of MSBuild update or something changed in CI environment? I also wasn't able to build locally even after pulling #1625.
