### ISSUE TITLE
Add support for Eto?

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/ReactiveUI#1629]
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">&quot;Boo hoo, no cross-platform UI framework in .NET Core&quot;<br><br>Um... Folks... Y&#39;all need to pay more attention to the ecosystem. <a href="https://t.co/fp01OoqkhZ">pic.twitter.com/fp01OoqkhZ</a></p>&mdash; Jo Shields (@directhex) <a href="https://twitter.com/directhex/status/993626943064068096?ref_src=twsrc%5Etfw">May 7, 2018</a></blockquote>

We need someone to research if / when we should support https://github.com/picoe/Eto and what's involved.

**Comment by Kavignon** [comment]
If thinking of cross-platform support, there’s also Avalonia that looks super great! Other than that, WPF is coming to .NET Core although !

**Comment by glennawatson** [comment]
We won't be supporting Eto in the short term.
