### ISSUE TITLE
[urgent] Xamarin.Forms v3.0.0 not compatible with EventGenerator

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/ReactiveUI#1630]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

💥 during compilation

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Remove #1624 and watch 💥 

**What is the expected behavior?**
 
🎉 

**What is the motivation / use case for changing the behavior?**

Fixing this allows us to bump to v3 of xamarin forms in the near future and unblocks #1577 

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**

v8.0.0

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by cabauman** [comment]
Looks like this was resolved in #1631.
