### ISSUE TITLE
netstandard20 not compatible with Microsoft Surface Hubs

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/ReactiveUI#1641]
**Do you want to request a *feature* or report a *bug*?**

It's not a bug.

It's an observation that Microsoft Surface Hub hardware isn't `netstandard20` compatible.

The device I'm testing with is running the latest Fast Ring Insider build.

**What is the current behavior?**

![img_20180514_093224_1024](https://user-images.githubusercontent.com/127353/39975347-51c5bbe8-5771-11e8-9827-208c79abd8a1.jpg)

![image](https://user-images.githubusercontent.com/127353/39975350-56441a66-5771-11e8-9358-6a9a0b3e406b.png)

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
https://github.com/ghuntley/Netstandard20Hub

**Comment by ghuntley** [comment]
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">yo <a href="https://twitter.com/terrajobst?ref_src=twsrc%5Etfw">@terrajobst</a> I&#39;ve found some issues with `netstandard20` and these devices over at <a href="https://t.co/hj5mZgQUl8">https://t.co/hj5mZgQUl8</a>. Can you route me (and this issue) to their product managers?</p>&mdash; 𝓖eoffrey 𝓗untley (@GeoffreyHuntley) <a href="https://twitter.com/GeoffreyHuntley/status/995853776073322496?ref_src=twsrc%5Etfw">May 14, 2018</a></blockquote>

**Comment by tomverhoeff** [comment]
The Surface Hub has traditionally been behind on Win10 OS updates as is the case here as well. Even if the Surface Hub us running the very latest Windows 10 build available it's still way behind what's required for netstandard20 support. 

From your screenshot above the Hub is running a 15063 build. netstandard20 support only comes with 16299. Guess it's a matter of waiting for the FCU on Surface Hub and things should start working.

**Comment by ghuntley** [comment]
Yup

**Comment by touseefbsb** [comment]
any update on this? @ghuntley
