### ISSUE TITLE
Winforms Designer generates automatically a ViewModel = null

### ISSUE THREAD

**Issue by Asesjix** [reactiveui/ReactiveUI#1648]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If a UserControl placed in a Form or UserControl , the Designer generates automatically a ViewModel = null in .Designer.cs
The result, is the ViewModel is null in WhenActivated.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
1. CustomUserControl
2. CustomViewModel
3. Some WhenActivated stuff
4. CustomUserControl > Form1

**What is the expected behavior?**
The Designer should not generate a ViewModel = null in .Designer.cs

**What is the motivation / use case for changing the behavior?**
User experience

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by Qonstrukt** [comment]
About which designer are we actually talking? The iOS designer? Wouldn’t that only define a property if you didn’t yourself in your main class file?

**Comment by Asesjix** [comment]
Oh sorry, yes it's the WinForms Designer.
When a custom control is placed on a form, the designer generates the code for it in a separate file, usually the developer does not intervene here because it is not the codebehind for the developer.
https://github.com/reactiveui/ReactiveUI/blob/c4c48cf1ec92935a2cb77c04bc793fef7022c600/integrationtests/IntegrationTests.WinForms/MainForm.Designer.cs#L39
After this line, the designer generates:
this.loginControl1.ViewModel = null;

**Comment by Qonstrukt** [comment]
Did you implement `IViewFor<TViewModel>` yourself on that control? Because then you could use the `DesignerSerializationVisibility` attribute on the ViewModel property perhaps to prevent it from being initialised in the designer file? I'm not familiar with WinForms, but that's what I found about the subject since it's not really RxUI specific.

**Comment by Asesjix** [comment]
I know, thanks for the tip! I will try is later 👍

**Comment by Asesjix** [comment]
That's it. Thank you! So that a user does not get the problem he must use the ReactiveUserControl or set the attribute itself.
