### ISSUE TITLE
reactive extension 4.0 upgrade?

### ISSUE THREAD

**Issue by touseefbsb** [reactiveui/ReactiveUI#1666]
**Question**

https://medium.com/@bnayae/reactive-extension-4-0-released-c6ca2e6fb869
 just saw this blog post about reactive extensions 4.0 being released and also a major upgrade coming with c# 8 in near future.  so where is reactive UI library in sync with that?

**Comment by ghuntley** [comment]
Okay so the reactiveui folks are one and the same as the maintainers of system.reactive. 4.0 is compatible with 3.11. There's no need for us to bump to 4.0 as min. I think there's currently restrictions that prevent 4.0 from being used but these can be relaxed now that we are out of rxnet alpha.

**Comment by touseefbsb** [comment]
oh alright, so to summarize if I just get the latest nuget of reactive ui, it is already using 4.0 of rx? sorry if the question doesnt make much sense I am new to this reactive and functional programming stuff.

**Comment by ghuntley** [comment]
ReactiveUI right now is using 3.11. We have pins in place to prevent usage of 4.0. These will be removed in the next release. There's mininal technical differences between 3.11 and 4.0 from a consumer point of view. After 4.0 is where you'll start to see perf improvements in rxnet and new features.

**Comment by touseefbsb** [comment]
oh ok, got it now.
