### ISSUE TITLE
windows community toolkit using reactive UI

### ISSUE THREAD

**Issue by touseefbsb** [reactiveui/ReactiveUI#1667]
this is just a suggestion as I saw reactive Ui proposal to be integrated in windows template studio I was wondering whether the controls and services within **windows community toolkit** can also be rewritten in reactive ui? this will convert whole ecosystem of uwp development to functional reactive programming, and make this new trend easier to adapt. ofcourse this is just a rough idea which I thought I should share, and I dont know whether its a good idea or not

**Comment by ghuntley** [comment]
Yes we want to do this.

**Comment by touseefbsb** [comment]
then I would suggest to start this discussion over in the **toolkit repo** ? I would love to join there as well :)

**Comment by touseefbsb** [comment]
commenting to keep the issue active :)

**Comment by RLittlesII** [comment]
Added proposal to keep the stalebot away.

**Comment by touseefbsb** [comment]
@ghuntley  Any plans on taking this to the toolkit team?

**Comment by RLittlesII** [comment]
@touseefbsb I found this on the Window Community Toolkit GH.  It seems like the aren't keen on the idea of taking our dependencies.  Seems to be better suited for Template Studio.

https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/2444

**Comment by gpriaulx** [comment]
How is this intended to look? I've never bothered using Windows Toolkit, but it looks like there is broad set of coverage. Would the focus just be on replacing controls, or would we go as far as replacing the services and stuff with Observable driven ones etc.

**Comment by touseefbsb** [comment]
coverage is pretty huge, yes, everything in the toolkit can actually be converted to using reactive UI, reactive UI can be used pretty much anywhere with c# code. if toolkit considers this we also might consider talking with "WINUI" team to adopt this as well, its all about convincing either teams about its benefits.
