### ISSUE TITLE
Update RxUI to use System.Reactive >= 4

### ISSUE THREAD

**Issue by glennawatson** [reactiveui/ReactiveUI#1672]
**Do you want to request a *feature* or report a *bug*?**
Upgrade

**What is the current behavior?**
Referencing System.Reactive 3.1.1

**What is the expected behavior?**
Update to System.Reactive >= 4.0.0

This avoids having NU1608 come up when compiling. 
warning NU1608: Detected package version outside of dependency constraint: ReactiveUI 8.2.1 requires System.Reactive (>= 3.1.1 && < 4.0.0) but version System.Reactive 4.0.0 was resolved.

**What is the motivation / use case for changing the behavior?**
RxUI is the main consumer of Rx and should maintain version parity.

**Which versions of ReactiveUI, and which platform / OS are affected by this issue?**
8.2.1, all

**Comment by ghuntley** [comment]
Fixed by #1674

**Comment by glennawatson** [comment]
Users are reporting weird issues which are solved by updating to 4.0.0
