### ISSUE TITLE
Not support .net4.5 now ?

### ISSUE THREAD

**Issue by wjkhappy14** [reactiveui/ReactiveUI#1677]
_We will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information. This repository's issues are reserved for feature requests and bug reports. For support questions, please ask on StackOverflow: https://stackoverflow.com/questions/tagged/reactiveui_

_Please delete this note before pressing the submit button_

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by glennawatson** [comment]
See the release notes at https://reactiveui.net/blog/2018/05/reactiveui-v8.0.0-released for the v8.0.0

The node in particular is:
The minimum version of .NET framework is now net461 which means you'll need to adjust your unit test projects and WinForms/WPF applications. We chose net461 as it's in alignment with Microsoft's official support policy and net461 is now the default option provided in Visual Studio 2017 when scaffolding File -> New Project.
