### ISSUE TITLE
WireUpControls for Android.Support.V4.App.Fragment is missing ResolveStrategy parameter

### ISSUE THREAD

**Issue by NZSmartie** [reactiveui/ReactiveUI#1679]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When using `[WireUpResource("some_id_ name")]` on properties inside a `Android.Support.V4.App.Fragment` fragment, then calling `this.WireUpControls();` in `OnCreateView`, an exception is thrown much like #1231

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

1. Create a new Fragment that is based on `Android.Support.V4.App.Fragment` 
1. Add a Control property to be wired up:

   ```C#
        [WireUpResource("text_some_name")]
        public TextInputEditText SomeTextInput { get; private set; }
   ``` 
1. Inflate with a layout with ids that do not match the property name in the fragmet's class but instead match with the `WireUpResource` attribute.
1. Override `OnCreateView(...)` with:

   ```C#
        public override View OnCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState)
        {
            var view = inflater.Inflate(Resource.Layout.some_fragment_dialog, container, false);

            if (view != null)
                this.WireUpControls(view);

            return view;
        }
   ```
1. Note that `this.WireUpControls(view);` does not have any overrides that accept a `ResolveStrategy ` parameter.

**What is the expected behavior?**

Supplying `ResolveStrategy.ExplicitOptIn` would allow use of properties with `WireUpResource` attributes

**What is the motivation / use case for changing the behavior?**

To be more consistent with `WireUpControls` method that is used with an `Activity` or `Fragment` class 

> Note that I'm using using the Fragment class from the Android support library instead of the default Fragment (as recommended by the Official Android Documentation)

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**

v8.3.1 (stable)

I've yet to test this against development

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

Suggest adding another `WireUpControls` extentionmethod in `ReactiveUI.AndroidSupport/ControlFetcherMixin.cs` that accepts the same (or similar) parameters much like `WireUpControls` for an `Activity` or `Fragment` (As seen in `ReactiveUI/Platforms/android/ControlFetcherMixins.cs`)

**Comment by NZSmartie** [comment]
Guess I should also mention that this applies to `Android.Support.V7.App.AppCompatActivity`

**Comment by Qonstrukt** [comment]
To be honest, I'm not sure the one in the AndroidSupport package is even needed.
If you add just `ReactiveUI` to your usings, you're able to use the correct extension method in `Android.Support.V7.App.AppCompatActivity` and `Android.Support.V4.App.Fragment`. 
At least that's how I remember using it, I'd have to doublecheck!

**Comment by eamiguinho** [comment]
Hi @glennawatson, @Qonstrukt, @NZSmartie with AndroidSupport version 9.1.4 I still can't WireUpControls on ReactiveUI.AndroidSupport.ReactiveFragment<VM>,  this.WireUpControls() isn't available? 

Thanks
