### ISSUE TITLE
The "Reactiveusercontrol" name does not exist in the  namespace "Http://reactiveui.net"

### ISSUE THREAD

**Issue by HeMinzhang** [reactiveui/ReactiveUI#1684]
_We will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information. This repository's issues are reserved for feature requests and bug reports. For support questions, please ask on StackOverflow: https://stackoverflow.com/questions/tagged/reactiveui_

_Please delete this note before pressing the submit button_

**Do you want to request a *feature* or report a *bug*?**
[ ReactiveUserControl<TViewModel>](https://reactiveui.net/api/reactiveui/reactiveusercontrol_1/)

> <rxui:ReactiveUserControl
>         x:Class="views:YourView"
>         x:TypeArguments="vms:YourViewModel"
>         xmlns:rxui="http://reactiveui.net"
>         xmlns:views="clr-namespace:Foo.Bar.Views"
>         xmlns:vms="clr-namespace:Foo.Bar.ViewModels">
>     
> </rxui:ReactiveUserControl>

**What is the current behavior?**
I can't use xaml syntax rxui:ReactiveUserControl implement my Wpf View.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

this is **AppView.xaml** code:
```
<rxui:ReactiveUserControl         
        x:Class="views:AppView"
        x:TypeArguments="vms:AppViewModel"
        xmlns:rxui="http://reactiveui.net"
        xmlns:views="clr-namespace:Love.Wpf.Views"
        xmlns:vms="clr-namespace:Love.Wpf.ViewModels"
             Height="450" Width="800">
    <!--<Grid>
            
    </Grid>-->
</rxui:ReactiveUserControl>

```
this is **AppView.xml.cs** code:
```
    public partial class AppView : ReactiveUserControl<AppViewModel>
    {
        public AppView()
        {
            InitializeComponent();
        }
    }

```
**What is the expected behavior?**
```
XDG0008 The "Reactiveusercontrol" name does not exist in the  namespace "Http://reactiveui.net". LOVE.WPF Appview.xaml

XDG0008	命名空间“http://reactiveui.net”中不存在“ReactiveUserControl”名称。	Love.Wpf	AppView.xaml
```

```
XLS0507 The type "Reactiveusercontrol" cannot be used as an object element because it is not public, or there is no public parameterless constructor or type converter defined. LOVE.WPF Appview.xaml

XLS0507	类型“ReactiveUserControl”不能用作对象元素，因为它不是公共的，或者未定义公共无参数构造函数或类型转换器。	Love.Wpf	AppView.xaml
```

**What is the motivation / use case for changing the behavior?**

I don't know..

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**

ReactiveUI.Wpf:8.3.1
VS2017:15.8.0 Preview 2.0

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

```
Error XDG0006 namespace prefix "x" has not been defined.	LOVE.WPF Appview.xaml 2

 Error XLS0413 the attribute ' Class ' was not found in type ' Reactiveusercontrol '.	
LOVE.WPF Appview.xaml 2

错误	XDG0006	命名空间前缀“x”尚未定义。	Love.Wpf	AppView.xaml	2	

错误	XLS0413	未在类型“ReactiveUserControl”中找到属性“Class”。	Love.Wpf	AppView.xaml	2
```

[Love.Wpf.zip](https://github.com/reactiveui/ReactiveUI/files/2176798/Love.Wpf.zip)

**Comment by glennawatson** [comment]
You are missing the xmlns:x in your xaml.

```
      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
```

**Comment by HeMinzhang** [comment]
@glennawatson 

**What is the expected behavior?**

> 
> X:class= "Views:appview" is invalid. ' Views:appview ' is an invalid class name. 
> 
> Error CS0103 the name "InitializeComponent" LOVE.WPF error does not exist in the current context XDG0008 namespace "clr-namespace:love.wpf.viewmodels" does not exist Appviewmodel "name.
> 
> The severity code indicates that the project file line suppresses display status	
> 
> Error XLS0301 the character sequence "views:" should not be in this position.
> 
> x:Class=“views:AppView”无效。“views:AppView”是无效的  类名称。 
> 
> 
> 错误	CS0103	当前上下文中不存在名称“InitializeComponent”	Love.Wpf	
> 
> 错误	XDG0008	命名空间“clr-namespace:Love.Wpf.ViewModels”中不存在“AppViewModel”名称。
> 
> 严重性	代码	说明	项目	文件	行	禁止显示状态
> 错误	XLS0301	在该位置不应为字符序列“views:”。

this is **AppView.xaml** code:

> <rxui:ReactiveUserControl     
>         xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
>         x:Class="views:AppView"
>         x:TypeArguments="vms:AppViewModel"
>         xmlns:rxui="http://reactiveui.net"
>         xmlns:views="clr-namespace:Love.Wpf.Views"
>         xmlns:vms="clr-namespace:Love.Wpf.ViewModels"
>         Height="450" Width="800">
>     
> </rxui:ReactiveUserControl>

**Comment by glennawatson** [comment]
Your x:Class looks wrong, should be something like 

```
x:Class="NameSpace.To.View"
```

This is unrelated to the reactive user control so closing this issue

**Comment by HeMinzhang** [comment]
@glennawatson 
so,[ ReactiveUserControl<TViewModel> api doc](https://reactiveui.net/api/reactiveui/reactiveusercontrol_1/) is error? Can I fix?

**Comment by HeMinzhang** [comment]
@glennawatson

thanks a million.
