### ISSUE TITLE
WPF XAML designer broken when using RoutedViewHost

### ISSUE THREAD

**Issue by glennawatson** [reactiveui/ReactiveUI#1696]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
RoutedViewHost when in WPF design mode will have a error complaining about the lack of IActivationForViewFetcher

This is due to ModeDetector.InUnitTestRunner() is not detecting the design mode correctly.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
1. Check out https://github.com/ApexAutomation/BaseApp
2. Load the MainWindow in either the xaml designer or the blend designer inside visual studio.

**What is the expected behavior?**
That you can design using the xaml editor.

**What is the motivation / use case for changing the behavior?**
Fix previously working experiences for users.  Fix user experience first found in https://stackoverflow.com/questions/51525704/using-reactiveui-v8-routedviewhost-in-wpf

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**
RxUI 8.3.1 WPF

**Comment by ghuntley** [comment]
👍

**Comment by Asesjix** [comment]
I do not think it's up to Mode.Detector.JUnitTestRunner().
Because the Designer works with the current ReativeUI master.
I think the cause was the same issue as Issue #1016 which I fixed with PR #1651.
@glennawatson Can you verify that?

![image](https://user-images.githubusercontent.com/7798041/43780075-11097316-9a5a-11e8-9589-7ac6d26287e4.png)

**Comment by glennawatson** [comment]
This appears to be fixed with 8.4.1. Thanks
