### ISSUE TITLE
ReactiveUI.Events + mtouch argument --registrar:static leads to failing build

### ISSUE THREAD

**Issue by TobiasBuchholz** [reactiveui/ReactiveUI#1697]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

I'm trying to add the mtouch argument `--registrar:static` to my xamarin iOS project but it results in the build errors from below. I would like to add the argument because it solves another build error after I've added the [Xamarin.Firebase.iOS.Analytics nuget package](https://github.com/xamarin/GoogleApisForiOSComponents/tree/master/Firebase.Analytics/component) to the project. The build is only failing for the simulator, builds for devices are fine.

_Build errors:_
```
/Users/tobiasbuchholz/Work/PressMatrix/xamarin/PressMatrix/PressMatrix.UI.iOS/obj/iPhoneSimulator/Debug/mtouch-cache/registrar.h(6579,53): error G9EBEE159: no type or protocol named 'MTKViewDelegate'
    @interface MetalKit_Rx_MTKViewDelegateRx : NSObject<MTKViewDelegate> {
                                                        ^ 
/Users/tobiasbuchholz/Work/PressMatrix/xamarin/PressMatrix/PressMatrix.UI.iOS/obj/iPhoneSimulator/Debug/mtouch-cache/registrar.h(6585,25): error G5EC502AB: expected a type
    -(void) drawInMTKView:(MTKView *)p0;
                                   ^ 
/Users/tobiasbuchholz/Work/PressMatrix/xamarin/PressMatrix/PressMatrix.UI.iOS/obj/iPhoneSimulator/Debug/mtouch-cache/registrar.h(6586,19): error G5EC502AB: expected a type
    -(void) mtkView:(MTKView *)p0 drawableSizeWillChange:(CGSize)p1;
                             ^ 
/Users/tobiasbuchholz/Work/PressMatrix/xamarin/PressMatrix/PressMatrix.UI.iOS/obj/iPhoneSimulator/Debug/mtouch-cache/registrar.m(27402,99): error GC871EEFB: unknown type name 'MTKView'
    static void native_to_managed_trampoline_494 (id self, SEL _cmd, MonoMethod **managed_method_ptr, MTKView * p0, uint32_t token_ref)
                                                                                                      ^ 
/Users/tobiasbuchholz/Work/PressMatrix/xamarin/PressMatrix/PressMatrix.UI.iOS/obj/iPhoneSimulator/Debug/mtouch-cache/registrar.m(27449,99): error GC871EEFB: unknown type name 'MTKView'
    static void native_to_managed_trampoline_495 (id self, SEL _cmd, MonoMethod **managed_method_ptr, MTKView * p0, CGSize p1, uint32_t token_ref)
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

1. Create a xamarin iOS project (Single View App)
2. Add ReactiveUI.Events package
3. Use it in code so it get's included
4. Add `--registrar:static` via Options -> iOS Build -> Additional mtouch arguments: 
5. Build

**What is the expected behavior? What is the motivation / use case for changing the behavior?**

The build succeeds without any errrors.

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**

Version: 8.3.1
Platform: iOS simulator only

I didn't try other versions but I assume the behavior would be the same (see below).

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

I've also created an [issue](https://github.com/xamarin/xamarin-macios/issues/4422) at the xamarin-macios repository because at first I didn't know ReactiveUI.Events is causing the problem. Turns out they don't add proper include directive in the generated registrar code for MetalKit, which might be on purpose because Apple didn't ship the MetalKit framework for the simulator (see [this comment](https://github.com/xamarin/xamarin-macios/issues/4422#issuecomment-407408830)). 
Since ReactiveUI.Events looks at **all** EventHandlers for a plattform it apparently also generates code for MetalKit (see `MTKViewDelegateRx` in the build errros) which causes the build to fail for simulator builds.

So my suggestion would be, in case that's even possible, to exclude the code generation for MetalKit for simulator builds until it's confirmed whether the whole issue is a bug of Xamarin.iOS itself or not.

**Comment by glennawatson** [comment]
@rolfbjarne in that thread indicated it's unlikely to be our side. Closing for now but feel free to reopen if he comes back indicating we should do something on our side
