### ISSUE TITLE
Fix the Visual Studio for Mac compilation

### ISSUE THREAD

**Issue by glennawatson** [reactiveui/ReactiveUI#1700]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
If you compile, the following fail to build. ReactiveUI.Wpf, ReactiveUI.Blend, ReactiveUI.Winforms, we should probably see if we can disable these during the build process.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Compile the project in Visual Studio 4 Mac.

**What is the expected behavior?**
That these non-mac allowed libraries don't compile.

**What is the motivation / use case for changing the behavior?**
Make it easier for Visual Studio 4 Mac users.

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**

Latest src.

**Comment by vatsalyagoel** [comment]
I can play around and see what we can do

**Comment by ghuntley** [comment]
I'd advise holding off. VS4Mac doesn't do multi-targeted builds properly. Until it does it's not worth supporting or investing effort into making it work because you'll hit dead ends that only Microsoft can resolve.

**Comment by ghuntley** [comment]
Keep an eye on this board https://github.com/mono/monodevelop/projects/1 when all items are DONE then proceed.

**Comment by RLittlesII** [comment]
Resolved #1932
