### ISSUE TITLE
[Help needed] Sample application for Xamarin.Forms using ReactiveMasterDetailPage

### ISSUE THREAD

**Issue by alokkms** [reactiveui/ReactiveUI#1714]
**Do you want to request a *feature* or report a *bug*?**
*feature*/*help*

**What is the current behavior?**
Could not find an example for Xamarin.Forms using the ReactiveMasterDetailPage. Especially, how to navigate to a different details page.

Here is a sample code: https://github.com/alokkms/ReactiveUISample 
but this does not work as expected.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by RLittlesII** [comment]
@alokkms Sorry it took me a few days to get something together.  The sample provided should be enough to get you started.

https://github.com/RLittlesII/ReactiveMasterDetail

**Comment by alokkms** [comment]
Thanks @RLittlesII for the sample.
There are few issues with this sample that I see:
1. Double tool bar (since you have masterdetail page inside navigation page, i see two tool bars)
2. After opening a detail page, the title does not show up in the tool bar. (This is perhaps a bug? The title shows up fine with regular MasterDetailPage)
3. When opening a detail page, it should not be put on the stack, instead it should replace the current detail page (with hamburger menu still visible, instead of back button).

Can you please take a look.

**Comment by RLittlesII** [comment]
@alokkms I am going to create an issue on the sample so we can track what your expectations are from a working sample there.
