### ISSUE TITLE
Need to write tests for ViewModel assembly in integration tests

### ISSUE THREAD

**Issue by glennawatson** [reactiveui/ReactiveUI#1716]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

No view model tests in our integration tests.

**What is the motivation / use case for changing the behavior?**
Need to finish the work that newbies need. This was meant to be part of #1598 but wanted to get the integration tests in so newbies can have a reference to work against, and build release managers could have something to test again.

We still need the unit tests to be written. 

Write tests for ViewModel assembly and ship them in IntegrationTests.Shared.Tests

**Comment by glennawatson** [comment]
@giusepe I think you expressed some interest in doing this part?

**Comment by giusepe** [comment]
That's right @glennawatson, I can do it. 
I was asking around the other day two questions:
1) View Model Unit Tests? (That's is already answered here)
2) Do we have any kind of pattern to be followed? Method names and specific techniques we want to use or can I just do what I usually do?

**Comment by glennawatson** [comment]
We use xunit 2.4.0 currently internally I imagine keeping it consistent would be good. 
I am getting the feeling from @ghuntley that he just would prefer it done and be consistent about it..

**Comment by ghuntley** [comment]
re: frameworks

Use xunit & shoudly. 

re: naming of tests

Use higher level language that matches application behaviours or features aka "What language would a product owner or business analyst use?"

Something like this but it doesn't really matter to much, it's very easy to change in the future so if you have a better idea then just do it!

```
Task TheLoginButton_IsDisabled_WhenUsernameOrPassword_IsInvalid
Task TheLoginButton_IsEnabled_WhenUsernameofPassword_IsValid
Task TheCancelButton_EnablesAutomatically_WhenUserIsLoggingIn
```

**Comment by giusepe** [comment]
Ok, 

I had some free time today, I pulled the master, found some tests that I think @ghuntley started, polished, updated and fixed most of them here: https://github.com/reactiveui/ReactiveUI/tree/IntegrationTestsViewModelUnitTests

There are still 2 broken tests: 

Registrations_Should_Resolve_Correctly => Do we really need this, I mean, if I would start it from scratch I don't think I would have created this :) 

CancelButton_IsAvailableUntil_TwoSeconds => I looked into it and it should be working, but it's not. I could use a second pair of eyes here.

**Comment by glennawatson** [comment]
I'll take a look at that second unit test tonight and see if I can diagnose it. 

In terms of first I think we'll just go for your judgement on the test and remove it. (Lets wait a day or so to see if @ghuntley replies just to be safe)

**Comment by hack2root** [comment]
@glennawatson I decide that more tests - the better (I got 100% code cov in https://build.experimentalcommunity.org). So think about not removing "broken" test (i think that any test case can be treated as positive), but changing a "sign", a "granularty",  or a "severity"

**Comment by glennawatson** [comment]
I believe @RLittlesII  is addressing this one soon based on @giusepe work

**Comment by cabauman** [comment]
Hi @RLittlesII. What’s the status on this? If needed, I can try to finish up if you let me know what’s left.
