### ISSUE TITLE
A lot of dependency from default libraryes in build folder

### ISSUE THREAD

**Issue by Guddiny** [reactiveui/ReactiveUI#1725]
A lot of dependency from default libraries in build folder (since i installed ReactiveUI) :
...
_System.AppContext.dll
System.Collections.dll
System.Collections.Concurrent.dll
System.Collections.NonGeneric.dll
System.Collections.Specialized.dll
System.ComponentModel.dll
System.ComponentModel.EventBasedAsync.dll
System.ComponentModel.Primitives.dll
System.ComponentModel.TypeConverter.dll
System.Console.dll
System.Data.Common.dll
System.Diagnostics.Contracts.dll
System.Diagnostics.Debug.dll
System.Diagnostics.FileVersionInfo.dll
System.Diagnostics.Process.dll
System.Diagnostics.StackTrace.dll
System.Diagnostics.TextWriterTraceListener.dll
System.Diagnostics.Tools.dll
System.Diagnostics.TraceSource.dll
System.Diagnostics.Tracing.dll
System.Drawing.Primitives.dll
System.Dynamic.Runtime.dll
System.Globalization.dll
System.Globalization.Calendars.dll
System.Globalization.Extensions.dll
System.IO.dll
System.IO.Compression.dll
System.IO.Compression.ZipFile.dll
System.IO.FileSystem.dll
System.IO.FileSystem.DriveInfo.dll
System.IO.FileSystem.Primitives.dll
System.IO.FileSystem.Watcher.dll
System.IO.IsolatedStorage.dll
System.IO.MemoryMappedFiles.dll
System.IO.Pipes.dll
System.IO.UnmanagedMemoryStream.dll
System.Linq.dll
System.Linq.Expressions.dll
System.Linq.Parallel.dll
System.Linq.Queryable.dll
System.Net.Http.dll
System.Net.NameResolution.dll
System.Net.NetworkInformation.dll
System.Net.Ping.dll
System.Net.Primitives.dll
System.Net.Requests.dll
System.Net.Security.dll
System.Net.Sockets.dll
System.Net.WebHeaderCollection.dll
System.Net.WebSockets.dll
System.Net.WebSockets.Client.dll
System.ObjectModel.dll
System.Reflection.dll
System.Reflection.Extensions.dll
System.Reflection.Primitives.dll
System.Resources.Reader.dll
System.Resources.ResourceManager.dll
System.Resources.Writer.dll
System.Runtime.dll
System.Runtime.CompilerServices.Unsafe.dll
System.Runtime.CompilerServices.VisualC.dll
System.Runtime.Extensions.dll
System.Runtime.Handles.dll
System.Runtime.InteropServices.dll
System.Runtime.InteropServices.RuntimeInformation.dll
System.Runtime.Numerics.dll
System.Runtime.Serialization.Formatters.dll
System.Runtime.Serialization.Json.dll
System.Runtime.Serialization.Primitives.dll
System.Runtime.Serialization.Xml.dll
System.Security.Claims.dll
System.Security.Cryptography.Algorithms.dll
System.Security.Cryptography.Csp.dll
System.Security.Cryptography.Encoding.dll
System.Security.Cryptography.Primitives.dll
System.Security.Cryptography.X509Certificates.dll
System.Security.Principal.dll
System.Security.SecureString.dll
System.Text.Encoding.dll
System.Text.Encoding.Extensions.dll
System.Text.RegularExpressions.dll
System.Threading.dll
System.Threading.Overlapped.dll
System.Threading.Tasks.dll
System.Threading.Tasks.Extensions.dll
System.Threading.Tasks.Parallel.dll
System.Threading.Thread.dll
System.Threading.ThreadPool.dll
System.Threading.Timer.dll
System.ValueTuple.dll
System.Windows.Interactivity.dll
System.Xml.ReaderWriter.dll
System.Xml.XDocument.dll
System.Xml.XmlDocument.dll
System.Xml.XmlSerializer.dll
System.Xml.XPath.dll
System.Xml.XPath.XDocument.dll
System.Runtime.CompilerServices.Unsafe.xml
System.Threading.Tasks.Extensions.xml
System.ValueTuple.xml_

Why?

**Comment by glennawatson** [comment]
Not really an issue per say. What platform are you compiling for?

**Comment by Guddiny** [comment]
Windows 7 x64

**Comment by glennawatson** [comment]
WPF? Xaml? .NET 4.6.2 or different?

**Comment by Guddiny** [comment]
Ou sorry. NET 4.6.1 WPF.

**Comment by glennawatson** [comment]
I just created a brand new application and only get the following outputting apart from the main executable.

reactiveui.dll - the main executable
splat.dll - our DI engine which is a requirement of rxui
system.drawing.primitives - required by splat
system.reactive - required by rxui 
system.valuetype - required by system.reactive and rxui, since we aren't using .net 4.7.1

Are you using the old style package.config nuget references of the newer packagereference?

Usually the newer format is better at working out dependencies better https://docs.microsoft.com/en-us/nuget/reference/migrate-packages-config-to-package-reference

**Comment by Guddiny** [comment]
It's my package.config (old style):
﻿<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Caliburn.Micro" version="3.2.0" targetFramework="net461" />
  <package id="Caliburn.Micro.Core" version="3.2.0" targetFramework="net461" />
  <package id="Fody" version="3.1.4" targetFramework="net461" developmentDependency="true" />
  <package id="PropertyChanged.Fody" version="2.5.9" targetFramework="net461" />
  <package id="ReactiveUI" version="8.5.1" targetFramework="net461" />
  <package id="ReactiveUI.Fody" version="8.5.1" targetFramework="net461" />
  <package id="ReactiveUI.WPF" version="8.5.1" targetFramework="net461" />
  <package id="SpicyTaco.AutoGrid" version="1.2.29" targetFramework="net461" />
  <package id="Splat" version="4.0.2" targetFramework="net461" />
  <package id="System.Drawing.Primitives" version="4.3.0" targetFramework="net461" />
  <package id="System.Reactive" version="4.1.0" targetFramework="net461" />
  <package id="System.Reactive.Core" version="4.1.0" targetFramework="net461" />
  <package id="System.Reactive.Experimental" version="4.1.0" targetFramework="net461" />
  <package id="System.Reactive.Interfaces" version="4.1.0" targetFramework="net461" />
  <package id="System.Reactive.Linq" version="4.1.0" targetFramework="net461" />
  <package id="System.Reactive.PlatformServices" version="4.1.0" targetFramework="net461" />
  <package id="System.Reactive.Providers" version="4.1.0" targetFramework="net461" />
  <package id="System.Reactive.Runtime.Remoting" version="4.1.0" targetFramework="net461" />
  <package id="System.Reactive.Windows.Forms" version="4.1.0" targetFramework="net461" />
  <package id="System.Reactive.Windows.Threading" version="4.1.0" targetFramework="net461" />
  <package id="System.Runtime.CompilerServices.Unsafe" version="4.5.0" targetFramework="net461" />
  <package id="System.Threading.Tasks.Extensions" version="4.5.1" targetFramework="net461" />
  <package id="System.ValueTuple" version="4.5.0" targetFramework="net461" />
</packages>

**Comment by glennawatson** [comment]
I did some testing, it's likely due to the fact you upgraded to System.Reactive 4.1.0

Basically those MS packages are updated compared to 4.6.1 version, if you updated to 4.7.1 you'll notice a dramatic number of those packages would disappear. 

The new package format is much better you should upgrade regardless.

**Comment by glennawatson** [comment]
One other thing, you only need System.Reactive now. Remove all those others.
