### ISSUE TITLE
Add Integration Tests to Build Pipeline

### ISSUE THREAD

**Issue by RLittlesII** [reactiveui/ReactiveUI#1726]
**Do you want to request a *feature* or report a *bug*?**

**feature**

Execute the Integration Test as part of the build pipeline for releases.

**What is the current behavior?**

Integration tests sit their dormant not adding value.

**What is the expected behavior?**

That the integration tests execute and make sure I didn't break stuff before the release goes out

**What is the motivation / use case for changing the behavior?**

Shipping better software

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

- [ ] Source packages for integration tests from myget

- [ ]  Affect some [NuGet Version Magic](https://docs.microsoft.com/en-us/nuget/reference/package-versioning) to allow packages to get latest source every execution

- [ ] Execute Integration Tests as part of the release process?

**Comment by glennawatson** [comment]
As part of this I want us to use the latest version of RxUI in our integration tests, and a nuget.config pointing towards a myget server.

You can find help on the versioning to get the latest here : https://docs.microsoft.com/en-us/nuget/reference/package-versioning

**Comment by ChrisPulman** [comment]
#2851 fixes this by using the current PR source code for RxUI
