### ISSUE TITLE
WhenActivated fails on WPF Window when migrating to ReactiveUI 8.7.2 from 7.4.0

### ISSUE THREAD

**Issue by rualmar** [reactiveui/ReactiveUI#1735]
**Do you want to request a *feature* or report a *bug*?**

It's an error on code working on version 7.4.0 and broken on migrating to 8.7.2. I want to know what's wrong with the code and how can I fix it.

**What is the current behavior?**

The final objective is to provide an async method to init my ViewModel parameters from DataBase once a window/control is loaded and showed on screeen, and not anymore, not even when changing to another Window while the first one is alive.

For that matter I have a Window that implements IActivatable and a ViewModel that implements ISupportsActivation. By calling WhenActivated on both I was able to invoke an InitAsync method on ViewModel once the Window was effectively shown on screen. 

After migating to v8.7.2, when I call WhenActivated on the Window, I receive the exception:

> System.ArgumentException: 'Don't know how to detect when ReactiveUIEx.Test.MainWindow is activated/deactivated, you may need to implement IActivationForViewFetcher'

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

The Window CodeBehind

```
public class MyWindow : Window, IActivatable, IViewFor<MyViewModel>
{
    MyViewModel IViewFor<MyViewModel>.ViewModel
    {
        get => DataContext as MyViewModel;
        set => DataContext = value;
    }

    object IViewFor.ViewModel
    {
        get => DataContext;
        set => DataContext = value;
    }

    public MyWindow()
    {
        this.WhenActivated(d => { }); //Necessary on 7.4.0. If I didn't do this, ViewModel's WhenActivated didn't get fired
   }
}
```

The ViewModel

```
public class MyViewModel : ReactiveObject
{
   public MyViewModel()
   {
      this.WhenActivated(d => InitAsync().ToObservable().Subscribe(
                res => { }, 
                async exc => await OnInitAsyncError(exc)
                ).DisposeWith(d));
   }

   protected Task InitAsync() 
   {
       //Do init actions asynchronously
   }

   protected Task OnInitAsyncError(Exception ex)
   {
       //Handle error (notify, log......)
   }
}
```

**What is the expected behavior?**

I expect WhenActivated on the ViewModel to be fired once the Window is effctively shown.

**What is the motivation / use case for changing the behavior?**

I had that code working on version 7.4.0 of ReactiveUI. I have no problem on refactor or reimplement it on v8.7.2 but I don't know how to achieve the same results without getting errors.

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**

The original code was working on version 7.4.0. Now it's being executed over 8.7.2

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by rualmar** [comment]
Sorry, I got it and now I feel so dumb 😝  I didn't know with v8.7.2 I had to install specific packages for each platform. Issue was solved adding reference to ReactiveUI.WPF NuGet.

**Comment by glennawatson** [comment]
Ironically I created this yesterday https://github.com/reactiveui/website/issues/167 -- one of our documentation guys is going to get it out soonish.
