### ISSUE TITLE
Add support for Avalonia properties in binding.

### ISSUE THREAD

**Issue by glennawatson** [reactiveui/ReactiveUI#1739]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
There is no support for Avalonia properties https://github.com/AvaloniaUI/Avalonia

**What is the expected behavior?**
To allow use of Avalonia's based properties.

**What is the motivation / use case for changing the behavior?**
To extend the number of users that can use RxBinding features.

**Comment by worldbeater** [comment]
Just to mention, Avalonia team has an <a href="https://github.com/AvaloniaUI/Avalonia/tree/master/src/Avalonia.ReactiveUI">Avalonia.ReactiveUI</a> package published in NuGet, it would be great if we could transfer it to ReactiveUI organization, rename to `ReactiveUI.Avalonia` and add support for type-safe bindings.

**Comment by glennawatson** [comment]
Want to open a issue on their website to see if they are willing?

**Comment by worldbeater** [comment]
Great news. AvaloniaUI now supports WhenActivated! https://github.com/AvaloniaUI/Avalonia/pull/1951

**Comment by RLittlesII** [comment]
@worldbeater Based on your assessment closing this issue.
