### ISSUE TITLE
.NET Native support

### ISSUE THREAD

**Issue by worldbeater** [reactiveui/ReactiveUI#1750]
**Do you want to request a *feature* or report a *bug*?**

I'd like to report a *bug*.

**What is the current behavior?**

Currently, ReactiveUI code-behind bindings get broken when I try to compile my <a href="https://github.com/worldbeater/MyFeed/pull/5">Universal Windows Platform</a> app using <a href="https://docs.microsoft.com/en-us/dotnet/framework/net-native/">.NET Native toolchain</a>. 

Let me illustrate the issue with code snippets. You know, ReactiveUI bindings can be created using the following extension methods: `OneWayBind`, `Bind`, `BindCommand`, `BindTo`, `InvokeCommand`. This is what happens when compiling an UWP app with .NET Native:

```csharp
// This method works fine without .NET Native. With .NET Native
// it throws a System.Reflection.TargetInvocationException. The 
// inner exception is of type System.InvalidOperationException.
// This is the message of the inner exception: "The second parameter 
// of the event delegate must be assignable to 'System.EventArgs'."
this.BindCommand(ViewModel,
  viewModel => viewModel.Load,
  view => view.RefreshCategories)
  .DisposeWith(disposables);

// This works fine both with and without .NET Native.
// '.BindTo(...)' also works great.
this.OneWayBind(ViewModel,
  viewModel => viewModel.Items,
  view => view.CategoriesPivot.ItemsSource)
  .DisposeWith(disposables);

// Doesn't throw any exceptions, but simply does nothing 
// when compiling the app with .NET Native.
this.Bind(ViewModel,
  viewModel => viewModel.Selection,
  view => view.CategoriesPivot.SelectedItem)
  .DisposeWith(disposables);
```

I'm experiencing this issue while trying to update my Universal Windows Platform sample app to satisfy ReactiveUI recommended approaches (<a href="https://reactiveui.net/docs/handbook/views/">type-safe bindings</a>, UserControls). Here it is: https://github.com/worldbeater/MyFeed/pull/5 The branch compiles and works fine without .NET Native toolchain turned on, but crashes with .NET Native toolchain turned on.

**Steps to reproduce:**
1. Create a new Universal Windows Platform application
2. Add something like this to your XAML:
```xml
<Button x:Name="ExampleButton" Content="Hello, world!"/>
```
3. Add something like this to your code-behind:
```csharp
InitializeComponent();
ViewModel = new ExampleViewModelWithCommand();
this.WhenActivated(disposables =>
{
    this.BindCommand(ViewModel, // The app will break here with .NET Native
        viewModel => viewModel.ExampleCommand,
        view => view.ExampleButton)
        .DisposeWith(disposables);
});
```
4. Compile in Release mode with .NET Native toolchain

**What is the expected behavior?**

No matter with or without .NET Native, ReactiveUI code-behind bindings should work as expected.

**What is the motivation / use case for changing the behavior?**

Universal Windows Platform developers usually prefer compiling their applications with .NET Native toolchain. Why? .NET Native increases the startup speed of an app and it's performance.

> For the vast majority of apps and scenarios, .NET Native offers significantly faster startup times and superior performance when compared to an app compiled to IL or to an NGEN image. — <a href="https://docs.microsoft.com/en-us/dotnet/framework/net-native/">Microsoft, "Compiling Apps with .NET Native"</a>   

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI?**

I was able to reproduce the issue using latest ReactiveUI 8.7.2 package and <a href="https://blogs.windows.com/windowsexperience/2017/10/17/whats-new-windows-10-fall-creators-update/">Fall Creators Update (1709)</a> as a minimum target. Also, I can confirm the issue exists since 8.0-alpha builds.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

> ...the input to .NET Native is the IL and metadata written to managed assemblies... — <a href="https://docs.microsoft.com/en-us/dotnet/framework/net-native/net-native-and-compilation#net-native-and-just-in-time-compilation">Microsoft, ".NET Native and Compilation"</a>  

.NET Native post-processes the IL code of a compiled assembly and I think some reflection-based code might not work as expected in our case.

**Comment by shiftkey** [comment]
>The branch compiles and works fine without .NET Native toolchain turned on, but crashes with .NET Native toolchain turned on.

@worldbeater can you provide more details about what this crash is? We had an earlier discussion about this in #1330 which might be related but kind of trailed off.

**Comment by worldbeater** [comment]
@shiftkey I wish I could provide more info, but there are no stack traces. If I do this:
```csharp
UnhandledException += (sender, e) =>
{
    e.Handled = true;
    System.Diagnostics.Debug.WriteLine(e.Exception);
    System.Diagnostics.Debug.WriteLine(e.Exception.InnerException);
};
```
I get such output and nothing else:
```
Exception thrown: "System.InvalidOperationException" in System.Reactive.dll
An exception of type "System.InvalidOperationException" occured in System.Reactive.dll, but was not handled in user code
The second parameter of the event delegate must be assignable to 'System.EventArgs'.

Exception thrown: "System.Reflection.TargetInvocationException" in System.Private.CoreLib.dll
Exception thrown: "System.Reflection.TargetInvocationException" in System.Reactive.dll
Exception thrown: "System.Reflection.TargetInvocationException" in System.Reactive.dll
An exception of type "System.Reflection.TargetInvocationException" occured in System.Reactive.dll, but was not handled in user code
Exception has been thrown by the target of an invocation.
```

**Comment by shiftkey** [comment]
@worldbeater it's interesting that both of those stacks involve `System.Reactive.dll` rather than ReactiveUI. @onovotny have you recently looked at Rx.NET and .NET Native playing together?

**Comment by worldbeater** [comment]
So folks, the good news is that <a href="https://github.com/reactiveui/ReactiveUI/issues/1330#issuecomment-319069826">this workaround</a> worked for me. I included all the nessesary types explicitly using the `Default.rd.xml` file and it worked. Now, `this.BindCommand` and `this.Bind` methods perform as expected:

**App\Properties\Default.rd.xml**
```xml
<Directives xmlns="http://schemas.microsoft.com/netfx/2013/01/metadata">  
   <Application>  
      <Assembly Name="*Application*" Dynamic="Required All" />

      <Type Name="Windows.UI.Xaml.Controls.Primitives.ButtonBase" Dynamic="Required All" />
      <Type Name="Windows.UI.Xaml.Controls.Primitives.ToggleButton" Dynamic="Required All" />
      <Type Name="Windows.UI.Xaml.Controls.Primitives.Selector" Dynamic="Required All" />
    
      <Type Name="Windows.UI.Xaml.Controls.TextBox" Dynamic="Required All" />
      <Type Name="Windows.UI.Xaml.Controls.Button" Dynamic="Required All" />
      <Type Name="Windows.UI.Xaml.Controls.RadioButton" Dynamic="Required All" />
      <Type Name="Windows.UI.Xaml.Controls.ToggleSwitch" Dynamic="Required All" />
      <Type Name="Windows.UI.Xaml.Controls.CheckBox" Dynamic="Required All" />
      <Type Name="Windows.UI.Xaml.Controls.ComboBox" Dynamic="Required All" />
      <Type Name="Windows.UI.Xaml.Controls.ItemsControl" Dynamic="Required All" />
   </Application>
</Directives>  
```

### But the exception isn't gone

When I create a UserControl and write such code (<a href="https://github.com/worldbeater/MyFeed/blob/rxui-bindings/MyFeed.Uwp/Views/FeedItemView.xaml.cs#L25">source</a>):
```csharp
DataContextChanged += (a, args) => ViewModel = args.NewValue as FeedViewModel;
```
I get the same exception from `System.Reactive.dll`:
```
Exception thrown: "System.InvalidOperationException" in System.Reactive.dll
An exception of type "System.InvalidOperationException" occured in System.Reactive.dll, but was not handled in user code
The second parameter of the event delegate must be assignable to 'System.EventArgs'.
```
Unable to figure out what causes it. 
Without `System.Reactive` or `ReactiveUI` packages there is no such issue.

**Comment by worldbeater** [comment]
I've accidentally found another <a href="https://github.com/moswald/RxUI-UWP-Sample/blob/master/RxUI-UWP-Sample/Properties/Default.rd.xml">Default.rd.xml file</a> that should do the trick. It includes only directives that ReactiveUI needs to support .NET Native. Here are the contents:

```xml
<Directives xmlns="http://schemas.microsoft.com/netfx/2013/01/metadata">
  <Application>
    <Assembly Name="*Application*" Dynamic="Required All" />
    
    <Type Name="ReactiveUI.BindingMixins">
      <Method Name="Bind{TViewModel, TView, TVMProp, TVProp}">
        <GenericParameter Name="TViewModel" Dynamic="Required All"/>
        <GenericParameter Name="TView" Dynamic="Required All"/>
        <GenericParameter Name="TVMProp" Dynamic="Required All"/>
        <GenericParameter Name="TVProp" Dynamic="Required All"/>
      </Method>

      <Method Name="OneWayBind{TViewModel, TView, TVMProp, TVProp}">
        <GenericParameter Name="TViewModel" Dynamic="Required All"/>
        <GenericParameter Name="TView" Dynamic="Required All"/>
        <GenericParameter Name="TVMProp" Dynamic="Required All"/>
        <GenericParameter Name="TVProp" Dynamic="Required All"/>
      </Method>

      <Method Name="OneWayBind{TViewModel, TView, TProp, TOut}">
        <GenericParameter Name="TViewModel" Dynamic="Required All"/>
        <GenericParameter Name="TView" Dynamic="Required All"/>
        <GenericParameter Name="TProp" Dynamic="Required All"/>
        <GenericParameter Name="TOut" Dynamic="Required All"/>
      </Method>

      <Method Name="BindTo{TValue, TTarget, TTValue}">
        <GenericParameter Name="TValue" Dynamic="Required All"/>
        <GenericParameter Name="TTarget" Dynamic="Required All"/>
        <GenericParameter Name="TTValue" Dynamic="Required All"/>
        <Parameter Name="target" Dynamic="Required All" />
        <Parameter Name="This" Dynamic="Required All" />
        <Parameter Name="property" Dynamic="Required All" />
      </Method>
    </Type>

    <Type Name="ReactiveUI.PropertyBinderImplementation">
      <Method Name="Bind{TViewModel, TView, TVMProp, TVProp, TDontCare}">
        <GenericParameter Name="TViewModel" Dynamic="Required All"/>
        <GenericParameter Name="TView" Dynamic="Required All"/>
        <GenericParameter Name="TVMProp" Dynamic="Required All"/>
        <GenericParameter Name="TVProp" Dynamic="Required All"/>
        <GenericParameter Name="TDontCare" Dynamic="Required All"/>
        <Parameter Name="property" Dynamic="Required All" />
      </Method>
      
      <Method Name="BindTo{TValue, TTarget, TTValue}">
        <GenericParameter Name="TTarget" Dynamic="Required All" />
        <GenericParameter Name="TValue" Dynamic="Required All" />
        <GenericParameter Name="TTValue" Dynamic="Required All" />
        <Parameter Name="target" Dynamic="Required All" />
        <Parameter Name="This" Dynamic="Required All" />
        <Parameter Name="property" Dynamic="Required All" />
      </Method>
      
      <Method Name="OneWayBind{TViewModel, TView, TVMProp, TVProp}">
        <GenericParameter Name="TViewModel" Dynamic="Required All"/>
        <GenericParameter Name="TView" Dynamic="Required All"/>
        <GenericParameter Name="TVMProp" Dynamic="Required All"/>
        <GenericParameter Name="TVProp" Dynamic="Required All"/>
      </Method>
      
      <Method Name="OneWayBind{TViewModel, TView, TProp, TOut}">
        <GenericParameter Name="TViewModel" Dynamic="Required All"/>
        <GenericParameter Name="TView" Dynamic="Required All"/>
        <GenericParameter Name="TProp" Dynamic="Required All"/>
        <GenericParameter Name="TOut" Dynamic="Required All"/>
      </Method>
    </Type>

  </Application>
</Directives>
```

**Comment by glennawatson** [comment]
So how do we go about resolving this. This just seems to be maybe a .net sample and documentation issue now.

**Comment by morganbr** [comment]
If there's an rd.xml file that generally works for ReactiveUI, it can be converted to a library rd.xml file by removing ```<Assembly Name="*Application*" Dynamic="Required All" />``` and switching the Application tags to something like ```<Library Name="ReactiveUI" />```. You can the make the rd.xml file an embedded resource of ReactiveUI and the .NET Native compiler will automatically pick it up.

**Comment by worldbeater** [comment]
@Lukespacewalker ReactiveUI uses [System.Reactive 4.0](https://github.com/reactiveui/ReactiveUI/blob/master/src/ReactiveUI/ReactiveUI.csproj#L13) internally. Personally I prefer to trust ReactiveUI instead of referencing any of the System.Reactive assemblies *directly* — by installing ReactiveUI, you also install the right version of System.Reactive packages containing all reactive extensions features.

**Comment by Lukespacewalker** [comment]
@worldbeater Thanks. So, It looks like I should wait until ReactiveUI its dependencies to System.Reactive 4.1/4.2.

**Comment by worldbeater** [comment]
@Lukespacewalker what features does `System.Reactive` 4.1 package contain that are not available in `System.Reactive` 4.0?

**Comment by Lukespacewalker** [comment]
@worldbeater [Rx.Net Release Note](https://github.com/dotnet/reactive/releases) From what I've seen in their release note. There are a lot of performance optimization and bug fix from 4.0 to 4.1.2.

**Comment by glennawatson** [comment]
We are delaying due to compile issues in rx 4.1 and above on xamarin Android.

**Comment by Lukespacewalker** [comment]
There is a workaround to make native compilation with ReactiveUI 9.3.5 + UWP 6.2.2 + System.Reactive 4.1 successful by enabling ShortcutGenericAnalysis flag in csproj
