### ISSUE TITLE
Missing System.Reactive.Linq.dll in Xamarin Forms

### ISSUE THREAD

**Issue by rubiktubik** [reactiveui/ReactiveUI#1751]
**Do you want to request a *feature* or report a *bug*?**

Probably a bug

**What is the current behavior?**

I created a new Xamarin Forms Project with Android. I installed the ReactiveUI.XamForms Nuget but when i want to compile the project i get this kind of error:

```
Xamarin.Android.Common.targets(1476,2): warning XA0106: Skipping Crowded.Droid.Resource.String.library_name. Please check that your Nuget Package versions are compatible.

error : Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'System.Reactive.Linq, Version=3.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'. Perhaps it doesn't exist in the Mono for Android profile?

...  "System.Reactive.Linq.dll"
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1590,2): error :    bei Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1590,2): error :    bei Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection 1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1590,2): error :    bei Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver)
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

Create a new Xamarin Forms App with .NET Standard and only Android as target and add `ReactiveUI.XamForms` as Nuget .

**What is the expected behavior?**

App is compiling and starting.

**What is the motivation / use case for changing the behavior?**

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**

- Visual Studio 2017
- Windows 10
- ReactiveUI: 8.7.2
- Xamarin Forms: 3.2.0.839982
- .NET Standard: 2.0.3

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by rubiktubik** [comment]
Ok, that works! 
But now i get Missing System.Threading.Tasks.Extensions.dll :-)

**Comment by rubiktubik** [comment]
I found a solution! It was my fault! 😅 
When i follow this [guide](https://reactiveui.net/docs/getting-started/installation/nuget-packages/) how to setup the nuget packages for Xamarin Forms. It works without problems.

**Comment by mdemrr** [comment]
+rubiktubik Thank you bro you save me.
