### ISSUE TITLE
When implementing IMutableDependencyResolver Splat is registering ILogManager twice

### ISSUE THREAD

**Issue by RejectKid** [reactiveui/ReactiveUI#1824]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Currently I implemented IMutableDependencyResolver utilizing ninject and when I'm registering components it's registering splat.ILogmanager twice

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
Create a plain application following the tutorial [here](https://reactiveui.net/docs/handbook/dependency-inversion/custom-dependency-inversion) but use ninject instead and it hit's resolve twice for serviceType == ILogManager

**What is the expected behavior?**
only 1 binding

**What is the motivation / use case for changing the behavior?**
upgrading project and following suggested guidelines

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**
RxUI 9.0.1, win10, have not tried on previous versions

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by RejectKid** [comment]
so i can confirm i'm not using `ILogManager`.  and in my bare bones app its registering ILogManager twice.  somehow autofac is getting around this where ninject cant.  i can do a rebind command instead of Bind to "hack" it for now it seems.  but ILogManager does get registered twice

**Comment by RejectKid** [comment]
so it appears i needed to use kernel.GetAll for my implementation of the IMutableDependecnyResolver and its good.  sorry.

tho idk if it is an issue but ILogManager does get registered twice

**Comment by glennawatson** [comment]
What windowing framework are you using. Wpf/winforms/uwp/xamarin?

**Comment by RejectKid** [comment]
WPF.

**Comment by RLittlesII** [comment]
@RejectKid Is this still an issue?  I remember we worked through some of this on slack.  If it is, please update the issue with any additional notes.  If not, feel free to close the issue.

**Comment by RejectKid** [comment]
@RLittlesII i believe its still an issue.  As there is a work around i can do, i believe the ILogManager being bound twice is probably an issue

**Comment by cabauman** [comment]
The referenced tutorial says to do

```
resolver.InitializeSplat();
resolver.InitializeReactiveUI();
Locator.Current = resolver;
```

but as discussed recently, assigning the new resolver triggers the callback to reinitialize both Splat and ReactiveUI again. So I think we should remove those two explicit initialize calls from the tutorial since they're already called by [the callback immediately](https://github.com/reactiveui/splat/blob/092aa529508fb455da0042f09dc1924cf61f65b6/src/Splat/ServiceLocation/Locator.cs#L111).

Also, we can now use the callback suppression functionality added here: reactiveui/ReactiveUI#217.

```
using (Locator.SuppressResolverCallbackChangedNotifications())
{
    Locator.Current = resolver;
}
```
