### ISSUE TITLE
The MouseEnter event does not get call.

### ISSUE THREAD

**Issue by Jerajo** [reactiveui/ReactiveUI#1831]
**Do you want to request a feature or report a bug?**

I'd like to report a bug.

**What is the current behavior?**

The `Image.Events().MouseEnter` just gets call on `MouseLeftButtonDown` event. I have not tessted others events to see it is just the 'MouseEnter' event that has this problem.

**Output**

```console
Mouse Left Button Down
Mouse Enter
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**XAML**

```XAML
<Image
	x:Name="ImageGrade1"
	Grid.Column="0"
	Margin="20"
	tz:Transitionz.Opacity="{tz:OpacityParams From=0,
		To=1,
		Duration=200,
		BeginTime=1000,
		TransitionOn=Loaded}"
	tz:Transitionz.Translate="{tz:TranslateParams From='0,20',
		To='0,0',
		Duration=100,
		BeginTime=1000,
		TransitionOn=Loaded}"
	MouseLeftButtonDown="ImageGrade1_MouseLeftButtonDown"
	OpacityMask="#A7000000"
	Source="{svgc:SvgImage /Resources/Images/Grado01.svg}" />
```

**View**

```C#
public MainSreen()
{
	InitializeComponent();
	ViewModel = new AnimationHandler();

	this.WhenActivated(disposable =>
	{
		this.BindCommand(
			this.ViewModel, 
			vm => vm.Image_MouseEnter,
			v => v.ImageGrade1, 
			ImageGrade1.Events().MouseEnter)
		.DisposeWith(disposable);
	}
}

private async void ImageGrade1_MouseLeftButtonDown(object sender, MouseButtonEventArgs e)
{
	Console.WriteLine("Mouse Left Button Down");
}
```

**ViewModel**

```C#
public class AnimationHandler : ReactiveObject
{
	public ReactiveCommand<MouseEventArgs, Unit> Image_MouseEnter { get; private set; }

	public ViewModel()
	{
		Image_MouseEnter = ReactiveCommand
		.ReactiveCommand.CreateFromObservable<MouseEventArgs, Unit>(Image_MouseEnterExecute);
	}


	private IObservable<Unit> Image_MouseEnterExecute(MouseEventArgs e)
	{
		Console.WriteLine("Mouse Enter");

		return Observable.Return(Unit.Default);
	}
}
```

**What is the expected behavior?**

The event should be call on `MouseEnter` not on the `MouseLeftButtonDown `event.

**Output**

```console
Mouse Enter
Mouse Left Button Down
```

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI?**

- **ReactiveUI v9.1.1**
- **.Net Standar**
- **WPF**
- **C#**

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

Another isue with the lambda expertion. #1829

**Comment by MarkusKgit** [comment]
Is this really a bug? In your code 
```C#
this.BindCommand(
	this.ViewModel, 
	vm => vm.Image_MouseEnter,
	v => v.ImageGrade1, 
	ImageGrade1.Events().MouseEnter)
```
the fourth parameter of the first overload of `BindCommand` is actually expected to be a string. From the docu:
```
toEvent:
        //     If specified, bind to the specific event instead of the default. NOTE: If this
        //     parameter is used inside WhenActivated, it's important to dispose the binding
        //     when the view is deactivated.
```
You just happened to hit another overload which expects `IObservable<TParam> withParameter` as fourth parameter

So if you change `ImageGrade1.Events().MouseEnter` to `nameof(Image.MouseEnter)` it should work.

Alternatively you could do it like so (with ReactiveUI.Events.Wpf):
```C#
this.Events()
	.MouseEnter
	.InvokeCommand(ViewModel, vm => vm.Image_MouseEnter)
	.DisposeWith(disposable);
```

**Comment by glennawatson** [comment]
Closing this due to solution shown.

**Comment by glennawatson** [comment]
Thanks @MarkusKgit for providing such a detailed answer
