### ISSUE TITLE
ReactiveCommand`2 and BindCommand, don't chains into subscription

### ISSUE THREAD

**Issue by WhitePhoera** [reactiveui/ReactiveUI#1857]
**Do you want to request a *feature* or report a *bug*?**

i ask explanation, but probably this is bug

**What is the current behavior?**

i can't recieve result of command.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

```cs
public class MainViewModel : ReactiveObject, IDisposable
  {
        CompositeDisposable disposable = new CompositeDisposable();
        public void Dispose()
        {
            Interlocked.Exchange(ref disposable, null)?.Dispose();
        }
        public ReactiveCommand<Unit, string> CreateProjectCommand => ReactiveCommand.CreateFromTask(async () =>
        {
            await Task.Delay(1000);
            return "SomeValue";
        });
        public MainViewModel()
        {
            CreateProjectCommand
                .Where(r => r != null)
                .Select(r =>
                {
                   //breakpoint here
                    return ("Успешно", $"Проект '{r}' успешно создан.");
                })
                .Subscribe(_onMessage)
                .DisposeWith(disposable);
        }
        private Subject<(string title, string text)> _onMessage = new Subject<(string title, string text)>(); public IObservable<(string title, string text)> OnMessage => _onMessage.AsObservable();
}    
    public partial class MainWindow : ReactiveWindow<MainViewModel>
    {
        public MainWindow()
        {
            InitializeComponent();
            ViewModel = new MainViewModel();
            this.WhenActivated(d =>
            {
                d(this.BindCommand(ViewModel, x => x.CreateProjectCommand, v => v.createProjectBTN));
            });
        }
    }
```

**What is the expected behavior?**

i expect breakpoint to hit, and _onMessage be called(it works in manual OnNext thou).
or looks like i missing something?

quote from docs

> ReactiveCommand<TInput, TOutput> is IObservable<TOutput> which can be used like any other IObservable. For example, since the ReactiveCommand is IObservable you can Subscribe() to it like any other observable, and add the output to a List on your view model. 

same thing with ThrownExceptions, it's chain not called with BindCommand.

> However, the subscription to this observable is often instigated by the binding infrastructure. As such, it's likely that you cannot even get a hold of the observable to observe any errors.
> 
> To address this dilemma, ReactiveCommand includes a ThrownExceptions observable (of type IObservable<Exception>). Any errors that occur in your execution logic will also tick through this observable. 

if i replace return with throw, my app will go down, despite of subscription.

what i do wrong?

**Comment by WhitePhoera** [comment]
fixed, ty.

**Comment by glennawatson** [comment]
You don't need to do the `Interlocked.Exchange()` in your `Dispose()` due to `CompositeDisposable` doing that already internally.

If this is a WPF application make sure you are including the NuGet package _ReactiveUI.WPF_ 

I don't see a subscription to `ThrownExceptions` there on the Command?

I can take a deeper look into your problem in my morning though if no-one else does (so about 8 hours).

**Comment by WhitePhoera** [comment]
> If this is a WPF application make sure you are including the NuGet package ReactiveUI.WPF
included, i have error with main thread without it.

> I don't see a subscription to ThrownExceptions there on the Command?
i just mentioned that, it's not here.

> I can take a deeper look into your problem in my morning though if no-one else does (so about 8 hours).
i will appreciate that, since it just forces me to make results subjects and invoke that all manually.
(i still hate thing that if awaited observable throws error not piped to task, but this is not RUI issue)

**Comment by WhitePhoera** [comment]
oh, seems my error, stupid error :(
key thing is => on property declaration.
it must be {get;}=, not =>.
every time i access property it creates new command.

was, so used to => for Subject, ObservableAsPropertyHelper, field access...that just did not saw that error.
thank you very much.

PS same reason ThrowsExceptions not worked.
