### ISSUE TITLE
Memory Leaks test do not run in the unit test harness

### ISSUE THREAD

**Issue by glennawatson** [reactiveui/ReactiveUI#1868]
The memory leak tests require the resharper unit test runner to run.

We should look into how we can get this to work without it.

Issue found as part of #1867

**Comment by glennawatson** [comment]
We need to follow potentially the instructions in here to run with Xunit 2 https://blog.jetbrains.com/dotnet/2015/09/15/memory-testing-on-a-ci-server-dotmemory-unit-standalone-launcher/

**Comment by cabauman** [comment]
@glennawatson are these the unit tests that I removed recently, or something different?

**Comment by glennawatson** [comment]
There is a jet brains project
