### ISSUE TITLE
ReactiveUserControl cannot be edited in Design view

### ISSUE THREAD

**Issue by Katsutami7moto** [reactiveui/ReactiveUI#1869]
**Do you want to request a *feature* or report a *bug*?**

To report a bug.

**What is the current behavior?**

ReactiveUserControl cannot be edited in Design view.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

I opened ReactiveDemo sample, tried to access NugetDetailsView.xaml in Design view, but it didn't appear.

**What is the expected behavior?**

ReactiveUserControl should be possible to edit in Design view.

**What is the motivation / use case for changing the behavior?**

How would I blindly create ReactiveUserControls?

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**

ReactiveUI.WPF latest stable v9.5.1
Windows 10 v1809 build 17763.195
.NET Framework v4.7.2

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

This solution: https://stackoverflow.com/questions/50219382/reactiveusercontrol-cannot-be-edited-in-design-view
doesn't work and shows this error:
"XDG0008	Name "NugetDetailsViewBase`1" doesn't exist in namespace "clr-namespace:ReactiveDemo"."

**Comment by glennawatson** [comment]
The xaml designer is broken with generic types. Now that wpf is being opened source there is hope stuff like this can be fixed. 

Recommend you open a bug in their GitHub page

**Comment by glennawatson** [comment]
Closing due to solution provided, and also issue should be opened on WPF project for XAML designer to provide generic support.
