### ISSUE TITLE
[Xamarin Forms] When using NavigateAndReset with a navigation stack containing more than one page, intermediate pages are displayed temporarily 

### ISSUE THREAD

**Issue by SpiegelSoft** [reactiveui/ReactiveUI#1873]
_We will close your issue without comment if you delete or do not fill out the issue checklist and provide ALL the requested information. This repository's issues are reserved for feature requests and bug reports. For support questions, please ask on StackOverflow: https://stackoverflow.com/questions/tagged/reactiveui_

**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
When using NavigateAndReset with a navigation stack containing more than one page, intermediate pages flash up on the screen before the new page is displayed.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**
1. Navigate to vm1 using NavigateAndReset.Execute()
2. Navigate to vm2 using Navigate.Execute()
3. Check that the NavigationStack contains vm1 and vm2
4. Navigate to vm3 using NavigateAndReset.Execute()
5. The vm2 page is displayed before the vm3 page becomes visible.

**What is the expected behavior?**
The vm3 page should display immediately.

**What is the motivation / use case for changing the behavior?**
Bug fix -- the appearance of the intermediate page means that my app is not production ready.

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**
9.5.1

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**
I have investigated, but it's not immediately clear how to fix this bug.

**Comment by SpiegelSoft** [comment]
Great fix -- thanks Rodney.

**Comment by RLittlesII** [comment]
Thanks to @cabauman for getting the fix in.
