### ISSUE TITLE
Provide Template pack for xamarin forms project in Visual studio and visual studio for mac

### ISSUE THREAD

**Issue by HobDev** [reactiveui/ReactiveUI#1881]
**Do you want to request a *feature* or report a *bug*?**

request a feature

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**What is the expected behavior?**
Template pack to make it easy to get started with Reactive UI . 

**What is the motivation / use case for changing the behavior?**
It is nearly impossible for a beginner like me to get started with Reactive UI. Lack of samples and docs. A TEMPLATE PACK can solve this at one and all. 

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**
Latest version

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by glennawatson** [comment]
Have you seen https://reactiveui.net/docs/ which may help your situation.

**Comment by HobDev** [comment]
@glennawatson Thanks for the link. But the docs are somewhat limited without appropriate samples. I am developing a xamarin forms app with tabs layout. I want to use ReactiveUI and find this [https://reactiveui.net/api/reactiveui.xamforms/reactivetabbedpage_1/](). But unable to implement the information in my app. May be its me.

**Comment by HobDev** [comment]
On the other hand getting started with prism is so easy with template pack and other resources.

**Comment by glennawatson** [comment]
Not disagreeing necessarily. Just want to get you up quickly. 

A good example is https://github.com/kentcb/WorkoutWotch

Also Kent boogart has written a book which is probably worth a read if your in a position to get it. 

https://kent-boogaart.com/you-i-and-reactiveui/

Just to warn you we aren't in a position to action this type of request immediately but will keep it in mind for future sample efforts.

**Comment by HobDev** [comment]
This is something which I feel can give me deep knowledge in  the subject. If you have read the book can you please confirm that the content of the book also cover xamarin forms

**Comment by gpriaulx** [comment]
I can't really say if the book covered Xamarin forms well or not. I read the book cover to cover, but my scope of interest was only desktop applications so I was mentally filtering that aspect out. It is pretty general and well structured, and didn't seem over fitted to any particular platform. To be honest I have looked at ReactiveUI a number of times in the past and didn't really get it. I would get started and everything would be great until I struck a problem. You, I, and ReactiveUI is what made everything make sense to me; it puts everything in perspective and Kent does a great job at explaining the 'whys'. I feel its value can't be overstated, and I would definitely recommend reading it if you would like to get into ReactiveUI.

**Comment by glennawatson** [comment]
Closed since this will be covered by #1516
