### ISSUE TITLE
Not correctly resolving the View + ViewModel in UWP (Splat 2.0)

### ISSUE THREAD

**Issue by assassin316** [reactiveui/ReactiveUI#1882]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Using the latest RxUI v8 preview and Splat 2.0, in a UWP project referencing a .Net Standard 2.0 library, I can't register my view and viewmodel unless they reside in the same assembly.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

For brevity, I'll link to my StackOverflow issue which has images to show the problem:

https://stackoverflow.com/questions/47755145/cant-register-a-view-and-viewmodel-between-2-assemblies-uwp-splat

**What is the expected behavior?**

We should be able to have the ViewModels in a seperate assemble and associate them with their Views (as it does in a Xamarin Forms project).

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI?**

This is issue is present in Splat 2.0.0.

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

I have the error messages displayed in my StackOverflow link above.

**ATTACHED PROJECT:**
[RxUI.Bootstrap.zip](https://github.com/reactiveui/splat/files/1552433/RxUI.Bootstrap.zip)

**Comment by glennawatson** [comment]
Moved this from the splat project, due to the fact this is more of a rxui issue (Splat has no knowledge of View/ViewModels etc)

**Comment by cabauman** [comment]
As an alternative to the proposed fix, what about exposing a optional property called ViewAssemblyName and replacing

```
var viewModelTypeName = viewModelType.AssemblyQualifiedName;
var proposedViewTypeName = ViewModelToViewFunc(viewModelTypeName);
var view = AttemptViewResolution(proposedViewTypeName, contract);
```

with

```
var viewModelTypeName = viewModelType.FullName;
var proposedViewTypeName = this.ViewModelToViewFunc(viewModelTypeName);
var viewAssemblyName = ViewAssemblyName ?? viewModelType.Assembly.FullName;
var proposedAssemblyQualifiedViewTypeName = $"{proposedViewTypeName}, {viewAssemblyName}";
var view = this.AttemptViewResolution(proposedAssemblyQualifiedViewTypeName, contract);
```

Works fine on my end.

**Comment by cabauman** [comment]
@assassin316 are you still using RxUI 8 preview? The current version is 9.7.2 and [this fix](https://github.com/reactiveui/ReactiveUI/commit/39abffec9927048af02bfd5c50217ae629170641) by @glennawatson last month may fix the problem you're encountering. Can you try and confirm?

**Comment by assassin316** [comment]
@cabauman  Yes, as soon asI get some time I'll update to the latest Rx and try out the fix. Thanks for the update!

**Comment by assassin316** [comment]
@cabauman Sorry for the delay, I've been having deployment issues with my app, as soon as I'm able to resolve them I'll report back on this issue.

**Comment by cabauman** [comment]
No problem @assassin316. Take your time. We finally revived this issue a year after you originally posted it, so we’re just happy you’re helping us confirm.

**Comment by assassin316** [comment]
@cabauman  Updated to the latest, removed my fix, re-compiled and ran my app, everything works perfectly!  So I can confirm I don't need my workaround anymore :)

**Comment by cabauman** [comment]
Nice! Thanks for confirming:)
