### ISSUE TITLE
ToUnit extension method for all observables

### ISSUE THREAD

**Issue by qrzychu** [reactiveui/ReactiveUI#1885]
This is very simple feature suggestion.

Whenever I want to gather notifications from multiple observables via `Merge`, I need to manually change type of observable via `Select` to Unit.

I wrote an extension method:

```
public static IObservable<Unit> ToUnit<T>(this IObservable<T> obs)
{
   return obs.Select(x => Unit.Default);
}

// also could be usefull, maybe with better name
public static IObservable<Unit> ToUnitWithBegin<T>(this IObservable<T> obs)
{
   return obs.Select(x => Unit.Default).StartWith(Unit.Default);
}
```

The problem is, I have to create it in every single project I do, sometimes have to copy it between projects within single solution (or create "Extensions" project that is shared, but there are sometimes .NET versions conflicts etc.).

It would be great to have it built-in.

Sample usage:

```
Observable.Merge(
   this.WhenAnyValue(x => x.SomeInteger).ToUnit(),
   this.SomeCommand.ToUnit(),
   this.WhenAnyValue(x => x.SomeString).Where(x => !string.IsNullOrEmpty(x)).ToUnit()
)
.Throttle(TimeSpan.FromSeconds(0.2))
.InvokeCommand(FetchSomeData);
```

**Comment by worldbeater** [comment]
AFAIK, in functional languages such functions are called "ignore" - they accept any type and return `Unit`, so refactoring this into something like this might make sence:
```cs
public static IObservable<Unit> Ignore<T>(this IObservable<T> o) => o.Select(x => Unit.Default);
```
Also worth migrating the issue to [dotnet/reactive](https://github.com/dotnet/reactive) repo which contains all LINQ over Observable operators.

**Comment by glennawatson** [comment]
Kent Boogart tends to use ToSignal()
