### ISSUE TITLE
Duplicate DependencyResolver registrations every time resolver changes

### ISSUE THREAD

**Issue by cabauman** [reactiveui/ReactiveUI#1897]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
[Locator.RegisterResolverCallbackChanged in RxApp](https://github.com/reactiveui/ReactiveUI/blob/5cab37cb8e6726a731424d2e2447b047ae209016/src/ReactiveUI/RxApp.cs#L89) causes all the default ReactiveUI  service registrations to duplicate every time the resolver is changed.

For example
ICreatesObservableForProperty
- INPCObservableForProperty
- IROObservableForProperty
- POCOObservableForProperty

becomes

ICreatesObservableForProperty
- INPCObservableForProperty
- IROObservableForProperty
- POCOObservableForProperty
- INPCObservableForProperty
- IROObservableForProperty
- POCOObservableForProperty

The following test fails:

```
[Fact]
public void RegistrationsShouldNotDuplicate()
{
    int expectedCount = _resolver.GetServices<ICreatesObservableForProperty>().Count();
    using (_resolver.WithResolver())
    {
        int count = _resolver.GetServices<ICreatesObservableForProperty>().Count();
        Assert.Equal(expectedCount, count);
    }
}
```

![dependency resolver test results](https://user-images.githubusercontent.com/6819362/50811678-d72ff080-1352-11e9-8702-69f26008e140.PNG)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem**

**What is the expected behavior?**
Default ReactiveUI registrations shouldn't duplicate.

**What is the motivation / use case for changing the behavior?**
Wastes memory and CPU

**Which versions of ReactiveUI, and which platform / OS are affected by this issue? Did this work in previous versions of ReativeUI? Please also test with the [latest stable](https://www.nuget.org/profiles/reactiveui) and [development snapshot](https://reactiveui.net/docs/getting-started/installation/nuget-packages/development-package-feed)**
9.7.2, Windows 10

**Other information (e.g. stacktraces, related issues, suggestions how to fix)**

**Comment by glennawatson** [comment]
Is this one fixed now @cabauman

**Comment by cabauman** [comment]
Yes, this is now fixed. Thanks for your help, Glenn.
