### ISSUE TITLE
Wpf in Core 3.0

### ISSUE THREAD

**Issue by osjimenez** [reactiveui/ReactiveUI#1898]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
ReactiveUI.Wpf only works for full framework

**What is the expected behavior?**
That ReactiveUI.Wpf work in new Core 3.0 too

**What is the motivation / use case for changing the behavior?**
The new Core 3.0 is the future :)

Any plan for this? How deep is this change for ReactiveUI? I'm hope we can continue enjoining with this framework in Core 3.0 ;)

**Comment by RLittlesII** [comment]
There are plans to get ReactiveUI.WPF .NET Core 3.0 compatible, I do not know what the time frame is for the support.

**Comment by glennawatson** [comment]
A couple weeks most likely. Don't hold me to that.

We will be doing a preview release first so look out for that.

**Comment by glennawatson** [comment]
https://github.com/reactiveui/ReactiveUI/releases/tag/10.0.0-preview.1

There is the preview release.

**Comment by glennawatson** [comment]
Going to close for this for the moment even though it's not in release. The functionality is there.
