### ISSUE TITLE
[BUG] ViewModelViewHost fails to find view when ComboBox.SelectedIndex is set to -1

### ISSUE THREAD

**Issue by andrejpanjan** [reactiveui/ReactiveUI#1920]
**Describe the bug**
When `ComboBox.SelectedIndex` is set to `-1`, exception "ViewModelViewHost could not find a valid view for the view model of type System.String and value ." is thrown.

**Steps To Reproduce**
1. Create a `ViewModel` class.
2. Create a `View` class that derives from `ReactiveUserControl<ViewModel>`.
3. Create a list of `ViewModel`-s (`List<ViewModel> viewModelsList`).
4. Put a `ComboBox comboBox` in a new window.
5. Set `comboBox.ItemsSource = viewModelsList`.
6. Run.
7. Select an item in ComboBox.
8. Set  `ComboBox.SelectedIndex = -1`.
9. Exception "ViewModelViewHost could not find a valid view for the view model of type System.String and value ." is thrown

**Expected behavior**
`ComboBox.SelectedItem = null` and `ComboBox.SelectionBox` is empty.

**Environment(please complete the following information):**
- OS: Windows 10
- ReactiveUI version: 9.8.9
- GUI framework: WPF

**Additional context**
It might be related to the fix of #1905.

**Comment by glennawatson** [comment]
I think it's related to #1905 just in terms of we never had the control active before in that context. 

I think the solution will be just changing that exception to information, and set the `Content = DefaultContent`

Should hopefully have a new bug release soon.

**Comment by glennawatson** [comment]
Please note, to anyone who takes on this task. Please assign yourself to the bug, then change it to "in progress" on the project here https://github.com/reactiveui/ReactiveUI/projects/4 

Also we will need unit tests around this guy if possible added.

**Comment by glennawatson** [comment]
Thanks for your patience again @andrejpanjan  -- there is a new release with a fix out today.

**Comment by andrejpanjan** [comment]
No worries. It works as expected. Thanks.
