### ISSUE TITLE
Android: add unit tests

### ISSUE THREAD

**Issue by glennawatson** [reactiveui/ReactiveUI#1939]
**Is your feature request related to a problem? Please describe.**
At the moment we don't run the unit tests in the Android platform of the unit tests. We need to run them and run a emulator to run all the tests.

**Describe the solution you'd like**
That unit tests run through the android emulator

**Describe suggestions on how to achieve the feature**
Something along the lines of https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/android?view=azure-devops#test-on-the-android-emulator

**Comment by Kavignon** [comment]
So you want to run the Android test in an emulator with the Asure DevOps pipeline to enhance the CI workflow?

**Comment by glennawatson** [comment]
I would follow what's in the https://github.com/reactiveui/splat project -- Add a android project for the tests, add a target framework to ReactiveUI.Tests as netstandard2.0, and then derive all run the tests through the android test project.

**Comment by dpvreony** [comment]
the runner in splat is https://github.com/xunit/devices.xunit automation would be tied to https://github.com/xunit/devices.xunit/issues/79

**Comment by glennawatson** [comment]
This was added as part of #2201
