### ISSUE TITLE
TaskCompletionSource from Observable<T> Stream

### ISSUE THREAD

**Issue by MongkonEiadon** [reactiveui/ReactiveUI#1950]
Hi, I have a question to ask you about this scenario;

I have one property in the ViewModel;
``` javascript

public Profile Profile {
  get => _profile;
  set => this.RaisedAndSetIfItChanged(ref _profile, value);
}

```

Then I have a another method (few seconds time execution) 
``` javascript
public Task SendingMessageAsync(string msg) {
 ....
}
```
then the ```Profile``` will set after call that ```SendingMessage``` so that;
I want to have another method to send and got the lastest incoming ```Profile``` result to response back like this;

```javascript

public Task<Profile> RetrievedProfileAsync(string id) {
var tcs = new TaskCompletionSource<Profile>();
try {
    
    this.WhenAnyValue(x => x.Profile).Where( x=> x!=null)
         .Subscribe(x => tcs.TryToSetValue(x));

    SendMessageAsync( " { ProfileId : Id } ");

}
catch (Exception ex) {
    tcs.TryToSetException(ex);
}

    return tcs.Task;
}


```

Then after this statement done, all Observable will broken and freeze somewhere else, Did i have to implement another way to work around this case

Thanks : )

**Comment by glennawatson** [comment]
Hi there,

We ask that questions be asked on https://stackoverflow.com/tags/reactiveui or on our slack channel.
