### ISSUE TITLE
[BUG] WhenActivated of a shown View and ViewModel is not called when in ViewModelViewHost

### ISSUE THREAD

**Issue by RwSgxx** [reactiveui/ReactiveUI#1952]
**Describe the bug**
When using ViewModelViewHost, the WhenActivated of a View and ViewModel not called and also the Compositedisposable is not disposed.

This basically renders the  ViewModelViewHost useless in Xamarin Forms.

**Steps To Reproduce**
Provide the steps to reproduce the behavior:

**Expected behavior**
When working with ViewModelViewHost the WhenActivated should be called when the view becomes visible and the Compositedisposable should be disposed when the view is not visible anymore. 

**Screenshots**

**Environment(please complete the following information):**
Xamarin Forms.  Android, iOS, UWP.

**Additional context**
It works in WPF.

**Comment by RwSgxx** [comment]
Does this depend on:

[UWP, Android, iOS] Added better life cycle events #3214
https://github.com/xamarin/Xamarin.Forms/pull/3214

and

[Enhancement] Add better life cycle events #2210
https://github.com/xamarin/Xamarin.Forms/issues/2210

?

**Comment by RLittlesII** [comment]
There is currently a bug in Xamarin.Forms on iOS that Xamararin is aware of.  They actually have the lifecycle method implemented in the wrong place for iOS.  Kent wrote a [blog](https://kent-boogaart.com/blog/hacking-xamarin.forms-page.appearing-for-ios) on it .


If you have a reproduction repository it would make it a lot easier to diagnose if it is ReactiveUI or a downstream dependency.

**Comment by glennawatson** [comment]
The xamarin group have started working on it recently https://github.com/xamarin/Xamarin.Forms/pull/3214

**Comment by gsgou** [comment]
> xamarin/Xamarin.Forms#3214

#3214 is closed

**Comment by RLittlesII** [comment]
It is closed.  Doesn't look like the work is actually completed.

https://github.com/xamarin/Xamarin.Forms/pull/3214#issuecomment-487943808

**Comment by gsgou** [comment]
Right. Looks like we have to subscribe on this one:
https://github.com/xamarin/Xamarin.Forms/issues/2210
