### ISSUE TITLE
Null pointer exception in the new setter methods.

### ISSUE THREAD

**Issue by glennawatson** [reactiveui/ReactiveUI#1959]
Hi there @glennawatson @gpriaulx! Thank you for the work on ReactiveUI it is great! :)

This commit unfortunately breaks some functionality. If a property value of a binding was null, the framework could (in v9.10.7) cleanly convert it into something appropriate. Example:
```csharp
this.WhenActivated(disposable =>
{
    this.WhenAnyValue(x => x.FormText)
        .BindTo(this, x => x.Text)
        .DisposeWith(disposable);
});
```

Please note that `this` refers to a Form. If for some reason the property `FormText` is `null` then an exception is thrown like:
 
```
PropertyBinderImplementation: x.Text Binding received an Exception!: System.NullReferenceException: Object reference not set to an instance of an object.
   at ReactiveUI.PropertyBinderImplementation.<>c__DisplayClass10_0`3.<BindToDirect>g__SetThenGet|0(Object paramTarget, Object paramValue, Object[] paramParams) in somepath\src\ReactiveUI\Bindings\Property\PropertyBinderImplementation.cs:line 459
   at ReactiveUI.PropertyBinderImplementation.<>c__DisplayClass10_0`3.<BindToDirect>b__1(TObs x) in somepath\src\ReactiveUI\Bindings\Property\PropertyBinderImplementation.cs:line 475
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in somepath\src\System.Reactive\Linq\Observable\Select.cs:line 39
```

_Originally posted by @axgdev in https://github.com/reactiveui/ReactiveUI/pull/1956#issuecomment-466046481_

**Comment by ronaldvdv** [comment]
I'm seeing the same problem and exception message in WPF since upgrading from 9.10.7 to 9.11.1

**Comment by Maskime** [comment]
I'm seeing this in the `samples/getting-started/ReactiveDemo` application.

**Comment by glennawatson** [comment]
I will be looking sometime this week.

**Comment by andrejpanjan** [comment]
I have the same issue (in WPF) all over the project after an upgrade from 9.10.7 to 9.11.1.

**Comment by MarkusKgit** [comment]
This is where it is throwing for me (tested with the Demo): https://github.com/reactiveui/ReactiveUI/blob/218cf245aae0e7ce8f2a9bbf1a09ec55306181f7/src/ReactiveUI/Bindings/Property/PropertyBinderImplementation.cs#L459
It is throwing because paramvalue is null. Adding a NullCheck like `paramValue?.GetType()` fixes the Demo for me. But my understanding of the code is far from deep enough to judge if it's the right fix.

**Comment by glennawatson** [comment]
Apologies in the delay in fixing it up. Thanks @MarkusKgit for the diagnosis.

**Comment by HofmeisterAn** [comment]
It seams like this issue also break your example in chapter [Getting Started](https://reactiveui.net/docs/getting-started/). I get the same null pointer exception with version 9.11.3. With 9.10.7 everything works fine.

**Comment by RLittlesII** [comment]
I just tested the sample with v9.11.3 and everything seems to be in order.  Prior to that I was getting some odd compilation issues.  I was able to search for the ReactiveUI packages and the Xamarin.Forms package without issue.

**Comment by HofmeisterAn** [comment]
That’s odd. I tested it with WPF yesterday.  If I remember correctly the error occurred within `OneWayBind`. After the downgrade everything worked fine. I'll look at it again tomorrow at noon and provide more information.

**Comment by glennawatson** [comment]
It was grabbing 9.11.1 (look at the file in your bin directory) for me. I had to wipe my nuget cache, bin/obj directories to make sure it was grabbing 9.11.3 -- maybe that can assist you in your testing @HofmeisterAn

**Comment by HofmeisterAn** [comment]
That happened to me, too. 9.11.3 works fine :thumbsup:. Sorry for the inconvenience.
