### ISSUE TITLE
view in model

### ISSUE THREAD

**Issue by ft9788501** [reactiveui/ReactiveUI#1969]
Please note although we can't commit to any timeline, priority will be given to those who are [Contributors](https://github.com/reactiveui/ReactiveUI#contribute ) to the project.

If this is a question please ask on [StackOverflow](https://stackoverflow.com/questions/tagged/reactiveui).

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Describe suggestions on how to achieve the feature**
A clear description to how to achieve the feature.

**Additional context**

**Comment by glennawatson** [comment]
Hi it doesn't seem to be any content? Closing.
