### ISSUE TITLE
Different Exception Handling while Executing a command

### ISSUE THREAD

**Issue by gerardo-lijs** [reactiveui/ReactiveUI#1977]
In WPF, when I execute a command using a normal binding (either code behing or XAML) if an exception is raised the Default Exception Handler works as expected.

But if I execute the command from a Click Event for example, the exception is not working. Not sure if there is a better method to manually execute Commands without an explicit Binding.

This code does not raise the exception
```csharp
private void TestDataGrid_MouseDoubleClick(object sender, MouseButtonEventArgs e)
{
	ViewModel.ItemSelectedOpen.Execute();
}
```

While this one in WhenActivated() does
```csharp
this.BindCommand(this.ViewModel, viewModel => viewModel.ItemSelectedOpen, view => view.ItemOpenButton).DisposeWith(disposableRegistration);
```

It's not critical and I can avoid the event to make it work, but just curious about this behavior or if  Command.Execute()  is the right way.

**Comment by gerardo-lijs** [comment]
Never mind, looks like I need to add the Suscribe at the end! It works now, getting it double but will try to fix that now

```csharp
private void TestDataGrid_MouseDoubleClick(object sender, MouseButtonEventArgs e)
{
	ViewModel.ItemSelectedOpen.Execute().Subscribe();
}
```

**Comment by glennawatson** [comment]
Yeah. The execute is a IObservable is lazy by default so makes sense your issue. You can use the reactiveui.events.wpf package to get observable for events.
Eg

`TestDataGrid.Events().Click.Select(args => Unit.Default).InvokeCommand(this, x => x.ViewModel.Refresh);`

**Comment by gerardo-lijs** [comment]
Thanks @glennawatson Worked perfectly! Much better way to Invoke the commands. I'm a big fan of ReactiveUI. Keep up the great work!

By the way, I was getting the double MessageBox because DispatcherUnhandledException and RxApp.DefaultExceptionHandler are both fired even though my code in DispatcherUnhandledException sets the e.Handled = true
