### ISSUE TITLE
The open/close Menu button becomes invisible indefinitely, after you open the menu and click a menu item within the  Xamarin Master Details Sample on a IOS simulator or actual device

### ISSUE THREAD

**Issue by me1986au** [reactiveui/ReactiveUI#1992]
I've downloaded the Xamarin Forms  Master-Details sample and tested it on an IOS device and simulator and found that 

The open/close Menu button becomes in-visible indefinitely, after you click the open/close menu button and then a menu item

The open/close menu button should stay visible. especially in the case that you set it as an ICON. For example a hamburger image

Please see attached, in your sample the word "Master" in the top left hand side of the first screenshot acts as the open/close menu button.  as you can see it is not visible in the the third screenshot.

<img width="394" alt="Screen Shot1" src="https://user-images.githubusercontent.com/13826361/55526483-ddbad380-56c7-11e9-88b0-56d97a6020bf.png">
<img width="407" alt="Screen Shot2" src="https://user-images.githubusercontent.com/13826361/55526484-de536a00-56c7-11e9-9a7f-d61b029e6252.png">
<img width="419" alt="Screen Shot3" src="https://user-images.githubusercontent.com/13826361/55526485-de536a00-56c7-11e9-96b3-6998a3852c34.png">

**Comment by wislon** [comment]
This has been a problem for years. Here's a quick workaround (once you've set up your master-detail pages), it would look something like:

```
                var masterPage = new NavigationView(/*your dependencies here*/)
                {
                    Title = "some title"
                };

                var masterDetailPage = new MasterDetailPage()
                {
                    Master = masterPage,
                    Detail = _detailPage,
                    MasterBehavior = MasterBehavior.Popover
                };

                //On iOS the Icon disappears when changing pages, so make sure it comes back
                _detailPage.PoppedToRoot += (sender, e) =>
                {
                    masterPage.Icon = (FileImageSource)ImageSource.FromFile("burger_menu");
                };
                masterPage.Icon = (FileImageSource)ImageSource.FromFile("burger_menu");

                return masterDetailPage;
```
HTH

**Comment by bluekuen** [comment]
I made it this way in MainPage.xaml.cs because we are not setting Detail page explicitly:

(Detail as NavigationPage).PoppedToRoot += MainPage_PoppedToRoot;

        private void MainPage_PoppedToRoot(object sender, NavigationEventArgs e)
        {
            Icon = (FileImageSource)ImageSource.FromFile("hamburger.png");
        }

But the Icon is still not showing. The Icon doesn't get set when navigating. 

Please someone help.

**Comment by glennawatson** [comment]
@bluekuen Jump on slack, people are there able to help. There is a smaller audience of people monitoring the issues here who can help. 

https://reactiveui.net/slack

**Comment by carbon-paulc** [comment]
@bluekuen I've just tried this and it works.  Are you by any chance trying to set the icon of the ReactiveMasterDetailPage rather than the ReactiveMasterDetailPage.Master Icon?  So above should look like:
```
        private void ViewHost_PoppedToRoot(object sender, Xamarin.Forms.NavigationEventArgs e)
        {
            Master.Icon = (FileImageSource)ImageSource.FromFile("hamburger_icon.png");
        }
```

Only issue I have with this is that there's a flicker where the menu icon disappears.

**Comment by carbon-paulc** [comment]
As an update - it seems the flicker can be stopped by assigning the image using the ViewHost property changed.  I've used [ReactiveUI.Events](https://reactiveui.net/docs/handbook/events/) and this in the ReactiveMasterDetailPage implementation eg: 

```
    public partial class MainPage : ReactiveMasterDetailPage<MainViewModel>
    {
        public MainPage(MainViewModel viewModel)
        {
            ViewModel = viewModel;

            InitializeComponent();

            this.WhenActivated(
                disposables =>
                {

                    // This resets the icon as ios seems to sometimes lose it
                    if (Device.RuntimePlatform == Device.iOS)
                    {
                        ViewHost
                            .Events()
                            .PropertyChanged
                            .Subscribe(e =>
                            {
                                if (e.PropertyName == nameof(ViewHost.RootPage))
                                    Master.Icon = (FileImageSource)ImageSource.FromFile(Master.Icon.File);
                            })
                            .DisposeWith(disposables);
                    }
                });
        }
    }
```

**Comment by bluekuen** [comment]
Hello @carbon-paulc,
 I've tested it and it works like a charm ! i was assigning the icon to the mainpage,
Thank you for your investigation, you helped me alot!

**Comment by glennawatson** [comment]
IS this issue resolved now? Can I close it?

**Comment by bluekuen** [comment]
Yes

**Comment by glennawatson** [comment]
Thanks

**Comment by bluekuen** [comment]
Issue does happen again in Xamarin 4.1 on iOS. 
@carbon-paulc  did you already update ?
