### ISSUE TITLE
[BUG] ReactiveCommand seems to block ToList, ToArray, etc

### ISSUE THREAD

**Issue by gtbuchanan** [reactiveui/ReactiveUI#1997]
**Describe the bug**
`ReactiveCommand` seems to block any `To*` methods called on it, such as `ToList` and `ToArray`. I've tried different schedulers (MainThread, TaskPool, Immediate) and different platforms, to no avail. No idea what could be going on here.

**Steps To Reproduce**
Call `ToArray`, `ToList`, `ToDictionary` and probably others on `ReactiveCommand`. The resulting sequence never returns anything.

**Expected behavior**
The resulting sequence should contain a single result.

**Environment**
- OS: Android, iOS, UWP, .NET Core
- Version: ReactiveUI 9.12.1

**Additional context**
[RxTest.zip](https://github.com/reactiveui/ReactiveUI/files/3066307/RxTest.zip)

**Comment by gtbuchanan** [comment]
Just realized this is probably because the sequence never completes. D'oh.

**Comment by glennawatson** [comment]
You can use dynamicdata for this, since it just updates as you go along. I believe you're correct about the sequence thing.
