### ISSUE TITLE
[BUG] ReactiveTabbedPage navigation not working

### ISSUE THREAD

**Issue by bluekuen** [reactiveui/ReactiveUI#2001]
I have a ReactiveMasterDetailPage (HostScreen) from which i navigate to a ReactiveTabbedPage.
Now i can't navigate to another Page. The ViewModel gets added on the NavigationStack but nothing is happening. 

I navigate with following method:
HostScreen.Router.Navigate.Execute(deviceSettingsVM);

**Steps To Reproduce**
1. Create MasterDetailPage.
2. Navigate to a ReactiveTabbedPage
3. From within the TabbedPage, try to navigate to another page. 

**Expected behavior**
Navigating to another page. 

**Environment**
- OS:       Xamarin.Forms Android
- Version   9.0
- Device:   SM-T825

**Comment by RLittlesII** [comment]
Is it possible to ask for a reproduction repository?  It would go a long way to helping identify and resolve this issue.

Also, do you have different `IScreen` registered for the Master Detail vs the Tabbed Navigation?

**Comment by bluekuen** [comment]
Thanks for answer !  I will create a reproduction repo this  week but today  unfortunately no time and cant provide the current one.

No i only use the IScreen from my MasterDetail, i tried with  extending my reactivetabbed vm with IScreen and navigating from the TabbedPage but with no success.

**Comment by bluekuen** [comment]
Nevermind, i fixed it myself.

I just had to add await in front of my call to Navigate like:

await HostScreen.Router.Navigate.Execute(deviceSettingsVM);

I didn't know you can await this, Intellisense didn't show awaitable as soon as i 
added using for System.Reactive.Linq. 

Sorry for the inconvenience, i'm pretty new to Reactive programming and thank you for your time, i appreciate it!

**Comment by glennawatson** [comment]
You can also do

`HostScreen.Router.Nvigation.Execute(deviceSettingsVM).Subscribe();`

**Comment by bluekuen** [comment]
@glennawatson oh ok, does subscribe not create an observable which needs to be disposed ? 
I didn't know you can use subscribe for one time operations.

**Comment by xleon** [comment]
> oh ok, does subscribe not create an observable which needs to be disposed ? I didn't know you can use subscribe for one time operations.
That´s actually one of my biggest doubts.
Some times I wrote things like `MyObservable.Execute().Subscribe().Dispose()` successfully but it doesn´t always work.

**Comment by glennawatson** [comment]
You don't need to dispose of Execute's observables, since it'll finish executing and hence the observable will finish.

Often people big mistake is to over dispose in Reactive programming. Dispose in reactive programming means "unsubscribe from the event" or in command's case "Stop performing the action".

You don't need to dispose of everything (and shouldn't) in Reactive/ReactiveUI

A good guide is :
https://github.com/cabauman/Rx.Net-ReactiveUI-CheatSheet#when-should-i-bother-disposing-of-idisposable-objects

Also worth noting your await is effectively Subscribe() wrapper anyway.

**Comment by bluekuen** [comment]
Thank you very much for the clarification and the helpful Link glen! much appreciated!

**Comment by xleon** [comment]
Thanks @glennawatson 
Very helpful
