### ISSUE TITLE
Update from MsBuild.Sdk.Extras to 2.0.24

### ISSUE THREAD

**Issue by glennawatson** [reactiveui/ReactiveUI#2026]
At the moment we are locked into MsBuild.Sdk.Extras by @onovotny to 1.6.68

Update to 2.0.24

At the moment #2021  is blocking us from upgrading.

**Comment by glennawatson** [comment]
As per the topic in https://github.com/reactiveui/ReactiveUI/issues/2021 this will have to wait until we upgrade the building on .net core 3.0

**Comment by RLittlesII** [comment]
Closing this as the MsBuild.Sdk.Extras version is now using a version higher than 2.0.24
