### ISSUE TITLE
RoutedViewHost disappeared from ReactiveUI UWP assembly in 9.14+

### ISSUE THREAD

**Issue by worldbeater** [reactiveui/ReactiveUI#2029]
**Describe the bug**

The `RoutedViewHost` control exists in ReactiveUI v9.13 and lower, but does not exist in v9.14+

**Steps To Reproduce**

See [repro](https://github.com/worldbeater/ReactiveUI.UwpRouting). Go to `.csproj`, change ReactiveUI version from 9.13 to 9.14 and it won't compile.

**Expected behavior**

`RoutedViewHost` should not disappear from ReactiveUI for UWP builds.

**Screenshots**

![image](https://user-images.githubusercontent.com/6759207/57614604-5728ca00-7582-11e9-9770-73cbcdb17912.png)

**Environment**

- OS: Windows 10
- Version: UWP SDK 1809 Build 17763
- Device: Windows Intel PC

**Comment by glennawatson** [comment]
[App5_TemporaryKey.zip](https://github.com/reactiveui/ReactiveUI/files/3172466/App5_TemporaryKey.zip)

Seems to work with that one?

**Comment by glennawatson** [comment]
Closing this one out..

Was able to get it to work with two changes to your repo.

Min version was changed to 10.0.17763.0 due to Microsoft requiring that is a minimum on Azure Devops

```
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
```

Also seems that this is out of date?

```
<PackageReference Include="Microsoft.NETCore.UniversalWindowsPlatform">
      <Version>6.2.8</Version>
    </PackageReference>
```

**Comment by worldbeater** [comment]
Thank you, with ReactiveUI 9.15 and 10.0.17763.0 it worksfine! 💖
