### ISSUE TITLE
[BUG] ReactiveUserControl is missing from the ReactiveUI namespace

### ISSUE THREAD

**Issue by miktap** [reactiveui/ReactiveUI#2031]
**Describe the bug**
Class `ReactiveUserControl<TViewModel>` is missing from the latest (9.15.1) `ReactiveUI` nuget package.

**Steps To Reproduce**
Provide the steps to reproduce the behavior:
1. Create new UWP application
2. Install `ReactiveUI` v9.15.1 nuget package
3. Try to use `ReactiveUI.ReactiveUserControl<TViewModel>` class

**Expected behavior**
The `ReactiveUserControl<TViewModel>` class is found.

**Screenshots**

**Environment**

- OS:       Windows10
- Version   10.0.17763
- Device:   Desktop

**Additional context**

**Comment by glennawatson** [comment]
```
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
```

Minimum version in 9.14 and above is 10.0.17763.0

Changed the release notes to make that more obvious now.

This change was required by Azure DevOps having that as a minimum on their servers.
