### ISSUE TITLE
[BUG] View Location does not work with WPF DataGrid

### ISSUE THREAD

**Issue by andrejpanjan** [reactiveui/ReactiveUI#2036]
**Describe the bug**
View Location does not work for WPF `DataGrid` when you Bind to `ItemsSource`.

**Steps To Reproduce**
1. Create a `ViewModel` class.
2. Create a `View` class that derives from `ReactiveUserControl<ViewModel>`.
3. Create a list of `ViewModel`-s (`List<ViewModel> viewModelsList`).
4. Put a `DataGrid datagrid` in a new window.
5. Set `DataGrid.ItemsSource = viewModelsList`.
6. Run.
7. The View is not loaded into the `datagrid `.

**Expected behavior**
The `View` should be loaded into the `datagrid `.

**Screenshots**

![image](https://user-images.githubusercontent.com/7609378/57935393-fbcc4400-78c1-11e9-866e-49b074df6813.png)

**Environment**

- OS:       Windows 10
- Version   9.13.1
- GUI framework: WPF

**Comment by glennawatson** [comment]
Realistically probably not something we are going to support. You could try setting a datatemplate column and use a ViewModelViewHost. DataGrid are funky though since they have a editing state and a column state.
