### ISSUE TITLE
[BUG] ReactiveUI.XamForms, WhenActivated generates FileNotFoundException Could not load file or assembly 'ReactiveUI.Wpf' or one of its dependencies

### ISSUE THREAD

**Issue by AkilaeTribe** [reactiveui/ReactiveUI#2038]
**Describe the bug**
In a Xamarin Forms projet, Using for the first time ReactiveUI.ViewForMixins.WhenActivated(this IActivatable @this, Action<CompositeDisposable> block, IViewFor view = null) generates two exceptions 

System.IO.FileNotFoundException: Timeout exceeded getting exception details
System.IO.FileNotFoundException: Could not load file or assembly 'ReactiveUI.Wpf' or one of its dependencies

**Steps To Reproduce**
1. Create new Xamarin Forms project (the starting root page should not be relevant to the issue)
2. Install ReactiveUI.XamForms (problems seems present on 9.15.1 and 10.0.1-preview.3)
3. Declare a view model (no property or base class required)
4. Change base type of starting root page to matching ReactiveUI.XamForms one and using the view model type
5. Instantiate a view model inside the starting root page constructor, and assign it to BindingContext
6. Add in constructor this.WhenActivated(disposables => { });
7. Ensure FileNotFoundException type is checked, in the Exception Settings window
8. Run application for Android in Debug mode, using an emulator

**Expected behavior**
No exception happens.

**Screenshots**
![Exception1](https://user-images.githubusercontent.com/16439698/57970760-845fe880-7985-11e9-986f-f8a469d4a19f.PNG)
![Exception2](https://user-images.githubusercontent.com/16439698/57970759-845fe880-7985-11e9-89a8-7760dfc55174.PNG)

**Environment**
- OS:       Windows 8.1 Professional
- Version   Android API 28 (emulator)
- Device:   Pixel (emulator)
- IDE:     Visual Studio 2019 Community 16.0.4

**Additional context**

Solution for reproduction
[MonoReactiveUI.zip](https://github.com/reactiveui/ReactiveUI/files/3194123/MonoReactiveUI.zip)

**Comment by glennawatson** [comment]
These won't crash your application correct? We just check for a series of approved DLLs. I don't believe this is a bug.

**Comment by AkilaeTribe** [comment]
> These won't crash your application correct?

This is correct, the application does not crash.

> We just check for a series of approved DLLs.

@glennawatson  I apologize, I am unsure about the meaning of that sentence. Would you like to elaborate, please ? Are opened bug issues only handled if they are related to specific versions ? Or there is some hardcoded part that looks for specific versions of DLLs ?

> I don't believe this is a bug.

If this is not a bug, then, do you agree that the exceptions are suspicious ? This is a Xamarin Forms project, with only one added NuGet package related to Xamarin Forms, yet the exception explicitly mentions Wpf. Even with a respectable '[Google-fu](https://en.wiktionary.org/wiki/Google-fu)" skill, I was not able to find anything related to it, suggesting that I was doing something wrong.

**Comment by glennawatson** [comment]
No not suspicious. 

https://github.com/reactiveui/ReactiveUI/blob/ddb56c7f037f07ba3bec45f77db262d1050661bc/src/ReactiveUI/Mixins/DependencyResolverMixins.cs#L34

As I already said comes from our list of approved assemblies

**Comment by glennawatson** [comment]
Anyway locking this topic.

**Comment by glennawatson** [comment]
Btw don't feel too bad about the issue being locked. I am going to be locking most resolved issues from now on since we been having a lot of instances of people commenting on 4 year old bugs with new bugs.

**Comment by glennawatson** [comment]
So two changes that are happening as a response to this. We will be adding a section to the documentation just commenting on this side effect. Second initialisation is changing in rxui for V10 and this will eliminate these exceptions.

**Comment by RLittlesII** [comment]
Further progress for this can be tracked on #1737
