### ISSUE TITLE
[BUG] Android references ReactiveUI.Winforms

### ISSUE THREAD

**Issue by jalbertSyncroTech** [reactiveui/ReactiveUI#2049]
**Describe the bug**
When debugging on Android and breaking on all exceptions, the first call to ReactiveUI, which in turn calls DependencyResolverMixins.InitializeReactiveUI, tries to load the assembly ReactiveUI.Winforms which is obviously not included in the Android build.

**Steps To Reproduce**
1. In VS2017/2019 Check Debug -> Windows -> Exception Settings -> Common Language Runtime Exceptions
2. Use any ReactiveUI function that triggers DependencyResolverMixins.InitializeReactiveUI

**Expected behavior**
The Android build should not reference ReactiveUI.Winforms or throw an unnecessary exception on startup

**Environment**
- OS: monoandroid90
- Version: 9.13.1
- Device: VS2019/Android

**Additional Context**
I'd be happy to debug into ReactiveUI/Splat to investigate further if someone could point me to the relevant .pdb files, since Source Link isn't supported when debugging on Android

**Call Stack**
 	0x76 in System.AppDomain.Load	C#
 	0x3 in System.AppDomain.Load	C#
 	0x6 in System.Reflection.Assembly.Load	C#
 	0x3B in ReactiveUI.Reflection.<>c.<.cctor>b__16_1	C#
 	0x2E in System.TypeSpec.Resolve	C#
 	0xB in System.TypeNameParser.GetType	C#
 	0x9 in System.Type.GetType	C#
 	0x22 in ReactiveUI.Reflection.<>c.<.cctor>b__16_0	C#
 	0x3F in Splat.MemoizingMRUCache<string,System.Type>.Get	C#
 	0x3 in Splat.MemoizingMRUCache<string,System.Type>.Get	C#
 	0x6 in ReactiveUI.Reflection.ReallyFindType	C#
 	0x35 in ReactiveUI.DependencyResolverMixins.ProcessRegistrationForNamespace	C#
 	0xD in ReactiveUI.DependencyResolverMixins.	C#
 	0x12 in ReactiveUI.CompatMixins.ForEach<string>	C#
 	0x99 in ReactiveUI.DependencyResolverMixins.InitializeReactiveUI	C#
 	0xD in ReactiveUI.RxApp.<>c.<.cctor>b__11_0	C#
 	0x50 in Splat.InternalLocator.RegisterResolverCallbackChanged	C#
 	0x6 in Splat.Locator.RegisterResolverCallbackChanged	C#
 	0x20 in ReactiveUI.RxApp..cctor	C#
 	0x39 in ReactiveUI.ReactiveCommand.Create	C#

**Comment by glennawatson** [comment]
Hey there this behaviour is normal. We hard code a list of modules we'll load in at runtime. 

We will be revamping initialisation soon for a future major release and this exception will disappear then. 

Thanks

**Comment by glennawatson** [comment]
https://github.com/reactiveui/ReactiveUI/blob/87cb10f9b82d04cf24d4c5cc4e5d1ee845493350/src/ReactiveUI/Mixins/DependencyResolverMixins.cs#L32 is the location we do it btw. We will be documenting this behaviour under our platform notes.

**Comment by jalbertSyncroTech** [comment]
@glennawatson Thanks! Obviously it's just an inconvenience since the exception isn't fatal, but since I couldn't find any other bug reports on the issue I wanted to at least verify it was working as expected.
