### ISSUE TITLE
Reactive 9.16.4 breaks WireUpControls for ReactiveUI.AndroidSupport.ReactiveFragment.

### ISSUE THREAD

**Issue by bfmyr4** [reactiveui/ReactiveUI#2052]
this.WireUpControls() no longer compiles inside a Fragment descended from ReactiveUI.AndroidSupport.ReactiveFragment.

Fragment in ReactiveUI.AndroidSupport.ControlFetcherMixin.WireUpControls (this Fragment fragment, View inflatedView, ReactiveUI.ControlFetcherMixin.ResolveStrategy resolveMembers = ReactiveUI.ControlFetcherMixin.ResolveStrategy.Implicit) in prior versions was Android.Support.V4.App.Fragment. It now is Android.App.Fragment.

**Comment by glennawatson** [comment]
Thanks for the bug report @bfmyr4

**Comment by glennawatson** [comment]
Fixed by #2054
