### ISSUE TITLE
RxUI 9.16.6 does not install properly in UWP app

### ISSUE THREAD

**Issue by wldevries** [reactiveui/ReactiveUI#2058]
After upgrading ReactiveUI from 9.10.1 to 9.16.6 in my x86 UWP app I get the following exception:

`Exception: You are referencing the Portable version of ReactiveUI in an App. Please change your reference to the specific version for your platform found here: https://reactiveui.net/docs/getting-started/installation/nuget-packages`

I'm not sure how to fix this since UWP uses the new package references project style.

In addition to not being able to use the latest version of ReactiveUI the link in the exception is broken.

**Steps To Reproduce**
Create UWP app targeting build 17763 and min version build 16299
Install RxUI 9.10.1
Update to 9.16.6

**Expected behavior**
Update runs fine and app runs as is

**Environment**
VS Pro 2019 16.1.1
- OS:       W10 x64 
- Version   v1809 b17763.529
- Device:   desktop

**Additional context**

**Comment by glennawatson** [comment]
https://github.com/reactiveui/ReactiveUI/releases/tag/9.15.1 I seen that type of error if the uwp target hasn't been changed after that release.

**Comment by wldevries** [comment]
Confirmed, setting the min version to 17763 fixes the issue.

I really dislike the moving target aspect of the libraries of today, whatever happened to backwards compatibility on the Microsoft platforms.

**Comment by wldevries** [comment]
The Nuget package has UAP version requirement v10.0.0.17763, but installs on projects targeting earlier Windows builds nonetheless because it can use the alternate .NETStandard,Version=v2.0 target as well.

**Comment by glennawatson** [comment]
Yeah. They kind of forced us to upgrade since I submitted a PR about 5 months ago to fix the build servers. They only in the last week approved and implement and have to wait for their build servers to it update before I can go back. 16299 is the important one due to it being the first supporting net standard 2.0
