### ISSUE TITLE
Broken link in PlatformRegistrations

### ISSUE THREAD

**Issue by wldevries** [reactiveui/ReactiveUI#2059]
Link in `PlatformRegistrations` is incorrect.

**Describe the bug**
The exception message mentions the link https://reactiveui.net/docs/getting-started/installation/nuget-packages which is broken.

It should probably link to: https://reactiveui.net/docs/getting-started/installation/

**Comment by glennawatson** [comment]
Duplicate of https://github.com/reactiveui/ReactiveUI/issues/2053
