### ISSUE TITLE
feature: Add Xamarin.Forms Collection View support

### ISSUE THREAD

**Issue by RLittlesII** [reactiveui/ReactiveUI#2068]
**Is your feature request related to a problem? Please describe.**

Create a `ReactiveCollectionView` that provides `IViewFor` and `IReactiveObject` implementations for [Xamarin.Forms Collectin View](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.collectionview?view=xamarin-forms)

**Describe the solution you'd like**

I would like a `ReactiveCollectionView` the same as I have at the Xamarin.iOS layer

https://github.com/reactiveui/ReactiveUI/blob/master/src/ReactiveUI/Platforms/uikit-common/ReactiveCollectionView.cs

**Describe alternatives you've considered**

None.

**Describe suggestions on how to achieve the feature**

**Additional context**

**Comment by HobDev** [comment]
This feature is of vital importance for xamarin.forms developers. Any updates?

**Comment by glennawatson** [comment]
We aren't planning to in the short term. Welcome pull requests though.
