### ISSUE TITLE
[BUG] Summary of item

### ISSUE THREAD

**Issue by zipswich** [reactiveui/ReactiveUI#2069]
//The following code shows CreationCollisionOption.ReplaceExisting is treated as CreationCollisionOption.OpenIfExists
            StorageFile sfFoo = await ApplicationData.Current.LocalFolder.CreateFileAsync("foo", CreationCollisionOption.ReplaceExisting);
            using (StreamWriter dr = new StreamWriter(await sfFoo.OpenStreamForWriteAsync()))
            {
                await dr.WriteAsync("this is foo + foo");
                await dr.FlushAsync();
                dr.Close(); //Supposed to be redundant
            }
            StorageFile sfFoo2 = await ApplicationData.Current.LocalFolder.CreateFileAsync("foo", CreationCollisionOption.ReplaceExisting);
            using (StreamWriter dr = new StreamWriter(await sfFoo.OpenStreamForWriteAsync()))
            {
                await dr.WriteAsync("this is abc");
                await dr.FlushAsync();
                dr.Close(); //Supposed to be redundant
            }

            StorageFile sfFooRead = await ApplicationData.Current.LocalFolder.GetFileAsync("foo");
            using (FileStream stream = File.OpenRead(sfFooRead.Path))
            using (StreamReader sr = new StreamReader(stream))
            {
                {
                    //The following outputs: "this is abc + foo"
                    //It is supposed to be: "this is abc"
                    Console.WriteLine(sr.ReadToEnd());
                }
            }

**Environment**

- OS:       iOS
- Version   12
- Device:   Simulator

Repro:
https://github.com/zipswich/UnoDebug

**Comment by glennawatson** [comment]
The code your highlighting is part of UWP and the windows storage API, just curious how this relates to ReactiveUI?

**Comment by glennawatson** [comment]
Going to close this one until we have further information. Feel free to comment back if you have more information how it relates to ReactiveUI.

**Comment by zipswich** [comment]
Very sorry, opened the issue at wrong place.
