### ISSUE TITLE
[BUG] RoutedViewHost Example from ReactiveUI Handbook doesn't work as expected

### ISSUE THREAD

**Issue by M0n7y5** [reactiveui/ReactiveUI#2076]
**Describe the bug**
RoutedViewHost doesn't go back to the default content. Also you must click on Go First button twice in order to enable Go Back button.

**Steps To Reproduce**
Just follow guide  here https://reactiveui.net/docs/handbook/routing/ and compile Routing example.

**Expected behavior**
Going back to default content & enable NavigateBack after one click on GoFirst

**Screenshots**
![SNcBK4hcRQ](https://user-images.githubusercontent.com/17201053/59606177-c610ba00-9110-11e9-9aef-5236c0a942b4.gif)

**Environment**
- OS:       Win 10 build 1803
- Version   9.17.4
- Device:   PC

**Comment by RLittlesII** [comment]
Do you happen to have the code that generated this issue in a repository we can access?  Just want to be sure there is no additional code that might be causing issues.  Also going to make the assumption this is WPF and not UWP or WinForms.

**Comment by M0n7y5** [comment]
@RLittlesII No i don't have this code in online repository. It's just exact code from online Handbook (ReactiveUI website). And yes this is WPF ... i forgot to mention it.

**Comment by RLittlesII** [comment]
@M0n7y5 I was able to reproduce your issue last night.  I am going to try and find a solution to the issue.  Seems that there is a disconnect for sure in the docs.  The video of the working sample in the docs, is indeed different than what you get by implementing it.

Thank You for reporting this.

**Comment by worldbeater** [comment]
To have the behavior from the GIF recording located at https://reactiveui.net/docs/handbook/routing/ the following line of code from the tutorial: 
```cs
GoBack = Router.NavigateBack;
```
Should be replaced with this line:
```cs
GoBack = ReactiveCommand.CreateFromObservable(
      () => Router.NavigateBack.Execute(Unit.Default));
```
Although there is a risk to get the `IndexOutOfBoundsException`. Ideally need to define the `canGoBack` condition via a call to `WhenAnyValue` and pass it to the reactive command. Probably we should simply replace the GIF from the tutorial to another one for simplicity, and mention other back button handling scenarios.

**Comment by stokara** [comment]
var canGoBack = this.WhenAnyValue(x => x.Router.NavigationStack.Count).Select( cnt => cnt > 0);
            GoBack = ReactiveCommand.CreateFromObservable(() => Router.NavigateBack.Execute(Unit.Default), canGoBack);

**Comment by glennawatson** [comment]
Seems to be a workaround.
