### ISSUE TITLE
[BUG] mouse events missing from 9.17.4

### ISSUE THREAD

**Issue by ChrisPulman** [reactiveui/ReactiveUI#2077]
**Describe the bug**
Update to ReactiveUI.Events.WPF V9.17.4 from V9.16.9 causes some of the events not to validate

**Steps To Reproduce**
Provide the steps to reproduce the behavior:
1. Go to Nuget, Update to ReactiveUI.Events.WPF V9.17.4 from V9.16.9
2. Click on 'Clean, Rebuild'
3. Go to a UserControl, Add this.Events().MouseMove.Subscribe();
add using System.Windows.Controls;
Error	CS1061	'ControlEvents' does not contain a definition for 'MouseMove' and no accessible extension method 'MouseMove' accepting a first argument of type 'ControlEvents' could be found (are you missing a using directive or an assembly reference?)

**Expected behavior**
MouseMove Observable is correctly resolved

**Environment**

- OS:       Windows 10 Pro
- Version   1903
- Device:   Laptop

**Additional context**
MouseMove is not the only Event that does not show up
Others include:
MouseLeftButtonUp
MouseRightButtonDown
DragOver
DragLeave
Drop
PreviewMouseDown
MouseUp
LayoutUpdated (From a Control)

**Comment by HBasler** [comment]
Hello,
the following workaround is necessary for Version 9.7.14 of ReactiveUI.EventsUI.WPF 
   var xx = (this as FrameworkElement).Events().Loaded;
   var yy = (this as UIElement).Events().KeyUp;

In preview Version the class WindowsEvents looks like
   (9.16.9) public class WindowEvents  : System.Windows.Controls.ControlEvents
know it looks 
   (9.7.14)  public class WindowEvents
and a lot of properties missing.

mfG
Helmut Basler

**Comment by glennawatson** [comment]
yeah, fairly easy fix on the way in the next 24 hours.

**Comment by glennawatson** [comment]
Fixed in 9.17.11
