### ISSUE TITLE
Add UWP tests

### ISSUE THREAD

**Issue by glennawatson** [reactiveui/ReactiveUI#2079]
At the moment none of the UWP tests run. We should see about getting xunit devices running on the build server for UWP. https://github.com/xunit/devices.xunit

**Comment by RLittlesII** [comment]
@glennawatson As far as I understand there is an issue with being able to execute these tests in a device runner from the command line.  It might work for UWP stand alone, but I am honestly not sure.

https://github.com/xunit/devices.xunit/issues/72
https://github.com/xunit/devices.xunit/issues/79

**Comment by glennawatson** [comment]
I would imagine it'd be the case of adding a new UWP project, making ReactiveUI.Tests also have a netstandard2.0 TargetFramework, and then deriving some tests from it in the first instance.

The tricky part will be getting it into the build server but would consider this done if we can get the first stage done.
