### ISSUE TITLE
Breaking change in splat 7.3.6

### ISSUE THREAD

**Issue by SimonCropp** [reactiveui/ReactiveUI#2081]
just an FYI, MemoizingMRUCache  now has an extra required runtime parameter https://github.com/reactiveui/splat/commit/161eeda1e321d038cf1e6b814b8bb7fcf9971e0a

![image](https://user-images.githubusercontent.com/122666/59915676-8a535880-9460-11e9-833e-45c2b1ab4a56.png)

which means your consumers will get this exception at runtime

```
System.MissingMethodException
Method not found: 'Void Splat.MemoizingMRUCache`2..ctor(System.Func`3<!0,System.Object,!1>, Int32, System.Action`1<!1>)'.
   at ReactiveUI.ReactiveNotifyPropertyChangedMixin..cctor()
```

**Comment by SimonCropp** [comment]
updating to the newest splat should fix this. let me know if u want a PR

**Comment by glennawatson** [comment]
We use the LibraryRange feature for NuGet so should automatically fix itself when we go to next version on NuGet. I am adding those constructors back though for other packages that rely on Splat.

**Comment by glennawatson** [comment]
https://developercommunity.visualstudio.com/content/problem/606218/error-xa5300-the-java-sdk-directory-could-not-be-f.html

**Comment by SimonCropp** [comment]
@glennawatson thanks, and no rush. i only noticed due to a dependabot auto update

**Comment by paul-charlton** [comment]
Hi, Is there a workaround for this in the meantime?  The latest release version of splat is 7.3.6, @SimonCropp did you mean use the pre-release version of splat 8.0.0-dotnet3-preview.8 ?

**Comment by glennawatson** [comment]
Just explicitly use the old version for the moment.

**Comment by glennawatson** [comment]
I would of released a fix by now but azure DevOps broke today unfortunately

**Comment by glennawatson** [comment]
Fixed by https://github.com/reactiveui/splat/pull/345

**Comment by SimonCropp** [comment]
@glennawatson thanks :)
