### ISSUE TITLE
Bring back support for 16299 for UWP apps

### ISSUE THREAD

**Issue by harvinders** [reactiveui/ReactiveUI#2103]
**Is your feature request related to a problem? Please describe.**

16299 is essential for enterprise customer, who can't/don't update to the latest version. It seems like the Azure DevOp [issue](https://github.com/microsoft/azure-pipelines-image-generation/pull/770) that was forcing RxUI to set the min version to 17763 is now merged. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Describe suggestions on how to achieve the feature**

**Additional context**

**Comment by glennawatson** [comment]
Will come back with rxui 10 which will be released soon.

**Comment by glennawatson** [comment]
Fixed by  #2102

**Comment by glennawatson** [comment]
This was released in 9.19.2 -- 10 was taking a bit too long to get out.
