### ISSUE TITLE
Add a hook for when the a View/ViewModel is removed from the navigation stack 

### ISSUE THREAD

**Issue by giusepe** [reactiveui/ReactiveUI#2115]
**Is your feature request related to a problem? Please describe.**

This issue is a result of this thread: https://reactivex.slack.com/archives/C02AJB872/p1562129797321400

Currently, on Cinephile we have this https://github.com/reactiveui/ReactiveUI.Samples/blob/master/xamarin-forms/Cinephile/Cinephile.ViewModels/UpcomingMoviesListViewModel.cs#L51

This service is not been added to the disposables and most likely casuing a memory leak, to add it to the disposables we would need to move the call to `WhenActivated` and that would be a little late in the process.
Also, adding it to the `WhenActivated` would cause some issues:
- possible flickering when going back and forward due the list been recreated
- if the user has scrolled down, detailed an item and come back to the list, the list would be recreated, flickered a bit and scrolled all the way up to the first item.

**Describe the solution you'd like**

Some suggestions on the thread were related to adding a hook to when the view is removed from the stack, but as I understand still open to discussion. 

**Describe alternatives you've considered**

**Describe suggestions on how to achieve the feature**

**Additional context**

I see this problem with Xamarin.Forms and Dynamic Data, not sure if it applies to other frameworks, platforms and libs.

**Comment by glennawatson** [comment]
We'll focus on this in sextant.
