### ISSUE TITLE
ReactiveUI.UnhandledErrorException very hard to fix

### ISSUE THREAD

**Issue by xleon** [reactiveui/ReactiveUI#2120]
**Is your feature request related to a problem? Please describe.**

In Xamarin, whenever we get this kind of exception `ReactiveUI.UnhandledErrorException` with the following message:
> An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case.

The stacktrace is not very useful (see below), thus it becomes really hard (nearly impossible sometimes) to know what part of the code is causing it. 

```
ReactiveUI.RxApp+<>c__DisplayClass11_0.<.cctor>b__2() in <f14022a837f640c48409b617fb3739d6#1429a6847e4caaa9e146a0ad1d7f9e29>:0
System.Reactive.Concurrency.Scheduler.Invoke(System.Reactive.Concurrency.IScheduler scheduler, System.Action action) in <370f6a6bb34048878534065376a195cb#1429a6847e4caaa9e146a0ad1d7f9e29>:0
ReactiveUI.NSRunloopScheduler+<>c__DisplayClass2_0`1[TState].<Schedule>b__0() in <f14022a837f640c48409b617fb3739d6#1429a6847e4caaa9e146a0ad1d7f9e29>:0
CoreFoundation.DispatchQueue.static_dispatcher_to_managed(System.IntPtr context) in <b28d782d99614fe0b872da2da418b7b8#1429a6847e4caaa9e146a0ad1d7f9e29>:0
UIKit.UIApplication.Main(System.String[] args, System.String principalClassName, System.String delegateClassName) in <b28d782d99614fe0b872da2da418b7b8#1429a6847e4caaa9e146a0ad1d7f9e29>:0
App.Mobile.Touch.Application.Main(System.String[] args) in <645aadc13efe4dfd94a4c53cc2af1ea3#1429a6847e4caaa9e146a0ad1d7f9e29>:0
UIKit.UIApplication.Main(System.String[] args, System.String principalClassName, System.String delegateClassName) in <b28d782d99614fe0b872da2da418b7b8#1429a6847e4caaa9e146a0ad1d7f9e29>:0
App.Mobile.Touch.Application.Main(System.String[] args) in <645aadc13efe4dfd94a4c53cc2af1ea3#1429a6847e4caaa9e146a0ad1d7f9e29>:0
```

**Describe the solution you'd like**

Change the error message to include the name of the failing property:
> An object with name (**[name of the property or object]**) implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case.

**Additional context**

Obviously the context of this issue is not when debugging, but looking at crashes reported for the app store / google play production app (raygun in my case)

**Comment by glennawatson** [comment]
https://github.com/reactiveui/ReactiveUI/blob/39aca809ddb702c5309fc1780a9607b45fc6ae74/src/ReactiveUI/RxApp.cs#L114

Hey there, we don't really know what's triggered that exception. Essentially we subscribe to the default exception handler above.

What you may be able to do though is look at the inner exception to get a stack trace?

**Comment by xleon** [comment]
The problem is that the inner exception is kind of broken: 
![image](https://user-images.githubusercontent.com/145087/61214902-820dd680-a709-11e9-84a8-faded21e4eaa.png)
Wondering now if that´s something related to RxUI or my code

**Comment by glennawatson** [comment]
I seen that type of thing when people dispose of ReactiveCommand and stuff. In observable land people tend to dispose a little greedily

**Comment by glennawatson** [comment]
I will attempt after 10 has been released to see if we can get some more debugging information for this one though. I'm sure multiple users will benefit from it.

**Comment by xleon** [comment]
So version 10 has changes regarding that exception?
I´ll try it as soon as it´s released and let you know then

**Comment by glennawatson** [comment]
Sorry, apologies, I meant once version 10 is out I can focus on new features like this one.

**Comment by xleon** [comment]
For now this is my workaround in a base viewmodel: 
```
try
                    {
                        await UserMessage.Handle(InteractionConfig.Alert(message, title));
                    }
                    catch (UnhandledInteractionException<InteractionConfig, bool> e)
                    {
                        Mvx.Resolve<IExceptionMonitor>().Send(e, new Dictionary<string, string>
                        {
                            ["context"] = $"{GetType().FullName}.{nameof(OnCommandException)} - token expired"
                        });
                    }
```
