### ISSUE TITLE
Create ReactiveUI.Events.Uno and publish it to NuGet

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/ReactiveUI#2135]
**Is your feature request related to a problem? Please describe.**

`ReactiveUI.Uno` now exists (yay) but `ReactiveUI.Events.Uno` does not.

**Describe the solution you'd like**

1. Access each TFM's eventhandlers as observables .
1. Access UWP eventhandlers (provided by Uno.UI) as observables on each TFM.

**Describe suggestions on how to achieve the feature**

For `netcoreapp, ios, android, uwp`

1. Take a reference to Uno.UI on each TFM
1. For each TFM (iOS, Android and UWP)
  a. Code generate that TFM's events and put that into the TFM's lib/
  b. Code generate the the UWP events and merge them into the TFM's lib/
1. For the netcoreapp TFM, code generate UWP events and merge them into the TFM's lib/ which will be used for WebAssembly projects.

**Additional context**

**Comment by glennawatson** [comment]
Realistically this will come after a upgrade is done on pharmacist. I am swapping it over to use a more efficient reflection metadata wrapper.

**Comment by glennawatson** [comment]
Pharmacist is going to deprecate the events projects soon. Which is why I haven't done Uno.
