### ISSUE TITLE
RegisterViewsForViewModels does not register my views

### ISSUE THREAD

**Issue by nicolasr75** [reactiveui/ReactiveUI#2141]
I am using ReactiveUI on Windows 10 in a WPF application. I have several views that I want to host in a ViewModelViewHost. Registering the views with 
    
    Locator.CurrentMutable.RegisterViewsForViewModels(Assembly.GetCallingAssembly());

in App.xaml.cs does not work. The output window of Visual Studio shows this

    DefaultViewLocator: Failed to resolve view for view model type 'System.Object'.
    ViewModelViewHost: The ViewModelViewHost could not find a valid view for the view model of type RSW.LEO.EBA.ViewModels.MeasuringPointComparisonViewModel and value RSW.LEO.EBA.ViewModels.MeasuringPointComparisonViewModel.

Registering my view explicitly with

    Locator.CurrentMutable.Register(() => new MeasuringPointComparisonView(), typeof(IViewFor<MeasuringPointComparisonViewModel>));

does work though. My view model looks like this

	namespace RSW.LEO.EBA.ViewModels
	{
		public class MeasuringPointComparisonViewModel : ReactiveObject
		{   
			public MeasuringPointComparisonViewModel(IDataRepository dr)
			{
			...
			}
		...
		}
	}

My view looks like this

	<reactiveui:ReactiveUserControl
		x:Class="RSW.LEO.EBA.Views.MeasuringPointComparisonView"
		x:TypeArguments="viewmodels:MeasuringPointComparisonViewModel"
		...
		xmlns:reactiveui="http://reactiveui.net"
		xmlns:viewmodels="clr-namespace:RSW.LEO.EBA.ViewModels"
	...
	</reactiveui:ReactiveUserControl>

with code-behing

	namespace RSW.LEO.EBA.Views
	{
		public partial class MeasuringPointComparisonView : ReactiveUserControl<MeasuringPointComparisonViewModel>
		{
			public MeasuringPointComparisonView()
			{
				InitializeComponent();                       

				this.WhenActivated(disposables =>
				{
					...
				});            
			} 
		}
	}

Am I doing something wrong or is this a bug?

**Comment by glennawatson** [comment]
The first question that comes to mind is wherever your calling RegisterViewsForViewModels the same assembly as your views?

**Comment by nicolasr75** [comment]
Oh, I didn't pay attention to that. Indeed, using `Assembly.GetCallingAssembly()` gives me PresentationFramework.dll which of course doesn't contain my types. I actually got that from the documentation.
However, when I switch to `Assembly.GetAssembly(typeof(MeasuredValuesExportView))` I get `System.InvalidOperationException: 'Sequence does not contain any element.'
`
I will try to debug the code of RegisterViewsForViewModels and see what happens...

**Comment by nicolasr75** [comment]
I found the problem: `private static Func<object> TypeFactory(TypeInfo typeInfo) `in DependencyResolverMixins searches for view constructors without parameters. For several reasons my MainView constructor does take a parameter which makes TypeFactory throw `'Sequence does not contain any element'.`

Since my MainView is the parent of the `ViewModelViewHost `and does not need to be registered, I will either avoid calling `RegisterViewsForViewModels `and register the views individually or just add a parameterless constructor to my MainView to avoid the error.

The documentation could maybe mention the requirement of a parameterless view constructor and it should not use `GetCallingAssembly` in the example code but use `GetExecutingAssembly` or derive the assembly from one of the view types.

**Comment by glennawatson** [comment]
Parameters based views in wpf is generally bad voodoo anyway. Eg you break the designer and live reload.

**Comment by nicolasr75** [comment]
Hmm, actually never had a problem with my main view. As I said, it's the only constructor that has a parameter but I could certainly redesign that. In contrast all my other views (ReactiveUserControls) don't have parameters and they break the designer! This ist the only fix I found https://stackoverflow.com/questions/50219382/reactiveusercontrol-cannot-be-edited-in-design-view

Anyway, it would be helpful to have two small comments in the documentation to avoid the traps I ran into. From my side you could close the issue, thanks for your time.
