### ISSUE TITLE
Adding synced API documentation of ReactiveUI with DocFX

### ISSUE THREAD

**Issue by Kavignon** [reactiveui/ReactiveUI#2146]
**Is your feature request related to a problem? Please describe.**

Along with the documentation website, I’m proposing of adding DocFX on top of ReactiveUI to keep a live documentation of the accessible APIs! Sometimes, it can end up that just seeing the APIs in one go is enough to see where you’re going. It can be hard also to make sure that documentation remains factual with time; so much change in so little time in this industry. DocFX would effortlessly document the code here.

**Describe the solution you'd like**

Add a separate Documentation project on top of the solution to keep track of every API found in the ReactiveUI project.

**Describe alternatives you've considered**

**Describe suggestions on how to achieve the feature**

**Additional context**

**Comment by RLittlesII** [comment]
@Kavignon have you seen https://reactiveui.net/api/

**Comment by glennawatson** [comment]
Closing due to already existing
