### ISSUE TITLE
Trying to improve the TransitioningContentControl/RoutedViewHost

### ISSUE THREAD

**Issue by Jasonfran** [reactiveui/ReactiveUI#2150]
Hi, I'm trying to improve the TransitioningContentControl so that it supports custom transitions that you can just bind to as currently they're all hard coded and you've got to edit the template to change them and you can only edit what is there.

I got told about this existing issue https://github.com/reactiveui/ReactiveUI/issues/930#issuecomment-138987052 with performance, so I thought I'd try and solve that too. I reworked the example from that issue into modern ReactiveUI and it performs better today than it did then. But I think the performance issue with it today is that activating WPF bindings are based on whether the view is visible. So if you add a transition into the mix then as soon as the control displays the view, the bindings are activated and you get an interrupted transition because of the loading. On simple views it's not noticeable, but on complex views such as one with 100 mini views with bindings, it is.

I think the solution to this would be to manually activate the view just before we set the content on the TransitioningContentControl. I've attempted implementing this myself but I'm struggling with how to do it properly since activating the parent view doesn't activate any views contained within it. And if a view is manually activatible it still needs the default activation that is currently present.

I've got a branch with what I've messed around with so far commented out and the RoutedViewHost is using the "ImprovedTransitioningContentControl" just so I can test it properly before moving that into the current class. https://github.com/Jasonfran/ReactiveUI/tree/Improving_the_TransitioningContentControl

**Comment by glennawatson** [comment]
Now that v10 of RxUI is out I've got time to revisit this. Will look at this in the next day or so.
