### ISSUE TITLE
[BUG] exception when using .netcoreapp3.0

### ISSUE THREAD

**Issue by glennawatson** [reactiveui/ReactiveUI#2155]
**Describe the bug**

https://github.com/StanleyGoldman/UnderstandReactiveUIProblem

```
System.TypeInitializationException : The type initializer for 'ReactiveUI.RxApp' threw an exceptio
---- System.TypeLoadException : Could not load type 'System.Reactive.Concurrency.DispatcherScheduler' from assembly 'System.Reactive, Version=4.2.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'.
```
I've tried adding `4.2.0-preview.625` explicitly and i'm not getting any luck

**Steps To Reproduce**

Add rxui 10 to netcoreapp3.0 on wpf. 

**Expected behavior**

No exception.

**Comment by glennawatson** [comment]
Issue is caused by the lack of `<UseWpf>true</UseWpf>` in the test .csproj file. This is expected functionality. Closing this issue.

**Comment by StanleyGoldman** [comment]
I didn't realize, thanks for the answer.
I am looking for where that is documented. I don't see it.
