### ISSUE TITLE
Add warning about .net standard project

### ISSUE THREAD

**Issue by glennawatson** [reactiveui/ReactiveUI#2164]
Add warning message if using the .NET Standard platform.

It was previous happening before this version came in this file https://github.com/reactiveui/ReactiveUI/blob/08503a73818157705765a0fa6742718ec4de65dd/src/ReactiveUI/Platforms/netstandard2.0/PlatformRegistrations.cs#L20

We have to be careful so we don't confuse WASM users as well.

**Comment by rgomez90** [comment]
Can give this a try if needed :)

**Comment by glennawatson** [comment]
@rgomez90 -- sure if you like. You can probably add a check in RxApp.cs -- if it's the DefaultScheduler it's likely to be wrong.

**Comment by rgomez90** [comment]
@glennawatson I think taking the descriptions at [https://reactiveui.net/docs/getting-started/installation/#release-packages] (https://reactiveui.net/docs/getting-started/installation/#release-packages) should be the way to go....what do you think?

**Comment by rgomez90** [comment]
@glennawatson with warning message do you mean `#warning` or ` LogHost.Default.Warn("...");`?

**Comment by glennawatson** [comment]
I would maybe even put it in the MainThreadScheduler getter with a bool value you set to avoid it happening excessively.

**Comment by glennawatson** [comment]
and LogHost is the correct approach., #warning would be compile time only.

**Comment by glennawatson** [comment]
so 

```
if (!_hasSchedulerBeenChecked && schedulerType == ...)
{
   _hasSchedulerBeenChecked = true;
```

Thanks for helping out with this one. If you haven't seen it sign up for a free tshirt here https://hacktoberfest.digitalocean.com

**Comment by rgomez90** [comment]
@glennawatson thank you for the quick replies!

Yes, I already signed (like previous years), but this is not the reason I am contributing. 

I wrote some sort of auto-measurement and device management app for my company (we produce transducers) and ported it to use ReactiveUI.

Since them I am in love with it, and helped me a lot to introduce myself in reactive programming....without it I wouldn't have put my nose in there...

That's the reason, I will use A LOT ReactiveUI and also want to give something back, to this really beautiful library 😃

**Comment by rgomez90** [comment]
Something like this would be ok?

```csharp
public static IScheduler MainThreadScheduler
{
    get
    {
        if (_unitTestMainThreadScheduler != null)
        {
            return _unitTestMainThreadScheduler;
        }

        // If Scheduler is DefaultScheduler, user is likely using .NET Standard
        if (!_hasSchedulerBeenChecked && _mainThreadScheduler == Scheduler.Default)
        {
            _hasSchedulerBeenChecked = true;
            LogHost.Default.Warn("ReactiveUi cannot run on .NET Standard! It needs a platform to run! (.Net Core, WPF, UWP...)");
        }

        return _mainThreadScheduler;
    }

    set
    {
        // N.B. The ThreadStatic dance here is for the unit test case -
        // often, each test will override MainThreadScheduler with their
        // own TestScheduler, and if this wasn't ThreadStatic, they would
        // stomp on each other, causing test cases to randomly fail,
        // then pass when you rerun them.
        if (ModeDetector.InUnitTestRunner())
        {
            _unitTestMainThreadScheduler = value;
            _mainThreadScheduler = _mainThreadScheduler ?? value;
        }
        else
        {
            _mainThreadScheduler = value;
        }
    }
}
```

**Comment by glennawatson** [comment]
It can run in .NET Standard 2.0 but in very limited scenarios. 

So web assembly projects such as Uno/Blazor will run the .net standard project in the web browser but those project types should be setting their own main thread scheduler as well so it should never be default.

So I would just say something along the lines of you need to add a nuget host package, such as ReactiveUI.WPF, ReactiveUI.Blazor etc.

We tend to do the `I` as upper case in the `UI`, so `ReactiveUI`.

**Comment by glennawatson** [comment]
So what I mean is in the blazor/uno case, the user should install ReactiveUI.Blazor or ReactiveUI.Uno, which will change the main thread scheduler.

**Comment by rgomez90** [comment]
@glennawatson thank you again for your explanation. I have close to no idea about the new Blazor and Uno. (Blazor is in my To-Do list)

So something like this should be better then

```csharp
...
 if (!_hasSchedulerBeenChecked && _mainThreadScheduler == Scheduler.Default)
    {
        _hasSchedulerBeenChecked = true;
        LogHost.Default.Warn("It seems you are running .NET Standard, but there is no host package installed!\n");
        LogHost.Default.Warn("You will need to install the specific host package for your platform (ReactiveUI.WPF, ReactiveUI.Blazor, ...)\n");
        LogHost.Default.Warn("You can install the needed package via NuGet");
    }
...
```

**Comment by glennawatson** [comment]
Seems good with the message.

Btw the .net standard mode only happens when you use Blazor client mode, they have a server mode that runs asp.net and signalr which is .NET Core 3 based.

**Comment by rgomez90** [comment]
@glennawatson was about to submit the PR, but have readed the [Contribution Guidelines](https://github.com/reactiveui/ReactiveUI/blob/master/CONTRIBUTING.md#submitting-a-pull-request) where is said, I should make a PR to `develop` branch....

But I can't find a `develop` branch, only a `master` & `preview/11.0.0` should I make PR against `master`?

**Comment by glennawatson** [comment]
If you want you can make a pr after this one to mention pr against master.

**Comment by rgomez90** [comment]
Me not understand...

I have forked the project and I created a branch in my fork `fix2164` where I made the changes...

Now I want to make PR and I need to select a base repository and branch. In your [Contribution Guidelines - Submitting a Pull Request](https://github.com/reactiveui/ReactiveUI/blob/master/CONTRIBUTING.md#submitting-a-pull-request) is said **In GitHub, send a pull request to `reactiveui:develop`**, but there is no develop branch...

![image](https://user-images.githubusercontent.com/12009909/66000824-880d8b00-e4a0-11e9-95a8-969c6b0d7c98.png)

So which branch should I select as branch? master?

**Comment by glennawatson** [comment]
I meant you can change the documentation via a PR to say master.

**Comment by rgomez90** [comment]
@glennawatson Oh now I understand, excuse me....it's getting late 😅

**Comment by glennawatson** [comment]
Sorry getting a bit tired here hence the hard to decipher comment

**Comment by glennawatson** [comment]
But the contribution guide is out of date hence it needs to be updated
