### ISSUE TITLE
[BUG] Universal Windows Application fails to build in Release with ReactiveUI

### ISSUE THREAD

**Issue by SuperJMN** [reactiveui/ReactiveUI#2166]
Universal Windows Application fails to build in Release with ReactiveUI

**Steps To Reproduce**
1. Create a blank Universal Windows Application.
1. Add the ReactiveUI package (latest version 10.1.6)
1. Change the configuration to Release
1. Change the platform to x86 or x64.
1. Build the application.
1. You should get an error like this:

> error : ILT0005: 'C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\runtime.win10-x86.microsoft.net.native.compiler\2.2.7-rel-27913-00\tools\x86\ilc\Tools\nutc_driver.exe @"C:\Users\JMN\source\repos\App6\App6\obj\x86\Release\ilc\intermediate\MDIL\App6.rsp"' returned exit code 1

**Expected behavior**
Build successful

**Environment**
- OS: Windows 10 x64 
- Version   18362.356
- Device:   Windows Desktop

**Additional context**
Targeting:
Target version: Windows version 1903
Min. version 1809

**Comment by glennawatson** [comment]
Updated to UWP 6.2.9 as part of #2167 -- this should solve your issue if not respond back to this issue.

**Comment by SuperJMN** [comment]
Sadly, the issue is still there :( I'm attaching a solution with the issue.

[App6.zip](https://github.com/reactiveui/ReactiveUI/files/3625081/App6.zip)

I've seen the Task Manager during the build process and from some point, it starts to consume a lot of memory. That can be related to the issue, as stated by @MattWhilden here https://twitter.com/SuperJMN/status/1172949559267475456?s=20

**Comment by SuperJMN** [comment]
# Workaround
## Cause
It seems the problem is that the compiler used during the build process is a 32-bit process + it uses a huge amount of RAM to do its job. 

## Fix
The 64-bit version of the compiler doesn't fail. We can force to use it instead the 32-bit compiler using this XML element inside the .csproj file of the affected project:

`<Use64Bitcompiler>true</Use64Bitcompiler>`

It should be added to the **first PropertyGroup** element of the file.
