### ISSUE TITLE
Different NuGet info for each package

### ISSUE THREAD

**Issue by TonyGravagno** [reactiveui/ReactiveUI#2182]
The description for all ReactiveUI packages in NuGet is the same. It's difficult to look at the packages and work out which ones to use for a project. I believe this makes the onboarding experience more difficult for the newcomer, myself included.

> A MVVM framework that integrates with the Reactive Extensions for .NET to create elegant, testable User Interfaces that run on any mobile or desktop platform. Supports Xamarin.iOS, Xamarin.Android, Xamarin.Mac, Xamarin Forms, Xamarin.TVOS, Tizen, WPF, Windows Forms, Universal Windows Platform (UWP) and the Uno Platform.

The [general information](https://reactiveui.net/docs/getting-started/installation/) for installation on the website is very helpful, as are individual pages like [this one](https://reactiveui.net/docs/getting-started/installation/xamarin-forms).

I'm requesting and recommending that the NuGet descriptions should have individual descriptions which are more in line with the project-specific info, including recommendations for the project type which they support and the other packages recommended for that project type.

Further, the tags for packages don't accurately describe them. Consider for ReactiveUI.WPF the tags include several related to xamarin and ios.

Finally, the project URL for all packages goe to reactiveui.net, and while accurate, that doesn't provide information about the package and its specific usage.

I'm guessing the content for the NuGet packages was created early-on and that this is all just a suggestion for taking the next step beyond that initial and successful effort.

Examples: Here are two identical descriptions for two different packages:
![image](https://user-images.githubusercontent.com/499473/65838696-ad40a480-e2ba-11e9-9270-9df23d0de78a.png)

![image](https://user-images.githubusercontent.com/499473/65838718-f5f85d80-e2ba-11e9-8fc1-e6fc7e6ac8f8.png)

**Comment by glennawatson** [comment]
Hey @TonyGravagno while the core maintainers won't be able to address this one immediately it's a new contributor friendly task. Essentially in the .csproj for each projects you would customise the metadata. 

At the moment it picks it up from the Directory.build.props file if not overridden in the project files.

**Comment by rgomez90** [comment]
@glennawatson I could give this a try, if still needed.

If so, should I pull the descriptions from somewhere or should I define them by myself?

**Comment by rgomez90** [comment]
@glennawatson I think using the descriptions at [https://reactiveui.net/docs/getting-started/installation/#release-packages](https://reactiveui.net/docs/getting-started/installation/#release-packages) should be the way to go....

What do you think?

**Comment by glennawatson** [comment]
Seems reasonable.

**Comment by rgomez90** [comment]
### Description suggestions

I just copy/paste most of them from [Releases page](https://reactiveui.net/docs/getting-started/installation/#release-packages).

I am not sure how to describe the last three packages...

I am also not sure if there are more packages, which are not listed here...

|          Package           | Description                                                  |
| :------------------------: | ------------------------------------------------------------ |
|         ReactiveUI         | Base package with the base platform implementations. You need it in every project you want to use ReactiveUI |
|     ReactiveUI.Events      | Base base package for ReactiveUI Events as Observables API   |
|    ReactiveUI.WinForms     | Contains the ReactiveUI platform specific extensions for Windows Forms |
| ReactiveUI.Events.WinForms | Provides Observable-based events API for Win Forms UI controls & event handlers |
|       ReactiveUI.WPF       | Contains the ReactiveUI platform specific extensions for Windows Presentation Foundation (WPF) |
|   ReactiveUI.Events.WPF    | Provides Observable-based events API for WPF UI controls & event handlers |
|    ReactiveUI.XamForms     | Contains the ReactiveUI platform specific extensions for Xamarin Forms |
| ReactiveUI.Events.XamForms | Provides Observable-based events API for Xamarin Forms UI controls & event handlers |
|      ReactiveUI.Fody       | Fody extension that will generate RaisePropertyChange notifications for properties and ObservableAsPropertyHelper properties |
|       ReactiveUI.Uno       | Contains the ReactiveUI platform specific extensions for Uno |
|     ReactiveUI.Blazor      | Contains the ReactiveUI platform specific extensions for Blazor |
|    Avalonia.ReactiveUI     | Contains the ReactiveUI platform specific extensions for Avalonia |
|   ReactiveUI.Validation    | Contains validation helpers for ReactiveUI-based solutions, functioning in a reactive way |
|     ReactiveUI.Testing     | Provides extensions for testing ReactiveUI based applications |
| ReactiveUI.AndroidSupport  | Provides additional extensions needed for Xamarin.Android    |
|      ReactiveUI.Blend      | (Provides Blend support ??)                                  |
|  ReactiveUI.XamEssentials  | (Contains extensions to use Xamarin Essentials in ReactiveUI solutions ??) |
|    ReactiveUI.AndroidX     | (Contains the ReactiveUI platform specific extensions for AndroidX ??) |

**Comment by rgomez90** [comment]
If you also want to change tags, I suggest to add all currently tags to the core packages like `ReactiveUI` and packages which can be used in all platforms like `ReactiveUI.Events`.

Then use the same list for specific platform package and deleting all tags from the list, which are not related to the given platform.

**Comment by dpvreony** [comment]
prepped a precompile validating step to check these get changed in projects (and any future projects to prevent it being missed). help yourself to the logic (keep in mind it currently breaks the build) leave you to play with the descriptions :)

**Comment by glennawatson** [comment]
@dpvreony I would modify that slightly so it doesn't produce an error in test projects otherwise looks good.

**Comment by glennawatson** [comment]
eg add inside the PropertyGroup of Directory.Build.Targets `<IsTestProject>$(MSBuildProjectName.Contains('Tests'))</IsTestProject>` and then check that in the Conditions of the Target.

**Comment by glennawatson** [comment]
So,

AndroidSupport and AndroidX are both libraries you tend to use when doing Android Native development, AndroidSupport is older and Google recently replaced it with AndroidX which Xamarin is starting to support now.

They basically offer a bunch of additional controls related to when you're doing native Android development and are wrappers around those particularly named Android libraries.

**Comment by glennawatson** [comment]
Blend is a tool that originally came out when WPF/Silverlight first came out, it was meant to be designers tool while programmers would use visual studio.

They had a sdk called "Blend SDK" that would allow you to do extra things inside XAML.

We offer reactive extensions based xaml components based on the Blend SDK library, eg, it allows you to fire a observable from XAML.

**Comment by glennawatson** [comment]
Xam Essentials adds non-UI related functionality to Xamarin, such as storage, gps, bunch of other stuff.

The ReactiveUI.Events.XamEssentials portion is our wrapper around the events, which allow you to use Observables instead of events.

**Comment by glennawatson** [comment]
ReactiveUI.Events -- that package we tend to have packages for any platform that has it's own independent TargetFramework, eg WPF/XamForms/WinForms do not, you don't add those to the 

`<TargetFrameworks>WinForms</TargetFrameworks>` for example. but MonoAndroid90 you do.

**Comment by rgomez90** [comment]
@glennawatson thank you again...

I updated the table with Blend, AndroidX and XamEssentials.
Please let me know if OK or changes needed.

Regarding `ReactiveUI.Events`, I understand what you said, I'll need some help there to get a decent description....

**Comment by glennawatson** [comment]
With ReactiveUI.Events you could just list the platforms I guess.

Provides Observable-based events API for Xamarin Native Platforms including Android, iOS, Mac, TVOS, Tizen, and UWP.

**Comment by glennawatson** [comment]
In terms of tags I would say go based off the ones in the `Directory.Build.Props` file at the moment and just subtract to have it make sense for your csproj.

**Comment by worldbeater** [comment]
Probably for the `ReactiveUI` base package I'd use:
> A MVVM framework that integrates with the Reactive Extensions for .NET to create elegant, testable User Interfaces that run on any mobile or desktop platform. This is the base package with the base platform implementations. You need it in every project you want to use ReactiveUI.

All other descriptions look good :+1:

**Comment by glennawatson** [comment]
One missing NuGet package is https://www.nuget.org/packages/ReactiveUI.Testing/

**Comment by glennawatson** [comment]
A MVVM framework that integrates with the Reactive Extensions for .NET to create elegant, testable User Interfaces that run on any mobile or desktop platform. This is the base package with the base platform implementations.

I would keep it at that, since NuGet packages will automatically include ReactiveUI.

**Comment by rgomez90** [comment]
This can be closed as it was fixed by #2190

**Comment by glennawatson** [comment]
Thanks closing
