### ISSUE TITLE
[BUG] RaisePropertyChanged does not allow null

### ISSUE THREAD

**Issue by jalbertSyncroTech** [reactiveui/ReactiveUI#2184]
**Describe the bug**

According to Microsoft, the `PropertyChanged` event of the `INotifyPropertyChanged` interface supports both `null` and `string.Empty`:
"The PropertyChanged event can indicate all properties on the object have changed by using either null or String.Empty as the property name in the PropertyChangedEventArgs."
https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.inotifypropertychanged.propertychanged?view=netframework-4.8#remarks

However, ReactiveUI prevents calling `RaisePropertyChanged(null)` via contract and will fail with an exception.
https://github.com/reactiveui/ReactiveUI/blob/89c4621c065eb2eabe2823cf809f1119bfc93160/src/ReactiveUI/ReactiveObject/IReactiveObjectExtensions.cs#L188

**Comment by glennawatson** [comment]
This is deliberate, these are internal helper methods that call into a method (which does not have that contract) on the actual object.

**Comment by glennawatson** [comment]
https://github.com/reactiveui/ReactiveUI/blob/89c4621c065eb2eabe2823cf809f1119bfc93160/src/ReactiveUI/ReactiveObject/ReactiveObject.cs#L74

We use explicit implementation since doing null/empty string tends to be a performance hit on most platforms.

**Comment by glennawatson** [comment]
Also there is a method on a IReactiveObject called `SuppressChangeNotifications()`, this is for the use case where you are about to update a bunch of properties and only want to fire a single `INotifyPropertyChanged` at the end.

So when you dispose of `SuppressChangeNotifications()` it will trigger the singular `INotifyPropertyChanged`.

Going to close this one but feel free to give some feedback if you feel it should be re-opened.

**Comment by jalbertSyncroTech** [comment]
@glennawatson I'd tend to agree with your assessment, only feedback is that when we recently updated from ReactiveUI  9.13.1 to 9.22.1 the few calls we had to RaisePropertyChanged(null) started throwing exceptions where previously they were updating the object per the Microsoft description.

I've already let our team know about the preferred alternatives, and in the meantime we're replacing RaisePropertyChanged(null) with RaisePropertyChanged(string.Empty). As long as the latter remains a viable alternative there's no need to reopen this.

**Comment by glennawatson** [comment]
Makes sense, we turned on analyzers around that time which detected when there was public interfacing relying on a non-null interface.

I don't see this arrangement changing for some time. We will at some point in the near future add C# 8 nullability contexts to the project but if you are running pre-C# 8 it's just attributes added to the methods/properties etc. If you ever used the jetbrains resharper nullable interfaces it's very similar to that.

The changes you've made would make you avoid those issues though.
