### ISSUE TITLE
[BUG] WhenAnyValue doesn't observe changes to DependencyProperty and/or docs need to be clarified

### ISSUE THREAD

**Issue by mattico** [reactiveui/ReactiveUI#2203]
**Describe the bug**

I'm trying to use `this.WhenAnyValue` to observe changes to a `DependencyProperty` of a `UserControl`. However, it does not actually subscribe to changes, only updating when the control is activated. I'm not sure if this is intended behavior and the docs should be improved, or if this is a bug.

**Steps To Reproduce**

```csharp
public partial class IncDecTextBox : UserControl, IActivatableView
{
    static readonly DependencyProperty _value = DependencyProperty.Register(
            nameof(Value), typeof(double), typeof(IncDecTextBox), new PropertyMetadata(0.0));
 
    public double Value
    {
        get => (double)GetValue(_value);
        set => SetValue(_value, value); 
    }
    
    public IncDecTextBox()
    {
        InitializeComponent();
        this.WhenActivated(disposable =>
        {
            this.WhenAnyValue(v => v.Value)
                    .Subscribe(x => Console.WriteLine(x))
                    .DisposeWith(disposable);
        });
    }
}
```

Change Value via bound TextBox, etc.

**Expected behavior**

Expect value to be printed on every change, instead it is only printed on view activation.
This is printed in the console:
>POCOObservableForProperty: The class WinLaserlux7.WPF.Controls.IncDecTextBox property Value is a POCO type and won't send change notifications, WhenAny will only return a single value!

**Environment**

Windows 10 x64
.NET Framework 4.7.2
ReactiveUI 10.4.1
ReactiveUI.WPF 10.4.1

**Additional context**

I think this might be the expected behavior. The WhenAny docs mention:

>INotifyPropertyChanged is required
>
>Watched properties must implement ReactiveUI's RaiseAndSetIfChanged or raise the standard INotifyPropertyChanged events. If you attempt to use WhenAny on a property without either of these in place, WhenAny will produce the current value of the property upon subscription, and nothing thereafter. Additionally, a warning will be issued at run time (ensure you have registered a service for ILogger to see this).

However, earlier on the page it says:

>WhenAny supports multiple property types including INotifyPropertyChanged, DependencyProperty and BindableProperty.
>
>It will check the property for support for each of those property types, and when you Subscribe() it will subscribe to the events offered by the applicable property notification mechanism.

My reading of that makes me think that DependencyProperties should support change notifications. Also `DependencyObjectObservableForProperty` seems like it should work for this situation.

So I think that either:

1. DependencyProperties aren't expected to produce change notifications. In this case I think the docs for "What Is WhenAny" should be changed to clarify that change notifications only work for INPC.

2. DependencyProperties should produce change notifications, but a bug in my code or ReactiveUI is preventing the `DependencyObjectObservableForProperty` from working and it's falling back to `POCOObservableForProperty`. If this is true the docs should be updated so that it doesn't make INPC seem mandatory.

**Comment by glennawatson** [comment]
It's due to the naming scheme and visibility of your dependency property. A lot of components are very fussy about the naming scheme of those and they have to be public as well.

Eg it should be : 

```cs
public static readonly DependencyProperty ValueProperty = DependencyProperty.Register(
            nameof(Value), typeof(double), typeof(IncDecTextBox), new PropertyMetadata(0.0));
```

Having a non-public dependency property and not following the microsoft naming scheme is likely to break more than just ReactiveUI.

As mentioned in the documentation https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/how-to-implement-a-dependency-property#example

It says:

> The name of the identifier field that you use to store the name and characteristics of the dependency property must be the Name you chose for the dependency property as part of the Register call, appended by the literal string Property.

**Comment by mattico** [comment]
Thank you!
