### ISSUE TITLE
Make Fody ToPropertyEx work against IReactiveObject

### ISSUE THREAD

**Issue by MartinZikmund** [reactiveui/ReactiveUI#2248]
**Is your feature request related to a problem? Please describe.**

I would like to use `ToPropertyEx` against an instance of `IReactiveObject`, but it unfortunately requires a `ReactiveObject`

**Describe the solution you'd like**

Change the generic constraint on `ToPropertyEx` to `class, IReactiveObject` to match `ToProperty` method.

**Describe alternatives you've considered**

Implementing the method manually, but that is less convenient that having this out of the box.

**Describe suggestions on how to achieve the feature**

Change the generic constraint on `ToPropertyEx` to `class, IReactiveObject` to match `ToProperty` method. Unfortunately this causes failure of API approval test. The change makes the constraint more permissive, but it is still a breaking change.

**Comment by MartinZikmund** [comment]
If we agree on a way to resolve this, I would love to contribute the change

**Comment by cabauman** [comment]
@glennawatson shall we consider this request at the same time as changing the ToPropertyEx name?

**Comment by glennawatson** [comment]
Yeah. I have this happening in my testing version.

**Comment by jcummings2** [comment]
Any update on this capability?

**Comment by glennawatson** [comment]
Next major release is the plan for this one. There is a major rewrite for the Fody coming up that will support these features.

**Comment by glennawatson** [comment]
The fody is going into maintenance-only mode at the moment while we work on a new project which will replace the functionality in general. Keeping this open to track for the new project.

**Comment by jcummings2** [comment]
By maintenance-only mode, I presume that's in reference to [everyone-should-be-a-fody-patron](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md).

Where is the new project and how can we contribute?

**Comment by ljnober** [comment]
I made some changes based on 19.5.41 to support this feature, but I'm not sure how to create pull requests
[https://github.com/reactiveui/ReactiveUI/compare/main...ljnober:ReactiveUI:nober-fody-support-IRectiveObject](url)

**Comment by glennawatson** [comment]
We are moving Fody out to its own repo soon. You can push the pr against that. Long term plan is to retire the project.

**Comment by ljnober** [comment]
Is this repo?
https://github.com/kswoll/ReactiveUI.Fody

**Comment by glennawatson** [comment]
No, on the weekend I'll do the work and deploy it to the rxui organisation as a separate repo. Similar to what we did with Uno.

Fody is not dependent on any particular RxUI version so doesn't need to be released with every rxui version.

**Comment by ljnober** [comment]
> 不，在周末，我将完成这项工作并将其作为单独的存储库部署到 rxui 组织。类似于我们对 Uno 所做的。
> 
> Fody 不依赖于任何特定的 RxUI 版本，因此不需要随每个 rxui 版本一起发布。

I found that Fody has been removed in version 19.5.72, but I can't find the ReactiveUI.Fody repository. How should I contribute to ReactiveUI.Fody

**Comment by ChrisPulman** [comment]
You can still use the last release of ReactiveUI.Fody, a new Source Generator version is being made that will replace Fody. Until then ReactiveUI.Fody can be used.

**Comment by ChrisPulman** [comment]
The original ReactiveUI.Fody will be placed in a separate Repository for security updates.

**Comment by ChrisPulman** [comment]
V1.1.26 of ReactiveUI.SourceGenerators has been released, please migrate where possible. IReactiveObject should be supported with this package.
