### ISSUE TITLE
[BUG] Any exception throw from setter fails to be thrown. 

### ISSUE THREAD

**Issue by iashaik** [reactiveui/ReactiveUI#2252]
**Describe the bug**
When ReactiveAttribute is used on a property to stops throwing any Setter Exceptions. 

**Steps To Reproduce**
` private GenderType? _gender;
[Reactive]
public GenderType? Gender
{
    get => _gender;
   set => _gender = value ?? throw new NotSupportedException(nameof(Gender));
}
`

**Expected behavior**
Should not eat up an exception, A simple that tests for the exception thrown should pass.   

` Assert.ThrowsException<NotSupportedException>(() => model.Gender = null);`

**Comment by glennawatson** [comment]
This isn't a bug, since the `[Reactive]` flag indicates to the Fody to replace the auto-property with the ReactiveObject's `RaiseAndSetIfChanged` extension method. So your code there will be wiped. If you want to have special functionality you will have to remove the `[Reactive]` flag.
