### ISSUE TITLE
[BUG] XAML-Designer-Exception

### ISSUE THREAD

**Issue by rgomez90** [reactiveui/ReactiveUI#2256]
**Describe the bug**

After upgrading to 10.5.31 I get `ArgumentException: Don't know how to detect when Mocks.{name of view} is activated/deactivated, you may need to implement IActivationForViewFetcher` in all my views in the designer. 

**Steps To Reproduce**

I created a [sample repo](https://github.com/rgomez90/BugTestReactiveUI-XAML-Designer) that reproduces the issue.

If you build the project & try to use the XAML-Designer with `TestUserControl.xaml` the designer will throw an exception like the one below under "screenshots".

**Expected behavior**
XAML-Designer should not throw an exception

**Screenshots**

![image](https://user-images.githubusercontent.com/12009909/69384553-ea268780-0cbc-11ea-9253-a7e73f991802.png)

**Environment**

- OS: Windows 10 Pro      

**Additional context**

**Comment by rgomez90** [comment]
After a few tests, it appears that this only happens with `UserControl`. 

I think the issue appears if you have a base class for your `UserControls` and you call `this.WhenActivated(....)` in its constructor.

So in order to reproduce the issue, just create a `UserControlBase<TViewModel>` implementing `IViewFor<TViewModel>` or inheriting `ReactiveUserControl<TViewModel>` and call `this.WhenActivated(...)` in its constructor.

Create a `FooUserControl : UserControlBase<FooViewModel>` & rebuild. 

You should see the exception in the XAML designer.

**Comment by glennawatson** [comment]
This will be fixed by #2272
