### ISSUE TITLE
[BUG] WPF - ViewModelViewHost creates the old view again when switching to a new view model

### ISSUE THREAD

**Issue by TolikPylypchuk** [reactiveui/ReactiveUI#2258]
**Describe the bug**
When a view model is changed for a `ViewModelViewHost`, it creates the old view again and only after that creates a new view, which can cause brief flickering of views. This happens in a WPF app on .NET Core 3.0 (not sure about other frameworks). ReactiveUI version is 10.5.31.

**Steps To Reproduce**
I've created a simple [repo](https://github.com/TolikPylypchuk/BugReactiveUIViewModelViewHost) to reproduce the issue.

The view flickering is not actually visible there, but if you debug the app in Visual Studio, you'll see the log output. When switching the view from View1 to View2, the following log can be seen:

```
MainViewModel: Switching the view.
View1: Creating the view 1
View2: Creating the view 2
```

**Expected behavior**
The old view is not created again when switching to a new view.

**Environment**
- OS: Windows 10 Home 1909

**Additional context**

The source of error is probably [in the constructor](https://github.com/reactiveui/ReactiveUI/blob/master/src/ReactiveUI/Platforms/windows-common/ViewModelViewHost.cs#L109) of the `ViewModelViewHost` class:

```
var contractChanged = _updateViewModel.Select(_ => ViewContractObservable).Switch();
var viewModelChanged = _updateViewModel.Select(_ => ViewModel);

var vmAndContract = contractChanged.CombineLatest(viewModelChanged, (contract, vm) => new { ViewModel = vm, Contract = contract });

vmAndContract.Subscribe(x => ResolveViewForViewModel(x.ViewModel, x.Contract));
```

I've debugged this code, and `x => ResolveViewForViewModel(x.ViewModel, x.Contract)` is hit twice  when switching the view model - first time with the old view model (hence creating the old view) and the second time with the new view model. I think this is becuase when a view model is changed, the `contractChanged` is fired, and then the `viewModelChanged` is fired, which is why `vmAndContract` is fired twice.

**Comment by Brimce** [comment]
Hi,
This bug can also be observed on the RoutedViewHost.
I have found it comes from the TransitioningContentControl which inherits ContentControl.

Navigation with RoutedViewHost or change of ViewModelViewHost.ViewModel has two consequences :
1. Change of Content property inherited from the ContentControl. (**Dispose the old view**)
2. Start of transition animation. (**Creates the old view again**)

To fix this i've first tried to inherits from Control and create my own Content property. 
But i faced multiple viewModel activation issue with the slide left transition.

I've then created a TransitioningContentControl that add a new ContentPresenter to the container children on each Content change. And remove the old ContentPresenter when transition is ended. The storyboard to animate the transition is created on the fly.

You can find my code [here](https://github.com/Brimce/ReactiveUI.TransitioningContentControl)
WpfTestApp illustrate 
1. Original **TransitioningContentControl** (navigation between OrginalView and OrginalViewBis) 
2. First attempt **TransitioningContentControl1** (navigation between FirstView and FirstViewBis)
3. Final **TransitioningContentControl2** (navigation between SecondView and SecondViewBis)

You can manage console log in [App.cs](https://github.com/Brimce/ReactiveUI.TransitioningContentControl/blob/master/WpfTestApp/App.xaml.cs)

I will be happy to have feedback on my code

**Comment by HrlecMatej** [comment]
I believe a simple solution is changing contractChanged.CombineLatest to contractChanged.Zip
The difference is, CombineLatest fires every time any of the two observables returns a new value. While Zip waits until both return a new value.
This fixes getting the old ViewModel again in the combined observable.
