### ISSUE TITLE
[BUG] Assembly references do not match in 10.5.43

### ISSUE THREAD

**Issue by velocitysystems** [reactiveui/ReactiveUI#2273]
**Describe the bug**
`ReactiveUI` 10.5.43 bumps `System.Reactive `to 4.3.1.
However, `DynamicData` takes a dependency on `System.Reactive` 4.2.

This leads the following error when compiling our app on iOS:

`error CS1701: Assuming assembly reference 'System.Reactive, Version=4.2.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263' used by 'DynamicData' matches identity 'System.Reactive, Version=4.3.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263' of 'System.Reactive', you may need to supply runtime policy`

**Steps To Reproduce**
1. Create a blank Xamarin.iOS app.
2. Install ReactiveUI 10.5.43 package.
3. Build.

**Expected behavior**
The error should not be thrown. Also, the dependency versions for System.Reactive should not be mismatched.

**Environment**
- OS:       iOS
- Version   vLatest

**Comment by velocitysystems** [comment]
Ideally, the dependency on` System.Reactive` should be downgraded to 4.2 until all other dependencies have been upgraded.

**Comment by velocitysystems** [comment]
Ideally, System.Reactive should be downgraded to 4.2 until DynamicData has been upgraded to use 4.3.1.

**Comment by glennawatson** [comment]
Just explicitly include 4.3.1 of system.reactive for the moment. Closing this issue since it's not really a rxui bug.
