### ISSUE TITLE
[BUG] RxApp.MainThreadScheduler resolves to the incorrect scheduler when compiled using Android < 9

### ISSUE THREAD

**Issue by winterdouglas** [reactiveui/ReactiveUI#2277]
**Describe the bug**
When using ReactiveUI >= 10.1.1 and compiling using Android < 9 it resolves the wrong `RxApp.MainThreadScheduler`, it resolves to a `DefaultScheduler` instead.

I noticed this behavior while doing some changes on Sextant, and since the sample there was targeting/compiling using Android 8.1 that was happening. The same doesn't happen if I compile using Android 9, it also works if I use ReactiveUI < 10.1.1. 

The whole investigation/details are described on this issue:
reactiveui/Sextant/issues/171

**Steps To Reproduce**
1. On a Droid project compiled with the framework < 9 and RxUI >= 10.1.1
2. Do anything set to run on the `RxApp.MainThreadScheduler`
3. The app crashes

**Expected behavior**
The code set to run on the main thread scheduler should run on the main thread.

**Screenshots**
See the linked issue

**Environment**
- OS:          Android
- Version   9
- Device:   Huawei P20, Emulator
---
- ReactiveUI: >= 10.1.1
- Targeting: Android 8.1
- Xamarin.Forms: 4.2 (tried 4.3 too)

**Comment by winterdouglas** [comment]
I plan to have a look into this issue myself tomorrow.

**Comment by glennawatson** [comment]
This is pretty simple, we don't support Android < 9 since Google don't allow Android < 9.

**Comment by glennawatson** [comment]
See https://developer.android.com/distribute/best-practices/develop/target-sdk

> When you upload an APK, it needs to meet Google Play’s target API level requirements. Both new apps and app updates must target at least Android 9 (API level 28).

**Comment by glennawatson** [comment]
I've updated the minimum version docs on the website now.

**Comment by winterdouglas** [comment]
I was about to comment exactly this, because on the docs it said Android 8.1 was supported.

**Comment by winterdouglas** [comment]
In the beginning I imagined that the minimum target possibly should be Android 9, but then I found on the docs about the 8.1 and thought this was a problem, still my concern when opening this one was that publishing to the Google Play Store is not the only way of publishing Android apps, so it may go unnoticed if someone still uses Android 8.1, for example. 

Anyway, thanks for updating the docs @glennawatson!
