### ISSUE TITLE
Fix ReactiveUI.Tests.Winforms CommandBindingTests

### ISSUE THREAD

**Issue by RLittlesII** [reactiveui/ReactiveUI#2279]
**Describe the bug**

Recently CommandBindingTests in ReactiveUI.Tests.Winforms seem to fail randomly.  When all tests are executed it tests won't pass.  When the failing test is executed in isolation it passes.

**Steps To Reproduce**

**Expected behavior**

My expected behavior is that the CI server can execute these tests without issue.

**Screenshots**

**Environment**

Local Development Machine
**Additional context**

**Comment by cabauman** [comment]
The tests have been passing since the #2496 was merged, so I'll close this now.
