### ISSUE TITLE
[BUG] AutoSuspendHelper crash on UWP

### ISSUE THREAD

**Issue by TheKeyblader** [reactiveui/ReactiveUI#2282]
**Describe the bug**

Using AutoSuspendHelper on UWP  do app crash
**Steps To Reproduce**

1. Create an empty uwp projet
2. Add ReactiveUI
3. Create an AutoSuspendHelper in App constructor

**Expected behavior**

App start

**Screenshots**

![image](https://user-images.githubusercontent.com/30444673/70917276-50cd6580-201d-11ea-800b-397ae5f47c6f.png)

**Environment**

- OS:       Windows
- Version   11.0.1
- Device:   Windows

**Additional context**

This exception is strange because we dont see method name on exception message but when i check the code, methodname can't be null

**Comment by Qonstrukt** [comment]
I have this same problem on iOS as well.

Environment

OS: iOS 13.3
Version 11.0.1
Device: macOS Catalina 10.15.2

Additional context

I've noticed the same as @TheKeyblader in the code in which the Item should never be `null` in the first place. Could this have something to do with `.FirstOrDefault()` returning an empty string now if it finds nothing since it's a non-nullable string since C# 8? Or am I fishing too much?

**Comment by glennawatson** [comment]
We haven't turned on nullability yet. Was on my todo list.

**Comment by TheKeyblader** [comment]
I can make a pull request, if you want ?

**Comment by glennawatson** [comment]
Hey @TheKeyblader what were you planning on putting in the pull request?

**Comment by TheKeyblader** [comment]
After re-check, the method Reflection.ThrowIfMethodsNotOverloaded will always throw an exception. because if we dont have missing methods, missingMethod default value is (null,null).
so i will just make a pull request to correct the method.

if is more fast for you, here the code:
```csharp
        public static void ThrowIfMethodsNotOverloaded(string callingTypeName, object targetObject, params string[] methodsToCheck)
        {
            var missingMethod = methodsToCheck
                .Select(x =>
                {
                    IEnumerable<MethodInfo> methods = targetObject.GetType().GetTypeInfo().DeclaredMethods;
                    return (methodName: x, methodImplementation: methods.FirstOrDefault(y => y.Name == x));
                })
                .FirstOrDefault(x => x.methodImplementation == null);

            if (missingMethod.methodName != default)
            {
                throw new Exception($"Your class must implement {missingMethod.methodName} and call {callingTypeName}.{missingMethod.methodName}");
            }
        }
```

**Comment by glennawatson** [comment]
Ok appreciate the PR.
