### ISSUE TITLE
[BUG] Router.NavigateBack seems to be broken in some cases

### ISSUE THREAD

**Issue by andrejpanjan** [reactiveui/ReactiveUI#2286]
**Describe the bug**
It look likes that Router.NavigateBack doesn't work as expected in some cases on Xamarin Forms, while the same code works perfectly on WPF.

**Steps To Reproduce**

Use attached Test. 
[Test.zip](https://github.com/reactiveui/ReactiveUI/files/3992956/Test.zip)

1. Tap Check Out on the Main Page.
2. Tap Save on the CheckOut page.
3. Tap Save on the Production page.
4. It should return to Main Page, but it doesn't. Also Router.NavigationStack and NavigationPage.Navigation.NavigationStack are not synchronized anymore.

**Expected behavior**
It should return to the Main Page when Save is tapped on the Production page.

**Environment**

- OS:       Android,  Xamarin Forms
- Version: 10
- Device:   Pixel 2

**Additional context**
May be related to #2040

**Comment by glennawatson** [comment]
I'll take a look at this one in the new year.

**Comment by andrejpanjan** [comment]
Is this planned to be fixed soon? Otherwise, I will start looking for a workaround.

**Comment by RLittlesII** [comment]
@andrejpanjan We have been working on clearing bugs recently.  I was able to reproduce #2040, I can push this further up my queue, can't commit to a "soon" timeline for resolution.

**Comment by glennawatson** [comment]
This issue is the one we are looking into now btw.

**Comment by RLittlesII** [comment]
@andrejpanjan I was looking at this last night.  This is what I see.

- The `RoutedViewHost` for XF seems to be popping to root on the first `NavigateBack` (Step 2)
- The second `NavigateBack` never reaches the call to the `INavigation` (Step 3)
     - This results in the `NavigationStack` getting out of sink
     - I watch the `NavigateBack` execute, but it seems the `NavigationChanged` observable doesn't tick

**Comment by RLittlesII** [comment]
@andrejpanjan Yes.  I saw that.  I am using your sample to debug the problem. Digging into the framework I am looking at when the actual `NavigationPage` fires `NavigationEventArgs` for the `Popped` event handler.

XF actually makes a distinction (although not clear) between `Popped` and `PoppedToRoot`.  The code you have written never seems to hit the `PopAsync` on the `RoutedViewHost`.  That said, I don't believe it's your code that's causing this behavior.

We also make a distinction listening for the `Popped` based on whether it is a custom command  or the software back button.  I am still digging.  Just wanted to give you an update an corroborate.

**Comment by glennawatson** [comment]
It seems @RLittlesII may have to refactor two classes to take the view model pushes from the xam forms events.

**Comment by RLittlesII** [comment]
@glennawatson I think that is the cleanest way.  I am still investigating a less invasive approach.  It just doesn't seem to make sense that the second tick of `Router.NavigationChanged` doesn't effect a corresponding `PopAsync`.

@andrejpanjan After rereading your points, and looking at this again.
The POP isn't called because it isn't firing the `INavigation.PopAsync`.  It is firing `INavigation.PopToRootAsync`.  This emits a different event, so the `RoutedViewHost` doesn't see the `NavigationEventArgs` for the `Popped` event handler to call the `PopAsync`.

`PopAsync` only seems to respect the software back button (the button provided by the navigation page).

**Comment by glennawatson** [comment]
@RLittlesII Let's just bite the bullet and go for it.

Let's do a mini RPC in this issue of the changes.

**Comment by andrejpanjan** [comment]
Any plans to have it fixed until Monday? I'm asking because I'm going to release my app on Monday and don't want put any effort into workaround if it will be fixed.

**Comment by RLittlesII** [comment]
@andrejpanjan Probably not by Monday.  I would want to do some extensive testing to make sure if we rewrite this everything will be correct.  I will get with @glennawatson to make sure my approach is good and I'll get back with your as soon as I have something functional.

**Comment by RLittlesII** [comment]
@andrejpanjan Well.  Good news.  I think I resolved your issue.

![ReactiveUI 2286](https://user-images.githubusercontent.com/6969701/72580892-1288c780-38a3-11ea-88cf-d06929e72e99.gif)

**Comment by andrejpanjan** [comment]
@RLittlesII That's great. Thank you.

**Comment by garyng** [comment]
The fix https://github.com/reactiveui/ReactiveUI/pull/2315 broke all of my existing `NavigateBack` though...

**Comment by glennawatson** [comment]
Mind providing a small sample @garyng so it makes it easier for @RLittlesII  to track down the issue. Thanks.

**Comment by garyng** [comment]
I am trying to reproduce. Would report back if I managed to do it.

**Comment by garyng** [comment]
Using the same sample provided by @andrejpanjan:

Change 
```cs
var completedInternally = Observable.Amb(
    Confirm.Select(_ => _),
    Cancel.Select(_ => _),
    Delete.Select(_ => _));

completedInternally.Subscribe(_ =>
{
    if (HostScreen.Router.NavigationStack.LastOrDefault() == this)
    {
        HostScreen.Router.NavigateBack.Execute().Subscribe(); // Return to the calling ViewModel when completed.

        if (NextViewModel != null)
            HostScreen.Router.Navigate.Execute(NextViewModel).Subscribe();
    }
});
```
inside `ItemViewModel` to 
```cs
var completedInternally = Observable.Amb(
        Confirm.Select(_ => _),
        Cancel.Select(_ => _),
        Delete.Select(_ => _))
    .Where(_ => HostScreen.Router.NavigationStack.LastOrDefault() == this)
    .SelectMany(_ => HostScreen.Router.NavigateBack.Execute());

completedInternally.Subscribe(_ =>
{
    if (NextViewModel != null)
        HostScreen.Router.Navigate.Execute(NextViewModel).Subscribe();
});
```

will break `NavigateBack`.

Is this a bug, or just I am stupidly using ReactiveUI wrongly?

---

I also get the same output as:

> I've put a couple of debug outputs in the attached Test.zip to track both `NavigationStack`-s. You can find them in the `AppBootstrapper.cs`. ADD and REMOVE lines are related to the `Router.NavigationStack` and PUSH and POP lines are related to the `Navigation.NavigationStack`. COUNT is a current `NavigationStack `count.
> 
> Here is what I see:
> 
>     1. Tap Check Out on the Main Page.
>        ADD: CheckOut COUNT: 2 TIME: 1/10/2020 6:58:09 PM
>        PUSH: CheckOut COUNT: 2 TIME: 1/10/2020 6:58:10 PM
> 
>     2. Tap Save on the CheckOut page.
>        REMOVE: CheckOut COUNT: 1 TIME: 1/10/2020 6:58:14 PM
>        ADD: Production COUNT: 2 TIME: 1/10/2020 6:58:14 PM
>        PUSH: Production COUNT: 2 TIME: 1/10/2020 6:58:14 PM
> 
>     3. Tap Save on the Production page.
>        REMOVE: Production COUNT: 1 TIME: 1/10/2020 6:58:18 PM
> 
>     4. Tap on the Back button
>        POP: Production COUNT: 1 TIME: 1/10/2020 6:59:47 PM
>        REMOVE: Main Page COUNT: 0 TIME: 1/10/2020 6:59:47 PM
> 
> 

```
- Tap CheckOut
ADD: CheckOut COUNT: 2 TIME: 17/01/2020 20:38:47
PUSH: CheckOut COUNT: 2 TIME: 17/01/2020 20:38:47

- Save on CheckOut
REMOVE: CheckOut COUNT: 1 TIME: 17/01/2020 20:39:15
ADD: Production COUNT: 2 TIME: 17/01/2020 20:39:21
PUSH: Production COUNT: 2 TIME: 17/01/2020 20:39:22

- Save on Production
REMOVE: Production COUNT: 1 TIME: 17/01/2020 20:40:05

- Back button
POP: Production COUNT: 1 TIME: 17/01/2020 20:40:15
POP: CheckOut COUNT: 1 TIME: 17/01/2020 20:44:55
```

---

This is the output with the original testing code:
```
- Tap CheckOut
ADD: CheckOut COUNT: 2 TIME: 17/01/2020 20:50:20
PUSH: CheckOut COUNT: 2 TIME: 17/01/2020 20:50:21

- Save on CheckOut
REMOVE: CheckOut COUNT: 1 TIME: 17/01/2020 20:50:38
ADD: Production COUNT: 2 TIME: 17/01/2020 20:50:38
* PUSH: Production COUNT: 3 TIME: 17/01/2020 20:50:38

- Save on Production
REMOVE: Production COUNT: 1 TIME: 17/01/2020 20:51:11
```

Not sure why the count is 3 on the `PUSH: Production`...

**Comment by RLittlesII** [comment]
@garyng Can you provide a sample.  Open a new issue and relate it to this one?

**Comment by garyng** [comment]
I am using the same sample provided by `@andrejpanjan` though.
