### ISSUE TITLE
Update to System.Reactive 4.3.2

### ISSUE THREAD

**Issue by velocitysystems** [reactiveui/ReactiveUI#2288]
**Is your feature request related to a problem? Please describe.**

Yes, `System.Reactive` 4.3.2 fixes a known issue with .NET native compilation.
Refer to https://github.com/dotnet/reactive/pull/1116

A separate issue has been raised for `DynamicData` here.
https://github.com/reactiveui/DynamicData/issues/314

**Describe the solution you'd like**

Update to `System.Reactive` 4.3.2.

**Describe alternatives you've considered**

N/A

**Describe suggestions on how to achieve the feature**

N/A

**Additional context**

N/A

**Comment by glennawatson** [comment]
Not a bug since you can just explicitly include 4.3.2 in your end application and it'll use that binary.
