### ISSUE TITLE
How to use ReactiveUI Command in MvvmCross WPF?

### ISSUE THREAD

**Issue by imckl** [reactiveui/ReactiveUI#2292]
I'm in favor of command binding in ReactiveUI and want to integrate into my current project, which based on MvvmCross.

I've followed the tutorial from [Data Binding - WPF](https://reactiveui.net/docs/handbook/data-binding/windows-presentation-foundation). I just modify View with IViewFor, but not ReactiveObject VIewModel because it inherits MvvmCross object.

Things working fine when I just bind command with basic set - Like ReactiveCommand.Create(TestCommand).
But when I try to use one of the favorable feature, can execute (Create(command, canExecute), it doesn't work :(

It seems `ViewModel = new TheViewModel();` in the tutorial just create another ViewModel instance for interaction. And any property change in my MvvmCross does not reflect to the ViewModel created in View.

So how to properly use ReactiveUI Command in MvvmCross WPF?

**Comment by glennawatson** [comment]
Hi there,

We request that you ask these sorts questions on either StackOverflow or on our slack channel to make them more discoverable to others.

Issues we restrict to just bug reports/feature requests.

Thanks.
