### ISSUE TITLE
Add ReactiveUI.Events support for WinUI

### ISSUE THREAD

**Issue by harvinders** [reactiveui/ReactiveUI#2297]
**Is your feature request related to a problem? Please describe.**

The UWP development has changed a bit, new controls are now added in WinUI library, instead of being release as part of OS release.  

The `ReactiveUI.Events` package for UWP does not have events for the new types added in WinUI, like `ItemRepeater`, `ProgressBar` etc

**Describe the solution you'd like**

A nuget package `ReactiveUI.Events.WinUI` that supports WinUI specific events.

**Describe alternatives you've considered**

A tried creating such as package using `Pharmacist` but ran into compilation error.

**Comment by glennawatson** [comment]
We aren't adding more events projects to RxUI and instead asking people to use pharmacist directly.

**Comment by glennawatson** [comment]
See https://github.com/reactiveui/pharmacist#how-do-i-use

**Comment by glennawatson** [comment]
If you have a compilation error with Pharmacist please just open an issue in that repo also and will look at solving it for you. Please provide a sample.

**Comment by harvinders** [comment]
@glennawatson Thanks, I have raised the issue in pharmacist at https://github.com/reactiveui/Pharmacist/issues/101.
