### ISSUE TITLE
Any working demo for winform?

### ISSUE THREAD

**Issue by jingyiliu** [reactiveui/ReactiveUI#2306]
Hi, guys

Is there any working demo for winform? The demo project said in document is based on ReactiveUI 8.0.1, which is too old, and the sample code does not work on the newer version of  ReactiveUI

**Comment by glennawatson** [comment]
Try https://github.com/reactiveui/ReactiveUI.Samples/tree/master/winforms

**Comment by jingyiliu** [comment]
Thank you.
Now it works
