### ISSUE TITLE
[BUG] Binding ReactiveCommand doesn't fire command correctly

### ISSUE THREAD

**Issue by RLittlesII** [reactiveui/ReactiveUI#2316]
**Describe the bug**

Related To: #2299 
Possibly Related: #2169 

**Steps To Reproduce**
`RefreshCommand = ReactiveCommand.CreateFromTask(async _ => await RefreshItemsAsync(), outputScheduler: RxApp.MainThreadScheduler);`
```
<RefreshView IsRefreshing="{Binding IsRefreshing, Mode=OneWay}"
                     Command="{Binding RefreshCommand}">
        <ScrollView>
               ...
        </ScrollView>
</RefreshView>
```

**Expected behavior**

That I can bind a `ReactiveCommand` to a Xamarin.Forms Visual Element.  Either in the XAML or in Code.

**Screenshots**

**Environment**

- OS: iOS 13.3
- Version ReactiveUI 11.1.1
- Device: iOS Simulator and iPad 10,5"

**Additional context**

It seems there is an issue either with Binding the `ReactiveCommand` or the thread execution of the `ReactiveCommand`.

Works:
```
RefreshView
     .Events()
     .Refreshing
     .InvokeCommand(this, x => x.ViewModel.RefreshCommand);
```

Doesn't Work:
```
this.BindCommand(ViewModel, x => x.RefreshCommand, x => x.RefreshView);
```

**Comment by winterdouglas** [comment]
Hey @RLittlesII it seems you are doing the `BindCommand` wrongly (or you wrote it wrongly here in the thread).
I'm talking about this line:
`this.BindCommand(ViewModel, x => x.RefreshCommand, x => x.RefreshView.IsRefreshing);`

You are binding the `IsRefreshing` with the VM command, was that really the intention?

**Comment by RLittlesII** [comment]
@winterdouglas It's just written wrong here.

`this.BindCommand(ViewModel, x => x.RefreshCommand, x => x.RefreshView);` doesn't work past the first pull.

**Comment by gsgou** [comment]
@RLittlesII you can close this as well as done for https://github.com/reactiveui/ReactiveUI/issues/2299
Tks for figuring out the relation to XF #9326 and
the workaround in the description 👍
