### ISSUE TITLE
[BUG] CS0263 when Nullable project property enabled

### ISSUE THREAD

**Issue by DevoidCoding** [reactiveui/ReactiveUI#2330]
**Describe the bug**
Enabling « Nullable » property on WPF project provide this error
> CS0263	Partial declarations of 'MainWindow' must not specify different base classes

**Steps To Reproduce**
Edit the .csproj
Enable Nullable by adding `<Nullable>enable</Nullable>` in the `PropertyGroup` node (don't forget to be in C# 8.0)
Try to build a project where a XAML window is type of ReactiveWindow with a ViewModel (in XAML and Source Code), try to build and you should have the error even if the classes are the same.

**Expected behavior**
Well, it should actually build.

**Environment**
- OS: Windows 10 
- Version: 18362.592

**Comment by glennawatson** [comment]
This isn't related to Nullability. Check https://stackoverflow.com/questions/4807984/wpf-error-message-partial-declaration-must-not-specify-different-base-classes

**Comment by DevoidCoding** [comment]
I know what this error is about, but it's related to Nullability. If you remove the Nullable property in the project, everything compile and build perfectly, you can just take the sample proposed in https://github.com/reactiveui/ReactiveUI.Samples/tree/master/wpf/getting-started/ReactiveDemo
Just add `<LangVersion>8.0</LangVersion>` and `<Nullable>enable</Nullable>` after line 17 here https://github.com/reactiveui/ReactiveUI.Samples/blob/master/wpf/getting-started/ReactiveDemo/ReactiveDemo.csproj#L17 and it will fail to build

**Comment by glennawatson** [comment]
Hi there. Nullability errors are Cs8600-cs8699 I believe. Lodge a bug with the .net team if you are incorrectly getting cs0263 since you'll likely get other libraries causing issues too.

**Comment by glennawatson** [comment]
We will be doing nullability conversion eventually btw but this bug shouldn't be happening just because the library doesn't have nullability turned off so definitely recommend you lodge that bug.

**Comment by glennawatson** [comment]
The issue looking into it further is that the wpf xaml types does not understand nullable types. Your going to have to set the type in code behind. Even with nullable enabled it's still causing cs0263 in a test I did.

**Comment by glennawatson** [comment]
Had a chat with a wpf team member. Will open a bug with them since the generic type arguments doesn't understand nullable. 

In the meantime use the uwp instructions found here which work https://reactiveui.net/api/reactiveui/reactiveusercontrol_1/
