### ISSUE TITLE
Designing collection around backend and UI changes

### ISSUE THREAD

**Issue by Bert-Proesmans** [reactiveui/ReactiveUI#2338]
Note; The Slack invite link, where I was directed to, is no longer valid. Please move this discussion elsewhere should it pollute the issue tracker.

I'm currently tackling an interesting challenge: Data should refresh, but also properly merge with (limited) model manipulations through the UI. The purpose is entirely for the art of programming.

To provide a concrete example; `class A` has fields `bool checked` and `int data`. The source collection of `A` objects should automatically refresh every few minutes because `data` might be changed in the meantime. The user has checked/unchecked a checkbox which is two-way (mutable) bound to `checked`.

At the moment I use an incremental collection update algorithm that outputs insert, remove and keep commands based on the result of a provided IEqualityComparer. This refreshes `data` but also resets `checked` to its original value. UI changes are not persisted. This approach is invasive; the model data and UI data are properties of the same class.

This question and corresponding solution are not limited to reactive programming but I'm curious to know opinions on how this could fit the Reactive program model.
Reading the docs I noticed you should compose or select specific changes. Maybe my problem doesn't have a generalized solution. 
Anyway, I'd appreciate general advice as well. (I imagine there is a lot of experienced devs gathered around this project, judging from the docs, code, and other issues)

Thank you in advance,
Bert

**Comment by glennawatson** [comment]
Hi Bert, 

We disabled invites temporarily a few weeks ago due to a spammer.

If you can provide me with a email I can send you an invite to slack.

**Comment by glennawatson** [comment]
We re-enabled the slack invite. Given this is much more theory based probably good to open a discussion there. https://reactiveui.net/slack

**Comment by Bert-Proesmans** [comment]
Great, thank you
