### ISSUE TITLE
Remove Dependency on Splat.Drawing

### ISSUE THREAD

**Issue by michaelstonis** [reactiveui/ReactiveUI#2342]
**Is your feature request related to a problem? Please describe.**
When the components of Splat.Drawing were created, they solved a very definite problem in the .NET ecosystem, especially on the Xamarin side of things. Now, we have a pretty good set of translation libraries on the Xamarin side (Xamarin.Essentials, etc.) and with other updates to .NET that open up the ability to share drawing primitives easily across platform.

Initializing Splat.Draw comes at a cost for something that I would imagine _most users don't use and perhaps don't even really know exists_. This appears to be especially true for Xamarin.Android which loads through all images in the bundle.

**Describe the solution you'd like**
Split it out so that Splat.Drawing is some kind of opt-in. Either, make it a separate package that only loads when included or make it a flag that can be enabled, if needed.

**Describe alternatives you've considered**
Perhaps keep things the way that they are more or less today, but make it so that it can be disabled. Right now everything there is statically registered, so it is always called and doesn't give a way to opt-out, so that portion would need to be updated.

**Comment by glennawatson** [comment]
Sounds like a good fix to another bug https://github.com/reactiveui/splat/issues/421
