### ISSUE TITLE
[BUG] Summary of item

### ISSUE THREAD

**Issue by seanalford** [reactiveui/ReactiveUI#2354]
**Describe the bug**
The ReactiveCommand canExecute doesn't seem to be working as expected.  This code did work at one point.

**Steps To Reproduce**
Run this project: https://github.com/seanalford/RxUIWhenAnyValue

**Expected behavior**
Login button should be disabled if Username or Password fields are null or empty.

**Screenshots**
![image](https://user-images.githubusercontent.com/8544833/75377408-c7010a80-589f-11ea-8699-ea51178a433a.png)

**Environment**

- OS:       Pie
- Version   9.0
- Device:   Pixel 2 Simulator

**Comment by RLittlesII** [comment]
You are inheriting from [BindableBase](https://github.com/seanalford/RxUIWhenAnyValue/blob/c95776bb1de06f77115e874534e75483bd00f783/RxUIWhenAnyValue/RxUIWhenAnyValue/ViewModelBase.cs#L9) not `ReactiveObject`

Change your inheritance and everything should work.

**Comment by glennawatson** [comment]
`BindableBase` would work except in this case you're using the Reactive Fody, you'd need to use whatever Prism's `INotifyPropertyChanged` mechanism.
