### ISSUE TITLE
[Winforms] Inherit another IViewFor<T> view

### ISSUE THREAD

**Issue by duongngh** [reactiveui/ReactiveUI#2360]
Hi ReativeUI team,

Is there any way to inherit an IViewFor in winform?
I've searched around, but I don't get it.

Example:
I have a base control
```
public class BaseControl: ReactiveUserControl<BaseViewModel>
{
}
```
This contains some common Properties, Methods.

Now I want:
```
public class ItemDetailControl: BaseControl, IViewFor<ItemDetailViewModel>
{
}
```
I follow (https://reactiveui.net/docs/handbook/view-location/extending-iviewfor)
But I can't find: "public static readonly BindableProperty ViewModelProperty =..." in Winforms

Thank you!

**Comment by RLittlesII** [comment]
@duongngh

`public static readonly BindableProperty ViewModelProperty` is a Xamarin.Forms construct that allows XF a bindable entry point for the binding engine.  This just allows you to interact with that UI platforms binding engine.

I am not sure what the equivalent is in WinForms, or if it has one.

The relevant code you care about for WinForms is in the [ReactiveUserControl](https://github.com/reactiveui/ReactiveUI/blob/56c488585d390b2412f51bc38df48b8c703e4372/src/ReactiveUI.Winforms/ReactiveUserControl.cs#L18-L54)

So you're doing it right.  You just have to solve the concerns of your target platform, how that platform expects.

The purpose of the `IViewFor` is to let the type system know that a given View component will have a specific type of ViewModel.  That is really what you want in this I believe.
