### ISSUE TITLE
Using ReactiveUI with 3rd party Winforms libraries

### ISSUE THREAD

**Issue by urosjovanovic** [reactiveui/ReactiveUI#2361]
Hello everyone,

I've been experimenting with ReactiveUI for some time now, and also tested with 3rd party Winforms libraries such as Telerik for Winforms. For the most part it works fine except that in majority of cases the control's availability (enabled/disabled) cannot be controlled automagically when binding to a command.

For example, RadCommandBar has CommandBarButton which doesn't derive from Component. By looking at this snippet here, I can also see why it doesn't work:
https://github.com/reactiveui/ReactiveUI/blob/a9e3373962c35daf8cea0129ae2b5856f4f0a5e5/src/ReactiveUI.Winforms/CreatesCommandBinding.cs#L82
Is there a particular reason behind this constraint? Would it be possible to allow any type which has the "Enabled" property? Because most of this Telerik UI items have it, just not the one from Component.

If not, what would be the recommended workaround for this?

Best regards,
Uros

**Comment by glennawatson** [comment]
What do the Telerik controls derive off?

Eg do they have any common base class that expose the Enabled

**Comment by urosjovanovic** [comment]
Yes, there is one RadElement class that provides the Enabled property.

**Comment by glennawatson** [comment]
What I would do in your situation then is create a new class derived off `ICreatesCommandBinding`

In the method `GetAffinityForObject` I would give a value of 15 if it's a `RadElement` otherwise 0 (has to be a value higher than what the default `ICreatesCommandBinding` offers.

Then I would implement the logic similar to the `Component` version in the default `ICreatesCommandBinding` but specific for the `RadElement`. 

Hope this helps.

**Comment by urosjovanovic** [comment]
Hi Glenn, thanks for the response.
How would I then inject this behavior into the framework? Or should I need to recompile the ReactiveUI.Winforms library?

**Comment by urosjovanovic** [comment]
Okay, here is what I did.
I didn't like the fact that I have to copy/paste an entire interface implementation from `CreatesWinformsCommandBinding` only to change a couple of lines. I've played with a couple of different solutions and came with something like this:
```C#
using System;
using System.Linq;
using System.Reactive.Disposables;
using System.Reactive.Linq;
using System.Reflection;
using System.Windows.Input;
using Telerik.WinControls;

namespace ReactiveUI.Winforms.Telerik
{
    /// <summary>
    /// This binder is the binder for <see cref="RadElement"/> controls
    /// </summary>
    public class CreatesTelerikWinformsCommandBinding : CreatesWinformsCommandBinding
    {
        public new IDisposable BindCommandToObject<TEventArgs>(ICommand command, object target, IObservable<object> commandParameter, string eventName)
        {
            var ret = (CompositeDisposable)((CreatesWinformsCommandBinding)this).BindCommandToObject<TEventArgs>(command, target, commandParameter, eventName);
            Type targetType = target.GetType();

            if (typeof(RadElement).IsAssignableFrom(targetType))
            {
                PropertyInfo enabledProperty = targetType.GetRuntimeProperty("Enabled");

                if (enabledProperty != null)
                {
                    object latestParam = null;
                    ret.Add(commandParameter.Subscribe(x => latestParam = x));

                    ret.Add(Observable.FromEventPattern<EventHandler, EventArgs>(x => command.CanExecuteChanged += x, x => command.CanExecuteChanged -= x)
                        .Select(_ => command.CanExecute(latestParam))
                        .StartWith(command.CanExecute(latestParam))
                        .Subscribe(x => {
                            enabledProperty.SetValue(target, x, null);
                        }));
                }
            }

            return ret;
        }
    }
}
```
This new binder inherits the default winforms binder but since no method is virtual, I had to 'hack' it with the `new` operator. It calls the 'base' method first and then adds the custom `RadElement` logic afterwards. The following snippet was added to `Program.cs` in Main to tie it all together (I am not 100% sure this is the correct way to add additional registrations).
```C#
IMutableDependencyResolver resolver = Locator.CurrentMutable;
resolver.Register(() => new CreatesTelerikWinformsCommandBinding(), typeof(ICreatesCommandBinding));
resolver.InitializeReactiveUI();
```
This solution is, of course, far from perfect since it relies a lot on some implementation details but it eliminates a lot of copy/paste code which will make maintenance easier.

Let me know your thoughts.

**Comment by glennawatson** [comment]
I can make that interface method virtual for the next release of rxui is probably a easy solution to that problem.

**Comment by urosjovanovic** [comment]
Yes, that would be great. 

But further testing, I've observed this odd behavior where sometimes this binder works (the buttons get disabled based on command canexecute) and sometimes they don't (on the next app run). I'm not sure if it may be due to the fact that there is now to resolvements registered for `ICreatesCommandBinding`. One is the default `CreatesWinformsCommandBinding` and one is this custom one, which derives from it. Not sure how the resolver acts in that case?

Anyhow, if I get some free time in the next couple of days I will also try to refactor the `CreatesWinformsCommandBinding` so it can more convenient to inherit and override and create a PR.
