### ISSUE TITLE
[BUG] Can't build on Xamarin.Android

### ISSUE THREAD

**Issue by Lapinou42** [reactiveui/ReactiveUI#2363]
**Describe the bug**

> /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2056,5): error XALNK7000: Mono.Linker.MarkException: Error processing method: 'System.Void Android.Media.RxAudioRecordEvents::<get_RoutingChanged>b__7_1(System.EventHandler`1<Android.Media.AudioRecord/RoutingChangedEventArgs>)' in assembly: 'ReactiveUI.Events.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void Android.Media.AudioRecord::add_RoutingChanged(System.EventHandler`1<Android.Media.AudioRecord/RoutingChangedEventArgs>)
> /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2056,5): error XALNK7000:   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod (Mono.Cecil.MethodReference reference) [0x00013] in <0275dd5bdfa6470181a4d79d0790489d>:0 
> /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2056,5): error XALNK7000:   at Mono.Linker.Steps.MarkStep.MarkMethod (Mono.Cecil.MethodReference reference) [0x0004a] in <0275dd5bdfa6470181a4d79d0790489d>:0 
> /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2056,5): error XALNK7000:   at Mono.Linker.Steps.MarkStep.MarkInstruction (Mono.Cecil.Cil.Instruction instruction) [0x00040] in <0275dd5bdfa6470181a4d79d0790489d>:0 
> /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2056,5): error XALNK7000:   at Mono.Linker.Steps.MarkStep.MarkMethodBody (Mono.Cecil.Cil.MethodBody body) [0x000c2] in <0275dd5bdfa6470181a4d79d0790489d>:0 
> /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2056,5): error XALNK7000:   at Mono.Linker.Steps.MarkStep.ProcessMethod (Mono.Cecil.MethodDefinition method) [0x00186] in <0275dd5bdfa6470181a4d79d0790489d>:0 
> /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2056,5): error XALNK7000:   at Mono.Linker.Steps.MarkStep.ProcessQueue () [0x0001b] in <0275dd5bdfa6470181a4d79d0790489d>:0 

**Steps To Reproduce**

**Environment**

- OS: Mac OS 10.15.3 (19D76)
- Android SDK version: 10
- VS version: 8.4.8 (build 2)
- ReactiveUI versions: 11.2.3 (ReactiveUI, ReactiveUI.Events, ReactiveUI.AndroidX, ReactiveUI.AndroidSupport)

**Comment by glennawatson** [comment]
Try pharmacist instead of the rxui events packages. These packages are fixed to one version only while pharmacist will adapt the exact version you are using. The rxui events projects are planned to be depreciated in the future.

**Comment by Lapinou42** [comment]
Thank you @glennawatson , I'm gonna to try it and let you know if it works :)

**Comment by Lapinou42** [comment]
I installed Pharmacist and got this error => https://github.com/reactiveui/Pharmacist/issues/119
