### ISSUE TITLE
[BUG] ReactiveUserControl / ViewModelViewHost do not verticaly stretch wehn used with ItemsControll

### ISSUE THREAD

**Issue by mmuecke** [reactiveui/ReactiveUI#2366]
**Describe the bug**
I bind  view models `IViewFor<T>` to a `ItemsControl` and enable scrolling by setting this in the `ItemsControl`:
```
<ItemsControl.Template>
 <ControlTemplate>
  <ScrollViewer>
   <ItemsPresenter />
  </ScrollViewer>
 </ControlTemplate>
</ItemsControl.Template>
```

When I use the same code for a scrollable  `ItemsControl` in a `ReactiveUserControl` and bind this  `ReactiveUserControl` to an outer `ItemsControl` the inner control is only scrolled horizontally and  not scrolled vertically. Vertically the height is not set stretched to outer controls height.

When I use a second `ItemsControl.Template` on the outer `ItemsControl` the `ReactiveUserControl` is bind to, the scrolling works within the outer `ItemsControl` and the inner content is stretched correctly.

**Steps To Reproduce**
Use the [demo project](https://github.com/mmuecke/ReactiveUIViewHostVerticalStretch) and resize the window.

**Expected behavior**
The `ItemsControl` in the `ReactiveUserControl` scrolls horizontally and vertically when the outer size is too low to display the content. A secound definition of a  `ItemsControl.Template` is not requeired to achieve this. Therefor the height of the inner `ItemsControl` is stretched to the space of the outer control.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/6346606/76974580-a9b8dc80-6931-11ea-9e60-bea96331c78d.png)
Showing the different cases in the demo app.

**Environment**

- OS: Windows 10
- UI Framework: .NetCore 3.0 WPF
- Frameworks: Microsoft.NETCore.App, Microsoft.WindowsDesktop.App, Microsoft.NETCore.App.WPF
- Pages: ReactiveUI (11.2.3), ReactiveUI.WPF (11.2.3) 
- Device:   PC

**Comment by glennawatson** [comment]
Try changing the HorizontalContentAlignment and VerticalContentAlignment to stretch.

**Comment by glennawatson** [comment]
On your ReactiveUserControl that is.
