### ISSUE TITLE
Activation closures keep viewmodel alive

### ISSUE THREAD

**Issue by 7unk** [reactiveui/ReactiveUI#2384]
**Describe the bug**

When dynamically switching a view's viewmodel, the first viewmodel instance is being kept alive. 

Encountered the issue while memory profiling a WPF app on .NET Framework 4.6.1. 
ReactiveUI version is 11.3.1.

**Steps To Reproduce**
I've created a simple [repo](https://github.com/7unk/AnimalActivation) to reproduce the issue. The view can be bound to multiple types of viewmodels (to emphasize the issue).

- On start up a `DogViewModel` is bound, the text "Dog" is displayed.
- Take base memory snapshot.
- Clicking the `Switch` button a `CatViewModel` is bound instead.
- Take second memory snapshot.
- Comparing snapshots reveals `DogViewModel` has not been released / GC'ed.

Note if we switch once more, we can verify `CatViewModel` is GC'ed correctly.

**Expected behavior**
A viewmodel that was bound (on startup) should become eligible for garbage collection when it is no longer being referenced by application code.

 

**Environment**

- OS: Windows 10 Pro
- Version: 10.0.18362 Build 18362

 

**Additional context**

Memory profiling shows that the original viewmodel is being kept alive by three roots. Two of those can be traced back to the view's activation cycle, which closes over the instance (ref blue highlighting).

![EventHandler](https://user-images.githubusercontent.com/40923114/79634585-8d47d400-816b-11ea-92be-9dafae47fb77.JPG)

Note I didn't use `ViewModelViewHost` to eliminate it from possible causes.

**Comment by RLittlesII** [comment]
@7unk I will take a look at your sample this week.  I just got my windows machine back up and running, I appreciate your patience.
