### ISSUE TITLE
[ReactiveUI.XamForms] Apple Forced Update needs Upgrade of Xamarin.Forms to 4.5

### ISSUE THREAD

**Issue by BoutemineOualid** [reactiveui/ReactiveUI#2386]
**Description**
Apple has requested recently to update all apps on the store to use the new iOS 13 SDK. The binding for this sdk are only available from version of Xamarin.Forms version 4.5. If possible update references to  this version to avoid rejection as we continue to receive warnings because of the 4.4 reference used by ReactiveUI.XamForms version 11.3.1.

Thanks

**Comment by RLittlesII** [comment]
@BoutemineOualid

A few things.

We had an [RFC](https://github.com/reactiveui/rfcs/issues/7) around Xamarin.Forms and our minimum supported version.  Our policy is to be one minor release behind.  This should not prevent you from migrating your projects to a higher version of Xamarin.Forms.

You mentioned warnings you are getting, care to provide an example of those warnings?  What point in the process you are running into them?  If they are just warnings does your application still function if you migrate to a 4.5 Xamarin.Forms package?

I just took a personal project (understanding that it is not being submitted to the AppStore), from Xamarin.Forms 4.3.0.991250 and migrated just the Xamarin.Forms dependency to 4.5.* I was able to launch the app in a 13.4.1 simulator with no issue.

We don't force a maximum version.  We just require that you meet a minimum version, which is currently ` Xamarin.Forms (>= 4.4.0.991864)`

Also, for documentation, it would be helpful to link the Apple Request.  I have seen reports of it on apple insider, but I cannot find where the official requirement is from Apple.

If you can provide more evidence that we need to bump the version, I wouldn't be opposed to making an exception.

**Comment by BoutemineOualid** [comment]
Hi Rodney,

Thanks for the quick Reply. I thought the package requires a max version. As for your questions, for the warning I am attaching  a screenshot I recently got from Apple.

<img width="705" alt="Screen Shot 2020-04-21 at 1 00 49 PM" src="https://user-images.githubusercontent.com/751981/79892347-7229ce00-83d0-11ea-94ed-c32265842d48.png">

The warning will only be received once the app is submitted to the store for processing. So for some reason, the linker is still including references to the deprecated UIWebView api even though I am setting the linker behavior correctly and running on the latest Xamarin.iOS and Xamarin.Forms.

The news from Apple can be [found here](https://developer.apple.com/news/?id=09102019a&1568158483). Developer started getting warning last February. For the API deprecation, you can check the release notes for XF 4.5 from the xamarin team [here](https://docs.microsoft.com/en-us/xamarin/ios/release-notes/13/13.16).

**Comment by RLittlesII** [comment]
I am generally pretty quick turning around the min version bump on Xamarin.Forms.  And I appreciate you showing the warning, as I suspected it's from the AppStore submission.

Please try upgrading your XF to 4.5 and see if you get the same warning.  That said, I see 4.6 is close to release.  Would will it cause you issues to wait for Xamarin to release 4.6?  I understand multiple AppStore Submissions can be a pain.

**Comment by BoutemineOualid** [comment]
No it's not an urgent matter. Thought it's better to point it out for you anyway to take it into consideration for the next release of ReactiveUI.
Thanks

**Comment by RLittlesII** [comment]
Again.  We upgrade Xamarin.Forms 1 minor version behind their current stable release version.  And we do an explicit release for that package.  So, when 4.6 drops, we will update our minimum dependent version to 4.5 and do a release.

**Comment by xleon** [comment]
I removed the app store warning yesterday by updating to XF 4.5. I don't think RXUI packages have any conflict issues with it.
