### ISSUE TITLE
Inferno

### ISSUE THREAD

**Issue by ingenerics** [reactiveui/ReactiveUI#2387]
Hi,

Congrats on the ReactiveUI framework, it's Event-driven done right.

I wanted to (ab)use this communication channel to inform you about [Inferno](https://github.com/ingenerics/Inferno), feel free to have a look and spread the word.

PS I've left Git history intact for the reviewers.

Gr

**Comment by RLittlesII** [comment]
Thank You for the information.  I appreciate you acknowledging you are abusing the communication channel.  We reserve issues for bug reports and feature requests.  I would make sure that you are following proper attribution guidelines.
