### ISSUE TITLE
Couldn't find an IPlatformOperations implementation

### ISSUE THREAD

**Issue by markusmorawitz77** [reactiveui/ReactiveUI#2389]
Running WPF windows app with the latest version of ReactiveUI published on  NuGet I receive the following error:

ViewModelViewHost: Couldn't find an IPlatformOperations implementation. Please make sure you have installed the latest version of the ReactiveUI packages for your platform. See https://reactiveui.net/docs/getting-started/installation for guidance.

The first attempt to fix this was to register the service using Slat within my bootstrapper code:

Locator.CurrentMutable.Register(() => new PlatformOperations(), typeof(IPlatformOperations));

But unfortunately this is not possible due to the fact that IPlatformOperations is defined as internal although PlatformOperation is public.

There seems to be no problem with the execution of my app. Everything just works fine. But I really would like to understand this error and get rid of the error in case it is not really meaningful.

The app is a netcoreapp3.1 using WPF and referencing the following ReactiveUI packages:
<PackageReference Include="ReactiveUI.Events.WPF" Version="11.3.7" />
<PackageReference Include="ReactiveUI.Fody" Version="11.3.7" />
<PackageReference Include="ReactiveUI.WPF" Version="11.3.7" />

**Comment by RLittlesII** [comment]
@markusmorawitz77 

- Was this an upgrade from a version to a version?
     - if so please identify the versions
- Is there any output of the error?
- What is the actual result?
    - does your application crash?
    - is this error just written to console?

Most of the time that this is caused due to the way we do scanning for things to register.

Is your issue similar to https://github.com/reactiveui/ReactiveUI/issues/2038

**Comment by glennawatson** [comment]
Closing since it's likely including `ReactiveUI.WPF` NuGet package.
