### ISSUE TITLE
Don't know how to detect when app is activated/deactivated.

### ISSUE THREAD

**Issue by ben1628** [reactiveui/ReactiveUI#2398]
The following is working fine in .NET 472, when I move them to .NETCORE, it compiles without problem but run into an exception.
Don't know how to detect when App.ClassName is activated/deactivated, you may need to implement IActivationForViewFetcher"

                this.WhenActivated(
                d =>
                {
                    d(this
                        .VM
                        .Confirm
                        .RegisterHandler(
                             interaction =>
                            {
                                interaction.SetOutput(true);
                                var deleteIt = UtilWin.ShowMessage($"{interaction.Input}", MessageBoxButtons.OK,
                                   interaction.GetOutput() ? MessageBoxIcon.Error : MessageBoxIcon.Information);

                            }));
                });

Any help would be appreciated. Thanks.

**Comment by glennawatson** [comment]
Have you installed the ReactiveUi.wpf nuget package?

**Comment by ben1628** [comment]
Thanks a lot.  Your suggestion points me into the right direction.  The Reactiveui.Window was installed in the .net 472, but not on dotnetcore 3.1.  

It is working well after I installed the windows package.
