### ISSUE TITLE
[BUG] 'RoutedViewHost' does not contain a definition for 'SetBinding'

### ISSUE THREAD

**Issue by ushenkodmitry** [reactiveui/ReactiveUI#2406]
**Describe the bug**
Compilation error when trying to build iOS project:
`'RoutedViewHost' does not contain a definition for 'SetBinding' and no accessible extension method 'SetBinding' accepting a first argument of type 'RoutedViewHost' could be found (are you missing a using directive or an assembly reference?).`

**Steps To Reproduce**

1. Create Uno application via the Uno template in VS.
2. Add RoutedViewHost on Page (UserControl, whatever)
3. Run build

**Expected behavior**
iOS head project builds without errors (UWP and Android projects are built without errors).

**Screenshots**

**Environment**

- OS:        Windows 10
- Version:    VS Community 2019 16.5.4

**Additional context**

ReactiveUI.Uno 11.3.8
Uno.UI 2.3.0-dev.98
Uno.Core 2.0.0-dev.7

**Comment by RLittlesII** [comment]
Just for clarity, is this something that worked with a previous version, and is now broken?  Or is this something you just discovered?

**Comment by ushenkodmitry** [comment]
I just discovered this error and don't know if it worked previously.
Just updated to 11.4.1. Still error.

**Comment by ushenkodmitry** [comment]
Hey,
I haven't seen this error for a long time. I think this issue may be closed. 
Thank you good man for fixing it!
