### ISSUE TITLE
[BUG] Two way binding is not working for NSTextfield

### ISSUE THREAD

**Issue by Dylan-DutchAndBold** [reactiveui/ReactiveUI#2412]
**Describe the bug**
When two way binding a ViewModel to an NSTextField. The ViewModel is never updated. However the NSTextField is updated.

**Steps To Reproduce**
1. Create a ReactiveViewController.
2. Bind in the constructor
```c#
this.Bind(ViewModel, vM => vM.ClientId, v => v.ClientIdTextField.StringValue);
```

**Expected behavior**

When changing the value of an NSTextField. The ViewModel's setter should be hit.
**Environment**

- OS:       MacOS 10.15
- Version   11.4.1
- Device:   Macbook Pro 16

**Additional context**
It seems extremely similar to an earlier reported issue. https://github.com/reactiveui/ReactiveUI/issues/1603 . Which was fixed may 2018. However I have been reading the docs over and over. And however it is missing some details about Xamarin.Mac implementations. I think I got it right. I'll post the full ViewController code below.

```c#
// This file has been autogenerated from a class added in the UI designer.

using System;
using Moneybird.MacOs.ViewModels.Preferences;
using ReactiveUI;

namespace Moneybird.MacOs
{
    public partial class PreferencesViewController : ReactiveViewController<GeneralPreferencesViewModel>
    {
        public PreferencesViewController(IntPtr handle)
            : base(handle)
        {
            this.Bind(ViewModel, vM => vM.ClientId, v => v.ClientIdTextField.StringValue);
            this.Bind(ViewModel, vM => vM.ClientSecret, v => v.ClientSecretTextField.StringValue);
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            ViewModel = RxApp.SuspensionHost.GetAppState<AppState>().GeneralPreferencesViewModel;
        }
    }
}
```

**Comment by Dylan-DutchAndBold** [comment]
Using the `WhenActivated` method has fixed my issue now. I had read before it was good practise, but not mandatory (https://reactiveui.net/docs/handbook/data-binding/#types-of-bindings). But it seems it was mandatory in this case. I just didn't know how it was supposed to be implemented, but the project readme had an good example here https://github.com/reactiveui/ReactiveUI#binding-our-viewmodel-to-the-platform-specific-ui .

**Comment by RLittlesII** [comment]
@Dylan-DutchAndBold Quick question I was going to ask.  Sometimes (depending on how you construct objects) you have to manually set the `BindingContext` (ViewModel = new ViewModel()) in the view.  Generally, I put a breakpoint in the `ViewModel` constructor to verify that it is getting hit when I run into issues like the one you described (literally did this before I saw the notification of this issue).

**Comment by Dylan-DutchAndBold** [comment]
@RLittlesII Thanks. I did put breakpoints on the getter and setter and noticed that only the getter was being hit, except for the setter being hit by Akavache once. I'm glad it is working now.
