### ISSUE TITLE
[BUG] Observable for System.Windows.Point

### ISSUE THREAD

**Issue by RomanSoloweow** [reactiveui/ReactiveUI#2420]
I added property in View:
```C#
Point PositionLeftClick { get; set; }
```
On mouse click I set property value.
And try use it as parameter for command parameter
```C#
this.WhenActivated(disposable =>
{
var positionRightClickObservable = this.ObservableForProperty(x => x.PositionRightClick).Select(x => x.Value);
this.BindCommand(this.ViewModel, x => x.CommandAddNodeWithUndoRedo, x => x.ItemAddNode, positionLeftClickObservable).DisposeWith(disposable);
});

```

But parameter value in command always 0,0

**Comment by glennawatson** [comment]
Use `WhenAnyValue` over `ObservableForProperty`

```
Point PositionLeftClick { get; set; }
```

The get/set is the problem above, you aren't using INotifyPropertyChanged nor any other notifiable property.
