### ISSUE TITLE
[BUG] Observable for System.Windows.Point 

### ISSUE THREAD

**Issue by RomanSoloweow** [reactiveui/ReactiveUI#2421]
Continue: https://github.com/reactiveui/ReactiveUI/issues/2420

I added property in View:
```C#
[Reactive] public Point PositionLeftClick { get; set; } = new Point();
```
On mouse click I set property value.
And try use it as parameter for command parameter
```C#
this.WhenActivated(disposable =>
{
var positionLeftClickObservable = this.WhenAnyValue(x => x.PositionLeftClick);

this.BindCommand(this.ViewModel, x => x.CommandAddNodeWithUndoRedo, x => x.ItemAddNode, positionLeftClickObservable).DisposeWith(disposable);
});

```

But parameter value in command always 0,0

How I can fix it?

**Comment by glennawatson** [comment]
As per the issue please use the resources mentioned.

**Comment by glennawatson** [comment]
In the issue template see the comment `If this is a question please ask on [StackOverflow](https://stackoverflow.com/questions/tagged/reactiveui)`
