### ISSUE TITLE
[BUG] WhenActivated called upon deactivation

### ISSUE THREAD

**Issue by koffmoff** [reactiveui/ReactiveUI#2422]
**Describe the bug**
The `WhenActivated`  hook is invoked when when a control is *deactivated*. It should only be called when the control is *activated*. It seems the control goes through an extra erroneous activation/deactivation cycle upon deactivation.

**Steps To Reproduce**
Repro repo here: https://github.com/koffmoff/ReactiveUI.DoubleActivation

1. Custom control `X` derived from `ReactiveUserControl`
2. `X` uses `WhenActivated` hook in constructor.
3. Present `X` in a `ViewModelViewHost` by setting its `ViewModel` property to the view model that is associated with `X`.
4. Disband `X` by setting `ViewModelViewHost.ViewModel` to `null`.
5. `X.WhenActivated` hook is invoked. It should not.

**Expected behavior**
Step 5 above should not happen.

**Screenshots**
See repro repo.

**Environment**
- OS: Windows
- Version: 10

**Additional context**
N/A

**Comment by glennawatson** [comment]
Anything in the dispose block is called on deactivation. Anything outside of that is called on activation. This is as designed.

**Comment by koffmoff** [comment]
I don't get it. What "dispose block" are you talking about? This is from my view's constructor:

```cs
this.WhenActivated(disp =>
{
    MainWindow.Log("View - Activate");
    Disposable.Create(() => MainWindow.Log("View - Deactivate")).DisposeWith(disp);
});
```

If I do this:
1. Show the control
2. Hide the control.

How can the log be this:
View - Activate
View - Deactivate
View - Activate
View - Deactivate

Where do the two last lines come from?

**Comment by glennawatson** [comment]
From your dispose block.  

`Disposable.Create(()`

**Comment by koffmoff** [comment]
The dispose block logs "View -Deactivate", yes. But it does so TWICE, when the control is deactivated ONCE.

Again, this is what happens:

1. Show the control.
  Log: "View - Activate".  GOOD
2. Hide the control.
  Log: "View - Deactivate". GOOD
  Log: "View - Activate". BAD - Why is this logged?
  Log: "View - Deactivate". BAD - Why is this logged?

See?

**Comment by koffmoff** [comment]
@glennawatson could you please re-open this until we've sorted this out?

**Comment by glennawatson** [comment]
I'm seeing you're registering the view twice?

```
Locator.CurrentMutable.RegisterViewsForViewModels(Assembly.
GetCallingAssembly());
Locator.CurrentMutable.Register(() => new TestView(), typeof(IViewFor<
TestViewModel>));
```

I don't think this should cause the issue though.

**Comment by koffmoff** [comment]
`RegisterViewsForViewModels` does not pick up my View/ViewModel for some reason. Had to register it specifically. But it doesn't matter. `RegisterViewsForViewModels` can be removed. Same result.

**Comment by chuuddo** [comment]
Events fires twice because of `TransitioningContentControl` that used inside `ViewModelViewHost`.
https://github.com/reactiveui/ReactiveUI/blob/552645cfddd1d6babf8a98fe4dd1f747af0e2261/src/ReactiveUI/Platforms/windows-common/ViewModelViewHost.cs#L38 
I create custom `ViewModelViewHost` with `ContentControl` and it works fine.

**Comment by glennawatson** [comment]
We will probably just have to replace the TransitioningContentControl
sometime soon.

**Comment by koffmoff** [comment]
Yeah that's it! I switched to good old `ContentControl` and it works fine!

**Comment by luisllamasbinaburo** [comment]
I'm facing this problem too. Problem is that FrameworkElement launch Loaded and unloaded Events while animation.
This animations are captured via RoutedEvent by Reactive.

I have not found a clean way to disable this Events, or to modify ReactiveUI to handle it.
