### ISSUE TITLE
[BUG] Fody ignores an entire assembly unless 'ReactiveObject' is mentioned somewhere in it

### ISSUE THREAD

**Issue by bawkee** [reactiveui/ReactiveUI#2423]
I noticed that Fody will ignore an assembly unless certain 'trigger keywords' such as `ReactiveObject` are mentioned anywhere in the code (which doesn't even have to be used). If you happen to use a derived class such as `MyReactiveObject` you're out of luck as Fody will **silently** ignore all your reactive attributes. 

There seem to be a variety of triggers, for example using `.WhenAny*` someplace in the assembly. Just placing an attribute, i.e. `[Reactive]` on your class will not work.

I attached a very small solution which demonstrates the issue. 

[FodyBug.zip](https://github.com/reactiveui/ReactiveUI/files/4695661/FodyBug.zip)

Inside is a simple console project which will output PropertyChanged notifications. If you remove a `DummyClass.cs`, everything will compile and run just fine but you will no longer receive notifications.

If this isn't a bug but rather some form of hidden optimisation I'd recommend we at least mention it somewhere. This bit of documentation:

> If a property is annotated with the `[Reactive]` attribute, the plugin will weave the boilerplate into your output based on the simple auto-property declaration you provide.

Is not entirely true. Fody also expects either of the following, from what I've observed so far:
- At least one class in the assembly directly deriving from `ReactiveObject`
- At least some ReactiveUI code used somewhere in the assembly, i.e. `WhenAnyValue`

What's silly about this issue is that after making a 100 assemblies with Fody that work just fine your 101st one will fail for no reason other than its code not having the magic words 😃.

**Comment by glennawatson** [comment]
Hmm. That fody might have a alternative soon. Stand by for a video blog in the next month.

**Comment by davidpurser** [comment]
Just ran into this on latest ReactiveUI.Fody (13.2.18).

My setup consists of a library project which defines base ViewModels, and then an application project which extends them (for cross-platform reasons).  The application never directly used "ReactiveObject" as a base class because all of its ViewModels were derived from base ViewModels in the library.  Properties marked `[Reactive]` in the application's ViewModels did not work as expected until I added a dummy class that derives from `ReactiveObject`.

**Comment by glennawatson** [comment]
The fody is going into maintenance-only mode at the moment while we work on a new project which will replace the functionality in general. Keeping this open to track for the new project.

**Comment by ChrisPulman** [comment]
If possible, please use [ReactiveUI.SourceGenerators](https://github.com/reactiveui/ReactiveUI.SourceGenerators) they work slightly differently but hopefully will fit with your needs.
I updated the example first provided to show that the Source Generators can solve this issue. 
[FodyBug.zip](https://github.com/user-attachments/files/16330141/FodyBug.zip)

As this proves that the issue can be solved by using the ReactiveUI Source Generators, and ReactiveUI.Fody is now in maintenance mode I will close this.
