### ISSUE TITLE
[Question] Proper use of the TestScheduler

### ISSUE THREAD

**Issue by Evangelink** [reactiveui/ReactiveUI#2436]
Hello,

I am having some trouble to use the `TestScheduler` properly, or at least I think so.

I have read the various website entries related to the `TestScheduler` but it seems that I am not getting things right all the time. I have some tests that are randomly failing and seem to be related to timing of "events". Do I need to use the `new TestScheduler().With(...);` pattern for all the tests that involve reactive commands and observables? It seems that quite a lot of my tests work the same with and without this but some don't.

Also, is there a rule of thumb on when I need to have the `scheduler.Start()` in the lambda I declare?

Finally, is there any important difference between `Sleep()` and `AdvanceBy`?

**Comment by glennawatson** [comment]
Jump on slack and feel free to ask there. 

https://reactiveui.net/slack

Also stackoverflow.com

**Comment by cabauman** [comment]
@Evangelink feel free to reach out to us on Slack or StackOverflow, like Glenn mentioned.
