### ISSUE TITLE
housekeeping: Azure Pipelines CI Badge link became broken 

### ISSUE THREAD

**Issue by worldbeater** [reactiveui/ReactiveUI#2438]
**Describe the bug**

After changing the default branch `master` to `main` in some of my repositories ([first](https://github.com/worldbeater/citrus.avalonia), [second](https://github.com/worldbeater/camelotia)), Azure Pipelines CI Badge links in `README.md` became broken. Then I decided to check if ReactiveUI's [main repository](https://github.com/reactiveui/ReactiveUI) experiences the same issue. It turned out, that the following link is no longer working:

https://dev.azure.com/dotnet/ReactiveUI/_build/latest?definitionId=11 

![image](https://user-images.githubusercontent.com/6759207/84375860-d2770800-abe8-11ea-9213-bce51a205cc3.png)

However, the following link works, but doesn't point to build results:

https://dev.azure.com/dotnet/ReactiveUI/_build/?definitionId=11

The link generated by Azure Pipelines `Status Badge` button is not working as well:

https://dev.azure.com/dotnet/ReactiveUI/_build/latest?definitionId=11&branchName=main

**Expected behavior**

When one clicks the Azure Pipelines CI badge, the page displaying build results should open.

**Additional context**

After looking through Azure Pipelines CI configuration, discovered that the branch name `master` is stored in `... -> Edit Pipeline -> ... -> Triggers -> YAML -> Get Sources -> Default branch for manual and scheduled builds`. Probably worth changing the branch name there as well. However, this doesn't seem to fix the original issue.

**Comment by glennawatson** [comment]
```
[![Build Status](https://dev.azure.com/dotnet/ReactiveUI/_apis/build/status/ReactiveUI-CI?branchName=main)](https://dev.azure.com/dotnet/ReactiveUI/_build/latest?definitionId=11&branchName=main)
```

or 

```https://dev.azure.com/dotnet/ReactiveUI/_apis/build/status/ReactiveUI-CI?branchName=main```

**Comment by worldbeater** [comment]
Getting 404 after clicking this badge: 
```
[![Build Status](https://dev.azure.com/dotnet/ReactiveUI/_apis/build/status/ReactiveUI-CI?branchName=main)](https://dev.azure.com/dotnet/ReactiveUI/_build/latest?definitionId=11&branchName=main)
```
[![Build Status](https://dev.azure.com/dotnet/ReactiveUI/_apis/build/status/ReactiveUI-CI?branchName=main)](https://dev.azure.com/dotnet/ReactiveUI/_build/latest?definitionId=11&branchName=main)

**Comment by glennawatson** [comment]
Yeah. This was the text produced by azure DevOps itself. I will make a tweet to the Microsoft twitter world in my morning.

**Comment by martinwoodward** [comment]
Looks to be a sitewide issue and not related to branch name change (see https://github.com/martinwoodward/hello64 - a project I haven't touched in a long time).

Pinging @vijayma and folks internally on the Pipelines team.

**Comment by worldbeater** [comment]
Thank you folks ❤︎

**Comment by vijayma** [comment]
We are investigating. This is not related to your branch name change.

**Comment by worldbeater** [comment]
Seems this issue is resolved now. Thank you, folks! 🎉
