### ISSUE TITLE
OneWayBind cannot bind ViewModel to DataContext

### ISSUE THREAD

**Issue by crud-boy** [reactiveui/ReactiveUI#2446]
Problem code
```C#
this.OneWayBind(this, vm => vm.ViewModel, view => view.DataContext).DisposeWith(d);
```
Normal binding code
```
this.DataContext = this.ViewModel
```

**Comment by glennawatson** [comment]
We encourage you not to use DataContext usually, instead if you use the ViewModel on the platform's provided controls with the code behind binding.

Also no mention of any platform here so no idea if you are talking WPF/UWP/Xamarin Forms/WinUI 3/Maui
