### ISSUE TITLE
[BUG] Mono.Linker.MarkException in Wasm

### ISSUE THREAD

**Issue by ushenkodmitry** [reactiveui/ReactiveUI#2462]
**Describe the bug**

Error building WASM project, created using Uno Template. 

Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:54.8453782] Fatal error in Mono IL Linker
Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:54.8461295]
Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:54.8473299] Unhandled Exception: Mono.Linker.MarkException: Error processing method: 'System.Void ReactiveUI.Uno.GlobalStaticResources::Initialize()' in assembly: 'ReactiveUI.Uno.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void Uno.UI.Wasm.GlobalStaticResources::Initialize()
Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:54.8473432]    at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:54.8473452]    at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:54.8473467]    at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:54.8473479]    at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:54.8473491]    at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:54.8473502]    at Mono.Linker.Steps.MarkStep.ProcessQueue()
Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:54.8473513]    --- End of inner exception stack trace ---
Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:54.8473524]    at Mono.Linker.Steps.MarkStep.ProcessQueue()
Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:54.8473534]    at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:54.8473553]    at Mono.Linker.Steps.MarkStep.Process()
Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:54.8473564]    at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:54.8473575]    at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:54.8473717]    at Mono.Linker.Pipeline.Process(LinkContext context)
Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:54.8473733]    at Mono.Linker.Driver.Run(ILogger customLogger)
Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:54.8473744]    at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
Uno.Wasm.Bootstrap.targets(126,2): error : [00:00:54.8473756]    at Mono.Linker.Driver.Main(String[] args)
Uno.Wasm.Bootstrap.targets(126,2): error : System.Exception: Failed to execute the linker
Uno.Wasm.Bootstrap.targets(126,2): error :    at Uno.Wasm.Bootstrap.ShellTask_va92f3a69a92510bbb7feabd262d39abbfb9e137e.RunPackager() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 709
Uno.Wasm.Bootstrap.targets(126,2): error :    at Uno.Wasm.Bootstrap.ShellTask_va92f3a69a92510bbb7feabd262d39abbfb9e137e.Execute() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 182

**Steps To Reproduce**

1. Create new Uno app using Uno template in VS (Microsoft Visual Studio Community 2019 Version 16.6.5)
2. Add latest ReactiveUI.Uno package and update all Uno dependencies to the latest (include prerelease versions)
```
    <PackageReference Include="ReactiveUI.Uno" Version="11.5.1" />
    <PackageReference Include="Uno.Microsoft.Toolkit.Uwp.UI.Controls" Version="6.1.0-build.186.g928c99f74d" />
    <PackageReference Include="Uno.UI.RemoteControl" Version="3.0.0-dev.1117" Condition="'$(Configuration)'=='Debug'" />
    <PackageReference Include="Uno.UI.WebAssembly" Version="3.0.0-dev.1117" />
    <PackageReference Include="Uno.Wasm.Bootstrap" Version="1.4.0-dev.14" />
    <PackageReference Include="Uno.Wasm.Bootstrap.DevServer" Version="1.4.0-dev.14" />
```
3. Build

**Expected behavior**

All projects are built without errors.

**Screenshots**

**Environment**

- OS:       
- Version   
- Device:   

**Additional context**

**Comment by glennawatson** [comment]
Might be worth also talking direct to the uno guys since they have supported us in the past with the wasm implementation.

**Comment by cabauman** [comment]
So according to the reply on the linked Uno issue, we just have to target Uno 3.0 because of a breaking change they made: https://github.com/unoplatform/uno/issues/3651#issuecomment-665614852

**Comment by ushenkodmitry** [comment]
Can we have a prerelease version of ReactiveUI.Uno for that?

**Comment by glennawatson** [comment]
No sorry.

We don't do pre-releases due to the support implications.

**Comment by glennawatson** [comment]
Uno released the 3.* series, so we've updated. Should resolve your issue, otherwise follow in the Uno issue.

**Comment by ushenkodmitry** [comment]
Thank you! I was waiting for this.

вс, 16 авг. 2020 г. в 08:28, Glenn <notifications@github.com>:
