### ISSUE TITLE
[BUG] SuspensionHost extensions broke when nullability was added

### ISSUE THREAD

**Issue by TolikPylypchuk** [reactiveui/ReactiveUI#2465]
**Describe the bug**

There seem to be 2 issues in the `SuspensionHostExtensions` class which appeared after upgrading to version 11.5.1. I'll describe them both here since they are quite small. I believe this is because of changes introduced [in this commit](https://github.com/reactiveui/ReactiveUI/commit/5e9219f46650d391439356cb414a777244ff1f11#diff-998c62f3331af15dfc3ef211a16a52e5).

1. `SetupDefaultSuspendResume` always throws `NullReferenceException`. I think this is because this code was added to the method:
```
if (item.AppState == null)
{
    throw new NullReferenceException(nameof(item.AppState));
}
```
As far as I understand, `item.AppState` is always going to be `null` at this point, because we're just setting up the suspension host and the app state didn't have a chance to be initialized yet.

2. `ObserveAppState` always throws `InvalidCastException`. This is because this line:
```
return item.WhenAny(x => x.AppState, x => (T)x.Value)
```
was changed to this:
```
return item.WhenAny(x => x.AppState, x => (T)x)
```

So now instead of casting `x.Value`, it tries to cast `x` which is of type `ObservedChange`.

**Steps To Reproduce**

1. Try to set up the suspension driver as described in [ReactiveUI's docs](https://www.reactiveui.net/docs/handbook/data-persistence/) or in [Avalonia's docs](https://avaloniaui.net/docs/reactiveui/suspension#creating-the-suspension-driver).

**Expected behavior**

Well, I would expect it not to throw any exceptions :)

**Environment**

- OS: Windows 10
- Version: 11.5.1

**Comment by ins0mniaque** [comment]
I'm having the same problem after updating to 11.5.1.

SetupDefaultSuspendResume throws NullReferenceException on start, and attempting to initialize the AppState to a non-null value before calling SetupDefaultSuspendResume will "workaround" the first bug, but it then throws InvalidCastException, exactly as described by @TolikPylypchuk.

**Comment by glennawatson** [comment]
Thanks for confirming. We will have a fix out in a day or so
