### ISSUE TITLE
Silent Bind Failure

### ISSUE THREAD

**Issue by Noggog** [reactiveui/ReactiveUI#2474]
**Describe the bug**
I've noticed one scenario where a Bind() call fails to work with zero other changes after updating from 11.4.17 -> 11.5.1.   Might apply to more situations than the one I've found, of course.

**Steps To Reproduce**
For me, I've only noticed it when binding a VM value to a ContentPresenter's content.  To help describe the specific situation, I've made a minimal repository to show the bug:  https://github.com/Noggog/RxUI-Binding-Bug

It is a -very- simple GUI, with a list of numbers.  Click on a number, and it shows in the content presenter.
Binding is set up via RxUI bindings in ReactiveUserControls.

If this solution is updated to the newest RxUI, the binding seems to not do its job anymore.  It doesn't seem to throw, but also doesn't seem to update the presenter's content as it did before.  It's almost as if it just does nothing now, and doesn't complain or warn.

Not exactly sure what could be causing the change in behavior, or why it doesn't affect my other Bind() calls I have in my GUIs

**Expected behavior**
The binding to the content presenter should set the content to the selected item

**Screenshot**

Like I said, a very minimal example GUI.  Content presenter number is to the right of the list.
![Minimal Example GUI](https://user-images.githubusercontent.com/24981326/88898148-f4b4fb80-d211-11ea-9d6a-67abe2c0dc66.png)

**Comment by CyLuGh** [comment]
I've also noticed some weird behaviors with the data binding when updating to 11.5.*

I'll have to try to get a simple example to illustrate it.

**Comment by RLittlesII** [comment]
We recently introduced C# nullability support.  Based on what I am seeing you seem to have `SelectedItem` as a nullable type.  This shoul work.  Looking into this.
