### ISSUE TITLE
[BUG] ReactiveUI-Events doesn't have "Click" for WPF

### ISSUE THREAD

**Issue by leek9** [reactiveui/ReactiveUI#2494]
This bug is similar to [issue#832](https://github.com/reactiveui/ReactiveUI/issues/832) where pharmacists failed to generate some controls event in WPF.

**Steps To Reproduce**
1. Create a button and/or checkbox in WPF project
2. In code behind call ReactiveUI-Event that is generated by pharmacists.
3. The button in this case will be bind to RxControlEvents instead which doesn't not have click event underneath.

**Expected behavior**
Primitive control such as button and checkbox in WPF should have pharmacists generated event.
Screenshots below is the current list that is generated in 11.4.0.0 version.

**Current workaround as mentioned in [issue#832](https://github.com/reactiveui/ReactiveUI/issues/832)**
`(DisBtn as ButtonBase).Events().Click.Subscribe(_ => DoSomething());`

**Screenshots**
![image](https://user-images.githubusercontent.com/15202418/90056681-426b4280-dcad-11ea-8555-393b3f0b1b89.png)

**Environment**
- OS:       Window 10
- Version   N/A
- Device:   Desktop

**Comment by ChrisPulman** [comment]
I understand that it works by scanning the namespace for events, you should add the relevant using which for a click event would be System.Windows.Controls.Primitives, I hope that this helps you to use Pharmacist with more success.

**Comment by leek9** [comment]
Thanks for replying, Chris.
Yes, casting is not needed once the primitive namespace is added.
And checkbox uses IsChecked event from toggle button.

I guess I will have to make do when there is an event that wasn't map.
Not sure I have the technical capabilities to figure out how pharmacist detects the controls' events and fix it myself.

Thanks.
