### ISSUE TITLE
[BUG] Due to a change after V11.3.8 the reactive chain is broken.

### ISSUE THREAD

**Issue by ChrisPulman** [reactiveui/ReactiveUI#2508]
**Describe the bug**
It has been identified in the following project that is based entirely upon RXUI that all versions after 11.3.8 cause the cutline feature to stop working.
https://github.com/Wouterdek/NodeNetwork/issues/82 

**Steps To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://github.com/Wouterdek/NodeNetwork get the latest source. 
2. Run the samples add at least two nodes and add a link between the nodes by clicking on an output from one node and dragging to another node.
3. Remove the cutline by right clicking and dragging across the line to remove it (the cutline creates a subscription between Nodes, once removed disposes of it and cleans up the subscriptions) 
4. Add a cutline again and then move a node around, you will see that the node is attached to the line. Everything is normal and operational.
5. Update the RxUi packages to 11.4.* or newer adding Splat.Drawing as required.
6. Run again and repeat steps 1 to 4 however at step 4 you will notice that the cutline is detached and no longer removable or movable.

**Expected behaviour**
At step 4 with the new RxUi packages the Cutline behaviour should remain the same as 11.3.8 or lower

**Environment**

- OS:       Windows 10 Pro
- Version   20H2
- Device:   Laptop

**Additional context**
Has same issue in net48 and netcoreapp3.1, this is a WPF library.

**Comment by dpvreony** [comment]
as per the Wouterdek/NodeNetwork#82 item

https://github.com/reactiveui/ReactiveUI/commit/7bb038c90e3f14ec79cf67f608c70d1880675c5d introduced a breaking change
