### ISSUE TITLE
[Question] How to handle nested view models?

### ISSUE THREAD

**Issue by ShadowDancer** [reactiveui/ReactiveUI#2529]
For a regular view models I think this is easy, I can easily handle this by myself:
```
this.WhenActivatedd(disposables =>{
NestedVm.Activator.Activate();
Disposable.Create(() => NestedVm.Activator.Deactivate()).DisposeWith(disposables);
});
```
However I think this is really cumbersome, I think there should be an extension method to handle this for me, like: `NestedVm.Activate(disposables)`:
```
this.WhenActivatedd(disposables =>{
NestedVm.Activate(disposables); // equivalent code
});
```

The problem I have is about having nested VMs. Let's assume I have something like this:
```
_entities.Connect()
    .Select(n => new EntryVm(n, this))
    .ObserveOn(RxApp.MainThreadScheduler)
    .Bind(out _vmList)
    .Subscribe()
    .DisposeWith(disposables);
```
If the nested vm does not need reference to my object I can ignore it, but what if it does? I think I could do something like:
```
this.WhenActivated(disposables =>{
_service.Entities.Connect()
    .ObserveOn(RxApp.MainThreadScheduler)
    .Select(n => {
          var entry = new EntryVm(n, this);
          entry.Activate(disposables); // using above extension method
          return entry;
    })
    .Bind(out _vmList)
    .Subscribe()
    .DisposeWith(disposables);
}
```

However there is problem, because the vm may be deactivated while events are waiting in `RxApp.MainThreadScheduler`, and "dangling" `EntryVm` may be created, which will never be disposed. What is recommended way to handle this?

**Comment by glennawatson** [comment]
We focus on answering questions via slack or stackoveflow. If you ask on slack might be best if you ask on the dynamic data channel. Thanks.
