### ISSUE TITLE
[BUG] (WPF) When a TransitioningContentControl's initial actual width or height is 0, it throws an exception in v12.1.1

### ISSUE THREAD

**Issue by TolikPylypchuk** [reactiveui/ReactiveUI#2565]
**Describe the bug**

This is a WPF issue; I don't know whether it also applies to other platforms.

When the content presenter of a `TransitioningContentControl` has a zero actual width/height, an exception is thrown in the [`TransitioningContentControl.GetRenderTargetBitmapFromUiElement`](https://github.com/reactiveui/ReactiveUI/blob/89f6a5140c1d77e9543637faf664bc890f59a58d/src/ReactiveUI.Wpf/TransitioningContentControl.cs#L225) method during the initial transition. This applies to v12.1.1 only - everything works fine in v11.x.

**Steps To Reproduce**

I've created a repository which reproduces the issue: https://github.com/TolikPylypchuk/ReactiveUIBugTransitioningControl.

The repository contains a simple window which contains a `ViewModelViewHost`. By default its content is stretched, so the exception will not be thrown. But if you go to `MainWindow.xaml` and remove the `TestHost`'s `HorizontalContentAlignment` or `VerticalContentAlignment` then the content's actual width or height will become 0, and an exception will be thrown when binding to a view model.

**Expected behavior**

No exceptions thrown when the initial actual width/height of the content is 0.

**Environment**

- OS: Windows 10
- Version: 2004

The issue is reproducible on .NET Core 3.1 and .NET 5 RC2.

**Additional context**

As a workaround, you can make sure that your `TransitioningContentControl` either has an explicit size or is stretched, and stretches its content, and then control the sizing in its child controls - this worked for me, but I guess it's not always applicable.

**Comment by glennawatson** [comment]
We are currently working on a fix for this one and should be out in the next couple days

**Comment by RLittlesII** [comment]
@TolikPylypchuk thanks for the detailed information and the reproduction.
