### ISSUE TITLE
[BUG] ReactiveCommand from ReactiveCommand.CreateFromObservable causes deadlock

### ISSUE THREAD

**Issue by bazarniy** [reactiveui/ReactiveUI#2593]
**Describe the bug**
I've tried to create reactive command from observable. I got deadlock while executing it.

**Steps To Reproduce**
This will wait forever:
```
await ReactiveCommand.CreateFromObservable<Unit, Unit>(_ =>
                        Observable
                            .Never<Unit>()
                            .StartWith(Unit.Default)
                    )
                    .Execute();
```

This one doesn't work in viewmodel's constructor

```
ReactiveCommand.CreateFromObservable<Unit, Unit>(_ =>
                    Observable
                        .Return(Unit.Default)
                )
                .Execute()
                .Wait();
```

**Expected behavior**
No infinite waiting after inner observable emit
If an inner observable must emit onComplete, what's wrong with second example?

**Environment**

- OS:       Win10
- Version   netcoreapp3.1 ReactiveUI.WPF 12.1.5

**Comment by glennawatson** [comment]
`Wait()` is never good even with Task libraries. It's likely to cause you deadlocks.
