### ISSUE TITLE
[BUG] InitializeReactiveUI for Uno tries to load XamForms

### ISSUE THREAD

**Issue by ushenkodmitry** [reactiveui/ReactiveUI#2601]
**Describe the bug**
Exception **Could not load the file 'ReactiveUI.XamForms'** raised when trying to call InitializeReactiveUI method with Uno namespace running Android head:

```
var assembly = Assembly.GetExecutingAssembly();
var builder = new ContainerBuilder();
builder.RegisterAssemblyModules(assembly);
var resolver = builder.UseAutofacDependencyResolver();
resolver.InitializeSplat();
resolver.InitializeReactiveUI(RegistrationNamespace.Uno);
```

**Steps To Reproduce**

1. Create new Uno solution
2. Add ReactiveUI.Uno nuget dependency
3. Use the code above to initialize ReactiveUI in App.OnLaunched

**Expected behavior**

No exception raised.

**Screenshots**

**Environment**

- OS:        Windows 10
- Version   
- Device:    Android  Emulator

**Additional context**

```
    <PackageReference Include="ReactiveUI.Uno">
      <Version>13.0.1</Version>
    </PackageReference>
```

**Comment by glennawatson** [comment]
This is normal and it's a caught exception.

**Comment by glennawatson** [comment]
We also added some functionality a little while back where you can limit the DLL it searches for. 

See https://github.com/reactiveui/ReactiveUI/blob/8b5fd711129ffc174ddd4195995c3f8957eaccce/src/ReactiveUI/PlatformRegistrationManager.cs#L25
