### ISSUE TITLE
[BUG] Cast<T>() Collision with System.Reactive.Linq.Observable

### ISSUE THREAD

**Issue by Noggog** [reactiveui/ReactiveUI#2625]
**Describe the bug**
I am currently getting an API collision between RxUI's offering of Cast and System.Reactive.Linq.Observable's offering.

**Steps To Reproduce**
- New project
- Add RxUI nuget
- Import
```
using ReactiveUI;
using System.Reactive.Linq;
```
- Add code
```
IObservable<string> test = null;
test.Cast<string?>();
```

**Comment by glennawatson** [comment]
Should be auto-released soon to nuget.
