### ISSUE TITLE
[BUG] Timer on RxApp.TaskpoolScheduler blocks under Blazor WASM view

### ISSUE THREAD

**Issue by genejo** [reactiveui/ReactiveUI#2628]
I'm trying to use an older VM which starts a finitely ticking timer under a Blazor WASM view. Each tick changes a property bound under the view. If started with `RxApp.TaskpoolScheduler`, each change in the property is reflected in real time. If started with `RxApp.MainThreadScheduler` only after the last tick is the page properly loaded.

```C#
this.WhenActivated(
    disposables => {
        Observable
            .Timer(
                TimeSpan.Zero,
                TimeSpan.FromMilliseconds(500),
                /*
                RxApp.MainThreadScheduler
                /*/
                RxApp.TaskpoolScheduler
                //*/
                )
            .Take(5)
            .Do(
                t => { Greeting = $"Hello, {t}!"; },
                () => Console.WriteLine("Those are all the greetings, folks! ")
            )
            .Subscribe()
            .DisposeWith(disposables);
    });
```

I understand Blazor WASM is single threaded, but shouldn't existing VMs used with WPF/Avalonia etc. work out of the box?

This is the [github project link](https://github.com/genejo/ReactiveBlazor/tree/master/HelloReactiveBlazor) if needed.

**Comment by glennawatson** [comment]
You can change what's defined in RxApp MainThreadSvheduler as a workaround to make your view models work

**Comment by genejo** [comment]
So I'll just do `RxApp.MainThreadScheduler = RxApp.TaskpoolScheduler;` in the main view constructor. Thank you!

**Comment by glennawatson** [comment]
I'll have a further play around after the break but that should get you up and running.
