### ISSUE TITLE
Base Class missing ?

### ISSUE THREAD

**Issue by MonsieurTib** [reactiveui/ReactiveUI#2649]
For MacOs Platform, the documentation indicates to use our normal iOS concepts that we would usually use in OSX development, with a list of base class some of which are missing ( reactivetableview, reactivetableviewcontroller ) in reactiveui package.

**Comment by glennawatson** [comment]
They exist

**Comment by MonsieurTib** [comment]
package version : 13.0.38

I can't find ReactiveTableView, ReactiveTableViewController :

<img width="821" alt="screen_reactive" src="https://user-images.githubusercontent.com/11044865/105324023-24462e80-5bcb-11eb-8751-654b5b7906c3.png">

**Comment by glennawatson** [comment]
https://github.com/reactiveui/ReactiveUI/blob/main/src/ReactiveUI/Platforms/uikit-common/ReactiveTableView.cs

I would check your iOS versions looks like you're getting the netstandard nuget being resolved

**Comment by MonsieurTib** [comment]
Im on MacOS (Xamarin.Mac) not iOS
