### ISSUE TITLE
ReactiveUI nuget package is incompatible with WinUI 3 (ARM64)

### ISSUE THREAD

**Issue by huoyaoyuan** [reactiveui/ReactiveUI#2657]
The same as https://github.com/dotnet/reactive/issues/1461

It requires `Microsoft.WindowsDesktop.App` on `net5.0-windows`, which is unavailable on win-arm64. But WinUI 3 supports win-arm64.

I see `System.Reactive.Linq.ControlObservable` using Windows Forms. I wonder why it isn't in ReactiveUI.WinForms.

**Comment by glennawatson** [comment]
We are unlikely to at the moment support WinUI 3 until it matures a bit more

**Comment by huoyaoyuan** [comment]
You have packages for WPF and WinForms. Why not moving the framework-dependent members into them?

I know it's the not the time for supporting WinUI 3, but current package structure prevents any custom utilization.

**Comment by agent00jackson** [comment]
Any updates? MS is really pushing WinUI 3 now.

**Comment by glennawatson** [comment]
I'll have another look in the coming weeks

One problem I had and others was they implemented INotifyPropertyChanged slightly different to most other platforms. Eg different namespaces etc

**Comment by kmgallahan** [comment]
Just commenting to add that this is a critical time for ReactiveUI to add support for WinUI 3. 

* New version of Windows is being announced on June 24th
* WinUI 3 is has moved from previews to supported releases
* UWP is effectively dead: https://github.com/microsoft/ProjectReunion/issues/105#issuecomment-825067277
* Anyone starting a desktop WinUI 3 project will see ReactiveUI isn't an option and be forced to proceed without it, likely never to spend the time to refactor it in later
 
I'm in that last boat. I had started to experiment with ReactiveUI in some LOB UWP projects 1-2 years ago, but after MS indicated UWP was dead and desktop is the way forward I put off further development. I'm starting back on up on the projects now and see that I have to make a choice to wait for ReactiveUI support or to proceed without it.

**Comment by glennawatson** [comment]
@kmgallahan WinUI 3 is preview and we won't commit to any release of libraries against preview. We generally add support after the full release.

**Comment by huoyaoyuan** [comment]
@glennawatson WinUI 3 is now *supported* with major version 0. It's not feature complete, but it's now supported.

The required action isn't to support anything specific to WinUI 3. It's a layering issue - System.Reactive shouldn't reference WinForms and only ReactiveUI.WinForms should.

**Comment by glennawatson** [comment]
Closing this issue for the moment.

**Comment by glennawatson** [comment]
I am refactoring out the net4/net5 targets from the core RxUI project, but this might not work how you want given System.Reactive also includes Winforms/WPF dependencies in their project.

**Comment by huoyaoyuan** [comment]
Yes, this is indeed a System.Reactive issue. But that issue isn't actively responded. It will be helpful if you can contact their maintainers.

**Comment by glennawatson** [comment]
I don't have any influence over their maintainers.

**Comment by glennawatson** [comment]
I will be removing the references to wpf and winforms in the main rxui nuget in a PR soon though. 

That's mostly there for backwards compatibility for users due to the way Rx 5 did some stuff but can be moved into the wpf and winforms nugets. 

WinUI3 is separate to this issue though and will make a separate issue to track so all those talking about winui this issue is related but not strictly related to it.

**Comment by FrancoisM** [comment]
"WinUI3 is separate to this issue though and will make a separate issue to track " => which separate issue @glennawatson please?

**Comment by glennawatson** [comment]
Search the issues for winui3

We don't have plans to support until it's fully realised.
