### ISSUE TITLE
[BUG] Blazor: ToProperty is not calling the property's setter

### ISSUE THREAD

**Issue by jhr007** [reactiveui/ReactiveUI#2658]
**Describe the bug**

An observable on the ViewModel that uses `ToProperty` doesn't call the property's setter, but `BindTo` does. 
It does however, trigger a `PropertyChanged` event. `¯\_(ツ)_/¯` From the initialization of the underlying OAPH?

I was originally using `WhenAnyValue(v => v.ViewModel.MyProperty)` in the view to try to trigger a `StateHasChanged`, but it was only triggering once on initialization. When the view logged the `PropertyChanged` events, it shows the property changing, but not the `WhenAnyValue` only logged empty on initialization.  A `Do` in the ViewModel pipeline showed the property was never being set, as well a log in the property's setter.  

I tried various SubscribeOn, ObserveOn, ToProperty(schedule:) combinations(think: monkeys banging out Shakespeare), but nothing. 

**Expected behavior**

I expect ToProperty to set the property 😃 

**Environment**

- OS:       Win 10, Net 5.0
- Device:   FireFox 84.0.2, Edge 88.0.705.50
- Version   
 ```
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="5.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="5.0.1" PrivateAssets="all" />
    <PackageReference Include="System.Net.Http.Json" Version="5.0.0" />
    <PackageReference Include="ReactiveUI.Blazor" Version="13.1.1" />
    <PackageReference Include="Splat.Microsoft.Extensions.DependencyInjection" Version="10.0.1" />
 ```

**Steps To Reproduce**

**Additional context**

Create a Blazor WASM stand alone project, start watching it. 
```
dotnet new blazorwasm --output ToPropertyBug
cd ToPropertyBug
dotnet watch run
```
Replace `Index.razor` with this block or change `@inherits` from `Index.IndexViewModel` to  match whatever razor file you paste it into `YourRazorFile.IndexViewModel`

The browser console shows the new ExpectedGuid being set, and the view seeing the property change, but not the property being set. 
```razor
@page "/"

@using System.ComponentModel
@using System.Reactive
@using System.Reactive.Concurrency
@using System.Reactive.Linq
@using System.Threading
@using ReactiveUI

@inherits ReactiveUI.Blazor.ReactiveComponentBase<Index.IndexViewModel>

<h1>Hello, world!</h1>

Welcome to your new app.
<br>
Guid: @ViewModel?.MyGuid
<br>
Expected: @ViewModel?.ExpectedGuid

@code
{
    protected override void OnInitialized()
    {
        ViewModel = new IndexViewModel();
        Console.WriteLine($"Mono.Runtime {Type.GetType("Mono.Runtime")} is not null");
        
//Shows the view can see the property change
        Observable
            .FromEvent<PropertyChangedEventHandler, PropertyChangedEventArgs>(
                handler => (sender, args) => handler(args), 
                eh => ViewModel.PropertyChanged += eh,
                eh => ViewModel.PropertyChanged -= eh)
            .Do(x => Console.WriteLine($"Property Changed: {x.PropertyName}"))
            .Subscribe();
    }

    public class IndexViewModel : ReactiveObject
    {
        public IndexViewModel()
        {
            //RxApp.MainThreadScheduler = RxApp.TaskpoolScheduler; // saw in another issue
            
//Originally had a property that triggered this pipeline, but I got tired of clicking the button
            Observable.Timer(TimeSpan.FromMilliseconds(30), TimeSpan.FromMilliseconds(1500))
                .Select(x => Guid.NewGuid())
                .Do(x => ExpectedGuid = x)
                .Do(x => Console.WriteLine(x))
                .WhereNotNull()
                // .BindTo(this, x=> x.MyGuid); //works 
                .ToProperty(this, x => x.MyGuid); //doesnt work
        }

        public Guid ExpectedGuid { get; set; }

        private Guid _myGuid;
        public Guid MyGuid
        {
            get => _myGuid;
            set
            {
//Never reached with ToProperty
                Console.WriteLine("Setter");
                this.RaiseAndSetIfChanged(ref _myGuid, value);
            }
        }
    }
}

```

**Comment by glennawatson** [comment]
You aren't doing anything with the return value of ToProperty().  Normally you have a private OAPH field.

**Comment by glennawatson** [comment]
Going to close this one and here's the docs https://www.reactiveui.net/docs/handbook/observable-as-property-helper/ any more info feel free to comment
