### ISSUE TITLE
Page WhenActivated, OnAppearing called when app is backgrounded and then foregrounded (Android only)

### ISSUE THREAD

**Issue by jeremy-bridges** [reactiveui/ReactiveUI#2665]
**Describe the bug**
On a ReactiveContentPage, we hand an Action to WhenActivated for it to be called when the View and ViewModel are initialized and bound together. In iOS, this is called on app start, but not when app simply comes to the foreground (without being removed from memory). In Android, WhenActivated is called every time the app comes back to the foreground.

**Steps To Reproduce**
1. Build an app with a page that overrides OnAppearing and calls this.WhenActivated in its constructor
2. Place breakpoints or logging in the Action body handed to WhenActivated and the OnAppearing override
3. Start app, watch breakpoints/logging be hit
4. Background app
5. Foreground app, watch breakpoints/logging be hit

**Expected behavior**
iOS and Android behavior should be consistent.

**Code**
```
    public partial class ExamplePage : ReactiveContentPage<ExamplePageViewModel>
    {
        public ShellView()
        {
            InitializeComponent();

            this.WhenActivated(disposables =>
            {
                // called only once in iOS, but every time the app is foregrounded in Android
                Debug.WriteLine("WhenActivated block called");
            });            
        }

        protected override void OnAppearing()
        {
            base.OnAppearing();

            // called only once in iOS, but every time the app is foregrounded in Android
            Debug.WriteLine("OnAppearing called");
        }
```

**Environment**

- OS:       iOS 14.x and Android 10
- Device:   tablets (iPad Pro and Mini, Samsung A7 and S6 Lite)

**Comment by xleon** [comment]
I think this behavior is expected and far beyond ReactiveUI limits IMO. It's how the life cycle of Android works. When moving an app from background to foreground, the current activity `OnResume()` method is called by the system, which triggers Xamarin.Forms `OnAppearing()`, which triggers ReactiveUI `WhenActivated()`. Changing that in ReactiveUI would break many apps (including mine).

**Comment by jeremy-bridges** [comment]
Alright. We'll keep this in mind for Android. Thanks for the advice.
