### ISSUE TITLE
[BUG] InvalidProgramException when [Reactive] property with Nullable<T> type is assigned null in member declaration

### ISSUE THREAD

**Issue by JesperTreetop** [reactiveui/ReactiveUI#2688]
**Describe the bug**
When a Fody-woven `[Reactive]` property of nullable value type (`Nullable<T>` for some `T`) is assigned `null` directly in the member declaration, running the constructor results in an InvalidProgramException.

**Steps To Reproduce**
1. Create a new WPF project.
2. Add ReactiveUI and the Fody package.
3. Add a Loaded event handler to the MainWindow window, and make the code mirror:
```csharp
    public partial class MainWindow : Window {
        public MainWindow() {
            InitializeComponent();
        }

        private void MainWindow_OnLoaded(object sender, RoutedEventArgs e) {
            var z = new TestViewModel(); // <- "A"
        }
    }

    public class TestViewModel :  ReactiveObject {
        [Reactive]
        public int? Floopy { get; set; } = null;
    }
```
4. Run. The code will crash in location "A". (The event doesn't matter, but the exception would be caught by XAML construction and obscured if run in the window's constructor.)

**Expected behavior**
For there not to be an issue. Assigning `null` happens to be redundant, and assigning other values does not seem to cause crashes. Nullable reference types are also not affected.

"Just don't do that" is a perfectly reasonable workaround - but it took me an hour to narrow it down to this being the issue.

**Environment**
- OS:       Windows
- Version   10
- Device:   PC
- Reactive UI: 13.1.1

**Comment by glennawatson** [comment]
For v14 of rxui I have a rewritten fody that can handle this much better. Just need time to finish it. Hopefully in the next week or so. 

Workaround for the moment is just to use the RaiseAndSetIfChanged for this one

**Comment by JesperTreetop** [comment]
In my case I solved it by just not assigning `null` to it, since that's the default value anyway, and since that's the only thing that triggers this bug (that I know of!) it's reasonable. (This appeared in a stretch of code where other properties were assigned to non-default values.) If something else triggered it, it could be fixed by moving the assignment to first thing inside the constructor too, that also works.

**Comment by glennawatson** [comment]
Our fody doesn't honour default values at the moment that's one of the planned fixes

**Comment by glennawatson** [comment]
The fody is going into maintenance-only mode at the moment while we work on a new project which will replace the functionality in general. Keeping this open to track for the new project.

**Comment by colejohnson66** [comment]
This issue was making me tear my hair out the past few days

**Comment by colejohnson66** [comment]
My guess is that, because the `Nullable<T>` is being assigned with the default value, there's no `stfld` opcode generated, but the weaver just grabbed the first opcode of any type where the operand is a field reference (which `ldflda` and `stfld` both have):

https://github.com/reactiveui/ReactiveUI/blob/f6aa1176ecd3159fe2890cf82d06e5ee452ef936/src/ReactiveUI.Fody/ReactiveUIPropertyWeaver.cs#L115

It seems changing that to also require the opcode to be a `stfld` might fix the issue.

**Comment by KyleC69** [comment]
> In my case I solved it by just not assigning `null` to it, since that's the default value anyway, and since that's the only thing that triggers this bug (that I know of!) it's reasonable. (This appeared in a stretch of code where other properties were assigned to non-default values.) If something else triggered it, it could be fixed by moving the assignment to first thing inside the constructor too, that also works.

As of Avalonia 11.0 rc1 and Reactive 18;  This bug still exists and also appears when attempting to assign a non-null value to an annotated property.  Let me know if more details are needed.

**Comment by glennawatson** [comment]
Fody are no longer maintained. Look for alternatives hopefully coming soon but we aren't maintaining at the moment due to maintenance burden

**Comment by KyleC69** [comment]
Thank you for the heads up. That's unfortunate,  Avalonia/Reactive may want to remove the recommendations from the docs, so someone else doesn't follow that rabbit hole :)  Any plans for Av or Rx to implement annotations?

**Comment by glennawatson** [comment]
We plan to. Just need time. Be closer to the mvvm toolkit using source generators. Just infinitely easier to maintain.

**Comment by KyleC69** [comment]
As of RC1 11.0 Source gens seem to still have a problem and requires to still use FindControl, think that might be fixed before releasing 11.0?  And thank you for your time and the info.  One more new-b question, What is the relationship between AvaloniaUI and ReactiveUI? Is it an off shoot with different maintainers? I find myself flipping between the two trying to solve a problem :) Just curious.

**Comment by glennawatson** [comment]
No idea. We don't control the Avalonia source generator. Just the rxui model generation stuff

**Comment by KyleC69** [comment]
Thanks Glenn have a good evening
