### ISSUE TITLE
[BUG] when SubscribeOn a collection ,we cannot receive any notification

### ISSUE THREAD

**Issue by Luoyingliang** [reactiveui/ReactiveUI#2706]
I want to observe a collection changed and process the notification in another thread,but when i call SubscribeOn method,it doesn't work, when i remove the SubscribeOn method it work so well.

**Environment:**
SDK : .Net 5.0 SDK
LIB: ReactiveUI 13.0.1
      ReactiveUI.WPF 13.0.1
      System.Reactive 5.0.0
OS: Windows 10

   ```    
    public class Model
    {
        public string Text { get; set; }
    }
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        private ObservableCollectionExtended<Model> Collection;

        public MainWindow()
        {
            InitializeComponent();

            //
            // it test can subscribeOn method work on thread pool scheduler
            Collection = new ObservableCollectionExtended<Model>();
            Collection.WhenAnyPropertyChanged()
                      .SubscribeOn(RxApp.TaskpoolScheduler)
                      .Select(x => x!)
                      .Subscribe(x =>RxApp.TaskpoolScheduler.Schedule(()=> Debug.WriteLine($"collection work on thread:{Thread.CurrentThread.ManagedThreadId}")));
            Collection.Add(new Model());
        }
    }
```

**Comment by glennawatson** [comment]
`ObservableCollectionExtended` isn't part of ReactiveUI, you probably want to find the DynamicData repository.

Also why SubscribeOn not ObserveOn?

**Comment by Luoyingliang** [comment]
> `ObservableCollectionExtended` isn't part of ReactiveUI, you probably want to find the DynamicData repository.
> 
> Also why SubscribeOn not ObserveOn?

thx
because i need to reduce variable to find out where the problem happen

**Comment by glennawatson** [comment]
I don't think you'll be any advantages here using `SubscribeOn()` -- try ObserveOn which will put everything on the TaskpoolThreadScheduler after that statement which will allow you optimisation in your Select.

**Comment by Luoyingliang** [comment]
> I don't think you'll be any advantages here using `SubscribeOn()` -- try ObserveOn which will put everything on the TaskpoolThreadScheduler after that statement which will allow you optimisation in your Select.

it means, stream will observeon TaskPoolScheduler,and it also process notification in TaskPoolScheduler?

**Comment by glennawatson** [comment]
You can't really control the notification thread, so there's just no advantage. Eg whatever sets the value is what thread the notificaiton happens on, it's more worth using ObserveOn after that.

**Comment by Luoyingliang** [comment]
oh! thx,i got it.thx for your reply
