### ISSUE TITLE
Assembly signing

### ISSUE THREAD

**Issue by georgiuk** [reactiveui/ReactiveUI#2709]
Hi. Don't get me wrong, I have read comments on issues #43,  #24 , etc about your view on assembly signing. 
But I also see in https://www.reactiveui.net/docs/getting-started/installation/ the following:
"ReactiveUI packages are now signed by the dotnet foundation...". 
I was wondering if is this something in TODOs or the doc is wrong.

Thanx
Kostas

**Comment by glennawatson** [comment]
One is code signing which won't be happening. 

The other is nuget package signing which is signed by the dot net foundation.

**Comment by glennawatson** [comment]
Code signing is a signature included on a DLL level with a sign hash. .net assembly loading can then make sure the hash matches what the program is setup to use 

Nuget package signing just verified that a particular entity made the nuget package.

**Comment by georgiuk** [comment]
Ah ok. I thought assemblies will be also signed.
Thanx for the info.
