### ISSUE TITLE
[BUG] Unable to handle Android layout resource with different casing

### ISSUE THREAD

**Issue by sgong-pdftron** [reactiveui/ReactiveUI#2721]
**Describe the bug**

WireUpControls would fail when Android layout ID contains the same characters but different casing, for example:

			// aapt resource value: 0x7F09004D
			public const int Toolbar = 2131296333;
			
			// aapt resource value: 0x7F090492
			public const int toolbar = 2131297426;

This would throw exception:
Failed to wire up the Property InputFieldsContainer to a View in your layout with a corresponding identifier ---> System.ArgumentException: An item with the same key has already been added. Key: toolbar

**Steps To Reproduce**

1. Create an Xamarin.Android project that uses WireUpControls
2. Include 2 binding libraries, one with resource toolbar, and one with resource Toolbar
3. The project will die run time due to 
Failed to wire up the Property InputFieldsContainer to a View in your layout with a corresponding identifier ---> System.ArgumentException: An item with the same key has already been added. Key: toolbar

**Expected behavior**

Different casing will be picked up properly

**Screenshots**

**Environment**

- OS: Android      
- Version  29 
- Device:  Emulator 

**Additional context**

**Comment by glennawatson** [comment]
This is deliberate that its case aware to match android's functionality.
