### ISSUE TITLE
[BUG] ToProperty not being executed in the right order

### ISSUE THREAD

**Issue by ajpinedam** [reactiveui/ReactiveUI#2734]
**Describe the bug**
When an Observable Pipeline tick and the result is chained into a `ToProperty` (OAPH) the property update seems to be deferred.

**Steps To Reproduce**
Attached there is a test project (Unit Testing) 

[ReactiveChain_ToPropertyIssue.zip](https://github.com/reactiveui/ReactiveUI/files/6267041/ReactiveChain_ToPropertyIssue.zip)

As a workaround, we replaced the  `ToProperty` for a `Subscribe()`

**Expected behavior**
`ToProperty()` would behave as the `Subscribe()`.

**Screenshots**

**Environment**

- OS:       
- Version   
- Device:   
- .NetCore: 3.1

**Additional context**
We tested it on RxUI Version 11.5.35 and also the latest version (13.2.10).

**Comment by ChrisPulman** [comment]
Hi @ajpinedam sorry this took so long to look at, in your workaround you have not specified a Scheduler for the Subscription, in a real application you would need a Scheduler to update your property or its highly likely to throw a cross thread exception. Updating your test to include an ImmediateScheduler for the ToProperty will allow it to operate in the same way, just as adding a CurrentThreadScheduler to your workaround Subscription will make them both operate in the same way but fail in the same way too.

`public SubjectToTest(IService service)
        {
            _service = service;

            _service.Updated
                .Select(x => x)
                .ToProperty(this, nameof(CurrentValue), out _currentValue, scheduler: ImmediateScheduler.Instance)
                .DisposeWith(_subscriptions);`

Thanks for your patience.
