### ISSUE TITLE
[BUG] ReactiveCommand.CreateFromTask does not change the UI  Thread To Worker Thread

### ISSUE THREAD

**Issue by MohammadSadeghSalimian** [reactiveui/ReactiveUI#2744]
**Describe the bug**

 ReactiveCommand.CreateFromTask does not change the UI thread leading to UI thread lock. I have written a ViewModel in which an Async Task method is implemented. However, when a reactiveCommand is fired, the thread remains in MainThrad and results in a UI thread Lock. I have checked many parts of my application, however, the problem cannot be eliminated. 

**Steps To Reproduce**

 
			public ReactiveCommand<Unit, Unit> UpdateCmd { get; private set; }
			public void InitializeCommands()
			{

			  UpdateCmd = ReactiveCommand.CreateFromTask(UpdateTelegram, this.WhenAnyValue(x => x.IsTelegramActive));
			}
			private async Task UpdateTelegram()
			{
			 try
			 {
				 Debug.WriteLine($"Thread ID: {Thread.CurrentThread.ManagedThreadId}");
				 await _mainUnit.GetTweetByUpdate();
				 Debug.WriteLine($"Thread ID: {Thread.CurrentThread.ManagedThreadId}");
			   
			 }
			 catch (Exception e)
			 {
				 await _messageUnit.ErrorMessageAsync(e.Message);
			 }
			}	

Thread ID: 1 Before Excuting  GetTweetByUpdate();
Thread ID: 1 During Excuting GetTweetByUpdate();
Thread ID: 1 After Excuting GetTweetByUpdate();
**Expected behavior**

**Screenshots**

**Environment**

- OS:       Windows 10
- Version   WPF .NET 5.0
- Device:   PC

**Additional context**

**Comment by glennawatson** [comment]
This is by design

https://www.reactiveui.net/docs/handbook/commands/#asynchronous-commands
