### ISSUE TITLE
[BUG] infinite heap allocation, if model interface not an IReactiveObject, and [Bind, WhenPropertyChanged] used

### ISSUE THREAD

**Issue by AlBannaTechno** [reactiveui/ReactiveUI#2763]
**Describe the bug**

this issue occurs, if you used two-way binding on an interface that not inherit from **IReactiveObject**
everything will work fine until you listen to these changes with any listener eg, **WhenPropertyChanged**
you will get heap allocation issue due to infinite loop notifications,
so at this stage, you must make your Model interface inherit from **IReactiveObject** 

like
```C#
this.Bind(ViewModel, vm => vm.DatabaseServices.Name, v => v.Username.Text)
                    .DisposeWith(d);
  
this.ViewModel.WhenPropertyChanged(vm => vm.DatabaseServices.Name, false)
    .Subscribe(_ =>
    {
        // ➜ this will called infinite times
    }).DisposeWith(d);
```

**Steps To Reproduce**
* [Use This Repository](https://github.com/AlBannaTechno/ReactiveUiTwoWayBindingWithChanges_Issue)
* Try to run the app, and it will hang due to an infinite notification loop [at](https://github.com/AlBannaTechno/ReactiveUiTwoWayBindingWithChanges_Issue/blob/f062b1b4685fc71b6fad84337b2f6e82f0b1f99c/ReactiveUiTwoWayBindingWithChangesIssue/MainWindow.xaml.cs#L28)
* [To make it work](https://github.com/AlBannaTechno/ReactiveUiTwoWayBindingWithChanges_Issue/blob/f062b1b4685fc71b6fad84337b2f6e82f0b1f99c/ReactiveUiTwoWayBindingWithChangesIssue/MainWindow.xaml.cs#L46) 

**Environment**

- OS:       Windows 10, Version	10.0.19042 Build 19042
- Version   13.3.2
- Device:   Laptop

**Additional context**
I just do not know if this is a bug, or it is just an intention behavior, or it is current limitations
but I will report it anyway, may be some one face the same issue

**Comment by glennawatson** [comment]
`WhenPropertyChanged` is not a reactiveui extension method. `WhenAnyValue` is
