### ISSUE TITLE
Blazor: Make CompositeDisposable accessible from derived components

### ISSUE THREAD

**Issue by TenBuck** [reactiveui/ReactiveUI#2783]
**Is your feature request related to a problem? Please describe.**

I want to easily hook to base component composite disposable in derived ReactiveComponentBase

**Describe the solution you'd like**

Make CompositeDisposable protected (or public)
https://github.com/reactiveui/ReactiveUI/blob/5c2665d27049add007e67bbb665b80e978925bd3/src/ReactiveUI.Blazor/ReactiveComponentBase.cs#L29

**Describe alternatives you've considered**

overriding virtual Dispose and using private CompositeDisposable. This works well but is not as clean and requires boilerplate

**Describe suggestions on how to achieve the feature**

Make CompositeDisposable protected
https://github.com/reactiveui/ReactiveUI/blob/5c2665d27049add007e67bbb665b80e978925bd3/src/ReactiveUI.Blazor/ReactiveComponentBase.cs#L29

**Additional context**

**Comment by glennawatson** [comment]
We won't be exposing this due to it just being logic for internal activation logic.
