### ISSUE TITLE
ReactiveUI Events doesn't seem to have an implementation of SelectionChanged for ListView

### ISSUE THREAD

**Issue by Awsmolak** [reactiveui/ReactiveUI#2791]
Attempting to use the events on a listview to get the selected items.

In my viewmodel:
```
this.MyListView.Events().SelectionChanged
....
```
Does not work because Events() doesn't seem to have SelectionChanged implemented.

**Comment by glennawatson** [comment]
If you're in a position to you can try moving to our preferred mechanism now the source generator https://github.com/reactivemarbles/ObservableEvents#observable-event-generator

**Comment by Awsmolak** [comment]
Not in a position at the moment. Going to go ahead and use Observable.FromEventPattern for the moment, if there truly is no event implementation yet.  [Like this](https://stackoverflow.com/questions/32440637/get-selected-items-collection-from-a-reactivelist-using-reactiveui) (I was wondering if I had maybe missed something...)

I'll explore using the generator sometime down the line.

**Comment by glennawatson** [comment]
When you are in a position it should be a straight swap over, no change in the syntax.

**Comment by Awsmolak** [comment]
The event I'm trying to subscribe to is System.Controls.Listview. The readme only discusses using the generator on classes in my assembly. So how would I get it to generate the event for references external assemblies?

**Comment by glennawatson** [comment]
The generator will work for ListView automatically.

**Comment by Awsmolak** [comment]
Gotcha!
I've added the package using the recommendation in the Readme, but I can't seem to reference ReactiveMarbles.ObservableEvents. My project is .NET 4.8 not .NET Core...

**Comment by glennawatson** [comment]
What version of Visual Studio are you using?

**Comment by Awsmolak** [comment]
2019 v16.9.4

**Comment by glennawatson** [comment]
New enough to handle source generators although v16.10 is better.

Sometimes you might need to give the project a compile first.

**Comment by Awsmolak** [comment]
I've tried rebuilding, reopening solution, installing from the package manager GUI instead of adding the packagereference to the .csproj. Nothing...

Updating VS now. Will update this comment after I try that...

**Comment by Awsmolak** [comment]
No luck. Maybe there is something funky going on with Nuget?
One interesting thing I noticed is that if I add:
```xml
<PackageReference Include="ReactiveMarbles.ObservableEvents.SourceGenerator" Version="1.0.2" PrivateAssets="all" />
```
to my .csproj, the package manager GUI no longer sees any of my other packages, just that one. But regardless of how I reference it in the project, the compiler will not pick it up.

**Comment by glennawatson** [comment]
If you want you can jump onto Slack I can probably maybe give you a bit more interactive help rather than in a issue. 

https://www.reactiveui.net/slack

**Comment by drepamig** [comment]
I was having a similar issue as @Awsmolak. After some troubleshooting, I found a solution. See [this issue](https://github.com/microsoft/CsWin32/issues/7). The key for me was the build failing in `*_wpftmp.csproj`

The fix is simply to add `<IncludePackageReferencesDuringMarkupCompilation>true</IncludePackageReferencesDuringMarkupCompilation>` to the `<PropertyGroup>` section in your project's `csproj` file.

**Comment by glennawatson** [comment]
Looks like there is a solution bsaed on @drepamig -- Thanks for the help.
