### ISSUE TITLE
[BUG] Summary of item

### ISSUE THREAD

**Issue by tomasfil** [reactiveui/ReactiveUI#2794]
**Describe the bug**
First of all, the documentation is wrong:
https://www.reactiveui.net/docs/handbook/routing/

xmlns:rxui="https://reactiveui.net"
should be
xmlns:rxui="http://reactiveui.net"

After this is fixed, then the program compiles, but this error persists:
![obrazek](https://user-images.githubusercontent.com/34779382/122423671-62832680-cf8e-11eb-82e0-485c8828a0c8.png)

Whole issue is well documented at stackoverflow issue:
https://stackoverflow.com/questions/68017205/reactive-ui-getting-started-with-compelling-example-wont-work

**Steps To Reproduce**
Try to compile the programs and they wont, even that they are almost 1:1 with compelling example.

https://reactivex.slack.com/archives/C02AJB872/p1623931697193400

**Environment**

- OS:       Win10
- Version   13.3.2
- Device:   PC
- NET:    NET5

**Comment by glennawatson** [comment]
Got it to work here locally. Think it was just invalid xaml

Here's the link

[KardexTerminal_WPF.zip](https://github.com/reactiveui/ReactiveUI/files/6675483/KardexTerminal_WPF.zip)

**Comment by tomasfil** [comment]
Hello, 

few questions. I just downloaded zip from you (*Thanks*), but:
I cannot access this.WhenActivated in your solution.
Also I have red errors with InitializeComponent()
And I cannot access ViewModel property.

![obrazek](https://user-images.githubusercontent.com/34779382/122530158-7d9d7700-d01e-11eb-8434-cf485dbea50d.png)

**Comment by glennawatson** [comment]
I think you are suffering from maybe NuGet issues now? I just grabbed that zip again and it compiles.

try going to a developer command line and doing a "dotnet restore"

**Comment by glennawatson** [comment]
I was definitely compile issues in your original zip though.

**Comment by glennawatson** [comment]
Also locking this issue since GitHub issues isn't hte appropriate place.

**Comment by glennawatson** [comment]
If you want to bring this up in a discussion happy to continue helping you there, but confirmed in a couple different IDE locally that it works. Issues tend to get clogged down and harder to track though for us for problem solving.
