### ISSUE TITLE
ISupportsActivation Removed?

### ISSUE THREAD

**Issue by vector-man** [reactiveui/ReactiveUI#2802]
I'm working on Windows Forms and updated my Nugets today, and cannot find ISupportsActivation anymore. Was it removed? If so, is there a workaround?

**Comment by ChrisPulman** [comment]
I believe that it has been superseded by IActivatableViewModel
https://www.reactiveui.net/docs/handbook/when-activated/

**Comment by glennawatson** [comment]
Closing due to the new interface identified.
