### ISSUE TITLE
WinForms: Using WhenAnyValue with BindingList item count change.

### ISSUE THREAD

**Issue by vector-man** [reactiveui/ReactiveUI#2825]
I need to create a command with a condition in the view model for WhenAnyValue that will work with a BindingList's Item Count change (the BindingList property in the view model is bound to a control on the form.)

When the item count is 0, I need the command to not work (reactive UI isn't seeing the change for me.)

Any help is appreciated.

**Comment by glennawatson** [comment]
Issues are reserved for bug and feature requests. You can use the GitHub discussion feature or slack if you need help.
