### ISSUE TITLE
[BUG] Fody fails to weaving record when it inherited from ReactiveRecord

### ISSUE THREAD

**Issue by asv7c2** [reactiveui/ReactiveUI#2831]
**Describe the bug**

Fody is failed to execute weaving on record. Shows such error:
```
  Fody: An unhandled exception occurred:
Exception:
Failed to execute weaver C:\Users\Alexander\.nuget\packages\reactiveui.fody\14.1.1\build\..\weaver\ReactiveUI.Fody.dll
Type:
System.Exception
StackTrace:
   at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 220
   at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 111
Source:
FodyIsolated
TargetSite:
Void ExecuteWeavers()
Sequence contains more than one matching element
Type:
System.InvalidOperationException
StackTrace:
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at ReactiveUI.Fody.ReactiveUIPropertyWeaver.Execute()
   at ReactiveUI.Fody.ModuleWeaver.Execute()
   at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 197
Source:
System.Linq
TargetSite:
Void ThrowMoreThanOneMatchException()
```

**Steps To Reproduce**

Code to reproduce:
```
using ReactiveUI;
using ReactiveUI.Fody.Helpers;

namespace Playground
{
    internal static class Program
    {
        private static void Main()
        {
        }
    }

    public record Test([property: Reactive] string Value) : ReactiveRecord;
}
```

**Expected behavior**

**Screenshots**

**Environment**

- OS:       
- Version   
- Device:   
OS: Windows 10 x64

**Additional context**

**Comment by glennawatson** [comment]
I have a rewrite of fody I need to get finished that can handle records just fine.

Expect it in about 3-4 weeks time it's on my todo list one weekend coming.

**Comment by glennawatson** [comment]
The fody is going into maintenance-only mode at the moment while we work on a new project which will replace the functionality in general. Keeping this open to track for the new project.

**Comment by mysteryx93** [comment]
I'm getting the same error on a small project and I'm not using records.

Where can I get information about the new project?

**Comment by ChrisPulman** [comment]
You can find details of the project here https://github.com/reactivemarbles/ObservableEvents

**Comment by glennawatson** [comment]
As mentioned, the fody is going into maintenance only at the moment. No ETA on providing the replacement.

**Comment by VAllens** [comment]
I'm having the same problem.
Change `record` to `class` and the problem disappears.
Other than that, is there any interim solution?

**Comment by ChrisPulman** [comment]
Please try our ReactiveUI.SourceGenerators as Fody is no longer being developed.
I will close this but please reopen if required
