### ISSUE TITLE
[BUG] ReactiveCommand.IsExecuting does not work when outputScheduler is RxApp.TaskpoolScheduler

### ISSUE THREAD

**Issue by HavenDV** [reactiveui/ReactiveUI#2834]
### Problem
```cs
var command = ReactiveCommand.CreateFromTask(
    cancellationToken => RunAsync(cancellationToken),
    outputScheduler: RxApp.TaskpoolScheduler);
command.IsExecuting
    .Subscribe(static value => 
    {
        Console.WriteLine($"IsExecuting: {value}");
    });
```
This code does not output anything to the console when the command starts and ends, only on initialization.
If I don't set the outputScheduler then everything works fine.

### Environment
ReactiveUI 13.3.2

**Comment by glennawatson** [comment]
What UI are you using. They can change what the RxApp refers to

**Comment by HavenDV** [comment]
WPF(net4.6.1 and net5.0)

**Comment by ChrisPulman** [comment]
The applied fix will still require you to use:
`command.IsExecuting.ObserveOn(RxApp.MainThreadScheduler).Subscribe(static value => Trace.WriteLine($"IsExecuting: {value}"));`

This is to handle the cross threading between the selected Execution thread and your UI Thread. 
This is due to the Subscriptions being created on the thread that you choose for Execution, in this case the TaskPool thread.
If you were to Subscribe to the CanExecute observable the same will apply.

I hope that this helps.

Thanks for reporting this issue.

**Comment by HavenDV** [comment]
I suppose I can omit `ObserveOn(RxApp.MainThreadScheduler)` in this use case?

```cs
_ = this
    .WhenAnyObservable(
        static x => x.Add.IsExecuting,
        static x => x.Delete.IsExecuting,
        static x => x.Update.IsExecuting,
        static (add, delete, update) => !add && !delete && !update)
    .ToPropertyEx(
        this,
        static x => x.IsEnabled,
        true,
        false,
        RxApp.MainThreadScheduler
        );
```

**Comment by glennawatson** [comment]
It should default to the main thread scheduler anyway with toproperty

**Comment by ChrisPulman** [comment]
I believe once you get the fix the code you have there should work, you normally flip onto the UI thread as late as possible when required, ToProperty and ToPropertyEx normally take you to the correct UI thread.

**Comment by HavenDV** [comment]
Have you thought about speeding up your release delivery a bit by releasing prerelease versions to NuGet every time you run ci after a pull request? You can get subversions automatically for example using einaregilsson/build-number or GITHUB_RUN_ID/GITHUB_RUN_NUMBER of the Github Actions variables.

**Comment by glennawatson** [comment]
We thought about it but not something we'll take up at the moment. We had it going with GitHub packages but there were issues. Versioning isn't a issue since Nerdbank git versioning handles that use case

**Comment by glennawatson** [comment]
Also not to completely shoot you down btw there's some complexity happening at the moment with releases behind the scenes hence why we haven't released in a bit

**Comment by HavenDV** [comment]
> It should default to the main thread scheduler anyway with toproperty

I remembered why I started to explicitly specify RxApp.MainThreadScheduler in ToPropertyEx - I think I was having problems in a Uno WebAssembly project and explicitly specifying RxApp.MainThreadScheduler helped.
But I'm not sure about this, it was a long time ago, so it needs to be tested.

**Comment by glennawatson** [comment]
As mentioned we have some release issues at the moment, as soon as they are resolved we'll do another build with this fix.

At the moment a workaround might be to do a `ObserveOn` on the canExecute observable.

**Comment by glennawatson** [comment]
We will be reverting this. The fix will be to use `ObserveOn` before you pass in the CanExecute
