### ISSUE TITLE
[BUG] net6.0 support messes with net6.0-android project references

### ISSUE THREAD

**Issue by panoukos41** [reactiveui/ReactiveUI#2895]
**Describe the bug**

When targeting net6.0-android for version `15.1.1` and you try to use apis from the ReactiveUI Android platform like `ReactiveUI.ControlFetcherMixin.WireUpControls(this);` you get the message:

> The type or namespace name `ControlFetcerMixin` does not exist in the namespace `ReactiveUI` (are you missing an assembly reference?)

Previous version such as `14.3.10` work as expected.

**Steps To Reproduce**

1. Create a new Android application with the new sdk project format targeting `net6.0-android`
2. Add reference to `ReactiveUI` version `15.1.1`
3. Go to the main activity and paste the following code at the end of the `OnCreate` method or try to find android specific code
```csharp
ReactiveUI.ControlFetcherMixin.WireUpControls(this);
```
4. Get the error!

**Expected behaviour**

It should find and use the mixin and all android specific code.

**Screenshots**

![image](https://user-images.githubusercontent.com/20771798/130336371-87a8938e-6085-4c93-87f7-22a9369289e3.png)

**Environment**

- OS: Windows10 
- Version: 21H1 
- Device: Desktop 
- ReactiveUI Version: 15.1.1

**Additional context**

Other libraries such as `ReactiveUI.AndroidX` have the same problem and there it finds the class on the editor only to show the error

> Reference to type 'ControlFetcherMixin.ResolveStrategy' claims it is defined in 'ReactiveUI', but it could not be found

![image](https://user-images.githubusercontent.com/20771798/130336580-ac7f80f3-c803-4d75-a65e-ee732997a1d3.png)

**Comment by glennawatson** [comment]
This should be fixed with a pr that went in today
