### ISSUE TITLE
[BUG] BindCommand isn't executed on Dispatcher in UWP in version 16.1.1

### ISSUE THREAD

**Issue by Sempek** [reactiveui/ReactiveUI#2905]
ReactiveCommand errors on execute in UWP app using version 16.1.1 - no error in Android or IOS.  
Same code exhibits no error in 15.1.1.

Do the following to reproduce:
In VIew:  
```
 <Button x:Name="PickFileButton" Text="Pick a File" Command="{Binding}"/>
```

    this.BindCommand(
        this.ViewModel,
        x => x.LoadFileCommand,
        x => x.PickFileButton
        );

In ViewModel:
```
     LoadFileCommand = ReactiveCommand
            .CreateFromObservable(
            () =>Observable.Create<Unit>(
                  async _=>
                  {
                    var fileResult = await FilePicker.PickAsync();
                    if (fileResult != null)
                    {
                      Debug.WriteLine($"FileName = {fileResult.FileName}");
                    }
                    return Disposable.Empty;
                  }));
    public ReactiveCommand<Unit, Unit> LoadFileCommand { get; private set; }
```

Executing in UWP results in the following exception:
The application called an interface that was marshalled for a different thread. (Exception from HRESULT: 0x8001010E (RPC_E_WRONG_THREAD))

**Comment by glennawatson** [comment]
Use the nuget package `reactiveui.uwp` which was added to support winui3

**Comment by glennawatson** [comment]
I will be adding extra documentation about this though to make it obvious to users.
