### ISSUE TITLE
[BUG] After updating ReactiveUI.XamForms to 16.1.1 bug with android -Android.Util.AndroidRuntimeException: 'Animators may only be run on Looper threads'"

### ISSUE THREAD

**Issue by draganDBL** [reactiveui/ReactiveUI#2907]
**Describe the bug**
After updating  ReactiveUI.XamForms to 16.1.1 android app crash after  executing command (e.g Button login click ).
Before on version 14.3.1 it was working 

Android target version is 10, android min version is 10
 

**Steps To Reproduce**

**Expected behaviour**

**Screenshots**

**Environment**

- OS:       
- Version   
- Device:   
- ReactiveUI Version:    

**Additional context**

**Comment by ChrisPulman** [comment]
@draganDBL May I ask for an example of your command or a small repo demonstrating the issue. I have tried to run our integration tests and our Samples both of which are using `ReactiveCommand.CreateFromObservable` neither of these are presenting any issues.

**Comment by draganDBL** [comment]
Hi @ChrisPulman 
 public ReactiveCommand<Unit, Unit> DeviceInfoDialogCommand { get; set; } 


DeviceInfoDialogCommand = ReactiveCommand.Create((() =>
            {
                INavigation navigation = new NavigationProxy();
                navigation.PushPopup(new DeviceInfoDialogPage()).Subscribe();

            }));
 and my  
 MainThreadScheduler = mainThreadScheduler ?? RxApp.MainThreadScheduler;  is a DefaultScheduler
 
![screenshot_1 (1)](https://user-images.githubusercontent.com/49031585/133065287-0becfd8a-72db-4602-b41b-76ef3a46ed4c.png)

**Comment by ChrisPulman** [comment]
Thanks very much for this additional information,  we will continue to try and find the issue. The following registration is setting up the RxApp.MainThreadScheduler as you had expected.
src/ReactiveUI/Platforms/android/PlatformRegistrations.cs
Would you be able to list the ReactiveUI packages used in your Android project.

**Comment by draganDBL** [comment]
List  on references I'm using in Android Proj.
```
<ItemGroup>
    <PackageReference Include="AutoMapper">
      <Version>10.1.1</Version>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json">
      <Version>13.0.1</Version>
    </PackageReference>
    <PackageReference Include="ReactiveUI">
      <Version>15.1.1</Version>
    </PackageReference>
    <PackageReference Include="ReactiveUI.Events.XamForms">
      <Version>15.1.1</Version>
    </PackageReference>
    <PackageReference Include="ReactiveUI.Fody">
      <Version>15.1.1</Version>
    </PackageReference>
    <PackageReference Include="ReactiveUI.Testing">
      <Version>15.1.1</Version>
    </PackageReference>
    <PackageReference Include="ReactiveUI.Validation">
      <Version>2.1.1</Version>
    </PackageReference>
    <PackageReference Include="ReactiveUI.XamForms">
      <Version>15.1.1</Version>
    </PackageReference>
    <PackageReference Include="Realm">
      <Version>10.5.0</Version>
    </PackageReference>
    <PackageReference Include="Rg.Plugins.Popup">
      <Version>2.0.0.12</Version>
    </PackageReference>
    <PackageReference Include="RxUI.Plugins.Popup">
      <Version>0.4.0</Version>
    </PackageReference>
    <PackageReference Include="Xam.Plugin.DeviceInfo">
      <Version>4.1.1</Version>
    </PackageReference>
    <PackageReference Include="Xam.Plugin.Media">
      <Version>5.0.1</Version>
    </PackageReference>
    <PackageReference Include="Xam.Plugins.Settings">
      <Version>3.1.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Essentials" Version="1.7.0" />
    <PackageReference Include="Xamarin.FFImageLoading.Forms">
      <Version>2.4.11.982</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.FFImageLoading.Transformations">
      <Version>2.4.11.982</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Forms.PancakeView">
      <Version>2.3.0.759</Version>
    </PackageReference>
    <PackageReference Include="ZXing.Net.Mobile">
      <Version>2.4.1</Version>
    </PackageReference>
    <PackageReference Include="ZXing.Net.Mobile.Forms">
      <Version>2.4.1</Version>
    </PackageReference>
  </ItemGroup>
```

**Comment by draganDBL** [comment]
@ChrisPulman  My thinking is that somehow the project is referencing a NetStandard2.0 version of ReactiveUI and therefor will set RxApp.MainThreadScheduler = DefaultScheduler.Instance;,
Is it possible to change this ?

**Comment by glennawatson** [comment]
Update to android 11 to match Google's requirement here https://developer.android.com/distribute/play-policies

**Comment by glennawatson** [comment]
So you probably just need to update the csproj and the manifest XML file to update the targetting version. Believe you can still have the minimum below 11 though.
