### ISSUE TITLE
[BUG] [WPF] Problems with default ActivationForViewFetcher when upgrade from 13.3.2 to 14.1.1

### ISSUE THREAD

**Issue by HavenDV** [reactiveui/ReactiveUI#2912]
**Describe the bug**
In WPF, when creating any form, an exception is thrown in the constructor after calling the `this.WhenActivated` extension :
System.ArgumentException: 'Don't know how to detect when Dedoose.Views.MainView is activated/deactivated, you may need to implement IActivationForViewFetcher'
The same behavior is repeated when updating to the latest version 16.2.1

**Screenshots**
![image](https://user-images.githubusercontent.com/3002068/131489664-2292234a-a129-450a-835a-fbd367b34d86.png)

**Environment**
- ReactiveUI Version: 14.1.1

**Comment by glennawatson** [comment]
Question I assume you have the wpf nuget package installed.

**Comment by HavenDV** [comment]
Sorry, the problem is trivial - I updated the ReactiveUI for the main library and forgot to update for the WPF project.

**Comment by HavenDV** [comment]
Small bug in 16.2.1:
PropertyBindingMixins.OneWayBind shows a nullable warning when using a selector function and a vm property that is not marked nullable.
```cs
public static IReactiveBinding<TView, TOut> OneWayBind<TViewModel, TView, TProp, TOut>(this TView view, TViewModel? viewModel, Expression<Func<TViewModel, TProp?>> vmProperty, Expression<Func<TView, TOut>> viewProperty, Func<TProp?, TOut> selector)
```
I'm assuming you don't need `?` for `TProp`
