### ISSUE TITLE
[BUG] Poco type warning when using ReactiveUI bindings in the WPF view

### ISSUE THREAD

**Issue by kgday** [reactiveui/ReactiveUI#2957]
**Describe the bug**

Bindings on the view using the this.Bind<whatever>() methods emits POCO warnings

**Steps To Reproduce**

Example:
```
this.OneWayBind(ViewModel, vm => vm.ToolBarViewModel, v => v.ToolBarHost.ViewModel).DisposeWith(d);
```
Emits a warning:

`The class MyApp.Views.MainWindow property ToolBarHost is a POCO type and won't send change notifications, WhenAny will only return a single value!`

another example:
```
//MapsDropDownButton is a WPF ToggleButton
this.Bind(viewModel, vm => vm.IsMapViewDroppedDown, v => v.MapsDropDownButton.IsChecked).DisposeWith(d);
```
emits the warning:
`The class MyApp.Views.ToolBarView property MapsDropDownButton is a POCO type and won't send change notifications, WhenAny will only return a single value!`
**Expected behaviour**

No warnings for ordinary reactiveui type bindings

**Screenshots**

**Environment**

- OS:        Windows 10
- Version   
- Device:   
- ReactiveUI Version:     16.2.6

**Additional context**

**Comment by glennawatson** [comment]
Is ToolBarHost.IsChecked a DependencyProperty or a INotifyPropertyChanged property. This error is telling you it's neither and therefore not a true TwoWayBind

**Comment by kgday** [comment]
And the end property of those controls are all dependency property

**Comment by kgday** [comment]
The toolbarhost is a Reactiveui ViewModelViewHost.

**Comment by kgday** [comment]
Quick repo comming up

**Comment by kgday** [comment]
[beeswallLocalService.zip](https://github.com/reactiveui/ReactiveUI/files/7309382/beeswallLocalService.zip)
Basic example, just with textblocks, TextBoxes and a checkbox.  Warnings are produced.

**Comment by glennawatson** [comment]
This is due to the WPF generating fields for the generated file based on the `x:Name`. We are unlikely to fix this one anytime soon and the warning is safe to ignore in this scenario.
