### ISSUE TITLE
OneWayBinding selector

### ISSUE THREAD

**Issue by RomanSoloweow** [reactiveui/ReactiveUI#3003]
The selector specified by the OneWayBinding is executed once. It seems to me this is not entirely obvious behavior.

![image](https://user-images.githubusercontent.com/29205560/140664521-cfddcea3-a8ad-465d-b829-b8fa50db149b.png)

It would be more obvious to perform this transformation in one of two cases:
1. When changing a property
2. At the moment of calling the command

I am not suggesting that we need to change the current behavior, I think we could extend the API to make the new behavior possible.

**Comment by glennawatson** [comment]
It gets called when the property changes. You have a list though so the property is never likely to change just the contents of the list. 

You'll likely want to look into dynamic data.

**Comment by RomanSoloweow** [comment]
@glennawatson 

I would agree with you, but it seems that I am doing everything right

![image](https://user-images.githubusercontent.com/29205560/140666147-456bc84f-4e5b-47c5-a5a9-37501a50a186.png)

+ if try to use SelectedElements with a [converter](https://github.com/AvaloniaUI/Avalonia/blob/7842883961d094e08e9def7f30cf32fd573179c7/src/Avalonia.Base/Data/Converters/IValueConverter.cs) in xaml [Avalonia](https://github.com/AvaloniaUI/Avalonia) everything works correctly and it **reacts to property changes** as expected

it seems the problem is something else
