### ISSUE TITLE
[BUG] ReactiveUI.Fody throws when propery with non-trivial getter is marked with ReactiveAttribute

### ISSUE THREAD

**Issue by mishun** [reactiveui/ReactiveUI#3013]
**Describe the bug**
Hi!

https://github.com/reactiveui/ReactiveUI/blob/22273171603cbbcf4332cefa8875917daef45b38/src/ReactiveUI.Fody/ReactiveUIPropertyWeaver.cs#L114-L117

`Single` here appears to throw `InvalidOperationException` if property getter touches any field other than one that it's supposed to get (or touches the field more than once). Also, are there any deep reasons to delete original field and replace it with identical one like that? It may cause very esoteric problems if anything else touches that field.

**Steps To Reproduce**
If you're curious about context the error appeared, F# compiler is a bit paranoid and sometimes emits runtime checks in property getters/setters. Following seems to be minimal example:
```F#
type ViewModel () as this =
    inherit ReactiveObject ()
    [<Reactive>] member val MyCoolString = "" with get, set
```

**Expected behaviour**

Not to do that :)
Or at least sensible error message.

**Environment**
Tested with
```
    <PackageReference Include="ReactiveUI" Version="16.3.5" />
    <PackageReference Include="ReactiveUI.Fody" Version="16.3.5" />
```

**Comment by glennawatson** [comment]
I was mid way doing a rewrite and wasn't replacing the get field. We aren't focusing on getting that rewrite done for a little while now though but will keep this issue open to track to make sure we keep the field when we get back to it n

**Comment by ChrisPulman** [comment]
We are now focusing on Source Generators instead of Fody. Please try them and see if they help you, ReactiveUI.SourceGenerators

**Comment by ChrisPulman** [comment]
As Fody is no longer a feature we are developing I will close this, many thanks

**Comment by mishun** [comment]
@ChrisPulman as far as I can see, new attribute can only be put onto a field, but not onto a property. Is that limitation is by design, or property variant is just not implemented yet (in latter case I can take a stab at it)?

**Comment by ChrisPulman** [comment]
The limitation currently is with source generators, currently there is no partial property and as we can only generate code not replace as Fody could, we need to apply the decorators to an element that will be part of the end code.
As soon as I can make a release there will be a code fix to change a property into a field with a [Reactive] decorator, hopefully this will aid the transition. If you have an AI available I found that it learned fairly quickly about the change from Fody to Source Generators and provided a fix for large classes of Fody decorators on properties to SG decorators on fields.
Apparently the next version of SG's will support  Properties too, so as soon as this is available I will add the relevant support, assuming that it works and is actually released this time. I understand that the partial property is being targeted for release alongside dotnet 9.0

**Comment by mishun** [comment]
Thank you for the explanation!
