### ISSUE TITLE
MAUI thread marshalling error for WinUI3

### ISSUE THREAD

**Issue by aschaefer94** [reactiveui/ReactiveUI#3020]
BUG:
In a new .NET Maui project, attempting to navigate using a command will cause a thread marshalling error. This bug seems to be the same as #2993. The most recent version included a pull request to try to fix it, but it does not seem to be fixed, as I am still hitting the same issue.

REPRO:
Create a new MAUI project and install the latest ReactiveUI package (16.3.10), as well as the matching ReactiveUI.Maui package (16.3.10). Create a command to execute navigation similar to this:

public ReactiveCommand<Unit, Unit> NavigateCommand = ReactiveCommand.Create(Navigate); 
private void Navigate()
{
     var viewModel = new ViewModel();
     Router.Navigate.Execute(viewModel);
}

**Expected behaviour**
Navigate to the expected View Model and it's registered page without issue.

**Environment**

- OS:       Windows 
- Version   10.0.19041
- ReactiveUI Version:  16.3.10

**Comment by aschaefer94** [comment]
@glennawatson here is the issue we talked about in the slack channel regarding dispatcher in MAUI for windows. Thanks!

**Comment by schnerring** [comment]
Having the same issue. Executing any `ReactiveCommand` via `Execute()` or `InvokeCommand()` ends up executing on the wrong thread, too.

I tried using `ObserveOn(RxApp.MainThreadScheduler)` to no avail.

**Comment by DonSagiv** [comment]
> Having the same issue. Executing any `ReactiveCommand` via `Execute()` or `InvokeCommand()` ends up executing on the wrong thread, too.
> 
> I tried using `ObserveOn(RxApp.MainThreadScheduler)` to no avail.

I fixed this problem by installing https://www.nuget.org/packages/ReactiveUI.WinUI/ on NuGet. This will only target the Windows platform (the other platforms will not have the package installed).

![devenv_XA9pV6kEKr](https://user-images.githubusercontent.com/13925038/168490011-80805a0c-e7dd-4178-9b28-9930c02bb0e4.png)

**Comment by ChrisPulman** [comment]
Fixed by #3306
