### ISSUE TITLE
[BUG] Unhandled `OverflowException` from a Textbox Data bound to a Nullable Integer Property

### ISSUE THREAD

**Issue by WalkerCodeRanger** [reactiveui/ReactiveUI#3021]
*Note:* this is similar to but different from issue #3000 that I filed recently. That bug was for `int`. This bug is for `int?` and exists in ReactiveUI v16.3.10

**Describe the bug**
Databinding a textbox to an `int?` causes an unhandled `OverflowException` when the user enters an out of range number (i.e. bigger than `int.MaxValue` or smaller than `int.MinValue`). This is inconsistent with the behavior when the user enters a non-integer value (e.g. "hello", or "3a4") or when databinding to an `int`.

**Steps To Reproduce**

1. Have a property in your view model that is an `int?`.
    ```csharp
    public class ExampleViewModel : ReactiveObject
    {
        [Reactive]
        public int? Percentage { get; set; };
    }
    ```
2. Bind that property to the text of a textbox in your view.
    ```csharp
    public ExampleView : ReactiveControl<ExampleViewModel>
    {
        public ExampleView()
        {
            InitializeComponent();
            this.WhenActivated(d =>
            {
                this.Bind(ViewModel, vm => vm.Percentage, v => v.PercentageTextBox.Text).DisposeWith(d);
            });
        }
    }
    ```
3. Add an event handler to the application dispatcher unhandled exception event.
    ```xaml
    <Application x:Class="Example.App"
                 xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                 xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                 Startup="Application_Startup"
                 DispatcherUnhandledException="Application_DispatcherUnhandledException">
        <Application.Resources>
        </Application.Resources>
    </Application>
    ```
    ```csharp
    public partial class App : Application
    {
        private void Application_DispatcherUnhandledException(object sender, DispatcherUnhandledExceptionEventArgs e)
        {
            // TODO report the exception to the user somehow
        }
    }
    ```
4. Run the app and enter a value larger than `int.MaxValue` into the textbox.

When step 4 is done, the unhandled exception handler will be called with an `OverflowException` from the attempt to parse the input string into an `int`.

**Expected behavior**
No unhandled exception. The view model property is unchanged.

When a user enters a non-integer value (e.g. "3a4"), there is no unhandled exception. The view model property is not changed. I would expect the same to happen in this case. 

**Environment**
- OS:       Windows 10 Pro
- Version: 10.0.19043 Build 19043
- Device:   Dell Laptop, Vostro 7590
- ReactiveUI Version:    16.3.10

**Additional context**
- .NET Framework 4.8
- WPF

**Comment by glennawatson** [comment]
Sounds like the converter @ChrisPulman added just needs to be extended to handle nullable int etc
