### ISSUE TITLE
[BUG] Call is ambiguous for System.Reactive.Linq.DispatcherObservable.ObserveOnDispatcher

### ISSUE THREAD

**Issue by pedromcrocha** [reactiveui/ReactiveUI#3084]
After upgrading to version 17.* when I use ObserveOnDispatcher in code, I have this error

Error	CS0121	The call is ambiguous between the following methods or properties: 'System.Reactive.Linq.DispatcherObservable.ObserveOnDispatcher<TSource>(System.IObservable<TSource>)' and 'System.Reactive.Linq.DispatcherObservable.ObserveOnDispatcher<TSource>(System.IObservable<TSource>)'	

**Steps To Reproduce**
update to 17.*
i try from 17.013 to 17.1.4

Environment
OS: Windows 10 or 11
ReactiveUI Version: 17.*
ReactiveUI.Fody Version: 17.*
ReactiveUI.WPF Version: 17.*

Platform windows CS/VB

**Comment by ChrisPulman** [comment]
What platform is your application using?
Do you have a Repo or test showing the issue?

**Comment by glennawatson** [comment]
Are you using net 6? We removed net 5 support.

**Comment by pedromcrocha** [comment]
i use .net framework 4.8

**Comment by ChrisPulman** [comment]
Please change `ObserveOnDispatcher()` to `ObserveOn(RxApp.MainThreadScheduler)`

**Comment by pedromcrocha** [comment]
changing ObserveOnDispatcher() to ObserveOn(RxApp.MainThreadScheduler) resolves the error thx.

**Comment by glennawatson** [comment]
Chris suggestion is correct but there's also a bug which I pushed a pr for.
