### ISSUE TITLE
[BUG] Broken initialization >=17.0.1

### ISSUE THREAD

**Issue by tomasfil** [reactiveui/ReactiveUI#3090]
**Describe the bug**

After upgrading from 16.3.10 to literally anything over 17.0.1 this breaks (Last working version: 16.4.1):
![image](https://user-images.githubusercontent.com/34779382/144860610-23d0d356-d530-49e8-97ca-dd3b87d5ce30.png)

**Expected behaviour**

Normal creation of command.

**Screenshots**

![image](https://user-images.githubusercontent.com/34779382/144860826-197fecdb-4195-4c77-baf9-b9a03daff04f.png)

**Environment**

- OS:       Windows
- Version   20H2
- Device:   
- ReactiveUI Version:    17.1.4

**Comment by tomasfil** [comment]
If I comment that code off, then this break:
![image](https://user-images.githubusercontent.com/34779382/144863804-4ce82d6a-8477-4c22-bd60-a9b4b13c8a82.png)

Something is very off in versions over 17.0.1

**Comment by tomasfil** [comment]
Maybe this has something to do with it?
```
warning NU1701: Package 'ReactiveUI.WPF 17.1.4' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0-windows7.0'. This package may not be fully compatible with your project.
warning NU1701: Package 'ReactiveUI.WPF 17.1.4' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0-windows7.0'. This package may not be fully compatible with your project.

```

**Comment by tomasfil** [comment]
When did you drop support for NET5?
https://github.com/reactiveui/ReactiveUI/blob/main/src/ReactiveUI.Wpf/ReactiveUI.Wpf.csproj

**Comment by tomasfil** [comment]
Dropped NET5 support as breaking change. Didnt see it anywhere posted.

**Comment by ChrisPulman** [comment]
https://github.com/reactiveui/ReactiveUI/releases#:~:text=e4b578a%20breaking%3A%20Remove%20Net5/NetCoreApp3.1/Net461%20FrameworkTarget%27s%20(%233062)%20%40ChrisPulman

**Comment by ChrisPulman** [comment]
Support for Net 5 was dropped as a breaking change hence the step to V17, as all new packages being released no longer support Net 5 we were forced to drop this Target. Please update to Net 6 to use versions > V16

**Comment by glennawatson** [comment]
Bumped the version number. Prefixed the pr with breaking to make it more obvious in the release notes. Had a issue opened and closed.
