### ISSUE TITLE
[Document Enhance] ReactiveWindow with other UI frameworks(such as MahApps.Metro)

### ISSUE THREAD

**Issue by LeiYangGH** [reactiveui/ReactiveUI#3095]
`reactiveui:ReactiveWindow` is convenient, but since it is a base class, it cannot directly work with other UI frameworks that also requires a base class, take [MahApps.Metro](https://mahapps.com/) for example, it needs the window to be 
`mah:MetroWindow`, while reactive ui needs `reactiveui:ReactiveWindow`, they cannot exist at the same time.

I know `reactiveui:ReactiveWindow` is not the only way to enable reactiveui, and I can manually implement IViewFor<TViewModel> myself, but the document didn't metion such conflict senarios and any ways to let them coexists?

Thanks!

**Comment by glennawatson** [comment]
Best to open this one in the website repo.
