### ISSUE TITLE
[BUG] WhenAnyValue might not send latest value

### ISSUE THREAD

**Issue by erikm-g** [reactiveui/ReactiveUI#3122]
**Describe the bug**
If a subscription is started for changes on a property using WhenAnyValue and the property is updated on another thread at approximately the same time, WhenAnyValue might send the old value as the initial value in the observable sequence and not send the updated value at all. 

**Steps To Reproduce**
Let one thread update a property and set up a subscription on changes for it from another. This unit test illustrates the problem. It passes most of the times, but if repeated often enough it will eventually fail. The value of anyReactiveObject.Value will be 2 but no call to the subscription is emitted.
´´´
    private class SomeReactiveObject : ReactiveObject
    {
        private int value;

        public int Value
        {
            get => value;
            set => this.RaiseAndSetIfChanged(ref this.value, value);
        }
    }

    [Test]
    [Repeat(10000)]
    public async Task WhenAnyShouldBeThreadSafe()
    {
        var anyReactiveObject = new SomeReactiveObject { Value = 1 };
        var task = Task.Run(() => anyReactiveObject.Value = 2);
        bool found = false;
        anyReactiveObject.WhenAnyValue(x => x.Value)
            .Where(v => v == 2).Subscribe(_ => found = true);
        await task;
        Assert.That(found);
    }
´´´
**Expected behaviour**
The test above should pass.
In a multithreaded environment, events may occur out of order, or if updates are very frequent some intermediate values might be missed, but the latest value should always be emitted to the pipeline.

**Environment**
- OS:  Windows 10
- Device:  PC
- ReactiveUI Version:  16.2.6

**Comment by kmgallahan** [comment]
Isn't this just a standard race condition?

Both threads are running in parallel and nothing is stopping the subscription from being setup before the Task has completed.

**Comment by erikm-g** [comment]
If the task completes before the subscription is setup, WhenAnyValue emits 2 and the test passes.
If the subscription is setup before the task starts to execute WhenAnyValue will emit first 1 and then 2 and the test passes.
If the task is executed at the same time as the subscription is setup, sometimes WhenAnyValue emits only the value 1 but the property's value is 2. This causes the test to fail.

**Comment by glennawatson** [comment]
There's a race condition in your Code. The task will start immediately which may or may not be before the WhenAnyValue is registered. 

Try converting your task into a Func<Task> and making it into a function you call after the WhenAnyValue is registered and then await that.

**Comment by kmgallahan** [comment]
@glennawatson I tested this code:

```cs
public MainWindowViewModel()
{
    var i = 1000;
    do
    {
        i--;
        WhenAnyShouldBeThreadSafe();
    } while (i > 0);
}

public void WhenAnyShouldBeThreadSafe()
{
    var anyReactiveObject = new SomeReactiveObject { Value = 1 };
    Task.Run(() => anyReactiveObject.Value = 2);
    anyReactiveObject.WhenAnyValue(x => x.Value)
        .Subscribe(x =>
        {
            if (anyReactiveObject.Value is 1) Debug.WriteLine(anyReactiveObject.Value);
        });
    }
}

public class SomeReactiveObject : ReactiveObject
{
    public int Value
    {
        get => value;
        set => this.RaiseAndSetIfChanged(ref this.value, value);
    }

    private int value;
}
```

In theory `1` should never be written to debug out because the subscription is always made after ` var anyReactiveObject = new SomeReactiveObject { Value = 1 };`. However, in the 1000 runs it does show up multiple times for me...

**Comment by glennawatson** [comment]
`Task.Run(() => anyReactiveObject.Value = 2); // This can run or not run before the WhenAnyValue happens, use a Func<Task>`
    anyReactiveObject.WhenAnyValue(x => x.Value)
        .Subscribe(x =>
        {
            if (anyReactiveObject.Value is 1) Debug.WriteLine(anyReactiveObject.Value);
        });

**Comment by kmgallahan** [comment]
@glennawatson Without `Task.Run(() => anyReactiveObject.Value = 2);` the observable / subscription should never fire because it happens after the value is assigned here `var anyReactiveObject = new SomeReactiveObject { Value = 1 };`, correct?

That would mean Value = 1 should never show up in the observable / subscription (be sent to debug out), or am I missing something?

**Comment by glennawatson** [comment]
`Func<Task> myFancyValueChanger = () => Task.Run(() => .... `

`something.WhenAnyValue(x => ....`
`await myFancyValueChanger.Invoke();`

**Comment by kmgallahan** [comment]
@glennawatson 

Ignoring all of the code above - from my understanding, just these 2 lines of code should never fire the subscription, correct?

```cs
anyReactiveObject.Value = 1;
anyReactiveObject.WhenAnyValue(x => x.Value).Subscribe(x => Debug.WriteLine(anyReactiveObject.Value));
```

So value = 1 should **never** show up in the debug output.

This code however will very seldomly show 1 in the debug output:

```cs
anyReactiveObject.Value = 1;
Task.Run(() => anyReactiveObject.Value = 2);
anyReactiveObject.WhenAnyValue(x => x.Value).Subscribe(x => Debug.WriteLine(anyReactiveObject.Value));
```

I can't reason as to why 1 should ever show up, but it does.

**Comment by glennawatson** [comment]
You don't control when Task.Run runs, it's up to the task scheduler

**Comment by kmgallahan** [comment]
@glennawatson 

I understand there is a race condition happening.

In this race condition there should be two scenarios:

1. Value is set to 2 **BEFORE** the subscription is setup, so the subscription is called printing 2 to the output
2. Value is set to 2 **AFTER** the subscription is setup, so nothing is printed to the output

There should be no scenario 3:

3. Value is set to 2 **BEFORE** the subscription is setup, the subscription prints **1** to the output

But that 3rd scenario does indeed occur 5-10 times out of 1000.

@RLittlesII Can you sanity check me here?

**Comment by glennawatson** [comment]
`WhenAnyValue` always emits the current initial value of the Property unless you do a Skip(1)

**Comment by glennawatson** [comment]
Scenario 3 can happen

1. Initial Value is 1
2. Task sets value to 2
3. WhenAnyValue grabs initial value of property and emits 2

**Comment by RLittlesII** [comment]
@kmgallahan 
> There should be no scenario 3:

> Value is set to 2 AFTER the subscription is setup, the subscription prints 1 to the output
But that 3rd scenario does indeed occur 5-10 times out of 1000.

The fact you are using `Task.Run` by definition means you are not in control of **when** it is set.  Asynchronous code does not happen where you write the line of code.  It happens at some point in the future.

**Comment by kmgallahan** [comment]
Sorry guys, didn't know it emitted the initial value on setup, please forget I ever existed, lol

I checked the docs [here](https://www.reactiveui.net/docs/handbook/when-any/#whenanyvalue) when I first saw this issue and it only mentions things like this for a while:

> This returns an observable that yields the current value of Foo each time it changes:

> You can Subscribe to the observable returned by the WhenAny variant and get notifications whenever the value changes.

Funny thing is I've been using it for months now...

**Comment by glennawatson** [comment]
I was just reading the docs so I could link you to them and thought the fact they emit the initial value wasn't very well described. If I get time I'll make it more obvious today.

**Comment by glennawatson** [comment]
FYI https://github.com/reactiveui/website/pull/745

**Comment by kmgallahan** [comment]
@glennawatson 

Thanks for the quick update.

I remember now why I assumed the initial value wasn't emitted for months - the [IntelliSense descriptions](https://github.com/reactiveui/ReactiveUI/blob/main/src/ReactiveUI/VariadicTemplates.cs) read:

> WhenAnyValue allows you to observe whenever the value of a property on an object has changed, providing an initial value when the Observable is set up

Yet during my first tests that seemed to not be happening, so I just thought: ¯\\_(ツ)\_/¯ I guess the docs are wrong.

Now I realize I must have only been testing it where the initial values were null, which is a significant gotcha.

I'd suggest that text be updated as well.

**Comment by erikm-g** [comment]
@glennawatson There is no race condition between setting the value to 1 and 2. There is a race condition between setting the value to 2 and setting up the subscription; that's the whole point of the test. To make the simplest possible code where some property is updated on another thread at the same time as a subscription is started. If the update occurs first, 2 should be emitted as the initial value. If the subscription is set up first 1 should be emitted as the initial value and 2 as an updated value. What causes the test to fail is that 2 is not emitted at all. If you close this bug saying that this is expected behavior you should really update the documentation to say that reactive UI should not be used for multi threaded applications.

**Comment by kmgallahan** [comment]
3 lines of code:

1. Set Value = 1 on Thread A
2. Run Task to set Value = 2 on a Thread B
3. Subscribe on Thread A and print Value to debug 

The race condition is that nothing prevents code line 3 from running before code line 2, they are separate threads.

If line 3 runs before line 2, then Value is still equal to 1 at the time the subscription is setup.

**Comment by erikm-g** [comment]
It is actually 5 lines of code:
 1. Set Value = 1 on Thread A
 2. Run Task to set Value = 2 on a Thread B
 3. Subscribe on Thread A and check if value is 2
 4. Await the task started in step 2 so that we know that the value has been set to 2 before continuing to step 5. Since no other code is updating the value, it must be equal to 2 now.
 5. Assert to check if Value has ever been 2. Assert fails (sometimes)

I don't care about the order things are happening and I don't care if I ever receive the value 1. I am subscribing to the initial value and every future updates on it, the subscription is still active, the value is currently 2 and the PropertyChanged event handler has finished executing, so I expect to have received the value 2 at some point on some thread.

**Comment by erikm-g** [comment]
I know how await and Task.Run works. When await task returns I know that the task has completed, that is what is important here. I want the task and setting up the subscription to be run in parallel in this test since that is what is triggering the error. In my real application it is a completely different part of the code running on a different thread updating the value. This is just a very simple example of reproducing the behavior of a multi threaded application where my WhenAnyValue subscriptions does not trigger if the value is updated at the same time as the subscription is set up.

**Comment by erikm-g** [comment]
That is not the issue. The problem is that the value 2 is never emitted. I can change the bool to an int, increment it with Interlocked.Increment in the subscription and add a memory barrier before my assert, it is still the same error. The lambda passed to subscribe is simply never executed.

**Comment by kmgallahan** [comment]
> The problem is that the value 2 is never emitted.
> The lambda passed to subscribe is simply never executed.

I have no idea what you are talking about now. If the lamba didn't execute then why does this print to console?

```cs
anyReactiveObject.WhenAnyValue(x => x.Value).Where(v => v == 2).Subscribe(_ => Debug.WriteLine("Hello World!"));
```

**Comment by RLittlesII** [comment]
@erikm-g Have you considered using [Synchronize](https://reactivex.io/documentation/operators/serialize.html) to ensure that the observables from multiple threads are received correctly?

**Comment by kmgallahan** [comment]
You may think there are cases where the lamba isn't being executed because the `Assert` shows `found` is false.

Each one of those cases is because bool isn't thread safe. Yes, when you `Assert.That(found);` the task has completed, but if the bool was set to `true` in the lambda on a different thread then it may or may not be true on the original thread at the time of the assertion - it isn't thread safe so this isn't a deterministic check.

**Comment by kmgallahan** [comment]
Also, in your original codebase initial values won't be emitted (the lamba won't be executed) if you use `WhenAnyValue(x.y.z).Subscribe` and x or y is null at the time of the subscription. That may be throwing you off as well.
