### ISSUE TITLE
[BUG] Constant crash when using ReactiveCommand

### ISSUE THREAD

**Issue by ccornici** [reactiveui/ReactiveUI#3124]
**Describe the bug**

See title.

I'm using 13.3.2 bcuz 17.1.9 is also broken (but with a different err). See here https://github.com/reactiveui/ReactiveUI/issues/3123

**Steps To Reproduce**

(might be removed if u read this in the future)
https://github.com/ccornici/reactive_ui_bug_1/tree/master
Read the README

**Expected behaviour**

Not crash

**Screenshots**

![image](https://user-images.githubusercontent.com/15718751/147290973-698745f6-c45b-4c50-8f0d-1556dde987ac.png)

**Environment**
OS: Win 10
Version 10.0.19043 Build 19043
Device:
ReactiveUI Version: 13.3.9, Fody & WPF

**Additional context**

I've used the same code in other apps, idk how come now it keeps crashing .....

**Comment by glennawatson** [comment]
Do you have the ReactiveUI.Wpf nuget package. 

Also we support net462 and net6 now. netcoreapp3.1 is not supported and there's a easy upgrade path to net6. Net6 is also long term support replacement of netcoreapp3.1

**Comment by ChrisPulman** [comment]
https://github.com/ChrisPulman/reactive_ui_bug_1
Please take a look at this, there is not an issue with ReactiveUI

**Comment by ccornici** [comment]
if you would have looked in the repo that reproduces it you would have seen that I have ReactiveUI.Wpf, yes

> Also we support net462 and net6 now. netcoreapp3.1 is not supported and there's a easy upgrade path to net6. Net6 is also long term support replacement of netcoreapp3.1

Interesting decision, given that VS 2019 doesn't even seem to work with 6.
But I guess VS 2019 is also not supported in this project?

**Comment by ccornici** [comment]
> https://github.com/ChrisPulman/reactive_ui_bug_1 Please take a look at this, there is not an issue with ReactiveUI
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/f177603ffc2ec2d914b944f221979ea1fec01f1fdc48ce5ba492ea47eb79e988/68747470733a2f2f6f70656e67726170682e6769746875626173736574732e636f6d2f636538313866633839643136363665613362613961366561636566626161653037313463383263353939343666613732396464666462353231313536383935302f436872697350756c6d616e2f72656163746976655f75695f6275675f31"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[GitHub - ChrisPulman/reactive_ui_bug_1](https://github.com/ChrisPulman/reactive_ui_bug_1)**Contribute to ChrisPulman/reactive_ui_bug_1 development by creating an account on GitHub.

You are pointing to a modified version of the repo with different packages.
I'm not sure what point ur trying to make here...
I can also show you that it works in different versions in other of my projects, How does that help?

Anyway, enjoy your time! I can work without this framework too, was just trying to help by reporting bugs.

**Comment by ChrisPulman** [comment]
![image](https://user-images.githubusercontent.com/4910015/147298299-f5936106-36e0-4bba-a5ba-73e1d93cdf1d.png)
As you can see the package versions are the same excepting the ReactiveUI ones which I have raised to the latest version suitable for your target framework, you had reported that it does not work in the latest version (17). 
I have however removed the packages that do not support the framework that you are attempting to target.
I have tried to assist you in showing you the best way to use ReactiveUI and the reason for the crash.

**Comment by ccornici** [comment]
Thanks! I appreciate you trying.

**Comment by glennawatson** [comment]
https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

NetCoreApp3.1 is ending at the end of next year.

Net 5 in the middle of next year.

Net 6 until end of 2024.

We decided to end the support early due to NuGet packages being released by Microsoft did not contain netcoreapp3.1 targets nor net5.0 targets.

**Comment by glennawatson** [comment]
Also net461 and earlier versions are being dropped April 2022 https://devblogs.microsoft.com/dotnet/net-framework-4-5-2-4-6-4-6-1-will-reach-end-of-support-on-april-26-2022/
