### ISSUE TITLE
[BUG] MemoryLeak with debugger attached.

### ISSUE THREAD

**Issue by tomasfil** [reactiveui/ReactiveUI#3132]
**Describe the bug**

Altought the memory leak without debugger was fixed:
https://github.com/reactiveui/ReactiveUI/issues/3091

There is still present memory leak when Debugger is attached. I am not really sure if it is ReactiveUI issue, or Visual studio issue.

**Steps To Reproduce**

https://github.com/tomasfil/ReactiveUI_Tests
Run MemoryLeak project with debugger in Visual Studio and wait.
(stopping the interval updates does not help)

**Expected behaviour**

No memory leak

**Environment**

- OS:       Windows 10
- ReactiveUI Version:    17.1.7

**Comment by glennawatson** [comment]
What version of visual studio

**Comment by tomasfil** [comment]
VS 2019 pro latest and also can confirm VS 2022 pro latest

**Comment by ammadislam6991** [comment]
Hi. Any update regarding this ? I am facing same issue in ReactiveUI Routing Sample. It's the simplest example but each time i navigate and go back memory usage keeps increasing and it never goes back to original state no matter how many times GC ran.

**Comment by glennawatson** [comment]
We won't get to this one until next month. Just real life unfortunately. Will be top of the list when we get back into action to test. 

I might test with vs2022 debugger since if it's a Microsoft bug be easier to track.

**Comment by ammadislam6991** [comment]
Thanks sir.

**Comment by rajeshwaranpj** [comment]
++

**Comment by rajeshwaranpj** [comment]
@tomasfil Is this a Microsoft bug too? and not RxUI?

**Comment by glennawatson** [comment]
Yeah unfortunately a Microsoft bug we tracked it down to.
