### ISSUE TITLE
[BUG] WinUI 3 ReactivePage<T> wont compile

### ISSUE THREAD

**Issue by tomasfil** [reactiveui/ReactiveUI#3169]
**Describe the bug**
Compiler generated code doesnt generate generic class, for ReactivePage, so the app wont launch after build and pops error.

**Steps To Reproduce**
https://github.com/tomasfil/ReactiveUI-WinUI-3-Tests
Clone and hit build.

**Expected behaviour**
**S**h**o**u**l**d **b**u**i**l**d**

**Screenshots**

![image](https://user-images.githubusercontent.com/34779382/151976651-fd9402c6-22aa-4371-9292-0be68bffe2b3.png)
![image](https://user-images.githubusercontent.com/34779382/151976687-1aebbfd6-7723-4c19-b572-f92a7474e50e.png)
![image](https://user-images.githubusercontent.com/34779382/151976718-c792667b-5b93-4154-abca-59c902a292c9.png)

**Environment**

- OS:       Windows 10
- ReactiveUI Version:    17.1.17

**Additional context**

**Comment by glennawatson** [comment]
You'll likely have to make a custom base class similar to what happens in uwp which doesn't support the typearguments tag either

**Comment by glennawatson** [comment]
Going to close this one since this is a bug with the  xaml implementation https://github.com/reactiveui/ReactiveUI/blob/51eb2c1fd2d438326cacd770944db066671ab7e9/src/ReactiveUI.Uwp/Common/ReactivePage.cs#L54
