### ISSUE TITLE
[BUG] WPF DataGrid memory leak

### ISSUE THREAD

**Issue by tomasfil** [reactiveui/ReactiveUI#3178]
**Describe the bug**

Memory leak when binding to DataGrid ItemsSource.

Not related to this: https://github.com/reactiveui/ReactiveUI/issues/3091
And yeah, its me again. Its like no one else is using RxUI with WPF or what :D

And also not related to this: https://github.com/reactiveui/ReactiveUI/issues/3132

**Steps To Reproduce**
Run this under any configuration: [ReactiveUI_DataGrid_MemoryLeak](https://github.com/tomasfil/ReactiveUI_Tests/tree/master/ReactiveUI_DataGrid_MemoryLeak)

**Expected behaviour**

Should not leak, everything is leaking on me, why always me lol? :D 

**Environment**

- OS:       Windows 10
- ReactiveUI Version:    Tested on NET5 16.4.15 and NET6 17.1.17

**Additional context**

As of other memory leak bug I would like to ask, if this get fixed, then please push the fix into NET5 version, since Oracle didnt fix their provider for NET6, so I cannot really upgrade to NET6 still.

**Comment by glennawatson** [comment]
One suggestion is to maybe use the WhenActivated pattern in your view model due to it using a lot of timers. Could potentially be leaks due to the timer object keeping your objects alive.

**Comment by tomasfil** [comment]
Hello @glennawatson, the repo is just to ilustrate the issue, not the actual use case

The ViewModel is only one and the timer is there, to simulate loading and removing data to table.
In my app user clicks Header and that loads Lines for a review, then another and another, that is the timer interval logic in ViewModel trying to simulate.

I did the repo just to strip any Database calls, converters in DataGrid, design styles etc. 

The issue seems to be the binding into DataGrid, since ItemsControl is fine with this approach, but I need the DataGrid for the table functionality.

**Comment by tomasfil** [comment]
Yeah I fully understand, there are plenty confusing parts of the life times of objects in base WPF, not daring to mention ReactiveUI.

But I think I have got that part handled and thats why I am posting it as Bug.

Seems like I have got talent on accidentally uncovering bugs

**Comment by tomasfil** [comment]
Acknowledged bug on WPF itself:
https://github.com/dotnet/wpf/issues/6087

**Comment by glennawatson** [comment]
Man we been getting a few of these type of issues lately where we think it's RxUI and turns into a Microsoft bug. Thanks for letting us know.
