### ISSUE TITLE
[BUG][Uno.WinUI] WhenActivated does not work

### ISSUE THREAD

**Issue by HavenDV** [reactiveui/ReactiveUI#3181]
**Steps To Reproduce**
[ReactiveUI.WinUI.WhenActivatedIssue.zip](https://github.com/reactiveui/ReactiveUI/files/8045229/ReactiveUI.WinUI.WhenActivatedIssue.zip)
Run `H.ReactiveUI.Apps.Uno.WinUI.Skia.Wpf.Host`. It throws:
```
System.ArgumentException: 'Don't know how to detect when H.ReactiveUI.Apps.Views.MainView is activated/deactivated, you may need to implement IActivationForViewFetcher'
```

**Expected behaviour**
`H.ReactiveUI.Apps.Uno.Skia.Wpf.Host` with the same code using ReactiveUI.Uno works correctly

**Screenshots**

**Environment**

- OS:       
- Version   
- Device:   
- ReactiveUI Version:    ReactiveUI.Uno.WinUI 17.1.17

**Additional context**

**Comment by HavenDV** [comment]
Past issue that was closed and didn't fix it: https://github.com/reactiveui/ReactiveUI/issues/3081

**Comment by glennawatson** [comment]
https://github.com/reactiveui/ReactiveUI/blob/8de9e98647ed1a0f1f27c45e39339e71fd5ab21f/src/ReactiveUI.Uno.WinUI/ReactiveUI.Uno.WinUI.csproj#L3

Due to the way winui works, there is no net472 target, nor a net6.0-windows target. Minimum had to be net6.0-windows10.0.17763.0. Got it to work but got other exceptions unrelated after that.

**Comment by HavenDV** [comment]
Uno.Skia.WPF uses .Net Standard 2.0. 
ReactiveUI.Uno.WinUI.csproj must not contain net6.0-windows10.0.17763.0

**Comment by glennawatson** [comment]
H.ReactiveUI.Apps.Uno.WinUI.Skia.Wpf.Host must be net6.0-windows10.0.17763.0

**Comment by glennawatson** [comment]
Most of ReactiveUI will break with just net6.0-windows due to System.Reactive not supporting it btw. https://github.com/dotnet/reactive/blob/6ff36f502d9239c72d7f3524752560b151cd7616/Rx.NET/Source/src/System.Reactive/System.Reactive.csproj#L3

So minimum is u

**Comment by glennawatson** [comment]
Target is minimum where you specify net6.0-windows is `net6.0-windows10.0.19041`

**Comment by HavenDV** [comment]
The PR was opened because its target is the same one that caused you to remove the UWP target from https://github.com/reactiveui/ReactiveUI/blob/main/src/ReactiveUI.Uno/ReactiveUI.Uno.csproj

Uno simply doesn't have such a TargetFramework. Because of this, applications that use ReactiveUI.Uno.WinUI try to use the wrong library.
ReactiveUI.Uno.WinUI just needs to use the same TargetFramework as Uno.WinUI
<img width="244" alt="image" src="https://user-images.githubusercontent.com/3002068/153528996-e8e7131b-f369-4172-bf3b-cf311f3c1aef.png">

**Comment by glennawatson** [comment]
Again, have you TRIED the fix

**Comment by glennawatson** [comment]
Like I need you to actually put some effort into your PRs, in the past you have a habit of submitting broken PRs and it's very obvious you put no effort into it, given you didn't even fill out the PR form.

**Comment by glennawatson** [comment]
Like if we need to make that change we will, but the project you are complaining about targets net6.0-windows that you say fails to run. Also you haven't done any of the basic PR form information or mentioned if you tried the modifications

**Comment by HavenDV** [comment]
What is the point of having net6.0-windows10.0.17763.0 TargetFramework in an Uno.WinUI project if it forbids using .Net Standard?

If you would give me more time, I would add more information to the PR. It makes no sense to close everything and everything without understanding.

**Comment by glennawatson** [comment]
try it please otherwise no PRs are happening.

**Comment by glennawatson** [comment]
RxUI in general doesn't have net6.0-maccatalyst so likely will need to be added throughout all the targeting apps.  So that's a larger body of work regardless.

**Comment by HavenDV** [comment]
> At the moment you have attempted to open PR way too early without any testing.
So you're mad at me for not testing the last PR enough? I admit, I made a mistake and did not take into account the fact that when building on CI, the package name was specified incorrectly. But at the same time, I tested everything locally. My only omission is that I did not try to build the package.
I apologize for wasting your time fixing this.

This time, I did a quick PR due to the fact that I have a lot of experience with the libraries for Uno and Uno.WinUI, and also saw yesterday's correspondence where another person was struggling with the same problem. I could add additional information to it at your request, or myself if you didn't immediately close it.
<img width="1447" alt="image" src="https://user-images.githubusercontent.com/3002068/153531770-059f8578-f6fe-46ec-a93a-bbe880d0cb66.png">

**Comment by HavenDV** [comment]
> Again, have you TRIED the fix

Your suggested fix will work for a Skia.WPF application. But this will not work for WebAssembly platform which uses net5/net6

**Comment by jeromelaban** [comment]
FYI,  targeting for ios/macos/catalyst is breaking again in .NET 6 Mobile Preview 13, and new builds will likely need to be created in order for everything to work properly (once Uno is updated to Preview 13).

As for the dependencies, unless there's a non-Uno winui package targeting only net6.0-windows.XX.XX (which can make sense) there may be cases where the TargetFramework for dependencies resolution may not work properly. 

@HavenDV If you can create a simple projects structure (with mostly empty projects and the required target frameworks) that demonstrates the issue and post it to the Uno repo, we can try to find a way to make the resolution work.

**Comment by HavenDV** [comment]
> As for the dependencies, unless there's a non-Uno winui package targeting only net6.0-windows.XX.XX (which can make sense) there may be cases where the TargetFramework for dependencies resolution may not work properly.

There is a separate WinUI package here - https://github.com/reactiveui/ReactiveUI/blob/main/src/ReactiveUI.WinUI/ReactiveUI.WinUI.csproj#L3

> @HavenDV If you can create a simple projects structure (with mostly empty projects and the required target frameworks) that demonstrates the issue and post it to the Uno repo, we can try to find a way to make the resolution work.

Ok, I will prepare an example like here, only in the standard Uno dotnet6 mobile template
