### ISSUE TITLE
Improve .net core 6 WinForms support

### ISSUE THREAD

**Issue by rallets** [reactiveui/ReactiveUI#3187]
Hi, related to some Slack threads with @glennawatson I would ask if it's possible to improve .net core 6 WinForms support.
I incurred in two issues:
1- in Dynamic Data the constant SUPPORTS_BINDINGLIST is not defined for net6.0-windows, hence the Bind method doesn't work (cc @RolandPheasant )
2- SelectedItems doesn't raise INotifyPropertyChanged, so .Bind is not able to react to the event

For 2) I'm now using as a "temporary replacement"
```
Observable.FromEventPattern(ev => lstItems.SelectedIndexChanged += ev, ev => lstItems.SelectedIndexChanged -= ev)
.Select(_ => lstItems.SelectedValue)
.BindTo(ViewModel, vm => vm.SelectedItem);
```
I have also built a demo app and I was wondering if it's something you could be interested in, to extend the examples in the `ReactiveUI.Samples](https://github.com/reactiveui/ReactiveUI.Samples/tree/main/winforms)` section. 
It's my first attempt using RxUI, so any feedback is really appreciated. 
The repo is [here](https://github.com/rallets/winforms-reactiveui-demo).

**Comment by glennawatson** [comment]
1. I did a release on the weekend. If you Bind(myBindingList) to an already created `BindingList` it should work now.

**Comment by glennawatson** [comment]
Don't use a `ReadOnlyObservableCollection<T>` instead use the BindingList direct is the trick with the Bind() method and WinForms net6

**Comment by glennawatson** [comment]
Definitely appreciate putting more content in the winforms samples section. Your sample looks good from what I can see.

**Comment by rallets** [comment]
Tks for the support, I made DynamicData working now. I'm glad to hear that you think I went for the right way. Tomorrow I will submit a PR to the samples repo with the same content.
