### ISSUE TITLE
Json serialization problem on System.Text.Json

### ISSUE THREAD

**Issue by VAllens** [reactiveui/ReactiveUI#3190]
`System.Text.Json` does not use the `System.Runtime.Serialization.IgnoreDataMember` attribute, it uses the `System.Text.Json.Serialization.JsonIgnore` attribute defined by itself.
Therefore, `Changing` and `Changed` and `ThrownExceptions` are serialized.

I have two suggestions: 
1. mark these three properties as `virtual` to allow subclasses to override them.
2. in the `ReactiveObject` and `ReactiveRecord` classes, add the `JsonIgnore` attribute to these three properties, but it needs to reference the `System.Text.Json` package.

FYI. :)

**Comment by VAllens** [comment]
I personally recommend the first option, which gives more flexibility while reducing the possibility of other dependencies.

**Comment by HugoRoss** [comment]
A quick check shows that there are other usages of the `IgnoreDataMember` in the repo:

- ReactiveUI\Platforms\android\ReactiveViewHost.cs
- ReactiveUI\ReactiveObject\ReactiveObject.cs
- ReactiveUI\ReactiveObject\ReactiveRecord.cs
- ReactiveUI\Routing\RoutingState.cs
- ReactiveUI.AndroidSupport\ReactiveRecyclerViewViewHolder.cs
- ReactiveUI.AndroidX\ReactiveRecyclerViewViewHolder.cs
- _ReactiveUI.Tests\ReactiveObject\Mocks\OaphNameOfTestFixture.cs_
- _ReactiveUI.Tests\ReactiveObject\Mocks\OaphTestFixture.cs_
- _ReactiveUI.Tests\ReactiveObject\Mocks\TestFixture.cs_
- _ReactiveUI.Tests\ReactiveObject\Mocks\WhenAnyTestFixture.cs_

Whether these are all candidates for Json serialization with System.Text.Json I can't say.

**Comment by VAllens** [comment]
Does anyone have any suggestions?

**Comment by glennawatson** [comment]
Yeah probably time we bite the bullet and swap to using full on system.text.json.

**Comment by ChrisPulman** [comment]
We have added support for System.Text.Json, please raise a new issue with any new findings, thank you

**Comment by VAllens** [comment]
goooooooooooooooooooooooooood !!!
