### ISSUE TITLE
[BUG] dev experience - rxui for windows desktop currently tied to net6.0.2+

### ISSUE THREAD

**Issue by dpvreony** [reactiveui/ReactiveUI#3191]
this is just a heads up as been chasing an issue with downstream dll's failing to build against rx ui 17.1.50

`
CSC : error CS1705: Assembly 'ReactiveUI.Wpf' with identity 'ReactiveUI.Wpf, Version=17.1.0.0, Culture=neutral, PublicKeyToken=null' uses 'PresentationFramework, Version=6.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher version than referenced assembly 'PresentationFramework' with identity 'PresentationFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
`

https://github.com/dotnet/core/issues/7176

i've resolved my issue by updating visual studio, but just in case anyone else turns around and states it's not building for wpf\winforms on older versions of visual studio 2022. it does mean there is a ripple effect on downstream projects until the core issue is resolved.

there is a workaround of

```
<ItemGroup>
<FrameworkReference
Update="Microsoft.WindowsDesktop.App;Microsoft.WindowsDesktop.App.WPF;Microsoft.WindowsDesktop.App.WindowsForms"
TargetingPackVersion="6.0.0" />
</ItemGroup>
```

happy to do the PR if wanted

**Comment by glennawatson** [comment]
This one seems to be resolved @dpvreony can you confirm?

**Comment by dpvreony** [comment]
yeah ado and github agents both fine now
