### ISSUE TITLE
[BUG] No constructor found for ReactiveRecyclerViewViewHolder::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership)

### ISSUE THREAD

**Issue by hungnt93** [reactiveui/ReactiveUI#3206]
Sometimes, I got an Exception that is related to JNI handle. 
I think it's caused by Reactive library doesn't public the constructor which has 2 args is:
Object(System.IntPtr, Android.Runtime.JniHandleOwnership)
In some cases, the system needs that to do something. When it is not available, this exception might happen.
Can you public that default constructor in all of class of Reactive?

This is the log detail is below:
Message: Unable to activate instance of type Skedulo.Droid.Features.JobDetails.MapViewHolder from native handle 0x7fcd4e8598 (key_handle 0x280d22).
Java.Interop.TypeManager.CreateInstance(System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) in Java.Interop.TypeManager.cs
Java.Lang.Object.GetObject(System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type type) in Java.Lang.Object.cs
Java.Lang.Object._GetObject[T](System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) in Java.Lang.Object.cs
Java.Lang.Object.GetObject[T](System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) in Java.Lang.Object.cs
Java.Lang.Object.GetObject[T](System.IntPtr jnienv, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) in Java.Lang.Object.cs
Android.Gms.Maps.IOnMapReadyCallbackInvoker.n_OnMapReady_Lcom_google_android_gms_maps_GoogleMap_(System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_googleMap) in Android.Gms.Maps.IOnMapReadyCallbackInvoker.cs
at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.143(intptr,intptr,intptr)
Message: No constructor found for Skedulo.Droid.Features.JobDetails.MapViewHolder::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership)
Java.Interop.TypeManager.CreateProxy(System.Type type, System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer) in <26089ba3b92240b18ff3f6bf76d430cb>
Java.Interop.TypeManager.CreateInstance(System.IntPtr handle, Android.Runtime.JniHandleOwnership transfer, System.Type targetType) in <26089ba3b92240b18ff3f6bf76d430cb>

**Comment by glennawatson** [comment]
We have that constructor. Linking can strip that constructor away. You need to adjust your linker settings.

**Comment by hungnt93** [comment]
@glennawatson thank you so much Glen!
Could you please let me know how to change this linker setting to the right option?

**Comment by glennawatson** [comment]
https://docs.microsoft.com/en-us/xamarin/android/deploy-test/linker

Consider the SDK only option

**Comment by hungnt93** [comment]
@glennawatson 
Thank you so so so much @glennawatson !
Have a nice day!
