### ISSUE TITLE
Can it support .net framework 4.0 to .net framework 4.6?

### ISSUE THREAD

**Issue by suc8899** [reactiveui/ReactiveUI#3211]
Can it support .net framework 4.0 to .net framework 4.6 ？
@glennawatson

**Comment by glennawatson** [comment]
No. Microsoft has stopped support for net framework 4.6

**Comment by glennawatson** [comment]
See https://docs.microsoft.com/en-us/lifecycle/faq/dotnet-framework#what-is-the-microsoft-lifecycle-policy-for--net-framework-
