### ISSUE TITLE
Unnecessary class constraints in generics

### ISSUE THREAD

**Issue by prostopsih** [reactiveui/ReactiveUI#3213]
I want to make an interface for ViewModel and create custom control derived from ReactiveContentView<TViewModel> where TViewModel will be an interface.

class constraint is not necessary here and in implementations such as ReactiveContentView<TViewModel>
```
public interface IViewFor<T> : IViewFor, IActivatableView where T : class
  {
    T? ViewModel { get; set; }
  }
```

Would be great to remove this constraints where they are not needed.

**Comment by tomasfil** [comment]
Given conversation, there is reason inside the framework, why that constrain exists:

![image](https://user-images.githubusercontent.com/34779382/179719907-915fdfa7-9c6b-48f6-b47b-e0f8b60b4e3c.png)


Furthermore I personally myself think there should not be reason to abstract ViewModel implementation from View.

I am closing this issue, but feel free to follow up on this if you need any further assistance
