### ISSUE TITLE
[Bug][WinUI]: ViewModelViewHost not working on WinUI projects.

### ISSUE THREAD

**Issue by lighterhy** [reactiveui/ReactiveUI#3248]
### Describe the bug 🐞

ViewModelViewHost not working on WinUI projects.
When I bind a ObservableCollection<TestUserControlViewModel> to a ListView, an XamlParseException occurs with following message:

`Exception thrown: 'Microsoft.UI.Xaml.Markup.XamlParseException' in WinRT.Runtime.dll
WinRT information: The type 'ViewModelViewHost' was not found because 'clr-namespace:ReactiveUI;assembly=ReactiveUI.WinUI' is an unknown namespace. [Line: 1 Position: 276]
XAML parsing failed.
`

Currently I use ViewModelViewHost directly in my DataTemplate to resolve this temporary.

### Step to reproduce

I create a simple project to reproduce this:

[App1.zip](https://github.com/reactiveui/ReactiveUI/files/8595547/App1.zip)

### Reproduction repository

https://github.com/reactiveui/ReactiveUI

### Expected behavior

Get the view rendered by the view model.

### IDE

Visual Studio 2022

### Operating system

Windows

### Version

10.0.22000.652

### Device

Surface Book 2

### ReactiveUI Version

18.0.10

**Comment by HavenDV** [comment]
WinUI has other namespace declarations. Try `xmlns:rx="using:ReactiveUI"`

**Comment by jdcrutchley** [comment]
I can confirm this as well.  Just giving a ListView a name and binding in the code-behind produces an XAML parsing error, but if I give it a DataTemplate containing nothing but a ViewModelViewHost with its ViewModel property set to {x:Bind}, everything works fine.
