### ISSUE TITLE
[FEATURE] Make in ReactiveCommand the possibility to flow the AsyncLocal(ExecutionContext) 

### ISSUE THREAD

**Issue by ScarletKuro** [reactiveui/ReactiveUI#3258]
**Is your feature request related to a problem? Please describe.**
It is known that because of the free-threaded nature of Rx itself the ExecutionContext isn't flowed as Task flows it. But, I really think that at least ReactiveCommand should flow the ExecutionContext.
My use case is that I use [scoped lifestyle](https://docs.simpleinjector.org/en/latest/lifetimes.html#scoped) in SimpleInjector which uses AsyncLocal inside and sometimes during ReactiveCommand you can get an exception like
```
CommandHandler is registered using the 'Async Scoped' lifestyle, but the instance is requested outside the context of an active (Async Scoped) scope. Please see https://simpleinjector.org/scoped for more information about how apply lifestyles and manage scopes.
```
This happens because ReactiveCommand used wrong ExecutionContext.
Another example without SimpleInjector is too use raw AsyncLocal and generate unique guids before the window creation then create new instance of a window, print the result in the ctor and then during ReactiveCommand. Result I would personally expect is to get **constantly**:
```
.ctor| 52274f82-15f5-45e3-b554-3f445a83bf58 
OnReactiveCommandTest | 52274f82-15f5-45e3-b554-3f445a83bf58
```
But sometimes you can get
```
.ctor | 6760589d-ff80-450f-a472-0419c95b7c63 
OnReactiveCommandTest | f7a554ef-2096-4de1-82e7-58fdca70edb1 //(or null depending if you had any other values in AsyncLocal before)
```

I won't give any reproduction repository since this behavior is not constant, on some machines this doesn't happen at all for some reason? Like mine. On some machines it happens 1 out of 1000 clicks, on some it happens constantly. There were cases when user got exception from the SimpleInjector, clicks ok on the messagebox and then clicks the button again(which is tied to ReactiveCommand) and it worked.

**Why it is important?**
Because there are libraries that rely on ExecutionContext: some DependencyInjection libs, logging libs(context logging, distributed tracing using Activity), Metrics(like OpenTelemetry),  JetBrains.Lifetimes etc.
It overall makes sense for ReactiveCommand to flow because it usually tied to some control action and developer might want to do some context based operation. Like I'm not saying you should make common observables to flow(otherwise I would write to Rx team), just the ReactiveCommand.

**Describe alternatives you've considered**
My current workaround is to use 
`_executionContext = ExecutionContext.Capture();` in the ctor and then restore it in inside the ReactiveCommand
```CSharp
public ReactiveCommand<Unit, Unit> TestCommand =>  ReactiveCommand.CreateFromTask(OnReactiveCommandTest);

private Task OnReactiveCommandTest()
{
            ExecutionContext.Restore(_executionContext );
            return _sender.Send(new SomeMediatrRequest(...));
}
```
This **completely** solves the problem.

Another alternative before that solution was to completely eliminate the usage of ReactiveCommand and use a simple implementation of ICommand which also solved the problem. But since I was tightly tied to Rx/RxUI infrastructure this wasn't a really way to go.

**Describe suggestions on how to achieve the feature**

1. Like in my example - simply to capture the ExecutionContext and then Restore it but make it inside the ReactiveCommands code. I know that the Restore was added only in net5, so either to use ExecutionContext.Run or another workaround like [this](https://github.com/CXuesong/WikiClientLibrary/blob/master/WikiClientLibrary/Infrastructures/ExecutionContextStash.cs).
3. I also think its possible to make an Scheduler that would maintain the ExecutionContext, since ReactiveComannd accepts IScheduler and reuse it not only for ReactiveCommand, but I guess you would need to write it for each platform because of the Dispatcher. But I really don't think its intuitive.

**Comment by glennawatson** [comment]
The ReactiveCommand by design will run a new task thread, which won't necessarily have an execution context. So the default functionality won't be changing. Originally RxUI did sync to the main UI thread but this had a huge performance cost especially on mobile platforms.

You could potentially add an extension method that would do your ExecutionContext.Run(() overload for the ReactiveCommand yourself which would achieve your desired results. Be similar to the existing "CreateFromTask" extension method we already use.
