### ISSUE TITLE
[Bug]: RoutedViewHost on ReactiveUserControl doesnt work when classes are in opposite order

### ISSUE THREAD

**Issue by tomasfil** [reactiveui/ReactiveUI#3262]
### Describe the bug 🐞

Well, this works with RoutedViewHost:
```
namespace ReactiveUI_NavBug
{
    public class ReacitveOkView : ReactiveUserControl<OkViewModel> { }

    /// <summary>
    /// Interaction logic for OkView.xaml
    /// </summary>
    public partial class OkView : ReacitveOkView
    {
        public OkView()
        {
            InitializeComponent();
        }
    }
}
```

And this doesnt, I am baffeld of why:
```
namespace ReactiveUI_NavBug
{
    /// <summary>
    /// Interaction logic for BrokenView.xaml
    /// </summary>
    public partial class BrokenView : ReactiveBrokenView
    {
        public BrokenView()
        {
            InitializeComponent();
        }
    }

    public class ReactiveBrokenView : ReactiveUserControl<BrokenViewModel> { }
}
```

### Step to reproduce

I have created reproduction repository, just run it see it and be baffled like me :D

### Reproduction repository

https://github.com/tomasfil/ReactiveUI_NavBug

### Expected behavior

The usercontrol should show without any connection to where the class is specified.

### Operating system

Windows

### Version

19042.1706

### ReactiveUI Version

latest

**Comment by glennawatson** [comment]
My only guess at the top of my head is some static variable but I can't think of any statics in the user control.

**Comment by tomasfil** [comment]
I have absolutely no clue how something like that can even happen

**Comment by ChrisPulman** [comment]
Hi @tomasfil there is a static dependency property for the ViewModelProperty, if this is not set before initialisation then the xaml is loaded before the association is made, therefore you will get the failure you are experiencing. 
The best option is to have seperate files for each class and partial class in your project and the compiler will handle the initialisation order to irradiate the issue.

**Comment by tomasfil** [comment]
Hello @ChrisPulman, may I ask if this is anyhow and anywhere documented?

Also I am confused by the "have seperate files for each class and partial class in your project". I am confused by the partial class. How would that look?

**Comment by glennawatson** [comment]
It's a wpf thing https://social.msdn.microsoft.com/Forums/vstudio/en-US/c5cca516-d3b0-4d83-aeed-96705910e995/order-for-the-dp-initialization?forum=wpf

**Comment by glennawatson** [comment]
And Chris suggestion is you put ReactiveBrokenView and ReactiveUI_NavBug in separate files this also fixes it

**Comment by glennawatson** [comment]
Closing due to being unrelated to rxui but might a issue on the website side since we do recommend having these classes mentioning order is important
