### ISSUE TITLE
[Bug]: Modifying button enabled state in a ReactiveCommand triggered by that button fails

### ISSUE THREAD

**Issue by philipkaare** [reactiveui/ReactiveUI#3293]
### Describe the bug 🐞

When connecting a button to a ReactiveCommand, which updates a variable in the ViewModel which decides button enabled state, I would expect that the enabled state of the button is updated based on that variable. 

### Step to reproduce

1. Click first on "Works", the button is then disabled. 
2. Click on "Doesn't work" and the button is not disabled. 

### Reproduction repository

https://github.com/philipkaare/ReactiveUIWinformsBug

### Expected behavior

Would expect that the enabled state is updated correctly. 

### IDE

Visual Studio 2022

### Operating system

Windows

### Version

11

### Device

PC

### ReactiveUI Version

18.1.8

### Additional information ℹ️

Calling Application.DoEvents() in the ReactiveCommand solves the problem.

**Comment by ChrisPulman** [comment]
Hi Philip, the command runs in a task pool thread therefore the UI thread is being held until the command has completed, calling DoEvents() will invoke a refresh of the UI thread causing the update to occur. There is an overload available for the command called CanExecute this takes an Observable which allows you to control both when the command can be executed and the UI of the button will automatically disable the button when this Observable returns false. You only require a single binding for your command to the button, everything else happens magically in the background. I can provide a PR to your report later to demonstrate the correct way.

**Comment by ChrisPulman** [comment]
Please see [Pull request with updated code](https://github.com/philipkaare/ReactiveUIWinformsBug/pull/1) for an updated method for your requirements.

**Comment by ChrisPulman** [comment]
I have updated the PR to include a colour change for the buttons

**Comment by philipkaare** [comment]
@ChrisPulman , thanks so much! I feel like the threading model of ReactiveUI with Winforms is a bit complicated - is there any documentation you can recommend?
