### ISSUE TITLE
Unable to catch global exceptions

### ISSUE THREAD

**Issue by mysteryx93** [reactiveui/ReactiveUI#3305]
### Describe the bug 🐞

Using ReactiveUI in Avalonia, I'm unable to catch exceptions with `RxApp.DefaultExceptionHandler`

### Step to reproduce

I created this class to handle exceptions.
```
/// <summary>
/// A global error handler that displays a message box when unhandled errors occur.
/// </summary>
public class GlobalErrorHandler : IObserver<Exception>
{
    private readonly IDialogService _dialogService;


    /// <summary>
    /// Sets the global error handler to display all errors with specified owner Window.
    /// </summary>
    /// <param name="owner">The Window owner in which to display the errors.</param>
    public static void Set(Window owner)
    {
        var errHandler = Locator.Current.GetService<GlobalErrorHandler>()!;
        errHandler.Owner = owner;
        RxApp.DefaultExceptionHandler = errHandler;
    }
    
    /// <summary>
    /// Initializes a new instance of the GlobalErrorHandler class.
    /// </summary>
    public GlobalErrorHandler(IDialogService dialogService)
    {
        _dialogService = dialogService;
    }

    /// <summary>
    /// Gets or sets the Window owner in which to display error messages.
    /// </summary>
    public Window? Owner { get; set; }
    
    /// <inheritdoc />
    public async void OnNext(Exception error)
    {
        if (Debugger.IsAttached) Debugger.Break();

        ShowError(error);
    }

    /// <inheritdoc />
    public void OnError(Exception error)
    {
        if (Debugger.IsAttached) Debugger.Break();

    }

    /// <inheritdoc />
    public void OnCompleted()
    {
        if (Debugger.IsAttached) Debugger.Break();

    }

    public async void ShowError(Exception error)
    {
        
        var _ = _dialogService.ShowMessageBoxAsync(Owner!, error.ToString(), "Application Error", MessageBoxButton.Ok, MessageBoxImage.Error);
    }
}
```

### Reproduction repository

https://github.com/reactiveui/ReactiveUI

### Expected behavior

This should happen...

**Comment by glennawatson** [comment]
Hey there. 

The Avalonia guys manage their plugin to ReactiveUI so best to bring it up with them

**Comment by mysteryx93** [comment]
On their side

> No, we use normal ReactiveUI.
> [Avalonia.ReactiveUI](https://github.com/AvaloniaUI/Avalonia/tree/master/src/Avalonia.ReactiveUI) is just some framework specific implementations and helpers for Avalonia projects.

I reproduced the problem in a blank project template
https://github.com/AvaloniaUI/Avalonia/issues/8457

**Comment by glennawatson** [comment]
I meant more they control their plugin which does it's own registrations. You've got some very Avalonia bits in your exception handler too

**Comment by maxkatz6** [comment]
@glennawatson Hi! I checked, and it doesn't seem to be an Avalonia issue.
Basically, ReactiveCommand is being created before custom default exception handler was set.
See: https://github.com/AvaloniaUI/Avalonia/issues/8457#issuecomment-1176565791

Workaround should be pretty simple though.
