### ISSUE TITLE
[Bug]: Can't restore ReactiveUI.Blazor from NuGet

### ISSUE THREAD

**Issue by ScottKane** [reactiveui/ReactiveUI#3314]
### Describe the bug 🐞

Add package reference to blazor wasm project `<PackageReference Include="ReactiveUI.Blazor" Version="18.2.9" />`

Restore log:
```
Cycle detected. 
  ReactiveUI -> ReactiveUI.Blazor 18.2.9 -> ReactiveUI (>= 18.2.9).
```

Restore fails and package can't be used. tried using other versions. I've never experienced this with any other package.

### IDE

Rider Windows

### Operating system

Windows

### Version

2022.1.2

### ReactiveUI Version

18.2.9

**Comment by glennawatson** [comment]
What was the issue in the end in case we have others with this issue?

**Comment by ScottKane** [comment]
The project I created to test the package was named ReactiveUI, can't say I've had this problem before but worth knowing I suppose
