### ISSUE TITLE
[Bug]: Couldn't find a Command Binder for DevExpress.XtraBars.BarButtonItem DevExpress

### ISSUE THREAD

**Issue by diepca** [reactiveui/ReactiveUI#3337]
### Describe the bug 🐞

Couldn't find a Command Binder for DevExpress.XtraBars.BarButtonItem DevExpress

### Step to reproduce

pictures below

### Reproduction repository

https://github.com/reactiveui/ReactiveUI

### Expected behavior

register success command for DevExpress.XtraBars.BarButtonItem 

### Screenshots 🖼️

<img width="1659" alt="image" src="https://user-images.githubusercontent.com/67899944/183122124-db5cb377-b988-473d-a13a-5593e4e940e7.png">
<img width="1639" alt="image" src="https://user-images.githubusercontent.com/67899944/183122191-e3d04ef4-7184-469b-ab1b-ec7911032735.png">

### Operating system

Windows

### Version

10.0.25169

### Device

Windows

### ReactiveUI Version

18.3.0.0

**Comment by glennawatson** [comment]
We don't support third party controls but we have a standard interface for adding support yourself. 

See here for a example https://github.com/reactiveui/ReactiveUI/blob/03f4c95cdc11805650e2956721ede5e7e1f852c6/src/ReactiveUI.Winforms/CreatesWinformsCommandBinding.cs#L21
