### ISSUE TITLE
[Bug]: ObservableAsPropertyHelper uses the wrong scheduler for winforms by default

### ISSUE THREAD

**Issue by daniel-lerch** [reactiveui/ReactiveUI#3339]
### Describe the bug 🐞

ReactiveUI's `ObservableAsPropertyHelper` uses `System.Reactive.Concurrency.CurrentThreadScheduler.Instance` as the default scheduler ([source](https://github.com/reactiveui/ReactiveUI/blob/03f4c95cdc11805650e2956721ede5e7e1f852c6/src/ReactiveUI/ObservableForProperty/ObservableAsPropertyHelper.cs#L150)). In a Windows Forms application however, this scheduler does not seem to work. The property value despite calculated is never updated and the value changed event never raised. 

### Step to reproduce

1. Create a Windows Forms application
`dotnet new winforms`

2. Create a new class with the following code
```csharp
public class TestViewModel : ReactiveObject
{
    private string text;
    private readonly ObservableAsPropertyHelper<bool> empty;

    public TestViewModel()
    {
        empty = this.WhenAnyValue(x => x.Text)
            .Select(x => string.IsNullOrEmpty(x))
            .ToProperty(this, x => x.Empty);

         // The following code instead would work
         // .ToProperty(this, x => x.Empty, RxApp.MainThreadScheduler);
    }

    public string Text
    {
        get => text;
        set => this.RaiseAndSetIfChanged(ref text, value);
    }

    public bool Empty => empty.Value;
}
```

3. Edit `Form1.cs`
```csharp
public partial class Form1 : Form
{
    public Form1()
    {
        InitializeComponent();
        var viewModel = new TestViewModel();
        viewModel.PropertyChanged += (sender, e) => System.Diagnostics.Debug.WriteLine($"{e.PropertyName} changed");
        Shown += (sender, e) => viewModel.Text = "Hello World!";
    }
}
```

4. Run this application
5. In the logs you will see `Text changed` but you won't see `Empty changed`

### Expected behavior

The value of an `ObservableAsPropertyHelper` should always be updated and the property changed event raised when the underlying value changed even when no scheduler is explicitly configured.

### IDE

Visual Studio 2022

### Operating system

Windows 10 Pro

### Version

10.0.19044.1889

### Runtime

.NET SDK 6.0.400

### ReactiveUI Version

18.3.1

### Additional information ℹ️

If changing the default scheduler will break other applications, it would be extremely helpful to throw an exception stating that a scheduler has to be specified in `.ToProperty()` when running on Windows Forms.

**Comment by glennawatson** [comment]
Are you including the `reactiveui.winforms` nuget package?

**Comment by daniel-lerch** [comment]
In my project the view model resides in a library which targets `net6.0` and does not include `ReactiveUI.WinForms`. The windows forms project with the view targets `net6.0-windows10.0.19041.0` and has a dependency on `ReactiveUI.WinForms`.

**Comment by daniel-lerch** [comment]
I ran some tests with my code provided here and can't reproduce this issue. Even with the view-model in a different library everything works fine.

[Vocup](https://github.com/daniel-lerch/vocup), the real application where I ran into this issue has a way more complicated startup. If get to isolate this bug, I will open a new issue.
