### ISSUE TITLE
[Bug]: CA1416: Validate platform compatibility for RaisePropertyChanged being reported in .Net Maui project

### ISSUE THREAD

**Issue by JRosanowski** [reactiveui/ReactiveUI#3340]
### Describe the bug 🐞

The warning in the screenshot below is being displayed but there seems to be no issue with the method on a Api 21 emulator.  Is it possible to resolve this warning somehow?

### Step to reproduce

1. Open attached project in Visual Studio 2022 17.3
2. Open ViewModel.cs 
3. Error will be visible under the call to RaisePropertyChanged

### Reproduction repository

https://github.com/reactiveui/ReactiveUI

### Expected behavior

No warning.

### Screenshots 🖼️

![RaisePropertyChanged](https://user-images.githubusercontent.com/14955434/185276835-f0c15d3c-50ef-4453-bdda-a5a4917add45.png)

### IDE

Visual Studio 2022

### Operating system

Windows

### ReactiveUI Version

18.3.1

### Additional information ℹ️

[MauiApp1.zip](https://github.com/reactiveui/ReactiveUI/files/9367101/MauiApp1.zip)

**Comment by ChrisPulman** [comment]
Please see #3315 and set your TargetPlatformMinVersion in your csproj

**Comment by ChrisPulman** [comment]
You most likely need to set
`<TargetPlatformMinVersion Condition="'$(TargetFramework)' == 'net6.0-android'">31.0</TargetPlatformMinVersion>`

**Comment by J-Swift** [comment]
When I tried this it didn't work as intended. I dont remember the details but it didn't play nicely with `SupportedOSPlatformVersion` I think.
