### ISSUE TITLE
[Bug]: BindCommand() Click button error focus to the next control

### ISSUE THREAD

**Issue by diepca** [reactiveui/ReactiveUI#3341]
### Describe the bug 🐞

Click in button -> Error focus in next Textbox 

### Step to reproduce

below image

### Reproduction repository

https://github.com/reactiveui/ReactiveUI

### Expected behavior

Focus current button

### Screenshots 🖼️

![image](https://user-images.githubusercontent.com/67899944/185538725-5a3d5bc4-179a-4c72-a909-ce9b1c41397b.png)
![image](https://user-images.githubusercontent.com/67899944/185539060-30afa7e7-f7cd-4602-8c5d-e45761778dea.png)

**Comment by ChrisPulman** [comment]
Sorry but you haven't supplied sufficient information to be able to see your issue, we would need to see what you are trying to do in the ViewModel. Please provide a repository link or zip to an example showing the bug you are trying to identify. Many thanks.

**Comment by diepca** [comment]
[](url
[WinFormsApp1.zip](https://github.com/reactiveui/ReactiveUI/files/9379610/WinFormsApp1.zip)
)
this is example error

**Comment by Illicitl** [comment]
Excuse me, How to fix this?

**Comment by ChrisPulman** [comment]
There is the ability to use ReactiveCommand.CreateRunInBackground(..... 
this should allow your UI state to be relevant to the action execution within the command. ReactiveCommand.Create is synchronous therefore the UI doesn't have chance to update the state. ReactiveCommand.CreateRunInBackground is Asynchronous therefore the UI thread is released during operation.
