### ISSUE TITLE
Allow null `TSender` for `WhenAnyObservable`

### ISSUE THREAD

**Issue by Nextra** [reactiveui/ReactiveUI#3343]
Unlike its `WhenAnyValue` counterpart, `WhenAnyObservable` complains about nullability mismatches when `TSender` may be null at the time of the call.

It feels like both should have the same nullability expectations/restrictions.

I'm using version 18.3.1

**Comment by anaisbetts** [comment]
It feels like neither WhenAny or WhenAnyObservable should allow a null sender, or? Unlike a null intermediate expression, a null sender can never eventually evaluate to a value, or?

**Comment by ChrisPulman** [comment]
I understand that if a call to WhenAny or WhenAnyObservable is made when the sender (which is often a nullable ViewModel), is Null then yes this will also result in the code not executing.

The issue with having the sender as a non-nullable TSender is that if the compiler wants protection against null values when you pass a nullable item in, therefore currently needs that protection in the end users code. By making TSender accept nullable senders this removes the need for the end user to protect every call to WhenAny....

Perhaps we should in addition have a message that goes into a debug log when the sender enters in a Null state to assist the end user with code execution issues that they may have.

**Comment by Nextra** [comment]
For what it's worth, from a user perspective I think both variants are perfectly acceptable. It's just the inconsistency that is a bit weird.

I figured doing it this way around was "correct" because previously `WhenAnyValue` was specifically changed to allow nullable values in #2760. It seems like this should also include `WhenAnyObservable` but it might have been accidentally reverted?
