### ISSUE TITLE
[Bug]: WhenAnyValue.toproperty output value not beeing updated properly

### ISSUE THREAD

**Issue by brignolff** [reactiveui/ReactiveUI#3358]
### Describe the bug 🐞

When using WhenAnyValue to subscribe to a nested property and to it's container, if the container is set to null, the output property doesn't change. 

### Step to reproduce

Please see the code provided in the .md file
[Code.md](https://github.com/reactiveui/ReactiveUI/files/9476242/Code.md)

### Expected behavior

The output value should be set to null.

### IDE

Visual Studio 2022

### Operating system

windows

### ReactiveUI Version

18.3.1

**Comment by kmgallahan** [comment]
https://www.reactiveui.net/docs/handbook/when-any/#watching-a-nested-property

> WhenAny variants can observe nested properties for changes, too:

`this.WhenAnyValue(x => x.Foo.Bar.Baz);`
> Presuming the properties between Foo.Bar.Baz are not null it will emit the current value and then any subsequent values.

> If either Foo or Bar are null then the value of Baz won't be emitted.

**Comment by glennawatson** [comment]
Thanks @kmgallahan
