### ISSUE TITLE
[Bug]: Xamarin.Mac binaries are missing in Visual Studio 2022 17.3.5

### ISSUE THREAD

**Issue by ChrisPulman** [reactiveui/ReactiveUI#3380]
### Describe the bug 🐞

[VS2022 17.3.5 Bug](https://developercommunity.visualstudio.com/t/XamarinMac-binaries-are-missing-in-173/10164443#T-ND10165277)

Microsoft are aware of the issue and working on a fix.

### Step to reproduce

1. Create a Xamarin.Mac20 targeted project
2. build will fail
3. Missing Xamarin.Mac.dll will be reported

### Reproduction repository

https://github.com/reactiveui/ReactiveUI

### Expected behavior

Xamarin.Mac projects should build with VS 2022.

Patch has been applied to ReactiveUI to allow build.

Remove when Visual Studio Bug is fixed.

### IDE

Visual Studio 2022

### Operating system

N/A

### Version

N/A

### Device

N/A

### ReactiveUI Version

N/A

### Additional information ℹ️

Adding the following to a Xamarin.Mac project should allow it to build as a temporary workaround.
`  <ItemGroup Condition=" $(TargetFramework.StartsWith('Xamarin.Mac')) ">
    <Reference Include="Xamarin.Mac">
      <HintPath Condition="Exists('c:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\Xamarin.VisualStudio')">c:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\Xamarin.VisualStudio\Xamarin.Mac.dll</HintPath>
      <HintPath Condition="Exists('c:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\Extensions\Xamarin.VisualStudio')">c:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\Extensions\Xamarin.VisualStudio\Xamarin.Mac.dll</HintPath>
      <HintPath Condition="Exists('c:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\Extensions\Xamarin.VisualStudio')">c:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\Extensions\Xamarin.VisualStudio\Xamarin.Mac.dll</HintPath>
      <HintPath Condition="Exists('c:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\Extensions\Xamarin.VisualStudio')">c:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\Extensions\Xamarin.VisualStudio\Xamarin.Mac.dll</HintPath>
    </Reference>
  </ItemGroup>`

**Comment by ChrisPulman** [comment]
If you use VS2022 17.4.0 Preview 5.0 this issue has been resolved

**Comment by kevcrooks** [comment]
I still seem to be missing the `Xamarin.Mac` assembly as of VS2022 17.4.0 and 17.5.0 Preview 1 (both released today) - is the fix expected to have been included?

**Comment by glennawatson** [comment]
Apparently not unfortunately. 

FYI - The latest release version of VS2022 17.4.0 can now be used to build RxUI, unfortunately they still haven't resolved the Xamarin.Mac reference issue, this problem is expected to be fixed as soon as Xcode 14.1 is released

**Comment by kevcrooks** [comment]
Thank you, I believe Xcode 14.1 is out now, so I guess the fix should filter through soon

**Comment by ChrisPulman** [comment]
Fixed in VS2022 17.4.3
