### ISSUE TITLE
[Bug]: DataContext inside Avalonia TabControl not binding correctly

### ISSUE THREAD

**Issue by Laurnz** [reactiveui/ReactiveUI#3437]
### Describe the bug 🐞

When using a reactive user control inside an Avalonia tab control, binding the data context breaks after switching tabs.
The first time loading a tab, the binding works. After switching to the tab again, the following expression is thrown:

[Binding] Error in binding to 'MyProject.MyView'.'DataContext': 'Null value in expression '{empty}' at ''.' (MyView #2594873)

### Step to reproduce

Reproduction with reproduction repository
1. Run project from reproduction repository
2. See the two labels displayed in current tab content
3. Switch to tab 2
4. Switch back to tab 1
5. The label with content binding is now missing

Principle of code in reproduction repository
1. Create reactive user control
2. Set user control as content in tab control
3. Bind data context of reactive user control to property of parent control

### Reproduction repository

https://github.com/Laurnz/AvaloniaActivatableTab

### Expected behavior

Binding to work and no exceptions to be thrown.

### IDE

Visual Studio 2022, Rider Windows

### Operating system

Windows, Linux

### Version

Windows 11, Ubuntu 22.04

### ReactiveUI Version

18.3.1

### Additional information ℹ️

Version of Avalonia: 11.0.0-preview4    and   0.10.18 have been tested

**Comment by Laurnz** [comment]
For clarification. The problem dies not occur when using a UserControl, but using ReactiveUserControl.
Things like IActivatableViewModel are also not activated. Turning on compiled binding fixes some of the problems.

**Comment by yankun** [comment]
I've a similar issue. I'm using a view model structure and the Tab's Items and SelectedItem properties. Navigating between the TabItems breaks the bindings. Filling the Tab manually with content (not using the Items property, but writing the content directly in XAML) works.

**Comment by ALIENQuake** [comment]
@Laurnz I've tested this again using the reproduction repository which you provided but I updated the code to use Avalonia 11.0.0-preview5+Avalonia.Themes.Fluent-11.0.0-preview5 and I no longer see such an issue.

**Comment by ChrisPulman** [comment]
As I understand this is resolved by Avalonia 11, therefore I will close. Avalonia support the Avalonia.ReactiveUI package within their support team so if this is still an issue I would recommend raising an issue there.
Many thanks
