### ISSUE TITLE
Source Generator and Reactive Attribute, as alternative to ReactiveWindow and ReactiveUserControl

### ISSUE THREAD

**Issue by martinrhan** [reactiveui/ReactiveUI#3449]
**Is your feature request related to a problem? Please describe.**
I am now working with ReactiveUI.Wpf and I found it very tedious to use ReactiveWindow and ReactiveUserControl.

Following text is copied from [the documentation](https://www.reactiveui.net/api/reactiveui/reactiveusercontrol_1/):

This class is a UserControl that is also reactive. That is, it implements [IViewFor<T>](https://www.reactiveui.net/api/ReactiveUI/IViewFor_1). You can extend this class to get an implementation of [IViewFor<T>](https://www.reactiveui.net/api/ReactiveUI/IViewFor_1) rather than writing one yourself.

Note that the XAML for your control must specify the same base class, including the generic argument you provide for your view model. To do this, use the TypeArguments attribute as follows:

```
<rxui:ReactiveUserControl
        x:Class="Foo.Bar.Views.YourView"
        x:TypeArguments="vms:YourViewModel"
        xmlns:rxui="http://reactiveui.net"
        xmlns:vms="clr-namespace:Foo.Bar.ViewModels"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        mc:Ignorable="d">
    <!-- view XAML here -->
</rxui:ReactiveUserControl>
```
Note that UWP and WinUI projects do not support the TypeArguments attribute. The XAML designer window in WPF projects also does not support generic types. To use [ReactiveUserControl<TViewModel>](https://www.reactiveui.net/api/ReactiveUI/ReactiveUserControl_1) in XAML documents you need to create a base class where you derive from [ReactiveUserControl<TViewModel>](https://www.reactiveui.net/api/ReactiveUI/ReactiveUserControl_1) with the type argument filled in.
```
 internal class YourViewBase : ReactiveUserControl<YourViewModel> { /* No code needed here */ }

 public partial class YourView : YourViewBase
 {
     /* Your code */
 }
```
Then you can use this base class as root in your XAML document.
```
<views:YourViewBase
        x:Class="Foo.Bar.Views.YourView"
        xmlns:rxui="http://reactiveui.net"
        xmlns:vms="clr-namespace:Foo.Bar.ViewModels"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        mc:Ignorable="d">
    <!-- view XAML here -->
</views:YourViewBase>
```
As you can see for WPF I need to add many additional code manaully for each View I creates. It become even more lousy when it comes to UWP and WinUI.

**Describe the solution you'd like**
Just after a View is created, no need addtional modify to the xaml, simply add a Reactive Attribute.
```
[Reactive]
 public partial class MyView : UserControl //This should also work for something else such as ContentControl
 {
     /* Your code */
 }
```
Then the Source Generator should generate the implementation.

**Describe alternatives you've considered**
An alternative is item templates. It can also automatically write all those things. However, this method lacks flexibility.

**Describe suggestions on how to achieve the feature**
I don't have much idea about how to do that. As I saw https://github.com/reactiveui/ReactiveUI/blob/main/src/ReactiveUI.Uwp/Common/ReactiveUserControl.cs
much more complecated than what I can handle. 

**Additional context**

**Comment by ChrisPulman** [comment]
Hi, I am working on some Source Generators to Generate from [IViewFor(nameof(ViewModelName)] these should be ready soon.

**Comment by ChrisPulman** [comment]
V1.1.26 has been released, please try using them, thank you for your suggestions, the `[IViewFor(YourViewModel)]` attribute should provide the functionality requested.
