### ISSUE TITLE
[Bug]: Cancelling a task from an object in a command cause the application to crash

### ISSUE THREAD

**Issue by SteezCram** [reactiveui/ReactiveUI#3450]
### Describe the bug 🐞

I was developing an object to synchronize some files over the network. I want the user to be able to stop the synchronization. I ended up utilizing `Task` to achieve that and a `CancellationTokenSource` to cancel the task.

I use this documentation to achieve it: https://learn.microsoft.com/en-us/dotnet/standard/parallel-programming/task-cancellation

So far, everything works as it was intended. But when I try to stop the synchronization by using a ReactiveCommand, my application exit (see https://www.reactiveui.net/docs/handbook/default-exception-handler/). Despite catching the exception, the default exception handler triggered an exception because my task was canceled...

### Step to reproduce

Simple object to reproduce:
```csharp
class MyObject
{
    private CancellationTokenSource _cancellationTokenSource = new();

    public MyObject() { }

    public async Task<bool> StartAsync()
    {
        for (int i = 0; i < 100; i++)
        {            
            try
            {
                await BackgroundMethodAsync();
            }
            catch (OperationCanceledException ex)
            {
                return false;
            }
        }
        
        return true;
    }

    public async Task StopAsync()
    {
        _cancellationTokenSource.Cancel();
        // Wait task to finish
        await Task.Delay(10000);
        _cancellationTokenSource.Dispose();
    }

    private async Task BackgroundMethodAsync()
    {
        for (int i = 0; i < 100; i++)
        {
            _cancellationTokenSource.Token.ThrowIfCancellationRequested();
            await Task.Delay(10000);
        }
    }
}
```

Just create 2 commands that use both `StartAsync` and `StopAsync`. If you called StopAsync and you abord the task, it should close the application.

### Expected behavior

When catching the exception it should not exit the application.

### IDE

Visual Studio 2022

### Operating system

Windows

### Version

Windows 11

### ReactiveUI Version

13.2.10

### Additional information ℹ️

The version of Avalonia 0.10.18 has been tested

**Comment by SteezCram** [comment]
EDIT: if the stop method is not a task, we do not have the bug

**Comment by ChrisPulman** [comment]
This should now be resolved, please raise a new issue with any new findings, many thanks
