### ISSUE TITLE
[Bug]: Latest ReactiveUI.Winforms version (18.4.20) breaks compilation

### ISSUE THREAD

**Issue by Micha-kun** [reactiveui/ReactiveUI#3471]
### Describe the bug 🐞

After updating to ReactiveUI.* 18.4.20, my solution started to break because, since this version, "net6.0-windows" framework is not compatible. 18.4.1 (prev version) had "net6.0-windows" compatibility.

### Step to reproduce

1. Create a Winforms project using **net6.0-windows** TargetFramework

```
<PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
     ....
</PropertyGroup>

```

2. Install **ReactiveUI.WinForms** v**18.4.20** NuGet.
3. Try to compile/run

### Reproduction repository

https://github.com/reactiveui/ReactiveUI

### Expected behavior

Compilation and running should be fine.

### IDE

Visual Studio 2022

### Operating system

Windows 10

### ReactiveUI Version

18.4.20

**Comment by glennawatson** [comment]
Due to the way Microsoft is doing minimum compatibility you need to specify a minimum version for winsdk stuff. 

Net6.0-10.0.19041

**Comment by Micha-kun** [comment]
Why not making compatible to Net6-Windows7.0 too? 18.4.1 was compatible with that.

![image](https://user-images.githubusercontent.com/1403350/216387059-d32936d9-ba7c-433a-9b1d-aac88cd39941.png)

**Comment by glennawatson** [comment]
Microsoft dropped support with all their nuget packages as well. Support was becoming hard for very little return. Targeting new versions doesn't stop users from making apps for older windows versions.
