### ISSUE TITLE
[Bug]: ReactiveCommand.Dispose doesn't end its observable

### ISSUE THREAD

**Issue by AArnott** [reactiveui/ReactiveUI#3474]
### Describe the bug 🐞

I'm using `await reactiveCommand.FirstOrDefaultAsync()` and expecting it to return null when the command is disposed. But it doesn't. It just asynchronously hangs. 

As an `IObservable<T>`, it should invoke `OnCompleted` on all its observers when it will no longer be sending additional values. Surely when the `ReactiveCommand.Dispose` method is called, that's an indication that the command will not be sending more values, right? At that point, it should send `OnCompleted`, but it doesn't.

### Step to reproduce

```cs
[Fact]
public async Task ReactiveCommandObservable()
{
	ReactiveCommand<Unit, object> cmd = ReactiveCommand.Create(() => new object());
	Task<object?> waiter = WaitForValueAsync();
	cmd.Dispose();
	Assert.Null(await waiter);

	async Task<object?> WaitForValueAsync() => await cmd.FirstOrDefaultAsync();
}
```

This test hangs, because `ReactiveCommand` never sends `OnCompleted` to its observers.

### Expected behavior

I expect the test to pass.

### IDE

Visual Studio 2022

### Operating system

Windows

### ReactiveUI Version

18.3.1

**Comment by ChrisPulman** [comment]
Thank you for finding this, I will check what happens during Dispose and update it if required.

**Comment by glennawatson** [comment]
The dispose on ReactiveCommand disposes CanExecute observable. This is the intended functionality when we made it.

**Comment by ChrisPulman** [comment]
This is intended functionality; therefore, we are closing this issue.

**Comment by AArnott** [comment]
@ChrisPulman Would you mind elaborating on how this is intended? How does one avoid a hang in this case? My interpretation of the interface is in the description. It seems hard to understand how to justify never raising OnCompleted.
