### ISSUE TITLE
add support net7.0 windows 7

### ISSUE THREAD

**Issue by kronic** [reactiveui/ReactiveUI#3476]

**Comment by dpvreony** [comment]
.NET 7 is not supported on Windows 7, which is end of life.

https://support.microsoft.com/en-us/windows/windows-7-support-ended-on-january-14-2020-b75d4580-2cc7-895a-2c9c-1466d9a53962
https://github.com/dotnet/core/blob/main/release-notes/7.0/supported-os.md#out-of-support-os-versions

**Comment by kronic** [comment]
@dpvreony I wrote a wpf .net 7 app and it works great.
Tell it to clients
