### ISSUE TITLE
[Bug]: CS0433/CS0121 for DispatcherObservable with 18.4.25 on net7.0-windows10.0.19041

### ISSUE THREAD

**Issue by Yarith** [reactiveui/ReactiveUI#3495]
### Describe the bug 🐞

In projects which target `.net7.0-windows10.0.19041` you can not simply access `System.Reactive.Linq.DispatcherObservable` or some of its members with the current version 18.4.25. It does not compile because following errors gets produced:
|Schweregrad|Code|Beschreibung|Projekt|Datei|Zeile|Unterdrückungszustand|
|-|-|-|-|-|-|-|
|Fehler|CS0433|Der Typ "DispatcherObservable" ist in "ReactiveUI.Wpf, Version=18.4.0.0, Culture=neutral, PublicKeyToken=null" und "System.Reactive, Version=5.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263" vorhanden.|ReactiveUITest|MainWindow.xaml.cs|30|Aktiv|
|Fehler|CS0121|Der Aufruf unterscheidet nicht eindeutig zwischen den folgenden Methoden oder Eigenschaften: "System.Reactive.Linq.DispatcherObservable.ObserveOn<TSource>(System.IObservable<TSource>, System.Reactive.Concurrency.DispatcherScheduler)" und "System.Reactive.Linq.DispatcherObservable.ObserveOn<TSource>(System.IObservable<TSource>, System.Reactive.Concurrency.DispatcherScheduler)"|ReactiveUITest|MainWindow.xaml.cs|33|Aktiv|

This is similar to #3493. I am using this type via the `ObserveOn(DispatcherScheduler)` extension method call.

### Step to reproduce

1. Create a new .net 7.0 wpf project
2. Change the content of the project file to following text:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows10.0.19041</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ReactiveUI" Version="18.4.25" />
    <PackageReference Include="ReactiveUI.Fody" Version="18.4.25" />
    <PackageReference Include="ReactiveUI.WPF" Version="18.4.25" />
    <PackageReference Include="System.Reactive" Version="5.0.0" />
    <PackageReference Include="System.Reactive.PlatformServices" Version="5.0.0" />
  </ItemGroup>

</Project>
```
3. Go to the `MainWindow.xaml.cs` file and add following using `using System.Reactive.Concurrency;`.
4. Try access `DispatcherObservable` or for example the `DispatcherScheduler` overload of `ObserveOn` in the constructor:
```csharp
/// <summary>
/// Interaction logic for MainWindow.xaml
/// </summary>
public partial class MainWindow : Window
{
   public MainWindow()
   {
       InitializeComponent();

       System.Reactive.Linq.DispatcherObservable.ObserveOn(DispatcherScheduler.Current);

        Observable.Timer(TimeSpan.FromSeconds(1))
            .ObserveOn(DispatcherScheduler.Current)
            .Subscribe();
    }
}
```
6. Look in the error list and you can see the errors CS0433 and CS0121.

### Reproduction repository

https://github.com/reactiveui/ReactiveUI

### Expected behavior

`DispatcherObservable` or some of its members should still not have any conflict with the `System.Reactive` package.

### Screenshots 🖼️

![image](https://user-images.githubusercontent.com/7803088/223652821-05afb5d8-22ff-4586-9507-3d129ba090c6.png)
![image](https://user-images.githubusercontent.com/7803088/223652865-955c6744-abab-4f06-8e0d-2e9e27f7c55a.png)

### IDE

Visual Studio 2022

### Operating system

Windows

### Version

Windows 10 22H2 (Build 19045.2604), Visual Studio 17.5.1

### ReactiveUI Version

18.4.25

**Comment by ChrisPulman** [comment]
Please update to V18.4.26 to resolve this issue, many thanks
