### ISSUE TITLE
[Bug]: Focus changes to next control when clicking a button bound to a command

### ISSUE THREAD

**Issue by rmcardle** [reactiveui/ReactiveUI#3500]
### Describe the bug 🐞

When clicking a button bound to a command, the focus changes to the next control. This looks bad and disrupts keyboard navigation.

### Step to reproduce

- Create a form with two buttons
- Bind both buttons to commands with BindCommand
- Run the program and click on the first button
- Observe that focus switches to the second button

### Reproduction repository

https://pastebin.com/3tgN2A59

### Expected behavior

Clicking a button should not change the focus to another control. Focus is a fundamental UI paradigm and that's not how it has ever worked.

### IDE

Visual Studio 2022

### Operating system

Windows 10

### ReactiveUI Version

18.4.26

### Additional information ℹ️

I am using WinForms but based on a conversation on Slack, this happens in WPF as well.

**Comment by glennawatson** [comment]
Thanks. As discussed with Tim Cooke on slack this may actually be expected behaviour because of our disabling the controls. 

Potentially you can use his logic to not do our disabling.

**Comment by glennawatson** [comment]
```cs
// INSTEAD OF:
this.BindCommand(VM, viewModel => viewModel.ButtonCommand1, view => view.button1);
// DO THIS INSTEAD:
button1.Events().Click.Select(_ => Unit.Default).InvokeCommand(VM, viewModel => viewModel.ButtonCommand1);
```

**Comment by timothylcooke** [comment]
> ```cs
> // INSTEAD OF:
> this.BindCommand(VM, viewModel => viewModel.ButtonCommand1, view => view.button1);
> // DO THIS INSTEAD:
> button1.Events().Click.Select(_ => Unit.Default).InvokeCommand(VM, viewModel => viewModel.ButtonCommand1);
> ```

One thing to note with this solution is that if the command is already executing, the call to `InvokeCommand` will not actually do anything: it will not cancel, invoke, or queue another execution of the command a second time.

**Comment by rmcardle** [comment]
> ```cs
> // INSTEAD OF:
> this.BindCommand(VM, viewModel => viewModel.ButtonCommand1, view => view.button1);
> // DO THIS INSTEAD:
> button1.Events().Click.Select(_ => Unit.Default).InvokeCommand(VM, viewModel => viewModel.ButtonCommand1);
> ```

Error CS1955 Non-invocable member 'Component.Events' cannot be used like a method.

**Comment by glennawatson** [comment]
[ReactiveMarbles Events](https://github.com/reactivemarbles/ObservableEvents) is the library we use for generating observables from C# plain events.
