### ISSUE TITLE
[Bug]: Installing ReactiveUI.Wpf in a .NET 7 WPF project forces a restore to .net framework

### ISSUE THREAD

**Issue by mStylias** [reactiveui/ReactiveUI#3523]
### Describe the bug 🐞

When installing any ReactiveUI.WPF version above 18.4.1 in a .net 7 WPF project it creates the following warning:
warning NU1701: Package 'ReactiveUI.WPF 18.4.26' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net7.0-windows7.0'. This package may not be fully compatible with your project.

One of the implications of this warning is that calculating code metrics doesn't work.

### Step to reproduce

1. Create a .NET 7 WPF project
2. Install ReactiveUI, ReactiveUI.WPF and ReactiveUI.Fody latest version nuget packages

### Reproduction repository

https://github.com/reactiveui/ReactiveUI

### Expected behavior

The project shouldn't get restored to .Net Framework

### IDE

Visual Studio 2022

### Operating system

Windows 11

### ReactiveUI Version

18.4.26

**Comment by dpvreony** [comment]
the default `net7.0-windows` targets windows 7 which isn't supported. you need to change your project to target `net7.0-windows10.0.17763.0` or later

**Comment by glennawatson** [comment]
Recommend you target net7.0-windows10.0.19041

**Comment by mStylias** [comment]
I see, thanks for the clarification!
