### ISSUE TITLE
An attribute for auto notify another property

### ISSUE THREAD

**Issue by my522cn** [reactiveui/ReactiveUI#3540]
we can use [Reactive] for PropertyChanged like this:
`[Reactive]public string SearchId { get; set; }`
This is a feature from ReactiveUI.Fody.

I need more attributes especially AlsoNotifyFor like PropertyChanged.Fody:
`[AlsoNotifyFor("FullName")] public string FamilyName { get; set; }`
When FamilyName changed will notify FullName

**Comment by anaisbetts** [comment]
You are taking your knowledge from other frameworks in a way that you shouldn't. Instead:

```cs
[Reactive]public string FirstName { get; set; }
[Reactive]public string LastName { get; set; }

ObservableAsPropertyHelper<string> _FullName = new();
public string FullName { get => _FullName.Value; }

// later in the ctor 
this.WhenAnyValue(x => x.FirstName, x => x.LastName, (fn, ln) => $"{fn} {ln}")
  .ToProperty(this, x => x.FullName, out _FullName);
```
