### ISSUE TITLE
[Feature] Interfaces with generic variants for `ReactiveCommand`

### ISSUE THREAD

**Issue by codingchipmunk** [reactiveui/ReactiveUI#3582]
**Is your feature request related to a problem? Please describe.**
When implementing more complex abstraction layers, one may define an interface with and without generics. When used with covariants, this allows for using implementations without having to define the concrete generic type when it is not of interest (as a nicer version of the `TDontCare` generics)

```csharp
interface IReturnType {..}

interface IMyInterface
{
    IReturnType MyFunc();
}

interface IMyInterface<out T> : IMyInterface
    where T:IReturnType
{
    new T MyFunc();
}

class MyImplementation<T> : IMyInterface<T>
    where T : IReturnType
{
    //Autocast from T to IReturnType possible
    IReturnType IMyInterface.MyFunc() => MyFunc();
    public T MyFunc() => throw new System.NotImplementedException();
}
```

Unfortunately, this does not work with reactive commands, as there is no interface defining `TParam` and `TResult` as con- and contravariant, respectively.

**Describe the solution you'd like**
An interface with generic variants for reactive commands.

**Describe alternatives you've considered**
An alternative solution for projects which require this feature would be to implement the interface, in combination with a wrapper for `ReactiveCommand`. [This gist](https://gist.github.com/codingchipmunk/7dd0e9ec4fd9b3fd328a4a49d217d468) demonstrates the "workaround".

**Describe suggestions on how to achieve the feature**
The change is rather simple.  In this example, I have called the interface `IReactiveCommandGeneric`, to avoid any confusion with the non-generic `IReactiveCommand`.

```csharp
public interface IReactiveCommandVariant<in TParam, out TResult> :IObservable<TResult>, ICommand, IReactiveCommand
{
    IObservable<TResult> Execute(TParam val);
    IObservable<TResult> Execute();
}
public abstract class ReactiveCommandBase<TParam, TResult> : IReactiveCommandVariant<TParam, TResult> {..}
```

**Additional context**
I would also propose something similar for `Interaction`.

**Comment by glennawatson** [comment]
This is deliberate and by design to only have the concrete type.

**Comment by glennawatson** [comment]
I wonder if a viable alternative would be declaring the generic types on the concrete types covariant etc

**Comment by codingchipmunk** [comment]
Unfortunately, variants are only applicable to generics of interfaces and delegates.

**Comment by glennawatson** [comment]
Will see what I can do

Big thing is not to have ICommand on the interfaces. It has caused a lot of confusion with our observable version of Execute.
