### ISSUE TITLE
[Bug]: ReactiveUINuGet package using unsigned dll files

### ISSUE THREAD

**Issue by emik-dev** [reactiveui/ReactiveUI#3588]
### Describe the bug 🐞

Windows 11 is introducing Smart App Control. One of the security checks for apps is ensuring that the app and its binaries are signed. Because DynamicData is referenced in the ReactiveUINuGet package and does not sign its binaries, software using it will be blocked from running when Smart App Control is enabled.

Please sign DLLs produced for DynamicData.

https://support.microsoft.com/en-us/topic/what-is-smart-app-control-285ea03d-fa88-4d56-882e-6698afdb7003

### Step to reproduce

Add dependency to ReactiveUI to project 

### Reproduction repository

https://github.com/reactiveui/ReactiveUI

### Expected behavior

DynamicData.dll should be signed.

**Comment by glennawatson** [comment]
Different type of signing. See code signing certificates

**Comment by glennawatson** [comment]
https://www.digicert.com/signing/code-signing-certificates

It's up to you to buy a certificate and sign your package. It does not rely on strong assembly signing.
