### ISSUE TITLE
[Bug]: Net6 can't be used, wpf, Windows Forms

### ISSUE THREAD

**Issue by 107295472** [reactiveui/ReactiveUI#3590]
### Describe the bug 🐞

已使用“.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1”而不是项目目标框架“net6.0-windows7.0”还原包“ReactiveUI.WinForms 19.4.1”。此包可能与项目不完全兼容。

### Step to reproduce

no error

### Reproduction repository

https://github.com/reactiveui/ReactiveUI

### Expected behavior

no error

**Comment by glennawatson** [comment]
We don't support net461. It's been unsupported by Microsoft for a while now.
