### ISSUE TITLE
ReactiveUI.WPF does not include .net 8.0 as a target: 

### ISSUE THREAD

**Issue by kgday** [reactiveui/ReactiveUI#3696]
### Describe the bug 🐞

When compiling after upgrading to latest reactui version, I get a compiler warning:
  BeesWall.csproj: [NU1701] Package 'ReactiveUI.WPF 19.5.31' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net8.0-windows7.0'. This package may not be fully compatible with your project.

### Step to reproduce

1. Create a wpf application
2. Make sure your WPF application targets .net 8.0
3. install reactiveui package and reactiveui.wpf package
4. Compile.

### Reproduction repository

https://github.com/reactiveui/ReactiveUI

### Expected behavior

No compiler warnings regarding package targets.

**Comment by ChrisPulman** [comment]
Please ensure that you are targeting at least windows10.0.17763.0

- `<TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>`

**Comment by kgday** [comment]
Thank you, that was the problem.
