### ISSUE TITLE
[Bug]: Unable to use activation of views on Windows with MAUI

### ISSUE THREAD

**Issue by mwhapples** [reactiveui/ReactiveUI#3700]
### Describe the bug 🐞

If I add a view which uses activation (eg. ViewModelViewHost) to a MAUI application then the application will fail with an exception on Windows. The exception is about not knowing how to activate the view and suggests implementing IActivationForViewFetcher. I have created an example project which can be found at https://github.com/mwhapples/ReactiveUIActivation 

### Step to reproduce

1. Open the example project from https://github.com/mwhapples/ReactiveUIActivation
2. Build and run on Windows
3. Observe the Error
4. Compare with running on other platform such as Android

### Reproduction repository

https://github.com/mwhapples/ReactiveUIActivation

### Expected behavior

App will load and the page will be shown

### Operating system

Windows

### ReactiveUI Version

19.5.31

**Comment by ChrisPulman** [comment]
This should be resolved with the next release, thank you for raising the issue.
