### ISSUE TITLE
[Bug]: WireUpControls throws exception in net8.0-android

### ISSUE THREAD

**Issue by tommy10344** [reactiveui/ReactiveUI#3714]
### Describe the bug 🐞

When calling `ReactiveUI.ControlFetcherMixin.WireUpControls()` in a .NET 8 Android app (`net8.0-android`), even though the correct resource ID is specified, a ` MissingFieldException` is thrown.

Stacktrace:
```
Exception has occurred: System.MissingFieldException
Failed to wire up the Property XXX to a View in your layout with a corresponding identifier
    at ReactiveUI.ControlFetcherMixin.WireUpControls(Activity activity, ResolveStrategy resolveMembers) in /_/src/ReactiveUI/Platforms/android/ControlFetcherMixin.cs:166
    at ReactiveUI_WireUpControls_Issue.MainActivity.OnCreate(Bundle savedInstanceState) in /path/to/projects/ReactiveUI-WireUpControls-Issue/MainActivity.cs:19
    at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_(IntPtr jnienv, IntPtr native__this, IntPtr native_savedInstanceState) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Android.App.Activity.cs:3082
    at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPL_V(_JniMarshal_PPL_V callback, IntPtr jnienv, IntPtr klazz, IntPtr p0) in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:125
```

### Step to reproduce

1. Install .NET 8. (I installed `8.0.100`)
2. Create a new `net8.0-android` project using `dotnet new android` command.
3. Add reference to `ReactiveUI` version `19.5.39` 
4. Open `MainActivity.cs` and change it so that MainActivity inherits `ReactiveUI.ReactiveActivity`.
```cs
public class MainActivity : ReactiveActivity
```
5. Assign an ID(`android:id`) to the `TextView` in `activity_main.xml` and add a member to `MainActivity.cs` to wire it up.
```xml
    <TextView 
        android:id="@+id/app_text"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_centerInParent="true"
        android:text="@string/app_text"
    />
```

```cs
    [WireUpResource("app_text")]
    public TextView AppText { get; private set; }
```

6. Add a call to `WireUpControls()` after `SetContentView()` in `OnCreate()`.
```cs
this.WireUpControls(ControlFetcherMixin.ResolveStrategy.ExplicitOptIn);
```
7. Build and launch application.
8. `MissingFieldException` is thrown from `WireUpControls()`.

### Reproduction repository

https://github.com/tommy10344/ReactiveUI-WireUpControls-Issue

### Expected behavior

After launching the application, the TextView should be wired up correctly, and the initial screen should be displayed.

Build the same code with .NET 7 (`net7.0-android`), it works as expected. (Confirmed in the [`dotnet7` branch of the reproduction repository](https://github.com/tommy10344/ReactiveUI-WireUpControls-Issue/tree/dotnet7))

### Screenshots 🖼️

![MissingFieldException](https://github.com/reactiveui/ReactiveUI/assets/13437918/67c4a1ed-daaa-4534-b707-045e90af3cca)

### IDE

Visual Studio Code

### Operating system

Android

### Version

13

### Device

Emulator

### ReactiveUI Version

19.5.39

### Additional information ℹ️

.NET 8 seems to have changed access to Android resources, is this issue related to this?
https://devblogs.microsoft.com/dotnet/android-resource-designer-dotnet-8/

Reading the implementation of `WireUpControls()`, it looks like it uses reflection to reference the `Resource.Id` class in the assembly of the application itself.
https://github.com/reactiveui/ReactiveUI/blob/main/src/ReactiveUI/Platforms/android/ControlFetcherMixin.cs#L230

However, in .NET8, it seems that a new assembly called `_Microsoft.Android.Resource.Designer` is created and the `Resource.Id` class is generated there.
I am guessing that this may be related to the problem.
(I'm not very familiar with .NET, so sorry if I'm wrong)

**Comment by dpvreony** [comment]
can you try

```<AndroidUseDesignerAssembly>False</AndroidUseDesignerAssembly>```

if it works then you're correct it's a resource issue.

**Comment by tommy10344** [comment]
@dpvreony Thanks! Sorry for the late reply.

I added `<AndroidUseDesignerAssembly>False</AndroidUseDesignerAssembly>` to csproj and tried to build it and got the following build error.
```
/usr/local/share/dotnet/packs/Microsoft.Android.Sdk.Darwin/34.0.52/tools/Xamarin.Android.Resource.Designer.targets(146,3): error XA1034: Your project references '/Users/foo/.nuget/packages/reactiveui/19.5.39/lib/net8.0-android34.0/ReactiveUI.dll' which uses the `_Microsoft.Android.Resource.Designer` assembly, but you do not have this feature enabled. Please set the `AndroidUseDesignerAssembly` MSBuild property to `true` in your project file. [/path/to/ReactiveUI-WireUpControls-Issue/ReactiveUI-WireUpControls-Issue.csproj]
```

To use this setting, does ReactiveUI also need to have the same setting?
https://github.com/xamarin/xamarin-android/blob/main/Documentation/guides/building-apps/build-properties.md#androidusedesignerassembly
> .NET 8 Projects which choose to turn this setting off will not be able to consume references which do use it. If you try to use an assembly which does have this feature enabled in a project that does not, you will get a `XA1034` build error.

Or is there any other way?

**Comment by ChrisPulman** [comment]
Hi, I will try to take a look at this at the weekend, I will be travelling back to the UK from Brazil tomorrow if I have any chance during the flight I will take a look then.

**Comment by ChrisPulman** [comment]
So after some investigations it looks like there is a more widespread issue with this, for some reason the Resource returns no elements for net 8.0. I am trying to see if there is a different method of obtaining Resources with net 8. I will update on my findings and create a fix unless its a core bug with net 8

**Comment by ChrisPulman** [comment]
![image](https://github.com/reactiveui/ReactiveUI/assets/4910015/6eef2e12-6e3b-448f-8280-380b9e2504a5)
This shows the issue we are experiencing with net 8.0

**Comment by ChrisPulman** [comment]
https://devblogs.microsoft.com/dotnet/android-resource-designer-dotnet-8/
This explains the reason, I will work on fixing this ASAP

**Comment by ChrisPulman** [comment]
This will be resolved in the release in the next hour, thank you for raising this issue and sorry we took so long to resolve it.

**Comment by gerardvanderkruijs** [comment]
@ChrisPulman Amazing!!
Just installed the updated package and everything works like a charm again, thank you so much! 🙌

**Comment by tommy10344** [comment]
@ChrisPulman Thank you for resolving this issue!
I have updated to `19.6.12` and confirmed that it works as expected without throwing exceptions.
