### ISSUE TITLE
[Bug]: WinUI/WAS - ReactiveUI.WinUi nuget attempts to load the ReactiveUI.XamForms assembly when WhenActivated is called on a IActivatableViewModel

### ISSUE THREAD

**Issue by matthewacme** [reactiveui/ReactiveUI#3786]
### Describe the bug 🐞

In a WinUI 3 app project that has a dependency on the ReactiveUI.WinUI nuget package, if you add the `IActivatableViewModel` interface to a view model and implement the interface, then in the Constructor for that view model set up the WhenActivated Linq method in the constructor. When the Constructor is loaded, ReactiveUI raises an error of 
"Could not load file or assembly 'ReactiveUI.XamForms, Version=19.6.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified."

This is a bug, the XamForms assembly can not be referenced in a WinUI project, nor should it be needed

### Step to reproduce

1. start a new WinUI 3 App - Blank project 
![image](https://github.com/reactiveui/ReactiveUI/assets/11168104/383961e9-19d4-4e09-b0c9-73a3e3377c6d)

2. Add A Class and cal it  MainPageViewModel

3. on the main page add a Dependency property to the newly created MainPageViewModel

4. In the MainPage constructor, initialize the dependency property to a new instance of MainPageViewModel

5. Add ReactiveUI.WinUI nuget dependency to the project

6. Run the project, it runs fine

7. Stop Project.

8. Add the `IActivatableViewModel` interface to MainPageViewModel and implement it.

9. Modify the constructor for the `MainPageViewModel` to be like so

```
    public MainPageViewModel()
    {
        Activator = new ViewModelActivator();

        ( this ).WhenActivated(disposables =>
        {
            // Use WhenActivated to execute logic
            // when the view model gets activated.
           // do nothing, this is just to cause the bug
            // HandleActivation(disposables);
        });
    }
```
 
10.  Run it, and you will break on the line 
`( this ).WhenActivated(disposables =>`

with the error of

> System.IO.FileNotFoundException
>   HResult=0x80070002
>   Message=Could not load file or assembly 'ReactiveUI.XamForms, Version=19.6.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
>   Source=<Cannot evaluate the exception source>
>   StackTrace:
> <Cannot evaluate the exception stack trace>

If you put a breakpoint i

### Reproduction repository

https://github.com/xsgeek/ReactiveUI-WinUI-Bug

### Expected behavior

The WinUI project should run just fine with just a reference to the ReactiveUI.WinUI assembly.

### IDE

Visual Studio 2022

### Operating system

Windows 11

### Version

net7.0-windows10.0.22621.0

### Device

Windows

### ReactiveUI Version

19.6.1

**Comment by anaisbetts** [comment]
Are you breaking in on first-chance exceptions? This is expected but this exception should be handled

**Comment by matthewacme** [comment]
No, I am not catching it on First-chance exceptions.

The error is getting raised up into my code, so apparently the Reactive Code is NOT properly handling that first exception.

Here is a screen shot of it happening in the example code at the top level of the project and as you can see it's percolating all the way up to the top level app code and not being handled / suppressed in the library ...



***@***.***

***@***.***
Matthew C. Hintzen [he-him-his] | Windows Washer
*
w - ***@***.******@***.***>
p - 321.234.8839
*

**Comment by dpvreony** [comment]
see if the following workaround prevents the issue. you need one of these in app initialisation before ReactiveUI is called.

if you're not doing any custom Splat DI config.

```
ReactiveUI.PlatformRegistrationManager.SetRegistrationNamespaces(RegistrationNamespace.WinUI);
```

if you're doing any custom config to Splat etc. you'll need something along the lines of. (you might want this version anyway so it's clearer when ReactiveUI is being set up)

```
Locator.CurrentMutable.InitializeSplat();
Locator.CurrentMutable.InitializeReactiveUI(RegistrationNamespace.WinUI); 
```

If the Assembly scanning is the issue, this should prevent it.

**Comment by matthewacme** [comment]
Thanks so much David,

I'll put that in as soon as I squash this current bug I'm working on, and let you know in the Git Issue if that fixed it!

***@***.***
Matthew C. Hintzen [he-him-his] | Windows Washer
*
w - ***@***.******@***.***>
p - 321.234.8839
*

**Comment by matthewacme** [comment]
@dpvreony 

Thank you, that worked perfectly...

hopefully anyone else coming across this bug will find this answer.
