### ISSUE TITLE
[Bug]: Hot reload not working when referencing ReactiveUI.WinUI when targeting net7.0

### ISSUE THREAD

**Issue by SoggyBottomBoy** [reactiveui/ReactiveUI#3854]
### Describe the bug 🐞

I was recently incorrectly referencing ReactiveUI in a WinUI project. After changing to ReactiveUI.WinUI edit & continue and hot reload stopped working. I get the following error message:

> CS7038: Failed to emit module MyApp. Changing the version of an assembly reference is not allowed during debugging: 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' changed version to '7.0.0.0'.

If I remove the package or switch back to ReactiveUI the problem goes away.

### Step to reproduce

1. Create a WinUI project using the lastest WindowsAppSDK and target net7.0-windows10.0.19041.0
2. Add the Reactive.WinUI nuget package to the project
3. Debug the project
4. Edit some code to trigger an "Edit & Continue" or HotReload
5. Check the output from hot reload in the output window 

### Reproduction repository

https://github.com/reactiveui/ReactiveUI

### Expected behavior

This should happen...

### IDE

Visual Studio 2022

### Operating system

Windows

### ReactiveUI Version

20.1.1

**Comment by SoggyBottomBoy** [comment]
I can confirm that this is an issue with 20.1.1. I downgraded to 20.0.1 then triggered a hot reload without any problem. Upgraded back to 20.1.1 and triggered a hot reload same issue forcing me to close the application.

**Comment by ChrisPulman** [comment]
Thank you for raising this issue, I will try to locate the root cause and release an update if necessary

**Comment by glennawatson** [comment]
Is it the fact it's net7? Net 7 went out of support in may 2024 so reactiveui does not support it
