### ISSUE TITLE
Source generators

### ISSUE THREAD

**Issue by markrendle** [reactiveui/ReactiveUI#3864]
**Is your feature request related to a problem? Please describe.**

`PropertyChanged` and `Command`s required a lot of verbose, repetitive boilerplate code.

**Describe the solution you'd like**

Source generators could generate properties and commands from fields and methods, applying best practices along the way.

**Describe suggestions on how to achieve the feature**

I'm using some very basic source generators in an Avalonia UI project at the moment, for example the Command generator can only handle parameterless methods right now, but it's a start.

I copied the implementations to a gist: https://gist.github.com/markrendle/93ccfb62f2e2f87137148b9aaa57f02f

```csharp
public partial class LoginViewModel : ViewModelBase
{
    [ReactiveProperty] private string? _userName; // Generates UserName property
    [ReactiveProperty] private string? _password; // Generates Password property
    [ReactiveProperty] private bool _loggingIn; // Generates LoggingIn property

    [ReactiveCommand] // Generates LoginCommand command using CanLogin as canExecute
    private void Login()
    {
        LoggingIn = true;
        _userManager.Login(UserName, Password);
    }

    private bool CanLogin() => !LoggingIn && UserName is { Length: > 0 } && Password is { Length: > 0 };
}
```

**Additional context**

Obviously this is inspired by https://github.com/CommunityToolkit/dotnet/tree/main/src/CommunityToolkit.Mvvm.SourceGenerators

**Comment by ChrisPulman** [comment]
You can find out how to use the Source Generators here:
https://www.reactiveui.net/docs/handbook/view-models/boilerplate-code.html

**Comment by ChrisPulman** [comment]
Closing this as the requested feature already exists
