### ISSUE TITLE
[Bug]: reactiveui.fody 19.5.41 bool value does not notify UI when using [Reactive] and bool value changed

### ISSUE THREAD

**Issue by SeptMorning** [reactiveui/ReactiveUI#3867]
### Describe the bug 🐞

I have a class named SyncAssistVM : ReactiveObject. situation：
`[Reactive] public bool PauseBtnEnable { get; set; } = false;，`
it does not notify ui when the value changed;  so far I've only seen this with bool.

### Step to reproduce

```
public bool SyncBtnEnable
    {
        get => _syncBtnEnable;
        set => this.RaiseAndSetIfChanged(ref _syncBtnEnable, value);
    }
```
it works on value changed.

### Reproduction repository

https://github.com/reactiveui/ReactiveUI

### Expected behavior

[Reactive] should work with bool just like it works with string property changed

### Screenshots 🖼️

![image](https://github.com/user-attachments/assets/bae8939a-69f3-4c12-a9a4-9c14c515e9f0)

### Operating system

Windows, Mac OS

### Version

windows 11, 10, macos 14.5

### Device

laptop

### ReactiveUI Version

19.5.41

**Comment by ChrisPulman** [comment]
If you are able to put a simple repo together to demonstrate the issue you are experiencing, this will help us to help you resolve the issue.

**Comment by ChrisPulman** [comment]
If your creating a new project you could also try using ReactiveUI.SourceGenerators https://www.reactiveui.net/docs/handbook/view-models/boilerplate-code.html

**Comment by SeptMorning** [comment]
> If your creating a new project you could also try using ReactiveUI.SourceGenerators https://www.reactiveui.net/docs/handbook/view-models/boilerplate-code.html
> 
> > **[The manual way to create properties in ReactiveUI | An advanced, composable, reactive model-view-viewmodel framework](https://www.reactiveui.net/docs/handbook/view-models/boilerplate-code.html)**

thank you, this solution is better.
