### ISSUE TITLE
[Bug]: .net 8.0 nuget add ReactiveUI.wpf  warn

### ISSUE THREAD

**Issue by yangl1025** [reactiveui/ReactiveUI#3895]
### Describe the bug 🐞

已使用“.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1”而不是项目目标框架“net8.0-windows8.0”还原包“ReactiveUI.WPF 20.1.1”。此包可能与项目不完全兼容

### Reproduction repository

https://github.com/reactiveui/ReactiveUI

### Expected behavior

This should happen...

### IDE

Visual Studio 2022

### Operating system

windows

### Version

20.1.1

### ReactiveUI Version

20.1.1

**Comment by dpvreony** [comment]
Please ensure that you are targeting at least windows10.0.19041.0

- `<TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>`
