### ISSUE TITLE
[Bug]: DynamicData 9 breaks ReactiveUI.Validation

### ISSUE THREAD

**Issue by Nextra** [reactiveui/ReactiveUI#3905]
### Describe the bug 🐞

This bug was reported a while ago in the Validation repository: https://github.com/reactiveui/ReactiveUI.Validation/issues/679

Since [20.1.52](https://github.com/reactiveui/ReactiveUI/releases/tag/20.1.52) now includes DynamicData 9 by default (via #3875), it is much more likely for users to hit this bug. Raising this here purely for awareness.

Reverting to 20.1.1 fixes the issue.

### Step to reproduce

1. Start a project with ReactiveUI 20.1.52 and ReactiveUI.Validation 4.0.9
2. Build a validatable ViewModel using `ReactiveValidationObject`
3. Instantiate this ViewModel
4. Exception `MissingMethodException` is thrown and probably crashes the application

### Expected behavior

ReactiveUI.Validation should be compatible with DynamicData 9.

### ReactiveUI Version

20.1.52

**Comment by ChrisPulman** [comment]
Thank you for your feedback, I will update the ReactiveUI.Validation to provide the relevant compatibility as soon as possible.

**Comment by Nextra** [comment]
Release [4.1.1](https://github.com/reactiveui/ReactiveUI.Validation/releases/tag/4.1.1) of ReactiveUI.Validation is now available which includes the fix for this incompatibility: https://github.com/reactiveui/ReactiveUI.Validation/pull/691. 

No update to the main ReactiveUI package is required. Thanks @ChrisPulman.
