### ISSUE TITLE
[Bug]: Wrong Nuget Version

### ISSUE THREAD

**Issue by GerdWB** [reactiveui/ReactiveUI#3931]
### Describe the bug 🐞

When creating a new .Net 6 Wpf Application and after adding NuGet Package ReactiveUI.WPF  20.1.63 I get the Compiler Warning:
warning NU1701: Package 'ReactiveUI.WPF 20.1.63' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework 'net6.0-windows7.0'. This package may not be fully compatible with your project.

### Step to reproduce

1. Create a new .Net6 WPF Application in VisualStudio 2022
2. Add NuGet Package ReactiveUI.WPF  20.1.63
3. Compile 
4. Check Output window for warnings

### Reproduction repository

https://github.com/reactiveui/ReactiveUI

### Expected behavior

The correct .Nuget Package ReactiveUI.WPF  20.1.63 for .Net 6 should be installed

### IDE

Visual Studio 2022

### Operating system

Windows 11

### ReactiveUI Version

20.1.63

**Comment by glennawatson** [comment]
https://www.reactiveui.net/docs/guidelines/platform/windows-presentation-framework.html

The generic -windows in the target framework won't work due to system.reactive not supporting it.

**Comment by GerdWB** [comment]
Ok, thanks, that works.
Normally I just leave the version as its is provided by the VisualStudio template.

**Comment by glennawatson** [comment]
Yeah it's a bit of a pain. The theory is more up to date versions allow you to get bug fixes but still target old versions.
