### ISSUE TITLE
Strong Name

### ISSUE THREAD

**Issue by ymerej** [reactiveui/ReactiveUI#43]
Paul, is it unreasonable to expect that the ReactiveUI should be strong named so that I can easily use it within a solution where everything is strong named?

I have used ReactiveUI on other projects and it has worked very well.  Great framework!

Thanks
Jeremy

**Comment by AArnott** [comment]
@paulcbetts Your argument to not strong-name sign your application is only useful if in fact the user you're talking to is writing an application (and thus is the terminal point for consumption). Yes, an app author can decide to not strong-name sign. And that would probably be fine. 

As you say, there are only a couple real tangible benefits to strong-name signing at the app-level. You mentioned one: loading more than one version of the assembly at a time. The one you did not mention is GAC'ing assemblies, which requires that they be strong-name signed. And sure, while there are strong arguments to be made against GAC'ing your assemblies, there are also tangible reasons for some apps to have a presence in the GAC, particularly on older versions of the CLR. 

But for library authors, they can't simply decide to not strong-name sign. It's not always up to them. Most likely, they've already shipped and are already strong-name signed. To stop strong-name signing would be a significant breaking change (as not even binding redirects would allow it to work I believe without *all* consumers recompiling). That would be a very strong point *for* strong-name signing: keep everything working. No real way around that. Sure, you can argue it was a problem that strong-name signing created to begin with, and perhaps you'd be right, but that doesn't really matter, does it? Regardless of who started the "problem", you are where you are. And you can keep the system running smoothly by continuing to strong name sign. That then limits the existing library author to only depend on other libraries that also strong-name sign.
So should strong-name signing be propagated to those other libraries? Yes. It promotes the open source agenda, which is to share code, get feedback, get more contributions and reduce redundancy. 
What is the cost to strong-name signing? I can't think of any. It may require that folks use binding redirects in their app.config files, but that's not really a big problem, especially now when nuget will write all that for them so it's basically automatic.

**Comment by jlaanstra** [comment]
> What is the cost to strong-name signing?

The cost for strong-name signing of ReactiveUI has been clearly stated at http://log.paulbetts.org/a-modest-proposal-strong-naming-carbon-offsets/

The other option is to sign it yourself. It has been stated plenty of times already, but just to repeat it: ReactiveUI will never be strong-name signed.

**Comment by AArnott** [comment]
@jlaanstra to be clear, I don't use reactiveui and have no interest in whether it strong name signs or not.
You say @paulcbetts states clearly the costs of strong name signing at that link. I've read it. I don't see a *single* cost stated. He says there are costs, but he doesn't state a single one.

**Comment by cbordeman** [comment]
This is inane.  Strongly sign it, or take it off of nuget.  I'm writing a VS extension and I don't have the option not to strongly sign.  Everyone in the world strongly signs their Nuget stuff, yet this project won't, why?  Because forkers would be confused?  Really?

I feel this issue is a big reason ReactiveUI hasn't really caught on as much as it should.

**Comment by paulcbetts** [comment]
We don't need any more discussion on this.
