### ISSUE TITLE
Change CommonReactiveSource to auto register cell types

### ISSUE THREAD

**Issue by tberman** [reactiveui/ReactiveUI#479]
I am opening this as an issue to build consensus before doing any of the work.

So right now the API is NSString based and assumes you have registered the table cell yourself. Would there be any interest to change it to be Type based, and automatically register the types?

Thoughts?

cc @meteficha

**Comment by ghuntley** [comment]
@tberman / @paulcbetts are we still NSString based? Keep this open for future PR?

**Comment by kentcb** [comment]
No longer `NSString`-based.
