### ISSUE TITLE
Better handling of Nullable<T> in Binding

### ISSUE THREAD

**Issue by clairernovotny** [reactiveui/ReactiveUI#481]
When binding to/from UI elements, it should be easier to bind to nullables.

The mechanism should have a conversion too as some controls in iOS return doubles (like UIStepper.Value), but I want to bind it to a `Nullable<int>` as it'll never have a decimal value.

Other things to take into account:
- default values other than default(T)
- conversions back for two-way binding

**Comment by glennawatson** [comment]
Going to reopen since seems useful but no updates

**Comment by ChrisPulman** [comment]
Can someone re-evaluate this with the latest source, nullable types should now be catered for with Bindings, but would be good to get a fresh view on this.
