### ISSUE TITLE
InvokeCommand on WhenActivated

### ISSUE THREAD

**Issue by jen20** [reactiveui/ReactiveUI#535]
It would nice if you could do something like this in the constructor of a View:

```csharp
public MyView() {
    this.WhenActivated(d => {
            //Set up all the bindings here
        })
        .InvokeCommand(ViewModel, vm => PrepareStuffCommand);
}
```

Assuming it's not already possible and I'm missing the syntax for it it seems that it would be possible by changing the WhenActivated mixin to return an IObservable<Unit> such that the invoke command can chain from that.

Any thoughts?

**Comment by kentcb** [comment]
This also assumes there's never any value to disposing of the value returned by `WhenActivated`. I know you've said as much on Slack, @paulcbetts, but I thought it worth pointing out anyway. Presumably there must be _some_ benefit to disposing, even if not strictly required.

**Comment by moswald** [comment]
PR #977 should address this, although you're still not guaranteed to have a ViewModel.
