### ISSUE TITLE
Meta: RxUI Chat Room

### ISSUE THREAD

**Issue by anaisbetts** [reactiveui/ReactiveUI#622]
Hey guys, I've created a new Slack chat room for RxUI owners (and anyone else who's interested in chatting Rx / RxUI). 

I've added some of you who I'm fairly sure would be interested in anyways, but if I missed you and you're interested, send me an Email to paul@paulbetts.org with the Email you want me to sign you up as. 

/cc @reactiveui/owners

**Comment by bimawa** [comment]
Slack useless with a lot of companies, mb u have a IRC channel mirror? Like we do in reactNative community?

**Comment by JackUkleja** [comment]
Why Slack over Gitter.im channel? Gitter.im seems likely to become the defacto place for discussing github projects, and is easy to join without setting up a new account for anyone already using GH. Sadly the RxUI channel seems to be dead: https://gitter.im/reactiveui/ReactiveUI
