### ISSUE TITLE
RxUI6 Preview 6 - Splat missing

### ISSUE THREAD

**Issue by shiftkey** [reactiveui/ReactiveUI#631]
Repro steps:
1. Install reactiveui-5.99.6-beta into a blank WPF 4.5 project: 

```
Install-Package reactiveui-pre
```
1. Create a simple viewmodel:

```
    public class ShellViewModel : ReactiveObject, IShellViewModel
    {
        bool _isLoading;
        public bool IsLoading
        {
            get { return _isLoading; }
            private set { this.RaiseAndSetIfChanged(ref _isLoading, value); }
        }
    }
```

**Expected:** things be compiling
**Actual:** compiler error on the `RaiseAndSetIfChanged`

```
The type 'Splat.IEnableLogger' is defined in an assembly that is not referenced. You must add a reference to assembly 'Splat, Version=1.3.1.0, Culture=neutral, PublicKeyToken=null'
```

Seems to be related to the declared dependencies for reactiveui-core: https://www.nuget.org/packages/reactiveui-core/5.99.6-beta

No error was raised with the previous preview:
https://www.nuget.org/packages/reactiveui-core/5.99.5-beta

**Comment by ryanthemadone** [comment]
This is still happening with the latest Nuget package.

**Comment by mgnslndh** [comment]
This problem is still occuring on reactiveui nuget 6.5.0. It seems to reference Splat 1.0.0 where IEnableLogger is not found. If I get latest Splat before ReactiveUI it works fine.

**Comment by Kintar** [comment]
As of 2015-11-19, this is still occurring with ReactiveUI 6.5.0.

**Comment by jbhaywood00** [comment]
Same issue as #928?

**Comment by Kintar** [comment]
Ah, yes it is.  Sorry for reviving a dead ticket.
