### ISSUE TITLE
MessageBus - Any Type Listener

### ISSUE THREAD

**Issue by prasannavl** [reactiveui/ReactiveUI#655]
Is there a way to listen to any message of any type from the message bus?

At the moment, to listen to, 

MessageBus.Current.SendMessage(4);
It has to be  MessageBus.Current.Listen<int>();

Unfortunately, MessageBus.Current.Listen<object> listen only to a direct object type, so it works only if its sent value is boxed.

Is there any way to listen to all types?
Say, to Log every message that comes through the bus under a different subscription.

**Comment by jlaanstra** [comment]
This is currently not possible. Note that it is recommended in the [docs](https://github.com/reactiveui/ReactiveUI/blob/master/ReactiveUI/MessageBus.cs) not to use the MessageBus.
