### ISSUE TITLE
After upgrading to ReactiveUI 6.0, WPF bindings break after about 10 seconds after application startup

### ISSUE THREAD

**Issue by patroza** [reactiveui/ReactiveUI#661]
First off, congrats on the major new release!!

I realize the error description is rather vague and does not really help, but it's a large app and I have no idea yet about the source of the problem, still trying to find whats going on :S

After about 10 seconds bindings seem to randomly break and my application no longer functions properly. Any suggestions what this might be?
(Still using legacy reactivecommand btw).

Thanks

**Comment by ElijahReva** [comment]
Guys, I see that same issue again when using MahApps.Metro 1.6.2 on .net 4.7.1.
