### ISSUE TITLE
Good Examples

### ISSUE THREAD

**Issue by WonderPanda** [reactiveui/ReactiveUI#687]
I'm sure that I'm not the only who has mentioned this but there is a definite lack of solid examples/documentation when trying to look at building an application using RxUI, especially with the release of version 6. The only content I've been able to find that's applicable are on @paulcbetts  personal blog and some half-finished (perhaps out of date with the new version) readmes in the docs branch.

The framework could desperately use some complete working examples of applications built on the different platforms it supports. I've found that the team at Adaptive have done some amazing work with Rx in WPF, HTML5, iOS and Windows Phone environments with an open source and well documented simulated trading application:
https://github.com/AdaptiveConsulting/ReactiveTrader

They seem to be rolling with their own implementation of MVVM leveraging Rx. Perhaps there would be opportunity to alter their codebase to leverage all the fantastic tools in ReactiveUI?

Either way it would be great to see some work on this front. I can personally volunteer my own time to work on a WPF sample application that could be open sourced but the lack of anything to follow is a big deterrent. Even knowing how to set up a MainViewModel properly is stumping me right now. Is there anyone from this community who I could collaborate with or even ask questions periodically about proper convention to build such a sample application to help other newcomers?

**Comment by ghuntley** [comment]
RxUI 6.3 example by @RolandPheasant at https://github.com/RolandPheasant/TradingDemo who also just published  https://github.com/RolandPheasant/DynamicData which is a comprehensive library of reactive extensions, which are used to manage in-memory collections. As the source collection changes the operators receive a changeset which enables them to self-maintain.

**Comment by RolandPheasant** [comment]
@ghuntley The best way to illustrate anything is by example which is why I put together the trading demo as a show case for dynamic data. I saw  ReactiveTrader by adaptive which personally I think is a tool for selling their skills as a company rather than as an education illustration.  This is why I have made each screen in the trading demo very simple so the code is easy to follow.

I have several more screens in mind which when I get a chance I will implement.  Although I set it up as living documentation for Dynamic Data, the more I look at ReactiveUI to more inclined I am to embrace it.  I think ReactiveUI and Dynamic Data complement each other very well which is why I wrote the adaptor see https://www.nuget.org/packages/DynamicData.ReactiveUI/

So perhaps going forward I will get rid of my crap mvvm implementation, use ReactiveUI and make it a living document for both.

**Comment by paulcbetts** [comment]
ReactiveTrader is a good example for how to use Rx in an API, but when they get to the actual UI layers, they fall back to imperative coding city. It's still worth looking at of course, just know that you can do far better :)

**Comment by RolandPheasant** [comment]
Well put Paul

**Comment by ade2la** [comment]
Visual Studio Project Templates will be highly appreciated

**Comment by ghuntley** [comment]
@ade2la preferred way of doing VS templates would be via http://sidewaffle.com/

**Comment by DarekDan** [comment]
Which parts of documentation and samples need the most help at the moment, @paulcbetts ? I hear that the best way to learn is to teach, so rolling my sleeves up to help with anything I can.

**Comment by ghuntley** [comment]
Welcome @DarekDan - have asked @paulcbetts to send over a invite to you can come discuss in slack, keen an eye out for the invite. Have a great of the following https://github.com/reactiveui/ReactiveUI/pull/771#issuecomment-67897111 and as soon as your in slack send send a message to @rdavisau and @ghuntley

**Comment by kondaskondas** [comment]
Hi, could someone tell me if i'm doing this right?, i made a  [Post](https://medium.com/@kondas/wpf-reactive-ui-firsts-steps-f8692c6901bb) about using ReactiveUI and a [GitHub repository](https://github.com/kondaskondas/FirstsStepsRUI).

**Comment by alexeyzimarev** [comment]
@jen20 gave a three hours talk on Progressive .NET 2014 about ReactiveUI, here is the repo https://github.com/jen20/ProgNET2014, here is the video https://skillsmatter.com/skillscasts/5217-building-reactive-user-interfaces (free, need to log in)

**Comment by jen20** [comment]
That talk covered Reactive UI 5 rather than 6 (6 wasn't released at that
point) - it's quite likely deficient in other ways too :-)

James

**Comment by alexeyzimarev** [comment]
Well, about a year ago I asked about RxUI docs and got an advice to watch the original Pau's video from, don't know, five or six years ago? When I said something like "it's too old" the answer was - concepts are still valid! I believe, most of the concepts that you touched in the talk are still valid as well :)

**Comment by ghuntley** [comment]
@shiftkey presentation on ReactiveUI v6 + WPF at NDC 2014 

code: https://github.com/shiftkey/octohipster
presentation: https://vimeo.com/97329155

**Comment by pdoh00** [comment]
This is a work in progress.  Xamarin app using ReactiveUI 6.0.x.x and Xamarin Forms.

https://github.com/pdoh00/Time2Brew

**Comment by ghuntley** [comment]
@RolandPheasant has been busy....

![](https://dynamicdataproject.files.wordpress.com/2015/03/logviewer3.gif)

Blog Entry: http://dynamic-data.org/2015/03/23/log-entry-viewer-using-dynamic-data-and-reactiveui/
Code: https://github.com/RolandPheasant/Dynamic.Trader

**Comment by ghuntley** [comment]
The demonstration application for Telephony uses RXUI6 on all mobile platforms (iOS, Android, Windows Phone) although currently only iOS and Android are implemented.

https://github.com/ghuntley/telephony

**Comment by underwater** [comment]
How many hours of work would it take to put together documentation or a video series on v.6 ?  I propose we estimate the budget and open a kickstarter project and try to reach potential supporters by posting the link here to see if the sufficient funds are raised, to justify the time the author will dedicate to this....

**Comment by ferbraz89** [comment]
I would kill for a pluralsight course about this topic.

**Comment by omares** [comment]
Hey i stumbled accross http://reactiveui.readthedocs.org/ - its not complete and as i understand its build upon the github resources but at least the content is more convinient to browse.

**Comment by ghuntley** [comment]
@omares Yep that's issue #771 - I can grant you or anyone else direct access to edit the pull request branch that RTD is being built off. Email @paulcbetts for invitation into the slack channel.

**Comment by ghuntley** [comment]
@pdoh00 has contributed written visual studio snippets for usage w/RXUI6 https://gist.github.com/pdoh00/7435255

**Comment by ghuntley** [comment]
Good article from 2013 - http://ianreah.com/2013/11/24/cross-platform-mvvm-with-reactiveui-and-xamarin.html

**Comment by abrahamja** [comment]
Any sample available on Xamarin.iOS with ReactiveUI and SQLite?

**Comment by gluck** [comment]
@abrahamja maybe https://github.com/paulcbetts/starter-mobile ?

Alternatively searching github for [reactiveui+sqlite+ios](https://github.com/search?l=xml&o=desc&q=reactiveui+sqlite+ios&s=indexed&type=Code&utf8=%E2%9C%93) can hint you at such projects.

**Comment by ghuntley** [comment]
![68747470733a2f2f7261772e6769746875622e636f6d2f74686564696c6c6f6e622f436f64654875622f6d61737465722f53637265656e73686f74732f496d616765332e706e67](https://cloud.githubusercontent.com/assets/127353/11969468/fdcc4ee8-a96d-11e5-9207-9f6856ae6013.png)
![68747470733a2f2f7261772e6769746875622e636f6d2f74686564696c6c6f6e622f436f64654875622f6d61737465722f53637265656e73686f74732f496d616765342e706e67](https://cloud.githubusercontent.com/assets/127353/11969470/fdd2d18c-a96d-11e5-9c64-fdc214260522.png)


Author: @thedillonb 
Website: http://dillonbuchanan.com/CodeHub/

Apple: https://itunes.apple.com/us/app/codehub-github-for-ios/id707173885?ls=1&mt=8

Source Code (!): https://github.com/thedillonb/CodeHub

**Comment by kentcb** [comment]
[Workout Wotch](https://github.com/kentcb/WorkoutWotch) is a Xamarin Forms (iOS + Android) app I wrote that uses ReactiveUI.

![Animation](https://raw.githubusercontent.com/kentcb/WorkoutWotch/master/Art/Animation.gif)

**Comment by ghuntley** [comment]
WPF + RxUI 6.5 @ https://github.com/kondaskondas/FirstsStepsRUI by @kondaskondas. Corresponding blog post @ https://kondaskondas.wordpress.com/2015/02/12/wpf-reactiveui-binding-and-routing-tutorial/

**Comment by DarekDan** [comment]
@ghuntley A link to LiveTemplates would be appreciated.

@kentcb Great looking example!

**Comment by ghuntley** [comment]
@derekdan I think these are the live templates @kondaskondas was referring to.

https://gist.github.com/pmbanka/b4f51b5d3b055a2cdc97

Personally I use and recommend https://github.com/kswoll/ReactiveUI.Fody

**Comment by ghuntley** [comment]
Example of ReactiveUI v6.5 and a ViewModel written in F# by @TeaDrivenDev - https://github.com/TeaDrivenDev/ReactiveUI.Samples/blob/fsharp/ReactiveUI.Samples.Basics.FSharp/ViewModels.fs#L121

**Comment by TeaDrivenDev** [comment]
@ghuntley I think it's v6.1; it's a direct port of the `ReactiveUI.Samples.Basics` project, and the samples currently all use ReactiveUI 6.1.

**Comment by ghuntley** [comment]
https://github.com/flagbug/Espera.Mobile by @flagbug uses Rx6.5 and Xamarin Android. This is the mobile counterpart of https://github.com/flagbug/Espera which is Rx6.5, Caliburn and WPF.

**Comment by ghuntley** [comment]
https://github.com/moswald/RxUI-UWP-Sample by @moswald for UWP .Net Native and RxUI v7 (ie. building from source)

**Comment by eightrivers** [comment]
Is there any references on how to use ReactiveUI in winfom based application?

**Comment by GiusepeCasagrande** [comment]
A very basic sample of how to use Routed navigation with Xamarin.Forms 2.3.2 and RxUI 7: https://github.com/GiusepeCasagrande/RoutingSimpleSample/

**Comment by huyngoduc** [comment]
Do you guys have any sample that works for Winform + DataGridView.

**Comment by fskroes** [comment]
Hi all, I recently starting with Reactive Extensions and also came across ReactiveUI, but do any of you know a basic example on how to use ReactiveUI for iOS and Android in native Xamarin, so not Xamarin.Forms?

**Comment by assassin316** [comment]
Seeing as how there are many posts in this thread, I'm wondering if it would make sense for the ReactiveUI team to provide a simple bootstrapped solution which consists of basic projects for each platform (WinForms, WPF, iOS-Xamarin-UWP with Xamarin Forms). This way, when someone wants to dive into REactiveUi, they can simply start off from this basic "Skeleton" solution and not have to worry about bootstrapping.

**Comment by biozal** [comment]
any examples on how to handle universal applications in Xamarin for both tablet and non-tablet (phone and tablet) on both IOS and Android?

**Comment by punker76** [comment]
[Simple Music Player](https://github.com/punker76/simple-music-player) using now ReactiveUI 7.2 (MahApps.Metro, WPF 4.5+)

![image](https://cloud.githubusercontent.com/assets/658431/23482769/931ece54-fed0-11e6-9d46-9ca0bd24a079.png)

**Comment by voltagex** [comment]
Where's a good "hello world"? An unsorted Issues thread is a little overwhelming when I've just started looking at the framework.

**Comment by aalmada** [comment]
@voltagex Try this one. It's based on a Xamarin tutorial. https://github.com/aalmada/reactive-dev-days-lab

**Comment by JonDouglas** [comment]
https://github.com/JonDouglas/BeingReactive - Xamarin.Android sample

**Comment by yehorhromadskyi** [comment]
@JonDouglas Hi, thank you for your sample. I was curious, where I should initialize my all startup stuff, like  IoC container registrations, etc. on Android, in my main activity? Thanks in advance.

**Comment by JonDouglas** [comment]
@yehorhromadskyi You should do it in a Custom Application class. You should be able to take any existing Xamarin IoC example as a baseline. However Splat seems to do a good enough job with it's service locator.

https://github.com/RobGibbens/Xamarin.IoC

**Comment by yehorhromadskyi** [comment]
@JonDouglas Thank you, that was helpful!

**Comment by gitbash-basher** [comment]
> @axefrog there's a set of docs relevant to RxUI 6 here: https://github.com/reactiveui/ReactiveUI/tree/master/docs
> 
> I appreciate the questions raised here, and I'd love to clarify the questions/issues you are grappling with about RxUI, so those gaps can be addressed...

404 not found :(

**Comment by glennawatson** [comment]
We been getting a decent set of samples here now https://github.com/reactiveui/reactiveui.samples
