### ISSUE TITLE
Question: MessageBus NotAWeakReference

### ISSUE THREAD

**Issue by mwpowellhtx** [reactiveui/ReactiveUI#688]
See also [MessageBus.cs](https://github.com/reactiveui/ReactiveUI/blob/master/ReactiveUI/MessageBus.cs). Am I correct in observing (pardoning the pun), that doing something like this: using WeakReference = NotAWeakReference, would be analog to anticipating there actually being WeakReference, which I take it NAWR is a stand-in for the said WR? Thank you...

**Comment by DavidTangWei** [comment]
I am agree with @mwpowellhtx . I have read the blog [ http://log.paulbetts.org/messagebus-and-why-you-shouldnt-use-it/]( http://log.paulbetts.org/messagebus-and-why-you-shouldnt-use-it/). This blog want to illustrate that as message bus is the global variable , it will invoke the memory leak (the observer which subsribe to this can not be collected by gc). But If we change the NotAWeakReference (strong reference) class to WeakReference, it can be collected by gc, this problem will be solved. I do not know the reason why you design this NotAWeakReference class. Can you explain this ? Thank You !

**Comment by mwpowellhtx** [comment]
Wow, it's been years since I've seen this. While the immediate concern is no longer there, it's not to say a message bus wouldn't be interesting as a possible future concern.
