### ISSUE TITLE
Add a ReactiveDictionary

### ISSUE THREAD

**Issue by TheGrandUser** [reactiveui/ReactiveUI#695]
A ReactiveDictionary, IReactiveDictionary, and IReadOnlyReactiveDictionary would all be a very useful to have.

**Comment by Asido** [comment]
Any progress on this?

**Comment by paulcbetts** [comment]
Why do people want this? The utility of it is way less because UI elements don't know how to natively bind to dictionaries

**Comment by TheGrandUser** [comment]
Less so for views binding to it as it is just generally useful to have a dictionary collection that's reactive. I find that I'm using the ReactiveUI throughout my application, not just as a communication method from the viewmodel to the view.

**Comment by Asido** [comment]
Exactly as TheGrandUser said. I am extensively utilizing reactive objects in an online game, where logic and communication with game server is in PCL and controllers/managers for each subsystem are reactive. More often than not these managers are not being directly bound to UI.

**Comment by flagbug** [comment]
I think this is a good feature request for https://github.com/RolandPheasant/DynamicData

**Comment by bradphelan** [comment]
I found one in my code today :)

    public class ReactiveDictionary<TKey, TObject> 
    {
        private readonly IDictionary<TKey, TObject> _Database 
            = new ConcurrentDictionary<TKey, TObject>();

        private readonly MultiLookup<TKey, IObserver<ReactiveDictionary.Event<TObject>>,List<IObserver<ReactiveDictionary.Event<TObject>>>> _Subscribers 
            = new MultiLookup<TKey, IObserver<ReactiveDictionary.Event<TObject>>, List<IObserver<ReactiveDictionary.Event<TObject>>>>();

        private readonly List<IObserver<ReactiveDictionary.Event<TObject>>> _GlobalSubscribers 
            = new List<IObserver<ReactiveDictionary.Event<TObject>>>();

        public IEnumerable<TKey> Keys => _Database.Keys;
        public int Count => _Database.Count;

        public IObservable<ReactiveDictionary.Event<TObject>> Listen(TKey key)
        {
            return Observable.Create<ReactiveDictionary.Event<TObject>>
                (observer =>
                 {
                     if (_Database.ContainsKey(key))
                     {
                        var e = new ReactiveDictionary.Event<TObject>(ReactiveDictionary.EventEnum.New, _Database[key]);
                         observer.OnNext(e);
                     }
                     _Subscribers.Add(key,observer);
                     return Disposable.Create(() => _Subscribers.Remove(key,observer));
                 });
        }
        public IObservable<ReactiveDictionary.Event<TObject>> Listen()
        {
            return Observable.Create<ReactiveDictionary.Event<TObject>>
                (observer =>
                 {
                     foreach (var kvp in _Database)
                     {
                         observer.OnNext(new ReactiveDictionary.Event<TObject>(ReactiveDictionary.EventEnum.New, kvp.Value));
                     }
                     _GlobalSubscribers.Add(observer);
                     return Disposable.Create(() => _GlobalSubscribers.Remove(observer));
                 });
        }

        public void Set(TKey key, TObject o)
        {
            var e = new ReactiveDictionary.Event<TObject>(ReactiveDictionary.EventEnum.New, o);
            _Subscribers[key].ForEach(s => s.OnNext(e));
            _GlobalSubscribers.ForEach(s=>s.OnNext(e));
            _Database[key] = o;
        }

        public Maybe<TObject> Get(TKey key) => _Database.ContainsKey(key) ? _Database[key] : Maybe<TObject>.None;

        public void Remove(TKey key)
        {
            if(!_Database.ContainsKey(key))
                return;

            var e = new ReactiveDictionary.Event<TObject>(ReactiveDictionary.EventEnum.Removed, _Database[key]);

            _Subscribers[key].ForEach(s => s.OnNext(e));
            _GlobalSubscribers.ForEach(s=>s.OnNext(e));

            _Database.Remove(key);

        }
    }

even have a spec for it

    public class ReactiveDictionarySpec
    {
        [Fact]
        public void ReactiveDictionaryShouldWork()
        {
            var d = new ReactiveDictionary<string, object>();
            d.Set("dog",15);
            int cat = 0;
            int cat2 = 0;
            int dog = 0;
            d.Listen("cat").Subscribe(e =>
                                      {
                                          switch (e.EventType)
                                          {
                                              case ReactiveDictionary.EventEnum.New:
                                                  cat++;
                                                  break;
                                              case ReactiveDictionary.EventEnum.Removed:
                                                  cat--;
                                                  break;
                                              default:
                                                  throw new ArgumentOutOfRangeException();
                                          }
                                      });
            d.Listen("cat").Subscribe(e =>
                                      {
                                          switch (e.EventType)
                                          {
                                              case ReactiveDictionary.EventEnum.New:
                                                  cat2++;
                                                  break;
                                              case ReactiveDictionary.EventEnum.Removed:
                                                  cat2--;
                                                  break;
                                              default:
                                                  throw new ArgumentOutOfRangeException();
                                          }
                                      });
            d.Listen("dog").Subscribe(e =>
                                      {
                                          switch (e.EventType)
                                          {
                                              case ReactiveDictionary.EventEnum.New:
                                                  dog++;
                                                  break;
                                              case ReactiveDictionary.EventEnum.Removed:
                                                  dog--;
                                                  break;
                                              default:
                                                  throw new ArgumentOutOfRangeException();
                                          }
                                      });

            cat.Should().Be(0);
            cat2.Should().Be(0);
            dog.Should().Be(1);

            d.Set("foo", 10);

            cat.Should().Be(0);
            cat2.Should().Be(0);
            dog.Should().Be(1);

            d.Set("cat", 1);

            cat.Should().Be(1);
            cat2.Should().Be(1);
            dog.Should().Be(1);

            d.Set("dog", 1);

            cat.Should().Be(1);
            cat2.Should().Be(1);
            dog.Should().Be(2);


            d.Remove("foo");

            cat.Should().Be(1);
            cat2.Should().Be(1);
            dog.Should().Be(2);


            d.Remove("cat");

            cat.Should().Be(0);
            cat2.Should().Be(0);
            dog.Should().Be(2);

            d.Remove("cat");

            cat.Should().Be(0);
            cat2.Should().Be(0);
            dog.Should().Be(2);

            d.Remove("dog");

            cat.Should().Be(0);
            cat2.Should().Be(0);
            dog.Should().Be(1);
        }
        
    }

**Comment by bradphelan** [comment]
If anybody is positive about it I can add it to reactiveui.
