### ISSUE TITLE
ReactiveCommand.ThrownExceptions must be "subscribed" to directly

### ISSUE THREAD

**Issue by ghotiphud** [reactiveui/ReactiveUI#702]
If I set up a command like so:  (On Android, haven't tried elsewhere)

    Command = ReactiveCommand.CreateAsyncTask(x => AsyncThingy());

    Command.ThrownExceptions.Select(ex => ex.Message).ToProperty(this, t => t.Message);

Then ThrownExceptions acts as if I haven't subscribed to it.

So, to try and diagnose, I added:

    Command.ThrownExceptions.Subscribe(ex => Debug.WriteLine(ex.Message));

Which of course fixed the issue.  Is this an issue with the Select extension method or something in how ThrowExceptions is implemented?

**Comment by jlaanstra** [comment]
Tracking this in #785.
