### ISSUE TITLE
Crashes when PropertyChangedEventArgs.PropertyName is null

### ISSUE THREAD

**Issue by frogger3d** [reactiveui/ReactiveUI#708]
When using a WhenAny for instance on an object that sends out PropertyChangedEventArgs with PropertyName set to null a NullReferenceException is thrown. 

Note that this is valid value according to INotifyPropertyChanged specifications. A workaround is to send an empty string instead of null.

This is a regression by the way, because it worked in the 5 branch.

**Comment by llusetti** [comment]
I'm still getting a NullReferenceException even with this fix, am I missing something ?
I am using nuget version 6.4.0.1

The exception is thrown by x.EventArgs.PropertyName.Equals(memberInfo.Name + "[]") but this piece of code should not even execute....

**Comment by llusetti** [comment]
Ok version 6.4.0.1 does not have this fix includedsince nuget package was release on 12 feb and fix is 22 feb. Sorry, my fault.

**Comment by frogger3d** [comment]
What do you mean? The fork mentioned above has not been merged.

**Comment by llusetti** [comment]
looking at the history it was merged on 22 feb
https://github.com/reactiveui/ReactiveUI/commits/master/ReactiveUI/INPCObservableForProperty.cs
am I wrong ?
I built the nuget packages from master and used in my prject and the error is gone

**Comment by llusetti** [comment]
i'm not a great expert on github merge, pulls etc etc but I see also a merge done by paulcbetts on 6 april in the master commits log

https://github.com/reactiveui/ReactiveUI/commits/master

**Comment by Suisse00** [comment]
@paulcbetts, @jlaanstra or @frogger3d  Could you close this issue? https://github.com/reactiveui/ReactiveUI/pull/811 fix the issue (the same way as I recommended) and has been merged a while ago.
