### ISSUE TITLE
Easy to repro race condition w/ WhenAnyValue

### ISSUE THREAD

**Issue by tberman** [reactiveui/ReactiveUI#716]
I have a simple test case that shows the race about 1/2 the time on the simulator for me. Just press the button, and then if you see the "Testing!" label, you didn't get the race, where as if you see no text on the subview, you have hit the race.

It appears to be related to the ViewModel being set while the subscription is being created.

Test case is here: https://github.com/tberman/rxui-race-test

**Comment by glennawatson** [comment]
The repo for the test case seems to have disappeared. Closing the issue.
