### ISSUE TITLE
Android: System.TypeInitializationException when adding Google Play Services Component

### ISSUE THREAD

**Issue by henningms** [reactiveui/ReactiveUI#733]
It seems adding the Google Play Services Component from the Xamarin Component Store causes ReactiveUI to throw exception:

System.TypeInitializationException: An exception was thrown by the type initializer for ReactiveUI.ControlFetcherMixin

It breaks when I try to use ReactiveViewHost:

StackTrace	"at ReactiveUI.LayoutViewHost..ctor (Android.Content.Context,int,Android.Views.ViewGroup,bool,bool) […"	string

InnerException:

Message	"An element with the same key already exists in the dictionary."	string

Any thoughts?

**Comment by ghuntley** [comment]
Closing due to old-age, please reply back with the stack trace if you want us to dig.
