### ISSUE TITLE
Can ReactiveUI target Mono for Windows?

### ISSUE THREAD

**Issue by afrentis** [reactiveui/ReactiveUI#734]
Hi. I'm currently looking into refactoring a Winforms application for Mvvm to use ReactiveUI so that I can subsequently port it to the Xamarin platform for multi-platform support. All is working well so far targeting the native .Net 4.5 & am loving ReactiveUI.

However I would also like to target the Mono runtime on Windows for testing purposes. When I do, I get the following error:

Missing method .ctor in assembly ...\ReactiveUITest\WinForms\bin\Debug\ReactiveUI.dll, type System.Windows.ThemeInfoAttribute
Can't find custom attr constructor image: ...\ReactiveUITest\WinForms\bin\Debug\ReactiveUI.dll mtoken: 0x0a000011
* Assertion at class.c:5594, condition `!mono_loader_get_last_error ()' not met

I've loaded the latest version 6.1 of ReactiveUI from Nuget.

Can ReactiveUI target Mono for Windows? Is there a simple config work-around (as per the similar error in issue #726)?

Thanks.

**Comment by ghuntley** [comment]
Yo @afrentis what approach did you end up taking?

**Comment by afrentis** [comment]
I didn't end up getting that far. I continued to refactor the Winforms application but had to move on to something else for awhile. Will revisit it in the Fall and once the refactoring for Mvvm & ReactiveUI is completed, & will move the whole thing over to the Mac and get it working with Xamarin.
