### ISSUE TITLE
Command binding does not work for UIButton (maybe others?) on Xamarin.iOS projects

### ISSUE THREAD

**Issue by johansson** [reactiveui/ReactiveUI#738]
As I tried to make an example ReactiveUI project for Xamarin.iOS (snippets can be found at this URL: https://gist.github.com/johansson/a68979fd2cdbfa1217b1 ), @paulcbetts responded to me with a proper example wiring up UIButton with a Command: http://cl.ly/1c373x3j0e14

But it doesn't work. Neither does my example project amended to call `RaiseAndSetIfChanged` properly. We are not seeing anything wrong with the `BindCommand` we're using.

**Comment by kentcb** [comment]
Can also use `WhenActivated`.
