### ISSUE TITLE
RxApp.MainThreadScheduler does not run on the UI Thread on WinRT

### ISSUE THREAD

**Issue by dimio85** [reactiveui/ReactiveUI#768]
I've been playing around with the library the last couple of days and I think I've found a bug regarding the scheduling on Windows Phone 8.1 (not silverlight)

I notice here https://github.com/reactiveui/ReactiveUI/blob/2a6dd935af47c7040aef612935553aff584d5a7d/ReactiveUI/RxApp.cs#L79
that the property returned is based on the DefaultScheduler. 
Shouldn't it be based on the CoreDispatcherScheduler? (http://rx.codeplex.com/SourceControl/latest#Rx.NET/Source/System.Reactive.Windows.Threading/Reactive/Concurrency/CoreDispatcherScheduler.cs)

I've run the following simple test on a viewmodel:
```
var backgroundScheduler = new EventLoopScheduler();
var currentScheduler = RxApp.MainThreadScheduler;

Observable
                .Interval(TimeSpan.FromMilliseconds(250), backgroundScheduler)
                .Take(20)
                .Select(o => string.Format("Title {0}", o))
                .ObserveOn(currentScheduler)
                .Subscribe(o => { this.MyList.Add(o); });
```
and it crashes with "bad thread" exception.
If I change to:
```
var currentScheduler = CoreDispatcherScheduler.Current;
```

the code runs fine.

My apologies if I'm missing something too obvious. I'm still trying to wire things up.

**Comment by jlaanstra** [comment]
We haven't seen a repro project. Closing this.
