### ISSUE TITLE
Running Unit Tests under Xamarin Studio without Xam.Mac

### ISSUE THREAD

**Issue by rpetz** [reactiveui/ReactiveUI#780]
**Preface**
This might be an issue of Xamarin Studio on Mac and not RxUI/Splat - however it appears to be an issue with the targets that are assigned to the NuGet package references and I can't seem to figure out what targets I should be changing the packages to...

**The issue**
When creating a unit test project (i.e. not a PCL) and adding ReactiveUI it tries to load PresentationCore even on OS X

**The reproduction steps**
- Create a new unit test project (doesn't matter if it starts on windows or mac) and add ReactiveUI and NUnit
- Create a ViewModel class deriving from ReactiveUI
- Create a test that interacts with the ViewModel class
- Run the test and it should fail with the following error:
  Could not load file or assembly 'PresentationCore'

**Environment**
Latest stable build of Xamarin Studio
Xamarin.iOS
OS X Yosemite

Looking at the test project file I notice that the references are utilizing the Net45 target - but after trying so many different combinations of other targets I still can't seem to get this to work...If it doesn't fail on PresentationCore is fails on System.Core

Any ideas on a workaround or what targets I should migrate the package references to?

Here's a simple solution that demonstrates the issue:
http://www.filedropper.com/rxtest

**Comment by DavidYKay** [comment]
Excellent documentation of the issue, gents. I'm bumping into this as well and would be willing to pitch in to get it resolved. What would it take to get a "Unit Testing Only" DLL?

And thanks for the library, @paulcbetts !

**Comment by paulcbetts** [comment]
@DavidYKay Creating the DLL is pretty easy, but deciding where to slot it in NuGet is the hard part :(  There is no "Unit test CLR profile" to use

**Comment by omares** [comment]
So if understand this issue correctly there is no way to run ReactiveUi unit tests on a mac with only a xamarin-android/ios license?

**Comment by omares** [comment]
@mteper Could you please elaborate on how you did that? That would help us out a lot.

**Comment by mteper** [comment]
@omares create unit tests in a xamarin.mac library project as opposed to plain .net library project. If you use the Unified variety, you won't even need to go in and manually tweak references inside the .csproj file.

**Comment by omares** [comment]
@mteper when i try to add the "reactiveui-testing" package to the mac library project i get following message:

    Could not install package 'reactiveui-testing 6.5.0'. You are trying to install this package into a project that targets 'Xamarin.Mac,Version=v2.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by omares** [comment]
Okay i got it, but it does not work without editing the csproj file manually. Here is a quick explanation for anyone else struggling to run tests their xamarin.android/ios tests when using reactiveui.

1. Install xamarin.mac using the xamarin.installer
2. Open your solution and add a new Library project from the Mac, Library, Unified API tree.
3. Delete all unneeded files like the `Main.cs` or `AppDeletage.cs`
4. Open the Options of the added solution and switch the Target Framework from "Xamarin.Mac Mobile Framework" to "Xamarin.Mac .Net 4.5 Framework" under Build, General.
5. Add your packages. Dont forget Nunit and reactiveui-testing.
6. Open the csproj file of the new project and change the path part from `Net45` to `Xamarin.Mac10` for the Splat and ReactiveUI references. See the example code.
7. Run your tests and be happy.

Broken references:

    <Reference Include="ReactiveUI">
      <HintPath>..\packages\reactiveui-core.6.5.0\lib\Net45\ReactiveUI.dll</HintPath>
    </Reference>
    <Reference Include="Splat">
      <HintPath>..\packages\Splat.1.6.2\lib\Net45\Splat.dll</HintPath>
    </Reference>

Fixed references:

    <Reference Include="ReactiveUI">
      <HintPath>..\packages\reactiveui-core.6.5.0\lib\Xamarin.Mac10\ReactiveUI.dll</HintPath>
    </Reference>
    <Reference Include="Splat">
      <HintPath>..\packages\Splat.1.6.2\lib\Xamarin.Mac10\Splat.dll</HintPath>
    </Reference>

**Comment by mteper** [comment]
:+1:

**Comment by Yaojian** [comment]
follow @omares 's steps, I got the error : `System.IO.FileNotFoundException : Could not load file or assembly 'System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' or one of its dependencies.`

Any ideas?

**Comment by rpetz** [comment]
Im pretty sure this is not a related issue to this thread - I would recommend opening a new thread for your issue.

**Comment by Yaojian** [comment]
@rpetz  Thanks for your response.

I setup a git repository https://github.com/Yaojian/RxHelloWorld and list the result after each step in 
https://github.com/Yaojian/RxHelloWorld/tree/master/RxHelloWorld

still no success :-(

**Comment by Yaojian** [comment]
For me, the Splat works when using `MonoMac` 

```
    <Reference Include="Splat">
      <HintPath>..\packages\Splat.1.6.2\lib\MonoMac\Splat.dll</HintPath>
    </Reference>
```

**Comment by maqui01** [comment]
I'm having the same issue as @Yaojian but changing Splat to MonoMac didn't solved the problem. Where could you see that Splat was causing the problem? I couldn't see any further log with that info 😞

**Comment by fvermeulen** [comment]
I have the problem as well

change to
`<Reference Include="ReactiveUI">
  <HintPath>..\packages\reactiveui-core.6.5.0\lib\Xamarin.Mac10\ReactiveUI.dll</HintPath>
</Reference>
<Reference Include="Splat">
  <HintPath>..\packages\Splat.1.6.2\lib\Xamarin.Mac10\Splat.dll</HintPath>
</Reference>`

--> results in no tests will be executed

will try linking other sources

**Comment by maqui01** [comment]
Hi guys, any update on this? I had to rollback to Xamarin Studio 5.9.x because of this problem :(

**Comment by fvermeulen** [comment]
@maqui01 I am working on it, but i didn't get it working will now :(

Will answer if I get it working

**Comment by fvermeulen** [comment]
I created a sample with ReactiveUi 7. Who can help me with that?
https://github.com/fvermeulen/ReactiveTest

I get in the test 'CommandWillBeExecuted' everytime this exception.
`System.TypeLoadException : Could not load type 'ReactiveTest.First' from assembly 'ReactiveTest, Version=1.0.6106.36677, Culture=neutral, PublicKeyToken=null'.`

can someone look into it and help me/us?

@paulcbetts @maqui01 @Yaojian

**Comment by pellet** [comment]
I'm having the same issue after changing the reactiveui and splat references to:
```
<Reference Include="ReactiveUI, Version=7.4.0.0, Culture=neutral, PublicKeyToken=null">
      <HintPath>..\packages\reactiveui-core.7.4.0\lib\Xamarin.Mac20\ReactiveUI.dll</HintPath>
    </Reference>
<Reference Include="Splat, Version=1.6.2.0, Culture=neutral, PublicKeyToken=null">
      <HintPath>..\packages\Splat.1.6.2\lib\MonoMac\Splat.dll</HintPath>
    </Reference>
```
I get:
`System.IO.FileNotFoundException: Could not load file or assembly 'UnitTests'`
I'm guessing this may have to do with it being Xamarin.Mac20 rather than Xamarin.Mac10 and it enforcing Mac app/file sandboxing?

**Comment by ghuntley** [comment]
This is fixed with `reactiveui v8`. We have split all WPF references away from the `reactiveui` package and WPF users now must use a separate nuget package. `reactiveui-wpf`
