### ISSUE TITLE
ToProperty() does not always make initial value immediately available

### ISSUE THREAD

**Issue by kentcb** [reactiveui/ReactiveUI#785]
I've just spent some time tracking down a scenario in which the initial value of an observable passed to `ToProperty()` is not immediately available and client code can see `default(T)` instead of the correct value.

Here is a repro:

``` C#
namespace RxUIToPropertyRepro
{
    using System;
    using System.Reactive.Concurrency;
    using System.Reactive.Linq;
    using NUnit.Framework;
    using ReactiveUI;

    [TestFixture]
    public class Repro
    {
        [Test]
        public void immediate_access_when_using_to_property()
        {
            var sut = new ToPropertyScenario(328);
            Assert.AreEqual(328, sut.Value);
        }

        [Test]
        public void immediate_access_via_current_thread_scheduler_when_using_to_property()
        {
            CurrentThreadScheduler.Instance.Schedule(() =>
            {
                var sut = new ToPropertyScenario(328);
                Assert.AreEqual(328, sut.Value);
            });
        }

        [Test]
        public void immediate_access_via_immediate_scheduler_when_using_to_property()
        {
            ImmediateScheduler.Instance.Schedule(() =>
            {
                var sut = new ToPropertyScenario(328);
                Assert.AreEqual(328, sut.Value);
            });
        }

        [Test]
        public void immediate_access_when_using_private_field()
        {
            var sut = new PrivateFieldScenario(328);
            Assert.AreEqual(328, sut.Value);
        }

        [Test]
        public void immediate_access_via_current_thread_scheduler_when_using_private_field()
        {
            CurrentThreadScheduler.Instance.Schedule(() =>
            {
                var sut = new PrivateFieldScenario(328);
                Assert.AreEqual(328, sut.Value);
            });
        }
    }

    public class ToPropertyScenario : ReactiveObject
    {
        private readonly ObservableAsPropertyHelper<int> value;

        public ToPropertyScenario(int initialValue = default(int))
        {
            this.value = Observable.Return(initialValue)
                .ToProperty(this, x => x.Value);
        }

        public int Value
        {
            get { return this.value.Value; }
        }
    }

    public class PrivateFieldScenario : ReactiveObject
    {
        private int value;

        public PrivateFieldScenario(int initialValue = default(int))
        {
            Observable.Return(initialValue)
                .Subscribe(x => this.Value = x);
        }

        public int Value
        {
            get { return this.value; }
            private set { this.RaiseAndSetIfChanged(ref this.value, value); }
        }
    }
}
```

Of these tests, only one fails: `immediate_access_via_current_thread_scheduler_when_using_to_property`. It seems that because the client code is executing inside a scheduled message, the value of the property is not available until later (i.e. when the scheduler is freed up to determine it). This is common when the code is executing as the result of a reactive command, for example.

This does not align with my expectations of how `ToProperty()` should work, nor does it seem to align with [the docs](https://github.com/reactiveui/ReactiveUI/blob/docs/docs/basics/to-property.md):

> It's important to know the semantics of `ToProperty` - you should conceptualize this method as similar to `Subscribe`: it causes the Observable to be evaluated, just like `foreach` causes Enumerables to be evaluated.

There are several workarounds that I know of, some of which are demonstrated in tests above:
1. Use a `private` field and `Subscribe` (see tests).
2. Use the immediate scheduler for the call to `ToProperty()` (see tests)
3. Specify the immediate scheduler in the call to `ToProperty()`
4. Specify the initial value in the call to `ToProperty()`, even though the observable is cold and has an initial value in it

None of these options quite fits my mental model of how `ToProperty()` should be working. Is my understanding of `ToProperty()` wrong, or is there an implementation problem here?

**Comment by paulcbetts** [comment]
Hm. While I think you're right, fixing ToProperty to Immediate also has negative effects - I would use option 3 here and specify ImmediateScheduler if you hit this problem

**Comment by shiftkey** [comment]
@paulcbetts yep, there are times when passing in `Scheduler.Immediate` to `ToProperty` is a necessary evil. 

cc @niik for any extra thoughts on this.

**Comment by Gentlee** [comment]
I have spent 1 hour trying to understand why my spinner is not showing, and the problem is in ObservableAsPropertyHelper:

Remove = ReactiveCommand.CreateAsyncTask(async x => await RemoveImpl(x as UserViewModel));
Update = ReactiveCommand.CreateAsyncTask(async _ => await UpdateImpl());

_loading = Observable
        .CombineLatest(Remove.IsExecuting, Update.IsExecuting, (x, y) => x || y)
        .ToProperty(this, x => x.IsLoading);

When i call Update right before showing my view, CombineLatest produces true, but property still returns false and when view binds to property it doesn't show spinner. Scheduler.Immediate doesn't help!

All works perfectly If I make usual property with RaiseAndSetIfChanged setter and write this:

Observable
       .CombineLatest(Remove.IsExecuting, Update.IsExecuting, (x, y) => x || y)
       .Subscribe(x => IsLoading = x);

**Comment by gluck** [comment]
@Gentlee sure you're not hitting #814 ? maybe you can give a try at the rxui7 branch, it has a fix merged.

**Comment by csmager** [comment]
Just stumbled on this issue - can anyone comment on why the use of `Scheduler.Immediate` here would have 'negative effects' or be considered 'evil'? If you were doing this imperatively, surely this is what you'd expect?

I stumbled on this while trying to set some of the properties after creating a view model but before showing it as a dialog.  I found it a bit surprising that all of my read only OAPH-based properties didn't update.

**Comment by kentcb** [comment]
@csmager my layman's understanding is that the immediate scheduler can get itself into infinite loops in certain circumstances. The current thread scheduler is somehow smarter and determines whether it's safe to perform the action immediately. If so, it does. If not, it schedules the work for later (but on the same thread, of course).

Why the current thread scheduler deems it necessary to schedule the work in the failing scenario is beyond me. Understanding that would require digging into Rx code.

I'm closing this for now because I don't really feel like there's anything RxUI can do about it. If anything, it might be that the heuristics used by Rx's `CurrentThreadScheduler` should be improved.
