### ISSUE TITLE
System.TypeInitializationException in ReactiveUI.XamForms.RoutedViewHost

### ISSUE THREAD

**Issue by detroitpro** [reactiveui/ReactiveUI#786]
After updating to Xamarin Forms 1.3.1-6294-pre1   - https://www.nuget.org/packages/Xamarin.Forms/1.3.1.6294-pre1

![image](https://cloud.githubusercontent.com/assets/49996/5597839/e62c9080-9277-11e4-8474-299c4f6c8601.png)

A sample application throws:  Method not found: 'Xamarin.Forms.BindableProperty.Create'.

![image](https://cloud.githubusercontent.com/assets/49996/5597835/cc0d9e60-9277-11e4-9ef5-d5622ac7d757.png)

![image](https://cloud.githubusercontent.com/assets/49996/5597821/6ebe2ef0-9277-11e4-9892-f3ad38c2fa61.png)

- This happens on application start.
- 'Xamarin.Forms.BindableProperty.Create' exists - the view model calls it and the sln compiles.

**Comment by kentcb** [comment]
Given the age of this issue and the fact that I've used XF successfully with RxUI several times recently, I'm going to assume that this was either due to linking or a quirk of that XF release. Closing, but please let me know if you can repro with rxui7-master.
