### ISSUE TITLE
Slack link on the reactiveui.net is broken

### ISSUE THREAD

**Issue by jesuswasrasta** [reactiveui/ReactiveUI#792]
![reactiveui-salck-broken-link](https://cloud.githubusercontent.com/assets/1121984/5789270/f773ce56-9e63-11e4-8b16-ada78c1b9ed6.png)

Just a small issue: the Slack link on http://reactiveui.net/ page is broken, it lacks a 't' on https.

Bye,
Nando :)

**Comment by ghuntley** [comment]
Thanks @jesuswasrasta - resolved!

**Comment by jesuswasrasta** [comment]
Don't mention it ;)
