### ISSUE TITLE
Proper way to handle ActivationKind.FileOpenPicker (or resume)?

### ISSUE THREAD

**Issue by gordonwatts** [reactiveui/ReactiveUI#793]
In this case, specifically for universal apps for Windows Phone and Windows Store app's there are reasons that one comes out of suspension that have nothing to do with the user just switched to your app to pick up where you left off. For example, the FileOpenPicker reason, that can be passed when the app is activated (it can be caught in the App's OnActivate method in App.xaml.cs) or it can be passed when the app resumes from a suspension.

The question is: how best to handle it in RxUI?

I was thinking to create a new version of AutoSuspendedHelper, with some special observables. I'd add an OnActivated method (like the OnLaunched method), and then a few extra observables that view models could subscribe to.

Is this an appropriate way to deal with this? Or is there something more general. If I do this and it works, do you want the code? :-)

**Comment by paulcbetts** [comment]
> Is this an appropriate way to deal with this?

So, the usual way to deal with this, is to stuff off extra data fields in the AutoSuspendHelper - the iOS one saves the Launch Options for example. I'd try to avoid changing the lifetime model itself unless you *really* have to

**Comment by gordonwatts** [comment]
I will take a look.
How about when arguments come in on an activate?

**Comment by gordonwatts** [comment]
Thanks!
Looking a little more carefully, in the Android version I see:

         readonly Subject<Bundle> onCreate = new Subject<Bundle>(); 
         readonly Subject<Unit> onRestart = new Subject<Unit>(); 
         readonly Subject<Unit> onPause = new Subject<Unit>(); 
         readonly Subject<Bundle> onSaveInstanceState = new Subject<Bundle>(); 

         public static Bundle LatestBundle { get; set; }

Actually, I couldn't find the iOS version (sorry - I'm not very familiar with the iOS versions of this library). BTW, I notice these are Subjects vs ReplaySubjects (as they are in the WinRT version). Is there a reason for that?

So, it looks like I should add a new observable called "IsActivating" or something like that to the WinRT's version, and a static variable for the payload (I think there are several different types, but I've not done a careful investigation yet).

Next question - from the Android example, it doesn't look like anyone outside the initial app ever knows (or needs to know) about the auto suspend helper. Is there a pattern for notifying the ViewModel's that need to know? I could just put it in the IoC container, for example. The view models will need to subscribe to the events... Up to now I've just subscribed to RxApp.SuspensionHost... But one needs a new event for the re-activating I think (I didn't see it anywhere in the current framework), and I agree, it isn't obvious that one should alter SuspensionHost for that.

**Comment by gordonwatts** [comment]
So, I started by doing the simplest thing I could, which was to copy your WinRT AutoSuspendHelper and add something for the activate.

https://gist.github.com/gordonwatts/4e0502fc93616c4d73d5

Also in there is a small amount of code that shows how it gets used (very ugly, yes, much of that is boilerplate, but, starting simple).

**Comment by gordonwatts** [comment]
Ugh. So this works. But I realized that if I wanted to port this to another platform other than WinRT or Phone, it would be very ugly - all of this is inherently single platform. And it infects my ViewModel's as I've currently coded it. At some level there is now way around - these are capabilities that are tied directly to a platform, and one does want to be able to take advantage of them. :-)

Not at all sure what the right way to do this is!

**Comment by paulcbetts** [comment]
So, what's the difference between Activated and ISuspensionHost's IsUnpausing? This feels like the same event

**Comment by gordonwatts** [comment]
Maybe nothing - currently the OnActivated call isn't trapped in ReactiveUI's source (note to make things rough it comes in with a different argument). Hence the decision to do that. But one could have on activate pump events into _launched as well. However, we would have to do a little thinking about the arguments... the IActivatedEventArgs contains the "Kind", but not the previous execution state (that is unique to the OnLaunched method arguments).

In general sending the argument down in the observable makes things a lot easier to deal with when you are interested in the arguments. I see that you did it in the Android version for some events. Is there a reason to put it as a global rather than do that? I definitely understand for the SuspensionHost Observables as you are trying to make them fairly cross platform.

https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.xaml.application.onactivated.aspx - discusses the conditions under which OnActivated is called as opposed to OnLaunched.

**Comment by paulcbetts** [comment]
> Is there a reason to put it as a global rather than do that? I definitely understand for the SuspensionHost Observables as you are trying to make them fairly cross platform.

That's mostly the reason, it allows you to pass off platform-specific info without polluting ISuspensionHost. You can always make an extension method to ISuspensionHost that is only available on WinRT `GetActivationParameters` or something, that hides the global variable access.

While I'm not super excited about changing the contract of ISuspensionHost, I totally am okay with changing the mapping of WinRT events <=> ISuspensionHost events to be more reasonable, and it sounds like we should mix OnActivated and OnLaunched together in this case to implement IsUnpausing

**Comment by gordonwatts** [comment]
Ok. I guess I was worrying that if someone decided to process one of these events on a background thread they could end up picking up the wrong version of arguments. However, besides common sense, that really shouldn't happen. And the extension function could do the global variable access and just shove the global variable into the observable stream. I like this.

So, I'm not an expert on lifetime, and, in particular, in your framework, what IsUnpausing means. But what we'd do, then, is OR the current definition of IsUnpausing with an OnActivate guy coming through. We'd then make the same modifications I've made (e.g. add OnActivate and the override check). This would break people's code when they upgraded, btw.

If you agree, I can make these changes and send you a pull request.

BTW, why use ReplaySubject instead of just Subject for _launched?
