### ISSUE TITLE
ReactiveCommand.Create method that takes an Action<object>

### ISSUE THREAD

**Issue by distantcam** [reactiveui/ReactiveUI#802]
With C# 6 coming there's some nice syntax saving to be made with ViewModels.

    public ICommand MyObservableCommand => ReactiveCommand.CreateAsyncObservable(MyObservableMethod);
    public ICommand MyTaskCommand => ReactiveCommand.CreateAsyncTask(MyTaskMethod);

It would be nice if it was also possible to do this with commands that just take an `Action<object>` as well.

    public ICommand MyCommand => ReactiveCommand.Create(MyMethod);

**Comment by kentcb** [comment]
This seems dangerous to me, since every access to the property would be creating a new command instance. If I have this ctor code in my VM:

```C#
this.MyCommand
    .Subscribe(DoSomeOtherThingWhenTheCommandIsExecuted);
```

And I have this in my view:

```C#
this.BindCommand(ViewModel, x => x.MyCommand, x => x.someButton);
```

It won't work as expected. The binding infrastructure will obtain a different instance than that used in my VM's ctor.

**Comment by distantcam** [comment]
@kentcb Ack! That's true. I took the optimisation a step too far and should have left it at this.

    public ICommand MyCommand { get; } = ReactiveCommand.Create(MyMethod);

**Comment by kentcb** [comment]
Well, waddaya know. #971 does exactly this by _requiring_ execution logic be provided as creation time. It will be merged shortly.
