### ISSUE TITLE
Unable to run tests

### ISSUE THREAD

**Issue by kentcb** [reactiveui/ReactiveUI#807]
Hi,

I've got a portable library containing some tests, including some that require RxUI. I'm unable to add a dependency on reactiveui-testing because it's not supported for my targets. I'm getting this exception when attempting to execute tests inside Visual Studio's test runner (XUnit, if it matters):
```
Result Message:	
System.TypeInitializationException : The type initializer for 'ReactiveUI.RxApp' threw an exception.
---- System.Exception : You are referencing the Portable version of ReactiveUI in an App. Reference the platform-specific version.
Result StackTrace:	
at ReactiveUI.RxApp.get_DefaultExceptionHandler()
   at ReactiveUI.ObservableAsPropertyHelper`1..ctor(IObservable`1 observable, Action`1 onChanged, Action`1 onChanging, T initialValue, IScheduler scheduler)
   at ReactiveUI.OAPHCreationHelperMixin.observableToProperty[TObj,TRet](TObj This, IObservable`1 observable, Expression`1 property, TRet initialValue, IScheduler scheduler)
   at ReactiveUI.OAPHCreationHelperMixin.ToProperty[TObj,TRet](IObservable`1 This, TObj source, Expression`1 property, TRet initialValue, IScheduler scheduler)
```
Strangely, if I debug through the test I see a `TypeInitializationException` with message `error CS0648: '' is a type not supported by the language`. Hmmm.

Digging in further, I found that Splat is returning `false` from `ModeDetector.InUnitTestRunner()`. Looking at Splat's code it seems that's the only reasonable fallback in a portable environment. I tried overriding it to force it to `true`:
```
public MyFixture()
{
    Splat.ModeDetector.OverrideModeDetector(new ForcedModeDetector());
}

private class ForcedModeDetector : IModeDetector
{
    public bool? InDesignMode() => false;

    public bool? InUnitTestRunner() => true;
}
```
But that still didn't help (same exception).

Any ideas how to rectify this? Is there a sane way to set up my unit test library so this just works?

**Comment by paulcbetts** [comment]
Is your unit test library a PLib? Make it a regular .NET 4.5 library and everything should be fine. XUnit 2.0 recently added (afaik) support for portable unit tests, but we're not there yet

**Comment by kentcb** [comment]
@paulcbetts yeah, it's a PCL. Sounds like you're planning to support this then? Any idea on timeframes? Until now I've been running my tests via the XUnit Xamarin runner (in the iOS simulator), so I could probably just keep doing that for now.

**Comment by paulcbetts** [comment]
I have no idea how to support PCL unit tests, because there is no PCL UI toolkit that RxUI could build on (i.e. there's no PCL version of a Dispatcher for example). I'll think about this - the unit test scenario specifically might be easier to handle

**Comment by kentcb** [comment]
I see your point, but I guess I was thinking solely of testing the UI-agnostic pieces of my code. That is, view models. Maybe I'm mistaken, but I was asking under the assumption that large swathes of RxUI are platform agnostic and should therefore be testable from a PCL.

**Comment by paulcbetts** [comment]
@kentcb Sure, but is there any reason you can't just use a .NET 4.5 library for unit tests?

**Comment by kentcb** [comment]
@paulcbetts because then I can't run them in the simulator or on a device (not supported, unless I'm missing something obvious). To me, it's important to be able to run tests quickly in VS, but it's super important that I be able to run them occasionally on the simulator/device.

**Comment by jlaanstra** [comment]
@paulcbetts this should be fixed now right?

**Comment by paulcbetts** [comment]
Fixed, at least in .NET 4.5

**Comment by paulcbetts** [comment]
Wait, this is a separate issue. Not fixed.

**Comment by kentcb** [comment]
It's not perfect, but I did [a blog post](http://kent-boogaart.com/blog/using-the-visual-studio-test-runner-for-mobile-development/) on how to get around this problem.
