### ISSUE TITLE
Are dynamic table sections supported?

### ISSUE THREAD

**Issue by kentcb** [reactiveui/ReactiveUI#808]
Hi,

I've been banging my head against a wall trying to get dynamic table sections working (using 6.4.0.1). I've run into at least three distinct issues, all probably related. The API seemingly supports my use case, but I'm wondering whether the implementation is known to be lacking...? I just want to know whether I should give up and try a different approach altogether or whether I'm possibly doing something wrong.

Essentially what I want is a table view where the sections and items within those sections are dynamically determined. My view model is written and tested, but binding to the view is throwing up errors around indexes being out of sync etcetera.

Is there a working sectioned table sample that includes this level of dynamism?

**Comment by rdavisau** [comment]
Is this for iOS? Are you working with ReactiveTableView and co?

**Comment by kentcb** [comment]
@nverinaud yes, iOS. Give me a few mins and I'll post a link to my little repro app that blows up.

**Comment by kentcb** [comment]
OK, [here](http://cl.ly/3l3B2C1c1j25) is my repro. You'll need to package restore.

The repro just creates a bunch of items sectioned into either "Active" or "Inactive" according to a flag on the `ItemViewModel`. That flag is dynamically and randomly modified, so items should move about between the two sections. Sections should disappear if they have no items in them, but I couldn't get the app to run reliably enough for me to test that aspect of the code.

**Comment by nverinaud** [comment]
@kentcb pseudo-fail exception. ^^

cc @rdavisau

**Comment by kentcb** [comment]
ha, sorry: auto-completion fail.

**Comment by kentcb** [comment]
Pulled the latest RxUI source, opened the *ReactiveUI_XSIOS* solution inside VS. Added my repro project to it. Fixed all the annoying reference missing errors. Modified the references so that my project used the source rather than NuGet binaries. Built it. Ran it. **It works.**

:expressionless: 

Removed the reference to the source project. Added back a dependency on the RxUI NuGet package. Built it. Ran it. **It borks every run.**

:sob:

According to the change log, there have been no changes since 6.4.0.1.

**What even is going on?**

**Comment by kentcb** [comment]
OK, somehow my RxUI repo had gotten itself into a bad state. I did a clean pull and now it fails regardless of whether I use the source or the binaries.

**Comment by kentcb** [comment]
Pretty certain this has to do with `ReloadData()` being called too frequently (not waiting for iOS to finish processing previous calls). Plan on looking into it more tomorrow, though from initial investigation it sounds difficult to impossible to actually know when iOS has finished processing the last reload request.

**Comment by rdavisau** [comment]
Yep, I also get the failures in your repro. 
I haven't used `CreateDerivedCollection` before but I understand how useful it can be. I spent a bit of time fiddling with this and was able to make the sample work by factoring out derived collections and using `ReactiveList`s instead. 

Specifically,

In `ViewModel.cs`:
 - Changed type of `sections` to `ObservableAsPropertyHelper<ReactiveList<SectionViewModel>>`
 - Changed type of `Sections` to `ReactiveList<SectionViewModel> Sections`
 - removed all `CreateDerivedCollection` methods in the ctor and replaced with:
````
this.allItems
	.ItemChanged
	.Select(x=> new ReactiveList<SectionViewModel>{
		new SectionViewModel("Active",  new ReactiveList<ItemViewModel>(allItems.Where(i=> i.IsActive))),
		new SectionViewModel("Inactive", new ReactiveList<ItemViewModel>(allItems.Where(i=> !i.IsActive)))})
	.ToProperty(this, x=> x.Sections, out sections);
````

In `View.cs`:
- Replaced the code in `ViewDidAppear` with:
````
this.WhenAnyValue(x => x.ViewModel.Sections)
    .Select(x => new ReactiveList<ItemsSection>(x.Select(y => new ItemsSection(y.Title, y.Items))))
    .Select(x => new ReactiveTableViewSource<ItemViewModel>(this.TableView) { Data = x })
    .BindTo(this.TableView, x => x.Source);
````

Obviously the above is very heavy handed and not a final solution, but from here it may be possible to start reintroducing derived collections (or at least, stop newing up so many items on every change). Otherwise, maybe @paulcbetts knows something about the process of using `DerivedCollections`with `ReactiveTableViewSource`s, or more about the correct pattern in general?

**Comment by paulcbetts** [comment]
@tberman wrote this code, perhaps he has some insight?

**Comment by tberman** [comment]
My guess is you are changing the collection from random threads, which you can't do.

**Comment by kentcb** [comment]
@rdavisau thanks for confirming the issue and playing around with the repro. I can confirm that making the changes you suggest does appear to work around the problem. Of course, as you say, it involves creating a whole lot more objects. However, I may just use it as an interim workaround because I am supposed to be giving a demo later this week.

@tberman I am not changing the collection from random threads - please see the repro.

I found a big 'ol comment in `CommonReactiveSource` basically stating that `ReloadData` is a nightmare, so my best guess is still that it is being called too frequently. However, I have evidence against that hypothesis too. I tried throttling the `sectionChanged` observable in `CommonReactiveSource` and that seems to help a little bit, but still fails eventually. I tried scaling down the frequency of updates to once every 2 seconds, and it still eventually fails.

I also found [this SO answer](http://stackoverflow.com/a/14944151/5380) that *might* give a reliable means of detecting when `ReloadData` is done. The answers with more upvotes seem outdated and no longer working, but that's SO for you. Of course, per above I'm not sure that `ReloadData` is the problem.

**Comment by tberman** [comment]
So, I found if you don't bind to 'shouldReset' everywhere w/ derived collections you ended up with random badness. We had a repro ages ago, not sure where it went. @paulcbetts you remember that one?

**Comment by kentcb** [comment]
@tberman not sure I follow. Are you saying simply adding an observer to the `ShouldReset` observable on each derived collection should resolve the issue? I just tried that and it didn't seem to have any effect.
