### ISSUE TITLE
ViewContractObservable (WhenAnyObservable) in ViewModelViewHost seems to not reflect replacement

### ISSUE THREAD

**Issue by patroza** [reactiveui/ReactiveUI#809]
If I define ViewContractObservable e.g in XAML on the ViewModelViewHost, then this Observable is not used, instead the default defined Observable is used.
If I comment out the default defined Observable from the ViewModelViewHost.cs, then the problem goes away and it will use my Observable.

Is this broken behavior of WhenAnyObservable in conjunction with DependencyProperty or?

**Comment by kentcb** [comment]
Closing this due to age. If this is still a problem, please open another ticket with a minimal repro. For example, it's not clear from the question how you're setting the `ViewContractObservable` property in XAML (custom converter, markup extension?).
