### ISSUE TITLE
Not able to interact with UITextField in a ReactiveTableViewCell

### ISSUE THREAD

**Issue by kentcb** [reactiveui/ReactiveUI#810]
I seem to be hitting lots of "fun" issues lately...

I've boiled this down to the simplest possible thing that fails, and here it is:

```C#
public class MainViewModel : ReactiveObject
{
    private readonly IReactiveList<ItemViewModel> items;

    public MainViewModel()
    {
        this.items = new ReactiveList<ItemViewModel>();
        this.items.Add(new ItemViewModel());
        this.items.Add(new ItemViewModel());
        this.items.Add(new ItemViewModel());
    }

    public IReactiveList<ItemViewModel> Items => this.items;
}

public class ItemViewModel : ReactiveObject
{
}

public class View : ReactiveTableViewController, IViewFor<MainViewModel>
{
    public static readonly NSString CellKey = new NSString("KEY");
    private MainViewModel viewModel;

    public View()
    {
        this.ViewModel = new MainViewModel();
    }

    public MainViewModel ViewModel
    {
        get { return this.viewModel; }
        set { this.RaiseAndSetIfChanged(ref this.viewModel, value); }
    }

    object IViewFor.ViewModel
    {
        get { return this.ViewModel; }
        set { this.ViewModel = (MainViewModel)value; }
    }

    public override void ViewDidLoad()
    {
        base.ViewDidLoad();

        this.TableView.RegisterClassForCellReuse(typeof(Cell), CellKey);

        this
            .WhenAnyValue(x => x.ViewModel)
            .Where(x => x != null)
            .Select(x => new ReactiveTableViewSource<ItemViewModel>(this.TableView, x.Items, CellKey, 30))
            .BindTo(this.TableView, x => x.Source);
    }
}

public class Cell : ReactiveTableViewCell
{
    public Cell(IntPtr handle) : base(handle)
    {
        this.Load();
    }

    private void Load()
    {
        var t = new UITextField(this.Bounds)
        {
            Text = "Some text"
        };
        this.AddSubview(t);
    }
}
```
This displays as expected, but the `UITextField` controls are not interactive. You can tap them all you want, and they simply don't allow editing. This is true in the simulator and on an actual device.

Now I noticed that very similar code *without* RxUI works, so I started suspecting something was up with `ReactiveTableViewCell`. Now hold onto your hats, because this is about to get weird...

If I comment out this in `ReactiveTableViewCell`:
```C#
//public override void WillMoveToSuperview(UIView newsuper)
//{
//    base.WillMoveToSuperview(newsuper);
//    RxApp.MainThreadScheduler.Schedule(() => (newsuper != null ? activated : deactivated).OnNext(Unit.Default));
//}
```
Everything works as expected. Naturally I assumed something was subscribed to `(de)activated` and was screwing things up. But when I changed the code to this:
```C#
public override void WillMoveToSuperview(UIView newsuper)
{
    base.WillMoveToSuperview(newsuper);
    //RxApp.MainThreadScheduler.Schedule(() => (newsuper != null ? activated : deactivated).OnNext(Unit.Default));
}
```
It still didn't work! That's right - merely overriding this method is enough to screw up interactivity in the cell.

Naturally, I figured at this point that maybe it's a Xamarin/iOS issue, not RxUI. So I went back to my non-RxUI code and modified the cell to override the same method. It still worked.

Now I'm still not convinced this is an RxUI problem, but I want to record this and come back to it next week because I need to get a demo ready this week.

Any thoughts welcome.

**Comment by rdavisau** [comment]
Interesting one - it seems you are right about overriding WillMoveToSuperView being the cause, whether or not you call base. 

 - If you derive directly from `UITableViewCell` (rather than `ReactiveViewCell`), the textfield is editable, once you and override `WillMoveToSuperview`, the textfield becomes uneditable. 
 - If you remove `ReactiveTableView` altogether and try it with a `UITableViewController`, the above still applies.

So it's probably not RxUI. 
But for more fun - 

- If you try to do the same in Objective C - derive a cell from UITableViewCell and override `willMoveToSuperview:` .. it all still seems to work. :ghost:

**Comment by kentcb** [comment]
@rdavisau Thanks for confirming that I'm not going insane. If, as you say, it occurs with a plain old `UITableViewCell` (I didn't manage to repro that, but was short on time), then I'd say it's a Xamarin issue of some nature. I'll report on bugzilla when I can and then close this issue.

**Comment by kentcb** [comment]
@rdavisau: in your Obj-C repro, can you please confirm for me whether you called `dequeueReusableCellWithIdentifier:forIndexPath:`? It's actually the *combination* of `dequeueReusableCellWithIdentifier:forIndexPath:` with `willMoveToSuperview:` override that is breaking the `UITextField` in the cell.

That is, if in Xamarin world I either use `DequeueReusableCell(NSString)` (no index) or don't override `WillMoveToSuperview()` then everything works fine, but if I use *both* `DequeueReusableCell(NSString, NSIndexPath)` *and* override `WillMoveToSuperview()` then it breaks the `UITextField`.

**Comment by rdavisau** [comment]
Interesting findings  and good question - my repro was not exact in that I used the `dequeueReusableCellWithIdentifier:` method. However, I just made the changes to use `dequeueReusableCellWithIdentifier:forIndexPath:` and it still works!

**Comment by rdavisau** [comment]
The objc repro that works:

`headers.h`
```objc
#import <UIKit/UIKit.h>

@interface AppDelegate : UIResponder <UIApplicationDelegate>
@property (strong, nonatomic) UIWindow *window;
@end

@interface MyCell : UITableViewCell
@end

@interface ViewController : UIViewController <UITableViewDataSource>
@end
```

`implementation.m`
```objc
#import "headers.h"

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    // Override point for customization after application launch.
    return YES;
}

@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    
    UITableView *tableView = [[UITableView alloc] initWithFrame:[self.view frame]];
    tableView.dataSource = self;
    
    [tableView registerClass:[MyCell class] forCellReuseIdentifier:@"HI"];
    
    [[self view] addSubview:tableView];
}

- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section
{
    return 5;
}

- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath
{
    return [tableView dequeueReusableCellWithIdentifier:@"HI" forIndexPath:indexPath];
}

@end

@implementation MyCell

- (void)willMoveToSuperview:(UIView *)newSuperview {
    NSLog(@"will move to superview override was called");
    [super willMoveToSuperview:newSuperview];
}
 
- (id)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString *)reuseIdentifier
{
    self = [super initWithStyle:style reuseIdentifier:reuseIdentifier];
    
    UITextField *textfield = [[UITextField alloc] initWithFrame:CGRectMake(80,0, 500,30)];
    
    textfield.text = @"Some Text";
    [self addSubview:textfield];
    
    return self;
}

@end
```

**Comment by kentcb** [comment]
@rdavisau Thanks very much for confirming this, Ryan.

For the record, I've reported the issue [here](https://bugzilla.xamarin.com/show_bug.cgi?id=27293).
