### ISSUE TITLE
WeakEventManager's WeakEventList isn't thread safe

### ISSUE THREAD

**Issue by lorentzm** [reactiveui/ReactiveUI#817]
Occasionally, I get a "System.InvalidOperationExceptionCollection was modified; enumeration operation may not execute." while iterating handlers in DeliverEvent (WeakEventManager line 340ish).  I'm not exactly sure why many people don't have this issue too but suspect it's because my ViewModel is getting it's properties set from ANT and BTLE hardware rather than a UI event.

I'm happy to submit a pull request; however, I'm not sure if it would be better to lock whenever changing or iterating handlers or if for performance it would be better to iterate on a copy collection.

**Comment by jlaanstra** [comment]
This is most likely by design.

**Comment by jlaanstra** [comment]
WeakEventManager was designed for use on a single thread so this is by design.

**Comment by lorentzm** [comment]
@jlaanstra, is it expected that all events a ViewModel interacts with will come through the UI thread?  This seems very limiting. Maybe, I'm misunderstanding the expected use. Can you help me out with a little more explanation?

It appears WeakEventManager is used for marshaling all property and collection changing and changed events on view-models.  Based on what you're telling me, this means that view-model properties and collections can only be changed from a single thread.  This puts me in a position where code in my view-model needs to care about the ui thread when being used with a view that has such a thing.  This is a violation of the encapsulation of the view.

Perhaps, the design is incorrect. This is a very easy problem to fix, I've made the fix in a version of my app that over 5k people have been using for a month or so now.  The exception went from happening several times a day to never happening. As I said before, I'll be happy to submit a patch or pull request if it helps.

**Comment by pdoh00** [comment]
I'm not sure if this is the same use case, but I am able to receive events in my ViewModels from separate threads.  The key is to use ObserveOn in order to marshal it correctly. 

Ex.
```
var locationChangeObs = 
  Observable.Publish<Location>(
    Observable.FromEventPattern<EventHandler<LocationChangedEventArgs>,LocationChangedEventArgs>(h => x.LocationChanged += h, h => x.LocationChanged -= h)
    .ObserveOn(RxApp.MainThreadScheduler));
```

**Comment by lorentzm** [comment]
@pdoh00, I'm aware that I can use the ObserveOn but it seems wrong to need to use the MainThreadScheduler in a ViewModel.  Only the view cares about the main thread, forcing this on the view model seems that it creates unnecessary burden that the developer has to be concerned with.  Isn't it more natural for the view to use ObserveOn(RxApp.MainThreadScheduler) and to have the bindings for views that need things to happen on the main thread to marshal to the main thread?

Come to think of it, I've noticed a time or two where a binding in Xamarin.iOS doesn't go to the main thread as I would expect it to and I have to fall back to using ObserveOn(RxApp.MainThreadScheduler) in the view model.  So, maybe this was a bigger design choice than just the WeakEventManager.

PS, didn't we have lunch a couple months back?

**Comment by pdoh00** [comment]
@lorentzm I don't want to be pedantic, but maybe some clarification on *"is it expected that all events a ViewModel interacts with will come through the UI thread? ".*  The answer to that is no. 

**But** all notifications of change to a property updated from another thread will happen on that other thread. 

The ViewModel is on the same thread as the View. If the view is bound to said property, it's going to get a notification on the wrong thread.  That's where the ObserveOn in the VM comes in.  By placing that on the event Subscription then the notifications end up getting marshaled back to the UI thread so the view works correctly :sparkles: 

From the View(i.e. Code Behind) the syntax doesn't really support ObserveOn. this.Bind(...), this.OneWayBind(...).  In addition (after a discussion with @paulcbetts) it could cause some very difficult debug problems to add the ObserveOn inside the Bind.

As for the iOS expectation....I am not sure I would expect that the binding would go to the UI thread.  As per above RxUI won't marshal it.  I think it will be platform dependent at best.  

In WPF for example scalars end up getting marshaled, but collections do not. If I use xaml binding.

PS. Yep we did have lunch a few months back. Thanks again

**Comment by lorentzm** [comment]
@pdoh00 Thanks for the explanation.  If there's a problem having the bindings enforce execution on the main thread then there's no reason to have the WeakEventManager safe for multiple threads.  
Also, not so bad to use the ObserveOn in the view model now that I think about it. Less to worry about in the view so better reuse across platforms.
