### ISSUE TITLE
ReactiveCommand's 'canExecute' should always be BehaviorSubjects?

### ISSUE THREAD

**Issue by thedillonb** [reactiveui/ReactiveUI#818]
The `canExecute` parameter to create a `ReactiveCommand` is a little odd to me and I was hoping someone might shed some light on what is actually going on. It would seem that the type of observable that is passed is extremely important. If I pass in a basic `Subject` that produces a few values before the command's `CanExecuteObservable` is subscribed I end up getting the wrong result. On the other hand, if I use a BehaviorSubject then I get the right result. Here's my example:

```
// In my View Model:
var list = new ReactiveList<T>();
CommandProperty = ReactiveCommand.CreateAsync(list.IsEmptyObservable.Select(x => !x), ...)

// Later in my View Model
list.Add(...)

// Later in my View's ctor once the ViewModel is attached
this.WhenAnyObservable(x => x.ViewModel.CommandProperty.CanExecuteObservable)
     .Subscribe(x => Console.WriteLine("The value is: " + x);
```

This always results in `False` even though it should be obvious that it should return true as the list is *not* empty. Unfortunately, as I suspect, this is because the subject is a plain `Subject` and the `ReactiveCommand` doesn't connect to the observable until `CanExecuteObservable` is called. If this is true, then it means I either have to subscribe to the `CanExecuteObservable` before I do anything (which I cant since the ViewModel needs to construct before the View can attach - duh) or I have to use a `BehaviorSubject`.

If I've made sense up to here this begs the question: Why does `ReactiveCommand` not immediately connect upon construction? This would prevent the user from having to know what type of IObservable they're passing in and also prevent them from having to trigger a subscription to `CanExecuteObservable` before they do anything that might flip the `canExecute` observable.

**Comment by kentcb** [comment]
This is fixed by #971, soon to be merged.
