### ISSUE TITLE
ViewModel and View are immediately deactivated on Windows Phone 8.1

### ISSUE THREAD

**Issue by flagbug** [reactiveui/ReactiveUI#822]
I'm using `WhenActivated` in a Windows Phone 8.1 application and as soon as a page is loaded, the disposable in the `WhenActivated` method is immediately disposed.

I've stepped through the `ActivationForViewFetcher` class at https://github.com/reactiveui/ReactiveUI/blob/5954c53255832ea0fb9d8c8a6ccef18cd334f742/ReactiveUI/Xaml/ActivationForViewFetcher.cs#L39 and it seems like `IsHitTestVisible` changes from `true` to `false` and then back to `true` again. so when it reaches `false` the Disposable in `WhenActivated` is disposed

I don't have much insight into the activation code, so I'm not sure how this can be fixed

**Comment by flagbug** [comment]
Oh, seems like someone on the RxUI mailing list had a similar problem: https://groups.google.com/forum/#!topic/reactivexaml/mgkhk3kCO5c

**Comment by jcmm33** [comment]
I found its related to the built in transitions causing this, if you remove the transitions it will resolve the issue.  A better fix is needed however.

**Comment by flagbug** [comment]
Hm, so basically we have to check if transitions are enabled, and if they are, ignore the first `true` and `false` value

**Comment by jlaanstra** [comment]
Maybe we should just ignore IsHitTestVisible?

**Comment by flagbug** [comment]
Well, that would work for me :smile:

No idea if that would break anything for anyone else

**Comment by jcmm33** [comment]
Of the top of my head i can't see why removing it would have any detrimental affect.
