### ISSUE TITLE
Signed version of ReactiveUI for Nuget

### ISSUE THREAD

**Issue by kishorejangid** [reactiveui/ReactiveUI#828]
Hi,

Is it possible to sign the version of ReactiveUI for Nuget, I want to use this assembly in one of my project, but since this is not signed, I have some difficulties.

**Comment by ghuntley** [comment]
![](http://www.reactiongifs.com/wp-content/uploads/2011/05/tumblr_ljh0puClWT1qfkt17.gif)

**Comment by jen20** [comment]
Pretty sure this link will answer that:
http://log.paulbetts.org/a-modest-proposal-strong-naming-carbon-offsets/

>

-- 
James

**Comment by kishorejangid** [comment]
Mine is not yet a commercial product yet, so I am closing this.

**Comment by ghuntley** [comment]
See also issue #843
