### ISSUE TITLE
ReactiveUI-Events doesn't have "Click" for a Windows Store Button

### ISSUE THREAD

**Issue by gordonwatts** [reactiveui/ReactiveUI#832]
When trying to hook the Click event of a Button up to execute a command (not attached to a ViewModel, so I couldn't use BindCommand), I discovered that Click wasn't implemented in ReactiveUI.Events. Is there a reason for that, or just an oversight? If an oversight would you take a PR (or someone else would do it)?

**Comment by paulcbetts** [comment]
All of ReactiveUI.Events are generated code - digging out why Click doesn't show up might not be a Joy (it looks to be defined on ButtonBase)

**Comment by paulcbetts** [comment]
All of ReactiveUI.Events are generated code - digging out why Click doesn't show up might not be a Joy (it looks to be defined on ButtonBase)

**Comment by jlaanstra** [comment]
> All of ReactiveUI.Events are generated code - digging out why Click doesn't show up might not be a Joy (it looks to be defined on ButtonBase)

The same applies to WPF, so assuming it works there, the cause is probably in the reflection code.

**Comment by flagbug** [comment]
Works on my machine

![click-events-reactiveui](https://cloud.githubusercontent.com/assets/964691/7021627/eb8c4722-dd23-11e4-8f90-9deb5fb2d5f5.png)

`CloseDetailViewButton` is of type `Button`

App is a Windows 8.1 Store app

**Comment by shiftkey** [comment]
@flagbug @gordonwatts which versions of `reactiveui-events` are we using here?

**Comment by flagbug** [comment]
@shiftkey 6.4.0.1

**Comment by flagbug** [comment]
Aha! I had a reference to the `Win81` profile in the NuGet package where the `Click` event exists, but it seems like it's missing in the `WPA81` profile.

**Comment by gordonwatts** [comment]
That is the issue for me, then. I'm using the WPA81.

**Comment by gordonwatts** [comment]
Since this is a difference in the implementations is it obvious what happened to one of you (e.g. it didn't get rebuilt) or shall I investigate?

**Comment by jlaanstra** [comment]
Can you try  using Windows.UI.Xaml.Controls.Primitives?

**Comment by gordonwatts** [comment]
How do you mean (and was that suggestion addressed to me)?

**Comment by kentcb** [comment]
I believe @jlaanstra meant adding a `using` statement for `Windows.UI.Xaml.Controls.Primitives`. Because events is generated code, the events for a given control are generated in the same namespace as said control. Since the event you want is on the base class, and the base class is in a different namespace to the derived class, you have to take the somewhat confusing step of including the base class's namespace.

**Comment by Odonno** [comment]
I had the same problem yesterday. Feels weird because there is no way to find Click event except to add the `using` manually.
