### ISSUE TITLE
Memory leak with a hidden ViewModelViewHost

### ISSUE THREAD

**Issue by xardison** [reactiveui/ReactiveUI#835]
Test example
https://github.com/xardison/TestExampleForReactiveUI

Steps to reproduce:
1) navigate to SwitcherView (they have 2 ViewModelViewHost: 'LeftView'(hidden) and 'RightView'(visible))
2) navigate back to BlankView
3) collect garbage

Finally destroyed all viewmodels except 'LeftViewModel' and his view 'LeftView'. When I commented out the WhenActivated in LeftView and tried again then it worked fine.

Also seen strange behavior when LeftView and RightView were created twice.

**Comment by xardison** [comment]
Of course this is not the solution, but this crutch helps me in both cases. On deactivate, I simply removed the ViewModel out of the ViewModelViewHost. Perhaps useful to someone else.

The static class ViewForMixins (file [Activation.cs](https://github.com/reactiveui/ReactiveUI/blob/master/ReactiveUI/Activation.cs) in ReactiveUI), change the line:
```var viewDisposable = handleViewActivation (block, activationEvents);```
on
```var viewDisposable = handleViewActivation (block, activationEvents, v as IViewFor);```

and
```static IDisposable handleViewActivation(Func<IEnumerable<IDisposable>> block, IObservable<bool> activation)```
on
```static IDisposable handleViewActivation(Func<IEnumerable<IDisposable>> block, IObservable<bool> activation, IViewFor viewFor)```

after the following lines:
```
if (activated) {
    viewDisposable.Disposable = new CompositeDisposable (block ());
}
```
adding:
```
else
{
    if (viewFor is ViewModelViewHost)
    {
        viewFor.ViewModel = null;
    }
}
```

**Comment by davecader** [comment]
As confirmation, I had a similar problem with memory leaks when using a ViewModelViewHost within the body of an Expander control. If the Expander was closed the ViewModelViewHost appeared to interfe with garbage collection, however this problem went away if the window was expanded. Unfortunately, I ended up having to replace ViewModelViewHost with a standard DataTemplate and ContentControl (boo).

**Comment by kentcb** [comment]
Without digging into the sample, not sure what platform this is. However, I suspect #1314 is the same thing (WPF).
