### ISSUE TITLE
Why are things internal in IReactiveObjectExtensions?

### ISSUE THREAD

**Issue by aventurella** [reactiveui/ReactiveUI#837]
https://github.com/reactiveui/ReactiveUI/blob/master/ReactiveUI/IReactiveObject.cs

I'm sure there is a good reason, I'm just curious as to why, same with the private classes in there as well. It pretty much means you are absolutely not allowed to create Custom Reactive Objects like the Cocoa NSViewController. So is there a reason to disallow users from creating their own reactive objects?

**Comment by paulcbetts** [comment]
What class are you trying to create?

**Comment by aventurella** [comment]
I'm trying to make a variation on the Cocoa.NSViewController that lines up more with some of the names and ways of working my team is used to. I could just subclass `NSViewController`, this is true. But as a lesson as to how it's all put together (ReactiveObjects), and doing some things the way our team does them, I ran into that internal/private wall that stopped me. I was more just curious the rationale behind preventing that kind of use. Here's the rope, if you wanna hang yourself, go nuts, we don't recommend it, but it's your party!

**Comment by aventurella** [comment]
More Concrete Example: There is no `WKInterfaceController` in the Cocoa examples right now, but I could have built my own if those private/internal values prohibit it.

**Comment by aventurella** [comment]
Another concrete example: we have our own UITableViewCell subclass, and I am using it, but I just need to add support for binding. If I could just make my one-off subclass reactive, I could do this. Instead I have to subclass ReactiveTableViewCell, add all of our methods back into it from our custom table view cell for working with models. Now that code is duplicated in 2 locations and makes me sad =,(

Or I have to convert all of our custom methods to extension methods on UITableViewCell, which is what I will likely end up doing. It would have been easier and I would not have had to refactor our custom library if I could choose when I need to implement reactive things.

**Comment by aventurella** [comment]
Another concrete example: 
It would be nice to have a ReactiveNSObject

**Comment by paulcbetts** [comment]
I'm not disagreeing with any of these, I just don't know the best way to make it happen, there's no such thing as a 'protected internal extension method'

**Comment by aventurella** [comment]
Is there a functional reason to keep some of the members of:
`public static class IReactiveObjectExtensions` **internal**?

I guess what I am getting at is, given this is an open source project, and individuals can freely attempt to fully understand the ramifications of their chosen implementations by viewing how it all works, why force the internal nature of some of those members. Unless of course there is a functional reason to prohibit access to them.

Freeing those from their `internal` bonds lets you off the hook for having to maintain, for example,  the Cocoa/ lib. I'm sure you are a busy guy do you really want to deal with: Hey I need NSObject or I need WKInterfaceController. Or you could say: ya sure go nuts and make your own, I have some sample implementations in Cocoa/ that shows what you need to do.

Also, if it's not clear, I really appreciate this lib. It's simplified many a thing for me, so I definitely appreciate it!

**Comment by paulcbetts** [comment]
The reason that it's internal is because otherwise these methods show up on anyone who is _using_ ReactiveObjects, so they are encouraged to do Incorrect Things like call `raisePropertyChanged`, and it ends up polluting the public API (i.e. what people discover via Intellisense)

**Comment by aventurella** [comment]
mmmmmm I definitely appreciate the Intellisense concern there. 
You'd end up with:

```
raisePropertyChanged
RaisePropertyChanged
```

and people getting confused or accidentally, with a slip of the finger, choosing the wrong method.

I definitely agree it's the right choice, it just seems like the trade off there is pretty expensive. Coding the API to cater to Intellisense sacrifices a lot of possibilities.

Reviewing some of the code a solution doesn't immediately come to mind either. But it's also the end of the day for me.

The goal of any solution would be to ideally keep Intellisense clean I take it?  Would you be opposed to something like:

```csharp
using System.ComponentModel;
[EditorBrowsable(EditorBrowsableState.Never)]
```

It would still show up internally, but anyone using it externally would not see the method in Intellisense. you would have to know it's there.

Follow that with something like (using a different method here as an example)

```csharp
/// <summary>
/// Represents an Observable that fires *after* a property has changed.
/// </summary>
public IObservable<IReactivePropertyChangedEventArgs<ReactiveViewController>> Changed {
    // getChangedObservable exists, but is intentionally hidden from Intellisense
    // so no one attempts to do weird things.
    get { return this.getChangedObservable(); }
}
```
