### ISSUE TITLE
WhenActivated executes when setting child viewmodel to null?

### ISSUE THREAD

**Issue by bradtwurst** [reactiveui/ReactiveUI#839]
Have a wpf application with two view/view model pairs.

The first has a ViewModelViewHost control that hosts the second

The button on the main view triggers the command action in the main model that sets the level1 property to null.  This causes the WhenActivated logic in the Level1 Model to execute.

I didn't expect this behavior.  Is it correct?  

I'm referencing the current version on nuget. (6.1.0.4)

``` xml
<!-- MainWindow.xaml -->
    <StackPanel>
        <Button x:Name="DoIt">Do It</Button>
        <reactiveUi:ViewModelViewHost x:Name="Level1" />
    </StackPanel>
```

``` c#
// MainWindow.xaml.cs
this.WhenActivated(d =>
{
  d(this.OneWayBind(ViewModel, vm => vm.Level1, v => v.Level1.ViewModel));
  d(this.BindCommand(ViewModel, vm => vm.DoItCmd, v => v.DoIt));
});
```

``` c#
// MainWindowModel.cs
MainWindowModel() {
  Level1 = new Level1Model();
  DoItCmd = ReactiveCommand.CreateAsyncTask(o =>
  {
    Level1 = null;
  });
}

private Level1Model _Level1;
public Level1Model Level1
{
get { return _Level1; }
set { this.RaiseAndSetIfChanged(ref _Level1, value); }
}
```

``` c#
// Level1.xaml.cs
this.WhenActivated(d =>
{
  Console.WriteLine("this logic is executed when level1 is set to null in main model");
  // other bindings...
});
```

**Comment by jlaanstra** [comment]
Can you provide a repro project?

**Comment by bradtwurst** [comment]
I've created a repository for an example at https://github.com/bradtwurst/ReactiveUiActivationIssue

it has message boxes embedded in both WhenActivated methods.

on startup, the main window's WhenActivated is executed.

clicking the DoIt button causes the child viewmodel to be created, which triggers the WhenActivated to execute (as expected).

clicking the DoIt button again sets the child viewmodel to null, which also triggers the WhenActivated for the child view model to execute.  I didn't expect this.

**Comment by Wouterdek** [comment]
It seems this bug is still present. Except, is it a bug? The documentation for WhenActivated never actually seems to specify what it really does. It triggers a notification when the view is "activated", but I can't seem to find what "activated" really means anywhere. Is it when the element enters the visual tree? Is it when the view gets a viewmodel assigned to it? Is it both?

I would update [the documentation](https://reactiveui.net/docs/handbook/when-activated/), but I don't know the answers.
