### ISSUE TITLE
Faulty Assembly References in NuGet-Package for .NET 4.5

### ISSUE THREAD

**Issue by MovGP0** [reactiveui/ReactiveUI#842]
when I create a WPF Application and add reactiveui core, then I get the error message 

```
Show Details	Severity	Code	Description	Project	File	Line
	Error	CS0012	The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
```

I reproduced the error with .NET Framework 4.5, 4.5.1, 4.5.2, and 4.6 with reactiveui 5.5.1 and 6.4.0.1. The code still works besides the compiler error. 

The error can be solved by manually deleting the reference to `\packages\reactiveui-core.6.4.0.1\lib\Portable-Net45+Win8+WP8+WPA81` and manually adding a reference to `\packages\reactiveui-core.6.4.0.1\lib\Net45`. So I guess there is something wrong with the NuGet package.

**Comment by paulcbetts** [comment]
Both of those versions definitely work, I think your machine / environment is not working properly. What version of VS / NuGet are you using?

**Comment by MovGP0** [comment]
Visual Studio 2015 CTP 6, NuGet 3.0.60225.100

**Comment by paulcbetts** [comment]
What happens when you use VS2013 Update 4 (i.e. the latest released VS)?

**Comment by ghuntley** [comment]
RxUI 6.5 is Working w/ 2015 Update 1.
