### ISSUE TITLE
Provide an snk file

### ISSUE THREAD

**Issue by MovGP0** [reactiveui/ReactiveUI#843]
There should be a public .snk file, so that reactiveui can be used from strongly signed assemblies. 

Such a key would naturally not allow to verify authorship, but it would allow for strong identification of the assembly and therefore be good enough for most purposes. 

Customers that need increased security could still replace the public .snk files with their own private keys. 

https://msdn.microsoft.com/en-us/library/h4fa028b(v=vs.100).aspx

**Comment by flagbug** [comment]
I'll just point you to this: http://log.paulbetts.org/a-modest-proposal-strong-naming-carbon-offsets/

**Comment by MovGP0** [comment]
I have read this comment. However, it is a red herring argument, since a secure private strongly key is not required. A public key without password would do and it only requires a few clicks.

**Comment by paulcbetts** [comment]
Send me an Email if you would like this service to be provided!

**Comment by MovGP0** [comment]
no need. i can do it myself...

**Comment by ghuntley** [comment]
Linking issue #828 to issue #843
