### ISSUE TITLE
Reaxctive ui initialization windows phone xamarin forms

### ISSUE THREAD

**Issue by BrunoVT1992** [reactiveui/ReactiveUI#844]
Hi is it possible to show me how to initialise rxui in win-phone with xamarin forms like the evolve example?

**Comment by ghuntley** [comment]
https://github.com/ghuntley/starter-mobile/blob/master/src/StarterMobile.WPA81/App.xaml.cs#L43 + a ```Forms.Init();```

**Comment by ghuntley** [comment]
Tagging #771 as reminder to cover this area in the documentation. If you progress please reply back and share with the community your findings.
