### ISSUE TITLE
Adding a reason to the canExecute observable

### ISSUE THREAD

**Issue by Evangelink** [reactiveui/ReactiveUI#853]
I am trying to create a custom ReactiveCommand that will allows me to specify a reason (string) along with the canExecute.

I have created a simple object that contains a bool and a string property and I have replaced the IObservable<bool> by an IObservable of my new type and I am calling the base class (i.e. ReactiveCommand) with a select on the boll property of my object. This seems to be working properly.

My question is how to expose the string property (the reason) to have the UI to be triggered (using the notifications) as the ReactiveCommand doesn't inherit from ReactiveObject.
- Implementing a simple version of the INotifyPropertyChanged works but seems a bit stupid as you already have an object that does it (and with a lot more functionalities). 
- Exposing an object inheriting from the ReactiveObject works also but again I don't think this can be the best idea.

What would you recommend?

**Comment by pdoh00** [comment]
Maybe something like this would work for you. It's not really a custom ReactiveCommand, but it does give you an opportunity to give a reason to the true/false ness of the CanExecute.

```
public class MySimpleObject
{
    public bool SomeBool{get;set;}
    public bool SomeString{get;set;}
}

ctor()
{
    CanExectute = (...); //set your bool and reason here
    this.WhenAnyValue(x=>CanExectute.SomeString)
          .ToProperty(this, x=>x.StringToExpose, out _StringToExpose);
    var cmd = ReactiveCommand.Create(this.WhenAnyValue(x=>x.canExecute.Select(x=>theBoolPart);
}

private MySimpleObject_CanExectute ;
private MySimpleObject CanExectute
{
    get { return _CanExectute; }
    set { this.RaiseAndSetIfChanged(ref _CanExectute, value); }
}

private ObservableAsPropertyHelper<string> _StringToExpose;
public bool StringToExpose
{
        get { return _StringToExpose.Value; }
}
```

**Comment by Evangelink** [comment]
Thank you for your answer @pdoh00 but except if I missed something on your explanation, I prefer to keep something that inherits from ReactiveCommand and just implement the INotifyPropertyChanged. I was mainly looking for a way to have something nice enough to suggest it as a PR looks like I still need some practice before I am able to do so.

**Comment by kentcb** [comment]
Something like:

```C#
public class ViewModel : ReactiveObject
{
    public string RequiredField { /* get/set with RaiseAndSetIfChanged */ }

    // an OAPH
    public string Message => this.message.Value;

    public ViewModel()
    {
        var message = this
            .WhenAnyValue(x => x.RequiredField)
            .Select(value => string.IsNullOrEmpty(value) ? "Need that!" : null);

        this.message = message.ToProperty(...);

        this.command = ReactiveCommand.Create(
            () => { /* do whatever */ },
            message.Select(x => x == null));
    }
}
```
