### ISSUE TITLE
ReactiveListAdapter calls NotifyDataSetChanged on wrong thread

### ISSUE THREAD

**Issue by jorisvergeer** [reactiveui/ReactiveUI#859]
Shouldn't the ReactiveListAdapter have ObserveOn(RxApp.MainThreadScheduler) when it subscribes on the Changed Observable in its constructor?

**Comment by flagbug** [comment]
Treat `ReactiveListAdapter` as UI control, i.e it's the callers responsibility to make sure any events to `ReactiveListAdapter` are dispatched on the UI thread, just like with normal UI controls
