### ISSUE TITLE
Shouldn't WhenAnyObservable be an empty observable when the expression is broken?

### ISSUE THREAD

**Issue by thedillonb** [reactiveui/ReactiveUI#866]
Take the following code for example:

```
this.WhenAnyObservable(x => x.ViewModel.Command)
                    .Subscribe(_ => { ViewModel = null; });
```

The `this` is a `ReactiveObject` which raises events for the `ViewModel` property. As expected, when `ViewModel` is assigned, the subscription is made and my command, when executed, will trigger the subscription delegate - everything is good so far. However, when I assign my `ViewModel` to null I would have expected executing the `Command` **not** to trigger the subscription delegate, but it does.

Why is it that a break in the expression does not result in an `Observable.Empty` to be switched onto?

**Comment by kentcb** [comment]
This is by design. See #976.
