### ISSUE TITLE
ViewModelViewHost is fundamentally flawed on iOS

### ISSUE THREAD

**Issue by kentcb** [reactiveui/ReactiveUI#868]
The current `ViewModelViewHost` implementation on iOS is a helper/utility class, not a UIKit class. It works by adding the resolved view to a target view on behalf of the caller. The problem is that the resolved view is a view controller but no attempt is made to integrate that view controller into the controller hierarchy. As such, there is a mismatch between the controller and view hierarchies, causing things to simply not work.

For example, if the resolved view is a `UITableViewController` and the target view is the view of a `UINavigationController`, the latter has no idea about the former and things go awry when attempting to navigate away from the `UITableViewController`.

Another problem is that it does not dispose of the old controller when a new one is created. This can cause old subscriptions to fire when they're no longer wanted. Since the `ViewModelViewHost` is responsible for the creation of the view controller, it too is responsible for disposing of it at the appropriate point in time.

My proposal (which I'll submit as a PR as soon as I have the time) is to replace the existing implementation with an implementation that is actually a view controller itself. This view controller would monitor its `ViewModel` property and dynamically swap in the appropriate view when the view model changes. Since it is actually a controller, one incorporates it into their controller hierarchy just as they would any other controller.

Example:

```C#
var host = new ViewModelViewHost();
host.ViewModel = ...;
host.NavigationItem.Title = "Foo";
var navigation = new UINavigationController(host);
```

**Comment by paulcbetts** [comment]
While I agree with your general proposal, at the time nested ViewControllers were a _very_ new feature of iOS and to be honest I didn't really understand it. Instead of paving VMVH, maybe just create a 2nd class?

**Comment by kentcb** [comment]
Sure - any ideas what to call it? Maybe `ViewModelViewControllerHost`?

**Comment by paulcbetts** [comment]
:+1:

**Comment by kentcb** [comment]
@paulcbetts thinking about this a bit more, would you be opposed to:

* renaming the existing `ViewModelViewHost` to, say, `ViewModelViewHostLegacy`
* marking it obsolete
* calling the new implementation `ViewModelViewHost`

The advantages of this would be:

* a consistent name for the recommended class. We can just say "use `ViewModelViewHost` for your chosen platform" instead of "use `ViewModelViewHost` unless you're on iOS, in which case use `ViewModelViewControllerHost`
* we intentionally break upgraders to make them consciously opt into using the legacy implementation or make the requisite changes to their code to use the revised/recommended solution
