### ISSUE TITLE
Erro on start an application using last nuget packets

### ISSUE THREAD

**Issue by jbravobr** [reactiveui/ReactiveUI#871]
Retrieve from the stack 

System.AppDomain.Load (assemblyRef={Splat, Version=1.6.2.0, Culture=neutral, PublicKeyToken=null}, assemblySecurity=(null)) in /Users/builder/data/lanes/1503/e6ebd18b/source/mono/mcs/class/corlib/System/AppDomain.cs:706

**Comment by kentcb** [comment]
Did you upgrade Splat after installing RxUI? See this similar issue: #860

**Comment by jbravobr** [comment]
@kentcb Yeap it's updated to last version (i guess it's 1.6.2)

**Comment by ghuntley** [comment]
Believe fixed in https://github.com/reactiveui/ReactiveUI/pull/905
