### ISSUE TITLE
BindCommand works in C# but not in VB

### ISSUE THREAD

**Issue by reader-man** [reactiveui/ReactiveUI#876]
Hi, i use VB in coding, so i converted a sample project to VB, and everything complies correctly, but one line, does not:

<pre lang="vb">    Public Sub New()
        InitializeComponent()
        VM = New HomeViewModel()

        ' Bind the view to the ReactiveUI viewmodel
        Me.Bind(VM, Function(x) x.EnteredText, Function(x) x.textBoxMyInput.Text)
        Me.Bind(VM, Function(x) x.Status, Function(x) x.toolStripStatusLabel1.Text)

        Me.BindCommand(VM, Function(x) x.OKCmd, Function(x) x.btnOK)
    End Sub</pre>
    

<b>the line is:</b>
<b><u><i>Me.BindCommand(VM, Function(x) x.OKCmd, Function(x) x.btnOK)</i></u></b>

<b>the error:</b>
Error   1   BindCommand is not a member of ReactiveUI_WinForms.Form1

<b>the project in c#:</b>
https://github.com/nrodriguez2001/WinFormMVVM

<b>here is, the converted project:</b>
http://1drv.ms/1G8eJgW

can you please help, it made me scratch all my head, as the C# code, compiles correctly.

**Comment by paulcbetts** [comment]
BindCommand is an extension method, not sure how those get pulled in on VB

**Comment by reader-man** [comment]
Also "Bind" is an extension method, but it works.
Can it be, that the "BindCommand" is deleted from the ReactiveUI project, and if so, whats the alternative?

**Comment by shiftkey** [comment]
Back in the good old days, `BindCommand` was only specific to WPF projects.

In the latest versions, there's an abstraction `ICommandBinderImplementation` which let's you control how to bind commands for your platform. I've not tried this with WinForms though - who's the best person to ask about that, gang?

**Comment by kentcb** [comment]
Bizarrely, it is because `CommandBinding` has a generic constraint against `IViewFor<T>` whereas `Bind` has a generic constraint against `IViewFor`. I proved this by defining my own copy of the extension methods and simplifying until it resolved.

Could this be a VB compiler bug?

**Comment by gardnerbp** [comment]
The main problem is that BindCommand is an extension - in C# the this parameter is passed implicitly, while in VB.Net we must pass it explicitly as follows:

ReactiveUI.CommandBinder.BindCommand(Me, VM, Function(x) x.OKCmd, Function(x) x.btnOK)

**Comment by kentcb** [comment]
Thanks @gardnerbp!
