### ISSUE TITLE
ReactiveUI 6 .NET 4.0 support

### ISSUE THREAD

**Issue by timotei** [reactiveui/ReactiveUI#883]
Hello,

I see that RUI 6 doesn't have .NET 4.0 support. However, there are many projects/people out there that really want to use it but they are stuck with the old 4 version (and sadly they can't upgrade in the foreseeable future to .NET 4.5). 

So, I am asking if you would accept a PR that would enable ReactiveUI 6 .NET 4.0 support; before starting to actually work on it.

Initial foray into the issue reveals that the support would be achieved quite easily without many code changes (we can use Microsoft.Bcl.Async for async/await stuff). This will also require Splat support for .NET 4.0 but that's very easy as well to do.

What do you think?

Thanks!

**Comment by kentcb** [comment]
I gotta warn you: using Microsoft.Bcl.Async from a library was a pretty terrible experience for me, so much so that I ended up just dropping 4 support from my OSS projects that were using it. It wasn't even particularly pleasant to use from an application.

**Comment by paulcbetts** [comment]
Are you kidding me?
