### ISSUE TITLE
Akavache with ReactiveUI's ReactiveCommand not working in Windows 8.1 Universal App

### ISSUE THREAD

**Issue by martingemme** [reactiveui/ReactiveUI#886]
I’m trying to make work Akavache with ReactiveCommand within a Windows 8.1 Universal application, just like @paulcbetts did at Xamarin Evolve.

To make sure that it is not related to my architecture, I did an empty solution that has all the necessary packages and requirements (VC++ for both platforms), and I still get the same issue. This is a blocker for me since I want all my queries to be cached.

```c#
BlobCache.ApplicationName = "MyApp"; // In AppBootstrapper`

// In My ViewModel
SubmitCommand = ReactiveCommand.CreateAsyncTask(async _ =>
{
    var isTrue = await BlobCache.UserAccount.GetOrFetchObject("login_credentials",
        async () => await Task.FromResult(true)
    );
    // My Code never goes further than this

    if (!isTrue)
    {
        throw new Exception("I'm false!");
    }

    return isTrue;
});

SubmitCommand.Subscribe(isTrue => {
    Debug.WriteLine("I got a new value!");
});

SubmitCommand.ThrownExceptions.Subscribe(ex => {
    UserError.Throw(ex.Message, ex);
});

// In The View
ViewModel = new MainPageViewModel();
this.BindCommand(ViewModel, x => x.SubmitCommand, x => x.SubmitCommand);

public MainPageViewModel ViewModel
{
    get { return (MainPageViewModel)GetValue(ViewModelProperty); }
    set { SetValue(ViewModelProperty, value); }
}
public static readonly DependencyProperty ViewModelProperty =
    DependencyProperty.Register("ViewModel", typeof(MainPageViewModel), typeof(MainPage), new PropertyMetadata(null));

object IViewFor.ViewModel
{
    get { return ViewModel; }
    set { ViewModel = (MainPageViewModel)value; }
}
```
I have the following stacktrace when I hover `BlobCache.LocalMachine`:
```StackTrace
at System.StubHelpers.StubHelpers.GetWinRTFactoryObject(IntPtr pCPCMD)
at Windows.Storage.ApplicationData.get_Current()
at Akavache.WinRTFilesystemProvider.GetDefaultSecretCacheDirectory()
at Akavache.Sqlite3.Registrations.<>c__DisplayClass6.<Register>b__4()
at System.Lazy1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Lazy1.get_Value()
at Akavache.Sqlite3.Registrations.<>c__DisplayClass6.<Register>b__5()
at Splat.ModernDependencyResolver.GetService(Type serviceType, String contract)
at Splat.DependencyResolverMixins.GetService[T](IDependencyResolver This, String contract)
at Akavache.BlobCache.get_Secure()
```

I'm using RXUI 6.5 (latest) with a Windows 8.1 Universal.

**Comment by martingemme** [comment]
After some debug, I decided to pull Akavache, link the dummy solution to Akavache's dll and now I get to SQLite.cs, line 3129 with: Additional information: Something went wrong in the build configuration.  This is the bait assembly, which is for referencing by portable libraries, and should never end up part of the app.  Reference the appropriate platform assembly instead.
The code looks like:
```
public static Result Open(string filename, out Sqlite3DatabaseHandle db, int flags, IntPtr zVfs)
{
#if USE_WP8_NATIVE_SQLITE
	return (Result)Sqlite3.sqlite3_open_v2(filename, out db, flags, "");
#else
	return (Result)Sqlite3Raw.sqlite3_open_v2(filename, out db, flags, null); // Exception happens here
#endif
}
```
So... what's missing? Which assembly am I not referencing?

**Comment by martingemme** [comment]
After some more debug, I was able to make work WinRT. Now Windows Phone 8.1 (Non-Silverlight/Jupiter) isn't working at all. It seems that I can't access (even with Akavache's Master) the Registrations method of Akavache.Sqlite3 and I result in a TypeInitializationException.

**Comment by martingemme** [comment]
So it was a Akavache related matter. Versioning of SQLite.raw vs SQLite.raw_basic. for more information, look here: https://github.com/akavache/Akavache/issues/230

**Comment by shiftkey** [comment]
@martingemme does this need to be kept open?

**Comment by martingemme** [comment]
I am still unsure if it is because it is because it doesn't register correctly in a ReactiveUI application or Akavache related (akavache/Akavache#230).
