### ISSUE TITLE
Nuget build is broken, tied to Splat 1.0.0

### ISSUE THREAD

**Issue by fahadash** [reactiveui/ReactiveUI#889]
Pulled latest from Nuget into my new WPF Application, ran the project to get the following error

Could not load type 'Splat.IEnableLogger' from assembly 'Splat, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.":"Splat.IEnableLogger"}	System.Exception {System.TypeLoadException}

Updating splat to 1.6.2 fixed the issue. The Nuget package dependencies need to be updated.

System Info:
NuGet Package Manager 2.8.6
Visual Studio 2013 (v 12.0.31101.00 Update 4)

Windows 7

**Comment by martingemme** [comment]
Isn't Splat v1.6.x? Maybe try to get first Splat v1.6.2 `Install-Package Splat -Version 1.6.2`, then reactiveui?

**Comment by fahadash** [comment]
I just installed reactiveui and trusted it to install all the correct dependencies for me. Let me try your solution.

**Comment by fahadash** [comment]
Worked. Somehow the Reactiveui release on Nuget is tied to Splat 1.0.0. May be I should change the Issue's description

**Comment by martingemme** [comment]
Great! Looks like Nuget didn't work properly.

**Comment by shiftkey** [comment]
> Worked. Somehow the Reactiveui release on Nuget is tied to Splat 1.0.0. May be I should change the Issue's description

The NuGet site has the Splat dependency defined as`(≥ 1.0 && < 2.0)` and from how [version ranges](http://docs.nuget.org/Create/versioning#Specifying-Version-Ranges-in-.nuspec-Files) work in NuGet it should be choosing the latest version that satisfies that range.

Any extra details you have about which VS and NuGet version you were using at the time would help us address this upstream, if it's repeatable...

**Comment by fahadash** [comment]
It was my work computer, I will see if I can try to log in. But it was VS2013.

**Comment by fahadash** [comment]
I tried to follow the same procedure of creating a new WPF App but could not reproduce the problem. I even went to the Package Manager and saw Splat 1.0.0 instead of the latest one in the Installed. Don't know what is so different in my particular project. I am closing this issue.

**Comment by paulcbetts** [comment]
NuGet is broken and for no reason is installing the lowest matching version, not the highest

**Comment by kentcb** [comment]
This is actually [by design](https://docs.nuget.org/release-notes/nuget-2.8):

> When resolving package dependencies, NuGet has historically implemented a strategy of selecting the lowest major and minor package version which satisfies the dependencies on the package. Unlike the major and minor version, however, the patch version was always resolved to the highest version.

This behavior can be overridden with `-DependencyVersion`:

```
install-package reactiveui -dependencyversion highest
```

But surely the problem here is that the Splat dependency is wrong? If Splat 1.0.x does not work with RxUI 6.5.0 then shouldn't the NuGet dependency be updated accordingly?

**Comment by dlech** [comment]
Looks like the missing `Splat.IEnableLogger` was [introduced in Splat 1.1](https://github.com/paulcbetts/splat/commit/4fc0aa9b63abf539f56216c76d4f59f22cfc2e37), so perhaps that should be the minimum version.

**Comment by ionoy** [comment]
This is still a problem as far as I can tell. Just installed did `install-package ReactiveUI` and got the same error as OP. `update-package Splat` helped.

**Comment by JasonBock** [comment]
Same here. Just updated some demos for my talk tomorrow and I got this error:

System.TypeInitializationException : The type initializer for 'ReactiveUI.RxApp' threw an exception.
---- System.TypeLoadException : Could not load type 'Splat.Locator' from assembly 'Splat, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

Call stack:

at ReactiveUI.RxApp.get_MainThreadScheduler()
   at ReactiveUI.Testing.TestUtils.WithScheduler(IScheduler sched)
   at ReactiveUI.Testing.TestUtils.With[T,TRet](T sched, Func`2 block)
   at ReactiveUI.Testing.TestUtils.With[T](T sched, Action`1 block)
   at CodeReactions.Tests.KeyloggerThrottledEventListenerTests.Listen()

**Comment by moswald** [comment]
I believe this is only fixed in the v7 beta.

**Comment by nibe** [comment]
I just had to run `Install-Package Splat -Version 1.6.2` after installing ReactiveUI via NuGet to get it to work.

NuGet installed Splat 1.4.0 by default as opposed to version 1.0.0 but the minimum required version seems to be 1.6.2.
