### ISSUE TITLE
Please add a way to use SVG images in ReactiveUI components

### ISSUE THREAD

**Issue by Emasoft** [reactiveui/ReactiveUI#892]
Please add a way to use SVG images in ReactiveUI components (i.e. buttons, switches, etc.).

**Comment by kentcb** [comment]
@Emasoft hi. Can you elaborate? ReactiveUI doesn't provide any UI components, so I'm not sure how this has anything to do with it.

**Comment by JohanLarsson** [comment]
Strange that there is no native support for SVG in WPF. Maybe Xaml & SVG are considered competing as they solve the same problem.

**Comment by treitmaier** [comment]
See also this [uservoice proposal](https://wpdev.uservoice.com/forums/110705-dev-platform/suggestions/8550346-support-svg-elements-in-xaml)

**Comment by jlaanstra** [comment]
Not an RxUI issue. Closing.
