### ISSUE TITLE
ReactiveCommand how to check IsExecuting state

### ISSUE THREAD

**Issue by arteny** [reactiveui/ReactiveUI#897]
Is it possible easy check IsExeuting state of command without adding additional property and background field?
I need some call that can return bool - is executing or not.

**Comment by martingemme** [comment]
You can Subscribe to IsExecuting of ReactiveCommand or await it using Take(1) or LastOrDefault. I'm usure where you need That boolean for.

**Comment by shiftkey** [comment]
Alternatively, you could map `IsExecuting` into a property using an `ObservableAsPropertyHelper` - the docs have a good walkthrough of this: 

https://github.com/reactiveui/ReactiveUI/blob/master/docs/basics/to-property.md
