### ISSUE TITLE
Add ReactiveSplitViewController

### ISSUE THREAD

**Issue by kentcb** [reactiveui/ReactiveUI#899]
The iOS platform layer is missing `ReactiveSplitViewController`.

**Comment by mteper** [comment]
Not to be forgotten: NSSplitViewController.
https://developer.apple.com/library/mac/documentation/AppKit/Reference/NSSplitViewController_Class/index.html#//apple_ref/occ/cl/NSSplitViewController

**Comment by kentcb** [comment]
Fixed by #917
