### ISSUE TITLE
Example binding mouse position/movement to viewmodel (WPF)

### ISSUE THREAD

**Issue by KingKnecht** [reactiveui/ReactiveUI#900]
I was sure I saw an example in the past which is showing how to bind the mouse position from view to viewmodel. Does anybody know this example or can show a snippet how to do that?
thx.

**Comment by shiftkey** [comment]
I haven't tested this code out (assumes WPF), but here's a rough example for your view code-behind:

```
var mouseMove = Observable.FromEventPattern<MouseEventArgs>(image, "MouseMove")
var mousePosition = mouseMove.Select(evt => evt.EventArgs.GetPosition(this));

mousePosition.Subscribe(pos => ViewModel.Position = pos);
```

This also assumes you've setup your [view bindings](https://github.com/reactiveui/ReactiveUI/blob/master/docs/basics/bindings.md).

**Comment by KingKnecht** [comment]
Thanks!
