### ISSUE TITLE
Reactive UI 6.5 has issues with IQbservable

### ISSUE THREAD

**Issue by krishan2510** [reactiveui/ReactiveUI#903]
var list = new ReactiveUI.ReactiveList<int>() { ChangeTrackingEnabled = true };
list.ItemsAdded.Where(x=>x==5).Select(x=>x).Subscribe(x => Console.WriteLine("Added:" + x));

gives following error (while with ReactiveUI 6.5, Reactive Interfaces 2.2.5 is shipped)

The type 'System.Reactive.Linq.IQbservable`1<T0>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Reactive.Interfaces, Version=2.0.20823.0, Culture=neutral, PublicKeyToken=f300afd708cefcd3'.

**Comment by gluck** [comment]
You may be referencing Rx libraries for .Net 4.0 (instead of 4.5) somehow, [this](http://stackoverflow.com/questions/13870857/is-there-some-trick-to-using-rx-from-net-framework-4-5) SO issue seems similar to yours.
Alternatively you can post your csproj file to a pastebin location of your choosing and I'll give a look.

**Comment by krishan2510** [comment]
Thanks for your quick response.

I have double checked and all references are to 4.5 libraries.

Following is the location where I have pasted the project file

http://pastebin.com/m4kXc2RN

**Comment by krishan2510** [comment]
I also have a packages.config file, following are the contents


<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="reactiveui" version="6.5.0" targetFramework="net45" />
  <package id="reactiveui-core" version="6.5.0" targetFramework="net45" />
  <package id="Rx-Core" version="2.2.5" targetFramework="net45" />
  <package id="Rx-Interfaces" version="2.2.5" targetFramework="net45" />
  <package id="Rx-Linq" version="2.2.5" targetFramework="net45" />
  <package id="Rx-Main" version="2.2.5" targetFramework="net45" />
  <package id="Rx-PlatformServices" version="2.2.5" targetFramework="net45" />
  <package id="Rx-XAML" version="2.2.5" targetFramework="net45" />
  <package id="Splat" version="1.6.2" targetFramework="net45" />
</packages>

**Comment by krishan2510** [comment]
I have been able to find the issue and resolve it, thanks again for the pointers...

There were two assemblies being referenced from the standard install of Reactive Extensions (System.Reactive.Providers and System.Reactive.Runtime.Remoting) which were causing the problem

Once I removed references of these 2 DLLs, I was able to compile the project and make it work.

Many Thanks!!
