### ISSUE TITLE
API for reactive commands can be improved

### ISSUE THREAD

**Issue by kwesolowski** [reactiveui/ReactiveUI#906]
I file it as issue to discuss some proposal. We created (for inhouse use;)) helper class `ReactiveCommandEx`, with following methods:

```
public static ReactiveCommand<Unit> CreateAlwaysAvailable(Action action);
public static ReactiveCommand<Unit> CreateAlwaysAvailableAsyncTask(Func<object, Task> action)
public static ReactiveCommand<Unit> CreateAlwaysAvailableAsyncTask(Func<Task> action)
public static ReactiveCommand<Unit> CreateAsyncTask(IObservable<bool> canExecute, Func<Task> action)

public static ReactiveCommand<Unit> CreateAsyncTask(IObservable<bool> canExecute, Func<object, Task> action)
public static ReactiveCommand<Unit> Create(IObservable<bool> canExecuteObservable, Action<object> action)
public static ReactiveCommand<Unit> Create(IObservable<bool> canExecuteObservable, Action action)
```

Which are simply wrappers for `ReactiveCommand` methods, ensuring that:

1. `ReactiveCommand<Unit>` is consistently used as return type,
2. When command is always available client code is shorter (no Observable.Return(true) everywhere :)).
3. When `Func<Task>` throws exception instead of returning faulted task it is properly converted to observable and is pushed to `ThrownExceptions`.

Is it worth integrating such functionality into ReactiveUI? If so I will create PR.

**Comment by mteper** [comment]
Could you give an example of before and after code?

**Comment by kwesolowski** [comment]
@mteper Does are mostly additions wrapping existing functionality, which code (client or library) you would like to see?

**Comment by mteper** [comment]
@kwesolowski just trying to understand the problem you are solving as it's not ringing a bell. So curious what your app code looks like without the helpers and then with.

**Comment by kwesolowski** [comment]
AD1: It is just minor annoyance - `ReactiveCommand.Create` creates `ReactiveCommand<object>` so if you change implementation to CreateAsyncTask you have to change type. Guidelines state that VM state should be used anyway (not object passed by command)).

AD2. it simply allows to replace:
`ReactiveCommand.CreateAsyncTask(Observable.Return(true), _ => actionAsync());` with:
`ReactiveCommandEx.CreateAlwaysAvailableAsyncTask(_ => actionAsync());` (with code completion this is faster to type:)).

AD3. `ReactiveCommand.CreateAsyncTask(IObservable<bool> canExecute, Func<object, Task> executeAsync, IScheduler scheduler = null)` uses `executeAsync(x).ToObservable()` to convert task to observable and use observable implementation. 

Then passed  `Func<object, IObservable<T>` is called within
```
class ReactiveCommand<T>  {
...
ExecuteAsync(...
{
 Observable.Create<T>(...
HERE
}
```
Where it will throw immediately if executeAsync(x) throws immediately instead of returning task in faulted state, causing exception to be not reported on ThrownExceptions. I can check it against latest nuget and file separate issue/PR.

And generally add conveniance method, because currently you cannot:
4a. Create synchronous version of command:
`ReactiveCommand.Create(Observable.Return(true), _ => doSth())` (you can subscribe to result of `Create` but then errors are not present in `ThrownExceptions`

4b. Create synchronous version of command not taking any argument:
`ReactiveCommand.Create(Observable.Return(true), () => doSth())` which allows shorter
`ReactiveCommand.Create(Observable.Return(true), doSth)`

4c. Create async task from async function not taking any argument (again requires ignoring it and writing lambda instead of using existing async method).

And for all three above extra overload for `AlwaysAvailable`.

**Comment by mteper** [comment]
@kwesolowski Thanks, that helps!

AD1: Perhaps @paulcbetts can speak to reason for inconsistency. Note, however, that the generic type is for the return value not input parameter.

AD2: I am pretty sure there is already an overload that lets you omit the `enabledWhen` observable.

AD3: if true, sounds like a good fix.

AD4: I'll again defer to @paulcbetts on design rationale

**Comment by patsissons** [comment]
@kwesolowski 

AD2 is definitely already in the [ReactiveCommand static functions](https://github.com/reactiveui/ReactiveUI/blob/master/ReactiveUI/ReactiveCommand.cs#L112)

AD4c could work like this perhaps (if I understand you correctly)
```csharp
ReactiveCommand.CreateAsyncTask(doSthAsync);

private Task doSthAsync(object parameter)
{
    return Task.FromResult(true);
}
```

**Comment by kwesolowski** [comment]
AD2: @patsissons Good point, i missed that - so this part is of my post is invalid.
AD4c sure it can can, but if you already have `private Task doSthAsync()` without parameter you have to wrap it in next lambda providing null (and if guidelines stating to ignore command parameters are still valid it would be clearer no to bother with this object at all).

**Comment by kentcb** [comment]
#971 radically overhauls the APIs for RxCommand. It will be merged shortly and included in RxUI 7.

**Comment by kentcb** [comment]
Further to my above comment, the only issue you raise that #971 does not address is AD3. I think you're right that exceptions thrown directly by the `executeAsync` (and `canExecute`) callbacks should be trapped and ticked through `ThrownExceptions`, so I'll add this as a separate issue.
