### ISSUE TITLE
Using nuget reactiveui installs incompatible splat

### ISSUE THREAD

**Issue by bvwj** [reactiveui/ReactiveUI#918]
The first time I used nuget to import reactiveUI the project would not compile because splat methods were missing.

Running nuget again on splat fixed the problem.

It appears reactiveUI installed Splat 1.0.0.  Running nuget splat installed Splat 1.6.2

**Comment by gluck** [comment]
See #889, fixed but not released yet, minimum compatible Splat version is indeed 1.6.2
