### ISSUE TITLE
Generalize UserError

### ISSUE THREAD

**Issue by kentcb** [reactiveui/ReactiveUI#920]
The `UserError` class is more widely applicable than just handling errors. It could also be used to prompt the user for confirmations or warnings, or simply to give them an important piece of information. Whilst it's technically possible to use it for such scenarios, the name is off-putting.

Renaming `UserError` to `UserAlert` would result in an API more suggestive of its purpose. Other members (such as the `Throw` method) will need to be renamed too.

**Comment by kentcb** [comment]
@paulcbetts before I put any effort into a PR, is this a direction you'd be happy with?

**Comment by flagbug** [comment]
I think this is a good idea :+1: 

Currently I'm passing functions to my ViewModels for user confirmations like this: `public MyViewModel(Func<Task<bool>> confirmDeletion)` but that doesn't really feel right.

**Comment by ghuntley** [comment]
I agree, `UserError` poorly explains what is possible and just how powerful it is.
