### ISSUE TITLE
WPF Command Binding Cancellation 

### ISSUE THREAD

**Issue by BenjaminHolland** [reactiveui/ReactiveUI#922]
There doesn't seem to be any good way to cancel a task started by a ReactiveCommand bound to the UI in WPF, and there doesn't seem to be any documentation on how or if this is supposed to work.

**Comment by gluck** [comment]
Unless I'm missing something, the binding in WPF deals with the command triggering, not its action/cancelation.
You usually handle command cancelation in RxUI by (early) disposing the 'action' subscription, e.g. using `TakeUntil` as described [here](http://stackoverflow.com/a/23884090/615903) or [there](http://stackoverflow.com/a/31636333/615903).

**Comment by kentcb** [comment]
I will add an example of this to the new RxCommand documentation.

**Comment by kentcb** [comment]
Please see [the docs](https://docs.reactiveui.net/en/user-guide/commands/canceling.html).
