### ISSUE TITLE
ReactiveUI .net 4.5 without WPF

### ISSUE THREAD

**Issue by grokys** [reactiveui/ReactiveUI#925]
Hi, this is related to #734 but coming at it from a slightly different angle.

I'm currently working on https://github.com/grokys/Perspex/ which aims to be a cross-platform UI toolkit somewhat similar to WPF. I would like to be able to support ReactiveUI but its being tied to WPF poses problems with cross-platform usage, in that when run on mono ReactiveUI tries to load PresentationFramework which doesn't exist on that platform.

I realize that you probably wouldn't want to add support for such a fledgling project directly in ReactiveUI right now, but I was looking to at least find a way to work around the problem.

What would be the best thing to do? Is there a simple hack I can use to make ReactiveUI not try to load WPF on mono? Or should I create a perspex-specific fork of ReactiveUI for now?

I'd be interested to hear you thoughts.

**Comment by SuperJMN** [comment]
Waiting for this to be fixed. :+1:

**Comment by grokys** [comment]
I was wondering if a stub PresentationFramework.dll for mono might fix this at least in the short-term?

**Comment by ghuntley** [comment]
'spoke with @grokys today. Avalonia currently has had to maintain their own fork because of this issue, they would _love_ to not have their own fork.

**Comment by SuperJMN** [comment]
Hi guys! 

@ghuntley and I have been talking and he proposed the following:
"What if you just did a stub assembly. That way resolution works but stuff goes.boom if invoked.
If there's no wpf on the running then I don't see how it can go boom. this is using really silly assumptions right now btw.
It's more ramblings than a proposal. I don't know enough on wpf internals to give proper direction at this stage"

**Comment by grokys** [comment]
Yep, I mentioned this above in a comment:

> I was wondering if a stub PresentationFramework.dll for mono might fix this at least in the short-term?

However it wasn't as easy as I anticipated. I can't remember the details but I seem to remember the stub had to go pretty deep.

**Comment by petersondrew** [comment]
The issue I'm running up against is that referencing RxUI from our PCL libraries works fine, but our unit test libraries have to target NET45/Mono in order for things like Moq to be available. When we run our unit test libraries under mono, RxUI looks for PresentationFramework.dll which isn't available.

Any ideas on how to solve this? Could RxUI-Core be separated from the PresentationFoundation requirement?

**Comment by petersondrew** [comment]
To anyone else that comes across this issue, forcing my unit test project to reference the portable reactive dll instead of the net45 dll resolves the issue. This seems to be a somewhat well-known issue with nuget and mono net45 (in that nuget will choose net45 over the portable library).

**Comment by jkoritzinsky** [comment]
@ghuntley I thought of a way to fix this (at least for Avalonia) without breaking compatibility. ReactiveUI could have an assembly like `ReactiveUI.XamForms` and `ReactiveUI.WinForms` called `ReactiveUI.Avalonia` that has a `Registrations` class that will register our scheduler as the main scheduler (which is all our fork does).

Any chance ReactiveUI would accept a PR based on this idea?

**Comment by ghuntley** [comment]
I've been thinking of dropping references WPF from the `reactiveui` package and moving it to its own - similar.to what is done with WinForms. This would unbreak Avolonia, open up the possibility for gtk# and resolve running unit tests in Visual Studio for Mac. Alternatively I've thought about making a `netappcore` target instead and/or in addition.

**Comment by grokys** [comment]
@ghuntley - this would be a great idea IMO. I've tentatively tried a few times to prepare a PR to get ReactiveUI building for Avalonia, but the fact all the WPF stuff is mixed in with the main project makes this difficult.

**Comment by jkoritzinsky** [comment]
@ghuntley @grokys I've put out a PR to move the WPF references into their own package.

**Comment by ghuntley** [comment]
@jkoritzinsky thank-you very much! 👍 Have reviewed and merged your contribution!
