### ISSUE TITLE
Having issues with BindTo Extensions for iOS UITableViews

### ISSUE THREAD

**Issue by PureWeen** [reactiveui/ReactiveUI#941]
I'm trying to use the "ReactiveTableViewSourceExtensions"  to generate TableSections but I keep getting an exception from the "ComponentModelTypeConverter"

My end goal is to create multiple "TableSectionInformations" and use BindTo but I get this same error even if I just use BindTo on say a ReactiveList<>

The Exception is
""No constructor found for System.ComponentModel.ReferenceConverter::.ctor()""

```
      readonly MemoizingMRUCache<Tuple<Type, Type>, TypeConverter> typeConverterCache = new MemoizingMRUCache<Tuple<Type, Type>, TypeConverter>((types, _) =>
        {
            // NB: String is a Magical Type(tm) to TypeConverters. If we are
            // converting from string => int, we need the Int converter, not
            // the string converter :-/
            if (types.Item1 == typeof(string)) {
                types = Tuple.Create(types.Item2, types.Item1);
            }

            var converter = TypeDescriptor.GetConverter(types.Item1); //Exception happens right here
            return converter.CanConvertTo(types.Item2) ? converter : null;
        }, RxApp.SmallCacheLimit);
```

types.Item1 is 
{System.Collections.Generic.IReadOnlyList`1[ReactiveUI.TableSectionInformation`2[,]]}

I tried it with a really simple use case and same exception
```
Observable.Return(new ReactiveList<SomeVM>())
                .BindTo< SomeVM,SomeCell >(TableView, 64f);
```

For now I can get around it by just creating my own extension that has the same stuff in "BindTo" but then I just specify a custom dummy IBindingTypeConverter

```
var bind = sectionsObservable.BindTo(source, x => x.Data, vmToViewConverterOverride:new Thing());
```

**Comment by kentcb** [comment]
Try a build that has linking disabled. I'm 99% sure that's the problem here.

**Comment by PureWeen** [comment]
Ok so I'm guessing that's because the linker is removing a default constructor because it's not being used?

SO given that  is there a way to have it not remove it?  Or is this a bug I should report to Xamarin...

Reading the documentation they say
https://developer.xamarin.com/guides/ios/advanced_topics/linker/
" If your application only works with -nolink, please submit a bug report."

**Comment by PureWeen** [comment]
Alright so if I add
--linkskip=System

to my mtouch build options then it works when I have LINK SDK only on 

 I'm not sure if that it an acceptable scenario or not though and something that should be fixed :-)

**Comment by kentcb** [comment]
You're in the domain of Xamarin's linker now, which naturally has nothing to do with RxUI.

Skipping the whole assembly via `--linkskip` is one way, but my preferred means of configuring the linker is via an XML config file. See [here](https://developer.xamarin.com/guides/cross-platform/advanced/custom_linking/) for an example. For the System DLL, I typically have these entries:

```XML
<assembly fullname="System">
    <type fullname="System.ComponentModel.NullableConverter">
        <method name=".ctor"/>
    </type>
    <type fullname="System.ComponentModel.ReferenceConverter">
        <method name=".ctor"/>
    </type>
</assembly>
```

As you can see, I'm giving the linker the bare minimum of config. By virtue of including these constructors, it will include anything the constructors statically depend on.

**Comment by PureWeen** [comment]
AWESOME!!! I knew there was a more precise way out there :-) I was just in the wrong "Advanced Linker Topic" :-/  Worked great thank you..

I'll reach out to Xamarin see if it's something they think they need to modify with their linker or not

Thanks for the great info :-)
