### ISSUE TITLE
Drop legacy platforms in RxUI7

### ISSUE THREAD

**Issue by kentcb** [reactiveui/ReactiveUI#945]
Remove support for:

* WINRT 8
* iOS non-unified
* Mac non-unified
* WP8

**Comment by ghuntley** [comment]
Agree WINRT 8, iOS/Mac non-unified. WP8 maybe not.

**Comment by onovotny** [comment]
All for dropping legacy platforms. I would concur with WinRT8. VS 2015 can't even open it as it forces 8.1. At a bare min I'd keep Win81+Wpa81 as that's a single portable library to cover both of those.

How many people actually use the Mac version? Are there stats on that?

**Comment by flagbug** [comment]
I only use Win8.1 and @onovotny has a good point about Win8 with VS 2015

**Comment by moswald** [comment]
Incidentally, as of now, the Windows Phone 8.0 project in the `rxui7-master` branch still compiles cleanly. I would recommend leaving it in the solution unless new code breaks it.

**Comment by ghuntley** [comment]
:fire: WinRT80 :fire: : not bringing it across in #1006 . It won't even load in VS2015 and the build is going to be complicated enough as it is. Thus for RXUIv7 it's gotta go.

**Comment by flagbug** [comment]
Just dropping this in here: https://github.com/reactiveui/ReactiveUI/pull/956

**Comment by moswald** [comment]
This was taken care of with #1045.
