### ISSUE TITLE
Remove IReactiveCommand

### ISSUE THREAD

**Issue by kentcb** [reactiveui/ReactiveUI#954]
Remove the `IReactiveCommand` and `IReactiveCommand<T>` interfaces. They serve no useful purpose.

**Comment by gluck** [comment]
Not sure about the generic version, but `IReactiveCommand` can be useful, e.g. to group heterogenous commands in a collection, when all you care is `IsExecuting` (e.g. [this](http://stackoverflow.com/a/32588849/615903) SO answer) or `CanExecuteObservable`.

**Comment by kentcb** [comment]
Could you not just use `ReactiveCommand` instead? Basically, wherever people were using an interface, they would instead just use the class.

**Comment by gluck** [comment]
You mean the non-generic version ? has it been added back in 7.X ? coz in 6.X there's only the generic version, and you can't have say `ReactiveCommand<bool>` and `ReactiveCommand<int>` in same collection w/o a base class/interface with the non-generic methods/properties in it.

**Comment by kentcb** [comment]
Ugh, you're right - it's been shifted under a legacy namespace and only the static `ReactiveCommand` remains. I assumed there was a non-static `ReactiveCommand` because I'm somewhat out of the loop with the discussions around this matter and from what I've seen it sounded to me like a simple job of removing interfaces. 

Note that #850 lists this as one of the things to do prior to shipping Rx7. I'll raise this matter in Slack. I don't mind re-instating or re-writing `ReactiveCommand` as appropriate. It'll just take longer than I envisaged.

**Comment by ghuntley** [comment]
https://reactiveui.readthedocs.org/en/latest/commands/ireactivecommand/

**Comment by kentcb** [comment]
See #971.
