### ISSUE TITLE
reactiveui-xamforms for universal project PCL (Profile259)

### ISSUE THREAD

**Issue by rajanranjit** [reactiveui/ReactiveUI#959]
Any update on this? my PCL is targeted to the following frameworks.let me know if anything needs to be changed on this. 

.NET Framework 4.5
Windows 8
Windows Phone Silverlight 8
ASP.NET Core 5.0
Windows Phone 8.1
Xamarin.Android
Xamarin.iOS
Xamarin.iOS (Classic)

Is reactiveui-xamforms available for windows universal project PCL(Profile259)? I am getting the following error when I tried to install the nuget package.

Could not install package 'reactiveui-xamforms 6.5.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
Thanks,
RJ

**Comment by ghuntley** [comment]
Can't fix this currently due to #993

**Comment by YogirajA** [comment]
Is there any update on this?

**Comment by moswald** [comment]
@YogirajA if you can update to RxUI v7 beta, it should work with `Profile259`.

nuget v3 = https://www.myget.org/F/reactiveui/api/v3/index.json
nuget v2 = https://www.myget.org/F/reactiveui/api/v2

**Comment by YogirajA** [comment]
@moswald still having the same issue 

> Could not install package 'reactiveui-xamforms 7.0.0.1464236131'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or 
content files that are compatible with that framework. For more information, contact the package author.

**Comment by jbogard** [comment]
It's also not working for Profile111.

**Comment by jbogard** [comment]
For 259, the folder name that this is dropped in should be:

```
portable-net45+netcore45+win8+wpa81+wp8+MonoAndroid403+MonoTouch10+Xamarin.iOS10
```

**Comment by onovotny** [comment]
note that you dn't need mono/Xamarin for 259, those are inferred.

`portable-net45+win8+wpa81+wp8` should be all that's required.

**Comment by jbogard** [comment]
For reference, the current folder created in the package is:

```
portable-net45+netcore45+wp8+UAP10+MonoAndroid403+MonoTouch10+Xamarin.iOS10
```

Which AFAIK doesn't refer to any profile.

And yep, confirmed that @onovotny 's suggestion works just fine.

**Comment by jbogard** [comment]
@onovotny is this accurate as far as the profile names? We have 111 and 259 apps, though shouldn't really need 259 for us these days. I mean, WP silverlight? yeesh.

**Comment by onovotny** [comment]
Is what accurate, missing some context?

**Comment by jbogard** [comment]
As far as using "netcore45" instead of "win" in `portable-net45+netcore45+wpa81+wp8`.

**Comment by onovotny** [comment]
oh, those are effectively the same for win8/pcl259. Everything seems to be using `win8`

The bigger thing to consider is the use of `netstandard` and what the best profiles for that would be.
