### ISSUE TITLE
ReactiveDerivedList is strongly bound to original list.

### ISSUE THREAD

**Issue by cfneese** [reactiveui/ReactiveUI#960]
Currently the lifetime of a ReactiveDerivedList is tied to the list it is following until the derived list is disposed.  This is because the derived list subscribes to the source list in several places giving the source list several strong references back to the derived list.  If these subscriptions were made with weak references, then the derived list could be garbage collected when no longer needed.  As a matter of fact, the derived lists wouldn't even need to be disposables at all.

It isn't such a big deal that derived lists are disposables, but on the other hand, ReactiveLists are not.  

I just created a small project called called [weakrx](https://github.com/cfneese/weakrx) that provides extension methods for subscribing to observables without creating strong references back to the subscriber.  I think that replacing the calls to Subscribe in reactive derived list to calls to WeakSubscribe would substantially improve RxUI's derived lists.  Does anyone think this is a good idea?

**Comment by bradphelan** [comment]
It might be a good idea to drop our ReactiveDerived list and instead use

https://github.com/RolandPheasant/DynamicData

It is much more powerful than ReactiveList. It's underlying changeset model supports a rich combinator library.

**Comment by glennawatson** [comment]
We have dropped ReactiveList and ReactiveDerivedList in the next version of ReactiveUI and latest. Closing.
