### ISSUE TITLE
ReactiveCommand exceptions & View deactivation

### ISSUE THREAD

**Issue by flagbug** [reactiveui/ReactiveUI#963]
Let's take the following piece of code:

``` cs
public class MyViewModel : ReactiveObject
{
    public ReactiveCommand<Unit> TheCommand { get; }

    public MyViewModel()
    {
        TheCommand = ReactiveCommand.CreateAsyncTask(_ => IWillThrowSoon());

        TheCommand.ThrownExceptions
           .SelectMany(ex => UserError.Throw("Message", ex))
           .Subscribe();
    }

    private async Task IWillThrowSoon()
    {
        await Task.Delay(5000);

        throw new Exception("Explosion!");
    }
}
```

In my view I'm registering the `UserError` to catch the exception that the command throws, so I can display the message to the user.

The problem: When my view deactivates, I unregister the `UserError`. If that happens before the command finishes, the ReactiveUI/Rx reroutes the `UserError` exception, because it has no subscribers and the app explodes.

My current solution looks something like this:

``` cs
public class MyViewModel : ReactiveObject, ISupportsActivation
{
    public ReactiveCommand<Unit> TheCommand { get; }

    public ViewModelActivator Activator { get; }

    public MyViewModel()
    {
        this.Activator = new ViewModelActivator();

        var deactivationSignal = new Subject<Unit>();

        this.WhenActivated(d =>
        {
            d(Disposable.Create(() =>
            {
                deactivationSignal.OnNext(Unit.Default);
            }));
        });

        TheCommand = ReactiveCommand.CreateAsyncTask(_ => IWillThrowSoon().ToObservable()
            .TakeUntil(deactivationSignal).DefaultIfEmpty(Unit.Default)));

        TheCommand.ThrownExceptions
           .SelectMany(ex => UserError.Throw("Message", ex))
           .Subscribe();
    }

    private async Task IWillThrowSoon()
    {
        await Task.Delay(5000);

        throw new Exception("Explosion!");
    }
}
```

But this doesn't feel pretty.

/cc @shiftkey With whom I discussed this today

**Comment by mteper** [comment]
Fwiw, in our app we solve this by having the user error subscription in the main view model that hangs around for the lifetime of the app.

**Comment by kentcb** [comment]
Hmmm. It seems to me that RxUI is working as expected here and perhaps you'll need to design around it. You could either take @mteper's suggestion and register the handler at a higher level, or ensure your view cannot be navigated away from until command execution completes.

**Comment by flagbug** [comment]
In this specific case I actually really don't care about the exception anymore, if the user has navigated away from the view.

What I could do, is write

```cs
TheCommand.ThrownExceptions
           .SelectMany(ex => UserError.Throw("Message", ex))
           .Catch<Unit, UnhandledUserErrorException>(_ => Observable.Empty<Unit>())
           .Subscribe();
```

but that feels a bit unclean to me.

**Comment by mteper** [comment]
Can this be closed now? Sounds like discussion has run its course.

 //cc @flagbug @kentcb @ghuntley

**Comment by kentcb** [comment]
Fine with me. Wotcha, @flagbug ?

**Comment by flagbug** [comment]
Hm, It'd still be great to have something like this.Activator.Deactivated, that I can pass into the `TakeUntil` method.

@kentcb You mentioned in the Slack channel, that you remembered to have seen something like this, and I do too! I wonder where that property has gone

**Comment by kentcb** [comment]
Returning to this after a long hiatus. There's definitely an `Activated` and `Deactivated` property on `ViewModelActivator`. I'm guessing it was added around or not long after this issue was brought up.
