### ISSUE TITLE
ReactiveUI.XamForms.RoutedViewHost navigates twice on startup for iOS

### ISSUE THREAD

**Issue by PureWeen** [reactiveui/ReactiveUI#972]
you can see this behavior by just running the "Playground-XamForms.iOS" project..
You'll see once it runs you can navigate back to the same view... This doesn't happen on android

This observable inside of " this.WhenActivated(new Action<Action<IDisposable>>(d => {" 
Runs after the app has loaded and pushes another version of the starting view onto the navigation stack

Not really sure why this Observable fires on iOS on startup but not on Android

```
 d(this.WhenAnyObservable(x => x.Router.Navigate)
                    .SelectMany(_ => pageForViewModel(Router.GetCurrentViewModel()))
                    .SelectMany(x => this.PushAsync(x).ToObservable())
                    .Subscribe())
```

**Comment by ericsink** [comment]
FWIW, in experimenting this week with Xamarin.Forms (2.0) and ReactiveUI (6.5), I have observed this problem as well.

**Comment by cabauman** [comment]
Just tested on my device. Doesn't seem to be a problem anymore so I'll go ahead and close this issue Xamarin.Forms (3.4) and ReactiveUI (9.8)
