### ISSUE TITLE
Exception swallowed in command if during executeAsync

### ISSUE THREAD

**Issue by csmager** [reactiveui/ReactiveUI#973]
Consider this code:
```csharp
var command = ReactiveCommand.CreateAsyncObservable(_ => ThrowImmediately());
// ...
private IObservable<Unit> ThrowImmediately()
{
    throw new InvalidOperationException();
}
```
`ReactiveCommand.ExecuteAsync` creates an observable using:
```csharp
var ret = Observable.Create<T>(subj => {
    if (Interlocked.Increment(ref inflightCount) == 1) {
        isExecuting.OnNext(true);
    }
    // ...
    var disp = executeAsync(parameter)
        .ObserveOn(scheduler)... // ...
```
The framework calls `command.Execute`. The code for this is currently:
```csharp
ExecuteAsync(parameter).Catch(Observable.Empty<T>()).Subscribe();
```
So it seems this happens:
- the framework calls `ReactiveCommand.Execute`
- `ReactiveCommand.ExecuteAsync` sets `IsExecuting = true`, disabling the command.  It returns an observable containing the exception.
- The exception is swallowed by the catch, and as the disposable that would set `IsExecuting = false` is never returned the command is stuck as disabled in the UI.

It seems this may relate to the changes in #686.  Is this a bug?  What is the expected behaviour?

**Comment by flagbug** [comment]
The expected behavior for `ReactiveCommand.Execute(object)` is, that it swallows all exceptions but surfaces them through `ReactiveCommand.ThrownExceptions`

**Comment by csmager** [comment]
I believe that to be the case - in this case, however, this doesn't happen. It's just lost.

**Comment by flagbug** [comment]
That's probably because your method should be

```
private IObservable<Unit> ThrowImmediately()
{
     return Observable.Throw(new InvalidOperationException());
}
```

Although I'm not sure what we should do about synchronous exceptions - thoughts @paulcbetts ?

**Comment by csmager** [comment]
The example I gave isn't real (obviously!). I was actually trying to sort out logging in my application and was testing various scenarios, and came across this oddity.  I can't catch it, I can't log it, and it breaks the internal state.  I'm not sure you can guarantee that creating the observable won't throw, either.

One suggestion is to just stick the exception into `ThrownExceptions` and carry on.  This is (probably naively) what I'd expect.  Something like replacing the call to `executeAsync(parameter)` with a call to `executeAsyncSafe(parameter)` should do it:
```
private IObservable<T> executeAsyncSafe(object parameter)
{
    IObservable<T> ret;

    try {
        ret = executeAsync(parameter);                
    }
    catch (Exception ex) {
        ret = Observable.Throw<T>(ex);
    }

    return ret;
}
```

**Comment by gluck** [comment]
Somebody wondered the same thing on [stackoverflow](http://stackoverflow.com/questions/32987488/how-to-catch-exception-from-reactivecommand/33037662#33037662).

I'd recommend going for the PR and forward the exception the the thrown ones, as silently dropping exceptions is a pretty bad practice by my standards.
