### ISSUE TITLE
Allow identity bindings

### ISSUE THREAD

**Issue by kentcb** [reactiveui/ReactiveUI#975]
Bindings of this form do not appear to work:

``` C#
this.Bind(this.ViewModel, x => x, x => x.foo.bar);
```

That is, the `x => x` appears to cause the binding to fail.

Investigate whether we can enable this scenario.

**Comment by martingemme** [comment]
It reminds me of what I'm currently using:

```c#
var subscriptionForViewModel = this.WhenAnyValue(x => x.ViewModel)
   .Where(x => x != null);
// with
subscriptionForViewModel
   .Subscribe(x => Grade.DataContext = x);
// or
subscriptionForViewModel.BindTo(this, x => x.DataContext);
```

What is the suggested approach? I tried once to use that approach for using Xaml Binding instead of numerous this.Bind() and didn't work for me either. The only approach that works are either of the two mentionned above.
