### ISSUE TITLE
Bindings with property chains not updating target when chain is broken

### ISSUE THREAD

**Issue by kentcb** [reactiveui/ReactiveUI#976]
The following test fails:

```C#
private class ViewModel : ReactiveObject
{
    private ChildViewModel child;

    public ChildViewModel Child
    {
        get { return this.child; }
        set { this.RaiseAndSetIfChanged(ref this.child, value); }
    }
}

private class ChildViewModel : ReactiveObject
{
    private string value;

    public string Value
    {
        get { return this.value; }
        set { this.RaiseAndSetIfChanged(ref this.value, value); }
    }
}

private class View : ReactiveObject, IViewFor<ViewModel>
{
    private ViewModel vm;
    private string value;

    public string Value
    {
        get { return this.value; }
        set { this.RaiseAndSetIfChanged(ref this.value, value); }
    }

    public ViewModel ViewModel
    {
        get { return this.vm; }
        set { this.RaiseAndSetIfChanged(ref this.vm, value); }
    }

    object IViewFor.ViewModel
    {
        get { return this.ViewModel; }
        set { this.ViewModel = (ViewModel)value; }
    }
}

[Fact]
public void aaa_repro()
{
    var scheduler = new TestScheduler();
    var viewModel = new ViewModel
    {
        Child = new ChildViewModel
        {
            Value = "test"
        }
    };
    var destination = new View
    {
        ViewModel = viewModel
    };

    destination.OneWayBind(viewModel, x => x.Child.Value, x => x.Value);

    Assert.Equal("test", destination.Value);

    viewModel.Child.Value = "new value";
    Assert.Equal("new value", destination.Value);

    viewModel.Child = new ChildViewModel
    {
        Value = "another new value"
    };
    Assert.Equal("another new value", destination.Value);

    // fails
    //viewModel.Child = null;
    //Assert.Null(destination.Value);

    // also fails
    destination.ViewModel = new ViewModel();
    Assert.Null(destination.Value);
}
```

Basically, when a binding includes a chain of properties, the target is not updated as expected when references within the chain are broken (i.e. nulled).

**Comment by gluck** [comment]
I think the first failure was already reported and explained "as designed" here no ? #314

As for the second one, seems pretty expected to me as well, given that you aren't really binding to the view ViewModel property in any way, although you probably could (disclaimer: haven't tried yet).

**Comment by kentcb** [comment]
Ugh, this really goes against my mental model of how bindings work. Hell, I opened #314 and had forgotten about it, perhaps showing that this just doesn't feel like the "right" behavior. Maybe my expectations are moulded by experience in other binding frameworks, such as WPF's.

To me, you have a property chain and every attempt is made to resolve it. If any change occurs along the chain, it's re-evaluated. If a value in the chain is missing, `null` is the result (or `default(T)`). I get what @paulcbetts is saying in #314 but I actually disagree that this should always work:

```C#
this.WhenAnyValue(x => x.Address.Line1)
    .Where(x => x == null)
    .Subscribe(_ => Address.Line1 = "(No Address)");
```

To me, it should be:

```C#
this.WhenAnyValue(x => x.Address.Line1)
    .Where(x => x == null)
    // I have no expectation that Address is non-null on this line
    .Subscribe(_ => Address?.Line1 = "(No Address)");
```

Breaking people's expectations for bindings to support Paul's example scenario seems like an incredibly bad idea to me. It's not a pit of success one wants from a framework - quite the opposite in fact.

You're right about the second scenario, but that's because I stuffed up my test. I was actually trying to simulate what happens when a VM changes in a cell, for example. In such a case, one would expect bindings to be re-evaluated because of a `WhenActivated` call - and they are, but they're subject to the same weird behavior above. That is, if the property chain in the new object hierarchy has a break in it, then the old value remains despite it being from a completely different VM!

I simply can't close this without more input from @paulcbetts. Is there something - anything - we can do here to make this work in a more sensible fashion whilst keeping everyone happy?

**Comment by kentcb** [comment]
Another thought: is the problem here that perhaps bindings should _not_ work in the same fashion as `WhenAny*`? Should a binding to `Foo.Bar.Baz` work conceptually like this:

```C#
this.WhenAnyValue(x => x.Foo, x => x.Foo.Bar, x => x.Foo.Bar.Baz, (_, _, _) => x.Foo?.Bar?.Baz)
```

**Comment by kentcb** [comment]
Yet another thought: bindings did at one point have the concept of fallback values, perhaps for exactly the reasons discussed here. However, they too were faulty and removed as part of #848. Perhaps they should actually be reinstated in such a way to make bindings work in the expected fashion...?
