### ISSUE TITLE
Is BundleSuspensionDriver missing the line of code that stores the state?

### ISSUE THREAD

**Issue by PureWeen** [reactiveui/ReactiveUI#984]
I'm probably just missing something obvious but

```
  public IObservable<Unit> SaveState(object state)
        {
            try {
                var serializer = new BinaryFormatter();
                var st = new MemoryStream();

                AutoSuspendHelper.LatestBundle.PutByteArray("__state", st.ToArray());
                return Observable.Return(Unit.Default);
            
            } catch(Exception ex) {
                return Observable.Throw<Unit>(ex);
            }
        }
```

Seems to be missing the line of code that serializes the state to the memory stream..

i.e.
```
serializer.Serialize(st, state);
```

My android state never seems to save and when I added the serialization in then it seemed to stick....

**Comment by paulcbetts** [comment]
lol, A+ coding @paulcbetts from 2014

**Comment by PureWeen** [comment]
HA ok :-)  I thought maybe there was some voodoo magic I was missing somewhere...

Also thoughts on using a DataContractSerializer instead of BinaryFormatter?  BinaryFormatter doesn't seem to play very nicely with PCL libraries cause of the non-existent [SerializableAttrribute]

i.e.
```
Tried to persist app state: System.Runtime.Serialization.SerializationException: Type 'ReactiveUI.ReactiveObject' in Assembly 'ReactiveUI, Version=6.4.0.1, Culture=neutral, PublicKeyToken=null' is not marked as serializable.
```

**Comment by paulcbetts** [comment]
Sure - really though, this class is like the "I didn't set anything up" fallback class, Akavache.Mobile is the one that you should use for production

**Comment by PureWeen** [comment]
AW ok good to know...

created a pull request for adding that line in...   Abandoned the  DataContractSerializer idea...  Didn't really think through that suggestion all the way

**Comment by ghuntley** [comment]
Thanks for the contribution @PureWeen
