### ISSUE TITLE
ItemChanging observable appears to fire *after* property is set

### ISSUE THREAD

**Issue by gingermike** [reactiveui/ReactiveUI#987]
Hi,

I have a little project that I'm working on that has a feature to monitor the delta of changes in an underlying model. Specifically, I need the value before the item changed and after. The objects I'm monitoring are in a ReactiveList with ChangeTrackingEnabled set to true, though when I subscribe to the ItemChanging observable, I only seem to receive events *after* the model's property has changed. 

Am I doing something incredibly stupid here? 

```C#
    private ReactiveList<Model> _list = new ReactiveList<Model> {ChangeTrackingEnabled = true}; 

        public MainWindowViewModel()
        {
            _list.Add(new Model {Test = "abcd123"});
            _list.ItemChanging.Subscribe(x => Debug.WriteLine("Value before: " + x.Sender.Test));
            _list.ItemChanged.Subscribe(x => Debug.WriteLine("Value after: " + x.Sender.Test));

            ChangeModel = ReactiveCommand.Create();
            ChangeModel.Subscribe(_ => _list[0].Test = "blahblah");
        }

        private ReactiveCommand<object> _changeModel;
        public ReactiveCommand<object> ChangeModel
        {
            get { return _changeModel; }
            set { this.RaiseAndSetIfChanged(ref _changeModel, value); }
        }
    }
````

The output I get in the console:

```
Value before: blahblah
Value after: blahblah
````

**Comment by flagbug** [comment]
What does your model look like?

**Comment by gingermike** [comment]
```c#
    public class Model : ReactiveObject
    {

        private string _test;

        public string Test
        {
            get { return _test; }
            set { this.RaiseAndSetIfChanged(ref _test, value); }
        }
    }
```

**Comment by kentcb** [comment]
This is due to `ItemChanging` and `ItemChanged` events being delivered via a scheduler. By default that scheduler is `RxApp.MainThreadScheduler`. Therefore, by the time you receive the event, the actual property has already changed.

You can pass `ImmediateScheduler.Instance` to your `ReactiveList` to receive events immediately.
