### ISSUE TITLE
[Documentation][Bug] Code snippet won't compile: Docs -> Errors -> The Handler Chain

### ISSUE THREAD

**Issue by dsaf** [reactiveui/ReactiveUI#988]
This code snippet does not compile:

http://reactiveui.readthedocs.org/en/stable/basics/errors/   -   'The Handler Chain'

``` csharp
var disconnectHandler = UserError.RegisterHandler(async error => {
    // We don't know what thread a UserError can be thrown from, we usually 
    // need to move things to the Main thread.
    await RxApp.MainThreadScheduler.ScheduleAsync(() => {
        // NOTE: This code is Incorrect, as it throws away 
        // Recovery Options and just returns Cancel. This is Bad™.
        return MesssageBox.Show(error.ErrorMessage);
    });

    return RecoveryOptionResult.CancelOperation;
});
```

Reasons:

1) outdated API;
2) spelling error: 'MesssageBox'.

**Comment by shiftkey** [comment]
If you're feeling up to the challenge, this is the source for that page:

https://github.com/reactiveui/ReactiveUI/blob/master/docs/basics/errors.md#the-handler-chain

**Comment by dsaf** [comment]
@shiftkey I am too new to Rx and ```async``` to be confident about creating a code snippet for official documentation. This is the best I could do:

```csharp
RxApp.MainThreadScheduler.Schedule(() => MessageBox.Show(message));
```

**Comment by jonstodle** [comment]
@ghuntley This issue could probably be closed as `UserError` is deprecated (and removed?) and the documentation doesn't mention it anymore.

**Comment by ghuntley** [comment]
Yup. Thanks you help with triaging.
