### ISSUE TITLE
Nuget release with new features

### ISSUE THREAD

**Issue by jorisvergeer** [reactiveui/ReactiveUI#990]
Hi,

Would you like to release a new version of ReactiveUI.AndroidSupport to nuget? The last update was in May and this commit https://github.com/reactiveui/ReactiveUI/commit/bc5ad889af5b1837a7981d818e4f9638d1ccaf95 from after may contains a very usefull new feature.

Kind regards,

**Comment by ghuntley** [comment]
Historically the project did not do pre-releases, Xamarin will be soon making their CI environments available to open-source packages. When this happens I'd love to start doing -pre releases.

See issue #993
