### ISSUE TITLE
Propagate CS0618 (obsolete) for API's within ReactiveUI-Events that are obsolete.

### ISSUE THREAD

**Issue by kentcb** [reactiveui/ReactiveUI#992]
This warning is for missing XML documentation, so leaving it enabled results in a plethora of warnings.

**Comment by kentcb** [comment]
Same goes for CS0618 (obsolete), and possibly more.

**Comment by shiftkey** [comment]
Documentation is nice.
xml-doc documentation is not something I miss.
Unnecessary warnings are just annoying.

:thumbsup: on :fire:

Not sure how I feel about CS0618 being disabled - is now a good time to review and clean those up? Do you have some examples which shouldn't be?

**Comment by kentcb** [comment]
@shiftkey note that I'm only talking about events projects here, which is entirely generated code. Moreover, it is somewhat obliged to use obsolete APIs because it's simply wrapping all APIs and surfacing an observable variant of the underlying API.

**Comment by shiftkey** [comment]
> Moreover, it is somewhat obliged to use obsolete APIs because it's simply wrapping all APIs and surfacing an observable variant of the underlying API.

So our generated APIs should then propagate the `[Obsolete]`, right? Or does that just seem not worth the investment?

**Comment by kentcb** [comment]
I would agree with that (if it's not already doing so - I haven't checked). But I would also consider that a separate issue :)

**Comment by ghuntley** [comment]
* suppress CS1591 =  :+1:  - let's leave it open for a newbie #1005 
* propagate CS0618 (obsolete) = :+1: - that might be too much for a newbie?

**Comment by glennawatson** [comment]
This was fixed in pharmacist.
