### ISSUE TITLE
Build borked on Xam4?

### ISSUE THREAD

**Issue by kentcb** [reactiveui/ReactiveUI#993]
Seems like the build might be broken with Xam4. Events, in particular, seem to fail to build.

**Comment by ghuntley** [comment]
Can't wait until Xamarin releases their CI (~ 2 weeks). 

When they do:

* Start producing  -pre nuget packages off master.
* Enable RED/GREEN merge workflow on PRs.

**Comment by jbogard** [comment]
This still borked? Looks like the last package with ReactiveUI.Events_XamForms not empty is 6.2.1.1

**Comment by ghuntley** [comment]
@jbogard we have CI up and running for v7 (including reactiveui-events for xamarin.forms). Have sent you a message on slack with the details.

**Comment by jbogard** [comment]
Uh oh. Which slack team room?

**Comment by ghuntley** [comment]
@jbogard https://reactivex.slack.com :-)

**Comment by glennawatson** [comment]
Fixed a while back.
