### ISSUE TITLE
vmToViewConverterOverride ignored.

### ISSUE THREAD

**Issue by ofirgeller** [reactiveui/ReactiveUI#995]
Im calling the OneWayBind method and passing in the vmToViewConvertorOverride  as a named argument.

    this.OneWayBind(ViewModel, vm => vm.PreAnswerVisability, v => v.UserAnswer.Visibility,vmToViewConverterOverride: new MyConvertor());

But the converter is never called, the "default" converter for the types in question is called instead.I looked at the code in ProprotyBindings.cs and it seems like it should work, using the ?? operator to only get the converter the system knows about if the override is null. So I don't know why this is happening.

Registering MyConvertor and passing it as a hint also made no difference.

I also did not find any unit tests that are passing in that parameter.

**Comment by kentcb** [comment]
Please provide a full repro. The following test (which I will tweak and then commit to cover conversion) succeeds:

```cs
        private class Converter : IBindingTypeConverter
        {
            public int GetAffinityForObjects(Type fromType, Type toType)
            {
                return 100;
            }

            public bool TryConvert(object from, Type toType, object conversionHint, out object result)
            {
                result = "converted";
                return true;
            }
        }

        [Fact]
        public void OneWayBindWithConverter()
        {
            var vm = new PropertyBindViewModel();
            var view = new PropertyBindView { ViewModel = vm };

            view.OneWayBind(view.ViewModel, x => x.Property1, x => x.SomeTextBox.Text, vmToViewConverterOverride: new Converter());

            Assert.Equal("converted", view.SomeTextBox.Text);
        }
```

**Comment by kentcb** [comment]
Closing. Please feel free to open again if you can provide a repro or more information with which we can repro.
