### ISSUE TITLE
Duplicate entries in list when using IReactiveDerivedList

### ISSUE THREAD

**Issue by modplug** [reactiveui/ReactiveUI#996]
When clearing and adding from a ReactiveDerivedList that has a IReactiveDerivedList I get duplicate entries. 

I've created a small repro case in wpf.

https://github.com/modplug/ReactiveDuplicateRepro/tree/Reprocase

**Comment by oysteinkrog** [comment]
Worth mentioning is that this only happens when using a scheduler in the derived list.

**Comment by dsaf** [comment]
This is a severe bug and I am facing it as well.

**Comment by oysteinkrog** [comment]
We've "solved" this by switching to DynamicData. It is much better in every way.

**Comment by dsaf** [comment]
@oysteinkrog This is the route I am currently exploring as well. Do you still use ReactiveUI for anything at all?

**Comment by oysteinkrog** [comment]
Yes we use ReactiveUI for most other things. I've heard there is talk of removing ReactiveList and just using DynamicData...

**Comment by dsaf** [comment]
Makes sense, thank you.
