### ISSUE TITLE
reactiveui-events-winforms nuget package - is this part of the ReactiveUI framework?

### ISSUE THREAD

**Issue by AidanCondon** [reactiveui/ReactiveUI#997]
I would like to know if this is one of the packages that is published by the core team (it does not look like it is looking at the owners, but I wanted to double-check).

If this package is not "official" ReactiveUI, any idea on how to achieve the same thing **using Windows Forms** with ReactiveUI-supported packages?

**Comment by gluck** [comment]
Indeed I published it (and not @paulcbetts), from a fork of ReactiveUI repo there: https://github.com/gluck/ReactiveUI/commits/Net40-support

Note that _reactiveui-*-events_ packages (neither the ones from Paul, nor mine) have no adherence to ReactiveUI per-se, you can do RxUI without them, and you can use them without RxUI. They're simply "generated extension methods for every type exposing .Net events to expose corresponding `IObservable` wrappers", to save you the burden of writing the `FromEvent`/`FromEventPattern` yourself.

This winforms package contains helpers for every type in `System.Windows.Forms.dll`.

**Comment by AidanCondon** [comment]
Thanks @gluck. Very helpful. I will go with the `FromEventPattern` for now.

**Comment by ghuntley** [comment]
See also https://github.com/reactiveui/ReactiveUI/issues/758
