### ISSUE TITLE
Is Windows Forms still a first-class citizen in the ReactiveUI framework?

### ISSUE THREAD

**Issue by AidanCondon** [reactiveui/ReactiveUI#998]
I unfortunately cannot use WPF because of "reasons" and have to stick with Windows Forms, but would like to benefit from a framework like ReactiveUI.

I cannot find any good examples of usage with Windows Forms and commits in the main repository are all about mobile stuff, so I'm not sure ReactiveUI is the right tool for me - I'm wishing it is.

Any advice?

**Comment by paulcbetts** [comment]
Yes it is

**Comment by ghuntley** [comment]
Hey @AidanCondon Windows.Forms is still first-class. You're not going to see much activity on the Windows.Forms front as it's pretty rare to see greenfield Windows.Forms in my experience. However we would love to take in anything you can contribute, documentation or sample apps.

**Comment by AidanCondon** [comment]
Thank you @paulcbetts and @ghuntley. I don't really know how to use ReactiveUI with Windows Forms just yet to contribute samples... I was actually trying to find some good ones for reference so I can decide to use RXUI or not with my project.

**Comment by gardnerbp** [comment]
For a recent example of ReactiveUI with WinForms please see http://www.codeproject.com/Articles/801986/Using-ReactiveUI-for-WinForms-MVVM-Design

**Comment by ghuntley** [comment]
Thanks @gardnerbp !
